---
permalink: audit/audit-message-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, message formats, message format 
summary: StorageGRIDシステム内で交換される監査メッセージには、すべてのメッセージに共通する標準情報と、報告されるイベントまたはアクティビティを説明する特定のコンテンツが含まれます。 
---
= 監査メッセージの形式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDシステム内で交換される監査メッセージには、すべてのメッセージに共通する標準情報と、報告されるイベントまたはアクティビティを説明する特定のコンテンツが含まれます。

提供された概要情報がlink:using-audit-explain-tool.html["監査説明"]そしてlink:using-audit-sum-tool.html["監査合計"]ツールだけでは不十分な場合は、このセクションを参照して、すべての監査メッセージの一般的な形式を理解してください。

以下は、監査ログ ファイルに表示される監査メッセージの例です。

[listing]
----
2014-07-17T03:50:47.484627
[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][ATYP(FC32):SYSU][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
各監査メッセージには、属性要素の文字列が含まれています。文字列全体が括弧で囲まれている(`[ ]`) であり、文字列内の各属性要素には次の特性があります。

* 括弧内 `[ ]`
* 文字列によって導入 `AUDT`監査メッセージを示す
* 前後に区切り文字（カンマやスペースなし）なし
* 改行文字で終了する `\n`


各要素には、属性コード、データ型、および次の形式で報告される値が含まれます。

[listing]
----
[ATTR(type):value][ATTR(type):value]...
[ATTR(type):value]\n
----
メッセージ内の属性要素の数は、メッセージのイベント タイプによって異なります。属性要素は特定の順序でリストされていません。

次のリストは、属性要素について説明しています。

* `ATTR`報告される属性の 4 文字のコードです。すべての監査メッセージに共通する属性と、イベント固有の属性があります。
* `type`UI64、FC32 など、値のプログラミング データ型の 4 文字の識別子です。型は括弧で囲まれます `( )`。
* `value`属性の内容であり、通常は数値またはテキスト値です。値は常にコロンの後に続きます(`:`）。データ型 CSTR の値は二重引用符 " " で囲まれます。

