---
permalink: audit/cbrb-object-receive-begin.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, CBRB, Object Receive Begin 
summary: 通常のシステム操作中は、データがアクセスされ、複製され、保持されるにつれて、コンテンツ ブロックは異なるノード間で継続的に転送されます。あるノードから別のノードへのコンテンツ ブロックの転送が開始されると、このメッセージは宛先エンティティによって発行されます。 
---
= CBRB: オブジェクト受信開始
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通常のシステム操作中は、データがアクセスされ、複製され、保持されるにつれて、コンテンツ ブロックは異なるノード間で継続的に転送されます。あるノードから別のノードへのコンテンツ ブロックの転送が開始されると、このメッセージは宛先エンティティによって発行されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CNID
 a| 
接続識別子
 a| 
ノード間セッション/接続の一意の識別子。



 a| 
CBID
 a| 
コンテンツブロック識別子
 a| 
転送されるコンテンツ ブロックの一意の識別子。



 a| 
CTDR
 a| 
転送方向
 a| 
CBID 転送がプッシュ開始かプル開始かを示します。

PUSH: 送信エンティティによって転送操作が要求されました。

PULL: 転送操作は受信側エンティティによって要求されました。



 a| 
CTSR
 a| 
ソースエンティティ
 a| 
CBID 転送のソース (送信者) のノード ID。



 a| 
CTDS
 a| 
宛先エンティティ
 a| 
CBID 転送の宛先 (受信側) のノード ID。



 a| 
CTSS
 a| 
開始シーケンス数
 a| 
要求された最初のシーケンス数を示します。成功した場合、転送はこのシーケンス カウントから開始されます。



 a| 
CTES
 a| 
予想される終了シーケンス数
 a| 
要求された最後のシーケンス数を示します。成功した場合、このシーケンス カウントが受信された時点で転送が完了したとみなされます。



 a| 
RSLT
 a| 
転送開始ステータス
 a| 
転送開始時のステータス:

SUCS: 転送が正常に開始されました。

|===
この監査メッセージは、コンテンツ ブロック識別子によって識別される単一のコンテンツに対してノード間データ転送操作が開始されたことを意味します。この操作では、「開始シーケンス カウント」から「予想される終了シーケンス カウント」までのデータが要求されます。送信ノードと受信ノードはノード ID によって識別されます。この情報は、システム データ フローを追跡するために使用でき、ストレージ監査メッセージと組み合わせてレプリカ数を確認するために使用できます。
