---
permalink: audit/cbre-object-receive-end.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, CBRE, Object Receive End 
summary: あるノードから別のノードへのコンテンツ ブロックの転送が完了すると、宛先エンティティによってこのメッセージが発行されます。 
---
= CBRE: オブジェクト受信終了
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
あるノードから別のノードへのコンテンツ ブロックの転送が完了すると、宛先エンティティによってこのメッセージが発行されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CNID
 a| 
接続識別子
 a| 
ノード間セッション/接続の一意の識別子。



 a| 
CBID
 a| 
コンテンツブロック識別子
 a| 
転送されるコンテンツ ブロックの一意の識別子。



 a| 
CTDR
 a| 
転送方向
 a| 
CBID 転送がプッシュ開始かプル開始かを示します。

PUSH: 送信エンティティによって転送操作が要求されました。

PULL: 転送操作は受信側エンティティによって要求されました。



 a| 
CTSR
 a| 
ソースエンティティ
 a| 
CBID 転送のソース (送信者) のノード ID。



 a| 
CTDS
 a| 
宛先エンティティ
 a| 
CBID 転送の宛先 (受信側) のノード ID。



 a| 
CTSS
 a| 
開始シーケンス数
 a| 
転送が開始されたシーケンス数を示します。



 a| 
CTAS
 a| 
実際の終了シーケンス数
 a| 
正常に転送された最後のシーケンス数を示します。実際の終了シーケンス数が開始シーケンス数と同じで、転送結果が成功しなかった場合、データは交換されませんでした。



 a| 
RSLT
 a| 
転送結果
 a| 
転送操作の結果（送信エンティティの観点から）:

SUCS: 転送が正常に完了しました。要求されたすべてのシーケンス カウントが送信されました。

CONL: 転送中に接続が失われました

CTMO: 確立または転送中に接続がタイムアウトしました

UNRE: 宛先ノードIDに到達できません

CRPT: 破損または無効なデータを受信したため転送が終了しました

|===
この監査メッセージは、ノード間のデータ転送操作が完了したことを意味します。転送結果が成功した場合、操作によって「開始シーケンス カウント」から「実際の終了シーケンス カウント」にデータが転送されました。送信ノードと受信ノードはノード ID によって識別されます。この情報を使用して、システムのデータ フローを追跡し、エラーを特定、表にまとめ、分析することができます。ストレージ監査メッセージと組み合わせると、レプリカ数の検証にも使用できます。
