---
permalink: audit/common-elements-in-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message, common elements, AMID, ANID, ASES, ASQN, ATID, ATIM, ATYP, AVER, RSLT 
summary: すべての監査メッセージには共通の要素が含まれています。 
---
= 監査メッセージの共通要素
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべての監査メッセージには共通の要素が含まれています。

[cols="1a,1a,4a"]
|===
| コード | タイプ | 説明 


 a| 
真ん中
 a| 
FC32
 a| 
モジュール ID: メッセージを生成したモジュール ID の 4 文字の識別子。これは、監査メッセージが生成されたコード セグメントを示します。



 a| 
アニド
 a| 
UI32
 a| 
ノード ID: メッセージを生成したサービスに割り当てられたグリッド ノード ID。 StorageGRIDシステムが構成およびインストールされたときに、各サービスに一意の識別子が割り当てられます。このIDは変更できません。



 a| 
ASES
 a| 
UI64
 a| 
監査セッション識別子: 以前のリリースでは、この要素は、サービスの起動後に監査システムが初期化された時刻を示していました。この時間値は、オペレーティング システムのエポック (1970 年 1 月 1 日 00:00:00 UTC) からのマイクロ秒単位で測定されました。

*注:* この要素は廃止されており、監査メッセージには表示されなくなりました。



 a| 
ASQN
 a| 
UI64
 a| 
シーケンス カウント: 以前のリリースでは、このカウンタはグリッド ノード (ANID) で生成された監査メッセージごとに増加し、サービスの再起動時にゼロにリセットされていました。

*注:* この要素は廃止されており、監査メッセージには表示されなくなりました。



 a| 
ATID
 a| 
UI64
 a| 
トレース ID: 単一のイベントによってトリガーされたメッセージのセットによって共有される識別子。



 a| 
アティム
 a| 
UI64
 a| 
タイムスタンプ: 監査メッセージをトリガーしたイベントが生成された時刻。オペレーティング システムのエポック (1970 年 1 月 1 日 00:00:00 UTC) からのマイクロ秒単位で測定されます。タイムスタンプをローカルの日付と時刻に変換するための利用可能なツールのほとんどは、ミリ秒に基づいていることに注意してください。

ログに記録されたタイムスタンプの丸めまたは切り捨てが必要になる場合があります。監査メッセージの冒頭に表示される、人間が読める形式の時刻。 `audit.log`ファイルは ISO 8601 形式の ATIM 属性です。日付と時刻は次のように表されます `_YYYY-MMDDTHH:MM:SS.UUUUUU_`、ここで `T`日付の時間セグメントの開始を示すリテラル文字列文字です。 `_UUUUUU_`マイクロ秒です。



 a| 
ATYP
 a| 
FC32
 a| 
イベント タイプ: 記録されるイベントの 4 文字の識別子。これは、メッセージの「ペイロード」コンテンツ、つまり含まれる属性を制御します。



 a| 
アバー
 a| 
UI32
 a| 
バージョン: 監査メッセージのバージョン。 StorageGRIDソフトウェアが進化するにつれて、新しいバージョンのサービスに監査レポートの新しい機能が組み込まれる可能性があります。このフィールドにより、AMS サービスでの下位互換性が有効になり、古いバージョンのサービスからのメッセージを処理できるようになります。



 a| 
RSLT
 a| 
FC32
 a| 
結果: イベント、プロセス、またはトランザクションの結果。メッセージに関連しない場合は、メッセージが誤ってフィルタリングされないように、SUCS ではなく NONE が使用されます。

|===