---
permalink: audit/etaf-security-authentication-failed.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, ETAF, Security Authentication Failed 
summary: 'このメッセージは、トランスポート層セキュリティ (TLS) を使用した接続試行が失敗したときに生成されます。' 
---
= ETAF: セキュリティ認証に失敗しました
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、トランスポート層セキュリティ (TLS) を使用した接続試行が失敗したときに生成されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CNID
 a| 
接続識別子
 a| 
認証が失敗した TCP/IP 接続の一意のシステム識別子。



 a| 
ルイド
 a| 
ユーザーID
 a| 
リモート ユーザーの ID を表すサービス依存の識別子。



 a| 
RSLT
 a| 
理由コード
 a| 
失敗の理由：

SCNI: 安全な接続の確立に失敗しました。

CERM: 証明書が見つかりません。

CERT: 証明書が無効でした。

CERE: 証明書の有効期限が切れています。

CERR: 証明書は取り消されました。

CSGN: 証明書の署名が無効です。

CSGU: 証明書の署名者が不明です。

UCRM: ユーザー資格情報が見つかりません。

UCRI: ユーザー資格情報が無効です。

UCRU: ユーザー資格情報が許可されませんでした。

TOUT: 認証がタイムアウトしました。

|===
TLS を使用する安全なサービスへの接続が確立されると、TLS プロファイルとサービスに組み込まれた追加ロジックを使用して、リモート エンティティの資格情報が検証されます。無効、予期しない、または許可されていない証明書または資格情報のためにこの認証が失敗した場合、監査メッセージが記録されます。これにより、不正なアクセスの試みやその他のセキュリティ関連の接続の問題を照会できるようになります。

このメッセージは、リモート エンティティの構成が誤っているか、無効または許可されていない資格情報をシステムに提示しようとしたことが原因で発生する可能性があります。システムへの不正アクセスの試みを検出するには、この監査メッセージを監視する必要があります。
