---
permalink: audit/gted-grid-task-ended.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, GTED, Grid Task Ended 
summary: この監査メッセージは、CMN サービスが指定されたグリッド タスクの処理を完了し、タスクを履歴テーブルに移動したことを示します。結果が SUCS、ABRT、または ROLF の場合、対応するグリッド タスク開始監査メッセージが表示されます。その他の結果は、このグリッド タスクの処理が開始されなかったことを示しています。 
---
= GTED: グリッドタスクが終了しました
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この監査メッセージは、CMN サービスが指定されたグリッド タスクの処理を完了し、タスクを履歴テーブルに移動したことを示します。結果が SUCS、ABRT、または ROLF の場合、対応するグリッド タスク開始監査メッセージが表示されます。その他の結果は、このグリッド タスクの処理が開始されなかったことを示しています。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
TSID
 a| 
タスクID
 a| 
このフィールドは、生成されたグリッド タスクを一意に識別し、グリッド タスクをそのライフサイクルにわたって管理できるようにします。

*注:* タスク ID は、グリッド タスクが送信されたときではなく、生成されたときに割り当てられます。特定のグリッド タスクが複数回送信される可能性がありますが、この場合、タスク ID フィールドでは、送信済み、開始済み、および終了済みの監査メッセージを一意にリンクするには不十分です。



 a| 
RSLT
 a| 
結果
 a| 
グリッド タスクの最終ステータス結果:

* SUCS: グリッド タスクは正常に完了しました。
* ABRT: グリッド タスクはロールバック エラーなしで終了しました。
* ROLF: グリッド タスクが終了し、ロールバック プロセスを完了できませんでした。
* CANC: グリッド タスクは、開始される前にユーザーによってキャンセルされました。
* EXPR: グリッド タスクは開始される前に期限が切れました。
* IVLD: グリッド タスクが無効でした。
* AUTH: グリッド タスクは許可されていません。
* DUPL: グリッド タスクは重複として拒否されました。


|===