---
permalink: audit/idel-ilm-initiated-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, IDEL, ILM Initiated Delete 
summary: このメッセージは、ILM がオブジェクトの削除プロセスを開始したときに生成されます。 
---
= IDEL: ILM による削除開始
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、ILM がオブジェクトの削除プロセスを開始したときに生成されます。

IDEL メッセージは、次のいずれかの状況で生成されます。

* *準拠 S3 バケット内のオブジェクトの場合*: このメッセージは、オブジェクトの保持期間が終了したために ILM がオブジェクトの自動削除プロセスを開始したときに生成されます (自動削除設定が有効になっていて、法的保留がオフになっていると想定)。
* *非準拠の S3 バケット内のオブジェクトの場合*。このメッセージは、アクティブな ILM ポリシー内の配置指示が現在オブジェクトに適用されていないため、ILM がオブジェクトの削除プロセスを開始したときに生成されます。


[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CBID
 a| 
コンテンツブロック識別子
 a| 
オブジェクトの CBID。



 a| 
CMPA
 a| 
コンプライアンス: 自動削除
 a| 
準拠した S3 バケット内のオブジェクトのみ対象です。  0 (false) または 1 (true)。バケットが法的保留中でない限り、準拠オブジェクトを保持期間の終了時に自動的に削除するかどうかを示します。



 a| 
CMPL
 a| 
コンプライアンス: 法的保留
 a| 
準拠した S3 バケット内のオブジェクトのみ対象です。  0 (false) または 1 (true)。バケットが現在法的保留中かどうかを示します。



 a| 
CMPR
 a| 
コンプライアンス: 保存期間
 a| 
準拠した S3 バケット内のオブジェクトのみ対象です。オブジェクトの保持期間の長さ（分）。



 a| 
CTME
 a| 
コンプライアンス: 取り込み時間
 a| 
準拠した S3 バケット内のオブジェクトのみ対象です。オブジェクトの取り込み時間。この値に保持期間（分単位）を追加して、バケットからオブジェクトを削除できるタイミングを決定できます。



 a| 
DMRK
 a| 
マーカーバージョンIDを削除
 a| 
バージョン管理されたバケットからオブジェクトを削除するときに作成される削除マーカーのバージョン ID。バケットに対する操作にはこのフィールドは含まれません。



 a| 
CSIZ
 a| 
コンテンツサイズ
 a| 
オブジェクトのサイズ（バイト）。



 a| 
LOCS
 a| 
場所
 a| 
StorageGRIDシステム内のオブジェクト データの保存場所。オブジェクトに場所がない場合（たとえば、削除されている場合）、LOCS の値は "" になります。

CLEC: 消去コード化オブジェクトの場合、オブジェクトのデータに適用される消去コード化プロファイル ID と消去コード化グループ ID。

CLDI: 複製されたオブジェクトの場合、オブジェクトの場所の LDR ノード ID とボリューム ID。

CLNL: オブジェクト データがアーカイブされている場合のオブジェクトの場所の ARC ノード ID。



 a| 
パス
 a| 
S3 バケット/キー
 a| 
S3 バケット名と S3 キー名。



 a| 
RSLT
 a| 
結果
 a| 
ILM 操作の結果。

SUCS: ILM 操作は成功しました。



 a| 
ルール
 a| 
ルールラベル
 a| 
* 準拠 S3 バケット内のオブジェクトが保持期間の期限切れにより自動的に削除されている場合、このフィールドは空白になります。
* 現在オブジェクトに適用されている配置指示がなくなったためにオブジェクトが削除されている場合、このフィールドには、オブジェクトに適用された最後の ILM ルールの判読可能なラベルが表示されます。




 a| 
SGRP
 a| 
サイト（グループ）
 a| 
存在する場合、オブジェクトは指定されたサイトで削除されましたが、そのサイトはオブジェクトが取り込まれたサイトではありません。



 a| 
UUID
 a| 
ユニバーサルユニーク識別子
 a| 
StorageGRIDシステム内のオブジェクトの識別子。



 a| 
VSID
 a| 
バージョン ID
 a| 
削除されたオブジェクトの特定のバージョンのバージョン ID。バケットおよびバージョン管理されていないバケット内のオブジェクトに対する操作には、このフィールドは含まれません。

|===