---
permalink: audit/object-retrieve-transactions.html 
sidebar: sidebar 
keywords: object retrieve, transactions, SGET, WGET 
summary: S3 API 固有の監査メッセージを見つけることで、監査ログ内のオブジェクト取得トランザクションを識別できます。 
---
= オブジェクト取得トランザクション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 API 固有の監査メッセージを見つけることで、監査ログ内のオブジェクト取得トランザクションを識別できます。

取得トランザクション中に生成されるすべての監査メッセージが次の表に記載されているわけではありません。取得トランザクションのトレースに必要なメッセージのみが含まれます。



== S3 取得監査メッセージ

[cols="1a,1a,2a,1a,1a"]
|===
| コード | Name | 説明 | トレース | 詳細については、 


 a| 
SGET
 a| 
S3 GET
 a| 
バケットからオブジェクトを取得する要求が行われました。
 a| 
CBID、S3BK、S3KY
 a| 
link:sget-s3-get.html["SGET: S3 ゲット"]

|===


== 監査メッセージの迅速な取得

[cols="1a,1a,2a,1a,1a"]
|===
| コード | Name | 説明 | トレース | 詳細については、 


 a| 
WGET
 a| 
Swift GET
 a| 
コンテナからオブジェクトを取得する要求。
 a| 
CBID、WCON、WOBJ
 a| 
link:wget-swift-get.html["WGET: Swift GET"]

|===


== 例: S3 オブジェクトの取得

S3 クライアントがストレージ ノード (LDR サービス) からオブジェクトを取得すると、監査メッセージが生成され、監査ログに保存されます。

以下の例には、トランザクション中に生成されるすべての監査メッセージがリストされているわけではないことに注意してください。  S3 取得トランザクション (SGET) に関連するものだけがリストされます。



=== SGET: S3 ゲット

オブジェクトの取得は、クライアントが LDR サービスに GetObject 要求を送信すると開始されます。メッセージには、オブジェクトを取得するバケットと、オブジェクトを識別するために使用されるオブジェクトの S3 キーが含まれています。

[listing, subs="specialcharacters,quotes"]
----
2017-09-20T22:53:08.782605 [AUDT:[RSLT(FC32):SUCS][TIME(UI64):47807][SAIP(IPAD):"10.96.112.26"][S3AI(CSTR):"43979298178977966408"][SACC(CSTR):"s3-account-a"][S3AK(CSTR):"SGKHt7GzEcu0yXhFhT_rL5mep4nJt1w75GBh-O_FEw=="][SUSR(CSTR):"urn:sgws:identity::43979298178977966408:root"][SBAI(CSTR):"43979298178977966408"][SBAC(CSTR):"s3-account-a"]\[S3BK\(CSTR\):"bucket-anonymous"\]\[S3KY\(CSTR\):"Hello.txt"\][CBID(UI64):0x83D70C6F1F662B02][CSIZ(UI64):12][AVER(UI32):10][ATIM(UI64):1505947988782605]\[ATYP\(FC32\):SGET\][ANID(UI32):12272050][AMID(FC32):S3RQ][ATID(UI64):17742374343649889669]]
----
バケット ポリシーで許可されている場合、クライアントは匿名でオブジェクトを取得したり、別のテナント アカウントが所有するバケットからオブジェクトを取得したりできます。監査メッセージにはバケット所有者のテナント アカウントに関する情報が含まれているため、これらの匿名リクエストやアカウント間リクエストを追跡できます。

次のサンプル メッセージでは、クライアントは、自分が所有していないバケットに保存されているオブジェクトに対して GetObject リクエストを送信します。  SBAI および SBAC の値には、バケット所有者のテナント アカウント ID と名前が記録されます。これは、S3AI および SACC に記録されるクライアントのテナント アカウント ID と名前とは異なります。

[listing, subs="specialcharacters,quotes"]
----
2017-09-20T22:53:15.876415 [AUDT:[RSLT(FC32):SUCS][TIME(UI64):53244][SAIP(IPAD):"10.96.112.26"]\[S3AI\(CSTR\):"17915054115450519830"\]\[SACC\(CSTR\):"s3-account-b"\][S3AK(CSTR):"SGKHpoblWlP_kBkqSCbTi754Ls8lBUog67I2LlSiUg=="][SUSR(CSTR):"urn:sgws:identity::17915054115450519830:root"]\[SBAI\(CSTR\):"43979298178977966408"\]\[SBAC\(CSTR\):"s3-account-a"\][S3BK(CSTR):"bucket-anonymous"][S3KY(CSTR):"Hello.txt"][CBID(UI64):0x83D70C6F1F662B02][CSIZ(UI64):12][AVER(UI32):10][ATIM(UI64):1505947995876415][ATYP(FC32):SGET][ANID(UI32):12272050][AMID(FC32):S3RQ][ATID(UI64):6888780247515624902]]
----


== 例: オブジェクトに対するS3 Select

S3 クライアントがオブジェクトに対して S3 Select クエリを発行すると、監査メッセージが生成され、監査ログに保存されます。

以下の例には、トランザクション中に生成されるすべての監査メッセージがリストされているわけではないことに注意してください。  S3 Select トランザクション (SelectObjectContent) に関連するものだけがリストされます。

各クエリの結果、2 つの監査メッセージが生成されます。1 つは S3 Select リクエストの承認を実行するメッセージ (S3SR フィールドは「select」に設定されます)、もう 1 つは処理中にストレージからデータを取得する後続の標準 GET 操作です。

[listing, subs="specialcharacters,quotes"]
----
2021-11-08T15:35:30.750038 [AUDT:[RSLT(FC32):SUCS][CNID(UI64):1636385730715700][TIME(UI64):29173][SAIP(IPAD):"192.168.7.44"][S3AI(CSTR):"63147909414576125820"][SACC(CSTR):"Tenant1636027116"][S3AK(CSTR):"AUFD1XNVZ905F3TW7KSU"][SUSR(CSTR):"urn:sgws:identity::63147909414576125820:root"][SBAI(CSTR):"63147909414576125820"][SBAC(CSTR):"Tenant1636027116"][S3BK(CSTR):"619c0755-9e38-42e0-a614-05064f74126d"][S3KY(CSTR):"SUB-EST2020_ALL.csv"][CBID(UI64):0x0496F0408A721171][UUID(CSTR):"D64B1A4A-9F01-4EE7-B133-08842A099628"][CSIZ(UI64):0][S3SR(CSTR):"select"][AVER(UI32):10][ATIM(UI64):1636385730750038][ATYP(FC32):SPOS][ANID(UI32):12601166][AMID(FC32):S3RQ][ATID(UI64):1363009709396895985]]
----
[listing, subs="specialcharacters,quotes"]
----
2021-11-08T15:35:32.604886 [AUDT:[RSLT(FC32):SUCS][CNID(UI64):1636383069486504][TIME(UI64):430690][SAIP(IPAD):"192.168.7.44"][HTRH(CSTR):"{\"x-forwarded-for\":\"unix:\"}"][S3AI(CSTR):"63147909414576125820"][SACC(CSTR):"Tenant1636027116"][S3AK(CSTR):"AUFD1XNVZ905F3TW7KSU"][SUSR(CSTR):"urn:sgws:identity::63147909414576125820:root"][SBAI(CSTR):"63147909414576125820"][SBAC(CSTR):"Tenant1636027116"][S3BK(CSTR):"619c0755-9e38-42e0-a614-05064f74126d"][S3KY(CSTR):"SUB-EST2020_ALL.csv"][CBID(UI64):0x0496F0408A721171][UUID(CSTR):"D64B1A4A-9F01-4EE7-B133-08842A099628"][CSIZ(UI64):10185581][MTME(UI64):1636380348695262][AVER(UI32):10][ATIM(UI64):1636385732604886][ATYP(FC32):SGET][ANID(UI32):12733063][AMID(FC32):S3RQ][ATID(UI64):16562288121152341130]]
----