---
permalink: audit/object-delete-transactions.html 
sidebar: sidebar 
keywords: object delete transaction, S3 delete, SDEL, WDEL 
summary: S3 API 固有の監査メッセージを見つけることで、監査ログ内のオブジェクト削除トランザクションを識別できます。 
---
= オブジェクト削除トランザクション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 API 固有の監査メッセージを見つけることで、監査ログ内のオブジェクト削除トランザクションを識別できます。

削除トランザクション中に生成されるすべての監査メッセージが次の表に記載されているわけではありません。削除トランザクションのトレースに必要なメッセージのみが含まれます。



== S3 監査メッセージ削除

[cols="1a,1a,2a,1a,2a"]
|===
| コード | Name | 説明 | トレース | 詳細については、 


 a| 
SDEL
 a| 
S3 削除
 a| 
バケットからオブジェクトを削除するリクエストが行われました。
 a| 
CBID、S3KY
 a| 
link:sdel-s3-delete.html["SDEL: S3 削除"]

|===


== 監査メッセージを迅速に削除

[cols="1a,1a,2a,1a,2a"]
|===
| コード | Name | 説明 | トレース | 詳細については、 


 a| 
WDEL
 a| 
迅速な削除
 a| 
コンテナからオブジェクトまたはコンテナを削除する要求。
 a| 
CBID、WOBJ
 a| 
link:wdel-swift-delete.html["WDEL: 迅速な削除"]

|===


== 例: S3 オブジェクトの削除

S3 クライアントがストレージ ノード (LDR サービス) からオブジェクトを削除すると、監査メッセージが生成され、監査ログに保存されます。


NOTE: 削除トランザクション中に生成されるすべての監査メッセージが以下の例にリストされているわけではありません。  S3 削除トランザクション (SDEL) に関連するものだけがリストされます。



=== SDEL: S3 削除

オブジェクトの削除は、クライアントが LDR サービスに DeleteObject 要求を送信すると開始されます。メッセージには、オブジェクトを削除するバケットと、オブジェクトを識別するために使用されるオブジェクトの S3 キーが含まれています。

[listing, subs="specialcharacters,quotes"]
----
2017-07-17T21:17:58.959669[AUDT:[RSLT(FC32):SUCS][TIME(UI64):14316][SAIP(IPAD):"10.96.112.29"][S3AI(CSTR):"70899244468554783528"][SACC(CSTR):"test"][S3AK(CSTR):"SGKHyalRU_5cLflqajtaFmxJn946lAWRJfBF33gAOg=="][SUSR(CSTR):"urn:sgws:identity::70899244468554783528:root"][SBAI(CSTR):"70899244468554783528"][SBAC(CSTR):"test"]\[S3BK\(CSTR\):"example"\]\[S3KY\(CSTR\):"testobject-0-7"\][CBID\(UI64\):0x339F21C5A6964D89][CSIZ(UI64):30720][AVER(UI32):10][ATIM(UI64):150032627859669][ATYP\(FC32\):SDEL][ANID(UI32):12086324][AMID(FC32):S3RQ][ATID(UI64):4727861330952970593]]
----