---
permalink: audit/orlm-object-rules-met.html 
sidebar: sidebar 
keywords: audit message, ORLM, Object Rules Met, ilm rule 
summary: このメッセージは、ILM ルールで指定されたとおりにオブジェクトが正常に保存およびコピーされたときに生成されます。 
---
= ORLM: オブジェクトルールが満たされました
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、ILM ルールで指定されたとおりにオブジェクトが正常に保存およびコピーされたときに生成されます。


NOTE: ポリシー内の別のルールがオブジェクト サイズの詳細フィルターを使用している場合、デフォルトの 2 つのコピーを作成するルールによってオブジェクトが正常に保存されても、ORLM メッセージは生成されません。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
ビルド
 a| 
バケットヘッダー
 a| 
バケット ID フィールド。内部操作に使用されます。  STAT が PRGD の場合にのみ表示されます。



 a| 
CBID
 a| 
コンテンツブロック識別子
 a| 
オブジェクトの CBID。



 a| 
CSIZ
 a| 
コンテンツサイズ
 a| 
オブジェクトのサイズ（バイト）。



 a| 
LOCS
 a| 
場所
 a| 
StorageGRIDシステム内のオブジェクト データの保存場所。オブジェクトに場所がない場合（たとえば、削除されている場合）、LOCS の値は "" になります。

CLEC: 消去コード化オブジェクトの場合、オブジェクトのデータに適用される消去コード化プロファイル ID と消去コード化グループ ID。

CLDI: 複製されたオブジェクトの場合、オブジェクトの場所の LDR ノード ID とボリューム ID。

CLNL: オブジェクト データがアーカイブされている場合のオブジェクトの場所の ARC ノード ID。



 a| 
パス
 a| 
S3 バケット/キー
 a| 
S3 バケット名と S3 キー名。



 a| 
RSLT
 a| 
結果
 a| 
ILM 操作の結果。

SUCS: ILM 操作は成功しました。



 a| 
ルール
 a| 
ルールラベル
 a| 
このオブジェクトに適用された ILM ルールに与えられた、人間が判読できるラベル。



 a| 
SEGC
 a| 
コンテナUUID
 a| 
セグメント化されたオブジェクトのコンテナの UUID。この値は、オブジェクトがセグメント化されている場合にのみ使用できます。



 a| 
SGCB
 a| 
コンテナCBID
 a| 
セグメント化されたオブジェクトのコンテナの CBID。この値は、セグメント化されたオブジェクトとマルチパート オブジェクトに対してのみ使用できます。



 a| 
統計
 a| 
ステータス
 a| 
ILM 操作のステータス。

完了: オブジェクトに対する ILM 操作が完了しました。

DFER: オブジェクトは将来の ILM 再評価の対象としてマークされています。

PRGD: オブジェクトはStorageGRIDシステムから削除されました。

NLOC: オブジェクト データがStorageGRIDシステム内に見つかりません。このステータスは、オブジェクト データのすべてのコピーが欠落しているか破損していることを示している可能性があります。



 a| 
UUID
 a| 
ユニバーサルユニーク識別子
 a| 
StorageGRIDシステム内のオブジェクトの識別子。



 a| 
VSID
 a| 
バージョン ID
 a| 
バージョン管理されたバケットに作成された新しいオブジェクトのバージョン ID。バケットおよびバージョン管理されていないバケット内のオブジェクトに対する操作には、このフィールドは含まれません。

|===
ORLM 監査メッセージは、単一のオブジェクトに対して複数回発行できます。たとえば、次のいずれかのイベントが発生するたびに発行されます。

* オブジェクトの ILM ルールは永久に満たされます。
* このエポックでは、オブジェクトの ILM ルールが満たされています。
* ILM ルールによってオブジェクトが削除されました。
* バックグラウンド検証プロセスにより、複製されたオブジェクト データのコピーが破損していることが検出されます。  StorageGRIDシステムは ILM 評価を実行して、破損したオブジェクトを置き換えます。


.関連情報
* link:object-ingest-transactions.html["オブジェクト取り込みトランザクション"]
* link:object-delete-transactions.html["オブジェクト削除トランザクション"]

