---
permalink: audit/s3-select-request.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, S3SL, S3 Select request 
summary: このメッセージは、ユーザーが S3 Select ジョブを開始したことを示します。 
---
= S3SL: S3 選択リクエスト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、S3 Select リクエストがクライアントに返された後の完了を記録します。 S3SL メッセージには、エラー メッセージとエラー コードの詳細が含まれる場合があります。リクエストが成功しなかった可能性があります。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
BYSC
 a| 
スキャンされたバイト数
 a| 
ストレージ ノードからスキャン (受信) されたバイト数。

オブジェクトが圧縮されている場合、BYSC と BYPR は異なる可能性があります。オブジェクトが圧縮されている場合、BYSC には圧縮されたバイト数が含まれ、BYPR には解凍後のバイト数が含まれます。



 a| 
BYPR
 a| 
処理されたバイト数
 a| 
処理されたバイト数。  S3 Select ジョブによって実際に処理または操作された「スキャンされたバイト数」を示します。



 a| 
BYRT
 a| 
返されたバイト数
 a| 
S3 Select ジョブがクライアントに返したバイト数。



 a| 
再広報
 a| 
処理されたレコード
 a| 
S3 Select ジョブがストレージノードから受信したレコードまたは行の数。



 a| 
RERT
 a| 
返されたレコード
 a| 
S3 Select ジョブがクライアントに返したレコードまたは行の数。



 a| 
ジョフィ
 a| 
仕事完了
 a| 
S3 Select ジョブの処理が完了したかどうかを示します。これが false の場合、ジョブは完了に失敗し、エラー フィールドにデータが含まれる可能性があります。クライアントは部分的な結果を受け取ったか、まったく結果を受け取った可能性があります。



 a| 
リード
 a| 
Request ID
 a| 
S3 Select リクエストの識別子。



 a| 
外務省
 a| 
実行時間
 a| 
S3 選択ジョブが完了するまでにかかった時間 (秒)。



 a| 
ERMG
 a| 
エラー メッセージ
 a| 
S3 Select ジョブによって生成されたエラー メッセージ。



 a| 
エルティ
 a| 
エラーの種類
 a| 
S3 Select ジョブによって生成されたエラーの種類。



 a| 
ERST
 a| 
エラースタックトレース
 a| 
S3 Select ジョブによって生成されたエラー スタック トレース。



 a| 
S3BK
 a| 
S3バケット
 a| 
S3 バケット名。



 a| 
S3AK
 a| 
S3 アクセスキー ID (リクエスト送信者)
 a| 
リクエストを送信したユーザーの S3 アクセスキー ID。



 a| 
S3AI
 a| 
S3テナントアカウントID（リクエスト送信者）
 a| 
リクエストを送信したユーザーのテナント アカウント ID。



 a| 
S3KY
 a| 
S3キー
 a| 
バケット名を含まない S3 キー名。

|===