---
permalink: audit/sdel-s3-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SDEL, S3 DELETE 
summary: S3 クライアントが DELETE トランザクションを発行すると、指定されたオブジェクトまたはバケットを削除するリクエストが行われます。トランザクションが成功した場合、このメッセージはサーバーによって発行されます。 
---
= SDEL: S3 削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 クライアントが DELETE トランザクションを発行すると、指定されたオブジェクトまたはバケットを削除するか、バケット/オブジェクトのサブリソースを削除するように要求されます。トランザクションが成功した場合、このメッセージはサーバーによって発行されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CBID
 a| 
コンテンツブロック識別子
 a| 
要求されたコンテンツ ブロックの一意の識別子。 CBID が不明な場合、このフィールドは 0 に設定されます。バケットに対する操作にはこのフィールドは含まれません。



 a| 
CNCH
 a| 
一貫性制御ヘッダー
 a| 
リクエスト内に存在する場合の Consistency-Control HTTP リクエスト ヘッダーの値。



 a| 
CNID
 a| 
接続識別子
 a| 
TCP/IP 接続の一意のシステム識別子。



 a| 
CSIZ
 a| 
コンテンツサイズ
 a| 
削除されたオブジェクトのサイズ（バイト単位）。バケットに対する操作にはこのフィールドは含まれません。



 a| 
DMRK
 a| 
マーカーバージョンIDを削除
 a| 
バージョン管理されたバケットからオブジェクトを削除するときに作成される削除マーカーのバージョン ID。バケットに対する操作にはこのフィールドは含まれません。



 a| 
GFID
 a| 
グリッドフェデレーション接続ID
 a| 
クロスグリッド レプリケーション削除要求に関連付けられたグリッド フェデレーション接続の接続 ID。宛先グリッドの監査ログにのみ含まれます。



 a| 
GFSA
 a| 
グリッドフェデレーションソースアカウントID
 a| 
クロスグリッド レプリケーション削除リクエストのソース グリッド上のテナントのアカウント ID。宛先グリッドの監査ログにのみ含まれます。



 a| 
HTRH
 a| 
HTTPリクエストヘッダー
 a| 
構成時に選択された、ログに記録された HTTP 要求ヘッダー名と値のリスト。

 `X-Forwarded-For`リクエストに存在し、 `X-Forwarded-For`値が要求送信者の IP アドレス (SAIP 監査フィールド) と異なります。

`x-amz-bypass-governance-retention`リクエスト内に存在する場合は自動的に含まれます。



 a| 
MTME
 a| 
最終更新日時
 a| 
オブジェクトが最後に変更された時刻を示す、マイクロ秒単位の Unix タイムスタンプ。



 a| 
RSLT
 a| 
結果コード
 a| 
DELETE トランザクションの結果。結果は常に次のようになります:

SUCS: 成功



 a| 
S3AI
 a| 
S3テナントアカウントID（リクエスト送信者）
 a| 
リクエストを送信したユーザーのテナント アカウント ID。空の値は匿名アクセスを示します。



 a| 
S3AK
 a| 
S3 アクセスキー ID (リクエスト送信者)
 a| 
リクエストを送信したユーザーのハッシュ化された S3 アクセスキー ID。空の値は匿名アクセスを示します。



 a| 
S3BK
 a| 
S3 バケット
 a| 
S3 バケット名。



 a| 
S3KY
 a| 
S3キー
 a| 
バケット名を含まない S3 キー名。バケットに対する操作にはこのフィールドは含まれません。



 a| 
S3SR
 a| 
S3 サブリソース
 a| 
該当する場合、操作対象のバケットまたはオブジェクト サブリソース。



 a| 
SACC
 a| 
S3テナントアカウント名（リクエスト送信者）
 a| 
リクエストを送信したユーザーのテナント アカウントの名前。匿名のリクエストの場合は空です。



 a| 
SAIP
 a| 
IPアドレス（リクエスト送信者）
 a| 
要求を行ったクライアント アプリケーションの IP アドレス。



 a| 
SBAC
 a| 
S3テナントアカウント名（バケット所有者）
 a| 
バケット所有者のテナント アカウント名。クロスアカウントまたは匿名アクセスを識別するために使用されます。



 a| 
SBAI
 a| 
S3 テナントアカウント ID (バケット所有者)
 a| 
ターゲット バケットの所有者のテナント アカウント ID。クロスアカウントまたは匿名アクセスを識別するために使用されます。



 a| 
SGRP
 a| 
サイト（グループ）
 a| 
存在する場合、オブジェクトは指定されたサイトで削除されましたが、そのサイトはオブジェクトが取り込まれたサイトではありません。



 a| 
SUSR
 a| 
S3 ユーザー URN (リクエスト送信者)
 a| 
テナント アカウント ID と、リクエストを行っているユーザーのユーザー名。ユーザーはローカル ユーザーまたは LDAP ユーザーのいずれかになります。例：  `urn:sgws:identity::03393893651506583485:root`

匿名のリクエストの場合は空です。



 a| 
時間
 a| 
Time
 a| 
リクエストの合計処理時間（マイクロ秒単位）。



 a| 
TLIP
 a| 
信頼できるロードバランサのIPアドレス
 a| 
リクエストが信頼できるレイヤー 7 ロード バランサによってルーティングされた場合は、ロード バランサの IP アドレス。



 a| 
UUDM
 a| 
削除マーカーのユニバーサルユニーク識別子
 a| 
削除マーカーの識別子。監査ログ メッセージは UUDM または UUID のいずれかを指定します。UUDM はオブジェクト削除要求の結果として作成された削除マーカーを示し、UUID はオブジェクトを示します。



 a| 
UUID
 a| 
ユニバーサルユニーク識別子
 a| 
StorageGRIDシステム内のオブジェクトの識別子。



 a| 
VSID
 a| 
バージョン ID
 a| 
削除されたオブジェクトの特定のバージョンのバージョン ID。バケットおよびバージョン管理されていないバケット内のオブジェクトに対する操作には、このフィールドは含まれません。

|===