---
permalink: audit/supd-s3-metadata-updated.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SUPD, S3 Metadata Updated 
summary: このメッセージは、S3 クライアントが取り込んだオブジェクトのメタデータを更新したときに、S3 API によって生成されます。メタデータの更新が成功した場合、サーバーによってメッセージが発行されます。 
---
= SUPD: S3 メタデータが更新されました
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、S3 クライアントが取り込んだオブジェクトのメタデータを更新したときに、S3 API によって生成されます。メタデータの更新が成功した場合、サーバーによってメッセージが発行されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CBID
 a| 
コンテンツブロック識別子
 a| 
要求されたコンテンツ ブロックの一意の識別子。 CBID が不明な場合、このフィールドは 0 に設定されます。バケットに対する操作にはこのフィールドは含まれません。



 a| 
CNCH
 a| 
一貫性制御ヘッダー
 a| 
バケットのコンプライアンス設定を更新するときの、Consistency-Control HTTP リクエスト ヘッダーの値 (リクエスト内に存在する場合)。



 a| 
CNID
 a| 
接続識別子
 a| 
TCP/IP 接続の一意のシステム識別子。



 a| 
CSIZ
 a| 
コンテンツサイズ
 a| 
取得したオブジェクトのサイズ（バイト単位）。バケットに対する操作にはこのフィールドは含まれません。



 a| 
HTRH
 a| 
HTTPリクエストヘッダー
 a| 
構成時に選択された、ログに記録された HTTP 要求ヘッダー名と値のリスト。

 `X-Forwarded-For`リクエストに存在し、 `X-Forwarded-For`値が要求送信者の IP アドレス (SAIP 監査フィールド) と異なります。



 a| 
RSLT
 a| 
結果コード
 a| 
GET トランザクションの結果。結果は常に次のようになります:

SUCS: 成功



 a| 
S3AI
 a| 
S3テナントアカウントID（リクエスト送信者）
 a| 
リクエストを送信したユーザーのテナント アカウント ID。空の値は匿名アクセスを示します。



 a| 
S3AK
 a| 
S3 アクセスキー ID (リクエスト送信者)
 a| 
リクエストを送信したユーザーのハッシュ化された S3 アクセスキー ID。空の値は匿名アクセスを示します。



 a| 
S3BK
 a| 
S3 バケット
 a| 
S3 バケット名。



 a| 
S3KY
 a| 
S3キー
 a| 
バケット名を含まない S3 キー名。バケットに対する操作にはこのフィールドは含まれません。



 a| 
SACC
 a| 
S3テナントアカウント名（リクエスト送信者）
 a| 
リクエストを送信したユーザーのテナント アカウントの名前。匿名のリクエストの場合は空です。



 a| 
SAIP
 a| 
IPアドレス（リクエスト送信者）
 a| 
要求を行ったクライアント アプリケーションの IP アドレス。



 a| 
SBAC
 a| 
S3テナントアカウント名（バケット所有者）
 a| 
バケット所有者のテナント アカウント名。クロスアカウントまたは匿名アクセスを識別するために使用されます。



 a| 
SBAI
 a| 
S3 テナントアカウント ID (バケット所有者)
 a| 
ターゲット バケットの所有者のテナント アカウント ID。クロスアカウントまたは匿名アクセスを識別するために使用されます。



 a| 
SUSR
 a| 
S3 ユーザー URN (リクエスト送信者)
 a| 
テナント アカウント ID と、リクエストを行っているユーザーのユーザー名。ユーザーはローカル ユーザーまたは LDAP ユーザーのいずれかになります。例：  `urn:sgws:identity::03393893651506583485:root`

匿名のリクエストの場合は空です。



 a| 
時間
 a| 
Time
 a| 
リクエストの合計処理時間（マイクロ秒単位）。



 a| 
TLIP
 a| 
信頼できるロードバランサのIPアドレス
 a| 
リクエストが信頼できるレイヤー 7 ロード バランサによってルーティングされた場合は、ロード バランサの IP アドレス。



 a| 
UUID
 a| 
ユニバーサルユニーク識別子
 a| 
StorageGRIDシステム内のオブジェクトの識別子。



 a| 
VSID
 a| 
バージョン ID
 a| 
メタデータが更新されたオブジェクトの特定のバージョンのバージョン ID。バケットおよびバージョン管理されていないバケット内のオブジェクトに対する操作には、このフィールドは含まれません。

|===