---
permalink: audit/svrf-object-store-verify-fail.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SVRF, Object Store Verify Fail 
summary: このメッセージは、コンテンツ ブロックが検証プロセスに失敗するたびに発行されます。複製されたオブジェクト データがディスクから読み取られたり、ディスクに書き込まれたりするときは毎回、要求元のユーザーに送信されるデータがシステムに最初に取り込まれたデータと同一であることを確認するために、いくつかの検証と整合性チェックが実行されます。これらのチェックのいずれかが失敗した場合、システムは破損した複製オブジェクト データを自動的に隔離し、再度取得されないようにします。 
---
= SVRF: オブジェクトストア検証失敗
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、コンテンツ ブロックが検証プロセスに失敗するたびに発行されます。複製されたオブジェクト データがディスクから読み取られたり、ディスクに書き込まれたりするときは毎回、要求元のユーザーに送信されるデータがシステムに最初に取り込まれたデータと同一であることを確認するために、いくつかの検証と整合性チェックが実行されます。これらのチェックのいずれかが失敗した場合、システムは破損した複製オブジェクト データを自動的に隔離し、再度取得されないようにします。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CBID
 a| 
コンテンツブロック識別子
 a| 
検証に失敗したコンテンツ ブロックの一意の識別子。



 a| 
RSLT
 a| 
結果コード
 a| 
検証失敗の種類:

CRCF: 巡回冗長検査 (CRC) に失敗しました。

HMAC: ハッシュベースのメッセージ認証コード (HMAC) チェックに失敗しました。

EHSH: 予期しない暗号化されたコンテンツ ハッシュ。

PHSH: 予期しない元のコンテンツ ハッシュ。

SEQC: ディスク上のデータ シーケンスが正しくありません。

PERR: ディスク ファイルの構造が無効です。

DERR: ディスク エラー。

FNAM: ファイル名が間違っています。

|===

NOTE: このメッセージは注意深く監視する必要があります。コンテンツ検証の失敗は、ハードウェア障害が差し迫っていることを示している可能性があります。

どの操作によってメッセージがトリガーされたかを確認するには、AMID (モジュール ID) フィールドの値を確認します。たとえば、SVFY 値は、メッセージが Storage Verifier モジュール (つまりバックグラウンド検証) によって生成されたことを示し、STOR は、メッセージがコンテンツの取得によってトリガーされたことを示します。
