---
permalink: audit/wdel-swift-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WDEL, Swift DELETE 
summary: Swift クライアントが DELETE トランザクションを発行すると、指定されたオブジェクトまたはコンテナを削除する要求が行われます。トランザクションが成功した場合、このメッセージはサーバーによって発行されます。 
---
= WDEL: 迅速な削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Swift クライアントが DELETE トランザクションを発行すると、指定されたオブジェクトまたはコンテナを削除する要求が行われます。トランザクションが成功した場合、このメッセージはサーバーによって発行されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CBID
 a| 
コンテンツブロック識別子
 a| 
要求されたコンテンツ ブロックの一意の識別子。 CBID が不明な場合、このフィールドは 0 に設定されます。コンテナに対する操作にはこのフィールドは含まれません。



 a| 
CSIZ
 a| 
コンテンツサイズ
 a| 
削除されたオブジェクトのサイズ（バイト単位）。コンテナに対する操作にはこのフィールドは含まれません。



 a| 
HTRH
 a| 
HTTPリクエストヘッダー
 a| 
構成時に選択された、ログに記録された HTTP 要求ヘッダー名と値のリスト。

 `X-Forwarded-For`リクエストに存在し、 `X-Forwarded-For`値が要求送信者の IP アドレス (SAIP 監査フィールド) と異なります。



 a| 
MTME
 a| 
最終更新日時
 a| 
オブジェクトが最後に変更された時刻を示す、マイクロ秒単位の Unix タイムスタンプ。



 a| 
RSLT
 a| 
結果コード
 a| 
DELETE トランザクションの結果。結果は常に次のようになります:

SUCS: 成功



 a| 
SAIP
 a| 
要求元クライアントのIPアドレス
 a| 
要求を行ったクライアント アプリケーションの IP アドレス。



 a| 
SGRP
 a| 
サイト（グループ）
 a| 
存在する場合、オブジェクトは指定されたサイトで削除されましたが、そのサイトはオブジェクトが取り込まれたサイトではありません。



 a| 
時間
 a| 
Time
 a| 
リクエストの合計処理時間（マイクロ秒単位）。



 a| 
TLIP
 a| 
信頼できるロードバランサのIPアドレス
 a| 
リクエストが信頼できるレイヤー 7 ロード バランサによってルーティングされた場合は、ロード バランサの IP アドレス。



 a| 
UUID
 a| 
ユニバーサルユニーク識別子
 a| 
StorageGRIDシステム内のオブジェクトの識別子。



 a| 
WACC
 a| 
SwiftアカウントID
 a| 
StorageGRIDシステムによって指定された一意のアカウント ID。



 a| 
WCON
 a| 
Swiftコンテナ
 a| 
Swift コンテナ名。



 a| 
WOBJ
 a| 
Swiftオブジェクト
 a| 
Swift オブジェクト識別子。コンテナに対する操作にはこのフィールドは含まれません。



 a| 
WUSR
 a| 
Swiftアカウントユーザー
 a| 
トランザクションを実行するクライアントを一意に識別する Swift アカウントのユーザー名。

|===