---
permalink: audit/wget-swift-get.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WGET, Swift GET 
summary: Swift クライアントが GET トランザクションを発行すると、オブジェクトの取得、コンテナー内のオブジェクトのリスト、またはアカウント内のコンテナーのリストの取得の要求が行われます。トランザクションが成功した場合、このメッセージはサーバーによって発行されます。 
---
= WGET: Swift GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Swift クライアントが GET トランザクションを発行すると、オブジェクトの取得、コンテナー内のオブジェクトのリスト、またはアカウント内のコンテナーのリストの取得の要求が行われます。トランザクションが成功した場合、このメッセージはサーバーによって発行されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CBID
 a| 
コンテンツブロック識別子
 a| 
要求されたコンテンツ ブロックの一意の識別子。 CBID が不明な場合、このフィールドは 0 に設定されます。アカウントおよびコンテナに対する操作にはこのフィールドは含まれません。



 a| 
CSIZ
 a| 
コンテンツサイズ
 a| 
取得したオブジェクトのサイズ（バイト単位）。アカウントおよびコンテナに対する操作にはこのフィールドは含まれません。



 a| 
HTRH
 a| 
HTTPリクエストヘッダー
 a| 
構成時に選択された、ログに記録された HTTP 要求ヘッダー名と値のリスト。

 `X-Forwarded-For`リクエストに存在し、 `X-Forwarded-For`値が要求送信者の IP アドレス (SAIP 監査フィールド) と異なります。



 a| 
RSLT
 a| 
結果コード
 a| 
GET トランザクションの結果。結果は常に

SUCS: 成功



 a| 
SAIP
 a| 
要求元クライアントのIPアドレス
 a| 
要求を行ったクライアント アプリケーションの IP アドレス。



 a| 
時間
 a| 
Time
 a| 
リクエストの合計処理時間（マイクロ秒単位）。



 a| 
TLIP
 a| 
信頼できるロードバランサのIPアドレス
 a| 
リクエストが信頼できるレイヤー 7 ロード バランサによってルーティングされた場合は、ロード バランサの IP アドレス。



 a| 
UUID
 a| 
ユニバーサルユニーク識別子
 a| 
StorageGRIDシステム内のオブジェクトの識別子。



 a| 
WACC
 a| 
SwiftアカウントID
 a| 
StorageGRIDシステムによって指定された一意のアカウント ID。



 a| 
WCON
 a| 
Swiftコンテナ
 a| 
Swift コンテナ名。アカウントに対する操作にはこのフィールドは含まれません。



 a| 
WOBJ
 a| 
Swiftオブジェクト
 a| 
Swift オブジェクト識別子。アカウントおよびコンテナに対する操作にはこのフィールドは含まれません。



 a| 
WUSR
 a| 
Swiftアカウントユーザー
 a| 
トランザクションを実行するクライアントを一意に識別する Swift アカウントのユーザー名。

|===