---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: StorageGRIDシステムをアップグレードする前に、システムがアップグレードに対応できる準備ができていることを確認します。システムが正常に動作しており、すべてのグリッド ノードが動作していることを確認します。 
---
= システムの状態を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDシステムをアップグレードする前に、システムがアップグレードに対応する準備ができていることを確認します。システムが正常に動作しており、すべてのグリッド ノードが動作していることを確認します。

.手順
. グリッドマネージャーにSign inには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
. アクティブなアラートを確認して解決します。
. 競合するグリッド タスクがアクティブまたは保留中になっていないことを確認します。
+
.. *サポート* > *ツール* > *グリッド トポロジ* を選択します。
.. *_site_* > *_primary Admin Node_* > *CMN* > *グリッド タスク* > *構成* を選択します。
+
情報ライフサイクル管理評価 (ILME) タスクは、ソフトウェア アップグレードと同時に実行できる唯一のグリッド タスクです。

.. 他のグリッド タスクがアクティブまたは保留中の場合は、それらのタスクが完了するまで待機するか、ロックを解除します。
+

NOTE: タスクが終了しない、またはロックが解除されない場合は、テクニカル サポートにお問い合わせください。



. 参照link:../network/internal-grid-node-communications.html["内部でのGridノードの通信"]そしてlink:../network/external-communications.html["外部コミュニケーション"]アップグレードする前に、 StorageGRID 11.9 に必要なすべてのポートが開いていることを確認します。
+

NOTE: StorageGRID 11.9 にアップグレードする場合、追加のポートは必要ありません。

+
StorageGRID 11.7 では次の必須ポートが追加されました。  StorageGRID 11.9 にアップグレードする前に、利用可能であることを確認してください。

+
[cols="1a,2a"]
|===
| ポート | 説明 


 a| 
18086
 a| 
StorageGRIDロード バランサから LDR および新しい LDR サービスへの S3 要求に使用される TCP ポート。

アップグレードする前に、このポートがすべてのグリッド ノードからすべてのストレージ ノードに開いていることを確認してください。

このポートをブロックすると、 StorageGRID 11.9 へのアップグレード後に S3 サービスが中断されます。

|===



CAUTION: カスタム ファイアウォール ポートを開いている場合は、アップグレードの事前チェック中に通知されます。アップグレードを続行する前に、テクニカル サポートに連絡する必要があります。
