---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: アップグレードにかかる時間に基づいて、いつアップグレードするかを検討します。アップグレードの各段階で実行できる操作と実行できない操作を認識しておいてください。 
---
= アップグレードの完了にかかる時間を見積もる
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードにかかる時間に基づいて、いつアップグレードするかを検討します。アップグレードの各段階で実行できる操作と実行できない操作を認識しておいてください。

.タスク概要
StorageGRID のアップグレードを完了するために必要な時間は、クライアントの負荷やハードウェアのパフォーマンスなど、さまざまな要因によって異なります。

この表には、主なアップグレード タスクの概要と、各タスクに必要なおおよその時間が記載されています。表の後の手順では、システムのアップグレード時間を見積もるために使用できる指示を示します。

[cols="1a,2a,2a,4a"]
|===
| アップグレードタスク | 説明 | 所要時間の目安 | この作業中 


 a| 
事前チェックを実行し、プライマリ管理ノードをアップグレードします
 a| 
アップグレードの事前チェックが実行され、プライマリ管理ノードが停止、アップグレード、再起動されます。
 a| 
30 分～ 1 時間。サービス アプライアンス ノードに最も時間がかかります。

今回は未解決の事前チェックエラーが増加します。
 a| 
プライマリ管理ノードにアクセスできません。接続エラーが報告される場合がありますが、無視できます。

アップグレードを開始する前にアップグレード事前チェックを実行すると、スケジュールされたアップグレードメンテナンスウィンドウの前にエラーを解決できます。



 a| 
アップグレードサービスを開始する
 a| 
ソフトウェア ファイルが配布され、アップグレード サービスが開始されます。
 a| 
グリッドノードごとに3分
 a| 



 a| 
他のグリッドノードをアップグレードする
 a| 
他のすべてのグリッド ノードのソフトウェアは、ノードを承認した順序でアップグレードされます。システム内のすべてのノードが 1 つずつダウンします。
 a| 
ノードあたり15分～1時間。アプライアンスノードでは最も時間がかかります。

*注*: アプライアンス ノードの場合、 StorageGRIDアプライアンス インストーラは自動的に最新リリースに更新されます。
 a| 
* グリッド構成は変更しないでください。
* 監査レベルの構成は変更しないでください。
* ILM 構成を更新しないでください。
* ホットフィックス、廃止、拡張などのその他のメンテナンス手順を実行することはできません。


*注*: 回復を実行する必要がある場合は、テクニカル サポートにお問い合わせください。



 a| 
機能を有効にする
 a| 
新しいバージョンの新機能が有効になります。
 a| 
5分未満
 a| 
* グリッド構成は変更しないでください。
* 監査レベルの構成は変更しないでください。
* ILM 構成を更新しないでください。
* 別のメンテナンス手順を実行することはできません。




 a| 
データベースのアップグレード
 a| 
アップグレード プロセスでは、各ノードをチェックして、Cassandra データベースを更新する必要がないことを確認します。
 a| 
ノードあたり10秒、グリッド全体では数分
 a| 
StorageGRID 11.8 から 11.9 へのアップグレードでは Cassandra データベースのアップグレードは必要ありませんが、各ストレージ ノードで Cassandra サービスが停止され、再起動されます。

今後のStorageGRID機能リリースでは、Cassandra データベースの更新手順が完了するまでに数日かかる可能性があります。



 a| 
最終アップグレード手順
 a| 
一時ファイルが削除され、新しいリリースへのアップグレードが完了します。
 a| 
5分
 a| 
*最終アップグレード手順*タスクが完了すると、すべてのメンテナンス手順を実行できます。

|===
.手順
. すべてのグリッド ノードをアップグレードするのに必要な時間を見積もります。
+
.. StorageGRIDシステム内のノードの数に 1 時間/ノードを掛けます。
+
一般に、アプライアンス ノードのアップグレードには、ソフトウェア ベースのノードよりも時間がかかります。

.. ダウンロードに必要な時間を考慮して、この時間に1時間を追加してください。 `.upgrade`ファイルを作成し、事前チェック検証を実行して、最終的なアップグレード手順を完了します。


. Linux ノードがある場合は、RPM または DEB パッケージのダウンロードとインストールに必要な時間を考慮して、ノードごとに 15 分を追加します。
. 手順 1 と 2 の結果を加算して、アップグレードにかかる合計推定時間を計算します。




== 例: StorageGRID 11.9 へのアップグレードにかかる推定時間

システムに 14 個のグリッド ノードがあり、そのうち 8 個が Linux ノードであるとします。

. 14 に 1 時間/ノードを掛けます。
. ダウンロード、事前チェック、最終手順を考慮して 1 時間を追加します。
+
すべてのノードをアップグレードするのにかかる推定時間は 15 時間です。

. Linux ノードに RPM または DEB パッケージをインストールする時間を考慮するには、8 に 15 分/ノードを掛けます。
+
このステップにかかる推定時間は 2 時間です。

. 値を合計します。
+
システムをStorageGRID 11.9.0 にアップグレードするには、最大 17 時間かかります。




NOTE: 必要に応じて、グリッド ノードのサブセットを複数のセッションでアップグレードすることを承認することで、メンテナンス ウィンドウをより小さなウィンドウに分割できます。たとえば、1 回のセッションでサイト A のノードをアップグレードし、その後のセッションでサイト B のノードをアップグレードする場合があります。アップグレードを複数のセッションで実行することを選択した場合は、すべてのノードがアップグレードされるまで新しい機能の使用を開始できないことに注意してください。
