---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: アップグレード中にStorageGRIDシステムにどのような影響が及ぶかを確認します。 
---
= アップグレード中にシステムにどのような影響があるか
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレード中にStorageGRIDシステムにどのような影響が及ぶかを確認します。



== StorageGRIDのアップグレードは無停止で実行される

StorageGRIDシステムは、アップグレード プロセス全体を通じてクライアント アプリケーションからデータを取り込んで取得できます。同じタイプのすべてのノード (たとえば、ストレージ ノード) のアップグレードを承認すると、ノードは 1 つずつ停止されるため、すべてのグリッド ノードまたは特定のタイプのすべてのグリッド ノードが使用できなくなる時間はありません。

継続的な可用性を確保するには、ILM ポリシーに各オブジェクトの複数のコピーを保存することを指定するルールが含まれていることを確認します。また、すべての外部 S3 クライアントが次のいずれかにリクエストを送信するように設定されていることを確認する必要があります。

* 高可用性（HA）グループの仮想IPアドレス
* 他社製の高可用性ロード バランサ
* 各クライアントに複数のゲートウェイノード
* 各クライアントに複数のストレージノード




== クライアントアプリケーションで短期的な中断が発生する可能性があります

StorageGRIDシステムは、アップグレード プロセス全体を通じてクライアント アプリケーションからデータを取り込んで取得できます。ただし、アップグレードでこれらのノード上のサービスを再起動する必要がある場合、個々のゲートウェイ ノードまたはストレージ ノードへのクライアント接続が一時的に中断される可能性があります。アップグレード プロセスが完了し、個々のノードでサービスが再開されると、接続が復元されます。

短期間の接続の喪失が許容できない場合は、アップグレードを適用するためにダウンタイムをスケジュールする必要がある場合があります。選択的承認を使用して、特定のノードが更新されるタイミングをスケジュールできます。


NOTE: 複数のゲートウェイと高可用性 (HA) グループを使用して、アップグレード プロセス中に自動フェイルオーバーを実現できます。説明書をご覧くださいlink:../admin/configure-high-availability-group.html["高可用性グループの構成"]。



== アプライアンスのファームウェアがアップグレードされました

StorageGRID 11.9 のアップグレード中:

* すべてのStorageGRIDアプライアンス ノードは、 StorageGRIDアプライアンス インストーラ ファームウェア バージョン 3.9 に自動的にアップグレードされます。
* SG6060 および SGF6024 アプライアンスは、BIOS ファームウェア バージョン 3B08.EX およびBMCファームウェア バージョン 4.00.07 に自動的にアップグレードされます。
* SG100 および SG1000 アプライアンスは、BIOS ファームウェア バージョン 3B13.EC およびBMCファームウェア バージョン 4.74.07 に自動的にアップグレードされます。
* SGF6112、SG6160、SG110、および SG1100 アプライアンスは、 BMCファームウェア バージョン 3.16.07 に自動的にアップグレードされます。




== ILMポリシーは、そのステータスに応じて異なる方法で処理されます。

* アップグレード後もアクティブなポリシーは同じままです。
* アップグレード時には、最新の 10 件の履歴ポリシーのみが保存されます。
* 提案されたポリシーがある場合は、アップグレード中に削除されます。




== アラートが発せられる可能性があります

サービスが開始および停止したとき、およびStorageGRIDシステムが混合バージョン環境 (一部のグリッド ノードが以前のバージョンを実行し、他のグリッド ノードが新しいバージョンにアップグレードされている) として動作しているときに、アラートがトリガーされる可能性があります。アップグレードが完了した後に他のアラートがトリガーされる可能性があります。

たとえば、サービスが停止すると「*ノードと通信できません*」というアラートが表示されたり、一部のノードがStorageGRID 11.9 にアップグレードされたが他のノードではまだStorageGRID 11.8 が実行されている場合は「*Cassandra 通信エラー*」というアラートが表示されることがあります。通常、アップグレードが完了するとこれらのアラートは消えます。

StorageGRID 11.9 へのアップグレード中にストレージ ノードが停止すると、*ILM 配置が不可能* というアラートがトリガーされる可能性があります。このアラートは、アップグレードの完了後も 1 日間表示され続ける可能性があります。

アップグレードが完了したら、グリッド マネージャー ダッシュボードから *最近解決されたアラート* または *現在のアラート* を選択して、アップグレード関連のアラートを確認できます。



== 多くのSNMP通知が生成される

アップグレード中にグリッド ノードが停止され、再起動されると、大量の SNMP 通知が生成される可能性があることに注意してください。過剰な通知を避けるには、アップグレードを開始する前に、[SNMP エージェント通知を有効にする] チェックボックスをオフにして (*[構成] > [監視] > [SNMP エージェント])、SNMP 通知を無効にします。アップグレードが完了したら、通知を再度有効にします。



== 構成の変更は制限されています


NOTE: このリストは、 StorageGRID 11.8 からStorageGRID 11.9 へのアップグレードに特に適用されます。別のStorageGRIDリリースにアップグレードする場合は、そのリリースのアップグレード手順に記載されている制限された変更のリストを参照してください。

*新機能の有効化*タスクが完了するまで:

* グリッド構成を変更しないでください。
* 新しい機能を有効化または無効化しないでください。
* ILM 構成を更新しないでください。そうしないと、一貫性のない予期しない ILM 動作が発生する可能性があります。
* ホットフィックスを適用したり、グリッド ノードを回復したりしないでください。
+

NOTE: アップグレード中にノードを回復する必要がある場合は、テクニカル サポートにお問い合わせください。

* StorageGRID 11.9 にアップグレードしている間は、HA グループ、VLAN インターフェイス、またはロード バランサ エンドポイントを管理しないでください。
* StorageGRID 11.9 へのアップグレードが完了するまで、HA グループを削除しないでください。他の HA グループ内の仮想 IP アドレスにアクセスできなくなる可能性があります。


*最終アップグレード手順*タスクが完了するまで:

* 拡張手順を実行しないでください。
* 廃止手順を実行しないでください。




== テナントマネージャからバケットの詳細を表示したり、バケットを管理したりすることはできません

StorageGRID 11.9 へのアップグレード中 (つまり、システムが混在バージョン環境で動作している間) は、テナント マネージャを使用してバケットの詳細を表示したり、バケットを管理したりすることはできません。テナント マネージャーの [バケット] ページに、次のいずれかのエラーが表示されます。

* 11.9 にアップグレードしている間は、この API は使用できません。
* 11.9 にアップグレードしている間は、テナント マネージャーでバケットのバージョン管理の詳細を表示することはできません。


このエラーは、11.9 へのアップグレードが完了すると解決されます。

.回避策
11.9 へのアップグレードが進行中は、テナント マネージャを使用する代わりに、次のツールを使用してバケットの詳細を表示したり、バケットを管理したりします。

* バケットに対して標準的なS3操作を実行するには、link:../s3/operations-on-buckets.html["S3 REST API"]またはlink:../tenant/understanding-tenant-management-api.html["テナント管理API"]。
* バケットに対してStorageGRIDカスタム操作 (バケットの一貫性の表示と変更、最終アクセス時間の更新の有効化または無効化、検索統合の構成など) を実行するには、テナント管理 API を使用します。

