---
permalink: upgrade/performing-upgrade.html 
sidebar: sidebar 
keywords: upgrade, how to perform a software upgrade 
summary: StorageGRID 11.9 にアップグレードし、同時にそのリリースの最新の修正プログラムを適用できます。StorageGRIDアップグレード ページには、推奨されるアップグレード パスと、適切なダウンロード ページへの直接リンクが記載されています。 
---
= アップグレードを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.9 にアップグレードし、同時にそのリリースの最新の修正プログラムを適用できます。StorageGRIDアップグレード ページには、推奨されるアップグレード パスと、適切なダウンロード ページへの直接リンクが記載されています。

.開始する前に
すべての考慮事項を確認し、計画と準備の手順をすべて完了しました。



== StorageGRIDアップグレードページにアクセス

最初のステップとして、Grid Manager のStorageGRIDアップグレード ページにアクセスします。

.手順
. グリッドマネージャーにSign inには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
. *メンテナンス* > *システム* > *ソフトウェアアップデート*を選択します。
. StorageGRIDアップグレード タイルから、[アップグレード] を選択します。




== ファイルを選択

StorageGRIDアップグレード ページの更新パスには、最新のStorageGRIDリリースを取得するためにインストールする必要があるメジャー バージョン (例: 11.9.0) とホットフィックス (例: 11.9.0.1) が示されています。推奨バージョンと修正プログラムは、表示されている順序でインストールする必要があります。


TIP: 更新パスが表示されない場合は、ブラウザがNetAppサポート サイトにアクセスできないか、 AutoSupportページ (*[サポート] > [ツール] > [AutoSupport] > [設定]) の [ソフトウェア更新の確認] チェックボックスが無効になっている可能性があります。

.手順
. *ファイルの選択*手順で、更新パスを確認します。
. 「ファイルのダウンロード」セクションで、各 *ダウンロード* リンクを選択し、 NetAppサポート サイトから必要なファイルをダウンロードします。
+
アップデートパスが表示されない場合は、 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetAppのダウンロード：StorageGRID"^]新しいバージョンまたは修正プログラムが利用可能かどうかを確認し、必要なファイルをダウンロードします。

+

NOTE: すべての Linux ホストに RPM または DEB パッケージをダウンロードしてインストールする必要がある場合は、更新パスにStorageGRID のアップグレード ファイルと修正プログラム ファイルがすでにリストされている可能性があります。

. *参照*を選択して、バージョンアップグレードファイルをStorageGRIDにアップロードします。 `NetApp_StorageGRID_11.9.0_Software_uniqueID.upgrade`
+
アップロードと検証のプロセスが完了すると、ファイル名の横に緑色のチェックマークが表示されます。

. 修正プログラム ファイルをダウンロードした場合は、[参照] を選択してそのファイルをアップロードします。修正プログラムはバージョンアップグレードの一環として自動的に適用されます。
. *続行*を選択します。




== 事前チェックを実行する

事前チェックを実行すると、グリッドのアップグレードを開始する前に、アップグレードの問題を検出して解決できます。

.手順
. *事前チェックの実行*手順では、まずグリッドのプロビジョニング パスフレーズを入力します。
. *リカバリ パッケージのダウンロード*を選択します。
+
プライマリ管理ノードをアップグレードする前に、リカバリ パッケージ ファイルの現在のコピーをダウンロードする必要があります。リカバリ パッケージ ファイルを使用すると、障害が発生した場合にシステムを復元できます。

. ファイルをダウンロードしたら、以下の内容にアクセスできることを確認してください。 `Passwords.txt`ファイル。
. ダウンロードしたファイルをコピーする(`.zip`) を 2 つの安全でセキュリティ保護された別の場所に保管します。
+

CAUTION: リカバリ パッケージ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティ保護する必要があります。

. *事前チェックを実行*を選択し、事前チェックが完了するまで待ちます。
. 報告された各事前チェックの詳細を確認し、報告されたエラーを解決します。参照 https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["StorageGRIDソフトウェア アップグレード解決ガイド"^]StorageGRID 11.9 リリース用。
+
システムをアップグレードする前に、すべての事前チェック エラーを解決する必要があります。ただし、アップグレード前に事前チェックの警告に対処する必要はありません。

+

CAUTION: カスタム ファイアウォール ポートを開いている場合は、事前チェック検証中に通知されます。アップグレードを続行する前に、テクニカル サポートに連絡する必要があります。

. 報告された問題を解決するために構成を変更した場合は、*事前チェックを実行*を再度選択して更新された結果を取得します。
+
すべてのエラーが解決された場合は、アップグレードを開始するように求められます。





== アップグレードを開始し、プライマリ管理ノードをアップグレードします

アップグレードを開始すると、アップグレードの事前チェックが再度実行され、プライマリ管理ノードが自動的にアップグレードされます。アップグレードのこの部分には最大 30 分かかる場合があります。


NOTE: プライマリ管理ノードのアップグレード中は、他の Grid Manager ページにアクセスすることはできません。監査ログも利用できなくなります。

.手順
. *アップグレードを開始*を選択します。
+
一時的にグリッド マネージャーにアクセスできなくなることを知らせる警告が表示されます。

. 警告を確認してアップグレードを開始するには、[*OK*] を選択します。
. アップグレードの事前チェックが実行され、プライマリ管理ノードがアップグレードされるまで待機します。
+

NOTE: 事前チェックエラーが報告された場合は、それを解決して再度「アップグレードの開始」を選択してください。

+
グリッドにオンラインで準備完了状態の別の管理ノードがある場合は、それを使用してプライマリ管理ノードのステータスを監視できます。プライマリ管理ノードがアップグレードされるとすぐに、他のグリッド ノードを承認できます。

. 必要に応じて、[*続行*] を選択して、[*他のノードのアップグレード*] ステップにアクセスします。




== 他のノードをアップグレードする

すべてのグリッド ノードをアップグレードする必要がありますが、複数のアップグレード セッションを実行し、アップグレード シーケンスをカスタマイズできます。たとえば、1 回のセッションでサイト A のノードをアップグレードし、その後のセッションでサイト B のノードをアップグレードする場合があります。アップグレードを複数のセッションで実行することを選択した場合は、すべてのノードがアップグレードされるまで新しい機能の使用を開始できないことに注意してください。

ノードのアップグレード順序が重要な場合は、ノードまたはノード グループを 1 つずつ承認し、各ノードのアップグレードが完了するまで待ってから、次のノードまたはノード グループを承認します。


NOTE: グリッド ノードでアップグレードが開始されると、そのノード上のサービスは停止されます。その後、グリッド ノードが再起動されます。ノードと通信しているクライアント アプリケーションのサービスが中断されないようにするには、ノードを停止して再起動する準備ができていることが確実でない限り、ノードのアップグレードを承認しないでください。必要に応じて、メンテナンス期間をスケジュールするか、顧客に通知します。

.手順
. *他のノードのアップグレード* ステップでは、アップグレード全体の開始時刻と各主要なアップグレード タスクのステータスを示す概要を確認します。
+
** *アップグレード サービスの開始* が最初のアップグレード タスクです。このタスク中に、ソフトウェア ファイルがグリッド ノードに配布され、各ノードでアップグレード サービスが開始されます。
** *アップグレード サービスの開始* タスクが完了すると、*他のグリッド ノードのアップグレード* タスクが開始され、リカバリ パッケージの新しいコピーをダウンロードするように求められます。


. プロンプトが表示されたら、プロビジョニング パスフレーズを入力し、リカバリ パッケージの新しいコピーをダウンロードします。
+

CAUTION: プライマリ管理ノードがアップグレードされた後、リカバリ パッケージ ファイルの新しいコピーをダウンロードする必要があります。リカバリ パッケージ ファイルを使用すると、障害が発生した場合にシステムを復元できます。

. 各タイプのノードのステータス テーブルを確認します。非プライマリ管理ノード、ゲートウェイノード、およびストレージノードのテーブルがあります。
+
テーブルが最初に表示されるとき、グリッド ノードは次のいずれかの段階にあります。

+
** アップグレードの開梱
** ダウンロード中
** 承認待ち


. [[approval-step]]アップグレードするグリッド ノードを選択する準備ができたら (または選択したノードを承認解除する必要がある場合は)、次の手順に従います。
+
[cols="1a,1a"]
|===
| Task | 命令 


 a| 
特定のサイトのすべてのノードなど、承認する特定のノードを検索します
 a| 
*検索*フィールドに検索文字列を入力します



 a| 
アップグレードするすべてのノードを選択
 a| 
*すべてのノードを承認*を選択します



 a| 
アップグレード対象として同じタイプのすべてのノードを選択します（たとえば、すべてのストレージノード）。
 a| 
ノードタイプの「すべて承認」ボタンを選択します

同じタイプのノードを複数承認すると、ノードは一度に 1 つずつアップグレードされます。



 a| 
アップグレードする個々のノードを選択する
 a| 
ノードの「承認」ボタンを選択します



 a| 
選択したすべてのノードのアップグレードを延期する
 a| 
*すべてのノードを承認しない*を選択



 a| 
同じタイプの選択されたすべてのノードのアップグレードを延期します
 a| 
ノードタイプの*すべて承認解除*ボタンを選択します



 a| 
個々のノードのアップグレードを延期する
 a| 
ノードの*非承認*ボタンを選択します

|===
. 承認されたノードが次のアップグレード段階を進むのを待ちます。
+
** 承認され、アップグレードを待機中
** サービスを停止しています
+

NOTE: ステージが「サービスの停止」に達した場合、ノードを削除することはできません。  *非承認*ボタンは無効です。

** コンテナを停止しています
** Dockerイメージのクリーンアップ
** ベースOSパッケージのアップグレード
+

NOTE: アプライアンス ノードがこの段階に達すると、アプライアンス上のStorageGRID Appliance Installer ソフトウェアが更新されます。この自動化されたプロセスにより、 StorageGRIDアプライアンス インストーラのバージョンがStorageGRIDソフトウェアのバージョンと同期された状態を維持します。

** リブートしています
+

NOTE: 一部のアプライアンス モデルでは、ファームウェアと BIOS をアップグレードするために複数回再起動する場合があります。

** 再起動後の手順の実行
** サービスの開始
** 完了


. 繰り返します<<approval-step,承認ステップ>>すべてのグリッド ノードがアップグレードされるまで、必要な回数だけ実行できます。




== 完全なアップグレード

すべてのグリッド ノードがアップグレード ステージを完了すると、*他のグリッド ノードのアップグレード* タスクが完了として表示されます。残りのアップグレード タスクはバックグラウンドで自動的に実行されます。

.手順
. *機能の有効化*タスクが完了すると（すぐに完了します）、link:whats-new.html["新機能"]アップグレードされたStorageGRIDバージョンで。
. *データベースのアップグレード* タスク中に、アップグレード プロセスは各ノードをチェックし、Cassandra データベースを更新する必要がないことを確認します。
+

NOTE: StorageGRID 11.8 から 11.9 へのアップグレードでは Cassandra データベースのアップグレードは必要ありませんが、各ストレージ ノードで Cassandra サービスが停止され、再起動されます。今後のStorageGRID機能リリースでは、Cassandra データベースの更新手順が完了するまでに数日かかる可能性があります。

. *データベースのアップグレード* タスクが完了したら、*最終アップグレード手順* が完了するまで数分間待ちます。
. *最終アップグレード手順*が完了すると、アップグレードは完了です。最初のステップである「ファイルを選択」が緑色の成功バナーとともに再表示されます。
. グリッド操作が正常に戻ったことを確認します。
+
.. サービスが正常に動作していること、および予期しないアラートがないことを確認します。
.. StorageGRIDシステムへのクライアント接続が期待どおりに動作していることを確認します。



