---
permalink: upgrade/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords:  
summary: このリリースでは、一部の機能が削除または廃止されました。これらの項目を確認して、アップグレード前にクライアント アプリケーションを更新する必要があるか、構成を変更する必要があるかを把握してください。 
---
= 削除または廃止された機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このリリースでは、一部の機能が削除または廃止されました。これらの項目を確認して、アップグレード前にクライアント アプリケーションを更新する必要があるか、構成を変更する必要があるかを把握してください。



== 用語の意味

非推奨:: この機能は、新しい本番環境では使用しないでください。既存の運用環境では、この機能を引き続き使用できます。
寿命の終わり:: この機能をサポートする最後に出荷されたバージョン。場合によっては、この段階で機能に関するドキュメントが削除されることがあります。
取り外し:: この機能をサポートしていない最初のバージョン。




== StorageGRIDの機能サポート終了

非推奨の機能は N+2 メジャー バージョンで削除されます。たとえば、ある機能がバージョン N (たとえば、6.3) で廃止された場合、その機能が存在する最後のバージョンは N+1 (たとえば、6.4) になります。バージョン N+2 (例: 6.5) は、製品に機能が存在しない最初のリリースです。

参照 https://mysupport.netapp.com/site/info/version-support["ソフトウェアバージョンサポートページ"^]追加情報については。


NOTE: 状況によっては、 NetApp は特定の機能のサポートを予告よりも早く終了する場合があります。

[cols="2a,1a,1a,1a,3a"]
|===
| 特徴 | 非推奨 | 寿命の終わり | 取り外し | 以前のドキュメントへのリンク 


 a| 
レガシーアラーム（アラートではありません）
 a| 
11.7
 a| 
11.8
 a| 
11.9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/monitor/alarms-reference.html["アラームリファレンス（StorageGRID 11.8）"^]



 a| 
アーカイブノードのサポート
 a| 
11.7
 a| 
11.8
 a| 
11.9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html["アーカイブノードの廃止に関する考慮事項（StorageGRID 11.8）"^]

*注意*: アップグレードを開始する前に、次の操作を行う必要があります。

. すべてのアーカイブ ノードを廃止します。見る https://docs.netapp.com/us-en/storagegrid-118/maintain/grid-node-decommissioning.html["グリッドノードの廃止（StorageGRID 11.8 ドキュメントサイト）"^]。
. ストレージ プールと ILM ポリシーからすべてのアーカイブ ノード参照を削除します。見る https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["NetAppナレッジベース: StorageGRID 11.9 ソフトウェア アップグレード解決ガイド"^]。




 a| 
CIFS/Samba 経由の監査エクスポート
 a| 
11.1
 a| 
11.6
 a| 
11.7
 a| 



 a| 
CLBサービス
 a| 
11.4
 a| 
11.6
 a| 
11.7
 a| 



 a| 
Dockerコンテナエンジン
 a| 
11.8
 a| 
11.9
 a| 
TBD
 a| 
ソフトウェアのみのデプロイメント用のコンテナ エンジンとしての Docker のサポートは非推奨になりました。Docker は将来のリリースで別のコンテナ エンジンに置き換えられる予定です。参照link:../ubuntu/software-requirements.html#docker-versions-tested["現在サポートされているDockerバージョンのリスト"]。



 a| 
NFS監査エクスポート
 a| 
11.8
 a| 
11.9
 a| 
12.0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-audit-client-access.html["NFS の監査クライアント アクセスを構成する (StorageGRID 11.8)"^]



 a| 
Swift APIサポート
 a| 
11.7
 a| 
11.9
 a| 
12.0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/swift/index.html["Swift REST API を使用する (StorageGRID 11.8)"^]



 a| 
RHEL 8.8
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
RHEL 9.0
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
RHEL 9.2
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
ウブントゥ 18.04
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
ウブントゥ 20.04
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
Debian 11
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 

|===
以下も参照してください:

* link:../upgrade/changes-to-grid-management-api.html["グリッド管理APIの変更"]
* link:../upgrade/changes-to-tenant-management-api.html["テナント管理APIの変更"]

