---
permalink: upgrade/troubleshooting-upgrade-issues.html 
sidebar: sidebar 
keywords: upgrade, troubleshoot, troubleshooting, errors, upgrade precheck 
summary: アップグレードの実行時に何か問題が発生した場合、自分で問題を解決できる可能性があります。問題を解決できない場合は、できるだけ多くの情報を収集してから、テクニカル サポートにお問い合わせください。 
---
= アップグレードの問題のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードの実行時に何か問題が発生した場合、自分で問題を解決できる可能性があります。問題を解決できない場合は、できるだけ多くの情報を収集してから、テクニカル サポートにお問い合わせください。



== アップグレードが完了しない

次のセクションでは、アップグレードが部分的に失敗した状況から回復する方法について説明します。



=== アップグレード事前チェックエラー

問題を検出して解決するには、実際のアップグレードを開始する前に、アップグレードの事前チェックを手動で実行できます。ほとんどの事前チェック エラーでは、問題を解決する方法に関する情報が提供されます。



=== プロビジョニングの失敗

自動プロビジョニング プロセスが失敗した場合は、テクニカル サポートにお問い合わせください。



=== グリッドノードがクラッシュするか起動に失敗する

アップグレード プロセス中にグリッド ノードがクラッシュした場合、またはアップグレードの完了後に正常に起動しない場合は、テクニカル サポートに連絡して、根本的な問題を調査して修正してください。



=== 取り込みまたはデータ取得が中断される

グリッド ノードをアップグレードしていないときにデータの取り込みまたは取得が予期せず中断された場合は、テクニカル サポートにお問い合わせください。



=== データベースのアップグレードエラー

データベースのアップグレードがエラーで失敗した場合は、アップグレードを再試行してください。再度失敗する場合は、テクニカル サポートにお問い合わせください。

.関連情報
link:checking-systems-condition-before-upgrading-software.html["ソフトウェアをアップグレードする前にシステムの状態を確認する"]



== ユーザ インターフェイスに関する問題

アップグレード中またはアップグレード後に、Grid Manager または Tenant Manager で問題が発生する可能性があります。



=== グリッド マネージャーはアップグレード中に複数のエラー メッセージを表示します

プライマリ管理ノードのアップグレード中にブラウザを更新したり、別のグリッド マネージャー ページに移動したりすると、「503: サービスを利用できません」および「サーバーへの接続に問題が発生しました」というメッセージが複数表示されることがあります。これらのメッセージは無視しても問題ありません。ノードがアップグレードされるとすぐに表示されなくなります。

アップグレードを開始してから 1 時間以上経過してもこれらのメッセージが表示される場合は、プライマリ管理ノードのアップグレードを妨げる何らかの問題が発生した可能性があります。問題を自分で解決できない場合は、テクニカル サポートにお問い合わせください。



=== Webインターフェースが期待通りに応答しない

StorageGRIDソフトウェアをアップグレードした後、Grid Manager または Tenant Manager が期待どおりに応答しない場合があります。

Web インターフェースで問題が発生した場合:

* 必ずlink:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"]。
+

NOTE: ブラウザのサポートは通常、 StorageGRID のリリースごとに変更されます。

* Web ブラウザのキャッシュをクリアします。
+
キャッシュをクリアすると、以前のバージョンのStorageGRIDソフトウェアで使用されていた古いリソースが削除され、ユーザー インターフェイスが再び正しく動作するようになります。手順については、Web ブラウザのドキュメントを参照してください。





== 「Docker イメージの可用性チェック」エラー メッセージ

アップグレード プロセスを開始しようとすると、「Docker イメージの可用性チェック検証スイートによって次の問題が特定されました」というエラー メッセージが表示される場合があります。アップグレードを完了する前に、すべての問題を解決する必要があります。

特定された問題を解決するために必要な変更が不明な場合は、テクニカル サポートにお問い合わせください。

[cols="1a,1a,1a"]
|===
| メッセージ | 原因 | 解決策 


 a| 
アップグレードバージョンを判別できません。アップグレードバージョン情報ファイル `{file_path}`予期された形式と一致しませんでした。
 a| 
アップグレード パッケージが破損しています。
 a| 
アップグレード パッケージを再度アップロードして、再試行してください。問題が解決しない場合は、テクニカル サポートにお問い合わせください。



 a| 
アップグレードバージョン情報ファイル `{file_path}`見つかりませんでした。アップグレードバージョンを判別できません。
 a| 
アップグレード パッケージが破損しています。
 a| 
アップグレード パッケージを再度アップロードして、再試行してください。問題が解決しない場合は、テクニカル サポートにお問い合わせください。



 a| 
現在インストールされているリリースバージョンを判別できません `{node_name}`。
 a| 
ノード上の重要なファイルが破損しています。
 a| 
テクニカル サポートにお問い合わせください。



 a| 
バージョンの一覧を表示中に接続エラーが発生しました `{node_name}`
 a| 
ノードがオフラインであるか、接続が中断されました。
 a| 
すべてのノードがオンラインであり、プライマリ管理ノードからアクセス可能であることを確認して、再試行してください。



 a| 
ノードのホスト `{node_name}`StorageGRIDを持っていない `{upgrade_version}`画像が読み込まれました。アップグレードを続行する前に、イメージとサービスをホストにインストールする必要があります。
 a| 
アップグレード用の RPM または DEB パッケージが、ノードが実行されているホストにインストールされていないか、イメージがまだインポート中です。

*注:* このエラーは、Linux 上でコンテナとして実行されているノードにのみ適用されます。
 a| 
ノードが実行されているすべての Linux ホストに RPM または DEB パッケージがインストールされていることを確認します。サービスと画像ファイルの両方のバージョンが正しいことを確認してください。数分待ってから再試行してください。

見るlink:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux: すべてのホストにRPMまたはDEBパッケージをインストールする"] 。



 a| 
ノードのチェック中にエラーが発生しました `{node_name}`
 a| 
予期しないエラーが発生しました。
 a| 
数分待ってから再試行してください。



 a| 
事前チェックの実行中にキャッチされないエラーが発生しました。 `{error_string}`
 a| 
予期しないエラーが発生しました。
 a| 
数分待ってから再試行してください。

|===