---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 11.9 
summary: StorageGRIDのこのリリースでは、次の機能が導入されています。 
---
= StorageGRID 11.9の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDのこのリリースでは、次の機能と機能変更が導入されています。



== 拡張性



=== データ専用ストレージノード

よりきめ細かなスケーリングを可能にするために、以下をインストールできるようになりました。link:../primer/what-storage-node-is.html#types-of-storage-nodes["データ専用ストレージノード"] 。メタデータ処理が重要でない場合は、コスト効率よくインフラストラクチャを最適化できます。この柔軟性により、さまざまなワークロードと成長パターンに対応できるようになります。



== クラウド ストレージ プールの機能強化



=== IAMロールをどこでも

StorageGRIDは、以下の短期認証情報をサポートするようになりました。link:../ilm/creating-cloud-storage-pool.html["クラウド ストレージ プール用の Amazon S3 のあらゆる場所での IAM ロール"] 。

長期的な認証情報を使用して S3 バケットにアクセスすると、これらの認証情報が侵害された場合にセキュリティ上のリスクが生じます。短期認証情報は有効期間が限られているため、不正アクセスのリスクが軽減されます。



=== S3 オブジェクトロックバケット

これでlink:../ilm/creating-cloud-storage-pool.html["Amazon S3エンドポイントを使用してクラウドストレージプールを構成する"]。  S3 オブジェクト ロックは、オブジェクトの偶発的または悪意のある削除を防ぐのに役立ちます。  StorageGRIDから Amazon S3 にデータを階層化する場合、両方のシステムでオブジェクト ロックを有効にすると、データのライフサイクル全体にわたってデータ保護が強化されます。



== マルチテナンシー



=== バケットの制限

によるlink:../tenant/creating-s3-bucket.html["S3バケットの制限を設定する"]テナントによる容量の独占を防ぐことができます。さらに、制御されない成長は予期しないコストをもたらす可能性があります。制限を定義することで、テナントの保管費用をより正確に見積もることができます。



=== テナントあたり5,000バケット

拡張性を高めるために、 StorageGRIDは最大link:../s3/operations-on-buckets.html["テナントあたり 5,000 個の S3 バケット"]。各グリッドには最大 100,000 個のバケットを含めることができます。

5,000 個のバケットをサポートするには、グリッド内の各ストレージ ノードに少なくとも 64 GB の RAM が必要です。



== S3 オブジェクトロックの改善

テナントごとの構成機能により、柔軟性とデータ セキュリティの適切なバランスが実現します。テナントごとの保持設定を次のように構成できるようになりました。

* コンプライアンスモードを許可または禁止する
* 最大保存期間を設定する


参照:

* link:../ilm/managing-objects-with-s3-object-lock.html["S3 オブジェクトロックでオブジェクトを管理する"]
* link:../ilm/how-object-retention-is-determined.html#how-grid-administrators-control-object-retention["グリッド管理者がオブジェクトの保持を制御する方法"]
* link:../admin/creating-tenant-account.html["テナントアカウントを作成する"]




== S3互換性



=== x-amz-checksum-sha256 チェックサム

* S3 REST API は、link:../s3/operations-on-objects.html のサポートを提供するようになりました。[`x-amz-checksum-sha256` [チェックサム]。
* StorageGRID は、PUT、GET、HEAD 操作に対して SHA-256 チェックサムのサポートを提供するようになりました。これらのチェックサムはデータの整合性を強化します。




=== S3プロトコルサポートの変更

* Amazon S3 のマウントポイントのサポートが追加されました。これにより、アプリケーションはローカル ファイル システムであるかのように S3 バケットに直接接続できるようになります。より多くのアプリケーションとユースケースでStorageGRID を使用できるようになりました。
* マウントポイントのサポート追加の一環として、 StorageGRID 11.9には以下が含まれています。link:../s3/index.html#updates-to-rest-api-support["S3プロトコルサポートへの追加変更"] 。




== メンテナンスとサポート



=== AutoSupport

link:../admin/what-is-autosupport.html["AutoSupport"]レガシーアプライアンスのハードウェア障害ケースを自動的に作成できるようになりました。



=== 拡張ノードクローン操作

ノード クローンの使いやすさが拡張され、より大きなストレージ ノードをサポートするようになりました。



=== 期限切れの削除マーカーのILM処理の改善

期間が日数の ILM 取り込み時間ルールでは、期限切れのオブジェクト削除マーカーも削除されるようになりました。削除マーカーは、日数の期間が経過し、現在の削除マーカーの有効期限が切れた場合にのみ削除されます (現在のバージョン以外のバージョンはありません)。

参照link:../ilm/how-objects-are-deleted.html#delete-s3-versioned-objects["S3 バージョン管理オブジェクトの削除方法"]そしてlink:../ilm/example-8-priorities-for-s3-bucket-lifecycle-and-ilm-policy.html#example-of-bucket-lifecycle-taking-priority-over-ilm-policy["ILM ポリシーよりも優先されるバケット ライフサイクルの例"]。



=== ノードの廃止の改善

StorageGRID次世代ハードウェアへのスムーズで効率的な移行を実現するために、link:../maintain/grid-node-decommissioning.html["ノードの廃止"]改善されました。



=== ロードバランサエンドポイントの Syslog

ロード バランサーのエンドポイント アクセス ログには、HTTP ステータス コードなどのトラブルシューティング情報が含まれています。 StorageGRIDがサポートするようになりましたlink:../monitor/configure-audit-messages.html["これらのログを外部のsyslogサーバーにエクスポートする"]。この機能強化により、より効率的なログ管理と、既存の監視およびアラート システムとの統合が可能になります。



=== メンテナンスとサポート性をさらに強化

* メトリクスUIの更新
* 新しいオペレーティングシステムの資格
* 新しいサードパーティコンポーネントのサポート




== セキュリティ



=== SSHアクセスキーのローテーション

グリッド管理者は、link:../admin/change-ssh-access-passwords.html["SSHキーの更新とローテーション"] 。  SSH キーをローテーションする機能は、セキュリティのベストプラクティスであり、予防的な防御メカニズムです。



=== ルートログインのアラート

不明なエンティティがグリッドマネージャにルートとしてサインインすると、link:../monitor/alerts-reference.html["アラートが発動される"] 。ルート SSH ログインを監視することは、インフラストラクチャを保護するための積極的なステップです。



== グリッドマネージャーの機能強化



=== 消去コーディングプロファイルページが移動しました

イレージャー コーディング プロファイル ページは、*CONFIGURATION* > *System* > *Erasure coding* に移動されました。以前は ILM メニューにありました。



=== 検索機能の強化

そのlink:../primer/exploring-grid-manager.html#search-field["グリッドマネージャーの検索フィールド"]より優れたマッチング ロジックが組み込まれ、一般的な略語やページ内の特定の設定の名前を検索してページを見つけることができるようになりました。ノード、ユーザー、テナント アカウントなど、さらに多くの種類の項目を検索することもできます。
