---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: すべての Ubuntu または Debian グリッド ホストにStorageGRIDをインストールする必要があります。サポートされているバージョンの一覧については、 NetApp相互運用性マトリックス ツールを使用してください。 
---
= Linuxをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべての Ubuntu または Debian グリッド ホストにStorageGRIDをインストールする必要があります。サポートされているバージョンの一覧については、 NetApp相互運用性マトリックス ツールを使用してください。

.開始する前に
オペレーティング システムが、以下に示す StorageGRID の最小カーネル バージョン要件を満たしていることを確認してください。コマンドを使用する `uname -r`オペレーティング システムのカーネル バージョンを取得するには、または OS ベンダーに問い合わせてください。

*注:* Ubuntu バージョン 18.04 および 20.04 のサポートは廃止されており、将来のリリースでは削除される予定です。

[cols="1a,2a,3a"]
|===
| Ubuntuバージョン | 最小カーネルバージョン | カーネルパッケージ名 


 a| 
18.04.6（非推奨）
 a| 
5.4.0-150-ジェネリック
 a| 
linux-image-5.4.0-150-generic/bionic-updates、bionic-security、現在 5.4.0-150.167~18.04.1



 a| 
20.04.5（非推奨）
 a| 
5.4.0-131-ジェネリック
 a| 
linux-image-5.4.0-131-generic/focal-updates、現在は5.4.0-131.147



 a| 
22.04.1
 a| 
5.15.0-47-ジェネリック
 a| 
linux-image-5.15.0-47-generic/jammy-updates、jammy-security、現在 5.15.0-47.51



 a| 
24.04
 a| 
6.8.0-31-ジェネリック
 a| 
linux-image-6.8.0-31-generic/noble、現在は6.8.0-31.31

|===
*注:* Debian バージョン 11 のサポートは非推奨となっており、将来のリリースでは削除される予定です。

[cols="1a,2a,2a"]
|===
| Debianバージョン | 最小カーネルバージョン | カーネルパッケージ名 


 a| 
11（非推奨）
 a| 
5.10.0-18-amd64
 a| 
linux-image-5.10.0-18-amd64/stable、現在は5.10.150-1



 a| 
12
 a| 
6.1.0-9-amd64
 a| 
linux-image-6.1.0-9-amd64/stable、現在は6.1.27-1

|===
.手順
. ディストリビューターの指示または標準の手順に従って、すべての物理または仮想グリッド ホストに Linux をインストールします。
+

NOTE: グラフィカルデスクトップ環境をインストールしないでください。Ubuntu をインストールするときは、*標準システムユーティリティ*を選択する必要があります。Ubuntu ホストへの ssh アクセスを有効にするには、*OpenSSH サーバー* を選択することをお勧めします。その他のオプションはすべてオフのままにできます。

. すべてのホストが Ubuntu または Debian パッケージ リポジトリにアクセスできることを確認します。
. スワップが有効な場合:
+
.. 次のコマンドを実行します。 `$ sudo swapoff --all`
.. すべてのスワップエントリを削除します `/etc/fstab`設定を保持します。
+

NOTE: スワップを完全に無効にしないと、パフォーマンスが大幅に低下する可能性があります。




