---
permalink: ubuntu/understanding-apparmor-profile-installation.html 
sidebar: sidebar 
keywords: how to install AppArmor profile 
summary: 自己展開の Ubuntu 環境で操作し、AppArmor 強制アクセス制御システムを使用している場合、ベース システムにインストールするパッケージに関連付けられた AppArmor プロファイルが、 StorageGRIDでインストールされた対応するパッケージによってブロックされる可能性があります。 
---
= AppArmorプロファイルのインストールを理解する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自己展開の Ubuntu 環境で操作し、AppArmor 強制アクセス制御システムを使用している場合、ベース システムにインストールするパッケージに関連付けられた AppArmor プロファイルが、 StorageGRIDでインストールされた対応するパッケージによってブロックされる可能性があります。

デフォルトでは、基本オペレーティング システムにインストールするパッケージに対して AppArmor プロファイルがインストールされます。  StorageGRIDシステム コンテナからこれらのパッケージを実行すると、AppArmor プロファイルがブロックされます。  DHCP、MySQL、NTP、tcdump の基本パッケージは AppArmor と競合し、他の基本パッケージも競合する可能性があります。

AppArmor プロファイルを処理するには、次の 2 つの選択肢があります。

* StorageGRIDシステム コンテナ内のパッケージと重複する、ベース システムにインストールされたパッケージの個別のプロファイルを無効にします。個々のプロファイルを無効にすると、AppArmor が有効になっていることを示すエントリがStorageGRIDログ ファイルに表示されます。
+
次のコマンドを使用します。

+
[listing]
----
sudo ln -s /etc/apparmor.d/<profile.name> /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/<profile.name>
----
+
*例：*

+
[listing]
----
sudo ln -s /etc/apparmor.d/bin.ping /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/bin.ping
----
* AppArmor を完全に無効にします。 Ubuntu 9.10 以降の場合は、Ubuntu オンライン コミュニティの指示に従ってください。 https://help.ubuntu.com/community/AppArmor#Disable_AppArmor_framework["AppArmorを無効にする"^] 。新しいバージョンの Ubuntu では、AppArmor を完全に無効にすることはできない可能性があります。
+
AppArmor を無効にすると、 StorageGRIDログ ファイルに AppArmor が有効であることを示すエントリが表示されなくなります。


