---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: Hardening guidelines, upgrades 
summary: 攻撃から身を守るには、 StorageGRIDシステムと関連サービスを最新の状態に保つ必要があります。 
---
= ソフトウェアアップグレードの強化ガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
攻撃から身を守るには、 StorageGRIDシステムと関連サービスを最新の状態に保つ必要があります。



== StorageGRIDソフトウェアへのアップグレード

可能な限り、 StorageGRIDソフトウェアを最新のメジャー リリースまたは以前のメジャー リリースにアップグレードする必要があります。 StorageGRID を最新の状態に保つことで、既知の脆弱性がアクティブになっている時間を短縮し、全体的な攻撃対象領域を減らすことができます。さらに、 StorageGRIDの最新リリースには、以前のリリースには含まれていなかったセキュリティ強化機能が含まれていることがよくあります。

ご相談ください https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool"^](IMT) を使用して、使用する必要があるStorageGRIDソフトウェアのバージョンを決定します。ホットフィックスが必要になった場合、NetAppは最新リリースに対するアップデートの作成を優先します。一部のパッチは以前のリリースと互換性がない可能性があります。

* 最新のStorageGRIDリリースとホットフィックスをダウンロードするには、 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetAppのダウンロード：StorageGRID"^] 。
* StorageGRIDソフトウェアをアップグレードするには、link:../upgrade/performing-upgrade.html["アップグレード手順"] 。
* 修正プログラムを適用するには、link:../maintain/storagegrid-hotfix-procedure.html["StorageGRIDホットフィックス手順"] 。




== 外部サービスへのアップグレード

外部サービスには、 StorageGRID に間接的に影響を及ぼす脆弱性が存在する可能性があります。StorageGRIDが依存するサービスが最新の状態に保たれていることを確認する必要があります。これらのサービスには、LDAP、KMS (または KMIP サーバー)、DNS、NTP が含まれます。

サポートされているバージョンのリストについては、 https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool"^] 。



== ハイパーバイザーのアップグレード

StorageGRIDノードが VMware または別のハイパーバイザー上で実行されている場合は、ハイパーバイザーのソフトウェアとファームウェアが最新であることを確認する必要があります。

サポートされているバージョンのリストについては、 https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool"^] 。



== *Linuxノードへのアップグレード*

StorageGRIDノードが Linux ホスト プラットフォームを使用している場合は、セキュリティ更新とカーネル更新がホスト OS に適用されていることを確認する必要があります。さらに、ファームウェアのアップデートが利用可能になったら、脆弱なハードウェアにアップデートを適用する必要があります。

サポートされているバージョンのリストについては、 https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool"^] 。
