---
permalink: harden/index.html 
sidebar: sidebar 
keywords: Hardening guidelines, system, security 
summary: システム強化は、 StorageGRIDシステムから可能な限り多くのセキュリティ リスクを排除するプロセスです。 
---
= システム強化に関する一般的な考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システム強化は、 StorageGRIDシステムから可能な限り多くのセキュリティ リスクを排除するプロセスです。

StorageGRIDをインストールして構成するときには、機密性、整合性、可用性に関する規定のセキュリティ目標を満たすために、これらのガイドラインを使用してください。

システム強化については、すでに業界標準のベスト プラクティスを使用しているはずです。たとえば、 StorageGRIDには強力なパスワードを使用し、HTTP ではなく HTTPS を使用し、可能な場合は証明書ベースの認証を有効にします。

StorageGRIDは https://security.netapp.com/policy/["NetApp脆弱性対応ポリシー"^]。報告された脆弱性は、製品のセキュリティ インシデント対応プロセスに従って検証され、対処されます。

StorageGRIDシステムを強化する場合は、次の点を考慮してください。

* *3 つのStorageGRIDネットワークのうちどれを実装しましたか*。すべてのStorageGRIDシステムはグリッド ネットワークを使用する必要がありますが、管理ネットワーク、クライアント ネットワーク、またはその両方を使用することもできます。ネットワークごとにセキュリティに関する考慮事項が異なります。
* StorageGRIDシステム内の個々のノードに使用する *プラットフォームの種類*。 StorageGRIDノードは、VMware 仮想マシン、Linux ホスト上のコンテナ エンジン内、または専用のハードウェア アプライアンスとして展開できます。各タイプのプラットフォームには、独自の強化ベスト プラクティスがあります。
* *テナント アカウントの信頼性*。信頼されていないテナント アカウントを持つサービス プロバイダーの場合、信頼できる社内テナントのみを使用する場合とは異なるセキュリティ上の懸念が生じます。
* *組織が従うセキュリティ要件と規則*。特定の規制または企業の要件に準拠する必要がある場合があります。

