---
permalink: network/external-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, external communications, ports, TCP, UDP, client communications 
summary: クライアントは、コンテンツを取り込んで取得するためにグリッド ノードと通信する必要があります。使用されるポートは、選択したオブジェクト ストレージ プロトコルによって異なります。これらのポートはクライアントからアクセスできる必要があります。 
---
= 外部コミュニケーション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クライアントは、コンテンツを取り込んで取得するためにグリッド ノードと通信する必要があります。使用されるポートは、選択したオブジェクト ストレージ プロトコルによって異なります。これらのポートはクライアントからアクセスできる必要があります。



== 港へのアクセス制限

企業のネットワーク ポリシーによっていずれかのポートへのアクセスが制限されている場合は、次のいずれかを実行できます。

* 使用link:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイント"]ユーザー定義のポートでのアクセスを許可します。
* ノードをデプロイするときにポートを再マップします。ただし、ロード バランサーのエンドポイントを再マップしないでください。  StorageGRIDノードのポート再マッピングに関する情報を参照してください。
+
** link:../rhel/creating-node-configuration-files.html#port-remap-keys["Red Hat Enterprise Linux 上のStorageGRIDのポート再マップ キー"]
** link:../ubuntu/creating-node-configuration-files.html#port-remap-keys["Ubuntu または Debian 上のStorageGRIDのポート再マップ キー"]
** link:../vmware/deploying-storagegrid-node-as-virtual-machine.html#vmware-remap-ports["VMware 上のStorageGRIDのポートの再マップ"]
** https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-remapping-network-ports-for-appliance.html["オプション: アプライアンスのネットワークポートを再マップする"^]






== 外部通信に使用されるポート

次の表は、ノードへのトラフィックに使用されるポートを示しています。


NOTE: このリストには、次のように設定される可能性のあるポートは含まれていません。link:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイント"] 。

[cols="1a,1a,1a,1a,1a,4a"]
|===
| ポート | TCPまたはUDP | プロトコル | から | に | 詳細 


 a| 
22
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
すべてのノード
 a| 
コンソール ステップを含む手順では、SSH またはコンソール アクセスが必要です。オプションで、ポート 22 の代わりにポート 2022 を使用することもできます。



 a| 
25
 a| 
TCP
 a| 
SMTP
 a| 
管理ノード
 a| 
メールサーバー
 a| 
アラートおよび電子メールベースのAutoSupportに使用されます。  「電子メール サーバー」ページを使用して、デフォルトのポート設定 25 を上書きできます。



 a| 
53
 a| 
TCP/UDP
 a| 
DNS
 a| 
すべてのノード
 a| 
DNSサーバ
 a| 
DNS に使用されます。



 a| 
67
 a| 
UDP
 a| 
DHCP
 a| 
すべてのノード
 a| 
DHCPサービス
 a| 
オプションで、DHCP ベースのネットワーク構成をサポートするために使用されます。静的に構成されたグリッドでは、dhclient サービスは実行されません。



 a| 
68
 a| 
UDP
 a| 
DHCP
 a| 
DHCPサービス
 a| 
すべてのノード
 a| 
オプションで、DHCP ベースのネットワーク構成をサポートするために使用されます。静的 IP アドレスを使用するグリッドでは、dhclient サービスは実行されません。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ブラウザ
 a| 
管理ノード
 a| 
ポート 80 は、管理ノード ユーザー インターフェイスのポート 443 にリダイレクトされます。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ブラウザ
 a| 
家電製品
 a| 
ポート 80 は、 StorageGRIDアプライアンス インストーラのポート 8443 にリダイレクトされます。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ADC 搭載ストレージノード
 a| 
AWS
 a| 
HTTP を使用する AWS またはその他の外部サービスに送信されるプラットフォーム サービス メッセージに使用されます。テナントは、エンドポイントを作成するときに、デフォルトの HTTP ポート設定 80 を上書きできます。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ストレージ ノード
 a| 
AWS
 a| 
HTTP を使用する AWS ターゲットに送信される Cloud Storage Pools リクエスト。グリッド管理者は、クラウド ストレージ プールを構成するときに、デフォルトの HTTP ポート設定 80 を上書きできます。



 a| 
111
 a| 
TCP/UDP
 a| 
RPCバインド
 a| 
NFSクライアント
 a| 
管理ノード
 a| 
NFS ベースの監査エクスポート (ポートマップ) で使用されます。

*注:* このポートは、NFS ベースの監査エクスポートが有効になっている場合にのみ必要です。

*注:* NFS のサポートは非推奨となっており、将来のリリースでは削除される予定です。



 a| 
123
 a| 
UDP
 a| 
NTP
 a| 
プライマリNTPノード
 a| 
外部NTP
 a| 
ネットワーク タイム プロトコル サービス。プライマリ NTP ソースとして選択されたノードは、外部 NTP タイム ソースとクロック時刻も同期します。



 a| 
161
 a| 
TCP/UDP
 a| 
SNMP
 a| 
SNMPクライアント
 a| 
すべてのノード
 a| 
SNMP ポーリングに使用されます。すべてのノードは基本情報を提供します。管理ノードはアラート データも提供します。設定するとデフォルトで UDP ポート 161 になります。

*注:* このポートは必須であり、SNMP が構成されている場合にのみノード ファイアウォールで開かれます。  SNMP を使用する予定の場合は、代替ポートを設定できます。

*注:* StorageGRIDでの SNMP の使用については、 NetApp のアカウント担当者にお問い合わせください。



 a| 
162
 a| 
TCP/UDP
 a| 
SNMP通知
 a| 
すべてのノード
 a| 
通知先
 a| 
送信 SNMP 通知とトラップはデフォルトで UDP ポート 162 に設定されます。

*注:* このポートは、SNMP が有効になっていて、通知先が設定されている場合にのみ必要です。  SNMP を使用する予定の場合は、代替ポートを設定できます。

*注:* StorageGRIDでの SNMP の使用については、 NetApp のアカウント担当者にお問い合わせください。



 a| 
389
 a| 
TCP/UDP
 a| 
LDAP
 a| 
ADC 搭載ストレージノード
 a| 
アクティブディレクトリ/LDAP
 a| 
Identity Federation の Active Directory または LDAP サーバーに接続するために使用されます。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
ブラウザ
 a| 
管理ノード
 a| 
グリッド マネージャーおよびテナント マネージャーにアクセスするために、Web ブラウザーおよび管理 API クライアントによって使用されます。

*注意*: Grid Manager ポート 443 または 8443 を閉じると、ブロックされたポートに現在接続しているすべてのユーザー (自分を含む) は、その IP アドレスが特権アドレス リストに追加されていない限り、Grid Manager にアクセスできなくなります。見るlink:../admin/configure-firewall-controls.html["ファイアウォール制御を構成する"]特権 IP アドレスを構成します。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
管理ノード
 a| 
Active Directory
 a| 
シングル サインオン (SSO) が有効な場合に、Active Directory に接続する管理ノードによって使用されます。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
ADC 搭載ストレージノード
 a| 
AWS
 a| 
HTTPS を使用する AWS またはその他の外部サービスに送信されるプラットフォーム サービス メッセージに使用されます。テナントは、エンドポイントを作成するときに、デフォルトの HTTP ポート設定 443 を上書きできます。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
ストレージ ノード
 a| 
AWS
 a| 
HTTPS を使用する AWS ターゲットに送信される Cloud Storage Pools リクエスト。グリッド管理者は、クラウド ストレージ プールを構成するときに、デフォルトの HTTPS ポート設定 443 を上書きできます。



 a| 
903
 a| 
TCP
 a| 
NFS
 a| 
NFSクライアント
 a| 
管理ノード
 a| 
NFSベースの監査エクスポートで使用される(`rpc.mountd`）。

*注:* このポートは、NFS ベースの監査エクスポートが有効になっている場合にのみ必要です。

*注:* NFS のサポートは非推奨となっており、将来のリリースでは削除される予定です。



 a| 
2022
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
すべてのノード
 a| 
コンソール ステップを含む手順では、SSH またはコンソール アクセスが必要です。オプションで、ポート 2022 の代わりにポート 22 を使用することもできます。



 a| 
2049
 a| 
TCP
 a| 
NFS
 a| 
NFSクライアント
 a| 
管理ノード
 a| 
NFS ベースの監査エクスポート (nfs) で使用されます。

*注:* このポートは、NFS ベースの監査エクスポートが有効になっている場合にのみ必要です。

*注:* NFS のサポートは非推奨となっており、将来のリリースでは削除される予定です。



 a| 
5353
 a| 
UDP
 a| 
mDNS
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
インストール、拡張、およびリカバリ中のフルグリッド IP の変更とプライマリ管理ノードの検出に使用されるマルチキャスト DNS (mDNS) サービスを提供します。



 a| 
5696
 a| 
TCP
 a| 
KMIP
 a| 
アプライアンス
 a| 
キオスク
 a| 
StorageGRIDアプライアンス インストーラの KMS 構成ページで別のポートが指定されていない限り、ノード暗号化用に構成されたアプライアンスからキー管理サーバ (KMS) へのキー管理相互運用性プロトコル (KMIP) 外部トラフィック。



 a| 
8022
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
すべてのノード
 a| 
ポート 8022 の SSH は、サポートとトラブルシューティングのために、アプライアンスおよび仮想ノード プラットフォーム上の基本オペレーティング システムへのアクセスを許可します。このポートは Linux ベース (ベアメタル) ノードでは使用されず、グリッド ノード間または通常の操作中にアクセスできる必要はありません。



 a| 
8443
 a| 
TCP
 a| 
HTTPS
 a| 
ブラウザ
 a| 
管理ノード
 a| 
オプション。グリッド マネージャーにアクセスするために Web ブラウザーおよび管理 API クライアントによって使用されます。  Grid Manager と Tenant Manager の通信を分離するために使用できます。

*注意*: Grid Manager ポート 443 または 8443 を閉じると、ブロックされたポートに現在接続しているすべてのユーザー (自分を含む) は、その IP アドレスが特権アドレス リストに追加されていない限り、Grid Manager にアクセスできなくなります。見るlink:../admin/configure-firewall-controls.html["ファイアウォール制御を構成する"]特権 IP アドレスを構成します。



 a| 
9022
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
家電製品
 a| 
サポートとトラブルシューティングのために、事前構成モードでStorageGRIDアプライアンスへのアクセスを許可します。このポートは、グリッド ノード間または通常の操作中にアクセスできる必要はありません。



 a| 
9091
 a| 
TCP
 a| 
HTTPS
 a| 
外部Grafanaサービス
 a| 
管理ノード
 a| 
StorageGRID Prometheus サービスへの安全なアクセスのために外部 Grafana サービスによって使用されます。

*注:* このポートは、証明書ベースの Prometheus アクセスが有効になっている場合にのみ必要です。



 a| 
9092
 a| 
TCP
 a| 
カフカ
 a| 
ADC 搭載ストレージノード
 a| 
Kafka クラスター
 a| 
Kafka クラスターに送信されるプラットフォーム サービス メッセージに使用されます。テナントは、エンドポイントを作成するときに、デフォルトの Kafka ポート設定 9092 を上書きできます。



 a| 
9443
 a| 
TCP
 a| 
HTTPS
 a| 
ブラウザ
 a| 
管理ノード
 a| 
オプション。  Web ブラウザおよび管理 API クライアントがテナント マネージャにアクセスするために使用します。  Grid Manager と Tenant Manager の通信を分離するために使用できます。



 a| 
18082
 a| 
TCP
 a| 
HTTPS
 a| 
S3クライアント
 a| 
ストレージ ノード
 a| 
S3 クライアント トラフィックをストレージ ノードに直接送信します (HTTPS)。



 a| 
18083
 a| 
TCP
 a| 
HTTPS
 a| 
Swiftクライアント
 a| 
ストレージ ノード
 a| 
Swift クライアント トラフィックをストレージ ノードに直接送信します (HTTPS)。



 a| 
18084
 a| 
TCP
 a| 
HTTP
 a| 
S3クライアント
 a| 
ストレージ ノード
 a| 
S3 クライアント トラフィックをストレージ ノードに直接送信します (HTTP)。



 a| 
18085
 a| 
TCP
 a| 
HTTP
 a| 
Swiftクライアント
 a| 
ストレージ ノード
 a| 
Swift クライアント トラフィックをストレージ ノードに直接送信します (HTTP)。



 a| 
23000-23999
 a| 
TCP
 a| 
HTTPS
 a| 
クロスグリッドレプリケーションのソースグリッド上のすべてのノード
 a| 
クロスグリッドレプリケーションの宛先グリッド上の管理ノードとゲートウェイノード
 a| 
この範囲のポートは、グリッド フェデレーション接続用に予約されています。特定の接続の両方のグリッドは同じポートを使用します。

|===