---
permalink: network/general-networking-requirements.html 
sidebar: sidebar 
keywords: networking requirements, storagegrid networks 
summary: すべてのStorageGRIDデプロイメントは、次の接続をサポートできる必要があります。 
---
= 一般的なネットワーク要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべてのStorageGRIDデプロイメントは、次の接続をサポートできる必要があります。

これらの接続は、ネットワーク トポロジの例に示されているように、グリッド ネットワーク、管理ネットワーク、またはクライアント ネットワーク、あるいはこれらのネットワークの組み合わせを介して行われます。

* *管理接続*: 通常は SSH を介して、管理者からノードへの受信接続。  Grid Manager、Tenant Manager、 StorageGRID Appliance Installer への Web ブラウザ アクセス。
* *NTP サーバー接続*: 着信 UDP 応答を受信する発信 UDP 接続。
+
プライマリ管理ノードから少なくとも 1 つの NTP サーバーにアクセスできる必要があります。

* *DNS サーバー接続*: 着信 UDP 応答を受信する発信 UDP 接続。
* *LDAP/Active Directory サーバー接続*: ストレージ ノード上の Identity サービスからの送信 TCP 接続。
* * AutoSupport*: 管理ノードから次のいずれかへのアウトバウンドTCP接続 `support.netapp.com`または顧客が設定したプロキシ。
* *外部キー管理サーバー*: ノード暗号化が有効になっている各アプライアンス ノードからの送信 TCP 接続。
* S3 クライアントからの受信 TCP 接続。
* CloudMirror レプリケーションなどのStorageGRIDプラットフォーム サービスまたは Cloud Storage Pools からの送信要求。


StorageGRID は、デフォルトのルーティング ルールを使用してプロビジョニングされた NTP サーバーまたは DNS サーバーのいずれにも接続できない場合、DNS サーバーおよび NTP サーバーの IP アドレスが指定されている限り、すべてのネットワーク (グリッド、管理、およびクライアント) への接続を自動的に試行します。どのネットワーク上でも NTP サーバーまたは DNS サーバーにアクセスできる場合、 StorageGRID は追加のルーティング ルールを自動的に作成し、今後のすべての接続試行でそのネットワークが使用されるようにします。


TIP: 自動的に検出されたホスト ルートを使用することもできますが、通常は、自動検出が失敗した場合に備えて接続を確保するために、DNS ルートと NTP ルートを手動で構成する必要があります。

デプロイメント中にオプションの管理ネットワークとクライアント ネットワークを構成する準備ができていない場合、構成手順中にグリッド ノードを承認するときにこれらのネットワークを構成できます。さらに、インストールが完了した後でも、IP変更ツール（link:../maintain/configuring-ip-addresses.html["IPアドレスを設定する"] ）。



== 管理ノードとゲートウェイノードの接続

管理ノードは、オープンインターネット上のクライアントなどの信頼できないクライアントから常に保護される必要があります。信頼できないクライアントがグリッド ネットワーク、管理ネットワーク、またはクライアント ネットワーク上の管理ノードにアクセスできないようにする必要があります。

高可用性グループに追加する予定の管理ノードとゲートウェイ ノードは、静的 IP アドレスを使用して構成する必要があります。見るlink:../admin/managing-high-availability-groups.html["高可用性グループの管理"] 。



== ネットワークアドレス変換（NAT）の使用

グリッド ノード間またはStorageGRIDサイト間のグリッド ネットワークでは、ネットワーク アドレス変換 (NAT) を使用しないでください。グリッド ネットワークにプライベート IPv4 アドレスを使用する場合、それらのアドレスはすべてのサイトのすべてのグリッド ノードから直接ルーティング可能である必要があります。ただし、必要に応じて、ゲートウェイ ノードにパブリック IP アドレスを提供する場合など、外部クライアントとグリッド ノード間で NAT を使用できます。  NAT を使用してパブリック ネットワーク セグメントをブリッジすることは、グリッド内のすべてのノードに対して透過的なトンネリング アプリケーションを使用する場合にのみサポートされます。つまり、グリッド ノードはパブリック IP アドレスを認識する必要はありません。
