---
permalink: network/internal-grid-node-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, internal communications, ports, TCP, UDP, grid communications, port 
summary: 'StorageGRID内部ファイアウォールは、ポート 22、80、123、および 443 を除く、グリッド ネットワーク上の特定のポートへの着信接続のみを許可します (外部通信に関する情報を参照)。接続は、ロード バランサーのエンドポイントによって定義されたポートでも受け入れられます。' 
---
= 内部でのGridノードの通信
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID内部ファイアウォールは、グリッド ネットワーク上の特定のポートへの着信接続を許可します。接続は、ロード バランサーのエンドポイントによって定義されたポートでも受け入れられます。


NOTE: NetApp、グリッド ノード間のインターネット制御メッセージ プロトコル (ICMP) トラフィックを有効にすることを推奨しています。  ICMP トラフィックを許可すると、グリッド ノードに到達できない場合のフェイルオーバー パフォーマンスが向上します。

ICMP と表に記載されているポートに加えて、 StorageGRID は仮想ルータ冗長プロトコル (VRRP) を使用します。  VRRP は、IP プロトコル番号 112 を使用するインターネット プロトコルです。  StorageGRID は、ユニキャスト モードでのみ VRRP を使用します。  VRRPは次の場合にのみ必要です。link:../admin/managing-high-availability-groups.html["高可用性グループ"]設定されています。



== Linuxベースのノードのガイドライン

エンタープライズ ネットワーク ポリシーによってこれらのポートへのアクセスが制限されている場合は、デプロイメント構成パラメータを使用してデプロイメント時にポートを再マップできます。ポートの再マッピングとデプロイメント構成パラメータの詳細については、以下を参照してください。

* link:../rhel/index.html["Red Hat Enterprise LinuxにStorageGRIDをインストールする"]
* link:../ubuntu/index.html["UbuntuまたはDebianにStorageGRIDをインストールする"]




== VMwareベースのノードのガイドライン

VMware ネットワーク外部のファイアウォール制限を定義する必要がある場合にのみ、次のポートを構成します。

エンタープライズ ネットワーク ポリシーによってこれらのポートへのアクセスが制限されている場合は、VMware vSphere Web Client を使用してノードを展開するときにポートを再マップするか、グリッド ノードの展開を自動化するときに構成ファイル設定を使用できます。ポートの再マッピングとデプロイメント構成パラメータの詳細については、以下を参照してください。link:../vmware/index.html["VMwareにStorageGRIDをインストールする"] 。



== アプライアンスノードのガイドライン

企業のネットワーク ポリシーによってこれらのポートへのアクセスが制限されている場合は、 StorageGRIDアプライアンス インストーラを使用してポートを再マップできます。見る https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-remapping-network-ports-for-appliance.html["オプション: アプライアンスのネットワークポートを再マップする"^]。



== StorageGRID内部ポート

[cols="1a,1a,1a,1a,4a"]
|===
| ポート | TCPまたはUDP | から | に | 詳細 


 a| 
22
 a| 
TCP
 a| 
プライマリ管理ノード
 a| 
すべてのノード
 a| 
メンテナンス手順では、プライマリ管理ノードはポート 22 で SSH を使用して他のすべてのノードと通信できる必要があります。他のノードからの SSH トラフィックを許可するかどうかはオプションです。



 a| 
80
 a| 
TCP
 a| 
家電製品
 a| 
プライマリ管理ノード
 a| 
StorageGRIDアプライアンスがプライマリ管理ノードと通信してインストールを開始するために使用されます。



 a| 
123
 a| 
UDP
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
ネットワーク タイム プロトコル サービス。各ノードは NTP を使用して他のすべてのノードと時刻を同期します。



 a| 
443
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストールやその他のメンテナンス手順中にプライマリ管理ノードにステータスを伝達するために使用されます。



 a| 
1055
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストール、拡張、回復、およびその他の保守手順のための内部トラフィック。



 a| 
1139
 a| 
TCP
 a| 
ストレージ ノード
 a| 
ストレージ ノード
 a| 
ストレージ ノード間の内部トラフィック。



 a| 
1501
 a| 
TCP
 a| 
すべてのノード
 a| 
ADC 搭載ストレージノード
 a| 
内部トラフィックのレポート、監査、および構成。



 a| 
1502
 a| 
TCP
 a| 
すべてのノード
 a| 
ストレージ ノード
 a| 
S3 および Swift 関連の内部トラフィック。



 a| 
1504
 a| 
TCP
 a| 
すべてのノード
 a| 
管理ノード
 a| 
NMS サービスのレポートと構成の内部トラフィック。



 a| 
1505
 a| 
TCP
 a| 
すべてのノード
 a| 
管理ノード
 a| 
AMS サービスの内部トラフィック。



 a| 
1506
 a| 
TCP
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
サーバーステータスの内部トラフィック。



 a| 
1507
 a| 
TCP
 a| 
すべてのノード
 a| 
ゲートウェイノード
 a| 
ロードバランサーの内部トラフィック。



 a| 
1508
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
構成管理の内部トラフィック。



 a| 
1511
 a| 
TCP
 a| 
すべてのノード
 a| 
ストレージ ノード
 a| 
メタデータの内部トラフィック。



 a| 
7001
 a| 
TCP
 a| 
ストレージ ノード
 a| 
ストレージ ノード
 a| 
Cassandra TLS ノード間クラスター通信。



 a| 
7443
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストール、拡張、回復、その他の保守手順、およびエラー レポートのための内部トラフィック。



 a| 
8011
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストール、拡張、回復、およびその他の保守手順のための内部トラフィック。



 a| 
8443
 a| 
TCP
 a| 
プライマリ管理ノード
 a| 
アプライアンスノード
 a| 
メンテナンス モード手順に関連する内部トラフィック。



 a| 
9042
 a| 
TCP
 a| 
ストレージ ノード
 a| 
ストレージ ノード
 a| 
Cassandra クライアント ポート。



 a| 
9999
 a| 
TCP
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
複数のサービスの内部トラフィック。メンテナンス手順、メトリック、ネットワークの更新が含まれます。



 a| 
10226
 a| 
TCP
 a| 
ストレージ ノード
 a| 
プライマリ管理ノード
 a| 
StorageGRIDアプライアンスによって、E シリーズSANtricity System Manager からプライマリ管理ノードにAutoSupportパッケージを転送するために使用されます。



 a| 
10342
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストール、拡張、回復、およびその他の保守手順のための内部トラフィック。



 a| 
18000
 a| 
TCP
 a| 
管理/ストレージノード
 a| 
ADC 搭載ストレージノード
 a| 
アカウント サービスの内部トラフィック。



 a| 
18001
 a| 
TCP
 a| 
管理/ストレージノード
 a| 
ADC 搭載ストレージノード
 a| 
アイデンティティ フェデレーションの内部トラフィック。



 a| 
18002
 a| 
TCP
 a| 
管理/ストレージノード
 a| 
ストレージ ノード
 a| 
オブジェクト プロトコルに関連する内部 API トラフィック。



 a| 
18003
 a| 
TCP
 a| 
管理/ストレージノード
 a| 
ADC 搭載ストレージノード
 a| 
プラットフォームは内部トラフィックをサービスします。



 a| 
18017
 a| 
TCP
 a| 
管理/ストレージノード
 a| 
ストレージ ノード
 a| 
Cloud Storage Pools の Data Mover サービスの内部トラフィック。



 a| 
18019
 a| 
TCP
 a| 
ストレージ ノード
 a| 
ストレージ ノード
 a| 
消失訂正符号化のためのチャンク サービス内部トラフィック。



 a| 
18082
 a| 
TCP
 a| 
管理/ストレージノード
 a| 
ストレージ ノード
 a| 
S3 関連の内部トラフィック。



 a| 
18083
 a| 
TCP
 a| 
すべてのノード
 a| 
ストレージ ノード
 a| 
Swift 関連の内部トラフィック。



 a| 
18086
 a| 
TCP
 a| 
すべてのグリッドノード
 a| 
すべてのストレージノード
 a| 
LDR サービスに関連する内部トラフィック。



 a| 
18200
 a| 
TCP
 a| 
管理/ストレージノード
 a| 
ストレージ ノード
 a| 
クライアント要求に関する追加の統計。



 a| 
19000
 a| 
TCP
 a| 
管理/ストレージノード
 a| 
ADC 搭載ストレージノード
 a| 
Keystoneサービスの内部トラフィック。

|===
.関連情報
link:external-communications.html["外部コミュニケーション"]
