---
permalink: network/linux-deployments.html 
sidebar: sidebar 
keywords: linux network, container engine, red hat enterprise linux rhel network, ubuntu network 
summary: 効率性、信頼性、セキュリティを実現するために、 StorageGRIDシステムはコンテナ エンジンのコレクションとして Linux 上で実行されます。  StorageGRIDシステムでは、コンテナ エンジン関連のネットワーク構成は必要ありません。 
---
= Linux の展開
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
効率性、信頼性、セキュリティを実現するために、 StorageGRIDシステムはコンテナ エンジンのコレクションとして Linux 上で実行されます。  StorageGRIDシステムでは、コンテナ エンジン関連のネットワーク構成は必要ありません。

コンテナ ネットワーク インターフェイスには、VLAN または仮想イーサネット (veth) ペアなどの非結合デバイスを使用します。ノード構成ファイルでこのデバイスをネットワーク インターフェイスとして指定します。


CAUTION: ボンドまたはブリッジデバイスをコンテナネットワークインターフェースとして直接使用しないでください。これを行うと、コンテナ名前空間内のボンドおよびブリッジデバイスで macvlan を使用する際のカーネルの問題により、ノードの起動が妨げられる可能性があります。

インストール手順については、link:../rhel/index.html["Red Hat Enterprise Linux"]またはlink:../ubuntu/index.html["UbuntuまたはDebian"]デプロイメント。



== コンテナ エンジン デプロイメントのホスト ネットワーク構成

コンテナ エンジン プラットフォームでStorageGRID の展開を開始する前に、各ノードが使用するネットワーク (グリッド、管理、クライアント) を決定します。各ノードのネットワーク インターフェイスが正しい仮想または物理ホスト インターフェイス上に構成され、各ネットワークに十分な帯域幅があることを確認する必要があります。



=== 物理ホスト

グリッド ノードをサポートするために物理ホストを使用している場合:

* すべてのホストが各ノード インターフェイスに対して同じホスト インターフェイスを使用していることを確認します。この戦略により、ホスト構成が簡素化され、将来のノード移行が可能になります。
* 物理ホスト自体の IP アドレスを取得します。
+

NOTE: ホスト上の物理インターフェースは、ホスト自体と、ホスト上で実行されている 1 つ以上のノードによって使用できます。このインターフェースを使用してホストまたはノードに割り当てられる IP アドレスはすべて一意である必要があります。ホストとノードは IP アドレスを共有できません。

* ホストに必要なポートを開きます。
* StorageGRIDで VLAN インターフェイスを使用する場合は、必要な VLAN へのアクセスを提供する 1 つ以上のトランク インターフェイスがホストに必要です。これらのインターフェースは、eth0、eth2、または追加インターフェースとしてノード コンテナに渡すことができます。トランクまたはアクセス インターフェイスを追加するには、次を参照してください。
+
** *RHEL (ノードをインストールする前)*:link:../rhel/creating-node-configuration-files.html["ノード構成ファイルを作成する"]
** *Ubuntu または Debian (ノードをインストールする前)*:link:../ubuntu/creating-node-configuration-files.html["ノード構成ファイルを作成する"]
** *RHEL、Ubuntu、または Debian (ノードをインストールした後)*:link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux: ノードにトランクまたはアクセスインターフェースを追加する"]






=== 最小帯域幅の推奨事項

次の表は、 StorageGRIDノードのタイプとネットワークのタイプごとに、最小 LAN 帯域幅の推奨事項を示しています。各物理ホストまたは仮想ホストに、そのホストで実行する予定のStorageGRIDノードの合計数と合計タイプに対する最小帯域幅要件を満たすのに十分なネットワーク帯域幅をプロビジョニングする必要があります。

[cols="1a,1a,1a,1a"]
|===
| ノードの種類 3+| ネットワークの種類 


 a| 
 a| 
Grid
 a| 
管理者
 a| 
クライアント



 a| 
 a| 
*最小LAN帯域幅*



 a| 
管理者
 a| 
10Gbps
 a| 
1Gbps
 a| 
1Gbps



 a| 
ゲートウェイ
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps



 a| 
ストレージ
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps



 a| 
アーカイブ
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps

|===

NOTE: この表には、共有ストレージへのアクセスに必要な SAN 帯域幅は含まれていません。イーサネット (iSCSI または FCoE) 経由でアクセスされる共有ストレージを使用している場合は、十分な SAN 帯域幅を提供するために、各ホストに個別の物理インターフェイスをプロビジョニングする必要があります。ボトルネックの発生を回避するには、特定のホストの SAN 帯域幅が、そのホストで実行されているすべてのストレージ ノードの合計ストレージ ノード ネットワーク帯域幅とほぼ一致する必要があります。

この表を使用して、各ホストで実行する予定のStorageGRIDノードの数とタイプに基づいて、各ホストでプロビジョニングするネットワーク インターフェイスの最小数を決定します。

たとえば、単一のホストで 1 つの管理ノード、1 つのゲートウェイ ノード、および 1 つのストレージ ノードを実行するには、次のようにします。

* 管理ノードでグリッドネットワークと管理ネットワークを接続する（10 + 1 = 11 Gbps が必要）
* ゲートウェイノードでグリッドとクライアントネットワークを接続する（10 + 10 = 20 Gbps が必要）
* ストレージノード上のグリッドネットワークを接続する（10 Gbps が必要）


このシナリオでは、少なくとも 11 + 20 + 10 = 41 Gbps のネットワーク帯域幅を提供する必要があります。これは、2 つの 40 Gbps インターフェイスまたは 5 つの 10 Gbps インターフェイスで対応でき、トランクとして集約され、ホストを含む物理データセンターのローカルのグリッド、管理、およびクライアント サブネットを伝送する 3 つ以上の VLAN で共有される可能性があります。

StorageGRID の導入に備えて、 StorageGRIDクラスタ内のホスト上の物理リソースとネットワーク リソースを構成するための推奨方法については、以下を参照してください。

* link:../rhel/configuring-host-network.html["ホストネットワークを構成する (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html["ホストネットワークを構成する（UbuntuまたはDebian）"]

