---
permalink: network/network-installation-and-provisioning.html 
sidebar: sidebar 
keywords: network install, network provisioning 
summary: ノードの展開およびグリッド構成中に、グリッド ネットワークとオプションの管理ネットワークおよびクライアント ネットワークがどのように使用されるかを理解する必要があります。 
---
= ネットワークのインストールとプロビジョニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードの展開およびグリッド構成中に、グリッド ネットワークとオプションの管理ネットワークおよびクライアント ネットワークがどのように使用されるかを理解する必要があります。



== ノードの初期展開

ノードを初めてデプロイするときは、ノードをグリッド ネットワークに接続し、プライマリ管理ノードにアクセスできることを確認する必要があります。グリッド ネットワークが分離されている場合は、グリッド ネットワークの外部から構成およびインストールにアクセスできるように、プライマリ管理ノード上に管理ネットワークを構成できます。

ゲートウェイが構成されたグリッド ネットワークは、デプロイメント中にノードのデフォルト ゲートウェイになります。デフォルト ゲートウェイを使用すると、グリッドが構成される前に、別のサブネット上のグリッド ノードがプライマリ管理ノードと通信できるようになります。

必要に応じて、NTP サーバーを含むサブネットや、グリッド マネージャーまたは API へのアクセスを必要とするサブネットも、グリッド サブネットとして構成できます。



== プライマリ管理ノードによる自動ノード登録

ノードがデプロイされると、グリッド ネットワークを使用して、ノード自体がプライマリ管理ノードに登録されます。その後、グリッドマネージャを使用して、 `configure-storagegrid.py`グリッドを構成し、登録されたノードを承認するための Python スクリプトまたはインストール API。グリッド構成時に、複数のグリッド サブネットを構成できます。グリッド構成が完了すると、グリッド ネットワーク ゲートウェイを介したこれらのサブネットへの静的ルートが各ノードに作成されます。



== 管理ネットワークまたはクライアントネットワークを無効にする

管理ネットワークまたはクライアントネットワークを無効にしたい場合は、ノード承認プロセス中にそれらの構成を削除するか、インストールが完了した後にIP変更ツールを使用することができます（link:../maintain/configuring-ip-addresses.html["IPアドレスを設定する"] ）。
