---
permalink: network/network-specific-requirements.html 
sidebar: sidebar 
keywords: network-specific requirements, network specific requirements, network requirements 
summary: 各StorageGRIDネットワーク タイプの要件に従ってください。 
---
= ネットワーク固有の要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各StorageGRIDネットワーク タイプの要件に従ってください。



== ネットワークゲートウェイとルーター

* 設定されている場合、特定のネットワークのゲートウェイは、特定のネットワークのサブネット内にある必要があります。
* 静的アドレス指定を使用してインターフェイスを構成する場合は、0.0.0.0 以外のゲートウェイ アドレスを指定する必要があります。
* ゲートウェイがない場合は、ゲートウェイ アドレスをネットワーク インターフェイスの IP アドレスに設定するのがベスト プラクティスです。




== サブネット


NOTE: 各ネットワークは、ノード上の他のネットワークと重複しない独自のサブネットに接続されている必要があります。

デプロイメント中に、グリッド マネージャーによって次の制限が適用されます。これらは、展開前のネットワーク計画を支援するためにここに提供されています。

* どのネットワーク IP アドレスのサブネット マスクも、255.255.255.254 または 255.255.255.255 (CIDR 表記では /31 または /32) にすることはできません。
* ネットワーク インターフェイスの IP アドレスとサブネット マスク (CIDR) によって定義されたサブネットは、同じノードに構成されている他のインターフェイスのサブネットと重複することはできません。
* どのノードのグリッド ネットワーク、管理ネットワーク、またはクライアント ネットワークにも、次の IPv4 アドレスを含むサブネットを使用しないでください。
+
** 192,168,130,101
** 192,168,131,101
** 192,168,130,102
** 192,168,131,102
** 198.51.100.2
** 198.51.100.4


+
たとえば、どのノードのグリッド ネットワーク、管理ネットワーク、またはクライアント ネットワークにも次のサブネット範囲を使用しないでください。

+
** 192.168.130.0/24 は、このサブネット範囲に IP アドレス 192.168.130.101 と 192.168.130.102 が含まれているためです。
** 192.168.131.0/24 は、このサブネット範囲に IP アドレス 192.168.131.101 と 192.168.131.102 が含まれているためです。
** 198.51.100.0/24 は、このサブネット範囲に IP アドレス 198.51.100.2 と 198.51.100.4 が含まれているためです。


* 各ノードのグリッド ネットワーク サブネットを GNSL に含める必要があります。
* 管理ネットワーク サブネットは、グリッド ネットワーク サブネット、クライアント ネットワーク サブネット、または GNSL 内のどのサブネットとも重複できません。
* AESL 内のサブネットは、GNSL 内のサブネットと重複できません。
* クライアント ネットワーク サブネットは、グリッド ネットワーク サブネット、管理ネットワーク サブネット、GNSL 内のサブネット、または AESL 内のサブネットと重複することはできません。




== グリッド ネットワーク

* デプロイメント時には、各グリッド ノードをグリッド ネットワークに接続し、ノードのデプロイメント時に指定したネットワーク構成を使用してプライマリ管理ノードと通信できる必要があります。
* 通常のグリッド操作中、各グリッド ノードはグリッド ネットワークを介して他のすべてのグリッド ノードと通信できる必要があります。
+

NOTE: グリッド ネットワークは各ノード間で直接ルーティング可能である必要があります。ノード間のネットワーク アドレス変換 (NAT) はサポートされていません。

* グリッド ネットワークが複数のサブネットで構成されている場合は、それらをグリッド ネットワーク サブネット リスト (GNSL) に追加します。  GNSL 内のサブネットごとに、すべてのノードに静的ルートが作成されます。
* グリッド ネットワーク インターフェイスが VLAN インターフェイスをサポートするトランクとして構成されている場合、トランク ネイティブ VLAN は、グリッド ネットワーク トラフィックに使用される VLAN である必要があります。すべてのグリッド ノードは、トランク ネイティブ VLAN 経由でアクセスできる必要があります。




== 管理者ネットワーク

管理ネットワークはオプションです。管理ネットワークを構成する予定の場合は、次の要件とガイドラインに従ってください。

管理ネットワークの一般的な用途には、管理接続、 AutoSupport、KMS、およびグリッド ネットワークまたはクライアント ネットワーク経由でこれらの接続が提供されない場合の NTP、DNS、LDAP などの重要なサーバへの接続が含まれます。


NOTE: 必要なネットワーク サービスとクライアントにアクセスできる限り、管理ネットワークと AESL は各ノードに対して一意にすることができます。


NOTE: 外部サブネットからの受信接続を有効にするには、管理ネットワーク上に少なくとも 1 つのサブネットを定義する必要があります。静的ルートは、AESL 内の各サブネットの各ノードで自動的に生成されます。



== クライアント ネットワーク

クライアント ネットワークはオプションです。クライアント ネットワークを構成する予定の場合は、次の考慮事項に注意してください。

* クライアント ネットワークは、S3 クライアントからのトラフィックをサポートするように設計されています。設定されている場合、クライアント ネットワーク ゲートウェイはノードのデフォルト ゲートウェイになります。
* クライアント ネットワークを使用する場合は、明示的に構成されたロード バランサのエンドポイントでのみ受信クライアント トラフィックを受け入れることで、 StorageGRID を敵対的な攻撃から保護できます。見るlink:../admin/configuring-load-balancer-endpoints.html["ロードバランサのエンドポイントを構成する"] 。
* クライアント ネットワーク インターフェイスが VLAN インターフェイスをサポートするためにトランクとして構成されている場合は、クライアント ネットワーク インターフェイス (eth2) を構成する必要があるかどうかを検討します。設定されている場合、クライアント ネットワーク トラフィックは、スイッチで設定されているとおりにトランク ネイティブ VLAN を介して流れます。


.関連情報
link:../maintain/changing-nodes-network-configuration.html["ノードネットワーク構成を変更する"]
