---
permalink: network/storagegrid-network-types.html 
sidebar: sidebar 
keywords: network types, grid traffic, admin traffic, client traffic, grid network, admin network, client network 
summary: StorageGRIDシステム内のグリッド ノードは、グリッド トラフィック、管理トラフィック、およびクライアント トラフィックを処理します。これら 3 種類のトラフィックを管理し、制御とセキュリティを提供するには、ネットワークを適切に構成する必要があります。 
---
= StorageGRIDネットワークの種類
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDシステム内のグリッド ノードは、_グリッド トラフィック_、_管理トラフィック_、および _クライアント トラフィック_ を処理します。これら 3 種類のトラフィックを管理し、制御とセキュリティを提供するには、ネットワークを適切に構成する必要があります。



== 交通の種類

[cols="1a,4a,2a"]
|===
| 交通の種類 | 説明 | ネットワークタイプ 


 a| 
グリッドトラフィック
 a| 
グリッド内のすべてのノード間を移動する内部StorageGRIDトラフィック。すべてのグリッド ノードは、このネットワークを介して他のすべてのグリッド ノードと通信できる必要があります。
 a| 
グリッドネットワーク（必須）



 a| 
管理者トラフィック
 a| 
システムの管理とメンテナンスに使用されるトラフィック。
 a| 
管理者ネットワーク（オプション）<<オプションのVLANネットワーク,VLANネットワーク（オプション）>>



 a| 
クライアントトラフィック
 a| 
S3 クライアントからのすべてのオブジェクト ストレージ要求を含む、外部クライアント アプリケーションとグリッド間を移動するトラフィック。
 a| 
クライアントネットワーク（オプション）<<オプションのVLANネットワーク,VLANネットワーク（オプション）>>

|===
ネットワークは次の方法で構成できます。

* グリッドネットワークのみ
* グリッドと管理ネットワーク
* グリッドとクライアントネットワーク
* グリッド、管理、クライアントネットワーク


グリッド ネットワークは必須であり、すべてのグリッド トラフィックを管理できます。管理ネットワークとクライアント ネットワークは、インストール時に含めることも、要件の変更に合わせて後で追加することもできます。管理ネットワークとクライアント ネットワークはオプションですが、これらのネットワークを使用して管理トラフィックとクライアント トラフィックを処理すると、グリッド ネットワークを分離して安全にすることができます。

内部ポートにはグリッド ネットワーク経由でのみアクセスできます。外部ポートはすべてのネットワーク タイプからアクセスできます。この柔軟性により、 StorageGRID の展開を設計し、スイッチとファイアウォールで外部 IP およびポート フィルタリングを設定するための複数のオプションが提供されます。見るlink:../network/internal-grid-node-communications.html["内部グリッドノード通信"]そしてlink:../network/external-communications.html["外部コミュニケーション"]。



== ネットワーク インターフェイス

StorageGRIDノードは、次の特定のインターフェースを使用して各ネットワークに接続されます。

[cols="1a,1a"]
|===
| ネットワーク | インターフェイス名 


 a| 
グリッドネットワーク（必須）
 a| 
eth0



 a| 
管理者ネットワーク（オプション）
 a| 
eth1



 a| 
クライアントネットワーク（オプション）
 a| 
eth2

|===
仮想ポートまたは物理ポートをノード ネットワーク インターフェイスにマッピングする方法の詳細については、インストール手順を参照してください。

.ソフトウェアベースのノード
* link:../rhel/index.html["Red Hat Enterprise LinuxにStorageGRIDをインストールする"]
* link:../ubuntu/index.html["UbuntuまたはDebianにStorageGRIDをインストールする"]
* link:../vmware/index.html["VMwareにStorageGRIDをインストールする"]


.アプライアンスノード
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg6100.html["SG6160 ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg6100.html["SGF6112 ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg6000.html["SG6000ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg5800.html["SG5800 ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg5700.html["SG5700 ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg110-and-1100.html["SG110およびSG1100サービス アプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg100-and-1000.html["SG100およびSG1000サービス アプライアンス"^]




=== 各ノードのネットワーク情報

ノード上で有効にするネットワークごとに以下を構成する必要があります。

* IPアドレス
* サブネット マスク
* ゲートウェイのIPアドレス


各グリッド ノード上の 3 つのネットワークごとに、IP アドレス/マスク/ゲートウェイの組み合わせを 1 つだけ構成できます。ネットワークのゲートウェイを構成しない場合は、IP アドレスをゲートウェイ アドレスとして使用する必要があります。



=== 高可用性グループ

高可用性 (HA) グループは、グリッドまたはクライアント ネットワーク インターフェイスに仮想 IP (VIP) アドレスを追加する機能を提供します。詳細については、以下を参照してください。 link:../admin/managing-high-availability-groups.html["高可用性グループの管理"] 。



== グリッド ネットワーク

グリッド ネットワークが必要です。これは、すべての内部StorageGRIDトラフィックに使用されます。グリッド ネットワークは、すべてのサイトおよびサブネットにわたるグリッド内のすべてのノード間の接続を提供します。グリッド ネットワーク上のすべてのノードは、他のすべてのノードと通信できる必要があります。グリッド ネットワークは複数のサブネットで構成できます。  NTP などの重要なグリッド サービスを含むネットワークも、グリッド サブネットとして追加できます。


NOTE: StorageGRID は、ノード間のネットワーク アドレス変換 (NAT) をサポートしていません。

管理ネットワークとクライアント ネットワークが構成されている場合でも、グリッド ネットワークはすべての管理トラフィックとすべてのクライアント トラフィックに使用できます。ノードにクライアント ネットワークが構成されていない限り、グリッド ネットワーク ゲートウェイがノードのデフォルト ゲートウェイになります。


CAUTION: グリッド ネットワークを構成するときは、オープン インターネット上のクライアントなどの信頼できないクライアントからネットワークが保護されていることを確認する必要があります。

グリッド ネットワーク ゲートウェイの次の要件と詳細に注意してください。

* グリッド サブネットが複数ある場合は、グリッド ネットワーク ゲートウェイを構成する必要があります。
* グリッド構成が完了するまで、グリッド ネットワーク ゲートウェイはノードのデフォルト ゲートウェイになります。
* グローバル グリッド ネットワーク サブネット リストに設定されているすべてのサブネットへのすべてのノードに対して、静的ルートが自動的に生成されます。
* クライアント ネットワークが追加されると、グリッド構成が完了すると、デフォルト ゲートウェイはグリッド ネットワーク ゲートウェイからクライアント ネットワーク ゲートウェイに切り替わります。




== 管理者ネットワーク

管理ネットワークはオプションです。設定すると、システム管理およびメンテナンス トラフィックに使用できます。管理ネットワークは通常はプライベート ネットワークであり、ノード間でルーティング可能である必要はありません。

管理ネットワークを有効にするグリッド ノードを選択できます。

管理ネットワークを使用する場合、管理およびメンテナンスのトラフィックはグリッド ネットワークを通過する必要がありません。管理ネットワークの一般的な用途は次のとおりです。

* Grid Manager および Tenant Manager ユーザー インターフェイスへのアクセス。
* NTP サーバー、DNS サーバー、外部キー管理サーバー (KMS)、Lightweight Directory Access Protocol (LDAP) サーバーなどの重要なサービスへのアクセス。
* 管理ノード上の監査ログへのアクセス。
* メンテナンスとサポートのためのセキュア シェル プロトコル (SSH) アクセス。


管理ネットワークは、内部グリッド トラフィックには使用されません。管理ネットワーク ゲートウェイが提供され、管理ネットワークが複数の外部サブネットと通信できるようになります。ただし、管理ネットワーク ゲートウェイはノードのデフォルト ゲートウェイとして使用されることはありません。

管理ネットワーク ゲートウェイの次の要件と詳細に注意してください。

* 管理ネットワーク サブネットの外部から接続を行う場合、または複数の管理ネットワーク サブネットが構成されている場合は、管理ネットワーク ゲートウェイが必要です。
* ノードの管理ネットワーク サブネット リストに設定されているサブネットごとに静的ルートが作成されます。




== クライアント ネットワーク

クライアント ネットワークはオプションです。設定すると、S3 などのクライアント アプリケーションにグリッド サービスへのアクセスを提供するために使用されます。 StorageGRIDデータを外部リソース (クラウド ストレージ プールやStorageGRID CloudMirror レプリケーション サービスなど) からアクセスできるようにする場合は、外部リソースでもクライアント ネットワークを使用できます。グリッド ノードは、クライアント ネットワーク ゲートウェイを介して到達可能な任意のサブネットと通信できます。

どのグリッド ノードでクライアント ネットワークを有効にするかを選択できます。すべてのノードが同じクライアント ネットワーク上にある必要はなく、ノードがクライアント ネットワークを介して相互に通信することはありません。グリッドのインストールが完了するまで、クライアント ネットワークは動作しません。

セキュリティを強化するために、ノードのクライアント ネットワーク インターフェイスを信頼できないものとして指定し、クライアント ネットワークで許可される接続をより制限することができます。ノードのクライアント ネットワーク インターフェイスが信頼されていない場合、インターフェイスは CloudMirror レプリケーションで使用されるような送信接続を受け入れますが、ロード バランサーのエンドポイントとして明示的に構成されたポート上の受信接続のみを受け入れます。見るlink:../admin/manage-firewall-controls.html["ファイアウォール制御を管理する"]そしてlink:../admin/configuring-load-balancer-endpoints.html["ロードバランサのエンドポイントを構成する"]。

クライアント ネットワークを使用する場合、クライアント トラフィックはグリッド ネットワークを通過する必要がありません。グリッド ネットワーク トラフィックは、安全でルーティング不可能なネットワークに分離できます。多くの場合、次のノード タイプがクライアント ネットワークで構成されます。

* ゲートウェイ ノード。これらのノードは、 StorageGRIDロード バランサ サービスへのアクセスと、グリッドへの S3 クライアント アクセスを提供するためです。
* ストレージ ノード。これらのノードは、S3 プロトコル、クラウド ストレージ プール、および CloudMirror レプリケーション サービスへのアクセスを提供するためです。
* 管理ノードは、テナント ユーザーが管理ネットワークを使用しなくてもテナント マネージャーに接続できるようにします。


クライアント ネットワーク ゲートウェイについては、次の点に注意してください。

* クライアント ネットワークが構成されている場合は、クライアント ネットワーク ゲートウェイが必要です。
* グリッド構成が完了すると、クライアント ネットワーク ゲートウェイがグリッド ノードのデフォルト ルートになります。




== オプションのVLANネットワーク

必要に応じて、クライアント トラフィックおよび一部の種類の管理トラフィックに仮想 LAN (VLAN) ネットワークを使用することもできます。ただし、グリッド トラフィックでは VLAN インターフェイスを使用できません。ノード間の内部StorageGRIDトラフィックは、常に eth0 上のグリッド ネットワークを使用する必要があります。

VLAN の使用をサポートするには、ノード上の 1 つ以上のインターフェイスをスイッチのトランク インターフェイスとして設定する必要があります。グリッド ネットワーク インターフェイス (eth0) またはクライアント ネットワーク インターフェイス (eth2) をトランクとして構成したり、ノードにトランク インターフェイスを追加したりできます。

eth0 がトランクとして設定されている場合、グリッド ネットワーク トラフィックは、スイッチで設定されているとおりにトランク ネイティブ インターフェイスを介して流れます。同様に、eth2 がトランクとして設定され、クライアント ネットワークも同じノード上に設定されている場合、クライアント ネットワークはスイッチ上に設定されているトランク ポートのネイティブ VLAN を使用します。

VLAN ネットワークでは、SSH、グリッド マネージャー、テナント マネージャー トラフィックなどに使用される受信管理トラフィックのみがサポートされます。  NTP、DNS、LDAP、KMS、クラウド ストレージ プールなどに使用される送信トラフィックは、VLAN ネットワーク経由ではサポートされません。


NOTE: VLAN インターフェイスは、管理ノードとゲートウェイ ノードにのみ追加できます。ストレージ ノードへのクライアントまたは管理者のアクセスには VLAN インターフェイスを使用できません。

見るlink:../admin/configure-vlan-interfaces.html["VLANインターフェースを構成する"]手順とガイドラインについてはこちらをご覧ください。

VLAN インターフェースは HA グループでのみ使用され、アクティブ ノードで VIP アドレスが割り当てられます。見るlink:../admin/managing-high-availability-groups.html["高可用性グループの管理"]手順とガイドラインについてはこちらをご覧ください。
