---
permalink: network/subnet-requirements.html 
sidebar: sidebar 
keywords: network subnets 
summary: ネットワーク サブネットについては、次の要件とガイドラインに従ってください。 
---
= サブネットの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワーク サブネットについては、次の要件とガイドラインに従ってください。


NOTE: 各ネットワークは、ノード上の他のネットワークと重複しない独自のサブネットに接続されている必要があります。

デプロイメント中に、グリッド マネージャーによって次の制限が適用されます。これらは、展開前のネットワーク計画を支援するためにここに提供されています。

* どのネットワーク IP アドレスのサブネット マスクも、255.255.255.254 または 255.255.255.255 (CIDR 表記では /31 または /32) にすることはできません。
* ネットワーク インターフェイスの IP アドレスとサブネット マスク (CIDR) によって定義されたサブネットは、同じノードに構成されている他のインターフェイスのサブネットと重複することはできません。
* どのノードのグリッド ネットワーク、管理ネットワーク、またはクライアント ネットワークにも、次の IPv4 アドレスを含むサブネットを使用しないでください。
+
** 192,168,130,101
** 192,168,131,101
** 192,168,130,102
** 192,168,131,102
** 198.51.100.2
** 198.51.100.4


+
たとえば、どのノードのグリッド ネットワーク、管理ネットワーク、またはクライアント ネットワークにも次のサブネット範囲を使用しないでください。

+
** 192.168.130.0/24 は、このサブネット範囲に IP アドレス 192.168.130.101 と 192.168.130.102 が含まれているためです。
** 192.168.131.0/24 は、このサブネット範囲に IP アドレス 192.168.131.101 と 192.168.131.102 が含まれているためです。
** 198.51.100.0/24 は、このサブネット範囲に IP アドレス 198.51.100.2 と 198.51.100.4 が含まれているためです。


* 各ノードのグリッド ネットワーク サブネットを GNSL に含める必要があります。
* 管理ネットワーク サブネットは、グリッド ネットワーク サブネット、クライアント ネットワーク サブネット、または GNSL 内のどのサブネットとも重複できません。
* AESL 内のサブネットは、GNSL 内のサブネットと重複できません。
* クライアント ネットワーク サブネットは、グリッド ネットワーク サブネット、管理ネットワーク サブネット、GNSL 内のサブネット、または AESL 内のサブネットと重複することはできません。

