= 
:allow-uri-read: 


[role="tabbed-block"]
====
.複製されたデータ
--
* 複製された修復の推定完了率を取得するには、 `show-replicated-repair-status` repair-data コマンドのオプション。
+
`repair-data show-replicated-repair-status`

* 修復が完了したかどうかを確認するには:
+
.. *NODES* > *_修復中のストレージノード_* > *ILM* を選択します。
.. 評価セクションの属性を確認します。修復が完了すると、「待機中 - すべて」属性にオブジェクトが 0 個と表示されます。


* 修復をより詳細に監視するには:
+
.. *サポート* > *ツール* > *グリッド トポロジ* を選択します。
.. *_grid_* > *_修復中のストレージノード_* > *LDR* > *データ ストア* を選択します。
.. 次の属性の組み合わせを使用して、複製された修復が完了しているかどうかを可能な限り判断します。
+

NOTE: Cassandra に不整合が存在する可能性があり、失敗した修復は追跡されません。

+
*** *修復試行 (XRPA)*: この属性を使用して、複製された修復の進行状況を追跡します。この属性は、ストレージ ノードが高リスクのオブジェクトの修復を試みるたびに増加します。この属性が現在のスキャン期間（*スキャン期間 - 推定*属性によって指定）よりも長い期間増加しない場合は、ILM スキャンでどのノードにも修復が必要な高リスク オブジェクトが見つからなかったことを意味します。
+

NOTE: 高リスクオブジェクトとは、完全に失われる危険性があるオブジェクトです。これには、ILM 構成を満たさないオブジェクトは含まれません。

*** *スキャン期間 - 推定 (XSCM)*: この属性を使用して、以前に取り込まれたオブジェクトにポリシーの変更がいつ適用されるかを推定します。 *修復試行* 属性が現在のスキャン期間よりも長い期間増加しない場合は、複製された修復が行われた可能性があります。スキャン期間は変更される可能性があることに注意してください。 *スキャン期間 - 推定 (XSCM)* 属性はグリッド全体に適用され、すべてのノード スキャン期間の最大値になります。グリッドの *スキャン期間 - 推定* 属性履歴を照会して、適切な時間枠を決定できます。






--
.消失訂正符号化（EC）データ
--
消去コード化されたデータの修復を監視し、失敗した可能性のある要求を再試行するには:

. 消失訂正符号化データの修復ステータスを確認します。
+
** 現在のジョブの完了までの推定時間と完了率を表示するには、[サポート] > [ツール] > [メトリック] を選択します。次に、Grafana セクションで *EC 概要* を選択します。*グリッド EC ジョブの完了推定時間*ダッシュボードと*グリッド EC ジョブの完了率*ダッシュボードを確認します。
** このコマンドを使用して、特定の `repair-data`手術：
+
`repair-data show-ec-repair-status --repair-id repair ID`

** すべての修復を一覧表示するには、次のコマンドを使用します。
+
`repair-data show-ec-repair-status`

+
出力には以下の情報が含まれます。 `repair ID` 、過去および現在実行中のすべての修復。



. 出力に修復操作が失敗したことが示されている場合は、 `--repair-id`修復を再試行するオプション。
+
このコマンドは、修復 ID 6949309319275667690 を使用して、失敗したノードの修復を再試行します。

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
このコマンドは、修復 ID 6949309319275667690 を使用して、失敗したボリューム修復を再試行します。

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====