= ストレージノードのホスト名を見つける
:allow-uri-read: 




== ストレージノードのホスト名を見つける

. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
+
ルートとしてログインすると、プロンプトは `$`に `#`。



. 使用 `/etc/hosts`ファイルを使用して、復元されたストレージ ボリュームのストレージ ノードのホスト名を見つけます。グリッド内のすべてのノードのリストを表示するには、次のように入力します。 `cat /etc/hosts` 。




== すべてのボリュームに障害が発生した場合にデータを修復する

すべてのストレージ ボリュームに障害が発生した場合は、ノード全体を修復します。複製データ、消失訂正符号化 (EC) データ、またはその両方のいずれを使用するかに応じて、*複製データ*、*消失訂正符号化 (EC) データ*、またはその両方の手順に従います。

一部のボリュームのみが故障している場合は、<<一部のボリュームのみが故障した場合にデータを修復する>> 。


NOTE: 走れない `repair-data`複数のノードに対して同時に操作を実行します。複数のノードを回復するには、テクニカル サポートにお問い合わせください。

[role="tabbed-block"]
====
.複製されたデータ
--
グリッドに複製データが含まれている場合は、 `repair-data start-replicated-node-repair`コマンドを `--nodes`オプション、ここで `--nodes`ストレージノード全体を修復するためのホスト名 (システム名) です。

このコマンドは、SG-DC-SN3 という名前のストレージ ノード上の複製されたデータを修復します。

`repair-data start-replicated-node-repair --nodes SG-DC-SN3`


NOTE: オブジェクト データが復元されるときに、 StorageGRIDシステムが複製されたオブジェクト データを見つけられない場合は、*オブジェクト損失* アラートがトリガーされます。システム全体のストレージ ノードでアラートがトリガーされる可能性があります。損失の原因と回復が可能かどうかを判断する必要があります。見るlink:../troubleshoot/investigating-lost-objects.html["紛失物の調査"] 。

--
.消失訂正符号化（EC）データ
--
グリッドに消失訂正符号化データが含まれている場合は、 `repair-data start-ec-node-repair`コマンドを `--nodes`オプション、ここで `--nodes`ストレージノード全体を修復するためのホスト名 (システム名) です。

このコマンドは、SG-DC-SN3 という名前のストレージ ノード上の消去コード化されたデータを修復します。

`repair-data start-ec-node-repair --nodes SG-DC-SN3`

この操作は一意の `repair ID`これを識別する `repair_data`手術。これを使う `repair ID`進捗状況と結果を追跡する `repair_data`手術。回復プロセスが完了しても、その他のフィードバックは返されません。

一部のストレージ ノードがオフラインの場合でも、消去コード化されたデータの修復を開始できます。すべてのノードが利用可能になると修復が完了します。

--
====


== 一部のボリュームのみが故障した場合にデータを修復する

一部のボリュームのみに障害が発生した場合は、影響を受けるボリュームを修復します。複製データ、消失訂正符号化 (EC) データ、またはその両方のいずれを使用するかに応じて、*複製データ*、*消失訂正符号化 (EC) データ*、またはその両方の手順に従います。

すべてのボリュームが失敗した場合は、<<すべてのボリュームに障害が発生した場合にデータを修復する>> 。

ボリューム ID を 16 進数で入力します。例えば、 `0000`最初の巻であり、 `000F`第16巻です。  1 つのボリューム、ボリュームの範囲、または連続していない複数のボリュームを指定できます。

すべてのボリュームは同じストレージ ノード上にある必要があります。複数のストレージ ノードのボリュームを復元する必要がある場合は、テクニカル サポートにお問い合わせください。

[role="tabbed-block"]
====
.複製されたデータ
--
グリッドに複製されたデータが含まれている場合は、 `start-replicated-volume-repair`コマンドを `--nodes`ノードを識別するオプション（ `--nodes`ノードのホスト名です。次に、 `--volumes`または `--volume-range`オプションは次の例のように使用できます。

*単一ボリューム*: このコマンドは複製されたデータをボリュームに復元します `0002`SG-DC-SN3 というストレージノード上:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0002`

*ボリュームの範囲*: このコマンドは、範囲内のすべてのボリュームに複製されたデータを復元します。 `0003`に `0009`SG-DC-SN3 というストレージノード上:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*複数のボリュームが連続していない*: このコマンドは、複製されたデータをボリュームに復元します `0001`、 `0005` 、 そして `0008`SG-DC-SN3 というストレージノード上:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0001,0005,0008`


NOTE: オブジェクト データが復元されるときに、 StorageGRIDシステムが複製されたオブジェクト データを見つけられない場合は、*オブジェクト損失* アラートがトリガーされます。システム全体のストレージ ノードでアラートがトリガーされる可能性があります。アラートの説明と推奨されるアクションに注意してください。損失の原因を特定し、回復が可能かどうかを確認します。

--
.消失訂正符号化（EC）データ
--
グリッドに消失訂正符号化データが含まれている場合は、 `start-ec-volume-repair`コマンドを `--nodes`ノードを識別するオプション（ `--nodes`ノードのホスト名です。次に、 `--volumes`または `--volume-range`オプションは次の例のように使用できます。

*単一ボリューム*: このコマンドは、消去符号化されたデータをボリュームに復元します `0007`SG-DC-SN3 というストレージノード上:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 0007`

*ボリュームの範囲*: このコマンドは、範囲内のすべてのボリュームに消去符号化データを復元します。 `0004`に `0006`SG-DC-SN3 というストレージノード上:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

*複数のボリュームが連続していない*: このコマンドは、消去符号化されたデータをボリュームに復元します `000A`、 `000C` 、 そして `000E`SG-DC-SN3 というストレージノード上:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 000A,000C,000E`

その `repair-data`操作は一意の値を返す `repair ID`これを識別する `repair_data`手術。これを使う `repair ID`進捗状況と結果を追跡する `repair_data`手術。回復プロセスが完了しても、その他のフィードバックは返されません。


NOTE: 一部のストレージ ノードがオフラインの場合でも、消去コード化されたデータの修復を開始できます。すべてのノードが利用可能になると修復が完了します。

--
====