= S3 オブジェクトロックが有効になっているバケットの要件
:allow-uri-read: 




== S3 オブジェクトロックが有効になっているバケットの要件

* StorageGRIDシステムでグローバル S3 オブジェクト ロック設定が有効になっている場合は、テナント マネージャ、テナント管理 API、または S3 REST API を使用して、S3 オブジェクト ロックが有効になっているバケットを作成できます。
* S3 オブジェクトロックを使用する予定の場合は、バケットを作成するときに S3 オブジェクトロックを有効にする必要があります。既存のバケットに対して S3 オブジェクトロックを有効にすることはできません。
* バケットに対して S3 オブジェクト ロックが有効になっている場合、 StorageGRID はそのバケットのバージョン管理を自動的に有効にします。  S3 オブジェクトロックを無効にしたり、バケットのバージョン管理を一時停止したりすることはできません。
* オプションで、テナント マネージャー、テナント管理 API、または S3 REST API を使用して、各バケットのデフォルトの保持モードと保持期間を指定できます。バケットのデフォルトの保持設定は、バケットに追加された、独自の保持設定を持たない新しいオブジェクトにのみ適用されます。アップロード時に各オブジェクト バージョンの保持モードと保持期限を指定することにより、これらのデフォルト設定を上書きできます。
* バケットのライフサイクル設定は、S3 オブジェクト ロックが有効になっているバケットでサポートされます。
* S3 オブジェクト ロックが有効になっているバケットでは、CloudMirror レプリケーションはサポートされません。




== S3 オブジェクトロックが有効になっているバケット内のオブジェクトの要件

* オブジェクト バージョンを保護するには、バケットのデフォルトの保持設定を指定するか、オブジェクト バージョンごとに保持設定を指定できます。オブジェクト レベルの保持設定は、S3 クライアント アプリケーションまたは S3 REST API を使用して指定できます。
* 保持設定は個々のオブジェクト バージョンに適用されます。オブジェクト バージョンには、保持期限設定と法的保留設定の両方が含まれる場合もあれば、どちらか一方だけが含まれる場合もあり、どちらも含まれない場合もあります。オブジェクトに対して保持期限または法的保留設定を指定すると、リクエストで指定されたバージョンのみが保護されます。オブジェクトの以前のバージョンはロックされたまま、オブジェクトの新しいバージョンを作成できます。




== S3 オブジェクトロックが有効になっているバケット内のオブジェクトのライフサイクル

S3 オブジェクトロックが有効になっているバケットに保存された各オブジェクトは、以下の段階を経ます。

. *オブジェクトの取り込み*
+
S3 オブジェクトロックが有効になっているバケットにオブジェクトバージョンが追加されると、保持設定が次のように適用されます。

+
** オブジェクトに保持設定が指定されている場合は、オブジェクト レベルの設定が適用されます。デフォルトのバケット設定はすべて無視されます。
** オブジェクトに保持設定が指定されていない場合は、デフォルトのバケット設定（存在する場合）が適用されます。
** オブジェクトまたはバケットに保持設定が指定されていない場合、オブジェクトは S3 オブジェクト ロックによって保護されません。


+
保持設定が適用されると、オブジェクトと S3 ユーザー定義メタデータの両方が保護されます。

. *オブジェクトの保持と削除*
+
保護された各オブジェクトの複数のコピーは、指定された保持期間にわたってStorageGRIDによって保存されます。オブジェクト コピーの正確な数とタイプ、および保存場所は、アクティブな ILM ポリシーの準拠ルールによって決まります。保護されたオブジェクトを、その保持期限に達する前に削除できるかどうかは、その保持モードによって異なります。

+
** オブジェクトが法的保留中の場合、保持モードに関係なく、誰もそのオブジェクトを削除することはできません。



