= S3 オブジェクトロックとは何ですか?
:allow-uri-read: 




== S3 オブジェクトロックとは何ですか?

StorageGRID S3 オブジェクト ロック機能は、Amazon Simple Storage Service (Amazon S3) の S3 オブジェクト ロックと同等のオブジェクト保護ソリューションです。

StorageGRIDシステムでグローバル S3 オブジェクト ロック設定が有効になっている場合、S3 テナント アカウントは、S3 オブジェクト ロックが有効になっているかどうかに関係なくバケットを作成できます。バケットで S3 オブジェクトロックが有効になっている場合は、バケットのバージョン管理が必要となり、自動的に有効になります。

*S3 オブジェクト ロックのないバケット* には、保持設定が指定されていないオブジェクトのみを含めることができます。取り込まれたオブジェクトには保持設定はありません。

*S3 オブジェクト ロックが有効なバケット* には、S3 クライアント アプリケーションによって指定された保持設定のあるオブジェクトと、保持設定のないオブジェクトを含めることができます。取り込まれたオブジェクトの中には保持設定を持つものがあります。

*S3 オブジェクト ロックとデフォルトの保持期間が設定されたバケット* には、保持期間設定が指定されたアップロード済みオブジェクトと、保持期間設定のない新しいオブジェクトを含めることができます。保持設定がオブジェクト レベルで構成されていないため、新しいオブジェクトではデフォルト設定が使用されます。

実際には、デフォルトの保持期間が設定されている場合、新しく取り込まれたすべてのオブジェクトに保持設定が行われます。オブジェクト保持設定のない既存のオブジェクトは影響を受けません。



=== 保持モード

StorageGRID S3 オブジェクト ロック機能は、オブジェクトに異なるレベルの保護を適用するための 2 つの保持モードをサポートしています。これらのモードは、Amazon S3 保持モードと同等です。

* コンプライアンスモードの場合:
+
** オブジェクトは、保持期限に達するまで削除できません。
** オブジェクトの保持期限を増やすことはできますが、減らすことはできません。
** オブジェクトの保持期限は、その日付に達するまで削除できません。


* ガバナンス モードの場合:
+
** 特別な権限を持つユーザーは、リクエストでバイパス ヘッダーを使用して、特定の保持設定を変更できます。
** これらのユーザーは、オブジェクト バージョンを、その保持期限に達する前に削除できます。
** これらのユーザーは、オブジェクトの保持期限を増減または削除できます。






=== オブジェクトバージョンの保持設定

S3 オブジェクト ロックを有効にしてバケットを作成した場合、ユーザーは S3 クライアント アプリケーションを使用して、バケットに追加されるオブジェクトごとに次の保持設定をオプションで指定できます。

* *保持モード*: コンプライアンスまたはガバナンスのいずれか。
* *保持期限*: オブジェクト バージョンの保持期限が将来の日付である場合、オブジェクトを取得することはできますが、削除することはできません。
* *法的保留*: オブジェクト バージョンに法的保留を適用すると、そのオブジェクトは直ちにロックされます。たとえば、調査や法的紛争に関連するオブジェクトに対して法的保留を設定する必要がある場合があります。法的保留には有効期限はありませんが、明示的に削除されるまで有効のままになります。法的保留は、保持期限とは無関係です。
+

NOTE: オブジェクトが法的保留中の場合、保持モードに関係なく、誰もそのオブジェクトを削除することはできません。

+
オブジェクト設定の詳細については、link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API を使用して S3 オブジェクトロックを設定する"] 。





=== バケットのデフォルトの保持設定

S3 オブジェクトロックを有効にしてバケットを作成すると、ユーザーはオプションでバケットの次のデフォルト設定を指定できます。

* *デフォルトの保持モード*: コンプライアンスまたはガバナンスのいずれか。
* *デフォルトの保持期間*: このバケットに追加された新しいオブジェクト バージョンを、追加された日から保持する期間。


デフォルトのバケット設定は、独自の保持設定を持たない新しいオブジェクトにのみ適用されます。これらのデフォルト設定を追加または変更しても、既存のバケット オブジェクトは影響を受けません。

見るlink:../tenant/creating-s3-bucket.html["S3バケットを作成する"]そしてlink:../tenant/update-default-retention-settings.html["S3 オブジェクトロックのデフォルト保持を更新"]。
