---
permalink: tenant/changing-bucket-versioning.html 
sidebar: sidebar 
keywords: how to change bucket versioning, disabled versioning, enabled versioning, suspended versioning 
summary: S3 テナントを使用している場合は、S3 バケットのバージョン管理状態を変更できます。 
---
= バケットのオブジェクトのバージョン管理を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 テナントを使用している場合は、S3 バケットのバージョン管理状態を変更できます。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたは、link:tenant-management-permissions.html["すべてのバケットまたはルートアクセス権限を管理する"] 。これらの権限は、グループまたはバケット ポリシーの権限設定をオーバーライドします。
* 必要な数のストレージ ノードとサイトが利用可能であることを確認しました。どのサイトでも 2 つ以上のストレージ ノードが利用できない場合、またはサイトが利用できない場合は、これらの設定を変更できない可能性があります。


.タスク概要
バケットのオブジェクトのバージョン管理を有効化または一時停止できます。バケットのバージョン管理を有効にすると、バージョン管理されていない状態に戻すことはできません。ただし、バケットのバージョン管理を一時停止することはできます。

* 無効: バージョン管理が有効になったことはありません
* 有効: バージョン管理が有効です
* 一時停止: バージョン管理は以前は有効でしたが、一時停止されています


詳細については、次を参照してください。

* link:../s3/object-versioning.html["オブジェクトのバージョン管理"]
* link:../ilm/example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["S3 バージョン管理オブジェクトの ILM ルールとポリシー (例 4)"]
* link:../ilm/how-objects-are-deleted.html["オブジェクトの削除方法"]


.手順
. ダッシュボードから*バケットの表示*を選択するか、*ストレージ (S3)* > *バケット*を選択します。
. テーブルからバケット名を選択します。
+
バケットの詳細ページが表示されます。

. *バケット オプション* タブから、*オブジェクトのバージョン管理* アコーディオンを選択します。
. このバケット内のオブジェクトのバージョン管理状態を選択します。
+
クロスグリッド レプリケーションに使用されるバケットでは、オブジェクトのバージョン管理を有効にしておく必要があります。  S3 オブジェクト ロックまたはレガシー コンプライアンスが有効になっている場合、*オブジェクトのバージョン管理* オプションは無効になります。

+
[cols="1a,3a"]
|===
| オプション | 説明 


 a| 
バージョン管理を有効にする
 a| 
このバケット内の各オブジェクトのすべてのバージョンを保存する場合は、オブジェクトのバージョン管理を有効にします。必要に応じて、オブジェクトの以前のバージョンを取得できます。

バケット内にすでに存在するオブジェクトは、ユーザーによって変更されるとバージョン管理されます。



 a| 
バージョン管理を一時停止
 a| 
新しいオブジェクト バージョンを作成する必要がなくなった場合は、オブジェクトのバージョン管理を一時停止します。既存のオブジェクト バージョンを引き続き取得できます。

|===
. *変更を保存*を選択します。

