---
permalink: tenant/configuring-platform-services-endpoints.html 
sidebar: sidebar 
keywords: how to configure platform services endpoint 
summary: バケットのプラットフォーム サービスを構成する前に、プラットフォーム サービスの宛先となるエンドポイントを少なくとも 1 つ構成する必要があります。 
---
= プラットフォーム サービスのエンドポイントを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バケットのプラットフォーム サービスを構成する前に、プラットフォーム サービスの宛先となるエンドポイントを少なくとも 1 つ構成する必要があります。

プラットフォーム サービスへのアクセスは、 StorageGRID管理者によってテナントごとに有効化されます。プラットフォーム サービス エンドポイントを作成または使用するには、ストレージ ノードが外部エンドポイント リソースにアクセスできるようにネットワークが構成されているグリッド内で、エンドポイントの管理権限またはルート アクセス権限を持つテナント ユーザーである必要があります。 1 つのテナントに対して、最大 500 個のプラットフォーム サービス エンドポイントを構成できます。詳細については、 StorageGRID管理者にお問い合わせください。



== プラットフォーム サービス エンドポイントとは何ですか?

プラットフォーム サービス エンドポイントは、 StorageGRID が外部の宛先にアクセスするために必要な情報を指定します。

たとえば、 StorageGRIDバケットから Amazon S3 バケットにオブジェクトを複製する場合は、 StorageGRID がAmazon の宛先バケットにアクセスするために必要な情報と認証情報を含むプラットフォーム サービス エンドポイントを作成します。

各タイプのプラットフォーム サービスには独自のエンドポイントが必要であるため、使用する予定のプラットフォーム サービスごとに少なくとも 1 つのエンドポイントを構成する必要があります。プラットフォーム サービス エンドポイントを定義した後、サービスを有効にするために使用される構成 XML で、エンドポイントの URN を宛先として使用します。

複数のソース バケットの宛先として同じエンドポイントを使用できます。たとえば、複数のソース バケットを構成して、オブジェクト メタデータを同じ検索統合エンドポイントに送信するようにすることで、複数のバケットにわたって検索を実行できるようになります。また、ソースバケットを複数のエンドポイントをターゲットとして使用するように設定することもできます。これにより、オブジェクトの作成に関する通知を 1 つの Amazon Simple Notification Service (Amazon SNS) トピックに送信し、オブジェクトの削除に関する通知を 2 番目の Amazon SNS トピックに送信するといったことが可能になります。



== CloudMirror レプリケーションのエンドポイント

StorageGRID は、S3 バケットを表すレプリケーション エンドポイントをサポートしています。これらのバケットは、Amazon Web Services、同じまたはリモートのStorageGRIDデプロイメント、あるいは別のサービスでホストされている場合があります。



== 通知のエンドポイント

StorageGRID は、Amazon SNS および Kafka エンドポイントをサポートしています。Simple Queue Service (SQS) または AWS Lambda エンドポイントはサポートされていません。

Kafka エンドポイントでは、相互 TLS はサポートされていません。その結果、もしあなたが `ssl.client.auth`に設定 `required`Kafka ブローカー構成では、Kafka エンドポイント構成の問題が発生する可能性があります。



== 検索統合サービスのエンドポイント

StorageGRID は、Elasticsearch クラスターを表す検索統合エンドポイントをサポートしています。これらの Elasticsearch クラスターは、ローカルデータセンターに配置することも、AWS クラウドやその他の場所でホストすることもできます。

検索統合エンドポイントは、特定の Elasticsearch インデックスとタイプを参照します。 StorageGRIDでエンドポイントを作成する前に、Elasticsearch でインデックスを作成する必要があります。そうしないと、エンドポイントの作成は失敗します。エンドポイントを作成する前にタイプを作成する必要はありません。  StorageGRID は、オブジェクト メタデータをエンドポイントに送信するときに、必要に応じてタイプを作成します。

.関連情報
link:../admin/index.html["StorageGRIDの管理"]
