---
permalink: tenant/considerations-for-platform-services.html 
sidebar: sidebar 
keywords: considerations for using platform services 
summary: プラットフォーム サービスを実装する前に、これらのサービスの使用に関する概要と考慮事項を確認してください。 
---
= プラットフォームサービスの概要と考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プラットフォーム サービスを実装する前に、これらのサービスの使用に関する概要と考慮事項を確認してください。

S3の詳細については、link:../s3/index.html["S3 REST APIを使用する"] 。



== プラットフォームサービスの概要

StorageGRIDプラットフォーム サービスは、イベント通知や S3 オブジェクトおよびオブジェクト メタデータのコピーを外部の宛先に送信できるようにすることで、ハイブリッド クラウド戦略の実装を支援します。

プラットフォーム サービスのターゲットの場所は通常、 StorageGRID展開の外部にあるため、プラットフォーム サービスにより、データの外部ストレージ リソース、通知サービス、検索サービスや分析サービスを使用することで得られるパワーと柔軟性が得られます。

単一の S3 バケットに対して、プラットフォーム サービスの任意の組み合わせを構成できます。たとえば、link:../tenant/understanding-cloudmirror-replication-service.html["CloudMirrorサービス"]そしてlink:../tenant/understanding-notifications-for-buckets.html["通知"]StorageGRID S3 バケットに作成することで、特定のオブジェクトを Amazon Simple Storage Service (S3) にミラーリングできると同時に、各オブジェクトに関する通知をサードパーティの監視アプリケーションに送信して、AWS 経費を追跡できるようになります。


TIP: プラットフォーム サービスの使用は、Grid Manager または Grid Management API を使用して、 StorageGRID管理者がテナント アカウントごとに有効にする必要があります。



== プラットフォームサービスの構成方法

プラットフォームサービスは、link:configuring-platform-services-endpoints.html["Tenant Manager"]またはlink:understanding-tenant-management-api.html["テナント管理API"]。各エンドポイントは、 StorageGRID S3 バケット、Amazon Web Services バケット、Amazon SNS トピック、ローカル、AWS、またはその他の場所でホストされている Elasticsearch クラスターなどの外部の宛先を表します。

外部エンドポイントを作成した後、バケットに XML 構成を追加して、バケットのプラットフォーム サービスを有効にできます。  XML 構成では、バケットが操作するオブジェクト、バケットが実行するアクション、およびバケットがサービスに使用するエンドポイントが識別されます。

構成するプラットフォーム サービスごとに個別の XML 構成を追加する必要があります。例えば：

* キーが次の文字で始まるすべてのオブジェクトを取得したい場合 `/images`Amazon S3 バケットにレプリケートするには、ソースバケットにレプリケーション設定を追加する必要があります。
* これらのオブジェクトがバケットに保存されたときにも通知を送信する場合は、通知設定を追加する必要があります。
* これらのオブジェクトのメタデータをインデックスする場合は、検索統合を実装するために使用されるメタデータ通知構成を追加する必要があります。


構成 XML の形式は、 StorageGRIDプラットフォーム サービスを実装するために使用される S3 REST API によって管理されます。

[cols="1a,2a,1a"]
|===
| プラットフォームサービス | S3 REST API | 参照 


 a| 
CloudMirrorレプリケーション
 a| 
* GetBucketReplication
* PutBucketレプリケーション

 a| 
* link:configuring-cloudmirror-replication.html["CloudMirrorレプリケーション"]
* link:../s3/operations-on-buckets.html["バケットの操作"]




 a| 
通知
 a| 
* GetBucketNotificationConfiguration
* PutBucketNotificationConfiguration

 a| 
* link:configuring-event-notifications.html["通知"]
* link:../s3/operations-on-buckets.html["バケットの操作"]




 a| 
検索統合
 a| 
* バケットメタデータ通知設定の取得
* PUT バケットメタデータ通知設定

 a| 
* link:configuring-search-integration-service.html["検索統合"]
* link:../s3/custom-operations-on-buckets.html["StorageGRIDカスタム操作"]


|===


== プラットフォームサービスの利用に関する考慮事項

[cols="1a,3a"]
|===
| 考慮事項 | 詳細 


 a| 
宛先エンドポイントの監視
 a| 
各宛先エンドポイントの可用性を監視する必要があります。宛先エンドポイントへの接続が長時間失われ、大量の要求のバックログが存在する場合、 StorageGRIDへの追加のクライアント要求 (PUT 要求など) は失敗します。エンドポイントに到達可能になったら、これらの失敗したリクエストを再試行する必要があります。



 a| 
宛先エンドポイントのスロットリング
 a| 
リクエストの送信速度が宛先エンドポイントがリクエストを受信できる速度を超えた場合、 StorageGRIDソフトウェアはバケットの受信 S3 リクエストを調整することがあります。スロットルは、宛先エンドポイントへの送信を待機しているリクエストのバックログがある場合にのみ発生します。

目に見える唯一の影響は、受信する S3 リクエストの実行に時間がかかるようになることです。パフォーマンスが大幅に低下していることが検出された場合は、取り込み速度を下げるか、容量の大きいエンドポイントを使用する必要があります。リクエストのバックログが増え続けると、クライアントの S3 操作 (PUT リクエストなど) は最終的に失敗します。

CloudMirror リクエストは、通常、検索統合リクエストやイベント通知リクエストよりも多くのデータ転送を伴うため、宛先エンドポイントのパフォーマンスの影響を受ける可能性が高くなります。



 a| 
注文保証
 a| 
StorageGRID は、サイト内のオブジェクトに対する操作の順序を保証します。オブジェクトに対するすべての操作が同じサイト内で行われる限り、最終的なオブジェクトの状態 (レプリケーションの場合) は常にStorageGRID内の状態と同じになります。

StorageGRID は、 StorageGRIDサイト間で操作が行われるときに、リクエストを順序付けるために最善を尽くします。たとえば、最初にサイト A にオブジェクトを書き込み、その後サイト B で同じオブジェクトを上書きした場合、CloudMirror によって宛先バケットに複製された最終的なオブジェクトが新しいオブジェクトである保証はありません。



 a| 
ILMによるオブジェクトの削除
 a| 
AWS CRR および Amazon Simple Notification Service の削除動作と一致させるため、 StorageGRID ILM ルールによりソースバケット内のオブジェクトが削除された場合、CloudMirror およびイベント通知リクエストは送信されません。たとえば、ILM ルールによって 14 日後にオブジェクトが削除された場合、CloudMirror またはイベント通知リクエストは送信されません。

対照的に、検索統合リクエストは、ILM によってオブジェクトが削除されたときに送信されます。



 a| 
Kafkaエンドポイントの使用
 a| 
Kafka エンドポイントでは、相互 TLS はサポートされていません。その結果、もしあなたが `ssl.client.auth`に設定 `required`Kafka ブローカー構成では、Kafka エンドポイント構成の問題が発生する可能性があります。

Kafka エンドポイントの認証では、次の認証タイプが使用されます。これらのタイプは、Amazon SNS などの他のエンドポイントの認証に使用されるタイプとは異なり、ユーザー名とパスワードの認証情報が必要です。

* SASL/プレーン
* SASL/SCRAM-SHA-256
* SASL/SCRAM-SHA-512


*注:* 構成されたストレージ プロキシ設定は、Kafka プラットフォーム サービス エンドポイントには適用されません。

|===


== CloudMirrorレプリケーションサービスの使用に関する考慮事項

[cols="1a,3a"]
|===
| 考慮事項 | 詳細 


 a| 
レプリケーションステータス
 a| 
StorageGRIDはサポートしていません `x-amz-replication-status`ヘッダ。



 a| 
オブジェクトのサイズ
 a| 
CloudMirror レプリケーション サービスによって宛先バケットにレプリケートできるオブジェクトの最大サイズは 5 TiB で、これはサポートされているオブジェクトの最大サイズと同じです。

*注*: 1 回の PutObject 操作の最大 _推奨_ サイズは 5 GiB (5,368,709,120 バイト) です。  5 GiB を超えるオブジェクトがある場合は、代わりにマルチパートアップロードを使用します。



 a| 
バケットのバージョン管理とバージョンID
 a| 
StorageGRIDのソース S3 バケットでバージョン管理が有効になっている場合は、宛先バケットでもバージョン管理を有効にする必要があります。

バージョン管理を使用する場合、S3 プロトコルの制限により、宛先バケット内のオブジェクト バージョンの順序付けはベスト エフォートであり、CloudMirror サービスによって保証されないことに注意してください。

*注意*: StorageGRIDのソース バケットのバージョン ID は、宛先バケットのバージョン ID とは関連がありません。



 a| 
オブジェクトバージョンのタグ付け
 a| 
CloudMirror サービスは、S3 プロトコルの制限により、バージョン ID を提供する PutObjectTagging または DeleteObjectTagging リクエストを複製しません。ソースと宛先のバージョン ID は関連していないため、特定のバージョン ID へのタグ更新が確実に複製されるかどうかはわかりません。

対照的に、CloudMirror サービスは、バージョン ID を指定しない PutObjectTagging リクエストまたは DeleteObjectTagging リクエストを複製します。これらのリクエストは、最新のキー (バケットがバージョン管理されている場合は最新バージョン) のタグを更新します。タグ付きの通常の取り込み (タグ付けの更新ではない) も複製されます。



 a| 
マルチパートアップロードと `ETag`価値観
 a| 
マルチパートアップロードを使用してアップロードされたオブジェクトをミラーリングする場合、CloudMirror サービスはパートを保持しません。その結果、 `ETag`ミラーリングされたオブジェクトの値は、 `ETag`元のオブジェクトの値。



 a| 
SSE-C（顧客提供のキーによるサーバー側暗号化）で暗号化されたオブジェクト
 a| 
CloudMirror サービスは、SSE-C で暗号化されたオブジェクトをサポートしていません。CloudMirror レプリケーションのソースバケットにオブジェクトを取り込もうとする際に、リクエストに SSE-C リクエストヘッダーが含まれていると、操作は失敗します。



 a| 
S3 オブジェクトロックが有効になっているバケット
 a| 
S3 オブジェクトロックが有効になっているソースバケットまたは宛先バケットでは、レプリケーションはサポートされません。

|===