---
permalink: tenant/creating-s3-bucket.html 
sidebar: sidebar 
keywords: how to create S3 bucket 
summary: テナント マネージャーを使用して、オブジェクト データ用の S3 バケットを作成できます。 
---
= S3バケットを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナント マネージャーを使用して、オブジェクト データ用の S3 バケットを作成できます。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* ルートアクセスまたはすべてのバケットの管理権限を持つユーザーグループに属しているlink:tenant-management-permissions.html["アクセス権"]。これらの権限は、グループまたはバケット ポリシーの権限設定をオーバーライドします。
+

NOTE: バケットまたはオブジェクトのS3オブジェクトロックプロパティを設定または変更する権限は、link:../s3/bucket-and-group-access-policies.html["バケットポリシーまたはグループポリシー"] 。

* バケットに対して S3 オブジェクト ロックを有効にする予定の場合は、グリッド管理者がStorageGRIDシステムのグローバル S3 オブジェクト ロック設定を有効にし、S3 オブジェクト ロック バケットとオブジェクトの要件を確認しておきます。
* 各テナントに 5,000 個のバケットがある場合、グリッド内の各ストレージ ノードには最低 64 GB の RAM があります。
+

NOTE: 各グリッドには最大 100,000 個のバケットを含めることができます。





== ウィザードにアクセスする

.手順
. ダッシュボードから*バケットの表示*を選択するか、*ストレージ (S3)* > *バケット*を選択します。
. *バケットを作成*を選択します。




== 詳細を入力してください

.手順
. バケットの詳細を入力します。
+
[cols="1a,3a"]
|===
| フィールド | 説明 


 a| 
バケット名
 a| 
次のルールに準拠するバケットの名前:

** 各StorageGRIDシステム全体で一意である必要があります (テナント アカウント内で一意なだけでなく)。
** DNS に準拠している必要があります。
** 3 文字以上 63 文字以下でなければなりません。
** 各ラベルは小文字または数字で始まり、終わる必要があり、小文字、数字、ハイフンのみを使用できます。
** 仮想ホスト形式のリクエストにはピリオドを含めることはできません。ピリオドを使用すると、サーバーのワイルドカード証明書の検証で問題が発生します。


詳細については、 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["バケット命名ルールに関する Amazon Web Services (AWS) ドキュメント"^] 。

*注意*: バケットを作成した後は、バケット名を変更することはできません。



 a| 
リージョン
 a| 
バケットのリージョン。

利用可能なリージョンはStorageGRID管理者が管理します。バケットのリージョンは、オブジェクトに適用されるデータ保護ポリシーに影響を与える可能性があります。デフォルトでは、すべてのバケットは `us-east-1`地域。

*注意*: バケットを作成した後はリージョンを変更できません。

|===
. *続行*を選択します。




== 設定の管理

.手順
. 必要に応じて、バケットのオブジェクトのバージョン管理を有効にします。
+
このバケット内の各オブジェクトのすべてのバージョンを保存する場合は、オブジェクトのバージョン管理を有効にします。必要に応じて、オブジェクトの以前のバージョンを取得できます。バケットをクロスグリッド レプリケーションに使用する場合は、オブジェクトのバージョン管理を有効にする必要があります。

. グローバル S3 オブジェクトロック設定が有効になっている場合は、オプションでバケットの S3 オブジェクトロックを有効にして、Write Once Read Many (WORM) モデルを使用してオブジェクトを保存します。
+
特定の規制要件を満たすためなど、オブジェクトを一定期間保持する必要がある場合にのみ、バケットに対して S3 オブジェクトロックを有効にします。S3 オブジェクト ロックは、一定期間または無期限にオブジェクトが削除または上書きされるのを防ぐのに役立つ永続的な設定です。

+

CAUTION: バケットに対して S3 オブジェクトロック設定を有効にすると、無効にすることはできません。適切な権限を持つユーザーは誰でも、変更できないオブジェクトをこのバケットに追加できます。これらのオブジェクトまたはバケット自体を削除できない可能性があります。

+
バケットに対して S3 オブジェクトロックを有効にすると、バケットのバージョン管理が自動的に有効になります。

. *S3 オブジェクトロックを有効にする*を選択した場合は、オプションでこのバケットの*デフォルトの保持期間*を有効にします。
+

NOTE: グリッド管理者は、次の権限を与える必要があります。link:../tenant/using-s3-object-lock.html["S3 オブジェクトロックの特定の機能を使用する"] 。

+
*デフォルトの保持期間* が有効になっている場合、バケットに追加された新しいオブジェクトは、削除または上書きされないように自動的に保護されます。*デフォルトの保持期間*設定は、独自の保持期間を持つオブジェクトには適用されません。

+
.. *デフォルトの保持*が有効になっている場合は、バケットの*デフォルトの保持モード*を指定します。
+
[cols="1a,2a"]
|===
| デフォルトの保持モード | 説明 


 a| 
ガバナンス
 a| 
*** ユーザーは `s3:BypassGovernanceRetention`許可は `x-amz-bypass-governance-retention: true`保持設定をバイパスするためのリクエスト ヘッダー。
*** これらのユーザーは、オブジェクト バージョンを、その保持期限に達する前に削除できます。
*** これらのユーザーは、オブジェクトの保持期限を増減または削除できます。




 a| 
コンプライアンス
 a| 
*** オブジェクトは、保持期限に達するまで削除できません。
*** オブジェクトの保持期限を増やすことはできますが、減らすことはできません。
*** オブジェクトの保持期限は、その日付に達するまで削除できません。


*注意*: グリッド管理者がコンプライアンス モードの使用を許可する必要があります。

|===
.. *デフォルトの保持*が有効になっている場合は、バケットの*デフォルトの保持期間*を指定します。
+
*デフォルトの保持期間* は、このバケットに追加された新しいオブジェクトが取り込まれた時点から保持される期間を示します。グリッド管理者によって設定されたテナントの最大保持期間以下の値を指定します。

+
グリッド管理者がテナントを作成するときに、1 日から 100 年までの値に設定できる最大保持期間が設定されます。 _デフォルト_の保持期間を設定する場合、最大保持期間に設定された値を超えることはできません。必要に応じて、グリッド管理者に最大保存期間の増減を依頼してください。



. [[capacity-limit]]オプションで、「*容量制限を有効にする*」を選択します。
+
容量制限は、このバケットのオブジェクトに使用できる最大容量です。この値は物理的な量 (ディスク上のサイズ) ではなく、論理的な量 (オブジェクトのサイズ) を表します。

+
制限が設定されていない場合、このバケットの容量は無制限になります。参照link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["容量制限の使用"]詳細についてはこちらをご覧ください。

. *バケットを作成*を選択します。
+
バケットが作成され、「バケット」ページのテーブルに追加されます。

. オプションで*バケットの詳細ページに移動*を選択してlink:viewing-s3-bucket-details.html["バケットの詳細を表示"]追加の構成を実行します。

