---
permalink: tenant/creating-groups-for-swift-tenant.html 
sidebar: sidebar 
keywords: how to create Swift tenant groups 
summary: フェデレーション グループをインポートするか、ローカル グループを作成することによって、Swift テナント アカウントのアクセス権限を管理できます。少なくとも 1 つのグループに Swift 管理者権限が必要です。この権限は、Swift テナント アカウントのコンテナーとオブジェクトを管理するために必要なものです。 
---
= Swiftテナントのグループを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
フェデレーション グループをインポートするか、ローカル グループを作成することによって、Swift テナント アカウントのアクセス権限を管理できます。少なくとも 1 つのグループに Swift 管理者権限が必要です。この権限は、Swift テナント アカウントのコンテナーとオブジェクトを管理するために必要なものです。


NOTE: Swift クライアント アプリケーションのサポートは非推奨となり、将来のリリースでは削除される予定です。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたは、link:tenant-management-permissions.html["ルートアクセス権限"] 。
* フェデレーショングループをインポートする予定の場合は、link:using-identity-federation.html["構成されたID連携"] 、フェデレーション グループは構成された ID ソースにすでに存在します。




== グループ作成ウィザードにアクセスする

.手順
最初のステップとして、グループの作成ウィザードにアクセスします。

. *アクセス管理* > *グループ*を選択します。
. *グループを作成*を選択します。




== グループの種類を選択

ローカル グループを作成したり、フェデレーション グループをインポートしたりできます。

.手順
. ローカル グループを作成するには *ローカル グループ* タブを選択し、以前に構成した ID ソースからグループをインポートするには *フェデレーション グループ* タブを選択します。
+
StorageGRIDシステムでシングル サインオン (SSO) が有効になっている場合、ローカル グループに属するユーザーは、グループの権限に基づいてクライアント アプリケーションを使用してテナントのリソースを管理することはできますが、テナント マネージャにサインインすることはできません。

. グループの名前を入力します。
+
** *ローカル グループ*: 表示名と一意の名前の両方を入力します。表示名は後で編集できます。
** *フェデレーション グループ*: 一意の名前を入力します。  Active Directoryの場合、一意の名前は `sAMAccountName`属性。  OpenLDAPの場合、一意の名前は `uid`属性。


. *続行*を選択します。




== グループ権限を管理する

グループ権限は、ユーザーがテナント マネージャーおよびテナント管理 API で実行できるタスクを制御します。

.手順
. *アクセス モード* では、次のいずれかを選択します。
+
** *読み取り/書き込み* (デフォルト): ユーザーは Tenant Manager にサインインし、テナント構成を管理できます。
** *読み取り専用*: ユーザーは設定と機能の表示のみが可能です。テナント マネージャーまたはテナント管理 API で変更を加えたり、操作を実行したりすることはできません。ローカルの読み取り専用ユーザーは自分のパスワードを変更できます。
+

NOTE: ユーザーが複数のグループに属しており、いずれかのグループが読み取り専用に設定されている場合、ユーザーは選択したすべての設定と機能に対して読み取り専用アクセス権を持ちます。



. グループ ユーザーが Tenant Manager または Tenant Management API にサインインする必要がある場合は、*ルート アクセス* チェックボックスをオンにします。
. *続行*を選択します。




== Swiftグループポリシーを設定する

Swift ユーザーは、コンテナを作成してオブジェクトを取り込むために、Swift REST API に認証するための管理者権限が必要です。

. グループ ユーザーが Swift REST API を使用してコンテナーとオブジェクトを管理する必要がある場合は、*Swift 管理者* チェックボックスをオンにします。
. ローカル グループを作成する場合は、[続行] を選択します。フェデレーション グループを作成する場合は、[*グループの作成*] と [*完了*] を選択します。




== ユーザーを追加する（ローカルグループのみ）

ユーザーを追加せずにグループを保存することも、オプションで既存のローカル ユーザーを追加することもできます。

.手順
. 必要に応じて、このグループのローカル ユーザーを 1 人以上選択します。
+
ローカル ユーザーをまだ作成していない場合は、[ユーザー] ページでこのグループをユーザーに追加できます。見るlink:../tenant/managing-local-users.html["ローカルユーザーの管理"] 。

. *グループの作成*と*完了*を選択します。
+
作成したグループがグループのリストに表示されます。


