---
permalink: tenant/creating-platform-services-endpoint.html 
sidebar: sidebar 
keywords: how to create platform services endpoint 
summary: プラットフォーム サービスを有効にする前に、正しいタイプのエンドポイントを少なくとも 1 つ作成する必要があります。 
---
= プラットフォーム サービス エンドポイントを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プラットフォーム サービスを有効にする前に、正しいタイプのエンドポイントを少なくとも 1 つ作成する必要があります。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* StorageGRID管理者によって、テナント アカウントに対してプラットフォーム サービスが有効化されました。
* あなたは、link:tenant-management-permissions.html["エンドポイントまたはルートアクセス権限を管理する"] 。
* プラットフォーム サービス エンドポイントによって参照されるリソースが作成されました。
+
** CloudMirrorレプリケーション: S3バケット
** イベント通知: Amazon Simple Notification Service (Amazon SNS) または Kafka トピック
** 検索通知: 宛先クラスターがインデックスを自動的に作成するように構成されていない場合の Elasticsearch インデックス。


* 宛先リソースに関する情報は次の通りです。
+
** URI (Uniform Resource Identifier) のホストとポート
+

NOTE: StorageGRIDシステムでホストされているバケットを CloudMirror レプリケーションのエンドポイントとして使用する予定の場合は、グリッド管理者に問い合わせて、入力する必要がある値を確認してください。

** ユニークリソース名 (URN)
+
link:specifying-urn-for-platform-services-endpoint.html["プラットフォーム サービス エンドポイントの URN を指定します"]

** 認証資格情報（必要な場合）:
+
[role="tabbed-block"]
====
.検索統合エンドポイント
--
検索統合エンドポイントでは、次の資格情報を使用できます。

*** アクセスキー: アクセスキーIDとシークレットアクセスキー
*** 基本的なHTTP: ユーザー名とパスワード


--
.CloudMirror レプリケーションエンドポイント
--
CloudMirror レプリケーション エンドポイントの場合、次の認証情報を使用できます。

*** アクセスキー: アクセスキーIDとシークレットアクセスキー
*** CAP (C2S アクセス ポータル): 一時資格情報 URL、サーバーおよびクライアント証明書、クライアント キー、およびオプションのクライアント秘密キー パスフレーズ。


--
.Amazon SNSエンドポイント
--
Amazon SNS エンドポイントの場合、次の認証情報を使用できます。

*** アクセスキー: アクセスキーIDとシークレットアクセスキー


--
.Kafkaエンドポイント
--
Kafka エンドポイントの場合、次の資格情報を使用できます。

*** SASL/PLAIN: ユーザー名とパスワード
*** SASL/SCRAM-SHA-256: ユーザー名とパスワード
*** SASL/SCRAM-SHA-512: ユーザー名とパスワード


--
====
** セキュリティ証明書（カスタム CA 証明書を使用している場合）


* Elasticsearch セキュリティ機能が有効になっている場合は、接続テストのためのクラスター監視権限と、ドキュメント更新のためのインデックス書き込み権限またはインデックスとインデックス削除の両方の権限が付与されます。


.手順
. *ストレージ (S3)* > *プラットフォーム サービス エンドポイント* を選択します。プラットフォーム サービス エンドポイント ページが表示されます。
. *エンドポイントの作成*を選択します。
. エンドポイントとその目的を簡単に説明する表示名を入力します。
+
エンドポイントがサポートするプラットフォーム サービスのタイプは、エンドポイント ページにリストされるときにエンドポイント名の横に表示されるため、名前にその情報を含める必要はありません。

. *URI* フィールドに、エンドポイントの一意のリソース識別子 (URI) を指定します。
+
--
次のいずれかの形式を使用します。

[listing]
----
https://host:port
http://host:port
----
ポートを指定しない場合は、次のデフォルト ポートが使用されます。

** HTTPS URIの場合はポート443、HTTP URIの場合はポート80（ほとんどのエンドポイント）
** HTTPS および HTTP URI のポート 9092 (Kafka エンドポイントのみ)


--
+
たとえば、 StorageGRIDでホストされているバケットの URI は次のようになります。

+
[listing]
----
https://s3.example.com:10443
----
+
この例では、 `s3.example.com` StorageGRID高可用性（HA）グループの仮想IP（VIP）のDNSエントリを表し、 `10443`ロード バランサーのエンドポイントで定義されたポートを表します。

+

NOTE: 可能な限り、単一障害点を回避するために、負荷分散ノードの HA グループに接続する必要があります。

+
同様に、AWS でホストされているバケットの URI は次のようになります。

+
[listing]
----
https://s3-aws-region.amazonaws.com
----
+

NOTE: エンドポイントが CloudMirror レプリケーション サービスに使用される場合は、URI にバケット名を含めないでください。  *URN* フィールドにバケット名を含めます。

. エンドポイントの一意のリソース名 (URN) を入力します。
+

NOTE: エンドポイントを作成した後は、エンドポイントの URN を変更することはできません。

. *続行*を選択します。
. *認証タイプ*の値を選択します。
+
[role="tabbed-block"]
====
.検索統合エンドポイント
--
検索統合エンドポイントの資格情報を入力またはアップロードします。

指定する資格情報には、宛先リソースに対する書き込み権限が必要です。

[cols="1a,2a,2a"]
|===
| 認証タイプ | 説明 | Credentials 


 a| 
匿名
 a| 
宛先への匿名アクセスを提供します。セキュリティが無効になっているエンドポイントでのみ機能します。
 a| 
認証なし。



 a| 
アクセス キー
 a| 
AWS スタイルの認証情報を使用して、宛先との接続を認証します。
 a| 
** アクセス キー ID
** シークレット アクセス キー




 a| 
基本的なHTTP
 a| 
ユーザー名とパスワードを使用して、宛先への接続を認証します。
 a| 
** ユーザー名
** パスワード


|===
--
.CloudMirror レプリケーションエンドポイント
--
CloudMirror レプリケーション エンドポイントの資格情報を入力またはアップロードします。

指定する資格情報には、宛先リソースに対する書き込み権限が必要です。

[cols="1a,2a,2a"]
|===
| 認証タイプ | 説明 | Credentials 


 a| 
匿名
 a| 
宛先への匿名アクセスを提供します。セキュリティが無効になっているエンドポイントでのみ機能します。
 a| 
認証なし。



 a| 
アクセス キー
 a| 
AWS スタイルの認証情報を使用して、宛先との接続を認証します。
 a| 
** アクセス キー ID
** シークレット アクセス キー




 a| 
CAP（C2Sアクセスポータル）
 a| 
証明書とキーを使用して、宛先への接続を認証します。
 a| 
** 一時認証情報URL
** サーバーCA証明書（PEMファイルのアップロード）
** クライアント証明書（PEMファイルのアップロード）
** クライアント秘密鍵（PEMファイルのアップロード、OpenSSL暗号化形式、または暗号化されていない秘密鍵形式）
** クライアントの秘密鍵のパスフレーズ（オプション）


|===
--
.Amazon SNSエンドポイント
--
Amazon SNS エンドポイントの認証情報を入力またはアップロードします。

指定する資格情報には、宛先リソースに対する書き込み権限が必要です。

[cols="1a,2a,2a"]
|===
| 認証タイプ | 説明 | Credentials 


 a| 
匿名
 a| 
宛先への匿名アクセスを提供します。セキュリティが無効になっているエンドポイントでのみ機能します。
 a| 
認証なし。



 a| 
アクセス キー
 a| 
AWS スタイルの認証情報を使用して、宛先との接続を認証します。
 a| 
** アクセス キー ID
** シークレット アクセス キー


|===
--
.Kafkaエンドポイント
--
Kafka エンドポイントの資格情報を入力またはアップロードします。

指定する資格情報には、宛先リソースに対する書き込み権限が必要です。

[cols="1a,2a,2a"]
|===
| 認証タイプ | 説明 | Credentials 


 a| 
匿名
 a| 
宛先への匿名アクセスを提供します。セキュリティが無効になっているエンドポイントでのみ機能します。
 a| 
認証なし。



 a| 
SASL/プレーン
 a| 
プレーンテキストのユーザー名とパスワードを使用して、宛先への接続を認証します。
 a| 
** ユーザー名
** パスワード




 a| 
SASL/SCRAM-SHA-256
 a| 
チャレンジ レスポンス プロトコルと SHA-256 ハッシュを使用したユーザー名とパスワードを使用して、宛先への接続を認証します。
 a| 
** ユーザー名
** パスワード




 a| 
SASL/SCRAM-SHA-512
 a| 
チャレンジ レスポンス プロトコルと SHA-512 ハッシュを使用したユーザー名とパスワードを使用して、宛先への接続を認証します。
 a| 
** ユーザー名
** パスワード


|===
ユーザー名とパスワードが Kafka クラスターから取得された委任トークンから派生している場合は、*委任された認証を使用する* を選択します。

--
====
. *続行*を選択します。
. *サーバーの検証*のラジオ ボタンを選択して、エンドポイントへの TLS 接続を検証する方法を選択します。
+
[cols="1a,2a"]
|===
| 証明書検証の種類 | 説明 


 a| 
カスタムCA証明書を使用する
 a| 
カスタム セキュリティ証明書を使用します。この設定を選択した場合は、カスタム セキュリティ証明書をコピーして、[CA 証明書] テキスト ボックスに貼り付けます。



 a| 
オペレーティング システムの CA 証明書を使用する
 a| 
接続を保護するには、オペレーティング システムにインストールされているデフォルトの Grid CA 証明書を使用します。



 a| 
証明書を検証しない
 a| 
TLS 接続に使用される証明書が検証されていません。このオプションは安全ではありません。

|===
. *エンドポイントのテストと作成*を選択します。
+
** 指定された資格情報を使用してエンドポイントに到達できる場合は、成功メッセージが表示されます。エンドポイントへの接続は、各サイトの 1 つのノードから検証されます。
** エンドポイントの検証に失敗した場合、エラー メッセージが表示されます。エラーを修正するためにエンドポイントを変更する必要がある場合は、[*エンドポイントの詳細に戻る*] を選択して情報を更新します。次に、*エンドポイントのテストと作成*を選択します。
+

NOTE: テナント アカウントでプラットフォーム サービスが有効になっていない場合、エンドポイントの作成は失敗します。  StorageGRID管理者に問い合わせてください。





エンドポイントを構成したら、その URN を使用してプラットフォーム サービスを構成できます。

.関連情報
* link:specifying-urn-for-platform-services-endpoint.html["プラットフォーム サービス エンドポイントの URN を指定します"]
* link:configuring-cloudmirror-replication.html["CloudMirrorレプリケーションを構成する"]
* link:configuring-event-notifications.html["イベント通知の設定"]
* link:configuring-search-integration-service.html["検索統合サービスを構成する"]

