---
permalink: tenant/creating-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create other user S3 access key 
summary: S3 テナントを使用しており、適切な権限がある場合は、バケットやオブジェクトへのアクセスが必要なアプリケーションなど、他のユーザーの S3 アクセスキーを作成できます。 
---
= 別のユーザーのS3アクセスキーを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 テナントを使用しており、適切な権限がある場合は、バケットやオブジェクトへのアクセスが必要なアプリケーションなど、他のユーザーの S3 アクセスキーを作成できます。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたは、link:tenant-management-permissions.html["ルートアクセス権限"] 。


.タスク概要
他のユーザーが自分のテナント アカウントのバケットを作成および管理できるように、1 つ以上の S3 アクセス キーを作成できます。新しいアクセス キーを作成したら、新しいアクセス キー ID とシークレット アクセス キーを使用してアプリケーションを更新します。セキュリティのため、ユーザーが必要とする以上のキーを作成しないでください。また、使用されていないキーは削除してください。キーが 1 つしかなく、そのキーの有効期限が近づいている場合は、古いキーの有効期限が切れる前に新しいキーを作成し、古いキーを削除します。

各キーには、特定の有効期限を設定することも、有効期限を設定しないこともできます。有効期限については次のガイドラインに従ってください。

* キーの有効期限を設定して、ユーザーのアクセスを特定の期間に制限します。有効期限を短く設定すると、アクセス キー ID とシークレット アクセス キーが誤って公開された場合のリスクを軽減できます。期限切れのキーは自動的に削除されます。
* 環境内のセキュリティ リスクが低く、定期的に新しいキーを作成する必要がない場合は、キーの有効期限を設定する必要はありません。後で新しいキーを作成する場合は、古いキーを手動で削除します。



CAUTION: ユーザーに属する S3 バケットとオブジェクトには、テナント マネージャーでそのユーザーに対して表示されるアクセス キー ID とシークレット アクセス キーを使用してアクセスできます。このため、アクセス キーはパスワードと同じように保護してください。アクセス キーを定期的にローテーションし、使用されていないキーはアカウントから削除し、他のユーザーと共有しないでください。

.手順
. *アクセス管理* > *ユーザー*を選択します。
. S3 アクセスキーを管理するユーザーを選択します。
+
ユーザーの詳細ページが表示されます。

. *アクセス キー* を選択し、*キーの作成* を選択します。
. 次のいずれかを実行します。
+
** 有効期限のないキーを作成するには、「有効期限を設定しない」を選択します。（デフォルト）
** *有効期限を設定する*を選択し、有効期限の日時を設定します。
+

NOTE: 有効期限は現在の日付から最大 5 年までとなります。有効期限は、現在の時刻から最低 1 分後に設定できます。



. *アクセスキーの作成*を選択します。
+
「アクセス キーのダウンロード」ダイアログ ボックスが表示され、アクセス キー ID とシークレット アクセス キーが一覧表示されます。

. アクセス キー ID とシークレット アクセス キーを安全な場所にコピーするか、*.csv をダウンロード* を選択して、アクセス キー ID とシークレット アクセス キーを含むスプレッドシート ファイルを保存します。
+

CAUTION: この情報をコピーまたはダウンロードするまで、このダイアログ ボックスを閉じないでください。ダイアログ ボックスを閉じた後は、キーをコピーまたはダウンロードすることはできません。

. *完了*を選択します。
+
新しいキーは、ユーザー詳細ページの [アクセス キー] タブに表示されます。

. テナント アカウントに *グリッド フェデレーション接続の使用* 権限がある場合は、オプションでテナント管理 API を使用して、ソース グリッドのテナントから宛先グリッドのテナントに S3 アクセス キーを手動で複製します。見るlink:grid-federation-clone-keys-with-api.html["API を使用して S3 アクセスキーを複製する"] 。

