---
permalink: tenant/deleting-s3-bucket.html 
sidebar: sidebar 
keywords: how to delete S3 bucket 
summary: テナント マネージャーを使用して、空の S3 バケットを削除できます。 
---
= S3バケットを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナント マネージャーを使用して、空の 1 つ以上の S3 バケットを削除できます。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたは、link:tenant-management-permissions.html["すべてのバケットまたはルートアクセス権限を管理する"] 。これらの権限は、グループまたはバケット ポリシーの権限設定をオーバーライドします。
* 削除するバケットは空です。削除したいバケットが空でない場合は、link:../tenant/deleting-s3-bucket-objects.html["バケットからオブジェクトを削除する"] 。


.タスク概要
これらの手順では、テナント マネージャーを使用して S3 バケットを削除する方法について説明します。  S3バケットを削除するには、link:understanding-tenant-management-api.html["テナント管理API"]またはlink:../s3/operations-on-buckets.html["S3 REST API"]。

S3 バケットにオブジェクト、非現在のオブジェクトバージョン、または削除マーカーが含まれている場合は、そのバケットを削除できません。  S3バージョン管理オブジェクトの削除方法については、以下を参照してください。link:../ilm/how-objects-are-deleted.html["オブジェクトの削除方法"] 。

.手順
. ダッシュボードから*バケットの表示*を選択するか、*ストレージ (S3)* > *バケット*を選択します。
+
「バケット」ページが表示され、既存の S3 バケットがすべて表示されます。

. *アクション* メニューまたは特定のバケットの詳細ページを使用します。
+
[role="tabbed-block"]
====
.[操作]メニュー
--
.. 削除する各バケットのチェックボックスを選択します。
.. *アクション* > *バケットの削除*を選択します。


--
.詳細ページ
--
.. バケット名を選択すると、その詳細が表示されます。
.. *バケットの削除*を選択します。


--
====
. 確認ダイアログボックスが表示されたら、「はい」を選択します。
+
StorageGRID は各バケットが空であることを確認し、各バケットを削除します。この処理には数分程度かかります。

+
バケットが空でない場合は、エラー メッセージが表示されます。絶対ですlink:../tenant/deleting-s3-bucket-objects.html["バケット内のすべてのオブジェクトと削除マーカーを削除します"]バケットを削除する前に。


