---
permalink: tenant/duplicating-group.html 
sidebar: sidebar 
keywords: how to duplicate tenant group 
summary: 既存のグループを複製することで、新しいグループをより速く作成できます。 
---
= 重複グループ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のグループを複製することで、新しいグループをより速く作成できます。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたは、ルートアクセス権限を持つユーザー グループに属しています。見るlink:tenant-management-permissions.html["テナント管理権限"] 。


.手順
. *アクセス管理* > *グループ*を選択します。
. 複製するグループのチェックボックスを選択します。
. *グループを複製*を選択します。グループ作成の詳細については、グループ作成の手順を参照してください。link:creating-groups-for-s3-tenant.html["S3テナント"]またはlink:creating-groups-for-swift-tenant.html["スウィフトの入居者"]。
. ローカル グループを作成するには *ローカル グループ* タブを選択し、以前に構成した ID ソースからグループをインポートするには *フェデレーション グループ* タブを選択します。
+
StorageGRIDシステムでシングルサインオン（SSO）が有効になっている場合、ローカルグループに属するユーザーはテナントマネージャにサインインできませんが、クライアントアプリケーションを使用してテナントのリソースを管理することはできます。link:tenant-management-permissions.html["グループ権限"] 。

. グループの名前を入力します。
+
** *ローカル グループ*: 表示名と一意の名前の両方を入力します。表示名は後で編集できます。
** *フェデレーション グループ*: 一意の名前を入力します。  Active Directoryの場合、一意の名前は `sAMAccountName`属性。  OpenLDAPの場合、一意の名前は `uid`属性。


. *続行*を選択します。
. 必要に応じて、このグループの権限を変更します。
. *続行*を選択します。
. 必要に応じて、S3 テナントのグループを複製する場合は、[*S3 ポリシーの追加*] ラジオ ボタンから別のポリシーを選択します。カスタム ポリシーを選択した場合は、必要に応じて JSON 文字列を更新します。
. *グループを作成*を選択します。

