---
permalink: tenant/enabling-or-disabling-last-access-time-updates.html 
sidebar: sidebar 
keywords: how to enable or disable last access time updates 
summary: 'グリッド管理者は、 StorageGRIDシステムの情報ライフサイクル管理 (ILM) ルールを作成するときに、オブジェクトの最終アクセス時刻を使用して、そのオブジェクトを別のストレージの場所に移動するかどうかを判断するようにオプションで指定できます。  S3 テナントを使用している場合は、S3 バケット内のオブジェクトの最終アクセス時刻の更新を有効にすることで、このようなルールを利用できます。' 
---
= 最終アクセス時間の更新を有効または無効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド管理者は、 StorageGRIDシステムの情報ライフサイクル管理 (ILM) ルールを作成するときに、オブジェクトの最終アクセス時刻を使用して、そのオブジェクトを別のストレージの場所に移動するかどうかを判断するようにオプションで指定できます。  S3 テナントを使用している場合は、S3 バケット内のオブジェクトの最終アクセス時刻の更新を有効にすることで、このようなルールを利用できます。

これらの手順は、*最終アクセス時刻* オプションを詳細フィルターまたは参照時刻として使用する ILM ルールが少なくとも 1 つ含まれるStorageGRIDシステムにのみ適用されます。 StorageGRIDシステムにそのようなルールが含まれていない場合は、これらの手順を無視できます。見るlink:../ilm/using-last-access-time-in-ilm-rules.html["ILMルールで最終アクセス時刻を使用する"]詳細については。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたは、link:tenant-management-permissions.html["すべてのバケットまたはルートアクセス権限を管理する"] 。これらの権限は、グループまたはバケット ポリシーの権限設定をオーバーライドします。


.タスク概要
*最終アクセス時間* は、ILM ルールの *参照時間* 配置指示に使用できるオプションの 1 つです。ルールの参照時間を最終アクセス時間に設定すると、グリッド管理者は、オブジェクトが最後に取得 (読み取りまたは表示) された時間に基づいて、オブジェクトが特定のストレージの場所に配置されるように指定できます。

たとえば、最近表示したオブジェクトがより高速なストレージに残るようにするために、グリッド管理者は以下を指定する ILM ルールを作成できます。

* 過去 1 か月間に取得されたオブジェクトは、ローカル ストレージ ノードに残ります。
* 過去 1 か月間に回収されていないオブジェクトは、オフサイトの場所に移動する必要があります。


デフォルトでは、最終アクセス時刻の更新は無効になっています。  StorageGRIDシステムに *最終アクセス時刻* オプションを使用する ILM ルールが含まれており、このオプションをこのバケット内のオブジェクトに適用する場合は、そのルールで指定された S3 バケットの最終アクセス時刻の更新を有効にする必要があります。


CAUTION: オブジェクトが取得されたときに最終アクセス時間を更新すると、特に小さなオブジェクトの場合、 StorageGRID のパフォーマンスが低下する可能性があります。

StorageGRID はオブジェクトが取得されるたびに次の追加手順を実行する必要があるため、最終アクセス時刻の更新によってパフォーマンスに影響が生じます。

* 新しいタイムスタンプでオブジェクトを更新する
* オブジェクトをILMキューに追加して、現在のILMルールとポリシーに照らして再評価できるようにします。


この表は、最終アクセス時間が無効または有効になっている場合にバケット内のすべてのオブジェクトに適用される動作をまとめたものです。

[cols="1a,1a,1a,1a,1a"]
|===


.2+| リクエストの種類 2+| 最終アクセス時刻が無効になっている場合の動作（デフォルト） 2+| 最終アクセス時刻が有効になっている場合の動作 


| 最終アクセス時間は更新されましたか? | オブジェクトが ILM 評価キューに追加されましたか? | 最終アクセス時間は更新されましたか? | オブジェクトが ILM 評価キューに追加されましたか? 


 a| 
オブジェクト、そのアクセス制御リスト、またはそのメタデータの取得要求
 a| 
いいえ
 a| 
いいえ
 a| 
はい
 a| 
はい



 a| 
オブジェクトのメタデータの更新リクエスト
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
オブジェクトまたはオブジェクトのバージョンの一覧表示のリクエスト
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
あるバケットから別のバケットにオブジェクトをコピーするリクエスト
 a| 
* いいえ、ソースコピーの場合
* はい、宛先コピー用

 a| 
* いいえ、ソースコピーの場合
* はい、宛先コピー用

 a| 
* はい、ソースコピーの場合
* はい、宛先コピー用

 a| 
* はい、ソースコピーの場合
* はい、宛先コピー用




 a| 
マルチパートアップロードの完了リクエスト
 a| 
はい、組み立てられたオブジェクトの場合
 a| 
はい、組み立てられたオブジェクトの場合
 a| 
はい、組み立てられたオブジェクトの場合
 a| 
はい、組み立てられたオブジェクトの場合

|===
.手順
. ダッシュボードから*バケットの表示*を選択するか、*ストレージ (S3)* > *バケット*を選択します。
. テーブルからバケット名を選択します。
+
バケットの詳細ページが表示されます。

. *バケット オプション* タブから、*最終アクセス時間の更新* アコーディオンを選択します。
. 最終アクセス時間の更新を有効または無効にします。
. *変更を保存*を選択します。

