---
permalink: tenant/ilm-policy-tags.html 
sidebar: sidebar 
keywords: how to assign ilm policy tag to bucket 
summary: オブジェクト ストレージの要件に基づいて、バケットに割り当てる ILM ポリシー タグを選択します。 
---
= バケットにILMポリシータグを適用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクト ストレージの要件に基づいて、バケットに適用する ILM ポリシー タグを選択します。

ILM ポリシーは、オブジェクト データが保存される場所と、一定期間後に削除されるかどうかを制御します。グリッド管理者は ILM ポリシーを作成し、複数のアクティブ ポリシーを使用する場合は ILM ポリシー タグに割り当てます。


NOTE: バケットのポリシータグを頻繁に再割り当てすることは避けてください。そうしないと、パフォーマンスの問題が発生する可能性があります。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたは、link:tenant-management-permissions.html["ルートアクセス、すべてのバケットの管理、またはすべてのバケットの表示権限"] 。これらの権限は、グループまたはバケット ポリシーの権限設定をオーバーライドします。


.手順
. ダッシュボードから*バケットの表示*を選択するか、*ストレージ (S3)* > *バケット*を選択します。
+
バケット ページが表示されます。必要に応じて、任意の列で情報を並べ替えたり、リスト内を前後に移動したりできます。

. ILM ポリシー タグを割り当てるバケットの名前を選択します。
+
すでにタグが割り当てられているバケットの ILM ポリシー タグの割り当てを変更することもできます。

+

NOTE: 表示されるオブジェクト数と使用済みスペースの値は推定値です。これらの見積りは、取り込みのタイミング、ネットワーク接続、およびノードの状態によって影響を受けます。バケットでバージョン管理が有効になっている場合、削除されたオブジェクトのバージョンもオブジェクト数に含まれます。

. バケット オプション タブで、ILM ポリシー タグ アコーディオンを展開します。このアコーディオンは、グリッド管理者がカスタム ポリシー タグの使用を有効にしている場合にのみ表示されます。
. 各ポリシータグの説明を読んで、バケットに適用するタグを決定します。
+

CAUTION: バケットの ILM ポリシー タグを変更すると、バケット内のすべてのオブジェクトの ILM 再評価がトリガーされます。新しいポリシーでオブジェクトを一定期間保持する場合、古いオブジェクトは削除されます。

. バケットに割り当てるタグのラジオボタンを選択します。
. *変更を保存*を選択します。キーを持つバケットに新しいS3バケットタグが設定されます `NTAP-SG-ILM-BUCKET-TAG`ILM ポリシー タグ名の値。
+

CAUTION: S3 アプリケーションが誤って新しいバケット タグを上書きまたは削除しないようにします。新しいタグセットをバケットに適用するときにこのタグを省略すると、バケット内のオブジェクトはデフォルトの ILM ポリシーに基づいて評価される状態に戻ります。

+

CAUTION: ILM ポリシー タグが検証される Tenant Manager または Tenant Manager API のみを使用して、ILM ポリシー タグを設定および変更します。変更しないでください `NTAP-SG-ILM-BUCKET-TAG`S3 PutBucketTagging API または S3 DeleteBucketTagging API を使用した ILM ポリシータグ。

+

NOTE: バケットに割り当てられたポリシー タグを変更すると、新しい ILM ポリシーを使用してオブジェクトが再評価されている間、一時的にパフォーマンスに影響が出ます。


