---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: 'テナント アカウントを使用すると、Simple Storage Service (S3) REST API または Swift REST API を使用して、 StorageGRIDシステムにオブジェクトを保存および取得できます。' 
---
= テナントアカウントを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナント アカウントを使用すると、Simple Storage Service (S3) REST API または Swift REST API を使用して、 StorageGRIDシステムにオブジェクトを保存および取得できます。



== テナントアカウントとは何ですか?

各テナント アカウントには、独自のフェデレーション グループまたはローカル グループ、ユーザー、S3 バケットまたは Swift コンテナ、およびオブジェクトがあります。

テナント アカウントを使用すると、保存されたオブジェクトを異なるエンティティごとに分離できます。たとえば、次のいずれかのユースケースでは複数のテナント アカウントを使用できます。

* *エンタープライズの使用例:* StorageGRIDシステムを企業内で使用している場合、グリッドのオブジェクト ストレージは組織内のさまざまな部門によって分離されている可能性があります。たとえば、マーケティング部門、カスタマー サポート部門、人事部門などのテナント アカウントが存在する場合があります。
+

NOTE: S3 クライアント プロトコルを使用する場合は、S3 バケットとバケット ポリシーを使用して、企業内の部門間でオブジェクトを分離することもできます。個別のテナント アカウントを作成する必要はありません。実装手順を参照link:../s3/bucket-and-group-access-policies.html["S3 バケットとバケットポリシー"]詳細についてはこちらをご覧ください。

* *サービス プロバイダーの使用例:* StorageGRIDシステムがサービス プロバイダーによって使用されている場合、グリッドのオブジェクト ストレージは、ストレージをリースするさまざまなエンティティによって分離される可能性があります。たとえば、会社 A、会社 B、会社 C などのテナント アカウントが存在する場合があります。




== テナントアカウントを作成する方法

テナントアカウントは、link:../admin/managing-tenants.html["グリッド マネージャを使用するStorageGRIDグリッド管理者"] 。テナント アカウントを作成するときに、グリッド管理者は次のことを指定します。

* テナント名、クライアント タイプ (S3)、オプションのストレージ クォータなどの基本情報。
* テナント アカウントの権限 (テナント アカウントが S3 プラットフォーム サービスを使用できるかどうか、独自の ID ソースを設定できるかどうか、S3 Select を使用できるかどうか、グリッド フェデレーション接続を使用できるかどうかなど)。
* StorageGRIDシステムがローカル グループとユーザー、ID フェデレーション、またはシングル サインオン (SSO) を使用するかどうかに基づく、テナントの初期ルート アクセス。


さらに、S3 テナント アカウントが規制要件に準拠する必要がある場合、グリッド管理者はStorageGRIDシステムの S3 オブジェクト ロック設定を有効にすることができます。  S3 オブジェクト ロックを有効にすると、すべての S3 テナント アカウントが準拠バケットを作成および管理できるようになります。



=== S3テナントを構成する

その後link:../admin/creating-tenant-account.html["S3テナントアカウントが作成される"]、テナント マネージャーにアクセスして、次のようなタスクを実行できます。

* アイデンティティ フェデレーションを設定する (アイデンティティ ソースがグリッドと共有されていない場合)
* グループとユーザーの管理
* アカウントのクローンとクロスグリッドレプリケーションにグリッドフェデレーションを使用する
* S3 アクセスキーを管理する
* S3バケットの作成と管理
* S3プラットフォームサービスを使用する
* S3 Selectを使用する
* ストレージ使用量を監視する



TIP: テナントマネージャでS3バケットを作成および管理できますが、link:../s3/index.html["S3クライアント"]またはlink:use-s3-console.html["S3 コンソール"]オブジェクトを取り込んで管理します。
