---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: テナント グループを作成する前に、そのグループに割り当てる権限を検討してください。テナント管理権限によって、ユーザーがテナント マネージャーまたはテナント管理 API を使用して実行できるタスクが決まります。ユーザーは 1 つ以上のグループに所属できます。ユーザーが複数のグループに属している場合、権限は累積されます。 
---
= テナント管理権限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナント グループを作成する前に、そのグループに割り当てる権限を検討してください。テナント管理権限によって、ユーザーがテナント マネージャーまたはテナント管理 API を使用して実行できるタスクが決まります。ユーザーは 1 つ以上のグループに所属できます。ユーザーが複数のグループに属している場合、権限は累積されます。

テナント マネージャーにサインインしたり、テナント管理 API を使用したりするには、ユーザーは少なくとも 1 つの権限を持つグループに属している必要があります。サインインできるすべてのユーザーは、次のタスクを実行できます。

* ダッシュボードを見る
* 自分のパスワードを変更する（ローカルユーザーの場合）


すべての権限について、グループのアクセス モード設定によって、ユーザーが設定を変更して操作を実行できるかどうか、または関連する設定と機能の表示のみが可能かどうかが決まります。


NOTE: ユーザーが複数のグループに属しており、いずれかのグループが読み取り専用に設定されている場合、ユーザーは選択したすべての設定と機能に対して読み取り専用アクセス権を持ちます。

グループには次の権限を割り当てることができます。S3 テナントと Swift テナントには異なるグループ権限があることに注意してください。

[cols="1a,3a,3a"]
|===
| 許可 | 説明 | 詳細 


 a| 
ルート アクセス
 a| 
テナント マネージャーとテナント管理 API へのフル アクセスを提供します。
 a| 
Swift ユーザーは、テナント アカウントにサインインするためにルート アクセス権限を持っている必要があります。



 a| 
管理者
 a| 
Swift テナントのみ。このテナント アカウントの Swift コンテナとオブジェクトへのフル アクセスを提供します
 a| 
Swift ユーザーは、Swift REST API を使用して操作を実行するために、Swift 管理者権限を持っている必要があります。



 a| 
独自のS3認証情報を管理する
 a| 
ユーザーが独自の S3 アクセスキーを作成および削除できるようにします。
 a| 
この権限を持たないユーザーには、*ストレージ (S3)* > *マイ S3 アクセス キー* メニュー オプションは表示されません。



 a| 
すべてのバケットを表示
 a| 
*S3 テナント*: ユーザーがすべてのバケットとバケット構成を表示できるようにします。

*Swift テナント*: Swift ユーザーがテナント管理 API を使用してすべてのコンテナとコンテナ構成を表示できるようにします。
 a| 
すべてのバケットの表示権限またはすべてのバケットの管理権限を持たないユーザーには、*バケット* メニュー オプションは表示されません。

この権限は、すべてのバケットの管理権限に置き換えられます。これは、S3 クライアントまたは S3 コンソールで使用される S3 バケットまたはグループ ポリシーには影響しません。

この権限は、テナント管理 API から Swift グループにのみ割り当てることができます。テナント マネージャーを使用して、Swift グループにこの権限を割り当てることはできません。



 a| 
すべてのバケットを管理する
 a| 
*S3 テナント*: ユーザーがテナント マネージャーとテナント管理 API を使用して S3 バケットを作成および削除したり、S3 バケットまたはグループ ポリシーに関係なく、テナント アカウント内のすべての S3 バケットの設定を管理したりできるようにします。

*Swift テナント*: Swift ユーザーがテナント管理 API を使用して Swift コンテナの一貫性を制御できるようにします。
 a| 
すべてのバケットの表示権限またはすべてのバケットの管理権限を持たないユーザーには、*バケット* メニュー オプションは表示されません。

この権限は、「すべてのバケットを表示」権限よりも優先されます。これは、S3 クライアントまたは S3 コンソールで使用される S3 バケットまたはグループ ポリシーには影響しません。

この権限は、テナント管理 API から Swift グループにのみ割り当てることができます。テナント マネージャーを使用して、Swift グループにこの権限を割り当てることはできません。



 a| 
エンドポイントを管理する
 a| 
ユーザーがテナント マネージャまたはテナント管理 API を使用して、 StorageGRIDプラットフォーム サービスの宛先として使用されるプラットフォーム サービス エンドポイントを作成または編集できるようにします。
 a| 
この権限を持たないユーザーには、*プラットフォーム サービス エンドポイント* メニュー オプションは表示されません。



 a| 
S3コンソールタブを使用する
 a| 
「すべてのバケットの表示」または「すべてのバケットの管理」権限と組み合わせると、ユーザーはバケットの詳細ページの S3 コンソール タブからオブジェクトを表示および管理できるようになります。
 a| 

|===