---
permalink: tenant/testing-connection-for-platform-services-endpoint.html 
sidebar: sidebar 
keywords: how to test platform services endpoint connection 
summary: プラットフォーム サービスへの接続が変更された場合は、エンドポイントの接続をテストして、宛先リソースが存在し、指定した資格情報を使用してアクセスできることを検証できます。 
---
= プラットフォーム サービス エンドポイントのテスト接続
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プラットフォーム サービスへの接続が変更された場合は、エンドポイントの接続をテストして、宛先リソースが存在し、指定した資格情報を使用してアクセスできることを検証できます。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたは、link:tenant-management-permissions.html["エンドポイントまたはルートアクセス権限を管理する"] 。


.タスク概要
StorageGRID は、資格情報に正しい権限があるかどうかを検証しません。

.手順
. *ストレージ (S3)* > *プラットフォーム サービス エンドポイント* を選択します。
+
プラットフォーム サービス エンドポイント ページが表示され、すでに構成されているプラットフォーム サービス エンドポイントのリストが表示されます。

. 接続をテストするエンドポイントを選択します。
+
エンドポイントの詳細ページが表示されます。

. *テスト接続*を選択します。
+
** 指定された資格情報を使用してエンドポイントに到達できる場合は、成功メッセージが表示されます。エンドポイントへの接続は、各サイトの 1 つのノードから検証されます。
** エンドポイントの検証に失敗した場合、エラー メッセージが表示されます。エラーを修正するためにエンドポイントを変更する必要がある場合は、[*構成*] を選択して情報を更新します。次に、[*テストして変更を保存*]を選択します。



