---
permalink: tenant/understanding-cloudmirror-replication-service.html 
sidebar: sidebar 
keywords: cloudmirror replication 
summary: StorageGRID がバケットに追加された特定のオブジェクトを 1 つ以上の宛先バケットに複製するようにしたい場合は、S3 バケットに対して CloudMirror レプリケーションを有効にすることができます。 
---
= CloudMirrorレプリケーションサービスを理解する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID がバケットに追加された特定のオブジェクトを 1 つ以上の外部宛先バケットに複製するようにする場合は、S3 バケットに対して CloudMirror レプリケーションを有効にすることができます。

たとえば、CloudMirror レプリケーションを使用して特定の顧客レコードを Amazon S3 にミラーリングし、AWS サービスを活用してデータの分析を実行することができます。


NOTE: ソースバケットで S3 オブジェクトロックが有効になっている場合、CloudMirror レプリケーションはサポートされません。



== CloudMirrorとILM

CloudMirror レプリケーションは、グリッドのアクティブな ILM ポリシーとは独立して動作します。 CloudMirror サービスは、オブジェクトがソース バケットに保存されるとすぐにそれを複製し、できるだけ早く宛先バケットに配信します。オブジェクトの取り込みが成功すると、複製されたオブジェクトの配信がトリガーされます。



== CloudMirrorとクロスグリッドレプリケーション

CloudMirror レプリケーションには、クロスグリッド レプリケーション機能との重要な類似点と相違点があります。。 link:../admin/grid-federation-compare-cgr-to-cloudmirror.html["クロスグリッドレプリケーションとCloudMirrorレプリケーションを比較する"] 。



== CloudMirrorとS3バケット

CloudMirror レプリケーションは通常、外部の S3 バケットを宛先として使用するように構成されます。ただし、別のStorageGRIDデプロイメントまたは任意の S3 互換サービスを使用するようにレプリケーションを構成することもできます。

既存のバケット:: 既存のバケットに対して CloudMirror レプリケーションを有効にすると、そのバケットに追加された新しいオブジェクトのみがレプリケートされます。バケット内の既存のオブジェクトは複製されません。既存のオブジェクトのレプリケーションを強制するには、オブジェクトのコピーを実行して既存のオブジェクトのメタデータを更新できます。
+
--

NOTE: CloudMirror レプリケーションを使用してオブジェクトを Amazon S3 の宛先にコピーする場合、Amazon S3 では各 PUT リクエスト ヘッダー内のユーザー定義メタデータのサイズが 2 KB に制限されていることに注意してください。オブジェクトに 2 KB を超えるユーザー定義のメタデータがある場合、そのオブジェクトは複製されません。

--
複数の宛先バケット:: 単一のバケット内のオブジェクトを複数の宛先バケットに複製するには、レプリケーション設定 XML で各ルールの宛先を指定します。オブジェクトを同時に複数のバケットに複製することはできません。
バージョン管理されたバケットまたはバージョン管理されていないバケット:: バージョン管理されたバケットまたはバージョン管理されていないバケットで CloudMirror レプリケーションを設定できます。宛先バケットはバージョン管理付きでもバージョン管理なしでも構いません。バージョン管理されたバケットとバージョン管理されていないバケットを任意に組み合わせて使用できます。たとえば、バージョン管理されたバケットをバージョン管理されていないソース バケットの宛先として指定したり、その逆を行ったりすることができます。バージョン管理されていないバケット間でレプリケートすることもできます。




== 削除、レプリケーションループ、イベント

削除動作:: Amazon S3 サービス、クロスリージョンレプリケーション (CRR) の削除動作と同じです。ソースバケット内のオブジェクトを削除しても、宛先内の複製されたオブジェクトは削除されません。ソースバケットと宛先バケットの両方がバージョン管理されている場合、削除マーカーが複製されます。宛先バケットがバージョン管理されていない場合、ソースバケット内のオブジェクトを削除しても、削除マーカーが宛先バケットに複製されず、宛先オブジェクトも削除されません。
レプリケーションループからの保護:: オブジェクトが宛先バケットに複製されると、 StorageGRID はそれらを「レプリカ」としてマークします。宛先StorageGRIDバケットは、レプリカとしてマークされたオブジェクトを再度レプリケートしないため、偶発的なレプリケーション ループから保護されます。このレプリカ マーキングはStorageGRID内部のものであり、Amazon S3 バケットを宛先として使用するときに AWS CRR を活用できないことはありません。
+
--

NOTE: レプリカをマークするために使用されるカスタムヘッダーは `x-ntap-sg-replica`。このマーキングはカスケードミラーを防止します。  StorageGRID は、2 つのグリッド間の双方向 CloudMirror をサポートしています。

--
宛先バケット内のイベント:: 宛先バケット内のイベントの一意性と順序は保証されません。配信の成功を保証するために実行された操作の結果として、ソース オブジェクトの複数の同一コピーが宛先に配信される場合があります。まれに、同じオブジェクトが 2 つ以上の異なるStorageGRIDサイトから同時に更新されると、宛先バケットでの操作の順序がソース バケットでのイベントの順序と一致しない場合があります。

