---
permalink: tenant/understanding-notifications-for-buckets.html 
sidebar: sidebar 
keywords: s3 bucket event notification, sequencer key 
summary: StorageGRID が指定されたイベントに関する通知を宛先の Kafka クラスターまたは Amazon Simple Notification Service に送信するようにする場合は、S3 バケットのイベント通知を有効にすることができます。 
---
= バケットの通知を理解する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID が指定されたイベントに関する通知を宛先の Kafka クラスターまたは Amazon Simple Notification Service に送信するようにする場合は、S3 バケットのイベント通知を有効にすることができます。

たとえば、バケットに追加された各オブジェクト（重要なシステム イベントに関連付けられたログ ファイルを表すオブジェクト）に関するアラートを管理者に送信するように設定できます。

イベント通知は、通知設定で指定されたとおりにソース バケットで作成され、宛先に配信されます。オブジェクトに関連付けられたイベントが成功すると、そのイベントに関する通知が作成され、配信のためにキューに入れられます。

通知の一意性と順序は保証されません。配信の成功を保証するために実行された操作の結果として、イベントの通知が複数宛先に配信される場合があります。また、配信は非同期であるため、特に異なるStorageGRIDサイトから発信された操作の場合、宛先での通知の時間順序がソース バケット上のイベントの順序と一致することは保証されません。使用することができます `sequencer`Amazon S3 ドキュメントで説明されているように、イベント メッセージ内のキーを使用して、特定のオブジェクトのイベントの順序を決定します。

StorageGRIDイベント通知は、いくつかの制限付きで Amazon S3 API に準拠します。

* 次のイベント タイプがサポートされています。
+
** s3:オブジェクトが作成されました:
** s3:オブジェクト作成:配置
** s3:オブジェクト作成:投稿
** s3:オブジェクト作成:コピー
** s3:ObjectCreated:CompleteMultipartUpload
** s3:オブジェクトが削除されました:
** s3:オブジェクトが削除されました:削除
** s3:オブジェクトが削除されました:削除マーカーが作成されました
** s3:オブジェクトの復元:投稿


* StorageGRIDから送信されるイベント通知では標準の JSON 形式が使用されますが、表に示すように、一部のキーは含まれず、他のキーには特定の値が使用されます。


[cols="1a,2a"]
|===
| キー名 | StorageGRIDの価値 


 a| 
イベントソース
 a| 
`sgws:s3`



 a| 
awsリージョン
 a| 
_含まれていません_



 a| 
x-amz-id-2
 a| 
_含まれていません_



 a| 
アーン
 a| 
`urn:sgws:s3:::bucket_name`

|===