---
permalink: tenant/use-s3-console.html 
sidebar: sidebar 
keywords: how to use s3 console 
summary: S3 コンソールを使用して、S3 バケット内のオブジェクトを表示および管理できます。 
---
= S3コンソールを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 コンソールを使用して、S3 バケット内のオブジェクトを表示および管理できます。

S3 コンソールでは次のことが可能です。

* オブジェクトのアップロード、ダウンロード、名前変更、コピー、移動、削除
* オブジェクトのバージョンを表示、元に戻す、ダウンロード、削除する
* 接頭辞でオブジェクトを検索する
* オブジェクトタグを管理する
* オブジェクトのメタデータを表示する
* フォルダの表示、作成、名前の変更、コピー、移動、削除


[NOTE]
====
S3 コンソールは、最も一般的なケースにおいて、改善されたユーザー エクスペリエンスを提供します。あらゆる状況で CLI または API 操作を置き換えるようには設計されていません。

S3 コンソールを使用すると操作に時間がかかりすぎる場合 (数分または数時間など)、次のことを検討してください。

* 選択したオブジェクトの数を減らす
* 非グラフィカル（API または CLI）メソッドを使用してデータにアクセスする


====
.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* オブジェクトを管理する場合は、ルート アクセス権限を持つユーザー グループに属している必要があります。または、「S3 コンソール タブの使用」権限と、「すべてのバケットの表示」権限または「すべてのバケットの管理」権限のいずれかを持つユーザー グループに属しています。見るlink:tenant-management-permissions.html["テナント管理権限"] 。
* ユーザーに対して S3 グループまたはバケット ポリシーが設定されています。見るlink:../s3/bucket-and-group-access-policies.html["バケットとグループのアクセスポリシーを使用する"] 。
* ユーザーのアクセス キー ID とシークレット アクセス キーがわかっています。オプションとして、 `.csv`この情報を含むファイル。参照link:creating-your-own-s3-access-keys.html["アクセスキーの作成手順"]。


.手順
. *ストレージ* > *バケット* > *_バケット名_* を選択します。
. S3 コンソールタブを選択します。
. アクセス キー ID とシークレット アクセス キーをフィールドに貼り付けます。それ以外の場合は、「アクセスキーをアップロード」を選択し、 `.csv`ファイル。
. *Sign in*を選択します。
. バケット オブジェクトのテーブルが表示されます。必要に応じてオブジェクトを管理できます。


.追加情報
* *プレフィックスによる検索*: プレフィックス検索機能は、現在のフォルダーを基準として特定の単語で始まるオブジェクトのみを検索します。検索には、他の場所にその単語が含まれるオブジェクトは含まれません。このルールはフォルダー内のオブジェクトにも適用されます。例えば、 `folder1/folder2/somefile-`範囲内のオブジェクトを返します `folder1/folder2/`フォルダと単語で始まる `somefile-`。
* *ドラッグ アンド ドロップ*: コンピュータのファイル マネージャーから S3 コンソールにファイルをドラッグ アンド ドロップできます。ただし、フォルダをアップロードすることはできません。
* *フォルダーの操作*: フォルダーを移動、コピー、または名前変更すると、フォルダー内のすべてのオブジェクトが一度に 1 つずつ更新されるため、時間がかかる場合があります。
* *バケットのバージョン管理が無効になっている場合の永続的な削除*: バージョン管理が無効になっているバケット内のオブジェクトを上書きまたは削除すると、その操作は永続的になります。見るlink:changing-bucket-versioning.html["バケットのオブジェクトのバージョン管理を変更する"] 。

