---
permalink: tenant/using-storagegrid-tenant-account.html 
sidebar: sidebar 
keywords: how to use tenant account 
summary: 'テナント アカウントを使用すると、Simple Storage Service (S3) REST API を使用して、 StorageGRIDシステムにオブジェクトを保存および取得できます。' 
---
= StorageGRIDテナントアカウントを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナント アカウントを使用すると、Simple Storage Service (S3) REST API を使用して、 StorageGRIDシステム内のオブジェクトを保存および取得できます。

各テナント アカウントには、独自のフェデレーション グループまたはローカル グループ、ユーザー、S3 バケット、オブジェクトがあります。


TIP: このバージョンのドキュメント サイトから Swift の詳細は削除されました。見る https://docs.netapp.com/us-en/storagegrid-118/tenant/using-storagegrid-tenant-account.html["StorageGRID 11.8: StorageGRIDテナントアカウントを使用する"^]。

オプションで、テナント アカウントを使用して、保存されたオブジェクトを異なるエンティティごとに分離できます。たとえば、次のいずれかのユースケースでは複数のテナント アカウントを使用できます。

* *エンタープライズの使用例:* StorageGRIDシステムを企業内で使用している場合、グリッドのオブジェクト ストレージは組織内のさまざまな部門によって分離されている可能性があります。たとえば、マーケティング部門、カスタマー サポート部門、人事部門などのテナント アカウントが存在する場合があります。
+

NOTE: S3 クライアント プロトコルを使用する場合は、S3 バケットとバケット ポリシーを使用して、企業内の部門間でオブジェクトを分離することもできます。個別のテナント アカウントを作成する必要はありません。実装手順を参照link:../s3/bucket-and-group-access-policies.html["S3 バケットとバケットポリシー"]詳細についてはこちらをご覧ください。

* *サービス プロバイダーの使用例:* StorageGRIDシステムがサービス プロバイダーによって使用されている場合、グリッドのオブジェクト ストレージは、ストレージをリースするさまざまなエンティティによって分離される可能性があります。たとえば、会社 A、会社 B、会社 C などのテナント アカウントが存在する場合があります。




== テナントアカウントを作成する

テナント アカウントは、グリッド マネージャを使用してStorageGRIDグリッド管理者によって作成されます。テナント アカウントを作成するときに、グリッド管理者は次の情報を指定します。

* テナントの表示名 (テナントのアカウント ID は自動的に割り当てられ、変更できません)。
* テナント アカウントが S3 プロトコルを使用するか、Swift プロトコルを使用するか。
* S3 テナント アカウントの場合: テナント アカウントがプラットフォーム サービスの使用を許可されているかどうか。プラットフォーム サービスの使用が許可されている場合は、その使用をサポートするようにグリッドを構成する必要があります。
* オプションで、テナント アカウントのストレージ クォータ (テナントのオブジェクトに使用できるギガバイト、テラバイト、またはペタバイトの最大数)。テナントのストレージ クォータは、物理的な量 (ディスク上のサイズ) ではなく、論理的な量 (オブジェクト サイズ) を表します。
* StorageGRIDシステムで ID フェデレーションが有効になっている場合、どのフェデレーション グループにテナント アカウントを構成するためのルート アクセス権限があるか。
* StorageGRIDシステムでシングル サインオン (SSO) が使用されていない場合、テナント アカウントが独自の ID ソースを使用するか、グリッドの ID ソースを共有するか、およびテナントのローカル ルート ユーザーの初期パスワード。


さらに、S3 テナント アカウントが規制要件に準拠する必要がある場合、グリッド管理者はStorageGRIDシステムの S3 オブジェクト ロック設定を有効にすることができます。  S3 オブジェクト ロックを有効にすると、すべての S3 テナント アカウントが準拠バケットを作成および管理できるようになります。



== S3テナントを構成する

S3 テナント アカウントが作成されると、テナント マネージャーにアクセスして次のようなタスクを実行できます。

* アイデンティティフェデレーションの設定（アイデンティティソースがグリッドと共有されていない場合）、またはローカルグループとユーザーの作成
* S3 アクセスキーの管理
* 準拠バケットを含む S3 バケットの作成と管理
* プラットフォーム サービスの使用 (有効な場合)
* ストレージ使用量の監視



TIP: テナント マネージャーを使用して S3 バケットを作成および管理できますが、オブジェクトの取り込みと管理には S3 アクセス キーが必要であり、S3 REST API を使用する必要があります。

.関連情報
* link:../admin/index.html["StorageGRIDの管理"]
* link:../s3/index.html["S3 REST APIを使用する"]

