---
permalink: tenant/viewing-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view other user access key 
summary: S3 テナントを使用しており、適切な権限を持っている場合は、他のユーザーの S3 アクセス キーを表示できます。リストを有効期限で並べ替えることができるので、どのキーがもうすぐ期限切れになるかを判断できます。必要に応じて、新しいキーを作成したり、使用されなくなったキーを削除したりできます。 
---
= 他のユーザーの S3 アクセスキーを表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 テナントを使用しており、適切な権限を持っている場合は、他のユーザーの S3 アクセス キーを表示できます。リストを有効期限で並べ替えることができるので、どのキーがもうすぐ期限切れになるかを判断できます。必要に応じて、新しいキーを作成したり、使用されなくなったキーを削除したりできます。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:tenant-management-permissions.html["ルートアクセス権限"]。



CAUTION: ユーザーに属する S3 バケットとオブジェクトには、テナント マネージャーでそのユーザーに対して表示されるアクセス キー ID とシークレット アクセス キーを使用してアクセスできます。このため、アクセス キーはパスワードと同じように保護してください。アクセス キーを定期的にローテーションし、使用されていないキーはアカウントから削除し、他のユーザーと共有しないでください。

.手順
. *アクセス管理* > *ユーザー*を選択します。
. 「ユーザー」ページで、S3 アクセスキーを表示するユーザーを選択します。
. ユーザー詳細ページで、*アクセス キー*を選択します。
. キーを*有効期限*または*アクセス キー ID*で並べ替えます。
. 必要に応じて、新しいキーを作成し、使用されなくなったキーを手動で削除します。
+
既存のキーの有効期限が切れる前に新しいキーを作成すると、ユーザーはアカウント内のオブジェクトへのアクセスを一時的に失うことなく、新しいキーの使用を開始できます。

+
期限切れのキーは自動的に削除されます。



.関連情報
* link:creating-another-users-s3-access-keys.html["別のユーザーのS3アクセスキーを作成する"]
* link:deleting-another-users-s3-access-keys.html["他のユーザーのS3アクセスキーを削除する"]

