---
permalink: tenant/viewing-your-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view your s3 access key 
summary: S3 テナントを使用しており、適切な権限がある場合は、S3 アクセスキーのリストを表示できます。リストを有効期限で並べ替えることができるため、どのキーがもうすぐ期限切れになるかを判断できます。必要に応じて、新しいキーを作成したり、使用しなくなったキーを削除したりできます。 
---
= S3 アクセスキーを表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3テナントを使用しており、link:tenant-management-permissions.html["適切な許可"] 、S3 アクセスキーのリストを表示できます。リストを有効期限で並べ替えることができるため、どのキーがもうすぐ期限切れになるかを判断できます。必要に応じて、link:creating-your-own-s3-access-keys.html["新しいキーを作成する"]またはlink:deleting-your-own-s3-access-keys.html["削除キー"]もう使用していないもの。


CAUTION: アカウントに属する S3 バケットとオブジェクトには、テナント マネージャーでアカウントに対して表示されるアクセス キー ID とシークレット アクセス キーを使用してアクセスできます。このため、アクセス キーはパスワードと同じように保護してください。アクセス キーを定期的にローテーションし、使用していないキーはアカウントから削除し、他のユーザーと共有しないでください。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたは、独自のS3認証情報を管理する権限を持つユーザーグループに属していますlink:tenant-management-permissions.html["アクセス権"]。


.手順
. *ストレージ (S3)* > *マイアクセスキー* を選択します。
. 「マイ アクセス キー」ページで、既存のアクセス キーを *有効期限* または *アクセス キー ID* で並べ替えます。
. 必要に応じて、新しいキーを作成するか、使用しなくなったキーを削除します。
+
既存のキーの有効期限が切れる前に新しいキーを作成すると、アカウント内のオブジェクトへのアクセスを一時的に失うことなく、新しいキーの使用を開始できます。

+
期限切れのキーは自動的に削除されます。


