---
permalink: tenant/viewing-s3-bucket-details.html 
sidebar: sidebar 
keywords: how to view bucket details 
summary: テナント アカウントでバケットを表示できます。 
---
= バケットの詳細を表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナント アカウントでバケットを表示できます。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたは、link:tenant-management-permissions.html["ルートアクセス、すべてのバケットの管理、またはすべてのバケットの表示権限"] 。これらの権限は、グループまたはバケット ポリシーの権限設定をオーバーライドします。


.手順
. ダッシュボードから*バケットの表示*を選択するか、*ストレージ (S3)* > *バケット*を選択します。
+
バケット ページが表示されます。

. 各バケットの概要表を確認します。
+
必要に応じて、任意の列で情報を並べ替えたり、リスト内を前後に移動したりできます。

+

NOTE: 表示されるオブジェクト数、使用領域、使用量の値は推定値です。これらの見積りは、取り込みのタイミング、ネットワーク接続、およびノードの状態によって影響を受けます。バケットでバージョン管理が有効になっている場合、削除されたオブジェクトのバージョンもオブジェクト数に含まれます。

+
Name:: バケットの一意の名前。変更できません。
有効な機能:: バケットに対して有効になっている機能のリスト。
S3 オブジェクトロック:: バケットに対して S3 オブジェクト ロックが有効になっているかどうか。
+
--
この列は、グリッドで S3 オブジェクト ロックが有効になっている場合にのみ表示されます。この列には、従来の準拠バケットの情報も表示されます。

--
リージョン:: バケットのリージョン。変更できません。この列はデフォルトでは非表示になっています。
オブジェクト数:: このバケット内のオブジェクトの数。バケットでバージョン管理が有効になっている場合、この値には現在のオブジェクト以外のバージョンが含まれます。
+
--
オブジェクトが追加または削除されても、この値はすぐに更新されない場合があります。

--
使用スペース:: バケット内のすべてのオブジェクトの論理サイズ。論理サイズには、複製されたコピーや消去コード化されたコピー、あるいはオブジェクト メタデータに必要な実際のスペースは含まれません。
+
--
この値の更新には最大 10 分かかる場合があります。

--
使用法:: バケットの容量制限の使用率（設定されている場合）。
+
--
使用量の値は内部推定に基づいており、場合によっては超過する可能性があります。たとえば、 StorageGRID は、テナントがオブジェクトのアップロードを開始すると容量制限 (設定されている場合) をチェックし、テナントが容量制限を超えている場合はこのバケットへの新しい取り込みを拒否します。ただし、 StorageGRID は、容量制限を超えたかどうかを判断する際に、現在のアップロードのサイズを考慮しません。オブジェクトが削除されると、容量制限の使用量が再計算されるまで、テナントはこのバケットに新しいオブジェクトをアップロードできなくなる場合があります。計算には10分以上かかる場合があります。

この値は、オブジェクトとそのメタデータを格納するために必要な物理サイズではなく、論理サイズを示します。

--
容量:: 設定されている場合、バケットの容量制限。
作成日:: バケットが作成された日時。この列はデフォルトでは非表示になっています。


. 特定のバケットの詳細を表示するには、テーブルからバケット名を選択します。
+
.. Web ページの上部にある概要情報を表示して、リージョンやオブジェクト数などのバケットの詳細を確認します。
.. 容量制限の使用状況バーを表示します。使用率が 100% または 100% に近い場合は、制限を増やすか、一部のオブジェクトを削除することを検討してください。
.. 必要に応じて、「*バケット内のオブジェクトの削除*」と「*バケットの削除*」を選択します。
+
[CAUTION]
====
これらの各オプションを選択したときに表示される注意事項に十分注意してください。詳細については、以下を参照してください。

*** link:deleting-s3-bucket-objects.html["バケット内のすべてのオブジェクトを削除する"]
*** link:deleting-s3-bucket.html["バケットを削除する"](バケットは空である必要があります)


====
.. 必要に応じて、各タブでバケットの設定を表示または変更します。
+
*** *S3 コンソール*: バケットのオブジェクトを表示します。詳細については、 link:use-s3-console.html["S3コンソールを使用する"] 。
*** *バケット オプション*: オプション設定を表示または変更します。  S3 オブジェクトロックなどの一部の設定は、バケットの作成後は変更できません。
+
**** link:manage-bucket-consistency.html["バケットの一貫性を管理する"]
**** link:enabling-or-disabling-last-access-time-updates.html["最終アクセス時間の更新"]
**** link:../tenant/creating-s3-bucket.html#capacity-limit["容量制限"]
**** link:changing-bucket-versioning.html["オブジェクトのバージョン管理"]
**** link:using-s3-object-lock.html["S3 オブジェクトロック"]
**** link:update-default-retention-settings.html["デフォルトのバケット保持"]
**** link:grid-federation-manage-cross-grid-replication.html["クロスグリッドレプリケーションを管理する"]（入居者に許可されている場合）


*** *プラットフォームサービス*:link:considerations-for-platform-services.html["プラットフォームサービスの管理"] （入居者に許可されている場合）
*** *バケット アクセス*: オプション設定を表示または変更します。特定のアクセス権限が必要です。
+
**** 設定link:configuring-cross-origin-resource-sharing-cors.html["クロスオリジンリソース共有（CORS）"]そのため、バケットとバケット内のオブジェクトは他のドメインの Web アプリケーションからアクセスできるようになります。
**** link:../tenant/manage-bucket-policy.html["ユーザーアクセスを制御する"]S3 バケットとそのバケット内のオブジェクト。







