---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html 
sidebar: sidebar 
keywords: how to automate installation 
summary: VMware OVF ツールを使用して、グリッド ノードの展開を自動化できます。  StorageGRIDの構成を自動化することもできます。 
---
= インストールを自動化する (VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware OVF ツールを使用して、グリッド ノードの展開を自動化できます。  StorageGRIDの構成を自動化することもできます。



== グリッドノードの展開を自動化

VMware OVF ツールを使用して、グリッド ノードの展開を自動化します。

.開始する前に
* Bash 3.2 以降を搭載した Linux/Unix システムにアクセスできます。
* VMware vSphere with vCenter をご利用の場合
* VMware OVF Tool 4.1 がインストールされ、正しく構成されています。
* OVFツールを使用してVMware vSphereにアクセスするためのユーザー名とパスワードを知っている
* OVF ファイルから VM を展開して電源をオンにするための十分な権限と、VM に接続する追加のボリュームを作成するための権限があります。参照 `ovftool`詳細についてはドキュメントをご覧ください。
* StorageGRID仮想マシンを展開する vSphere 内の場所の仮想インフラストラクチャ (VI) URL がわかっている必要があります。この URL は通常、vApp またはリソース プールになります。例：  `vi://vcenter.example.com/vi/sgws`
+

NOTE: VMwareを使用することができます `ovftool`この値を決定するユーティリティ（ `ovftool`詳細についてはドキュメントを参照してください。

+

NOTE: vApp にデプロイする場合、仮想マシンは初回は自動的に起動しないため、手動で電源をオンにする必要があります。

* デプロイメント構成ファイルに必要なすべての情報を収集しました。見るlink:collecting-information-about-your-deployment-environment.html["展開環境に関する情報を収集する"]情報については。
* StorageGRIDの VMware インストール アーカイブから次のファイルにアクセスできます。


[cols="1a,1a"]
|===
| ファイル名 | 説明 


| NetApp-SG バージョン-SHA.vmdk  a| 
グリッド ノード仮想マシンを作成するためのテンプレートとして使用される仮想マシン ディスク ファイル。

*注意:* このファイルは、 `.ovf`そして `.mf`ファイル。



| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
オープン仮想化フォーマットのテンプレートファイル(`.ovf`）およびマニフェストファイル(`.mf`) を使用してプライマリ管理ノードを展開します。



| vsphere-non-primary-admin.ovf vsphere-non-primary-admin.mf  a| 
テンプレートファイル(`.ovf`）およびマニフェストファイル(`.mf`) を使用して、プライマリ以外の管理ノードを展開します。



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
テンプレートファイル(`.ovf`）およびマニフェストファイル(`.mf`) ゲートウェイ ノードを展開します。



| vsphere-storage.ovf vsphere-storage.mf  a| 
テンプレートファイル(`.ovf`）およびマニフェストファイル(`.mf`) を使用して、仮想マシンベースのストレージ ノードを展開します。



| デプロイvsphere-ovftool.sh  a| 
仮想グリッド ノードのデプロイメントを自動化するために使用される Bash シェル スクリプト。



| デプロイ-vsphere-ovftool-sample.ini  a| 
で使用するサンプル設定ファイルは、 `deploy-vsphere-ovftool.sh`スクリプト。

|===


=== デプロイメント用の構成ファイルを定義する

StorageGRIDの仮想グリッドノードを展開するために必要な情報を構成ファイルに指定します。この情報は `deploy-vsphere-ovftool.sh`Bash スクリプト。サンプル構成ファイルを変更することで、ファイルを最初から作成する必要がなくなります。

.手順
. サンプル設定ファイルのコピーを作成する(`deploy-vsphere-ovftool.sample.ini`）。新しいファイルを `deploy-vsphere-ovftool.ini`同じディレクトリに `deploy-vsphere-ovftool.sh`。
. 開ける `deploy-vsphere-ovftool.ini`。
. VMware 仮想グリッド ノードを展開するために必要なすべての情報を入力します。
+
見る<<configuration-file-settings,設定ファイルの設定>>情報については。

. 必要な情報をすべて入力して確認したら、ファイルを保存して閉じます。




=== 設定ファイルの設定

その `deploy-vsphere-ovftool.ini`構成ファイルには、仮想グリッド ノードを展開するために必要な設定が含まれています。

構成ファイルには、最初にグローバル パラメータがリストされ、次にノード名で定義されたセクションにノード固有のパラメータがリストされます。ファイルを使用する場合:

* _グローバル パラメータ_ はすべてのグリッド ノードに適用されます。
* _ノード固有のパラメータ_ はグローバル パラメータをオーバーライドします。




==== グローバルパラメータ

グローバル パラメータは、個々のセクションの設定によって上書きされない限り、すべてのグリッド ノードに適用されます。複数のノードに適用されるパラメータをグローバル パラメータ セクションに配置し、必要に応じて個々のノードのセクションでこれらの設定をオーバーライドします。

* *OVFTOOL_ARGUMENTS*: OVFTOOL_ARGUMENTS をグローバル設定として指定することも、特定のノードに個別に引数を適用することもできます。例えば：
+
[listing, subs="specialcharacters,quotes"]
----
OVFTOOL_ARGUMENTS = --powerOn --noSSLVerify --diskMode=eagerZeroedThick --datastore='_datastore_name_'
----
+
使用することができます `--powerOffTarget`そして `--overwrite`既存の仮想マシンをシャットダウンして置き換えるオプション。

+

CAUTION: ノードを異なるデータストアにデプロイし、グローバルではなくノードごとに OVFTOOL_ARGUMENTS を指定する必要があります。

* *ソース*: StorageGRID仮想マシンテンプレートへのパス(`.vmdk`)ファイルと `.ovf`そして `.mf`個々のグリッド ノードのファイル。デフォルトでは現在のディレクトリになります。
+
[listing, subs="specialcharacters,quotes"]
----
SOURCE = /downloads/StorageGRID-Webscale-_version_/vsphere
----
* *TARGET*: StorageGRIDがデプロイされる場所の VMware vSphere 仮想インフラストラクチャ (vi) URL。例えば：
+
[listing]
----
TARGET = vi://vcenter.example.com/vm/sgws
----
* *GRID_NETWORK_CONFIG*: IP アドレスを取得するために使用される方法 (STATIC または DHCP)。デフォルトはSTATICです。すべてのノードまたはほとんどのノードが IP アドレスを取得するために同じ方法を使用する場合は、ここでその方法を指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
GRID_NETWORK_CONFIG = STATIC
----
* *GRID_NETWORK_TARGET*: グリッド ネットワークに使用する既存の VMware ネットワークの名前。すべてのノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここで指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
GRID_NETWORK_TARGET = SG Admin Network
----
* *GRID_NETWORK_MASK*: グリッド ネットワークのネットワーク マスク。すべてのノードまたはほとんどのノードが同じネットワーク マスクを使用する場合は、ここで指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
GRID_NETWORK_MASK = 255.255.255.0
----
* *GRID_NETWORK_GATEWAY*: グリッド ネットワークのネットワーク ゲートウェイ。すべてのノードまたはほとんどのノードが同じネットワーク ゲートウェイを使用する場合は、ここで指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
GRID_NETWORK_GATEWAY = 10.1.0.1
----
* *GRID_NETWORK_MTU*: オプション。グリッド ネットワーク上の最大転送単位 (MTU)。指定する場合、値は 1280 ～ 9216 の範囲でなければなりません。例えば：
+
[listing]
----
GRID_NETWORK_MTU = 9000
----
+
省略した場合は 1400 が使用されます。

+
ジャンボ フレームを使用する場合は、MTU を 9000 などのジャンボ フレームに適した値に設定します。それ以外の場合はデフォルト値を維持します。

+

NOTE: ネットワークの MTU 値は、ノードが接続されている vSphere の仮想スイッチ ポートで構成された値と一致する必要があります。そうしないと、ネットワーク パフォーマンスの問題やパケット損失が発生する可能性があります。

+

NOTE: 最適なネットワーク パフォーマンスを得るには、すべてのノードのグリッド ネットワーク インターフェイスで同様の MTU 値を構成する必要があります。個々のノード上のグリッド ネットワークの MTU 設定に大きな違いがある場合、*グリッド ネットワーク MTU 不一致* アラートがトリガーされます。  MTU 値はすべてのネットワーク タイプで同じである必要はありません。

* *ADMIN_NETWORK_CONFIG*: IP アドレスを取得するために使用される方法 (DISABLED、STATIC、DHCP のいずれか)。デフォルトはDISABLEDです。すべてのノードまたはほとんどのノードが IP アドレスを取得するために同じ方法を使用する場合は、ここでその方法を指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
ADMIN_NETWORK_CONFIG = STATIC
----
* *ADMIN_NETWORK_TARGET*: 管理ネットワークに使用する既存の VMware ネットワークの名前。管理ネットワークが無効になっていない限り、この設定は必須です。すべてのノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここで指定できます。グリッド ネットワークとは異なり、すべてのノードを同じ管理ネットワークに接続する必要はありません。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
ADMIN_NETWORK_TARGET = SG Admin Network
----
* *ADMIN_NETWORK_MASK*: 管理ネットワークのネットワーク マスク。静的 IP アドレスを使用している場合は、この設定が必要です。すべてのノードまたはほとんどのノードが同じネットワーク マスクを使用する場合は、ここで指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
ADMIN_NETWORK_MASK = 255.255.255.0
----
* *ADMIN_NETWORK_GATEWAY*: 管理ネットワークのネットワークゲートウェイ。静的 IP アドレスを使用し、ADMIN_NETWORK_ESL 設定で外部サブネットを指定する場合は、この設定が必要です。 (つまり、ADMIN_NETWORK_ESL が空の場合は必要ありません。)すべてのノードまたはほとんどのノードが同じネットワーク ゲートウェイを使用する場合は、ここで指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
ADMIN_NETWORK_GATEWAY = 10.3.0.1
----
* *ADMIN_NETWORK_ESL*: 管理ネットワークの外部サブネット リスト (ルート)。CIDR ルートの宛先のコンマ区切りリストとして指定されます。すべてのノードまたはほとんどのノードが同じ外部サブネット リストを使用する場合は、ここで指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
ADMIN_NETWORK_ESL = 172.16.0.0/21,172.17.0.0/21
----
* *ADMIN_NETWORK_MTU*: オプション。管理ネットワーク上の最大転送単位 (MTU)。 ADMIN_NETWORK_CONFIG = DHCP の場合は指定しないでください。指定する場合、値は 1280 ～ 9216 の範囲でなければなりません。省略した場合は 1400 が使用されます。ジャンボ フレームを使用する場合は、MTU を 9000 などのジャンボ フレームに適した値に設定します。それ以外の場合は、デフォルト値を維持します。すべてのノードまたはほとんどのノードが管理ネットワークに同じ MTU を使用する場合は、ここで指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
ADMIN_NETWORK_MTU = 8192
----
* *CLIENT_NETWORK_CONFIG*: IP アドレスを取得するために使用される方法 (DISABLED、STATIC、DHCP のいずれか)。デフォルトはDISABLEDです。すべてのノードまたはほとんどのノードが IP アドレスを取得するために同じ方法を使用する場合は、ここでその方法を指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
CLIENT_NETWORK_CONFIG = STATIC
----
* *CLIENT_NETWORK_TARGET*: クライアント ネットワークに使用する既存の VMware ネットワークの名前。クライアント ネットワークが無効になっていない限り、この設定は必須です。すべてのノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここで指定できます。グリッド ネットワークとは異なり、すべてのノードが同じクライアント ネットワークに接続する必要はありません。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
CLIENT_NETWORK_TARGET = SG Client Network
----
* *CLIENT_NETWORK_MASK*: クライアント ネットワークのネットワーク マスク。静的 IP アドレスを使用している場合は、この設定が必要です。すべてのノードまたはほとんどのノードが同じネットワーク マスクを使用する場合は、ここで指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
CLIENT_NETWORK_MASK = 255.255.255.0
----
* *CLIENT_NETWORK_GATEWAY*: クライアント ネットワークのネットワーク ゲートウェイ。静的 IP アドレスを使用している場合は、この設定が必要です。すべてのノードまたはほとんどのノードが同じネットワーク ゲートウェイを使用する場合は、ここで指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
CLIENT_NETWORK_GATEWAY = 10.4.0.1
----
* *CLIENT_NETWORK_MTU*: オプション。クライアント ネットワーク上の最大転送単位 (MTU)。 CLIENT_NETWORK_CONFIG = DHCP の場合は指定しないでください。指定する場合、値は 1280 ～ 9216 の範囲でなければなりません。省略した場合は 1400 が使用されます。ジャンボ フレームを使用する場合は、MTU を 9000 などのジャンボ フレームに適した値に設定します。それ以外の場合は、デフォルト値を維持します。すべてのノードまたはほとんどのノードがクライアント ネットワークに同じ MTU を使用する場合は、ここで指定できます。その後、1 つまたは複数の個別のノードに対して異なる設定を指定して、グローバル設定を上書きできます。例えば：
+
[listing]
----
CLIENT_NETWORK_MTU = 8192
----
* *PORT_REMAP*: 内部グリッド ノード通信または外部通信のためにノードが使用するポートを再マップします。エンタープライズ ネットワーク ポリシーによってStorageGRIDが使用する 1 つ以上のポートが制限されている場合は、ポートの再マッピングが必要です。  StorageGRIDで使用されるポートのリストについては、内部グリッドノード通信および外部通信を参照してください。link:../network/index.html["ネットワークガイドライン"] 。
+

NOTE: ロード バランサーのエンドポイントを構成するために使用する予定のポートを再マップしないでください。

+

NOTE: PORT_REMAP のみが設定されている場合、指定したマッピングは受信通信と送信通信の両方に使用されます。  PORT_REMAP_INBOUND も指定されている場合、PORT_REMAP は送信通信にのみ適用されます。

+
使用される形式は次のとおりです。 `_network type/protocol/default port used by grid node/new port_`ここで、ネットワーク タイプはグリッド、管理者、またはクライアントであり、プロトコルは tcp または udp です。

+
例えば：

+
[listing]
----
PORT_REMAP = client/tcp/18082/443
----
+
この例の設定を単独で使用すると、グリッド ノードの受信通信と送信通信の両方がポート 18082 からポート 443 に対称的にマッピングされます。  PORT_REMAP_INBOUND と組み合わせて使用すると、この例の設定では、ポート 18082 からの送信通信がポート 443 にマッピングされます。

+
カンマ区切りのリストを使用して複数のポートを再マップすることもできます。

+
例えば：

+
[listing]
----
PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80
----
* *PORT_REMAP_INBOUND*: 指定されたポートの受信通信を再マップします。  PORT_REMAP_INBOUND を指定しても、PORT_REMAP の値を指定しない場合は、ポートの送信通信は変更されません。
+

NOTE: ロード バランサーのエンドポイントを構成するために使用する予定のポートを再マップしないでください。

+
使用される形式は次のとおりです。 `_network type_/_protocol/_default port used by grid node_/_new port_`ここで、ネットワーク タイプはグリッド、管理者、またはクライアントであり、プロトコルは tcp または udp です。

+
例えば：

+
[listing]
----
PORT_REMAP_INBOUND = client/tcp/443/18082
----
+
この例では、内部ファイアウォールを通過するためにポート 443 に送信されるトラフィックを取得し、グリッド ノードが S3 要求をリッスンしているポート 18082 に送信します。

+
カンマ区切りのリストを使用して複数の受信ポートを再マップすることもできます。

+
例えば：

+
[listing]
----
PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22
----
* *TEMPORARY_PASSWORD_TYPE*​​: ノードがグリッドに参加する前に、VM コンソールまたはStorageGRIDインストール API にアクセスするとき、または SSH を使用するときに使用する一時インストール パスワードのタイプ。
+

TIP: すべてのノードまたはほとんどのノードが同じタイプの一時インストール パスワードを使用する場合は、グローバル パラメータ セクションでそのタイプを指定します。次に、オプションで個々のノードに異なる設定を使用します。たとえば、*カスタム パスワードを使用する*をグローバルに選択すると、*CUSTOM_TEMPORARY_PASSWORD=<password>* を使用して各ノードのパスワードを設定できます。

+
*TEMPORARY_PASSWORD_TYPE* は次のいずれかになります。

+
** *ノード名を使用*: ノード名は一時的なインストール パスワードとして使用され、VM コンソール、 StorageGRIDインストール API、および SSH へのアクセスを提供します。
** *パスワードを無効にする*: 一時インストール パスワードは使用されません。インストールの問題をデバッグするためにVMにアクセスする必要がある場合は、link:troubleshooting-installation-issues.html["インストールの問題のトラブルシューティング"] 。
** *カスタム パスワードを使用する*: *CUSTOM_TEMPORARY_PASSWORD=<password>* で指定された値は、一時的なインストール パスワードとして使用され、VM コンソール、 StorageGRIDインストール API、および SSH へのアクセスを提供します。
+

TIP: オプションで、*TEMPORARY_PASSWORD_TYPE* パラメータを省略し、*CUSTOM_TEMPORARY_PASSWORD=<password>* のみを指定することもできます。



* *CUSTOM_TEMPORARY_PASSWORD=<パスワード>* オプション。  VM コンソール、 StorageGRIDインストール API、および SSH にアクセスするときにインストール中に使用する一時パスワード。  *TEMPORARY_PASSWORD_TYPE*​​ が *ノード名を使用する* または *パスワードを無効にする* に設定されている場合は無視されます。




==== ノード固有のパラメータ

各ノードは構成ファイルの独自のセクションにあります。各ノードには次の設定が必要です。

* セクション ヘッダーは、グリッド マネージャーに表示されるノード名を定義します。ノードのオプションの NODE_NAME パラメータを指定することにより、その値を上書きできます。
* *NODE_TYPE*: VM_Admin_Node、VM_Storage_Node、または VM_API_Gateway_Node
* *STORAGE_TYPE*: 結合、データ、またはメタデータ。ストレージ ノードのこのオプション パラメータは、指定されていない場合はデフォルトで結合 (データとメタデータ) になります。詳細については、以下を参照してください。 link:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードの種類"] 。
* *GRID_NETWORK_IP*: グリッド ネットワーク上のノードの IP アドレス。
* *ADMIN_NETWORK_IP*: 管理ネットワーク上のノードの IP アドレス。ノードが管理ネットワークに接続され、ADMIN_NETWORK_CONFIG が STATIC に設定されている場合にのみ必要です。
* *CLIENT_NETWORK_IP*: クライアント ネットワーク上のノードの IP アドレス。ノードがクライアント ネットワークに接続され、このノードの CLIENT_NETWORK_CONFIG が STATIC に設定されている場合にのみ必要です。
* *ADMIN_IP*: グリッド ネットワーク上のプライマリ管理ノードの IP アドレス。プライマリ管理ノードの GRID_NETWORK_IP として指定した値を使用します。このパラメータを省略すると、ノードは mDNS を使用してプライマリ管理ノードの IP を検出しようとします。詳細については、以下を参照してください。 link:how-grid-nodes-discover-primary-admin-node.html["グリッドノードがプライマリ管理ノードを検出する方法"] 。
+

NOTE: プライマリ管理ノードでは ADMIN_IP パラメータは無視されます。

* グローバルに設定されなかったパラメータ。たとえば、ノードが管理ネットワークに接続されていて、ADMIN_NETWORK パラメータをグローバルに指定していない場合は、ノードに対してパラメータを指定する必要があります。


.プライマリ管理ノード
プライマリ管理ノードには次の追加設定が必要です。

* *ノードタイプ*: VM_Admin_Node
* *ADMIN_ROLE*: プライマリ


この例のエントリは、3 つのネットワークすべてに存在するプライマリ管理ノード用です。

[listing]
----
[DC1-ADM1]
  ADMIN_ROLE = Primary
  NODE_TYPE = VM_Admin_Node
  TEMPORARY_PASSWORD_TYPE = Use custom password
  CUSTOM_TEMPORARY_PASSWORD = Passw0rd

  GRID_NETWORK_IP = 10.1.0.2
  ADMIN_NETWORK_IP = 10.3.0.2
  CLIENT_NETWORK_IP = 10.4.0.2
----
次の追加設定は、プライマリ管理ノードではオプションです。

* *DISK*: デフォルトでは、管理ノードには監査とデータベースの使用のために 2 つの追加の 200 GB ハード ディスクが割り当てられます。 DISK パラメータを使用してこれらの設定を増やすことができます。例えば：
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 管理ノードの場合、INSTANCES は常に 2 に等しくなければなりません。

.ストレージ ノード
ストレージ ノードには次の追加設定が必要です。

* *ノードタイプ*: VM_ストレージノード
+
この例のエントリは、グリッド ネットワークと管理ネットワーク上にあり、クライアント ネットワーク上にはないストレージ ノード用です。このノードは、ADMIN_IP 設定を使用して、グリッド ネットワーク上のプライマリ管理ノードの IP アドレスを指定します。

+
[listing]
----
[DC1-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.0.3
  ADMIN_NETWORK_IP = 10.3.0.3

  ADMIN_IP = 10.1.0.2
----
+
この 2 番目の例エントリは、顧客のエンタープライズ ネットワーク ポリシーで S3 クライアント アプリケーションはポート 80 または 443 を使用してのみストレージ ノードにアクセスできることが規定されているクライアント ネットワーク上のストレージ ノード用です。サンプル構成ファイルでは、PORT_REMAP を使用して、ストレージノードがポート 443 で S3 メッセージを送受信できるようにします。

+
[listing]
----
[DC2-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3
  CLIENT_NETWORK_IP = 10.4.1.3
  PORT_REMAP = client/tcp/18082/443

  ADMIN_IP = 10.1.0.2
----
+
最後の例では、ポート 22 からポート 3022 への SSH トラフィックの対称再マッピングを作成しますが、受信トラフィックと送信トラフィックの両方の値を明示的に設定します。

+
[listing]
----
[DC1-S3]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3

  PORT_REMAP = grid/tcp/22/3022
  PORT_REMAP_INBOUND = grid/tcp/3022/22

  ADMIN_IP = 10.1.0.2
----


次の追加設定は、ストレージ ノードではオプションです。

* *DISK*: デフォルトでは、ストレージ ノードには RangeDB 用に 3 つの 4 TB ディスクが割り当てられます。 DISK パラメータを使用してこれらの設定を増やすことができます。例えば：
+
[listing]
----
DISK = INSTANCES=16, CAPACITY=4096
----
* *STORAGE_TYPE*: デフォルトでは、すべての新しいストレージ ノードは、オブジェクト データとメタデータの両方を保存するように構成され、_結合_ ストレージ ノードと呼ばれます。 STORAGE_TYPE パラメータを使用して、データまたはメタデータのみを保存するようにストレージ ノード タイプを変更できます。例えば：
+
[listing]
----
STORAGE_TYPE = data
----


.ゲートウェイ ノード
ゲートウェイ ノードには次の追加設定が必要です。

* *ノードタイプ*: VM_API_ゲートウェイ


この例のエントリは、3 つのネットワークすべてにおけるゲートウェイ ノードの例です。この例では、構成ファイルのグローバル セクションでクライアント ネットワーク パラメータが指定されていないため、ノードに対して指定する必要があります。

[listing]
----
[DC1-G1]
  NODE_TYPE = VM_API_Gateway

  GRID_NETWORK_IP = 10.1.0.5
  ADMIN_NETWORK_IP = 10.3.0.5

  CLIENT_NETWORK_CONFIG = STATIC
  CLIENT_NETWORK_TARGET = SG Client Network
  CLIENT_NETWORK_MASK = 255.255.255.0
  CLIENT_NETWORK_GATEWAY = 10.4.0.1
  CLIENT_NETWORK_IP = 10.4.0.5

  ADMIN_IP = 10.1.0.2
----
.非プライマリ管理ノード
プライマリ以外の管理ノードには次の追加設定が必要です。

* *ノードタイプ*: VM_Admin_Node
* *ADMIN_ROLE*: 非プライマリ


この例のエントリは、クライアント ネットワーク上にない非プライマリ管理ノード用です。

[listing]
----
[DC2-ADM1]
  ADMIN_ROLE = Non-Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_TARGET = SG Grid Network
  GRID_NETWORK_IP = 10.1.0.6
  ADMIN_NETWORK_IP = 10.3.0.6

  ADMIN_IP = 10.1.0.2
----
次の追加設定は、非プライマリ管理ノードではオプションです。

* *DISK*: デフォルトでは、管理ノードには監査とデータベースの使用のために 2 つの追加の 200 GB ハード ディスクが割り当てられます。 DISK パラメータを使用してこれらの設定を増やすことができます。例えば：
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 管理ノードの場合、INSTANCES は常に 2 に等しくなければなりません。



== Bashスクリプトを実行する

使用することができます `deploy-vsphere-ovftool.sh`VMware vSphere でのStorageGRIDノードのデプロイメントを自動化するために変更した Bash スクリプトと deploy-vsphere-ovftool.ini 構成ファイル。

.開始する前に
環境用の deploy-vsphere-ovftool.ini 構成ファイルを作成しました。

ヘルプコマンドを入力すると、Bashスクリプトで利用可能なヘルプを利用できます。(`-h/--help` ）。例えば：

[listing]
----
./deploy-vsphere-ovftool.sh -h
----
または

[listing]
----
./deploy-vsphere-ovftool.sh --help
----
.手順
. Bash スクリプトを実行するために使用している Linux マシンにログインします。
. インストール アーカイブを抽出したディレクトリに移動します。
+
例えば：

+
[listing]
----
cd StorageGRID-Webscale-version/vsphere
----
. すべてのグリッド ノードをデプロイするには、環境に適したオプションを使用して Bash スクリプトを実行します。
+
例えば：

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd ./deploy-vsphere-ovftool.ini
----
. エラーのためにグリッド ノードのデプロイに失敗した場合は、エラーを解決し、そのノードに対してのみ Bash スクリプトを再実行します。
+
例えば：

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd --single-node="DC1-S3" ./deploy-vsphere-ovftool.ini
----


各ノードのステータスが「成功」になったら、デプロイは完了です。

[listing]
----
Deployment Summary
+-----------------------------+----------+----------------------+
| node                        | attempts | status               |
+-----------------------------+----------+----------------------+
| DC1-ADM1                    |        1 | Passed               |
| DC1-G1                      |        1 | Passed               |
| DC1-S1                      |        1 | Passed               |
| DC1-S2                      |        1 | Passed               |
| DC1-S3                      |        1 | Passed               |
+-----------------------------+----------+----------------------+
----


== StorageGRIDの構成を自動化する

グリッド ノードを展開した後、 StorageGRIDシステムの構成を自動化できます。

.開始する前に
* インストール アーカイブから次のファイルの場所がわかっています。
+
[cols="1a,1a"]
|===
| ファイル名 | 説明 


| ストレージグリッドを構成する.py  a| 
構成を自動化するために使用されるPythonスクリプト



| ストレージグリッドの設定.サンプル.json  a| 
スクリプトで使用するサンプル設定ファイル



| ストレージグリッドを構成する.blank.json  a| 
スクリプトで使用するための空の設定ファイル

|===
* 作成しました `configure-storagegrid.json`設定ファイル。このファイルを作成するには、サンプル構成ファイルを変更します。(`configure-storagegrid.sample.json` ）または空の設定ファイル(`configure-storagegrid.blank.json`）。
+
使用することができます `configure-storagegrid.py`Pythonスクリプトと `configure-storagegrid.json`StorageGRIDシステムの構成を自動化するためのグリッド構成ファイル。

+

NOTE: グリッド マネージャーまたはインストール API を使用してシステムを構成することもできます。



.手順
. Python スクリプトを実行するために使用している Linux マシンにログインします。
. インストール アーカイブを抽出したディレクトリに移動します。
+
例えば：

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
どこ `platform`debs、rpms、または vsphere です。

. Python スクリプトを実行し、作成した構成ファイルを使用します。
+
例えば：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.結果
回復パッケージ `.zip`ファイルは構成プロセス中に生成され、インストールおよび構成プロセスを実行しているディレクトリにダウンロードされます。 1 つ以上のグリッド ノードに障害が発生した場合にStorageGRIDシステムを回復できるように、リカバリ パッケージ ファイルをバックアップする必要があります。たとえば、安全なバックアップされたネットワークの場所と安全なクラウド ストレージの場所にコピーします。


CAUTION: リカバリ パッケージ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティ保護する必要があります。

ランダムパスワードを生成するように指定した場合は、 `Passwords.txt`ファイルを開いて、 StorageGRIDシステムにアクセスするために必要なパスワードを探します。

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
確認メッセージが表示されたら、 StorageGRIDシステムがインストールされ、構成されています。

[listing]
----
StorageGRID has been configured and installed.
----
.関連情報
* link:navigating-to-grid-manager.html["グリッドマネージャーに移動する"]
* link:overview-of-installation-rest-api.html["インストールREST API"]

