---
permalink: vmware/collecting-information-about-your-deployment-environment.html 
sidebar: sidebar 
keywords: how to collect information about your deployment environment 
summary: グリッド ノードを展開する前に、ネットワーク構成と VMware 環境に関する情報を収集する必要があります。 
---
= 展開環境に関する情報を収集する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド ノードを展開する前に、ネットワーク構成と VMware 環境に関する情報を収集する必要があります。


NOTE: 一部のノードを今インストールし、一部のノードを後でインストールするよりも、すべてのノードを 1 回インストールする方が効率的です。



== VMware情報

デプロイメント環境にアクセスし、VMware 環境、グリッド、管理、およびクライアント ネットワーク用に作成されたネットワーク、およびストレージ ノードに使用する予定のストレージ ボリューム タイプに関する情報を収集する必要があります。

次のような VMware 環境に関する情報を収集する必要があります。

* デプロイメントを完了するための適切な権限を持つ VMware vSphere アカウントのユーザー名とパスワード。
* 各StorageGRIDノード仮想マシンのホスト、データストア、およびネットワーク構成情報。



NOTE: VMware ライブ vMotion は仮想マシンのクロック時間をジャンプさせるため、どのタイプのグリッド ノードでもサポートされません。まれではありますが、クロック時刻が正しくないと、データが失われたり、構成が更新されたりする可能性があります。



== グリッドネットワーク情報

StorageGRIDグリッド ネットワーク (必須) 用に作成された VMware ネットワークに関する以下の情報を収集する必要があります。

* ネットワーク名。
* IP アドレスを割り当てるために使用される方法 (静的または DHCP)。
+
** 静的 IP アドレスを使用している場合は、各グリッド ノードに必要なネットワークの詳細 (IP アドレス、ゲートウェイ、ネットワーク マスク)。
** DHCP を使用している場合は、グリッド ネットワーク上のプライマリ管理ノードの IP アドレス。見るlink:how-grid-nodes-discover-primary-admin-node.html["グリッドノードがプライマリ管理ノードを検出する方法"]詳細についてはこちらをご覧ください。






== 管理者ネットワーク情報

オプションのStorageGRID管理ネットワークに接続されるノードについては、このネットワーク用に作成された VMware ネットワークに関する次のような情報を収集する必要があります。

* ネットワーク名。
* IP アドレスを割り当てるために使用される方法 (静的または DHCP)。
+
** 静的 IP アドレスを使用している場合は、各グリッド ノードに必要なネットワークの詳細 (IP アドレス、ゲートウェイ、ネットワーク マスク)。
** DHCP を使用している場合は、グリッド ネットワーク上のプライマリ管理ノードの IP アドレス。見るlink:how-grid-nodes-discover-primary-admin-node.html["グリッドノードがプライマリ管理ノードを検出する方法"]詳細についてはこちらをご覧ください。


* 管理ネットワークの外部サブネット リスト (ESL)。




== クライアントネットワーク情報

オプションのStorageGRIDクライアント ネットワークに接続されるノードについては、このネットワーク用に作成された VMware ネットワークに関する次のような情報を収集する必要があります。

* ネットワーク名。
* IP アドレスを割り当てるために使用される方法 (静的または DHCP)。
* 静的 IP アドレスを使用している場合は、各グリッド ノードに必要なネットワークの詳細 (IP アドレス、ゲートウェイ、ネットワーク マスク)。




== 追加インターフェースに関する情報

ノードをインストールした後、オプションで、vCenter 内の VM にトランク インターフェイスまたはアクセス インターフェイスを追加できます。たとえば、管理ノードまたはゲートウェイ ノードにトランク インターフェイスを追加して、VLAN インターフェイスを使用して、異なるアプリケーションまたはテナントに属するトラフィックを分離することができます。または、高可用性 (HA) グループで使用するアクセス インターフェイスを追加することもできます。

追加したインターフェースは、グリッド マネージャーの VLAN インターフェース ページと HA グループ ページに表示されます。

* トランク インターフェイスを追加する場合は、新しい親インターフェイスごとに 1 つ以上の VLAN インターフェイスを設定します。見るlink:../admin/configure-vlan-interfaces.html["VLANインターフェースを設定する"] 。
* アクセス インターフェイスを追加する場合は、それを HA グループに直接追加する必要があります。見るlink:../admin/configure-high-availability-group.html["高可用性グループを構成する"] 。




== 仮想ストレージノードのストレージボリューム

仮想マシンベースのストレージ ノードについては、次の情報を収集する必要があります。

* 追加予定のストレージボリューム（ストレージLUN）の数とサイズ。link:storage-and-performance-requirements.html["ストレージとパフォーマンスの要件"] 。




== グリッド構成情報

グリッドを構成するには、次の情報を収集する必要があります。

* グリッドライセンス
* ネットワークタイムプロトコル（NTP）サーバーのIPアドレス
* DNSサーバーのIPアドレス

