---
permalink: vmware/deploying-storagegrid-node-as-virtual-machine.html 
sidebar: sidebar 
keywords: how to deploy grid nodes in vsphere or vsphere web client, port, remap, port remap 
summary: VMware vSphere Web Client を使用して、各グリッド ノードを仮想マシンとして展開します。展開中に、各グリッド ノードが作成され、1 つ以上のStorageGRIDネットワークに接続されます。 
---
= StorageGRIDノードを仮想マシンとして展開する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere Web Client を使用して、各グリッド ノードを仮想マシンとして展開します。展開中に、各グリッド ノードが作成され、1 つ以上のStorageGRIDネットワークに接続されます。

StorageGRIDアプライアンスのストレージノードを展開する必要がある場合は、 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/deploying-appliance-storage-node.html["アプライアンスストレージノードを展開する"^] 。

オプションで、ノードの電源をオンにする前に、ノード ポートを再マップしたり、ノードの CPU またはメモリ設定を増やしたりすることができます。

.開始する前に
* 方法を確認しましたlink:index.html["設置の計画と準備"]ソフトウェア、CPU と RAM、ストレージとパフォーマンスの要件を理解します。
* VMware vSphere Hypervisor に精通しており、この環境に仮想マシンを展開した経験があります。
+

NOTE: その `open-vm-tools`VMware Tools に似たオープンソース実装であるパッケージが、 StorageGRID仮想マシンに含まれています。  VMware Tools を手動でインストールする必要はありません。

* VMware 用の正しいバージョンのStorageGRIDインストール アーカイブをダウンロードして解凍しました。
+

CAUTION: 拡張またはリカバリ操作の一環として新しいノードを展開する場合は、グリッド上で現在実行されているStorageGRIDのバージョンを使用する必要があります。

* StorageGRID仮想マシンディスクをお持ちの場合(`.vmdk`） ファイル：


[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
----
* あなたは `.ovf`そして `.mf`デプロイするグリッド ノードの種類ごとに次のファイルを作成します。
+
[cols="1a,1a"]
|===
| ファイル名 | 説明 


| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
プライマリ管理ノードのテンプレート ファイルとマニフェスト ファイル。



| vsphere-non-primary-admin.ovf vsphere-non-primary-admin.mf  a| 
非プライマリ管理ノードのテンプレート ファイルとマニフェスト ファイル。



| vsphere-storage.ovf vsphere-storage.mf  a| 
ストレージ ノードのテンプレート ファイルとマニフェスト ファイル。



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
ゲートウェイ ノードのテンプレート ファイルとマニフェスト ファイル。

|===
* その `.vdmk`、 `.ovf` 、 そして `.mf`ファイルはすべて同じディレクトリにあります。
* 障害ドメインを最小限に抑える計画があります。たとえば、すべてのゲートウェイ ノードを単一の vSphere ESXi ホストに展開しないでください。
+

CAUTION: 実稼働環境では、単一の仮想マシン上で複数のストレージ ノードを実行しないでください。許容できない障害ドメインの問題が発生する場合は、同じ ESXi ホスト上で複数の仮想マシンを実行しないでください。

* 拡張または回復操作の一環としてノードを展開する場合は、link:../expand/index.html["StorageGRIDシステムを拡張するための手順"]またはlink:../maintain/index.html["回復とメンテナンスの手順"]。
* NetApp ONTAPシステムからストレージが割り当てられた仮想マシンとしてStorageGRIDノードを展開する場合は、ボリュームにFabricPool階層化ポリシーが有効になっていないことを確認します。たとえば、 StorageGRIDノードが VMware ホスト上で仮想マシンとして実行されている場合は、ノードのデータストアをバックアップするボリュームでFabricPool階層化ポリシーが有効になっていないことを確認します。StorageGRIDノードで使用するボリュームでFabricPoolによる階層化を無効にすることで、トラブルシューティングとストレージの処理がシンプルになります。
+

NOTE: FabricPoolを使用してStorageGRIDに関連するデータをStorageGRID自体に階層化することは絶対にしないでください。StorageGRIDにStorageGRIDデータを階層化すると、トラブルシューティングと運用がより複雑になります。



.タスク概要
VMware ノードを最初に展開したり、拡張で新しい VMware ノードを追加したり、リカバリ操作の一環として VMware ノードを置き換えたりするには、次の手順に従います。手順に記載されている場合を除き、ノードの展開手順は、管理ノード、ストレージ ノード、ゲートウェイ ノードを含むすべてのノード タイプで同じです。

新しいStorageGRIDシステムをインストールする場合:

* ノードは任意の順序でデプロイできます。
* 各仮想マシンがグリッド ネットワーク経由でプライマリ管理ノードに接続できることを確認する必要があります。
* グリッドを構成する前に、すべてのグリッド ノードをデプロイする必要があります。


拡張または回復操作を実行する場合:

* 新しい仮想マシンがグリッド ネットワーク経由で他のすべてのノードに接続できることを確認する必要があります。


ノードのポートのいずれかを再マップする必要がある場合は、ポートの再マップ構成が完了するまで新しいノードの電源を入れないでください。

.手順
. VCenter を使用して、OVF テンプレートをデプロイします。
+
URL を指定する場合は、次のファイルを含むフォルダーを指定します。それ以外の場合は、ローカル ディレクトリからこれらの各ファイルを選択します。

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-_node_.ovf
vsphere-_node_.mf
----
+
たとえば、これが展開する最初のノードである場合は、次のファイルを使用してStorageGRIDシステムのプライマリ管理ノードを展開します。

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-primary-admin.ovf
vsphere-primary-admin.mf
----
. 仮想マシンの名前を指定します。
+
標準的な方法としては、仮想マシンとグリッド ノードの両方に同じ名前を使用します。

. 仮想マシンを適切な vApp またはリソース プールに配置します。
. プライマリ管理ノードを展開する場合は、エンド ユーザー ライセンス契約を読んで同意します。
+
vCenter のバージョンに応じて、エンド ユーザー ライセンス契約への同意、仮想マシンの名前の指定、データストアの選択の手順の順序は異なります。

. 仮想マシンのストレージを選択します。
+
リカバリ操作の一環としてノードを展開する場合は、<<step_recovery_storage,ストレージ回復ステップ>>新しい仮想ディスクを追加するか、障害が発生したグリッド ノードから仮想ハード ディスクを再接続するか、またはその両方を実行します。

+
ストレージ ノードを展開する場合は、各ストレージ ボリュームが 4 TB 以上の 3 つ以上のストレージ ボリュームを使用します。ボリューム 0 には少なくとも 4 TB を割り当てる必要があります。

+

NOTE: ストレージ ノードの .ovf ファイルは、ストレージ用の複数の VMDK を定義します。これらの VMDK がストレージ要件を満たしていない場合は、ノードの電源を入れる前に、それらを削除し、ストレージに適切な VMDK または RDM を割り当てる必要があります。  VMDK は VMware 環境でより一般的に使用され、管理が容易ですが、RDM はより大きなオブジェクト サイズ (たとえば、100 MB を超える) を使用するワークロードに対してより優れたパフォーマンスを提供する可能性があります。

+

NOTE: 一部のStorageGRIDインストールでは、一般的な仮想化ワークロードよりも大規模でアクティブなストレージ ボリュームが使用される場合があります。ハイパーバイザーのパラメータを調整する必要があるかもしれません。 `MaxAddressableSpaceTB` 、最適なパフォーマンスを実現します。パフォーマンスが低下した場合は、仮想化サポート リソースに連絡して、ワークロード固有の構成チューニングによって環境が改善されるかどうかを確認してください。

. ネットワークを選択します。
+
各ソース ネットワークの宛先ネットワークを選択して、ノードが使用するStorageGRIDネットワークを決定します。

+
** グリッド ネットワークが必要です。  vSphere 環境で宛先ネットワークを選択する必要があります。 + グリッド ネットワークは、すべての内部StorageGRIDトラフィックに使用されます。グリッド内のすべてのノード、すべてのサイトおよびサブネット間の接続を提供します。グリッド ネットワーク上のすべてのノードは、他のすべてのノードと通信できる必要があります。
** 管理ネットワークを使用する場合は、vSphere 環境で別の宛先ネットワークを選択します。管理ネットワークを使用しない場合は、グリッド ネットワークに選択したのと同じ宛先を選択します。
** クライアント ネットワークを使用する場合は、vSphere 環境で別の宛先ネットワークを選択します。クライアント ネットワークを使用しない場合は、グリッド ネットワークに選択したのと同じ宛先を選択します。
** 管理ネットワークまたはクライアント ネットワークを使用する場合、ノードは同じ管理ネットワークまたはクライアント ネットワーク上にある必要はありません。


. *テンプレートのカスタマイズ*では、必要なStorageGRIDノードのプロパティを構成します。
+
.. *ノード名*を入力します。
+

NOTE: グリッド ノードを回復する場合は、回復するノードの名前を入力する必要があります。

.. 新しいノードがグリッドに参加する前に、VM コンソールまたはStorageGRIDインストール API にアクセスしたり、SSH を使用したりできるように、*一時インストール パスワード* ドロップダウンを使用して一時インストール パスワードを指定します。
+

NOTE: 一時インストール パスワードは、ノードのインストール時にのみ使用されます。グリッドにノードを追加したら、link:../admin/change-node-console-password.html["ノードコンソールのパスワード"]に記載されている `Passwords.txt`リカバリ パッケージ内のファイル。

+
*** *ノード名を使用*: *ノード名* フィールドに指定した値は、一時的なインストール パスワードとして使用されます。
*** *カスタム パスワードを使用する*: 一時的なインストール パスワードとしてカスタム パスワードが使用されます。
*** *パスワードを無効にする*: 一時インストール パスワードは使用されません。インストールの問題をデバッグするためにVMにアクセスする必要がある場合は、link:troubleshooting-installation-issues.html["インストールの問題のトラブルシューティング"] 。


.. *カスタム パスワードを使用する* を選択した場合は、*カスタム パスワード* フィールドに使用する一時インストール パスワードを指定します。
.. *グリッド ネットワーク (eth0)* セクションで、*グリッド ネットワーク IP 構成* に STATIC または DHCP を選択します。
+
*** STATIC を選択した場合は、*グリッド ネットワーク IP*、*グリッド ネットワーク マスク*、*グリッド ネットワーク ゲートウェイ*、および *グリッド ネットワーク MTU* を入力します。
*** DHCP を選択した場合は、*グリッド ネットワーク IP*、*グリッド ネットワーク マスク*、および *グリッド ネットワーク ゲートウェイ* が自動的に割り当てられます。


.. *プライマリ管理 IP* フィールドに、グリッド ネットワークのプライマリ管理ノードの IP アドレスを入力します。
+

NOTE: デプロイするノードがプライマリ管理ノードである場合、この手順は適用されません。

+
プライマリ管理ノードの IP アドレスを省略した場合、プライマリ管理ノード、または ADMIN_IP が設定された少なくとも 1 つの他のグリッド ノードが同じサブネット上に存在する場合、IP アドレスは自動的に検出されます。ただし、ここではプライマリ管理ノードの IP アドレスを設定することをお勧めします。

.. *管理ネットワーク (eth1)* セクションで、*管理ネットワーク IP 構成* として STATIC、DHCP、または DISABLED を選択します。
+
*** 管理ネットワークを使用しない場合は、「無効」を選択し、管理ネットワーク IP として *0.0.0.0* を入力します。他のフィールドは空白のままにしておくことができます。
*** STATIC を選択した場合は、*管理ネットワーク IP*、*管理ネットワーク マスク*、*管理ネットワーク ゲートウェイ*、および *管理ネットワーク MTU* を入力します。
*** STATIC を選択した場合は、*管理ネットワークの外部サブネット リスト* を入力します。ゲートウェイも構成する必要があります。
*** DHCP を選択した場合は、*管理ネットワーク IP*、*管理ネットワーク マスク*、および *管理ネットワーク ゲートウェイ* が自動的に割り当てられます。


.. *クライアント ネットワーク (eth2)* セクションで、*クライアント ネットワーク IP 構成* として STATIC、DHCP、または DISABLED を選択します。
+
*** クライアント ネットワークを使用しない場合は、[DISABLED] を選択し、クライアント ネットワーク IP に *0.0.0.0* を入力します。他のフィールドは空白のままにしておくことができます。
*** STATIC を選択した場合は、*クライアント ネットワーク IP*、*クライアント ネットワーク マスク*、*クライアント ネットワーク ゲートウェイ*、および *クライアント ネットワーク MTU* を入力します。
*** DHCP を選択した場合は、*クライアント ネットワーク IP*、*クライアント ネットワーク マスク*、および *クライアント ネットワーク ゲートウェイ* が自動的に割り当てられます。




. 仮想マシンの構成を確認し、必要な変更を加えます。
. 完了する準備ができたら、[完了] を選択して仮想マシンのアップロードを開始します。
. [[step_recovery_storage]]このノードをリカバリ操作の一部としてデプロイし、これがフルノードリカバリではない場合は、デプロイが完了した後に次の手順を実行します。
+
.. 仮想マシンを右クリックし、[設定の編集] を選択します。
.. ストレージ用に指定されているデフォルトの仮想ハード ディスクをそれぞれ選択し、[削除] を選択します。
.. データ回復の状況に応じて、ストレージ要件に応じて新しい仮想ディスクを追加するか、以前に削除された障害が発生したグリッド ノードから保存された仮想ハード ディスクを再接続するか、またはその両方を実行します。
+
次の重要なガイドラインに注意してください。

+
*** 新しいディスクを追加する場合は、ノードのリカバリ前に使用されていたのと同じタイプのストレージ デバイスを使用する必要があります。
*** ストレージ ノードの .ovf ファイルは、ストレージ用の複数の VMDK を定義します。これらの VMDK がストレージ要件を満たしていない場合は、ノードの電源を入れる前に、それらを削除し、ストレージに適切な VMDK または RDM を割り当てる必要があります。  VMDK は VMware 環境でより一般的に使用され、管理が容易ですが、RDM はより大きなオブジェクト サイズ (たとえば、100 MB を超える) を使用するワークロードに対してより優れたパフォーマンスを提供する可能性があります。




. [[vmware-remap-ports]]このノードで使用されるポートを再マップする必要がある場合は、次の手順に従ってください。
+
企業のネットワーク ポリシーによって、 StorageGRIDが使用する 1 つ以上のポートへのアクセスが制限されている場合は、ポートの再マップが必要になることがあります。参照link:../network/index.html["ネットワークガイドライン"]StorageGRIDで使用されるポート用。

+

NOTE: ロード バランサーのエンドポイントで使用されるポートを再マップしないでください。

+
.. 新しい VM を選択します。
.. [構成] タブから、*設定* > *vApp オプション* を選択します。  *vApp オプション* の場所は、vCenter のバージョンによって異なります。
.. *プロパティ* テーブルで、PORT_REMAP_INBOUND と PORT_REMAP を見つけます。
.. ポートの受信通信と送信通信の両方を対称的にマップするには、*PORT_REMAP* を選択します。
+

NOTE: PORT_REMAP のみが設定されている場合、指定したマッピングは受信通信と送信通信の両方に適用されます。  PORT_REMAP_INBOUND も指定されている場合、PORT_REMAP は送信通信にのみ適用されます。

+
... *値の設定*を選択します。
... ポート マッピングを入力します。
+
`<network type>/<protocol>/<default port used by grid node>/<new port>`

+
`<network type>`グリッド、管理者、またはクライアントであり、 `<protocol>` tcp または udp です。

+
たとえば、ssh トラフィックをポート 22 からポート 3022 に再マップするには、次のように入力します。

+
`client/tcp/22/3022`

+
カンマ区切りのリストを使用して複数のポートを再マップできます。

+
例えば：

+
`client/tcp/18082/443, client/tcp/18083/80`

... 「OK」を選択します。


.. ノードへの受信通信に使用するポートを指定するには、*PORT_REMAP_INBOUND* を選択します。
+

NOTE: PORT_REMAP_INBOUND を指定し、PORT_REMAP の値を指定しない場合、ポートの送信通信は変更されません。

+
... *値の設定*を選択します。
... ポート マッピングを入力します。
+
`<network type>/<protocol>/<remapped inbound port>/<default inbound port used by grid node>`

+
`<network type>`グリッド、管理者、またはクライアントであり、 `<protocol>` tcp または udp です。

+
たとえば、ポート 3022 に送信される着信 SSH トラフィックをグリッド ノードによってポート 22 で受信されるように再マップするには、次のように入力します。

+
`client/tcp/3022/22`

+
カンマ区切りのリストを使用して、複数の受信ポートを再マップできます。

+
例えば：

+
`grid/tcp/3022/22, admin/tcp/3022/22`

... [OK]を選択します




. ノードの CPU またはメモリをデフォルト設定から増やす場合は、次の手順を実行します。
+
.. 仮想マシンを右クリックし、[設定の編集] を選択します。
.. 必要に応じて CPU の数またはメモリの量を変更します。
+
*メモリ予約*を、仮想マシンに割り当てられた*メモリ*と同じサイズに設定します。

.. 「OK」を選択します。


. 仮想マシンの電源をオンにします。


.終了後の操作
拡張または回復手順の一部としてこのノードを展開した場合は、その手順に戻って手順を完了してください。
