---
permalink: vmware/how-grid-nodes-discover-primary-admin-node.html 
sidebar: sidebar 
keywords: how grid nodes discover the primary Admin Node 
summary: グリッド ノードは、構成と管理のためにプライマリ管理ノードと通信します。各グリッド ノードは、グリッド ネットワーク上のプライマリ管理ノードの IP アドレスを認識している必要があります。 
---
= グリッドノードがプライマリ管理ノードを検出する方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド ノードは、構成と管理のためにプライマリ管理ノードと通信します。各グリッド ノードは、グリッド ネットワーク上のプライマリ管理ノードの IP アドレスを認識している必要があります。

グリッド ノードがプライマリ管理ノードにアクセスできるようにするには、ノードをデプロイするときに次のいずれかを実行します。

* ADMIN_IP パラメータを使用して、プライマリ管理ノードの IP アドレスを手動で入力できます。
* ADMIN_IP パラメータを省略すると、グリッド ノードが値を自動的に検出するようになります。自動検出は、グリッド ネットワークが DHCP を使用してプライマリ管理ノードに IP アドレスを割り当てる場合に特に便利です。


プライマリ管理ノードの自動検出は、マルチキャスト ドメイン ネーム システム (mDNS) を使用して実行されます。プライマリ管理ノードが最初に起動すると、mDNS を使用して IP アドレスを公開します。同じサブネット上の他のノードは IP アドレスを照会し、自動的に取得できるようになります。ただし、マルチキャスト IP トラフィックは通常サブネット間でルーティングできないため、他のサブネット上のノードはプライマリ管理ノードの IP アドレスを直接取得できません。

[NOTE]
====
自動検出を使用する場合:

* プライマリ管理ノードが直接接続されていないサブネット上の少なくとも 1 つのグリッド ノードに ADMIN_IP 設定を含める必要があります。このグリッド ノードは、サブネット上の他のノードが mDNS で検出できるように、プライマリ管理ノードの IP アドレスを公開します。
* ネットワーク インフラストラクチャがサブネット内でのマルチキャスト IP トラフィックの通過をサポートしていることを確認します。


====