---
permalink: vmware/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: 仮想マシンを使用して、あらゆるタイプのStorageGRIDノードをホストできます。グリッド ノードごとに 1 つの仮想マシンが必要です。 
---
= VMware のソフトウェア要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシンを使用して、あらゆるタイプのStorageGRIDノードをホストできます。グリッド ノードごとに 1 つの仮想マシンが必要です。



== VMware vSphere ハイパーバイザー

準備された物理サーバーに VMware vSphere Hypervisor をインストールする必要があります。  VMware ソフトウェアをインストールする前に、ハードウェア (ファームウェア バージョンと BIOS 設定を含む) を正しく構成する必要があります。

* インストールするStorageGRIDシステムのネットワークをサポートするために、必要に応じてハイパーバイザーでネットワークを構成します。
+
link:../network/index.html["ネットワークガイドライン"]

* データストアが、グリッド ノードをホストするために必要な仮想マシンと仮想ディスクに対して十分な大きさであることを確認します。
* 複数のデータストアを作成する場合は、仮想マシンを作成するときに各グリッド ノードに使用するデータストアを簡単に識別できるように、各データストアに名前を付けます。




== ESXホストの構成要件


CAUTION: 各 ESX ホストでネットワーク タイム プロトコル (NTP) を適切に構成する必要があります。ホスト時間が正しくない場合、データ損失などの悪影響が発生する可能性があります。



== VMware の構成要件

StorageGRIDノードを展開する前に、VMware vSphere と vCenter をインストールして構成する必要があります。

VMware vSphere HypervisorおよびVMware vCenter Serverソフトウェアのサポートされているバージョンについては、 https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool"^] 。

これらの VMware 製品をインストールするために必要な手順については、VMware のドキュメントを参照してください。
