---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot installation issues 
summary: StorageGRIDシステムのインストール中に問題が発生した場合は、インストール ログ ファイルにアクセスできます。 
---
= インストールの問題のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDシステムのインストール中に問題が発生した場合は、インストール ログ ファイルにアクセスできます。

以下は、テクニカル サポートが問題を解決するために必要となる可能性のある主なインストール ログ ファイルです。

* `/var/local/log/install.log`（すべてのグリッドノードで見つかります）
* `/var/local/log/gdu-server.log`（プライマリ管理ノードにあります）


.関連情報
ログファイルにアクセスする方法については、link:../monitor/logs-files-reference.html["ログファイルリファレンス"] 。

さらにサポートが必要な場合は、 https://mysupport.netapp.com/site/global/dashboard["NetAppサポート"^] 。



== 仮想マシンのリソース予約には調整が必要です

OVF ファイルには、各グリッド ノードが効率的に動作するために十分な RAM と CPU を確保するように設計されたリソース予約が含まれています。これらの OVF ファイルを VMware にデプロイして仮想マシンを作成する場合、事前定義された数のリソースが利用できないと、仮想マシンは起動しません。

.タスク概要
VM ホストに各グリッド ノードに十分なリソースがあることが確実な場合は、各仮想マシンに割り当てられたリソースを手動で調整し、仮想マシンの起動を試みてください。

.手順
. VMware vSphere Hypervisor クライアント ツリーで、起動されていない仮想マシンを選択します。
. 仮想マシンを右クリックし、[設定の編集] を選択します。
. 仮想マシンのプロパティ ウィンドウで、*リソース* タブを選択します。
. 仮想マシンに割り当てられたリソースを調整します。
+
.. *CPU* を選択し、予約スライダーを使用してこの仮想マシンに予約されている MHz を調整します。
.. *メモリ*を選択し、予約スライダーを使用してこの仮想マシン用に予約されている MB を調整します。


. [OK]をクリックします。
. 同じ VM ホストでホストされている他の仮想マシンについても、必要に応じて繰り返します。




== 一時インストールパスワードが無効になりました

VMware ノードをデプロイするときに、オプションで一時的なインストール パスワードを指定できます。新しいノードがグリッドに参加する前に、VM コンソールにアクセスしたり SSH を使用したりするには、このパスワードが必要です。

一時的なインストール パスワードを無効にすることを選択した場合は、インストールの問題をデバッグするための追加の手順を実行する必要があります。

次のいずれかを実行できます。

* VM を再デプロイしますが、コンソールにアクセスしたり、SSH を使用してインストールの問題をデバッグしたりできるように、一時的なインストール パスワードを指定します。
* vCenter を使用してパスワードを設定します。
+
.. VM の電源をオフにします。
.. *VM* に移動し、*構成* タブを選択して、*vApp オプション* を選択します。
.. 設定する一時インストール パスワードの種類を指定します。
+
*** カスタムの一時パスワードを設定するには、*CUSTOM_TEMPORARY_PASSWORD* を選択します。
*** ノード名を一時パスワードとして使用するには、*TEMPORARY_PASSWORD_TYPE* を選択します。


.. *値の設定*を選択します。
.. 一時パスワードを設定します:
+
*** *CUSTOM_TEMPORARY_PASSWORD* をカスタム パスワード値に変更します。
*** *TEMPORARY_PASSWORD_TYPE* を *Use node name* 値で更新します。


.. 新しいパスワードを適用するには、VM を再起動します。



