---
permalink: rhel/cpu-and-ram-requirements.html 
sidebar: sidebar 
keywords: cpu, ram, cpu cores 
summary: StorageGRIDソフトウェアをインストールする前に、ハードウェアを確認して構成し、 StorageGRIDシステムをサポートできる状態にしておきます。 
---
= CPUとRAMの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDソフトウェアをインストールする前に、ハードウェアを確認して構成し、 StorageGRIDシステムをサポートできる状態にしておきます。

各StorageGRIDノードには、次の最小リソースが必要です。

* CPUコア数: ノードあたり8個
* RAM: 利用可能なRAMの合計容量とシステム上で実行されているStorageGRID以外のソフトウェアの量によって異なります。
+
** 通常、ノードあたり少なくとも24 GB、システム全体のRAMより2～16 GB少ない
** 約5,000個のバケットを持つテナントごとに最低64 GB




ソフトウェア ベースのメタデータのみのノード リソースは、既存のストレージ ノード リソースと一致する必要があります。例えば：

* 既存のStorageGRIDサイトが SG6000 または SG6100 アプライアンスを使用している場合、ソフトウェアベースのメタデータのみのノードは次の最小要件を満たしている必要があります。
+
** 128GBのRAM
** 8コアCPU
** Cassandra データベース用の 8 TB SSD または同等のストレージ (rangedb/0)


* 既存のStorageGRIDサイトが 24 GB RAM、8 コア CPU、3 TB または 4 TB のメタデータ ストレージを備えた仮想ストレージ ノードを使用している場合、ソフトウェア ベースのメタデータ専用ノードでは同様のリソース (24 GB RAM、8 コア CPU、4 TB のメタデータ ストレージ (rangedb/0)) を使用する必要があります。


新しいStorageGRIDサイトを追加する場合、新しいサイトの合計メタデータ容量は少なくとも既存のStorageGRIDサイトと一致し、新しいサイトのリソースは既存のStorageGRIDサイトのストレージ ノードと一致する必要があります。

各物理ホストまたは仮想ホストで実行する予定のStorageGRIDノードの数が、使用可能な CPU コア数または物理 RAM を超えないようにしてください。ホストがStorageGRID の実行専用でない場合は (非推奨)、他のアプリケーションのリソース要件を考慮してください。


NOTE: CPU とメモリの使用状況を定期的に監視し、これらのリソースが引き続きワークロードに対応できることを確認します。たとえば、仮想ストレージ ノードの RAM と CPU の割り当てを 2 倍にすると、 StorageGRIDアプライアンス ノードに提供されるものと同様のリソースが提供されます。さらに、ノードあたりのメタデータの量が 500 GB を超える場合は、ノードあたりの RAM を 48 GB 以上に増やすことを検討してください。オブジェクトメタデータストレージの管理、メタデータ予約領域設定の増加、CPUとメモリ使用量の監視については、link:../admin/index.html["管理する"] 、link:../monitor/index.html["監視"] 、 そしてlink:../upgrade/index.html["アップグレード"]StorageGRID。

基盤となる物理ホストでハイパースレッディングが有効になっている場合は、ノードごとに 8 個の仮想コア (4 個の物理コア) を提供できます。基盤となる物理ホストでハイパースレッディングが有効になっていない場合は、ノードごとに 8 つの物理コアを提供する必要があります。

仮想マシンをホストとして使用し、VM のサイズと数を制御できる場合は、 StorageGRIDノードごとに 1 つの VM を使用し、それに応じて VM のサイズを調整する必要があります。

実稼働環境では、同じ物理ストレージ ハードウェアまたは仮想ホスト上で複数のストレージ ノードを実行しないでください。単一のStorageGRID展開内の各ストレージ ノードは、独自の分離された障害ドメインに配置する必要があります。単一のハードウェア障害が単一のストレージ ノードにのみ影響するようにすれば、オブジェクト データの耐久性と可用性を最大限に高めることができます。

参照link:storage-and-performance-requirements.html["ストレージとパフォーマンスの要件"] 。
