---
permalink: rhel/creating-node-configuration-files.html 
sidebar: sidebar 
keywords: how to create red hat linux node configuration files, port, remap, port remap 
summary: ノード構成ファイルは、 StorageGRIDホスト サービスがノードを起動し、適切なネットワークおよびブロック ストレージ リソースに接続するために必要な情報を提供する小さなテキスト ファイルです。ノード構成ファイルは仮想ノードに使用され、アプライアンス ノードには使用されません。 
---
= Red Hat Enterprise Linux デプロイメント用のノード構成ファイルを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノード構成ファイルは、 StorageGRIDホスト サービスがノードを起動し、適切なネットワークおよびブロック ストレージ リソースに接続するために必要な情報を提供する小さなテキスト ファイルです。ノード構成ファイルは仮想ノードに使用され、アプライアンス ノードには使用されません。



== ノード構成ファイルの場所

各StorageGRIDノードの設定ファイルを `/etc/storagegrid/nodes`ノードが実行されるホスト上のディレクトリ。たとえば、HostAで管理ノード1台、ゲートウェイノード1台、ストレージノード1台を実行する場合は、3つのノード構成ファイルを `/etc/storagegrid/nodes`HostA 上。

vim や nano などのテキスト エディターを使用して各ホスト上で直接構成ファイルを作成することも、他の場所で作成して各ホストに移動することもできます。



== ノード構成ファイルの命名

構成ファイルの名前は重要です。フォーマットは `node-name.conf`、 どこ `node-name`ノードに割り当てる名前です。この名前はStorageGRIDインストーラに表示され、ノードの移行などのノードのメンテナンス操作に使用されます。

ノード名は、次の規則に従う必要があります。

* 一意である必要があります。
* 文字で始まっていなければなりません
* AからZ、aからzまでの文字を含めることができます
* 0から9までの数字を含めることができます
* 1つ以上のハイフン（-）を含めることができます
* 32文字以内でなければなりません（ `.conf`拡大


任意のファイル `/etc/storagegrid/nodes`これらの命名規則に従わないファイルは、ホスト サービスによって解析されません。

グリッドにマルチサイト トポロジを計画している場合、一般的なノード命名スキームは次のようになります。

`site-nodetype-nodenumber.conf`

例えば、 `dc1-adm1.conf`データセンター1の最初の管理ノードの場合、 `dc2-sn3.conf`データセンター 2 の 3 番目のストレージ ノード用。ただし、すべてのノード名が命名規則に従っている限り、任意のスキームを使用できます。



== ノード構成ファイルの内容

構成ファイルには、1 行につき 1 つのキーと 1 つの値のキー/値のペアが含まれます。各キー/値のペアについては、次の規則に従います。

* キーと値は等号で区切る必要があります(`=`) およびオプションの空白。
* キーにはスペースを含めることはできません。
* 値には埋め込みスペースを含めることができます。
* 先頭または末尾の空白は無視されます。


次の表は、サポートされているすべてのキーの値を定義します。各キーには次のいずれかの指定があります。

* *必須*: すべてのノードまたは指定されたノードタイプに必須
* *ベストプラクティス*: オプションですが推奨されます
* *オプション*: すべてのノードでオプション




=== 管理者ネットワークキー



==== 管理者IP

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
このノードが属するグリッドのプライマリ管理ノードのグリッド ネットワーク IPv4 アドレス。 NODE_TYPE = VM_Admin_Node および ADMIN_ROLE = Primary のグリッド ノードの GRID_NETWORK_IP に指定したのと同じ値を使用します。このパラメータを省略すると、ノードは mDNS を使用してプライマリ管理ノードを検出しようとします。

link:how-grid-nodes-discover-primary-admin-node.html["グリッドノードがプライマリ管理ノードを検出する方法"]

*注*: この値はプライマリ管理ノードでは無視され、禁止される可能性があります。
 a| 
ベストプラクティス

|===


==== 管理者ネットワーク構成

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
DHCP、静的、または無効
 a| 
オプション

|===


==== 管理者ネットワークESL

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
このノードが管理ネットワーク ゲートウェイを使用して通信するサブネットの CIDR 表記のコンマ区切りリスト。

例： `172.16.0.0/21,172.17.0.0/21`
 a| 
オプション

|===


==== 管理者ネットワークゲートウェイ

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
このノードのローカル管理ネットワーク ゲートウェイの IPv4 アドレス。 ADMIN_NETWORK_IP および ADMIN_NETWORK_MASK で定義されたサブネット上にある必要があります。この値は、DHCP 設定されたネットワークでは無視されます。

例:

`1.1.1.1`

`10.224.4.81`
 a| 
必須の場合 `ADMIN_NETWORK_ESL`が指定されます。それ以外の場合はオプションです。

|===


==== 管理者ネットワークIP

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
管理ネットワーク上のこのノードの IPv4 アドレス。このキーは、ADMIN_NETWORK_CONFIG = STATIC の場合にのみ必要です。他の値の場合は指定しないでください。

例:

`1.1.1.1`

`10.224.4.81`
 a| 
ADMIN_NETWORK_CONFIG = STATIC の場合に必須です。

それ以外の場合はオプションです。

|===


==== 管理者ネットワークMAC

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
コンテナ内の管理ネットワーク インターフェースの MAC アドレス。

このフィールドはオプションです。省略した場合、MAC アドレスは自動的に生成されます。

コロンで区切られた 6 組の 16 進数字である必要があります。

例： `b2:9c:02:c2:27:10`
 a| 
オプション

|===


==== 管理者ネットワークマスク

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
管理ネットワーク上のこのノードの IPv4 ネットマスク。  ADMIN_NETWORK_CONFIG = STATIC の場合はこのキーを指定します。他の値の場合は指定しないでください。

例:

`255.255.255.0`

`255.255.248.0`
 a| 
ADMIN_NETWORK_IP が指定され、ADMIN_NETWORK_CONFIG = STATIC の場合に必須です。

それ以外の場合はオプションです。

|===


==== 管理者ネットワークMTU

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
管理ネットワーク上のこのノードの最大転送単位 (MTU)。 ADMIN_NETWORK_CONFIG = DHCP の場合は指定しないでください。指定する場合、値は 1280 ～ 9216 の範囲でなければなりません。省略した場合は 1500 が使用されます。

ジャンボ フレームを使用する場合は、MTU を 9000 などのジャンボ フレームに適した値に設定します。それ以外の場合はデフォルト値を維持します。

*重要*: ネットワークの MTU 値は、ノードが接続されているスイッチ ポートで設定されている値と一致する必要があります。そうしないと、ネットワーク パフォーマンスの問題やパケット損失が発生する可能性があります。

例:

`1500`

`8192`
 a| 
オプション

|===


==== 管理者ネットワークターゲット

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
StorageGRIDノードによる管理ネットワーク アクセスに使用するホスト デバイスの名前。ネットワーク インターフェイス名のみがサポートされます。通常、GRID_NETWORK_TARGET または CLIENT_NETWORK_TARGET に指定されたものとは異なるインターフェイス名を使用します。

*注意*: ネットワーク ターゲットとしてボンド デバイスまたはブリッジ デバイスを使用しないでください。ボンドデバイスの上に VLAN (またはその他の仮想インターフェース) を構成するか、ブリッジと仮想イーサネット (veth) のペアを使用します。

*ベスト プラクティス*: このノードに最初は管理ネットワーク IP アドレスがない場合でも、値を指定します。その後、ホスト上のノードを再構成することなく、管理ネットワーク IP アドレスを追加できます。

例:

`bond0.1002`

`ens256`
 a| 
ベストプラクティス

|===


==== 管理者ネットワークターゲットタイプ

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
インターフェース (サポートされている値はこれだけです。)
 a| 
オプション

|===


==== ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
真か偽か

キーを「true」に設定すると、 StorageGRIDコンテナは管理ネットワーク上のホスト ターゲット インターフェイスの MAC アドレスを使用します。

*ベスト プラクティス:* 無差別モードが必要なネットワークでは、代わりに ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC キーを使用します。

MAC クローニングの詳細については、以下を参照してください。

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC アドレスの複製に関する考慮事項と推奨事項 (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC アドレスの複製に関する考慮事項と推奨事項 (Ubuntu または Debian)"]

 a| 
ベストプラクティス

|===


==== 管理者ロール

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
プライマリまたは非プライマリ

このキーは、NODE_TYPE = VM_Admin_Node の場合にのみ必要です。他のノード タイプでは指定しないでください。
 a| 
NODE_TYPE = VM_Admin_Node の場合に必須

それ以外の場合はオプションです。

|===


=== ブロックデバイスキー



==== ブロックデバイス監査ログ

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
このノードが監査ログの永続的な保存に使用するブロック デバイス特殊ファイルのパスと名前。

例:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
NODE_TYPE = VM_Admin_Node のノードに必須です。他のノード タイプには指定しないでください。

|===


==== ブロックデバイス範囲DB_nnn

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
このノードが永続オブジェクト ストレージに使用するブロック デバイス特殊ファイルのパスと名前。このキーは、NODE_TYPE = VM_Storage_Node のノードにのみ必要です。他のノード タイプには指定しないでください。

必須は BLOCK_DEVICE_RANGEDB_000 のみで、残りはオプションです。  BLOCK_DEVICE_RANGEDB_000 に指定されるブロック デバイスは少なくとも 4 TB である必要があります。その他のデバイスはより小さくてもかまいません。

隙間を残さないでください。  BLOCK_DEVICE_RANGEDB_005 を指定する場合は、BLOCK_DEVICE_RANGEDB_004 も指定する必要があります。

*注*: 既存のデプロイメントとの互換性のため、アップグレードされたノードでは 2 桁のキーがサポートされます。

例:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
必須：

ブロックデバイス範囲DB_000

オプション：

ブロックデバイス範囲DB_001

ブロックデバイス範囲DB_002

ブロックデバイス範囲DB_003

ブロックデバイス範囲DB_004

ブロックデバイス範囲DB_005

ブロックデバイス範囲DB_006

ブロックデバイス範囲DB_007

ブロックデバイス範囲DB_008

ブロックデバイス範囲DB_009

ブロックデバイス範囲DB_010

ブロックデバイス範囲DB_011

ブロックデバイス範囲DB_012

ブロックデバイス範囲DB_013

ブロックデバイス範囲DB_014

ブロックデバイス範囲DB_015

|===


==== ブロックデバイステーブル

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
このノードがデータベース テーブルの永続ストレージに使用するブロック デバイス特殊ファイルのパスと名前。このキーは、NODE_TYPE = VM_Admin_Node のノードにのみ必要です。他のノード タイプには指定しないでください。

例:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
必須

|===


==== ブロックデバイス変数ローカル

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
このノードが使用するブロックデバイス特殊ファイルのパスと名前 `/var/local`永続的なストレージ。

例:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
必須

|===


=== クライアントネットワークキー



==== クライアントネットワーク構成

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
DHCP、静的、または無効
 a| 
オプション

|===


==== クライアントネットワークゲートウェイ

[cols="4a,2a"]
|===


 a| 
Value
 a| 
指定



 a| 
このノードのローカル クライアント ネットワーク ゲートウェイの IPv4 アドレス。これは、CLIENT_NETWORK_IP および CLIENT_NETWORK_MASK によって定義されたサブネット上にある必要があります。この値は、DHCP 設定されたネットワークでは無視されます。

例:

`1.1.1.1`

`10.224.4.81`
 a| 
オプション

|===


==== クライアントネットワークIP

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
クライアント ネットワーク上のこのノードの IPv4 アドレス。

このキーは、CLIENT_NETWORK_CONFIG = STATIC の場合にのみ必要です。他の値の場合は指定しないでください。

例:

`1.1.1.1`

`10.224.4.81`
 a| 
CLIENT_NETWORK_CONFIG = STATIC の場合に必須

それ以外の場合はオプションです。

|===


==== クライアントネットワークMAC

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
コンテナ内のクライアント ネットワーク インターフェイスの MAC アドレス。

このフィールドはオプションです。省略した場合、MAC アドレスは自動的に生成されます。

コロンで区切られた 6 組の 16 進数字である必要があります。

例： `b2:9c:02:c2:27:20`
 a| 
オプション

|===


==== クライアントネットワークマスク

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
クライアント ネットワーク上のこのノードの IPv4 ネットマスク。

CLIENT_NETWORK_CONFIG = STATIC の場合はこのキーを指定します。他の値の場合は指定しないでください。

例:

`255.255.255.0`

`255.255.248.0`
 a| 
CLIENT_NETWORK_IP が指定され、CLIENT_NETWORK_CONFIG = STATIC の場合に必須

それ以外の場合はオプションです。

|===


==== クライアントネットワークMTU

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
クライアント ネットワーク上のこのノードの最大転送単位 (MTU)。 CLIENT_NETWORK_CONFIG = DHCP の場合は指定しないでください。指定する場合、値は 1280 ～ 9216 の範囲でなければなりません。省略した場合は 1500 が使用されます。

ジャンボ フレームを使用する場合は、MTU を 9000 などのジャンボ フレームに適した値に設定します。それ以外の場合はデフォルト値を維持します。

*重要*: ネットワークの MTU 値は、ノードが接続されているスイッチ ポートで設定されている値と一致する必要があります。そうしないと、ネットワーク パフォーマンスの問題やパケット損失が発生する可能性があります。

例:

`1500`

`8192`
 a| 
オプション

|===


==== クライアントネットワークターゲット

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
StorageGRIDノードによるクライアント ネットワーク アクセスに使用するホスト デバイスの名前。ネットワーク インターフェイス名のみがサポートされます。通常、GRID_NETWORK_TARGET または ADMIN_NETWORK_TARGET に指定されたものとは異なるインターフェイス名を使用します。

*注意*: ネットワーク ターゲットとしてボンド デバイスまたはブリッジ デバイスを使用しないでください。ボンドデバイスの上に VLAN (またはその他の仮想インターフェース) を構成するか、ブリッジと仮想イーサネット (veth) のペアを使用します。

*ベスト プラクティス:* このノードに最初にクライアント ネットワーク IP アドレスがない場合でも、値を指定します。その後、ホスト上のノードを再構成することなく、クライアント ネットワーク IP アドレスを追加できます。

例:

`bond0.1003`

`ens423`
 a| 
ベストプラクティス

|===


==== クライアントネットワークターゲットタイプ

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
インターフェース (サポートされている値は次のとおりです。)
 a| 
オプション

|===


==== クライアント_ネットワーク_ターゲット_タイプ_インターフェース_クローン_MAC

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
真か偽か

キーを「true」に設定すると、 StorageGRIDコンテナはクライアント ネットワーク上のホスト ターゲット インターフェイスの MAC アドレスを使用します。

*ベスト プラクティス:* 無差別モードが必要なネットワークでは、代わりに CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC キーを使用します。

MAC クローニングの詳細については、以下を参照してください。

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC アドレスの複製に関する考慮事項と推奨事項 (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC アドレスの複製に関する考慮事項と推奨事項 (Ubuntu または Debian)"]

 a| 
ベストプラクティス

|===


=== グリッドネットワークキー



==== GRID_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
静的またはDHCP

指定されていない場合はデフォルトで STATIC になります。
 a| 
ベストプラクティス

|===


==== グリッドネットワークゲートウェイ

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
このノードのローカル グリッド ネットワーク ゲートウェイの IPv4 アドレス。これは、GRID_NETWORK_IP および GRID_NETWORK_MASK によって定義されたサブネット上にある必要があります。この値は、DHCP 設定されたネットワークでは無視されます。

グリッド ネットワークがゲートウェイのない単一のサブネットである場合は、サブネットの標準ゲートウェイ アドレス (XYZ1) またはこのノードの GRID_NETWORK_IP 値のいずれかを使用します。どちらの値を使用しても、将来のグリッド ネットワークの拡張が簡素化されます。
 a| 
必須

|===


==== グリッドネットワークIP

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
グリッド ネットワーク上のこのノードの IPv4 アドレス。このキーは、GRID_NETWORK_CONFIG = STATIC の場合にのみ必要です。他の値の場合は指定しないでください。

例:

`1.1.1.1`

`10.224.4.81`
 a| 
GRID_NETWORK_CONFIG = STATIC の場合に必須

それ以外の場合はオプションです。

|===


==== グリッドネットワークMAC

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
コンテナ内のグリッド ネットワーク インターフェイスの MAC アドレス。

コロンで区切られた 6 組の 16 進数字である必要があります。

例： `b2:9c:02:c2:27:30`
 a| 
オプション

省略した場合、MAC アドレスは自動的に生成されます。

|===


==== グリッドネットワークマスク

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
グリッド ネットワーク上のこのノードの IPv4 ネットマスク。  GRID_NETWORK_CONFIG = STATIC の場合はこのキーを指定します。他の値の場合は指定しないでください。

例:

`255.255.255.0`

`255.255.248.0`
 a| 
GRID_NETWORK_IP が指定され、GRID_NETWORK_CONFIG = STATIC の場合に必須です。

それ以外の場合はオプションです。

|===


==== グリッドネットワークMTU

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
グリッド ネットワーク上のこのノードの最大転送単位 (MTU)。 GRID_NETWORK_CONFIG = DHCP の場合は指定しないでください。指定する場合、値は 1280 ～ 9216 の範囲でなければなりません。省略した場合は 1500 が使用されます。

ジャンボ フレームを使用する場合は、MTU を 9000 などのジャンボ フレームに適した値に設定します。それ以外の場合はデフォルト値を維持します。

*重要*: ネットワークの MTU 値は、ノードが接続されているスイッチ ポートで設定されている値と一致する必要があります。そうしないと、ネットワーク パフォーマンスの問題やパケット損失が発生する可能性があります。

*重要*: 最高のネットワーク パフォーマンスを得るには、すべてのノードのグリッド ネットワーク インターフェイスで同様の MTU 値を構成する必要があります。個々のノード上のグリッド ネットワークの MTU 設定に大きな違いがある場合、*グリッド ネットワーク MTU 不一致* アラートがトリガーされます。  MTU 値はすべてのネットワーク タイプで同じである必要はありません。

例:

`1500`

`8192`
 a| 
オプション

|===


==== グリッドネットワークターゲット

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
StorageGRIDノードによるグリッド ネットワーク アクセスに使用するホスト デバイスの名前。ネットワーク インターフェイス名のみがサポートされます。通常、ADMIN_NETWORK_TARGET または CLIENT_NETWORK_TARGET に指定されたものとは異なるインターフェース名を使用します。

*注意*: ネットワーク ターゲットとしてボンド デバイスまたはブリッジ デバイスを使用しないでください。ボンドデバイスの上に VLAN (またはその他の仮想インターフェース) を構成するか、ブリッジと仮想イーサネット (veth) のペアを使用します。

例:

`bond0.1001`

`ens192`
 a| 
必須

|===


==== グリッドネットワークターゲットタイプ

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
インターフェース (サポートされている値はこれだけです。)
 a| 
オプション

|===


==== GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
真か偽か

キーの値を「true」に設定すると、 StorageGRIDコンテナはグリッド ネットワーク上のホスト ターゲット インターフェイスの MAC アドレスを使用するようになります。

*ベスト プラクティス:* 無差別モードが必要なネットワークでは、代わりに GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC キーを使用します。

MAC クローニングの詳細については、以下を参照してください。

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC アドレスの複製に関する考慮事項と推奨事項 (Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC アドレスの複製に関する考慮事項と推奨事項 (Ubuntu または Debian)"]

 a| 
ベストプラクティス

|===


=== インストールパスワードキー（一時）



==== カスタム一時パスワードハッシュ

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
プライマリ管理ノードの場合、インストール中にStorageGRIDインストール API のデフォルトの一時パスワードを設定します。

*注意*: インストール パスワードはプライマリ管理ノードにのみ設定してください。別のノード タイプにパスワードを設定しようとすると、ノード構成ファイルの検証は失敗します。

インストールが完了したら、この値を設定しても効果はありません。

このキーを省略すると、デフォルトでは一時パスワードは設定されません。または、 StorageGRIDインストール API を使用して一時パスワードを設定することもできます。

である必要があります `crypt()`SHA-512パスワードハッシュの形式 `$6$<salt>$<password hash>`パスワードは 8 文字以上 32 文字以下でなければなりません。

このハッシュは、次のようなCLIツールを使用して生成できます。 `openssl passwd` SHA-512 モードのコマンド。
 a| 
ベストプラクティス

|===


=== インターフェースキー



==== インターフェースターゲット_nnnn

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
このノードに追加する追加インターフェースの名前とオプションの説明。各ノードに複数の追加インターフェースを追加できます。

_nnnn_ には、追加する各 INTERFACE_TARGET エントリに一意の番号を指定します。

値には、ベアメタル ホスト上の物理インターフェースの名前を指定します。次に、オプションでコンマを追加し、VLAN インターフェイス ページと HA グループ ページに表示されるインターフェイスの説明を入力します。

例： `INTERFACE_TARGET_0001=ens256, Trunk`

トランク インターフェイスを追加する場合は、 StorageGRIDで VLAN インターフェイスを設定する必要があります。アクセス インターフェイスを追加する場合は、インターフェイスを HA グループに直接追加できます。VLAN インターフェイスを構成する必要はありません。
 a| 
オプション

|===


=== 最大RAMキー



==== 最大RAM

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
このノードが消費できる RAM の最大量。このキーを省略すると、ノードにはメモリ制限はありません。実稼働レベルのノードに対してこのフィールドを設定する場合は、少なくとも 24 GB で、システム RAM の合計より 16 ～ 32 GB 少ない値を指定します。

*注意*: RAM 値は、ノードの実際のメタデータ予約領域に影響します。参照link:../admin/managing-object-metadata-storage.html["メタデータ予約領域とは何かの説明"]。

このフィールドの形式は `_numberunit_`、 どこ `_unit_`できる `b`、 `k` 、 `m` 、 または `g`。

例:

`24g`

`38654705664b`

*注意*: このオプションを使用する場合は、メモリ cgroup のカーネル サポートを有効にする必要があります。
 a| 
オプション

|===


=== ノードタイプキー



==== ノードタイプ

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
ノードの種類:

* VM_管理ノード
* VM_ストレージ_ノード
* VM_アーカイブ_ノード
* VM_API_ゲートウェイ

 a| 
必須

|===


==== ストレージタイプ

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
ストレージ ノードに含まれるオブジェクトのタイプを定義します。詳細については、以下を参照してください。 link:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードの種類"] 。このキーは、NODE_TYPE = VM_Storage_Node のノードにのみ必要です。他のノード タイプには指定しないでください。ストレージタイプ:

* 組み合わせた
* data
* metadata


*注*: STORAGE_TYPE が指定されていない場合、ストレージ ノード タイプはデフォルトで結合 (データとメタデータ) に設定されます。
 a| 
オプション

|===


=== ポート再マップキー



==== ポートリマップ

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
内部グリッド ノード通信または外部通信のためにノードによって使用されるポートを再マップします。エンタープライズネットワークポリシーがStorageGRIDで使用される1つ以上のポートを制限している場合、ポートの再マッピングが必要です。link:../network/internal-grid-node-communications.html["内部でのGridノードの通信"]またはlink:../network/external-communications.html["外部コミュニケーション"]。

*重要*: ロード バランサーのエンドポイントを構成するために使用する予定のポートを再マップしないでください。

*注*: PORT_REMAP のみが設定されている場合、指定したマッピングは受信通信と送信通信の両方に使用されます。  PORT_REMAP_INBOUND も指定されている場合、PORT_REMAP は送信通信にのみ適用されます。

使用される形式は次のとおりです。 `_network type_/_protocol_/_default port used by grid node_/_new port_` 、 どこ `_network type_`グリッド、管理者、またはクライアントであり、 `_protocol_` tcp または udp です。

例： `PORT_REMAP = client/tcp/18082/443`

カンマ区切りのリストを使用して複数のポートを再マップすることもできます。

例： `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
オプション

|===


==== ポート再マップ受信

[cols="4a,2a"]
|===
| Value | 指定 


 a| 
受信通信を指定されたポートに再マップします。  PORT_REMAP_INBOUND を指定しても、PORT_REMAP の値を指定しない場合は、ポートの送信通信は変更されません。

*重要*: ロード バランサーのエンドポイントを構成するために使用する予定のポートを再マップしないでください。

使用される形式は次のとおりです。 `_network type_/_protocol_/_remapped port_/_default port used by grid node_` 、 どこ `_network type_`グリッド、管理者、またはクライアントであり、 `_protocol_` tcp または udp です。

例： `PORT_REMAP_INBOUND = grid/tcp/3022/22`

カンマ区切りのリストを使用して複数の受信ポートを再マップすることもできます。

例： `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
オプション

|===