---
permalink: rhel/installing-linux.html 
sidebar: sidebar 
keywords: how to install on red hat linux 
summary: すべての Red Hat Enterprise Linux グリッド ホストにStorageGRIDをインストールする必要があります。サポートされているバージョンの一覧については、 NetApp相互運用性マトリックス ツールを使用してください。 
---
= Linuxをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべての Red Hat Enterprise Linux グリッド ホストにStorageGRIDをインストールする必要があります。サポートされているバージョンの一覧については、 NetApp相互運用性マトリックス ツールを使用してください。

.開始する前に
オペレーティング システムが、以下に示す StorageGRID の最小カーネル バージョン要件を満たしていることを確認してください。コマンドを使用する `uname -r`オペレーティング システムのカーネル バージョンを取得するには、または OS ベンダーに問い合わせてください。

[cols="1a,2a,2a"]
|===
| Red Hat Enterprise Linux バージョン | 最小カーネルバージョン | カーネルパッケージ名 


 a| 
8.8（非推奨）
 a| 
4.18.0-477.10.1.el8_8.x86_64
 a| 
カーネル-4.18.0-477.10.1.el8_8.x86_64



 a| 
8.10
 a| 
4.18.0-553.el8_10.x86_64
 a| 
カーネル-4.18.0-553.el8_10.x86_64



 a| 
9.0（非推奨）
 a| 
5.14.0-70.22.1.el9_0.x86_64
 a| 
カーネル-5.14.0-70.22.1.el9_0.x86_64



 a| 
9.2（非推奨）
 a| 
5.14.0-284.11.1.el9_2.x86_64
 a| 
カーネル-5.14.0-284.11.1.el9_2.x86_64



 a| 
9.4
 a| 
5.14.0-427.18.1.el9_4.x86_64
 a| 
カーネル-5.14.0-427.18.1.el9_4.x86_64



 a| 
9.6
 a| 
5.14.0-570.18.1.el9_6.x86_64
 a| 
カーネル-5.14.0-570.18.1.el9_6.x86_64

|===
.手順
. ディストリビューターの指示または標準の手順に従って、すべての物理または仮想グリッド ホストに Linux をインストールします。
+

NOTE: 標準の Linux インストーラーを使用している場合は、「コンピューティング ノード」ソフトウェア構成 (使用可能な場合) または「最小インストール」ベース環境を選択します。グラフィカルデスクトップ環境をインストールしないでください。

. すべてのホストが Extras チャネルを含むパッケージ リポジトリにアクセスできることを確認します。
+
このインストール手順の後半で、これらの追加パッケージが必要になる場合があります。

. スワップが有効な場合:
+
.. 次のコマンドを実行します。 `$ sudo swapoff --all`
.. すべてのスワップエントリを削除します `/etc/fstab`設定を保持します。


+

NOTE: スワップを完全に無効にしないと、パフォーマンスが大幅に低下する可能性があります。


