---
permalink: rhel/overview-of-installation-rest-api.html 
sidebar: sidebar 
keywords: installation overview red hat linux 
summary: StorageGRID は、インストール タスクを実行するためのStorageGRIDインストール API を提供します。 
---
= インストールREST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID は、インストール タスクを実行するためのStorageGRIDインストール API を提供します。

API は、Swagger オープンソース API プラットフォームを使用して API ドキュメントを提供します。 Swagger を使用すると、開発者と非開発者の両方が、API がパラメーターとオプションにどのように応答するかを示すユーザー インターフェースで API を操作できます。このドキュメントでは、標準の Web テクノロジーと JSON データ形式に精通していることを前提としています。


CAUTION: API ドキュメント Web ページを使用して実行するすべての API 操作はライブ操作です。誤って設定データやその他のデータを作成、更新、削除しないように注意してください。

各 REST API コマンドには、API の URL、HTTP アクション、必須またはオプションの URL パラメーター、および予想される API 応答が含まれます。



== StorageGRIDインストール API

StorageGRIDインストール API は、 StorageGRIDシステムを最初に構成するとき、およびプライマリ管理ノードのリカバリを実行する必要がある場合にのみ使用できます。インストール API には、グリッド マネージャーから HTTPS 経由でアクセスできます。

API ドキュメントにアクセスするには、プライマリ管理ノードのインストール Web ページに移動し、メニュー バーから *ヘルプ* > *API ドキュメント* を選択します。

StorageGRIDインストール API には、次のセクションが含まれています。

* *config* -- 製品リリースと API のバージョンに関連する操作。製品のリリース バージョンと、そのリリースでサポートされている API のメジャー バージョンを一覧表示できます。
* *grid* -- グリッドレベルの構成操作。グリッドの詳細、グリッド ネットワークのサブネット、グリッド パスワード、NTP および DNS サーバーの IP アドレスなどのグリッド設定を取得および更新できます。
* *nodes* -- ノードレベルの構成操作。グリッド ノードのリストを取得したり、グリッド ノードを削除したり、グリッド ノードを構成したり、グリッド ノードを表示したり、グリッド ノードの構成をリセットしたりできます。
* *provision* -- プロビジョニング操作。プロビジョニング操作を開始し、プロビジョニング操作のステータスを表示できます。
* *recovery* -- プライマリ管理ノードのリカバリ操作。情報をリセットしたり、回復パッケージをアップロードしたり、回復を開始したり、回復操作のステータスを表示したりできます。
* *recovery-package* -- リカバリ パッケージをダウンロードする操作。
* *sites* -- サイトレベルの構成操作。サイトを作成、表示、削除、変更できます。
* *temporary-password* -- インストール中に mgmt-api を保護するための一時パスワードに対する操作。

