---
permalink: rhel/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: 仮想マシンを使用して、あらゆるタイプのStorageGRIDノードをホストできます。グリッド ノードごとに 1 つの仮想マシンが必要です。 
---
= Red Hat Enterprise Linux のソフトウェア要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシンを使用して、あらゆるタイプのStorageGRIDノードをホストできます。グリッド ノードごとに 1 つの仮想マシンが必要です。

Red Hat Enterprise Linux (RHEL) にStorageGRIDをインストールするには、サードパーティのソフトウェア パッケージをいくつかインストールする必要があります。サポートされている一部の Linux ディストリビューションには、これらのパッケージがデフォルトで含まれていません。StorageGRIDインストールがテストされるソフトウェア パッケージのバージョンには、このページに記載されているものが含まれます。

これらのパッケージのいずれかを必要とする Linux ディストリビューションおよびコンテナー ランタイムのインストール オプションを選択した場合に、Linux ディストリビューションによって自動的にインストールされない場合は、プロバイダーまたは Linux ディストリビューションのサポート ベンダーから入手できる場合は、ここにリストされているバージョンのいずれかをインストールしてください。それ以外の場合は、ベンダーから入手可能なデフォルトのパッケージ バージョンを使用します。

すべてのインストール オプションには、Podman または Docker のいずれかが必要です。両方のパッケージをインストールしないでください。インストール オプションに必要なパッケージのみをインストールします。


NOTE: ソフトウェアのみのデプロイメント用のコンテナ エンジンとしての Docker のサポートは非推奨になりました。Docker は将来のリリースで別のコンテナ エンジンに置き換えられる予定です。



== テストされたPythonのバージョン

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6




== テストされたPodmanのバージョン

* 3.2.3-0
* 3.4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12




== テスト済みのDockerバージョン


IMPORTANT: Docker サポートは非推奨であり、将来のリリースで削除される予定です。

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3
* Docker-CE 23.0.6-1
* Docker-CE 24.0.2-1
* Docker-CE 24.0.4-1
* Docker-CE 24.0.5-1
* Docker-CE 24.0.7-1
* 1.5-2

