---
permalink: admin/admin-group-permissions.html 
sidebar: sidebar 
keywords: admin group permissions 
summary: 管理者ユーザー グループを作成するときは、グリッド マネージャーの特定の機能へのアクセスを制御するための 1 つ以上の権限を選択します。その後、各ユーザーを 1 つ以上の管理者グループに割り当てて、そのユーザーが実行できるタスクを決定できます。 
---
= 管理者グループの権限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理者ユーザー グループを作成するときは、グリッド マネージャーの特定の機能へのアクセスを制御するための 1 つ以上の権限を選択します。その後、各ユーザーを 1 つ以上の管理者グループに割り当てて、そのユーザーが実行できるタスクを決定できます。

各グループに少なくとも 1 つの権限を割り当てる必要があります。そうしないと、そのグループに属するユーザーは Grid Manager または Grid Management API にサインインできなくなります。

デフォルトでは、少なくとも 1 つの権限を持つグループに属するすべてのユーザーは、次のタスクを実行できます。

* グリッドマネージャーにSign in
* ダッシュボードを見る
* ノードページを表示する
* 現在のアラートと解決済みのアラートを表示する
* 自分のパスワードを変更する（ローカル ユーザーのみ）
* 構成ページとメンテナンスページで提供される特定の情報を表示します




== 権限とアクセスモードの相互作用

すべての権限について、グループの *アクセス モード* 設定によって、ユーザーが設定を変更して操作を実行できるかどうか、または関連する設定と機能の表示のみが可能かどうかが決まります。ユーザーが複数のグループに属しており、いずれかのグループが *読み取り専用* に設定されている場合、ユーザーは選択したすべての設定と機能に対して読み取り専用アクセス権を持ちます。

次のセクションでは、管理者グループを作成または編集するときに割り当てることができる権限について説明します。明示的に記載されていない機能には、*ルート アクセス* 権限が必要です。



== ルート アクセス

この権限により、すべてのグリッド管理機能にアクセスできます。



== テナントのルートパスワードを変更する

この権限により、テナント ページの *ルート パスワードの変更* オプションにアクセスでき、テナントのローカル ルート ユーザーのパスワードを変更できるユーザーを制御できます。この権限は、S3 キーのインポート機能が有効になっている場合に S3 キーを移行するためにも使用されます。この権限を持たないユーザーには、*ルート パスワードの変更* オプションは表示されません。


NOTE: *ルート パスワードの変更* オプションを含むテナント ページへのアクセスを許可するには、*テナント アカウント* 権限も割り当てます。



== グリッドトポロジページの構成

この権限により、*サポート* > *ツール* > *グリッド トポロジ* ページの構成タブにアクセスできます。


NOTE: グリッド トポロジ ページは非推奨となり、将来のリリースで削除される予定です。



== ILM

この権限により、次の *ILM* メニュー オプションにアクセスできます。

* ルール
* ポリシー
* ポリシータグ
* ストレージプール
* 保管グレード
* 地域
* オブジェクトメタデータ検索



NOTE: ストレージ グレードを管理するには、ユーザーは *その他のグリッド構成* および *グリッド トポロジ ページ構成* 権限を持っている必要があります。



== メンテナンス

これらのオプションを使用するには、ユーザーはメンテナンス権限を持っている必要があります。

* *構成* > *アクセス制御*:
+
** グリッドパスワード


* *設定* > *ネットワーク*:
+
** S3エンドポイントのドメイン名


* *メンテナンス* > *タスク*:
+
** 運用停止
** 拡張
** オブジェクトの存在チェック
** リカバリ


* *メンテナンス* > *システム*:
+
** 回復パッケージ
** ソフトウェアアップデート


* *サポート* > *ツール*:
+
** Logs




メンテナンス権限を持たないユーザーは、次のページを表示できますが、編集することはできません。

* *メンテナンス* > *ネットワーク*:
+
** DNSサーバ
** グリッド ネットワーク
** NTPサーバ


* *メンテナンス* > *システム*:
+
** ライセンス


* *設定* > *ネットワーク*:
+
** S3エンドポイントのドメイン名


* *構成* > *セキュリティ*:
+
** 証明書


* *構成* > *監視*:
+
** 監査および Syslog サーバー






== アラートを管理する

この権限により、アラートを管理するためのオプションにアクセスできます。サイレンス、アラート通知、アラート ルールを管理するには、ユーザーにこの権限が必要です。



== メトリクスクエリ

この権限により、次のものへのアクセスが提供されます:

* *サポート* > *ツール* > *メトリクス* ページ
* グリッド管理 API の *Metrics* セクションを使用したカスタム Prometheus メトリック クエリ
* メトリックを含むグリッド マネージャー ダッシュボード カード




== オブジェクトメタデータ検索

この権限により、*ILM* > *オブジェクト メタデータ検索* ページへのアクセスが提供されます。



== その他のグリッド構成

この権限により、追加のグリッド構成オプションにアクセスできます。


TIP: これらの追加オプションを表示するには、ユーザーは *グリッド トポロジ ページの構成* 権限も持っている必要があります。

* *ILM*:
+
** 保管グレード


* *構成* > *システム*:
* *サポート* > *その他*:
+
** リンクコスト






== ストレージアプライアンス管理者

この権限により、次のことが提供されます。

* グリッド マネージャーを介してストレージ アプライアンス上の E シリーズSANtricityシステム マネージャーにアクセスします。
* これらの操作をサポートするアプライアンスの「ドライブの管理」タブでトラブルシューティングおよびメンテナンス タスクを実行する機能。




== テナントアカウント

この権限により、次のことが可能になります:

* テナントページにアクセスして、テナントアカウントを作成、編集、削除できます。
* 既存のトラフィック分類ポリシーを表示する
* テナントの詳細を含むグリッド マネージャー ダッシュボード カードを表示する

