---
permalink: admin/benefits-of-active-idle-and-concurrent-http-connections.html 
sidebar: sidebar 
keywords: active http connection benefits, idle http connection benefits, concurrent http connection benefits 
summary: HTTP 接続の構成方法は、 StorageGRIDシステムのパフォーマンスに影響を与える可能性があります。構成は、HTTP 接続がアクティブかアイドルか、または複数の同時接続があるかによって異なります。 
---
= アクティブ、アイドル、同時HTTP接続の利点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HTTP 接続の構成方法は、 StorageGRIDシステムのパフォーマンスに影響を与える可能性があります。構成は、HTTP 接続がアクティブかアイドルか、または複数の同時接続があるかによって異なります。

次の種類の HTTP 接続のパフォーマンス上の利点を確認できます。

* アイドル状態のHTTP接続
* アクティブなHTTP接続
* 同時HTTP接続




== アイドル状態のHTTP接続を開いたままにしておくことの利点

クライアント アプリケーションがアイドル状態のときでも HTTP 接続を開いたままにして、クライアント アプリケーションが開いている接続を介して後続のトランザクションを実行できるようにする必要があります。NetAppでは、アイドルHTTP接続を開いておく時間を10分までにすることを推奨します。  StorageGRID は、10 分以上開いたままアイドル状態になっている HTTP 接続を自動的に閉じる場合があります。

オープンおよびアイドル状態の HTTP 接続には、次のような利点があります。

* StorageGRIDシステムがHTTPトランザクションを実行する必要があると判断した時点から、 StorageGRIDシステムがトランザクションを実行できる時点までのレイテンシが短縮されます。
+
待ち時間の短縮は、特に TCP/IP および TLS 接続を確立するために必要な時間に関して、主な利点です。

* 以前に実行された転送でTCP/IPスロースタートアルゴリズムを準備することにより、データ転送速度が向上します。
* クライアント アプリケーションとStorageGRIDシステム間の接続を中断するいくつかのクラスの障害状態を即時に通知します。


アイドル接続を開いたままにする時間を決定することは、既存の接続に関連付けられたスロースタートの利点と、内部システム リソースへの接続の理想的な割り当てとの間のトレードオフです。



== アクティブHTTP接続の利点

ストレージ ノードに直接接続する場合、HTTP 接続でトランザクションが継続的に実行される場合でも、アクティブな HTTP 接続の継続時間を最大 10 分に制限する必要があります。

接続を開いたままにしておくべき最大期間を決定することは、接続の永続性の利点と、内部システム リソースへの接続の理想的な割り当てとの間のトレードオフです。

ストレージ ノードへのクライアント接続の場合、アクティブな HTTP 接続を制限すると、次の利点が得られます。

* StorageGRIDシステム全体で最適な負荷分散を実現します。
+
時間の経過とともに、負荷分散の要件が変化するため、HTTP 接続が最適ではなくなる可能性があります。クライアント アプリケーションがトランザクションごとに個別の HTTP 接続を確立すると、システムは最適な負荷分散を実行しますが、これにより、永続的な接続に関連するより貴重な利点が打ち消されます。

* クライアント アプリケーションが、使用可能なスペースを持つ LDR サービスに HTTP トランザクションを送信できるようにします。
* メンテナンス手順を開始できます。
+
一部のメンテナンス手順は、進行中の HTTP 接続がすべて完了した後にのみ開始されます。



ロード バランサ サービスへのクライアント接続の場合、開いている接続の期間を制限すると、一部のメンテナンス手順をすぐに開始できるようになります。クライアント接続の期間が制限されていない場合は、アクティブな接続が自動的に終了するまでに数分かかることがあります。



== 同時HTTP接続の利点

並列処理を可能にしてパフォーマンスを向上させるには、 StorageGRIDシステムへの複数の TCP/IP 接続を開いたままにしておく必要があります。並列接続の最適な数は、さまざまな要因によって異なります。

同時 HTTP 接続には次のような利点があります。

* 遅延の低減
+
他のトランザクションが完了するのを待たずに、トランザクションをすぐに開始できます。

* スループットの向上
+
StorageGRIDシステムは並列トランザクションを実行し、総トランザクション スループットを向上させることができます。



クライアント アプリケーションは複数の HTTP 接続を確立する必要があります。クライアント アプリケーションがトランザクションを実行する必要がある場合、現在トランザクションを処理していない確立された接続を選択してすぐに使用できます。

各StorageGRIDシステムのトポロジでは、パフォーマンスが低下し始めるまでの同時トランザクションおよび接続のピーク スループットが異なります。ピーク スループットは、コンピューティング リソース、ネットワーク リソース、ストレージ リソース、WAN リンクなどの要因によって異なります。サーバーとサービスの数、およびStorageGRIDシステムがサポートするアプリケーションの数も要因となります。

StorageGRIDシステムは、多くの場合、複数のクライアント アプリケーションをサポートします。クライアント アプリケーションで使用される同時接続の最大数を決定するときは、この点に留意する必要があります。クライアント アプリケーションが、それぞれStorageGRIDシステムへの接続を確立する複数のソフトウェア エンティティで構成されている場合は、エンティティ間のすべての接続を合計する必要があります。次の状況では、同時接続の最大数を調整する必要が生じる場合があります。

* StorageGRIDシステムのトポロジは、システムがサポートできる同時トランザクションと接続の最大数に影響します。
* 帯域幅が制限されたネットワーク経由でStorageGRIDシステムと対話するクライアント アプリケーションでは、個々のトランザクションが適切な時間内に完了するように同時実行の度合いを下げる必要がある場合があります。
* 多数のクライアント アプリケーションがStorageGRIDシステムを共有する場合、システムの制限を超えないように同時実行の度合いを下げる必要がある場合があります。




== 読み取り操作と書き込み操作の HTTP 接続プールの分離

読み取り操作と書き込み操作に別々の HTTP 接続プールを使用し、それぞれに使用するプールの量を制御できます。  HTTP 接続の個別のプールにより、トランザクションをより適切に制御し、負荷を分散できるようになります。

クライアント アプリケーションは、取得主体 (読み取り) または保存主体 (書き込み) のロードを作成できます。読み取りトランザクションと書き込みトランザクションに別々の HTTP 接続プールを使用することで、各プールのどれだけを読み取りまたは書き込みトランザクション専用にするかを調整できます。
