---
permalink: admin/changing-network-options-object-encryption.html 
sidebar: sidebar 
keywords: enable http, storage node connections 
summary: ネットワークとオブジェクトのセキュリティを設定して、保存されたオブジェクトを暗号化したり、特定の S3 リクエストを防止したり、ストレージノードへのクライアント接続で HTTPS ではなく HTTP を使用できるようにしたりできます。 
---
= ネットワークとオブジェクトのセキュリティを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークとオブジェクトのセキュリティを設定して、保存されたオブジェクトを暗号化したり、特定の S3 リクエストを防止したり、ストレージノードへのクライアント接続で HTTPS ではなく HTTP を使用できるようにしたりできます。



== 保存されたオブジェクトの暗号化

保存されたオブジェクトの暗号化により、S3 を介して取り込まれるすべてのオブジェクト データの暗号化が可能になります。デフォルトでは、保存されたオブジェクトは暗号化されませんが、AES‐128 または AES‐256 暗号化アルゴリズムを使用してオブジェクトを暗号化することを選択できます。この設定を有効にすると、新しく取り込まれたすべてのオブジェクトが暗号化されますが、既存の保存されたオブジェクトは変更されません。暗号化を無効にすると、現在暗号化されているオブジェクトは暗号化されたままになりますが、新しく取り込まれたオブジェクトは暗号化されません。

保存されたオブジェクトの暗号化設定は、バケットレベルまたはオブジェクトレベルの暗号化によって暗号化されていない S3 オブジェクトにのみ適用されます。

StorageGRID暗号化方式の詳細については、以下を参照してください。link:../admin/reviewing-storagegrid-encryption-methods.html["StorageGRIDの暗号化方式を確認する"] 。



== クライアントの変更を防止する

クライアントの変更を禁止するのはシステム全体の設定です。  *クライアントの変更を禁止する* オプションを選択すると、次の要求は拒否されます。



=== S3 REST API

* DeleteBucketリクエスト
* 既存のオブジェクトのデータ、ユーザー定義のメタデータ、または S3 オブジェクトのタグ付けを変更するリクエスト




== ストレージノード接続にHTTPを有効にする

デフォルトでは、クライアント アプリケーションは、ストレージ ノードへの直接接続に HTTPS ネットワーク プロトコルを使用します。オプションで、非本番グリッドをテストする場合など、これらの接続に対して HTTP を有効にすることもできます。

S3 クライアントがストレージ ノードに直接 HTTP 接続を行う必要がある場合にのみ、ストレージ ノード接続に HTTP を使用します。  HTTPS接続のみを使用するクライアントや、ロードバランササービスに接続するクライアントの場合は、このオプションを使用する必要はありません（link:../admin/configuring-load-balancer-endpoints.html["各ロードバランサのエンドポイントを構成する"] HTTP または HTTPS のいずれかを使用します。

見るlink:summary-ip-addresses-and-ports-for-client-connections.html["概要: クライアント接続の IP アドレスとポート"]HTTP または HTTPS を使用してストレージ ノードに接続するときに S3 クライアントが使用するポートを確認します。



== オプションを選択

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* ルートアクセス権限があります。


.手順
. *構成* > *セキュリティ* > *セキュリティ設定*を選択します。
. *ネットワークとオブジェクト*タブを選択します。
. 保存されたオブジェクトの暗号化については、保存されたオブジェクトを暗号化しない場合は *なし* (デフォルト) 設定を使用し、保存されたオブジェクトを暗号化するには *AES-128* または *AES-256* を選択します。
. S3 クライアントが特定のリクエストを行わないようにする場合は、オプションで *クライアントの変更を禁止する* を選択します。
+

NOTE: この設定を変更した場合、新しい設定が適用されるまで約 1 分かかります。構成された値は、パフォーマンスとスケーリングのためにキャッシュされます。

. クライアントがストレージ ノードに直接接続し、HTTP 接続を使用する場合は、オプションで [*ストレージ ノード接続に HTTP を有効にする*] を選択します。
+

NOTE: 実稼働グリッドで HTTP を有効にする場合は、リクエストが暗号化されずに送信されるため注意してください。

. *保存*を選択します。

