---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: 管理ノードの SSH アクセス パスワードを変更すると、グリッド内の各ノードの一意の内部 SSH キー セットも更新されます。プライマリ管理ノードは、これらの SSH キーを使用して、安全なパスワードレス認証でノードにアクセスします。 
---
= 管理ノードのSSHアクセスパスワードを変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理ノードの SSH アクセス パスワードを変更すると、グリッド内の各ノードの一意の内部 SSH キー セットも更新されます。プライマリ管理ノードは、これらの SSH キーを使用して、安全なパスワードレス認証でノードにアクセスします。

SSHキーを使用してノードにログインします `admin`または、VM または物理コンソール接続上の root ユーザーにアクセスします。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:admin-group-permissions.html["メンテナンスまたはルートアクセス権限"]。
* 現在のプロビジョニング パスフレーズを持っています。


.タスク概要
管理ノードの新しいアクセスパスワードと各ノードの新しい内部キーは、 `Passwords.txt`リカバリ パッケージ内のファイル。キーはそのファイルの「パスワード」列にリストされています。

ノード間の通信に使用される SSH キーには、個別の SSH アクセス パスワードがあります。これらはこの手順では変更されません。



== ウィザードにアクセスする

.手順
. *構成* > *アクセス制御* > *グリッド パスワード* を選択します。
. *SSH キーの変更* の下で、*変更を加える* を選択します。




== [[download-current]]現在のリカバリパッケージをダウンロードする

SSH アクセス キーを変更する前に、最新のリカバリ パッケージをダウンロードしてください。いずれかのノードでキー変更プロセスが失敗した場合は、このファイル内のキーを使用できます。

.手順
. グリッドのプロビジョニング パスフレーズを入力します。
. *リカバリ パッケージのダウンロード*を選択します。
. リカバリパッケージファイルをコピーする(`.zip`) を 2 つの安全でセキュリティ保護された別の場所に保管します。
+

CAUTION: リカバリ パッケージ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティ保護する必要があります。

. *続行*を選択します。
. 確認ダイアログが表示されたら、SSH アクセス キーの変更を開始する準備ができたら [*はい*] を選択します。
+

CAUTION: このプロセスは開始後にキャンセルすることはできません。





== SSHアクセスキーを変更する

SSH アクセス キーの変更プロセスが開始されると、新しいキーを含む新しいリカバリ パッケージが生成されます。その後、各ノードでキーが更新されます。

.手順
. 新しい回復パッケージが生成されるまで待ちます。これには数分かかる場合があります。
. 新しいリカバリパッケージのダウンロードボタンが有効になったら、*新しいリカバリパッケージのダウンロード*を選択し、新しいリカバリパッケージファイルを保存します。(`.zip` ) を 2 つの安全でセキュリティ保護された別の場所に保管します。
. ダウンロードが完了すると次のようになります。
+
.. 開く `.zip`ファイル。
.. 以下のコンテンツにアクセスできることを確認してください。 `Passwords.txt`新しい SSH アクセス キーが含まれるファイル。
.. 新しいリカバリパッケージファイルをコピーします(`.zip`) を 2 つの安全でセキュリティ保護された別の場所に保管します。
+

CAUTION: 古いリカバリ パッケージを上書きしないでください。

+
リカバリ パッケージ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティ保護する必要があります。



. 各ノードでキーが更新されるまで待ちます。これには数分かかる場合があります。
+
すべてのノードのキーが変更されると、緑色の成功バナーが表示されます。

+
更新プロセス中にエラーが発生した場合、キーの変更に失敗したノードの数がバナー メッセージにリストされます。システムは、キーの変更に失敗したノード上でプロセスを自動的に再試行します。一部のノードにまだ変更されたキーがない状態でプロセスが終了した場合は、[再試行] ボタンが表示されます。

+
1 つ以上のノードでキーの更新に失敗した場合:

+
.. 表にリストされているエラー メッセージを確認します。
.. 問題を解決してください。
.. *再試行*を選択します。
+
再試行すると、以前のキー変更の試行中に失敗したノード上の SSH アクセス キーのみが変更されます。



. すべてのノードのSSHアクセスキーが変更されたら、<<download-current,最初にダウンロードしたリカバリパッケージ>> 。
. オプションで、*メンテナンス* > *システム* > *リカバリ パッケージ* を選択して、新しいリカバリ パッケージの追加コピーをダウンロードします。

