---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: security, browser inactivity timeout, management API stack track 
summary: インターフェース セキュリティ設定では、指定された時間を超えてユーザーが非アクティブだった場合にユーザーをログアウトするかどうか、および API エラー応答にスタック トレースを含めるかどうかを制御できます。 
---
= インターフェースのセキュリティ設定を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インターフェース セキュリティ設定では、指定された時間を超えてユーザーが非アクティブだった場合にユーザーをログアウトするかどうか、および API エラー応答にスタック トレースを含めるかどうかを制御できます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたが持っているlink:admin-group-permissions.html["ルートアクセス権限"]。


.タスク概要
*セキュリティ設定* ページには、*ブラウザの非アクティブ タイムアウト* と *管理 API スタック トレース* の設定が含まれています。

ブラウザの非アクティブタイムアウト:: ユーザーがサインアウトするまでに、ユーザーのブラウザが非アクティブになっていられる時間を示します。デフォルトは15分です。
+
--
ブラウザの非アクティブ タイムアウトは、次の要素によっても制御されます。

* システム セキュリティのために組み込まれた、個別の構成不可能なStorageGRIDタイマー。各ユーザーの認証トークンは、ユーザーがサインインしてから 16 時間後に期限切れになります。ユーザーの認証の有効期限が切れると、ブラウザの非アクティブ タイムアウトが無効になっている場合やブラウザのタイムアウト値に達していない場合でも、そのユーザーは自動的にサインアウトされます。トークンを更新するには、ユーザーは再度サインインする必要があります。
* StorageGRIDでシングル サインオン (SSO) が有効になっていることを前提とした、ID プロバイダーのタイムアウト設定。
+
SSO が有効になっていて、ユーザーのブラウザがタイムアウトした場合、ユーザーは SSO 資格情報を再入力してStorageGRID に再度アクセスする必要があります。見るlink:configuring-sso.html["シングルサインオンを構成する"] 。



--
管理APIスタックトレース:: Grid Manager および Tenant Manager API エラー応答でスタック トレースが返されるかどうかを制御します。
+
--
このオプションはデフォルトで無効になっていますが、テスト環境ではこの機能を有効にする必要がある場合があります。一般に、API エラーが発生したときに内部ソフトウェアの詳細が公開されないように、運用環境ではスタック トレースを無効のままにしておく必要があります。

--


.手順
. *構成* > *セキュリティ* > *セキュリティ設定*を選択します。
. *インターフェース*タブを選択します。
. ブラウザの非アクティブタイムアウトの設定を変更するには:
+
.. アコーディオンを展開します。
.. タイムアウト期間を変更するには、60 秒から 7 日間の値を指定します。デフォルトのタイムアウトは 15 分です。
.. この機能を無効にするには、チェックボックスをオフにします。
.. *保存*を選択します。
+
新しい設定は、現在サインインしているユーザーには影響しません。新しいタイムアウト設定を有効にするには、ユーザーは再度サインインするか、ブラウザを更新する必要があります。



. 管理 API スタック トレースの設定を変更するには:
+
.. アコーディオンを展開します。
.. チェックボックスを選択すると、Grid Manager および Tenant Manager API エラー応答でスタック トレースが返されます。
+

CAUTION: API エラーが発生したときに内部ソフトウェアの詳細が公開されないように、運用環境ではスタック トレースを無効のままにしておきます。

.. *保存*を選択します。



