---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: グリッド内の各ノードには一意のノード コンソール パスワードがあり、ノードにログインするにはこのパスワードが必要です。グリッド内の各ノードのノード コンソール パスワードを変更するには、次の手順に従います。パスワードはリカバリ パッケージに保存されます。 
---
= ノードコンソールのパスワードを変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド内の各ノードには一意のノード コンソール パスワードがあり、ノードにログインするにはこのパスワードが必要です。グリッド内の各ノードの固有のノード コンソール パスワードを変更するには、次の手順に従います。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:admin-group-permissions.html["メンテナンスまたはルートアクセス権限"]。
* 現在のプロビジョニング パスフレーズを持っています。


.タスク概要
ノード コンソールのパスワードを使用して、SSH を使用して「admin」としてノードにログインするか、VM/物理コンソール接続で root ユーザーとしてログインします。ノードコンソールのパスワード変更プロセスは、グリッド内の各ノードに新しいパスワードを作成し、更新されたパスワードを保存します。 `Passwords.txt`リカバリ パッケージ内のファイル。パスワードは、Passwords.txt ファイルの「パスワード」列に記載されています。


NOTE: ノード間の通信に使用される SSH キーには、個別の SSH アクセス パスワードがあります。この手順では SSH アクセス パスワードは変更されません。



== ウィザードにアクセスする

.手順
. *構成* > *アクセス制御* > *グリッド パスワード* を選択します。
. *ノード コンソールのパスワードの変更* の下で、*変更を行う* を選択します。




== プロビジョニングパスフレーズを入力してください

.手順
. グリッドのプロビジョニング パスフレーズを入力します。
. *続行*を選択します。




== [[download-current]]現在のリカバリパッケージをダウンロードする

ノード コンソールのパスワードを変更する前に、現在のリカバリ パッケージをダウンロードしてください。いずれかのノードでパスワード変更プロセスが失敗した場合は、このファイル内のパスワードを使用できます。

.手順
. *リカバリ パッケージのダウンロード*を選択します。
. リカバリパッケージファイルをコピーする(`.zip`) を 2 つの安全でセキュリティ保護された別の場所に保管します。
+

CAUTION: リカバリ パッケージ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティ保護する必要があります。

. *続行*を選択します。
. 確認ダイアログが表示されたら、ノード コンソールのパスワードの変更を開始する準備ができたら [*はい*] を選択します。
+
このプロセスは開始後にキャンセルすることはできません。





== ノードコンソールのパスワードを変更する

ノード コンソールのパスワード プロセスが開始すると、新しいパスワードを含む新しいリカバリ パッケージが生成されます。その後、各ノードでパスワードが更新されます。

.手順
. 新しい回復パッケージが生成されるまで待ちます。これには数分かかる場合があります。
. *新しいリカバリ パッケージのダウンロード*を選択します。
. ダウンロードが完了すると次のようになります。
+
.. 開く `.zip`ファイル。
.. 以下のコンテンツにアクセスできることを確認してください。 `Passwords.txt`ファイルには新しいノード コンソールのパスワードが含まれています。
.. 新しいリカバリパッケージファイルをコピーします(`.zip`) を 2 つの安全でセキュリティ保護された別の場所に保管します。
+

CAUTION: 古いリカバリ パッケージを上書きしないでください。

+
リカバリ パッケージ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティ保護する必要があります。



. 新しいリカバリ パッケージをダウンロードし、その内容を確認したことを示すには、チェックボックスを選択します。
. *ノード コンソールのパスワードの変更* を選択し、すべてのノードが新しいパスワードで更新されるまで待ちます。これには数分かかる場合があります。
+
すべてのノードのパスワードが変更されると、緑色の成功バナーが表示されます。次の手順へ進みます。

+
更新プロセス中にエラーが発生した場合、バナー メッセージにパスワードの変更に失敗したノードの数が表示されます。システムは、パスワードの変更に失敗したノードに対してプロセスを自動的に再試行します。一部のノードでパスワードが変更されていない状態でプロセスが終了した場合は、[再試行] ボタンが表示されます。

+
1 つ以上のノードでパスワードの更新に失敗した場合:

+
.. 表にリストされているエラー メッセージを確認します。
.. 問題を解決してください。
.. *再試行*を選択します。
+

NOTE: 再試行すると、以前のパスワード変更の試行中に失敗したノード上のノード コンソール パスワードのみが変更されます。



. すべてのノードのノードコンソールのパスワードが変更されたら、<<download-current,最初にダウンロードしたリカバリパッケージ>> 。
. 必要に応じて、*リカバリ パッケージ* リンクを使用して、新しいリカバリ パッケージの追加コピーをダウンロードします。

