---
permalink: admin/configuring-storage-proxy-settings.html 
sidebar: sidebar 
keywords: storage proxy, non-transparent proxy, platform service endpoint 
summary: プラットフォーム サービスまたはクラウド ストレージ プールを使用している場合は、ストレージ ノードと外部 S3 エンドポイント間に非透過プロキシを構成できます。たとえば、プラットフォーム サービス メッセージをインターネット上のエンドポイントなどの外部エンドポイントに送信できるようにするには、非透過プロキシが必要になる場合があります。 
---
= ストレージプロキシを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プラットフォーム サービスまたはクラウド ストレージ プールを使用している場合は、ストレージ ノードと外部 S3 エンドポイント間に非透過プロキシを構成できます。たとえば、プラットフォーム サービス メッセージをインターネット上のエンドポイントなどの外部エンドポイントに送信できるようにするには、非透過プロキシが必要になる場合があります。


NOTE: 構成されたストレージ プロキシ設定は、Kafka プラットフォーム サービス エンドポイントには適用されません。

.開始する前に
* あなたが持っているlink:admin-group-permissions.html["特定のアクセス権限"]。
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。


.タスク概要
単一のストレージ プロキシの設定を構成できます。

.手順
. *構成* > *セキュリティ* > *プロキシ設定*を選択します。
. *ストレージ*タブで、*ストレージ プロキシを有効にする*チェックボックスをオンにします。
. ストレージ プロキシのプロトコルを選択します。
. プロキシ サーバーのホスト名または IP アドレスを入力します。
. 必要に応じて、プロキシ サーバーに接続するために使用するポートを入力します。
+
プロトコルのデフォルト ポート (HTTP の場合は 80、SOCKS5 の場合は 1080) を使用するには、このフィールドを空白のままにします。

. *保存*を選択します。
+
ストレージ プロキシを保存した後、プラットフォーム サービスまたはクラウド ストレージ プールの新しいエンドポイントを構成してテストできます。

+

NOTE: プロキシの変更が有効になるまでに最大 10 分かかる場合があります。

. プロキシ サーバーの設定を確認し、 StorageGRIDからのプラットフォーム サービス関連のメッセージがブロックされないようにします。
. ストレージ プロキシを無効にする必要がある場合は、チェックボックスをオフにして、[保存] を選択します。

