---
permalink: admin/configuring-admin-proxy-settings.html 
sidebar: sidebar 
keywords: admin proxy, autosupport, non-transparent proxy 
summary: 'HTTP または HTTPS を使用してAutoSupportパッケージを送信する場合は、管理ノードとテクニカル サポート (AutoSupport) の間に非透過プロキシ サーバーを設定できます。' 
---
= 管理プロキシ設定を構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HTTP または HTTPS を使用してAutoSupportパッケージを送信する場合は、管理ノードとテクニカル サポート (AutoSupport) の間に非透過プロキシ サーバーを設定できます。

AutoSupportの詳細については、以下を参照してください。link:configure-autosupport-grid-manager.html["AutoSupportを構成する"] 。

.開始する前に
* あなたが持っているlink:admin-group-permissions.html["特定のアクセス権限"]。
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。


.タスク概要
単一の管理プロキシの設定を構成できます。

.手順
. *構成* > *セキュリティ* > *プロキシ設定*を選択します。
+
プロキシ設定ページが表示されます。デフォルトでは、タブ メニューで [ストレージ] が選択されています。

. *管理者*タブを選択します。
. *管理プロキシを有効にする*チェックボックスを選択します。
. プロキシ サーバーのホスト名または IP アドレスを入力します。
. プロキシ サーバーに接続するために使用するポートを入力します。
. 必要に応じて、プロキシ サーバーのユーザー名とパスワードを入力します。
+
プロキシ サーバーでユーザー名またはパスワードが不要な場合は、これらのフィールドを空白のままにしておきます。

. 次のいずれかを選択します。
+
** 管理プロキシへの接続を保護する場合は、「プロキシ証明書の検証」を選択します。管理プロキシ サーバーによって提示された SSL 証明書の信頼性を検証するために、CA バンドルをアップロードします。
+

CAUTION: プロキシ証明書が検証されている場合、 AutoSupport on Demand、 StorageGRID経由の E シリーズAutoSupport 、およびStorageGRIDアップグレード ページでの更新パスの決定は機能しません。

+
CA バンドルをアップロードすると、そのメタデータが表示されます。

** 管理プロキシ サーバーと通信するときに証明書を検証しない場合は、[プロキシ証明書を検証しない] を選択します。


. *保存*を選択します。
+
管理プロキシが保存されると、管理ノードとテクニカル サポート間のプロキシ サーバーが構成されます。

+

NOTE: プロキシの変更が有効になるまでに最大 10 分かかる場合があります。

. 管理プロキシを無効にする必要がある場合は、[管理プロキシを有効にする] チェックボックスをオフにして、[保存] を選択します。

