---
permalink: admin/configuring-stored-object-compression.html 
sidebar: sidebar 
keywords: object compression, compress stored objects 
summary: オブジェクト圧縮を有効にすると、 StorageGRIDに保存されるオブジェクトのサイズが縮小され、オブジェクトが消費するストレージが少なくなります。 
---
= 保存されたオブジェクトを圧縮する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクト圧縮を有効にすると、 StorageGRIDに保存されるオブジェクトのサイズが縮小され、オブジェクトが消費するストレージが少なくなります。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたが持っているlink:admin-group-permissions.html["特定のアクセス権限"]。


.タスク概要
デフォルトでは、オブジェクトの圧縮は無効になっています。圧縮を有効にすると、 StorageGRID は保存時にロスレス圧縮を使用して各オブジェクトを圧縮しようとします。


NOTE: この設定を変更した場合、新しい設定が適用されるまで約 1 分かかります。構成された値は、パフォーマンスとスケーリングのためにキャッシュされます。

オブジェクト圧縮を有効にする前に、次の点に注意してください。

* 保存されるデータが圧縮可能であることがわかっていない限り、[*保存されたオブジェクトの圧縮*] を選択しないでください。
* オブジェクトをStorageGRIDに保存するアプリケーションは、保存する前にオブジェクトを圧縮する場合があります。クライアント アプリケーションがオブジェクトをStorageGRIDに保存する前にすでに圧縮している場合は、このオプションを選択してもオブジェクトのサイズはさらに縮小されません。
* StorageGRIDでNetApp FabricPoolを使用している場合は、「*保存されたオブジェクトの圧縮*」を選択しないでください。
* *保存されたオブジェクトを圧縮* を選択した場合、S3 クライアント アプリケーションは、返されるバイトの範囲を指定する GetObject 操作の実行を回避する必要があります。これらの「範囲読み取り」操作は、 StorageGRID が要求されたバイトにアクセスするためにオブジェクトを効果的に解凍する必要があるため、非効率的です。非常に大きなオブジェクトから小さな範囲のバイトを要求する GetObject 操作は特に非効率的です。たとえば、50 GB の圧縮されたオブジェクトから 10 MB の範囲を読み取るのは非効率的です。
+
範囲が圧縮されたオブジェクトから読み取られる場合、クライアント要求がタイムアウトする可能性があります。

+

NOTE: オブジェクトを圧縮する必要があり、クライアント アプリケーションで範囲読み取りを使用する必要がある場合は、アプリケーションの読み取りタイムアウトを増やします。



.手順
. *構成* > *システム* > *ストレージ設定* > *オブジェクト圧縮*を選択します。
. *保存されたオブジェクトを圧縮する*チェックボックスを選択します。
. *保存*を選択します。

