---
permalink: admin/creating-enterprise-application-azure.html 
sidebar: sidebar 
keywords: enterprise application, azure ad, single sign on, sso 
summary: Azure AD を使用して、システム内の各管理ノードに対してエンタープライズ アプリケーションを作成します。 
---
= Azure AD でエンタープライズ アプリケーションを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Azure AD を使用して、システム内の各管理ノードに対してエンタープライズ アプリケーションを作成します。

.開始する前に
* StorageGRIDのシングル サインオンの構成を開始し、SSO タイプとして *Azure* を選択しました。
* グリッド マネージャーのシングル サインオン ページで *サンドボックス モード* が選択されています。見るlink:../admin/using-sandbox-mode.html["サンドボックスモードを使用する"] 。
* システム内の各管理ノードには *エンタープライズ アプリケーション名* があります。これらの値は、 StorageGRIDシングル サインオン ページの管理ノードの詳細テーブルからコピーできます。
+

NOTE: StorageGRIDシステム内の各管理ノードに対してエンタープライズ アプリケーションを作成する必要があります。各管理ノードにエンタープライズ アプリケーションを用意することで、ユーザーはどの管理ノードにも安全にサインインおよびサインアウトできるようになります。

* Azure Active Directory でエンタープライズ アプリケーションを作成した経験があること。
* アクティブなサブスクリプションを持つ Azure アカウントがあります。
* Azure アカウントで、グローバル管理者、クラウド アプリケーション管理者、アプリケーション管理者、またはサービス プリンシパルの所有者のいずれかのロールを持っていること。




== Azure AD にアクセスする

.手順
. ログイン https://portal.azure.com["Azureポータル"^]。
. 移動先 https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["Azure アクティブ ディレクトリ"^]。
. 選択 https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["エンタープライズアプリケーション"^]。




== エンタープライズアプリケーションを作成し、 StorageGRID SSO構成を保存する

StorageGRIDに Azure の SSO 構成を保存するには、Azure を使用して各管理ノードのエンタープライズ アプリケーションを作成する必要があります。  Azure からフェデレーション メタデータ URL をコピーし、 StorageGRIDシングル サインオン ページの対応する *フェデレーション メタデータ URL* フィールドに貼り付けます。

.手順
. 各管理ノードに対して次の手順を繰り返します。
+
.. Azure エンタープライズ アプリケーション ペインで、*新しいアプリケーション* を選択します。
.. *独自のアプリケーションを作成する*を選択します。
.. 名前には、 StorageGRIDシングル サインオン ページの管理ノードの詳細テーブルからコピーした *エンタープライズ アプリケーション名* を入力します。
.. *ギャラリーに見つからないその他のアプリケーションを統合する (ギャラリー以外)* ラジオ ボタンを選択したままにします。
.. *作成*を選択します。
.. *2 の *開始* リンクを選択します。  *シングル サインオンの設定* ボックスをクリックするか、左余白の *シングル サインオン* リンクを選択します。
.. *SAML* ボックスを選択します。
.. *ステップ 3 SAML 署名証明書* の下にある *アプリ フェデレーション メタデータ URL* をコピーします。
.. StorageGRIDシングル サインオン ページに移動し、使用した *エンタープライズ アプリケーション名* に対応する *フェデレーション メタデータ URL* フィールドに URL を貼り付けます。


. 各管理ノードのフェデレーション メタデータ URL を貼り付け、SSO 構成に必要なその他の変更をすべて行った後、 StorageGRIDシングル サインオン ページで [*保​​存*] を選択します。




== すべての管理ノードのSAMLメタデータをダウンロードする

SSO 構成を保存した後、 StorageGRIDシステム内の各管理ノードの SAML メタデータ ファイルをダウンロードできます。

.手順
. 各管理ノードに対してこれらの手順を繰り返します。
+
.. 管理ノードからStorageGRIDにSign in。
.. *構成* > *アクセス制御* > *シングル サインオン* を選択します。
.. ボタンを選択して、その管理ノードの SAML メタデータをダウンロードします。
.. ファイルを保存します。このファイルは Azure AD にアップロードされます。






== 各エンタープライズアプリケーションにSAMLメタデータをアップロードする

各StorageGRID管理ノードの SAML メタデータ ファイルをダウンロードした後、Azure AD で次の手順を実行します。

.手順
. Azure ポータルに戻ります。
. 各エンタープライズ アプリケーションに対して次の手順を繰り返します。
+

NOTE: 以前にリストに追加したアプリケーションを表示するには、エンタープライズ アプリケーション ページを更新する必要がある場合があります。

+
.. エンタープライズ アプリケーションのプロパティ ページに移動します。
.. *割り当てが必要*を*いいえ*に設定します（割り当てを個別に構成する場合を除く）。
.. シングル サインオン ページに移動します。
.. SAML 構成を完了します。
.. *メタデータ ファイルのアップロード* ボタンを選択し、対応する管理ノード用にダウンロードした SAML メタデータ ファイルを選択します。
.. ファイルが読み込まれたら、[*保存*] を選択し、[*X*] を選択してペインを閉じます。  SAML を使用したシングル サインオンの設定ページに戻ります。


. 以下の手順に従ってくださいlink:../admin/using-sandbox-mode.html["サンドボックスモードを使用する"]各アプリケーションをテストします。

