---
permalink: admin/creating-traffic-classification-policies.html 
sidebar: sidebar 
keywords: traffic classification, network traffic, traffic limits, policy 
summary: バケット、テナント、IP サブネット、またはロード バランサー エンドポイントごとにネットワーク トラフィックを監視し、必要に応じて制限する場合は、トラフィック分類ポリシーを作成します。オプションで、帯域幅、同時リクエスト数、またはリクエストレートに基づいてポリシーの制限を設定できます。 
---
= トラフィック分類ポリシーを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監視する場合、トラフィック分類ポリシーを作成し、必要に応じてバケット、バケット正規表現、CIDR、ロード バランサ エンドポイント、またはテナントごとにネットワーク トラフィックを制限できます。オプションで、帯域幅、同時リクエスト数、またはリクエストレートに基づいてポリシーの制限を設定できます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:admin-group-permissions.html["ルートアクセス権限"]。
* 一致させるロード バランサー エンドポイントを作成しました。
* 一致させるテナントを作成しました。


.手順
. *構成* > *ネットワーク* > *トラフィック分類*を選択します。
. *作成*を選択します。
. ポリシーの名前と説明（オプション）を入力し、「続行」を選択します。
+
たとえば、このトラフィック分類ポリシーが何に適用され、何が制限されるかを説明します。

. *ルールの追加*を選択し、次の詳細を指定して、ポリシーに一致するルールを 1 つ以上作成します。作成するポリシーには、少なくとも 1 つの一致するルールが必要です。*続行*を選択します。
+
[cols="1a,3a"]
|===
| フィールド | 説明 


 a| 
タイプ
 a| 
一致ルールが適用されるトラフィックの種類を選択します。トラフィック タイプは、バケット、バケット正規表現、CIDR、ロード バランサ エンドポイント、テナントです。



 a| 
一致値
 a| 
選択したタイプに一致する値を入力します。

** バケット: 1 つ以上のバケット名を入力します。
** バケット正規表現: バケット名のセットを一致させるために使用される 1 つ以上の正規表現を入力します。
+
正規表現はアンカーされていません。バケット名の先頭に一致させるには ^ アンカーを使用し、名前の末尾に一致させるには $ アンカーを使用します。正規表現マッチングは、PCRE (Perl 互換正規表現) 構文のサブセットをサポートします。

** CIDR: 目的のサブネットに一致する 1 つ以上の IPv4 サブネットを CIDR 表記で入力します。
** ロード バランサー エンドポイント: エンドポイント名を選択します。これらは、link:../admin/configuring-load-balancer-endpoints.html["ロードバランサのエンドポイントを構成する"] 。
** テナント: テナントのマッチングにはアクセス キー ID が使用されます。リクエストにアクセス キー ID が含まれていない場合 (匿名アクセスなど)、アクセスされたバケットの所有権を使用してテナントが決定されます。




 a| 
逆マッチ
 a| 
定義したタイプと一致値に一致するトラフィックを除くすべてのネットワーク トラフィックを一致させる場合は、[逆一致] チェックボックスをオンにします。それ以外の場合は、チェックボックスをオフのままにします。

たとえば、このポリシーを 1 つを除くすべてのロード バランサー エンドポイントに適用する場合は、除外するロード バランサー エンドポイントを指定し、*逆一致* を選択します。

複数のマッチャーを含み、そのうち少なくとも 1 つが逆マッチャーであるポリシーの場合は、すべてのリクエストに一致するポリシーを作成しないように注意してください。

|===
. 必要に応じて、「*制限を追加*」を選択し、次の詳細を選択して、ルールに一致するネットワーク トラフィックを制御するための 1 つ以上の制限を追加します。
+

NOTE: StorageGRID は、制限を追加しない場合でもメトリックを収集するため、トラフィックの傾向を把握できます。

+
[cols="1a,3a"]
|===
| フィールド | 説明 


 a| 
タイプ
 a| 
ルールに一致するネットワーク トラフィックに適用する制限の種類。たとえば、帯域幅や要求レートを制限できます。

*注*: 総帯域幅を制限したり、リクエストごとの帯域幅を制限したりするポリシーを作成できます。ただし、 StorageGRID両方のタイプの帯域幅を同時に制限することはできません。集約帯域幅が使用されている場合、リクエストごとの帯域幅は使用できません。逆に、リクエストごとの帯域幅が使用されている場合、集約帯域幅は利用できません。総帯域幅を制限すると、制限のないトラフィックのパフォーマンスも多少低下する可能性があります。

帯域幅制限の場合、 StorageGRID は設定された制限の種類に最も一致するポリシーを適用します。たとえば、一方向のトラフィックのみを制限するポリシーがある場合、帯域幅制限のある追加のポリシーに一致するトラフィックがあっても、反対方向のトラフィックは無制限になります。  StorageGRID は、次の順序で帯域幅制限の「最適な」一致を実装します。

** 正確な IP アドレス (/32 マスク)
** 正確なバケット名
** バケット正規表現
** テナント
** エンドポイント
** CIDR の完全一致ではない (/32 ではない)
** 逆マッチ




 a| 
適用対象
 a| 
この制限がクライアントの読み取り要求 (GET または HEAD) に適用されるか、書き込み要求 (PUT、POST、または DELETE) に適用されるかを示します。



 a| 
Value
 a| 
選択したユニットに基づいて、ネットワーク トラフィックが制限される値。たとえば、このルールに一致するネットワーク トラフィックが 10 MiB/s を超えないようにするには、10 と入力して MiB/s を選択します。

*注*: 単位の設定に応じて、使用可能な単位はバイナリ (例: GiB) または 10 進数 (例: GB) のいずれかになります。単位設定を変更するには、グリッド マネージャーの右上にあるユーザー ドロップダウンを選択し、*ユーザー設定* を選択します。



 a| 
単位
 a| 
入力した値を表す単位。

|===
+
たとえば、SLA 層に 40 GB/秒の帯域幅制限を作成する場合は、40 GB/秒の GET/HEAD と 40 GB/秒の PUT/POST/DELETE の 2 つの集約帯域幅制限を作成します。

. *続行*を選択します。
. トラフィック分類ポリシーを読んで確認します。 *前へ*ボタンを使用して戻って、必要に応じて変更を加えます。ポリシーに満足したら、[*保存して続行*] を選択します。
+
S3 クライアント トラフィックは、トラフィック分類ポリシーに従って処理されるようになりました。



.終了後の操作
link:viewing-network-traffic-metrics.html["ネットワークトラフィックのメトリックを表示する"]ポリシーが期待どおりのトラフィック制限を適用していることを確認します。
