---
permalink: admin/deactivate-features-from-api.html 
sidebar: sidebar 
keywords: deactivate features from api 
summary: Grid Management API を使用すると、 StorageGRIDシステムの特定の機能を完全に非アクティブ化できます。機能が非アクティブ化されると、その機能に関連するタスクを実行する権限を誰にも割り当てることができなくなります。 
---
= APIを使用して機能を無効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grid Management API を使用すると、 StorageGRIDシステムの特定の機能を完全に非アクティブ化できます。機能が非アクティブ化されると、その機能に関連するタスクを実行する権限を誰にも割り当てることができなくなります。

.タスク概要
非アクティブ化された機能システムを使用すると、 StorageGRIDシステム内の特定の機能へのアクセスを禁止できます。機能を非アクティブ化することは、ルート ユーザーまたは *ルート アクセス* 権限を持つ管理者グループに属するユーザーがその機能を使用できないようにする唯一の方法です。

この機能がどのように役立つかを理解するには、次のシナリオを検討してください。

_A 社は、テナント アカウントを作成してStorageGRIDシステムのストレージ容量をリースするサービス プロバイダーです。賃借人の物件のセキュリティを保護するために、A 社は、アカウントが展開された後は自社の従業員がテナント アカウントにアクセスできないようにしたいと考えています。

_A 社は、グリッド管理 API の非アクティブ化機能システムを使用してこの目標を達成できます。  A 社は、グリッド マネージャー (UI と API の両方) の *テナント ルート パスワードの変更* 機能を完全に無効にすることで、管理者ユーザー (ルート ユーザーおよび *ルート アクセス* 権限を持つグループに属するユーザーを含む) が、テナント アカウントのルート ユーザーのパスワードを変更できないようにします。

.手順
. グリッド管理 API の Swagger ドキュメントにアクセスします。見るlink:using-grid-management-api.html["グリッド管理APIを使用する"] 。
. 機能の非アクティブ化エンドポイントを見つけます。
. テナント ルート パスワードの変更などの機能を無効にするには、次のような本文を API に送信します。
+
`{ "grid": {"changeTenantRootPassword": true} }`

+
リクエストが完了すると、テナント ルート パスワードの変更機能は無効になります。  *テナント ルート パスワードの変更* 管理権限はユーザー インターフェースに表示されなくなり、テナントのルート パスワードを変更しようとするすべての API 要求は「403 禁止」で失敗します。





== 無効化された機能を再有効化

デフォルトでは、Grid Management API を使用して、非アクティブ化された機能を再アクティブ化できます。ただし、非アクティブ化された機能が再度アクティブ化されないようにしたい場合は、*activateFeatures* 機能自体を非アクティブ化することができます。


CAUTION: *activateFeatures* 機能は再アクティブ化できません。この機能を非アクティブ化することにした場合、非アクティブ化された他の機能を再アクティブ化することができなくなることに注意してください。失われた機能を復元するには、テクニカル サポートに連絡する必要があります。

.手順
. グリッド管理 API の Swagger ドキュメントにアクセスします。
. 機能の非アクティブ化エンドポイントを見つけます。
. すべての機能を再アクティブ化するには、次のように本文を API に送信します。
+
`{ "grid": null }`

+
この要求が完了すると、テナント ルート パスワードの変更機能を含むすべての機能が再アクティブ化されます。  *テナント ルート パスワードの変更* 管理権限がユーザー インターフェイスに表示されるようになり、ユーザーが *ルート アクセス* または *テナント ルート パスワードの変更* 管理権限を持っていると仮定すると、テナントのルート パスワードを変更しようとするすべての API 要求が成功します。




TIP: 前の例では、非アクティブ化されたすべての機能が再アクティブ化されます。非アクティブ化されていて非アクティブのままにしておく必要がある他の機能が非アクティブ化されている場合は、PUT リクエストでそれらを明示的に指定する必要があります。たとえば、テナント ルート パスワードの変更機能を再度アクティブ化し、storageAdmin 管理権限を引き続き非アクティブ化するには、次の PUT リクエストを送信します。+
`{ "grid": {"storageAdmin": true} }`
