---
permalink: admin/grid-federation-compare-cgr-to-cloudmirror.html 
sidebar: sidebar 
keywords: cross-grid replication, cloudmirror replication 
summary: グリッド フェデレーションの使用を開始するときは、クロス グリッド レプリケーションとStorageGRID CloudMirror レプリケーション サービスの類似点と相違点を確認してください。 
---
= クロスグリッドレプリケーションとCloudMirrorレプリケーションを比較する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドフェデレーションの使用を開始する際には、以下の類似点と相違点を確認してください。link:grid-federation-what-is-cross-grid-replication.html["クロスグリッドレプリケーション"]そしてlink:../tenant/understanding-cloudmirror-replication-service.html["StorageGRID CloudMirror レプリケーション サービス"]。

[cols="1a,3a,3a"]
|===
|  | クロスグリッドレプリケーション | CloudMirrorレプリケーションサービス 


 a| 
主な目的は何ですか?
 a| 
1 つのStorageGRIDシステムが災害復旧システムとして機能します。バケット内のオブジェクトは、グリッド間で一方向または双方向に複製できます。
 a| 
テナントがStorageGRID内のバケット (ソース) から外部の S3 バケット (宛先) にオブジェクトを自動的に複製できるようにします。

CloudMirror レプリケーションは、独立した S3 インフラストラクチャ内にオブジェクトの独立したコピーを作成します。この独立したコピーはバックアップとしては使用されませんが、多くの場合、クラウドでさらに処理されます。



 a| 
どのように設定されていますか?
 a| 
. 2 つのグリッド間のグリッド フェデレーション接続を構成します。
. 新しいテナント アカウントを追加します。これは他のグリッドに自動的に複製されます。
. 新しいテナント グループとユーザーを追加します。これらも複製されます。
. 各グリッドに対応するバケットを作成し、一方向または双方向でグリッド間のレプリケーションを有効にします。

 a| 
. テナント ユーザーは、テナント マネージャーまたは S3 API を使用して CloudMirror エンドポイント (IP アドレス、資格情報など) を定義することにより、CloudMirror レプリケーションを構成します。
. そのテナント アカウントが所有するバケットは、CloudMirror エンドポイントを指すように構成できます。




 a| 
設定の責任者は誰ですか?
 a| 
* グリッド管理者は接続とテナントを構成します。
* テナント ユーザーは、グループ、ユーザー、キー、バケットを構成します。

 a| 
通常は、テナント ユーザーです。



 a| 
目的地はどこですか？
 a| 
グリッド フェデレーション接続内の他のStorageGRIDシステム上の対応する同一の S3 バケット。
 a| 
* 互換性のある任意の S3 インフラストラクチャ (Amazon S3 を含む)。
* Google Cloud Platform（GCP）




 a| 
オブジェクトのバージョン管理は必須ですか?
 a| 
はい、ソースバケットと宛先バケットの両方でオブジェクトのバージョン管理が有効になっている必要があります。
 a| 
いいえ、CloudMirror レプリケーションでは、ソースと宛先の両方で、バージョン管理されていないバケットとバージョン管理されたバケットの任意の組み合わせがサポートされます。



 a| 
オブジェクトが目的地に移動される原因は何ですか?
 a| 
オブジェクトは、クロスグリッド レプリケーションが有効になっているバケットに追加されると、自動的にレプリケートされます。
 a| 
オブジェクトは、CloudMirror エンドポイントで設定されたバケットに追加されると、自動的に複製されます。バケットが CloudMirror エンドポイントで構成される前にソース バケットに存在していたオブジェクトは、変更されない限り複製されません。



 a| 
オブジェクトはどのように複製されますか?
 a| 
クロスグリッド レプリケーションではバージョン管理されたオブジェクトが作成され、バージョン ID がソース バケットから宛先バケットに複製されます。これにより、両方のグリッド間でバージョンの順序を維持できます。
 a| 
CloudMirror レプリケーションではバージョン管理が有効なバケットは必要ないため、CloudMirror はサイト内のキーの順序のみを維持できます。別のサイトにあるオブジェクトへのリクエストの順序が維持されるという保証はありません。



 a| 
オブジェクトを複製できない場合はどうなりますか?
 a| 
オブジェクトは、メタデータ ストレージの制限に従って、レプリケーションのキューに入れられます。
 a| 
オブジェクトは、プラットフォームサービスの制限に従って、レプリケーションのキューに入れられます（link:manage-platform-services-for-tenants.html["プラットフォームサービスの利用に関する推奨事項"] ）。



 a| 
オブジェクトのシステム メタデータは複製されていますか?
 a| 
はい、オブジェクトが他のグリッドに複製されると、そのシステム メタデータも複製されます。メタデータは両方のグリッドで同一になります。
 a| 
いいえ、オブジェクトが外部バケットに複製されると、そのシステム メタデータが更新されます。メタデータは、取り込み時間と独立した S3 インフラストラクチャの動作に応じて、場所によって異なります。



 a| 
オブジェクトはどのように取得されますか?
 a| 
アプリケーションは、どちらかのグリッドのバケットにリクエストを送信することで、オブジェクトを取得または読み取ることができます。
 a| 
アプリケーションは、 StorageGRIDまたは S3 宛先にリクエストを送信することで、オブジェクトを取得または読み取ることができます。たとえば、CloudMirror レプリケーションを使用してオブジェクトをパートナー組織にミラーリングするとします。パートナーは独自のアプリケーションを使用して、S3 の送信先からオブジェクトを直接読み取ったり更新したりできます。  StorageGRIDの使用は必須ではありません。



 a| 
オブジェクトが削除されるとどうなりますか?
 a| 
* バージョン ID を含む削除要求は、宛先グリッドに複製されることはありません。
* バージョン ID が含まれていない削除リクエストは、ソース バケットに削除マーカーを追加します。これは、オプションで宛先グリッドに複製できます。
* クロスグリッド レプリケーションが一方向のみに設定されている場合、ソースに影響を与えずに宛先バケット内のオブジェクトを削除できます。

 a| 
結果は、ソースバケットと宛先バケットのバージョン管理状態によって異なります (同じである必要はありません)。

* 両方のバケットがバージョン管理されている場合、削除リクエストによって両方の場所に削除マーカーが追加されます。
* ソース バケットのみがバージョン管理されている場合、削除リクエストによってソースに削除マーカーが追加されますが、宛先には追加されません。
* どちらのバケットもバージョン管理されていない場合、削除リクエストによってソースからはオブジェクトが削除されますが、宛先からは削除されません。


同様に、ソースに影響を与えずに宛先バケット内のオブジェクトを削除できます。

|===