---
permalink: admin/guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords: admin network, client network, grid network, access interface, trunk interface 
summary: StorageGRID はグリッド ノードごとに最大 3 つのネットワーク インターフェイスをサポートしているため、セキュリティとアクセスの要件に合わせて各グリッド ノードのネットワークを構成できます。 
---
= StorageGRIDネットワークのガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grid Manager を使用して、 StorageGRIDネットワークと接続を構成および管理できます。

見るlink:configuring-client-connections.html["S3クライアント接続を構成する"]S3 クライアントを接続する方法を学習します。



== デフォルトのStorageGRIDネットワーク

デフォルトでは、 StorageGRID はグリッド ノードごとに 3 つのネットワーク インターフェイスをサポートしているため、セキュリティとアクセスの要件に合わせて各グリッド ノードのネットワークを構成できます。

ネットワークトポロジの詳細については、以下を参照してください。link:../network/index.html["ネットワークガイドライン"] 。



=== グリッド ネットワーク

必須。グリッド ネットワークは、すべての内部StorageGRIDトラフィックに使用されます。グリッド内のすべてのノード間、すべてのサイトおよびサブネット間の接続を提供します。



=== 管理者ネットワーク

オプション。管理ネットワークは通常、システムの管理とメンテナンスに使用されます。クライアント プロトコル アクセスにも使用できます。管理ネットワークは通常はプライベート ネットワークであり、サイト間でルーティング可能である必要はありません。



=== クライアント ネットワーク

オプション。クライアント ネットワークは、通常、S3 クライアント アプリケーションへのアクセスを提供するために使用されるオープン ネットワークであるため、グリッド ネットワークを分離して保護できます。クライアント ネットワークは、ローカル ゲートウェイ経由で到達可能な任意のサブネットと通信できます。



== ガイドライン

* 各StorageGRIDノードには、割り当てられているネットワークごとに専用のネットワーク インターフェイス、IP アドレス、サブネット マスク、ゲートウェイが必要です。
* グリッド ノードは、ネットワーク上で複数のインターフェイスを持つことはできません。
* ネットワークごと、グリッド ノードごとに 1 つのゲートウェイがサポートされており、ノードと同じサブネット上にある必要があります。必要に応じて、ゲートウェイでより複雑なルーティングを実装できます。
* 各ノードでは、各ネットワークが特定のネットワーク インターフェイスにマップされます。
+
[cols="1a,1a"]
|===
| ネットワーク | インターフェイス名 


 a| 
Grid
 a| 
eth0



 a| 
管理者（オプション）
 a| 
eth1



 a| 
クライアント（オプション）
 a| 
eth2

|===
* ノードがStorageGRIDアプライアンスに接続されている場合、各ネットワークに特定のポートが使用されます。詳細については、アプライアンスのインストール手順を参照してください。
* デフォルト ルートはノードごとに自動的に生成されます。  eth2 が有効な場合、0.0.0.0/0 は eth2 上のクライアント ネットワークを使用します。  eth2 が有効になっていない場合、0.0.0.0/0 は eth0 上のグリッド ネットワークを使用します。
* クライアントネットワークは、グリッドノードがグリッドに参加するまで動作しません。
* グリッド ノードの展開中に管理ネットワークを構成して、グリッドが完全にインストールされる前にインストール ユーザー インターフェイスにアクセスできるようにすることができます。




== オプションインターフェース

オプションで、ノードに追加のインターフェースを追加できます。たとえば、管理ノードまたはゲートウェイノードにトランクインターフェースを追加して、link:../admin/configure-vlan-interfaces.html["VLANインターフェイス"]異なるアプリケーションまたはテナントに属するトラフィックを分離します。または、アクセスインターフェースを追加して、link:../admin/configure-high-availability-group.html["高可用性（HA）グループ"] 。

トランクまたはアクセス インターフェイスを追加するには、次を参照してください。

* *VMware (ノードのインストール後)*:link:../maintain/vmware-adding-trunk-or-access-interfaces-to-node.html["VMware: ノードにトランクまたはアクセス インターフェースを追加する"]
+
** *Red Hat Enterprise Linux (ノードをインストールする前)*:link:../rhel/creating-node-configuration-files.html["ノード構成ファイルを作成する"]
** *Ubuntu または Debian (ノードをインストールする前)*:link:../ubuntu/creating-node-configuration-files.html["ノード構成ファイルを作成する"]
** *RHEL、Ubuntu、または Debian (ノードをインストールした後)*:link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux: ノードにトランクまたはアクセスインターフェースを追加する"]



