---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords: ha groups, high availability group 
summary: '高可用性 (HA) グループを使用すると、オブジェクト データおよび管理用途のためにStorageGRIDへの高可用性接続を提供できます。' 
---
= HA グループはどのように使用されますか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
高可用性 (HA) グループを使用すると、オブジェクト データおよび管理用途のためにStorageGRIDへの高可用性接続を提供できます。

* HA グループは、グリッド マネージャまたはテナント マネージャへの高可用性の管理接続を提供できます。
* HA グループは、S3 クライアントに高可用性のデータ接続を提供できます。
* インターフェースが 1 つだけ含まれる HA グループでは、多数の VIP アドレスを提供したり、IPv6 アドレスを明示的に設定したりできます。


HA グループは、グループに含まれるすべてのノードが同じサービスを提供する場合にのみ、高可用性を提供できます。  HA グループを作成するときは、必要なサービスを提供するノードの種類からインターフェイスを追加します。

* *管理ノード*: ロード バランサ サービスを含め、グリッド マネージャまたはテナント マネージャへのアクセスを有効にします。
* *ゲートウェイ ノード*: ロード バランサ サービスを含めます。


[cols="1a,2a"]
|===
| HAグループの目的 | このタイプのノードをHAグループに追加する 


 a| 
グリッドマネージャーへのアクセス
 a| 
* プライマリ管理ノード（*プライマリ*）
* 非プライマリ管理ノード


*注:* プライマリ管理ノードはプライマリ インターフェイスである必要があります。一部のメンテナンス手順は、プライマリ管理ノードからのみ実行できます。



 a| 
テナントマネージャーのみへのアクセス
 a| 
* プライマリまたは非プライマリ管理ノード




 a| 
S3 クライアントアクセス - ロードバランサーサービス
 a| 
* 管理ノード
* ゲートウェイノード




 a| 
S3クライアントアクセスlink:../admin/manage-s3-select-for-tenant-accounts.html["S3セレクト"]
 a| 
* サービスアプライアンス
* VMwareベースのソフトウェアノード


*注意*: S3 Select を使用する場合は HA グループが推奨されますが、必須ではありません。

|===


== グリッド マネージャーまたはテナント マネージャーで HA グループを使用する際の制限

Grid Manager または Tenant Manager サービスに障害が発生した場合、HA グループのフェイルオーバーはトリガーされません。

フェイルオーバーが発生したときに Grid Manager または Tenant Manager にサインインしている場合は、サインアウトされるため、タスクを再開するには再度サインインする必要があります。

プライマリ管理ノードが利用できない場合、一部のメンテナンス手順は実行できません。フェイルオーバー中は、Grid Manager を使用してStorageGRIDシステムを監視できます。
