---
permalink: admin/managing-traffic-classification-policies.html 
sidebar: sidebar 
keywords: QoS, quality of service, traffic classification, best practices, limit traffic, monitor traffic 
summary: 'トラフィック分類ポリシーを使用すると、さまざまな種類のネットワーク トラフィックを識別および監視できます。これらのポリシーは、トラフィックの制限と監視に役立ち、サービス品質 (QoS) の向上に役立ちます。' 
---
= トラフィック分類ポリシーとは何ですか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
トラフィック分類ポリシーを使用すると、さまざまな種類のネットワーク トラフィックを識別および監視できます。これらのポリシーは、トラフィックの制限と監視に役立ち、サービス品質 (QoS) の向上に役立ちます。

トラフィック分類ポリシーは、ゲートウェイ ノードと管理ノードのStorageGRIDロード バランサ サービスのエンドポイントに適用されます。トラフィック分類ポリシーを作成するには、ロード バランサー エンドポイントをあらかじめ作成しておく必要があります。



== マッチングルール

各トラフィック分類ポリシーには、次の 1 つ以上のエンティティに関連するネットワーク トラフィックを識別するための 1 つ以上の一致ルールが含まれています。

* バケット
* サブネット
* テナント
* ロード バランサ エンドポイント


StorageGRID は、ルールの目的に従って、ポリシー内の任意のルールに一致するトラフィックを監視します。ポリシーのルールに一致するトラフィックはすべて、そのポリシーによって処理されます。逆に、指定したエンティティを除くすべてのトラフィックに一致するルールを設定することもできます。



== 交通制限

必要に応じて、次の制限タイプをポリシーに追加できます。

* 総帯域幅
* リクエストごとの帯域幅
* 同時リクエスト
* リクエストレート


制限値はロードバランサーごとに適用されます。トラフィックが複数のロード バランサーに同時に分散される場合、合計最大レートは指定したレート制限の倍数になります。


NOTE: 総帯域幅を制限したり、リクエストごとの帯域幅を制限したりするポリシーを作成できます。ただし、 StorageGRID両方のタイプの帯域幅を同時に制限することはできません。総帯域幅を制限すると、制限のないトラフィックのパフォーマンスも多少低下する可能性があります。

総計またはリクエストごとの帯域幅制限の場合、リクエストは設定したレートでストリーミングされます。 StorageGRID は1 つの速度のみを適用できるため、マッチャー タイプによる最も具体的なポリシー マッチが適用されます。リクエストによって消費された帯域幅は、集約帯域幅制限ポリシーを含む、より具体的でない他の一致ポリシーに対してカウントされません。その他のすべての制限タイプでは、クライアント要求は 250 ミリ秒遅延され、一致するポリシー制限を超える要求に対して 503 Slow Down 応答が返されます。

グリッド マネージャーでは、トラフィック チャートを表示し、ポリシーが期待どおりのトラフィック制限を適用していることを確認できます。



== SLA を使用したトラフィック分類ポリシーの使用

トラフィック分類ポリシーを容量制限およびデータ保護と組み合わせて使用することで、容量、データ保護、およびパフォーマンスの詳細を提供するサービス レベル アグリーメント (SLA) を適用できます。

次の例は、SLA の 3 つの層を示しています。各 SLA 層のパフォーマンス目標を達成するためにトラフィック分類ポリシーを作成できます。

[cols="1a,1a,1a,1a,1a"]
|===
| サービスレベル層 | 容量 | データ保護 | 許容される最大パフォーマンス | 料金 


 a| 
Gold
 a| 
1 PBのストレージが許可されます
 a| 
3コピーILMルール
 a| 
25Kリクエスト/秒

5 GB/秒（40 Gbps）の帯域幅
 a| 
月額$$$



 a| 
Silver
 a| 
250 TBのストレージが許可されます
 a| 
2コピーILMルール
 a| 
10Kリクエスト/秒

1.25 GB/秒（10 Gbps）の帯域幅
 a| 
月額$$



 a| 
Bronze
 a| 
100 TBのストレージが許可されます
 a| 
2コピーILMルール
 a| 
5K リクエスト/秒

1 GB/秒（8 Gbps）の帯域幅
 a| 
月額$

|===