---
permalink: admin/manage-platform-services-for-tenants.html 
sidebar: sidebar 
keywords: platform service, cloudmirror replication, event notification, search integration service 
summary: プラットフォーム サービスには、CloudMirror レプリケーション、イベント通知、検索統合サービスが含まれます。 
---
= プラットフォームサービスとは何ですか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プラットフォーム サービスには、CloudMirror レプリケーション、イベント通知、検索統合サービスが含まれます。

S3 テナント アカウントに対してプラットフォーム サービスを有効にする場合は、テナントがこれらのサービスを使用するために必要な外部リソースにアクセスできるようにグリッドを構成する必要があります。



== CloudMirrorレプリケーション

StorageGRID CloudMirror レプリケーション サービスは、 StorageGRIDバケットから指定された外部宛先に特定のオブジェクトをミラーリングするために使用されます。

たとえば、CloudMirror レプリケーションを使用して特定の顧客レコードを Amazon S3 にミラーリングし、AWS サービスを活用してデータの分析を実行することができます。


NOTE: CloudMirror レプリケーションには、クロスグリッド レプリケーション機能との重要な類似点と相違点がいくつかあります。詳細については、link:../admin/grid-federation-compare-cgr-to-cloudmirror.html["クロスグリッドレプリケーションとCloudMirrorレプリケーションを比較する"] 。


NOTE: ソースバケットで S3 オブジェクトロックが有効になっている場合、CloudMirror レプリケーションはサポートされません。



== 通知

バケットごとのイベント通知は、オブジェクトに対して実行された特定のアクションに関する通知を、指定された外部 Kafka クラスターまたは Amazon Simple Notification Service に送信するために使用されます。

たとえば、バケットに追加された各オブジェクト（重要なシステム イベントに関連付けられたログ ファイルを表すオブジェクト）に関するアラートを管理者に送信するように設定できます。


NOTE: S3 オブジェクト ロックが有効になっているバケットでイベント通知を設定できますが、オブジェクトの S3 オブジェクト ロック メタデータ (保持期限や法的保留ステータスを含む) は通知メッセージに含まれません。



== 検索統合サービス

検索統合サービスは、S3 オブジェクト メタデータを指定された Elasticsearch インデックスに送信するために使用され、そこでメタデータは外部サービスを使用して検索または分析できます。

たとえば、S3 オブジェクトのメタデータをリモート Elasticsearch サービスに送信するようにバケットを設定できます。その後、Elasticsearch を使用してバケット全体の検索を実行し、オブジェクト メタデータに存在するパターンの高度な分析を実行できます。


NOTE: S3 オブジェクト ロックが有効になっているバケットで Elasticsearch 統合を設定できますが、オブジェクトの S3 オブジェクト ロック メタデータ (保持期限や法的保留ステータスを含む) は通知メッセージに含まれません。

プラットフォーム サービスにより、テナントは外部ストレージ リソース、通知サービス、およびデータを使用した検索や分析サービスを使用できるようになります。プラットフォーム サービスのターゲットの場所は通常、 StorageGRID展開の外部にあるため、テナントにこれらのサービスの使用を許可するかどうかを決定する必要があります。その場合は、テナント アカウントを作成または編集するときに、プラットフォーム サービスの使用を有効にする必要があります。また、テナントが生成するプラットフォーム サービス メッセージが宛先に届くようにネットワークを構成する必要があります。



== プラットフォームサービスの利用に関する推奨事項

プラットフォーム サービスを使用する前に、次の推奨事項に注意してください。

* StorageGRIDシステム内の S3 バケットでバージョン管理と CloudMirror レプリケーションの両方が有効になっている場合は、宛先エンドポイントの S3 バケットのバージョン管理も有効にする必要があります。これにより、CloudMirror レプリケーションはエンドポイントで同様のオブジェクト バージョンを生成できるようになります。
* CloudMirror レプリケーション、通知、および検索統合を必要とする S3 リクエストでは、100 を超えるアクティブテナントを使用しないでください。アクティブなテナントが 100 を超えると、S3 クライアントのパフォーマンスが低下する可能性があります。
* 完了できないエンドポイントへのリクエストは、最大 500,000 件のリクエストまでキューに入れられます。この制限はアクティブなテナント間で均等に共有されます。新しく作成されたテナントが不当に罰せられないように、新しいテナントはこの 500,000 の制限を一時的に超えることが許可されます。


.関連情報
* link:../tenant/what-platform-services-are.html["プラットフォームサービスの管理"]
* link:configuring-storage-proxy-settings.html["ストレージプロキシ設定を構成する"]
* link:../monitor/index.html["StorageGRIDを監視する"]

