---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 'テナント アカウントを使用すると、Simple Storage Service (S3) REST API を使用して、 StorageGRIDシステムにオブジェクトを保存および取得できます。' 
---
= テナント アカウントとは何ですか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナント アカウントを使用すると、Simple Storage Service (S3) REST API を使用して、 StorageGRIDシステム内のオブジェクトを保存および取得できます。


TIP: このバージョンのドキュメント サイトから Swift の詳細は削除されました。見る https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11.8: テナントの管理"^]。

グリッド管理者は、S3 クライアントがオブジェクトの保存と取得に使用するテナント アカウントを作成および管理します。

各テナント アカウントには、フェデレーション グループまたはローカル グループ、ユーザー、S3 バケット、オブジェクトがあります。

テナント アカウントを使用すると、保存されたオブジェクトを異なるエンティティごとに分離できます。たとえば、次のいずれかのユースケースでは複数のテナント アカウントを使用できます。

* *エンタープライズの使用例:* エンタープライズ アプリケーションでStorageGRIDシステムを管理している場合、組織内のさまざまな部門ごとにグリッドのオブジェクト ストレージを分離する必要がある場合があります。この場合、マーケティング部門、カスタマー サポート部門、人事部門などのテナント アカウントを作成できます。
+

NOTE: S3 クライアント プロトコルを使用する場合は、S3 バケットとバケット ポリシーを使用して、企業内の部門間でオブジェクトを分離できます。テナント アカウントを使用する必要はありません。実装手順を参照link:../s3/bucket-and-group-access-policies.html["S3 バケットとバケットポリシー"]詳細についてはこちらをご覧ください。

* *サービス プロバイダーの使用例:* StorageGRIDシステムをサービス プロバイダーとして管理している場合は、グリッドのオブジェクト ストレージを、グリッド上でストレージをリースするさまざまなエンティティごとに分離できます。この場合、会社 A、会社 B、会社 C などのテナント アカウントを作成します。


詳細については、以下を参照してください。 link:../tenant/index.html["テナントアカウントを使用する"] 。



== テナント アカウントを作成するにはどうすればよいですか?

グリッド マネージャーを使用してテナント アカウントを作成します。テナント アカウントを作成するときは、次の情報を指定します。

* テナント名、クライアント タイプ (S3)、オプションのストレージ クォータなどの基本情報。
* テナント アカウントの権限 (テナント アカウントが S3 プラットフォーム サービスを使用できるかどうか、独自の ID ソースを設定できるかどうか、S3 Select を使用できるかどうか、グリッド フェデレーション接続を使用できるかどうかなど)。
* StorageGRIDシステムがローカル グループとユーザー、ID フェデレーション、またはシングル サインオン (SSO) を使用するかどうかに基づく、テナントの初期ルート アクセス。


さらに、S3 テナント アカウントが規制要件に準拠する必要がある場合は、 StorageGRIDシステムの S3 オブジェクト ロック設定を有効にできます。  S3 オブジェクト ロックを有効にすると、すべての S3 テナント アカウントが準拠バケットを作成および管理できるようになります。



== Tenant Manager は何に使用されますか?

テナント アカウントを作成すると、テナント ユーザーはテナント マネージャーにサインインして次のようなタスクを実行できます。

* アイデンティティ フェデレーションを設定する (アイデンティティ ソースがグリッドと共有されていない場合)
* グループとユーザーの管理
* アカウントのクローンとクロスグリッドレプリケーションにグリッドフェデレーションを使用する
* S3 アクセスキーを管理する
* S3バケットの作成と管理
* S3プラットフォームサービスを使用する
* S3 Selectを使用する
* ストレージ使用量を監視する



TIP: S3 テナント ユーザーは、Tenant Manager を使用して S3 アクセス キーとバケットを作成および管理できますが、オブジェクトの取り込みと管理には S3 クライアント アプリケーションを使用する必要があります。見るlink:../s3/index.html["S3 REST APIを使用する"]詳細については。
