---
permalink: admin/managing-full-storage-nodes.html 
sidebar: sidebar 
keywords: storage node is full 
summary: ストレージ ノードの容量が限界に達したら、新しいストレージを追加してStorageGRIDシステムを拡張する必要があります。利用可能なオプションは、ストレージ ボリュームの追加、ストレージ拡張シェルフの追加、ストレージ ノードの追加の 3 つです。 
---
= 完全なストレージノードを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ ノードの容量が限界に達したら、新しいストレージを追加してStorageGRIDシステムを拡張する必要があります。利用可能なオプションは、ストレージ ボリュームの追加、ストレージ拡張シェルフの追加、ストレージ ノードの追加の 3 つです。



== ストレージボリュームを追加する

各ストレージ ノードは、最大数のストレージ ボリュームをサポートします。定義される最大値はプラットフォームによって異なります。ストレージ ノードに含まれるストレージ ボリュームの数が最大数より少ない場合は、ボリュームを追加して容量を増やすことができます。説明書をご覧くださいlink:../expand/index.html["StorageGRIDシステムの拡張"]。



== ストレージ拡張棚を追加する

SG6060 や SG6160 などの一部のStorageGRIDアプライアンス ストレージ ノードは、追加のストレージ シェルフをサポートできます。拡張機能を備えたStorageGRIDアプライアンスがあり、まだ最大容量まで拡張されていない場合は、ストレージ シェルフを追加して容量を増やすことができます。説明書をご覧くださいlink:../expand/index.html["StorageGRIDシステムの拡張"]。



== ストレージノードの追加

ストレージノードを追加することでストレージ容量を増やすことができます。ストレージを追加するときは、現在アクティブな ILM ルールと容量要件を慎重に考慮する必要があります。説明書をご覧くださいlink:../expand/index.html["StorageGRIDシステムの拡張"]。
