---
permalink: admin/networking-and-ports-for-platform-services.html 
sidebar: sidebar 
keywords: platform services, ports for platform services, 443, 80 
summary: S3 テナントにプラットフォーム サービスの使用を許可する場合は、プラットフォーム サービス メッセージが宛先に配信されるようにグリッドのネットワークを構成する必要があります。 
---
= プラットフォームサービス用のネットワークとポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 テナントにプラットフォーム サービスの使用を許可する場合は、プラットフォーム サービス メッセージが宛先に配信されるようにグリッドのネットワークを構成する必要があります。

テナント アカウントを作成または更新するときに、S3 テナント アカウントのプラットフォーム サービスを有効にできます。プラットフォーム サービスが有効になっている場合、テナントは、S3 バケットからの CloudMirror レプリケーション、イベント通知、または検索統合メッセージの送信先として機能するエンドポイントを作成できます。これらのプラットフォーム サービス メッセージは、ADC サービスを実行するストレージ ノードから宛先エンドポイントに送信されます。

たとえば、テナントは次のタイプの宛先エンドポイントを構成する場合があります。

* ローカルにホストされたElasticsearchクラスター
* Amazon Simple Notification Service メッセージの受信をサポートするローカルアプリケーション
* ローカルにホストされた Kafka クラスター
* StorageGRIDの同じインスタンスまたは別のインスタンス上のローカルにホストされた S3 バケット
* Amazon Web Services 上のエンドポイントなどの外部エンドポイント。


プラットフォーム サービス メッセージが確実に配信されるようにするには、ADC ストレージ ノードを含むネットワークを構成する必要があります。プラットフォーム サービス メッセージを宛先エンドポイントに送信するには、次のポートを使用できることを確認する必要があります。

デフォルトでは、プラットフォーム サービス メッセージは次のポートで送信されます。

* *80*: httpで始まるエンドポイントURI（ほとんどのエンドポイント）
* *443*: httpsで始まるエンドポイントURI（ほとんどのエンドポイント）
* *9092*: http または https で始まるエンドポイント URI の場合 (Kafka エンドポイントのみ)


テナントは、エンドポイントを作成または編集するときに別のポートを指定できます。


NOTE: StorageGRIDデプロイメントを CloudMirror レプリケーションの宛先として使用すると、レプリケーション メッセージが 80 または 443 以外のポートで受信される可能性があります。宛先StorageGRIDデプロイメントによって S3 に使用されているポートがエンドポイントで指定されていることを確認します。

非透過プロキシサーバーを使用する場合は、link:configuring-storage-proxy-settings.html["ストレージプロキシ設定を構成する"]インターネット上のエンドポイントなどの外部エンドポイントにメッセージを送信できるようにします。

.関連情報
link:../tenant/index.html["テナントアカウントを使用する"]
