---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: 'オブジェクトを保存または取得するために、S3 クライアント アプリケーションは、すべての管理ノードとゲートウェイ ノードに含まれるロード バランサ サービス、またはすべてのストレージ ノードに含まれるローカル ディストリビューション ルータ (LDR) サービスに接続します。' 
---
= 概要: クライアント接続の IP アドレスとポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトを保存または取得するために、S3 クライアント アプリケーションは、すべての管理ノードとゲートウェイ ノードに含まれるロード バランサ サービス、またはすべてのストレージ ノードに含まれるローカル ディストリビューション ルータ (LDR) サービスに接続します。

クライアント アプリケーションは、グリッド ノードの IP アドレスとそのノード上のサービスのポート番号を使用してStorageGRIDに接続できます。オプションで、負荷分散ノードの高可用性 (HA) グループを作成して、仮想 IP (VIP) アドレスを使用する高可用性接続を提供することもできます。  IP アドレスまたは VIP アドレスではなく完全修飾ドメイン名 (FQDN) を使用してStorageGRIDに接続する場合は、DNS エントリを設定できます。

この表は、クライアントがStorageGRIDに接続できるさまざまな方法と、各接続タイプで使用される IP アドレスとポートをまとめたものです。ロードバランサエンドポイントと高可用性（HA）グループをすでに作成している場合は、<<IPアドレスを見つける場所>>グリッド マネージャーでこれらの値を見つけます。

[cols="1a,1a,1a,1a"]
|===
| 接続が行われる場所 | クライアントが接続するサービス | IPアドレス | ポート 


 a| 
HAグループ
 a| 
ロード バランサ
 a| 
HAグループの仮想IPアドレス
 a| 
ロードバランサのエンドポイントに割り当てられたポート



 a| 
管理ノード
 a| 
ロード バランサ
 a| 
管理ノードのIPアドレス
 a| 
ロードバランサのエンドポイントに割り当てられたポート



 a| 
ゲートウェイ ノード
 a| 
ロード バランサ
 a| 
ゲートウェイノードのIPアドレス
 a| 
ロードバランサのエンドポイントに割り当てられたポート



 a| 
ストレージ ノード
 a| 
LDR
 a| 
ストレージノードのIPアドレス
 a| 
デフォルトの S3 ポート:

* HTTPS: 18082
* HTTP: 18084


|===


== URLの例

クライアント アプリケーションをゲートウェイ ノードの HA グループのロード バランサ エンドポイントに接続するには、次に示すような構造の URL を使用します。

`https://_VIP-of-HA-group:LB-endpoint-port_`

たとえば、HA グループの仮想 IP アドレスが 192.0.2.5 で、ロード バランサ エンドポイントのポート番号が 10443 の場合、アプリケーションは次の URL を使用してStorageGRIDに接続できます。

`\https://192.0.2.5:10443`



== IPアドレスを見つける場所

. グリッドマネージャーにSign inには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
. グリッド ノードの IP アドレスを見つけるには:
+
.. 「NODES」を選択します。
.. 接続する管理ノード、ゲートウェイ ノード、またはストレージ ノードを選択します。
.. *概要*タブを選択します。
.. ノード情報セクションで、ノードの IP アドレスをメモします。
.. IPv6 アドレスとインターフェース マッピングを表示するには、[*詳細を表示*] を選択します。
+
クライアント アプリケーションからリスト内の任意の IP アドレスへの接続を確立できます。

+
*** *eth0:* グリッドネットワーク
*** *eth1:* 管理ネットワーク（オプション）
*** *eth2:* クライアントネットワーク（オプション）
+

NOTE: 管理ノードまたはゲートウェイ ノードを表示していて、それが高可用性グループ内のアクティブ ノードである場合、HA グループの仮想 IP アドレスが eth2 に表示されます。





. 高可用性グループの仮想 IP アドレスを見つけるには:
+
.. *構成* > *ネットワーク* > *高可用性グループ*を選択します。
.. 表で、HA グループの仮想 IP アドレスを書き留めます。


. ロード バランサ エンドポイントのポート番号を見つけるには:
+
.. *構成* > *ネットワーク* > *ロード バランサー エンドポイント* を選択します。
.. 使用するエンドポイントのポート番号をメモします。
+

NOTE: ポート番号が 80 または 443 の場合、これらのポートは管理ノードで予約されているため、エンドポイントはゲートウェイ ノードでのみ構成されます。他のすべてのポートは、ゲートウェイ ノードと管理ノードの両方で構成されます。

.. テーブルからエンドポイントの名前を選択します。
.. *クライアント タイプ* (S3) がエンドポイントを使用するクライアント アプリケーションと一致していることを確認します。



