---
permalink: admin/temporarily-disabling-and-reenabling-sso-for-admin-node.html 
sidebar: sidebar 
keywords: signing in when sso is down, single sign on failure 
summary: 'シングル サインオン (SSO) システムがダウンすると、Grid Manager にサインインできなくなる可能性があります。この場合、1 つの管理ノードに対して SSO を一時的に無効にし、再度有効にすることができます。  SSO を無効にしてから再度有効にするには、ノードのコマンド シェルにアクセスする必要があります。' 
---
= 1つの管理ノードのシングルサインオンを一時的に無効にし、再度有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シングル サインオン (SSO) システムがダウンした場合、Grid Manager にサインインできない可能性があります。この場合、1 つの管理ノードに対して SSO を一時的に無効にし、再度有効にすることができます。  SSO を無効にしてから再度有効にするには、ノードのコマンド シェルにアクセスする必要があります。

.開始する前に
* あなたが持っているlink:admin-group-permissions.html["特定のアクセス権限"]。
* あなたは `Passwords.txt`ファイル。
* ローカル ルート ユーザーのパスワードを知っています。


.タスク概要
1 つの管理ノードの SSO を無効にした後、ローカル ルート ユーザーとして Grid Manager にサインインできます。  StorageGRIDシステムを保護するには、サインアウトしたらすぐにノードのコマンド シェルを使用して管理ノードで SSO を再度有効にする必要があります。


TIP: 1 つの管理ノードの SSO を無効にしても、グリッド内の他の管理ノードの SSO 設定には影響しません。グリッド マネージャーのシングル サインオン ページの *SSO を有効にする* チェックボックスは選択されたままになり、更新しない限り既存の SSO 設定はすべて維持されます。

.手順
. 管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@Admin_Node_IP`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
+
ルートとしてログインすると、プロンプトは `$`に `#`。



. 次のコマンドを実行します。``disable-saml``
+
メッセージは、コマンドがこの管理ノードにのみ適用されることを示します。

. SSO を無効にすることを確認します。
+
ノード上でシングル サインオンが無効になっていることを示すメッセージが表示されます。

. Web ブラウザから、同じ管理ノード上のグリッド マネージャーにアクセスします。
+
SSO が無効になっているため、Grid Manager のサインイン ページが表示されます。

. ユーザー名 root とローカル root ユーザーのパスワードでSign in。
. SSO 構成を修正する必要があったために SSO を一時的に無効にした場合:
+
.. *構成* > *アクセス制御* > *シングル サインオン* を選択します。
.. 不正確または古い SSO 設定を変更します。
.. *保存*を選択します。
+
シングル サインオン ページで [*保存*] を選択すると、グリッド全体の SSO が自動的に再度有効になります。



. 他の理由でグリッド マネージャーにアクセスする必要があったため、SSO を一時的に無効にした場合:
+
.. 実行する必要があるタスクをすべて実行します。
.. *サインアウト*を選択し、グリッド マネージャーを閉じます。
.. 管理ノードで SSO を再度有効にします。次のいずれかの手順を実行できます。
+
*** 次のコマンドを実行します。 `enable-saml`
+
メッセージは、コマンドがこの管理ノードにのみ適用されることを示します。

+
SSO を有効にすることを確認します。

+
ノードでシングル サインオンが有効になっていることを示すメッセージが表示されます。

*** グリッド ノードを再起動します。 `reboot`




. Web ブラウザから、同じ管理ノードからグリッド マネージャーにアクセスします。
. StorageGRIDSign inページが表示され、Grid Manager にアクセスするには SSO 資格情報を入力する必要があることを確認します。

