---
permalink: admin/use-s3-setup-wizard.html 
sidebar: sidebar 
keywords: S3, S3 setup wizard 
summary: S3 セットアップ ウィザードを使用して、 StorageGRID をS3 アプリケーションのオブジェクト ストレージ システムとして設定できます。 
---
= S3 セットアップウィザードの使用: 考慮事項と要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 セットアップ ウィザードを使用して、 StorageGRID をS3 アプリケーションのオブジェクト ストレージ システムとして設定できます。



== S3 セットアップウィザードを使用する場合

S3 セットアップ ウィザードは、S3 アプリケーションで使用するためにStorageGRIDを構成する各手順をガイドします。ウィザードを完了する過程で、S3 アプリケーションに値を入力するために使用できるファイルをダウンロードします。ウィザードを使用すると、システムをより迅速に構成し、設定がStorageGRID のベスト プラクティスに準拠していることを確認できます。

もしあなたがlink:admin-group-permissions.html["ルートアクセス権限"]StorageGRID Grid Manager の使用を開始するときに S3 セットアップ ウィザードを完了することも、後でいつでもウィザードにアクセスして完了することもできます。要件に応じて、必要な項目の一部またはすべてを手動で設定し、ウィザードを使用して S3 アプリケーションに必要な値を組み立てることもできます。



== ウィザードを使用する前に

ウィザードを使用する前に、これらの前提条件が満たされていることを確認してください。

IPアドレスを取得し、VLANインターフェースを設定する:: 高可用性 (HA) グループを構成する場合は、S3 アプリケーションが接続するノードと、使用されるStorageGRIDネットワークがわかります。また、サブネット CIDR、ゲートウェイ IP アドレス、仮想 IP (VIP) アドレスに入力する値もわかっています。
+
--
仮想 LAN を使用して S3 アプリケーションからのトラフィックを分離する予定の場合は、VLAN インターフェイスはすでに構成されています。見るlink:../admin/configure-vlan-interfaces.html["VLANインターフェースを構成する"] 。

--
ID連携とSSOを構成する:: StorageGRIDシステムで ID フェデレーションまたはシングル サインオン (SSO) を使用する予定の場合は、これらの機能が有効になっています。また、S3 アプリケーションが使用するテナント アカウントのルート アクセス権を持つフェデレーション グループも把握しています。見るlink:../admin/using-identity-federation.html["アイデンティティフェデレーションを使用する"]そしてlink:../admin/configuring-sso.html["シングルサインオンを構成する"]。
ドメイン名の取得と設定:: StorageGRIDに使用する完全修飾ドメイン名 (FQDN) がわかっていること。ドメイン ネーム サーバー (DNS) エントリは、この FQDN を、ウィザードを使用して作成する HA グループの仮想 IP (VIP) アドレスにマッピングします。
+
--
S3仮想ホスト形式のリクエストを使用する予定の場合は、link:../admin/configuring-s3-api-endpoint-domain-names.html["設定されたS3エンドポイントドメイン名"] 。仮想ホスト形式のリクエストを使用することをお勧めします。

--
ロードバランサとセキュリティ証明書の要件を確認する:: StorageGRIDロード バランサを使用する予定の場合は、ロード バランシングに関する一般的な考慮事項を確認しておきます。アップロードする証明書、または証明書を生成するために必要な値があります。
+
--
外部 (サードパーティ) ロード バランサー エンドポイントを使用する予定の場合は、そのロード バランサーの完全修飾ドメイン名 (FQDN)、ポート、および証明書が必要です。

--
グリッドフェデレーション接続を構成する:: S3 テナントがグリッド フェデレーション接続を使用してアカウント データを複製し、バケット オブジェクトを別のグリッドに複製できるようにする場合は、ウィザードを開始する前に次の点を確認してください。
+
--
* あなたが持っているlink:grid-federation-manage-connection.html["グリッドフェデレーション接続を構成しました"]。
* 接続のステータスは*接続済み*です。
* ルートアクセス権限があります。


--

