---
permalink: admin/viewing-network-traffic-metrics.html 
sidebar: sidebar 
keywords: network traffic, traffic classification policy, monitor traffic 
summary: トラフィック分類ポリシー ページから利用できるグラフを表示することで、ネットワーク トラフィックを監視できます。 
---
= ネットワークトラフィックのメトリックを表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
トラフィック分類ポリシー ページから利用できるグラフを表示することで、ネットワーク トラフィックを監視できます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:admin-group-permissions.html["ルートアクセスまたはテナントアカウントの権限"]。


.タスク概要
既存のトラフィック分類ポリシーについては、ロード バランサ サービスのメトリックを表示して、ポリシーがネットワーク全体のトラフィックを正常に制限しているかどうかを確認できます。グラフのデータは、ポリシーを調整する必要があるかどうかを判断するのに役立ちます。

トラフィック分類ポリシーに制限が設定されていない場合でも、メトリックが収集され、グラフによってトラフィックの傾向を理解するのに役立つ情報が提供されます。

.手順
. *構成* > *ネットワーク* > *トラフィック分類*を選択します。
+
トラフィック分類ポリシー ページが表示され、既存のポリシーが表にリストされます。

. メトリックを表示するトラフィック分類ポリシー名を選択します。
. *メトリック*タブを選択します。
+
トラフィック分類ポリシー グラフが表示されます。グラフには、選択したポリシーに一致するトラフィックのメトリックのみが表示されます。

+
このページには次のグラフが含まれています。

+
** 要求レート: このグラフには、すべてのロード バランサーによって処理される、このポリシーに一致する帯域幅の量が表示されます。受信データには、すべてのリクエストのリクエスト ヘッダーと、本文データを持つ応答の本文データ サイズが含まれます。送信には、すべてのリクエストの応答ヘッダーと、応答に本文データが含まれるリクエストの応答本文データ サイズが含まれます。
+

NOTE: リクエストが完了すると、このグラフには帯域幅の使用状況のみが表示されます。低速または大きなオブジェクト要求の場合、実際の瞬間帯域幅はこのグラフで報告される値と異なる場合があります。

** エラー応答率: このグラフは、このポリシーに一致するリクエストがクライアントにエラー (HTTP ステータス コード >= 400) を返すおおよその割合を示します。
** 平均リクエスト期間 (エラーなし): このグラフには、このポリシーに一致する成功したリクエストの平均期間が表示されます。
** ポリシー帯域幅の使用状況: このグラフには、すべてのロード バランサーによって処理される、このポリシーに一致する帯域幅の量が表示されます。受信データには、すべてのリクエストのリクエスト ヘッダーと、本文データを持つ応答の本文データ サイズが含まれます。送信には、すべてのリクエストの応答ヘッダーと、応答に本文データが含まれるリクエストの応答本文データ サイズが含まれます。


. 折れ線グラフの上にカーソルを置くと、グラフの特定の部分の値のポップアップが表示されます。
. ポリシーのすべてのグラフを表示するには、メトリック タイトルのすぐ下にある *Grafana ダッシュボード* を選択します。  *メトリック* タブの 4 つのグラフに加えて、さらに 2 つのグラフを表示できます。
+
** オブジェクト サイズ別の書き込み要求レート: このポリシーに一致する PUT/POST/DELETE 要求のレート。個々のセルに配置すると、1 秒あたりのレートが表示されます。ホバー ビューに表示されるレートは整数カウントに切り捨てられ、バケット内にゼロ以外のリクエストがある場合は 0 と報告されることがあります。
** オブジェクト サイズ別の読み取り要求レート: このポリシーに一致する GET/HEAD 要求のレート。個々のセルに配置すると、1 秒あたりのレートが表示されます。ホバー ビューに表示されるレートは整数カウントに切り捨てられ、バケット内にゼロ以外のリクエストがある場合は 0 と報告されることがあります。


. または、*サポート* メニューからグラフにアクセスします。
+
.. *サポート* > *ツール* > *メトリック*を選択します。
.. *Grafana* セクションから *トラフィック分類ポリシー* を選択します。
.. ページの左上にあるメニューからポリシーを選択します。
.. グラフの上にカーソルを置くと、サンプルの日時、カウントに集計されるオブジェクト サイズ、その期間中の 1 秒あたりのリクエスト数を示すポップアップが表示されます。
+
トラフィック分類ポリシーは ID によって識別されます。ポリシー ID は、トラフィック分類ポリシー ページにリストされます。



. グラフを分析して、ポリシーがトラフィックを制限している頻度と、ポリシーを調整する必要があるかどうかを判断します。

