---
permalink: admin/what-is-autosupport.html 
sidebar: sidebar 
keywords: autosupport, technical support, storagegrid health, system status, Active IQ 
summary: AutoSupport機能により、 StorageGRID はヘルスおよびステータス パッケージをNetAppテクニカル サポートに送信できるようになります。 
---
= AutoSupportとは何ですか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport機能により、 StorageGRID はヘルスおよびステータス パッケージをNetAppテクニカル サポートに送信できるようになります。

AutoSupportを使用すると、問題の特定と解決が大幅に高速化されます。テクニカル サポートでは、システムのストレージのニーズを監視し、新しいノードまたはサイトを追加する必要があるかどうかを判断するお手伝いもいたします。オプションで、 AutoSupportパッケージを 1 つの追加の送信先に送信するように設定できます。

StorageGRID には 2 種類のAutoSupportがあります。

* * StorageGRID AutoSupport* は、 StorageGRIDソフトウェアの問題を報告します。 StorageGRIDを初めてインストールすると、デフォルトで有効になります。あなたはできるlink:configure-autosupport-grid-manager.html["デフォルトのAutoSupport設定を変更する"]必要であれば。
+

NOTE: StorageGRID AutoSupportが有効になっていない場合、Grid Manager ダッシュボードにメッセージが表示されます。メッセージには、 AutoSupport構成ページへのリンクが含まれています。メッセージを閉じると、 AutoSupport が無効のままであっても、ブラウザのキャッシュがクリアされるまでメッセージは再び表示されません。

* *アプライアンス ハードウェアAutoSupport* は、 StorageGRIDアプライアンスの問題を報告します。絶対ですlink:configure-autosupport-grid-manager.html#autosupport-for-appliances["各アプライアンスでハードウェアAutoSupportを構成する"]。




== Active IQとは何ですか？

Active IQは、NetApp のインストールベースからの予測分析とコミュニティの知恵を活用するクラウドベースのデジタル アドバイザーです。継続的なリスク評価、予測アラート、規範的なガイダンス、自動化されたアクションにより、問題が発生する前に防止することができ、システムの健全性が向上し、システムの可用性が高まります。

NetAppサポート サイトでActive IQダッシュボードと機能を使用する場合は、 AutoSupport を有効にする必要があります。

https://docs.netapp.com/us-en/active-iq/index.html["Active IQDigital Advisorのドキュメント"^]



== AutoSupportパッケージに含まれる情報

AutoSupportパッケージには、次のファイルと詳細が含まれています。

[cols="2a,2a,3a"]
|===
| ファイル名 | フィールド | 説明 


 a| 
AUTOSUPPORT-HISTORY.XML
 a| 
AutoSupportシーケンス番号 + このAutoSupportの宛先 + 配信ステータス + 配信試行回数 + AutoSupport件名 + 配信URI + 最終エラー + AutoSupport PUTファイル名 + 生成時刻 + AutoSupport圧縮サイズ + AutoSupport解凍サイズ + 合計収集時間（ミリ秒）
 a| 
AutoSupport履歴ファイル。



 a| 
AUTOSUPPORT.XML
 a| 
ノード + サポートへの問い合わせプロトコル + HTTP/HTTPS のサポート URL + サポート アドレス + AutoSupport OnDemand の状態 + AutoSupport OnDemand サーバ URL + AutoSupport OnDemand のポーリング間隔
 a| 
AutoSupportステータス ファイル。使用されているプロトコル、テクニカル サポートの URL とアドレス、ポーリング間隔、および OnDemand AutoSupport (有効または無効) の詳細を提供します。



 a| 
バケット.XML
 a| 
バケット ID + アカウント ID + ビルド バージョン + 場所制約設定 + コンプライアンス有効化 + コンプライアンス設定 + S3 オブジェクト ロック有効化 + S3 オブジェクト ロック設定 + 一貫性設定 + CORS 有効化 + CORS 設定 + 最終アクセス時刻有効化 + ポリシー有効化 + ポリシー設定 + 通知有効化 + 通知設定 + クラウド ミラー有効化 + クラウド ミラー設定 + 検索有効化 + 検索設定 + バケットタグ付け有効化 + バケットタグ付け設定 + バージョン設定
 a| 
バケット レベルで構成の詳細と統計を提供します。バケット構成の例には、プラットフォーム サービス、コンプライアンス、バケットの一貫性などがあります。



 a| 
グリッド構成.XML
 a| 
属性ID + 属性名 + 値 + インデックス + テーブルID + テーブル名
 a| 
グリッド全体の構成情報ファイル。グリッド証明書、メタデータ予約領域、グリッド全体の構成設定（コンプライアンス、S3オブジェクトロック、オブジェクト圧縮、アラート、syslog、ILM構成）、消失訂正コーディングプロファイルの詳細、DNS名、およびlink:../primer/nodes-and-services.html#storagegrid-services["NMS name"]。



 a| 
GRID-SPEC.XML
 a| 
グリッド仕様、生のXML
 a| 
StorageGRID の構成と展開に使用されます。グリッド仕様、NTP サーバー IP、DNS サーバー IP、ネットワーク トポロジ、およびノー​​ドのハードウェア プロファイルが含まれます。



 a| 
グリッドタスク.XML
 a| 
ノード + サービスパス + 属性ID + 属性名 + 値 + インデックス + テーブルID + テーブル名
 a| 
グリッド タスク (保守手順) ステータス ファイル。グリッドのアクティブ、終了、完了、失敗、および保留中のタスクの詳細を提供します。



 a| 
グリッド.JSON
 a| 
グリッド + リビジョン + ソフトウェアバージョン + 説明 + ライセンス + パスワード + DNS + NTP + サイト + ノード
 a| 
グリッド情報。



 a| 
ILM-CONFIGURATION.XML
 a| 
属性ID + 属性名 + 値 + インデックス + テーブルID + テーブル名
 a| 
ILM 構成の属性のリスト。



 a| 
ILM-STATUS.XML
 a| 
ノード + サービスパス + 属性ID + 属性名 + 値 + インデックス + テーブルID + テーブル名
 a| 
ILM メトリック情報ファイル。各ノードの ILM 評価レートとグリッド全体のメトリックが含まれます。



 a| 
ILM.XML
 a| 
ILM 生の XML
 a| 
ILM アクティブ ポリシー ファイル。ストレージ プール ID、取り込み動作、フィルター、ルール、説明など、アクティブな ILM ポリシーに関する詳細が含まれます。



 a| 
ログ.TGZ
 a| 
_該当なし_
 a| 
ダウンロード可能なログ ファイル。含む `bycast-err.log`そして `servermanager.log`各ノードから。



 a| 
マニフェスト.XML
 a| 
収集順序 + このデータのAutoSupportコンテンツファイル名 + このデータ項目の説明 + 収集されたバイト数 + 収集にかかった時間 + このデータ項目のステータス + エラーの説明 + このデータのAutoSupportコンテンツタイプ +
 a| 
AutoSupportメタデータとすべてのAutoSupportファイルの簡単な説明が含まれています。



 a| 
NMS-ENTITIES.XML
 a| 
属性インデックス + エンティティOID + ノードID + デバイスモデルID + デバイスモデルバージョン + エンティティ名
 a| 
グループおよびサービスエンティティlink:../primer/nodes-and-services.html#storagegrid-services["NMSツリー"]。グリッド トポロジの詳細を提供します。ノードは、ノード上で実行されているサービスに基づいて決定できます。



 a| 
オブジェクトステータス.XML
 a| 
ノード + サービスパス + 属性ID + 属性名 + 値 + インデックス + テーブルID + テーブル名
 a| 
オブジェクトのステータス。バックグラウンド スキャンのステータス、アクティブな転送、転送速度、合計転送数、削除率、破損したフラグメント、失われたオブジェクト、不足しているオブジェクト、試行された修復、スキャン速度、推定スキャン期間、および修復完了ステータスが含まれます。



 a| 
サーバーステータス.XML
 a| 
ノード + サービスパス + 属性ID + 属性名 + 値 + インデックス + テーブルID + テーブル名
 a| 
サーバー構成。各ノードについて、プラットフォームの種類、オペレーティング システム、インストールされているメモリ、使用可能なメモリ、ストレージの接続性、ストレージ アプライアンスのシャーシのシリアル番号、ストレージ コントローラの障害が発生したドライブの数、コンピューティング コントローラのシャーシの温度、コンピューティング ハードウェア、コンピューティング コントローラのシリアル番号、電源、ドライブ サイズ、およびドライブの種類の詳細が含まれます。



 a| 
サービスステータス.XML
 a| 
ノード + サービスパス + 属性ID + 属性名 + 値 + インデックス + テーブルID + テーブル名
 a| 
サービス ノード情報ファイル。割り当てられた表スペース、空き表スペース、データベースの Reaper メトリック、セグメント修復期間、修復ジョブ期間、自動ジョブ再起動、自動ジョブ終了などの詳細が含まれます。



 a| 
ストレージグレード.XML
 a| 
ストレージグレードID + ストレージグレード名 + ストレージノードID + ストレージノードパス
 a| 
各ストレージ ノードのストレージ グレード定義ファイル。



 a| 
サマリー属性.XML
 a| 
グループOID + グループパス + サマリー属性ID + サマリー属性名 + 値 + インデックス + テーブルID + テーブル名
 a| 
StorageGRID の使用状況情報を要約した高レベルのシステム ステータス データ。グリッド名、サイト名、グリッドおよびサイトあたりのストレージ ノードの数、ライセンスの種類、ライセンスの容量と使用状況、ソフトウェア サポート条件、S3 操作の詳細などの詳細を提供します。



 a| 
システムアラート.XML
 a| 
名前 + 重大度 + ノード名 + アラートステータス + サイト名 + アラート発生時刻 + アラート解決時刻 + ルールID + ノードID + サイトID + サイレンス + その他の注釈 + その他のラベル
 a| 
StorageGRIDシステムの潜在的な問題を示す現在のシステム アラート。



 a| 
ユーザーエージェント.XML
 a| 
ユーザーエージェント + 日数 + 合計 HTTP リクエスト + 取り込まれた合計バイト数 + 取得された合計バイト数 + PUT リクエスト + GET リクエスト + DELETE リクエスト + HEAD リクエスト + POST リクエスト + OPTIONS リクエスト + 平均リクエスト時間 (ミリ秒) + 平均 PUT リクエスト時間 (ミリ秒) + 平均 GET リクエスト時間 (ミリ秒) + 平均 DELETE リクエスト時間 (ミリ秒) + 平均 HEAD リクエスト時間 (ミリ秒) + 平均 POST リクエスト時間 (ミリ秒) + 平均 OPTIONS リクエスト時間 (ミリ秒)
 a| 
アプリケーション ユーザー エージェントに基づく統計。たとえば、ユーザーエージェントごとの PUT/GET/DELETE/HEAD 操作の数と各操作の合計バイト サイズなどです。



 a| 
X-ヘッダーデータ
 a| 
X-Netapp-asup-generated-on + X-Netapp-asup-hostname + X-Netapp-asup-os-version + X-Netapp-asup-serial-num + X-Netapp-asup-subject + X-Netapp-asup-system-id + X-Netapp-asup-model-name +
 a| 
AutoSupportヘッダー データ。

|===