---
permalink: s3/bucket-and-group-access-policies.html 
sidebar: sidebar 
keywords: bucket access policies, group access policies 
summary:  
---
= バケットとグループのアクセスポリシーを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID は、Amazon Web Services (AWS) ポリシー言語を使用して、S3 テナントがバケットおよびバケット内のオブジェクトへのアクセスを制御できるようにします。  StorageGRIDシステムは、S3 REST API ポリシー言語のサブセットを実装します。  S3 API のアクセス ポリシーは JSON で記述されます。



== アクセスポリシーの概要

StorageGRIDでサポートされているアクセス ポリシーには 2 種類あります。

* *バケット ポリシー*。GetBucketPolicy、PutBucketPolicy、DeleteBucketPolicy S3 API 操作、または Tenant Manager または Tenant Management API を使用して管理されます。バケット ポリシーはバケットに添付され、バケット所有者アカウントまたはその他のアカウントのユーザーによるバケットおよびバケット内のオブジェクトへのアクセスを制御するように構成されます。バケット ポリシーは 1 つのバケットにのみ適用され、複数のグループに適用される場合があります。
* *グループ ポリシー*。これは、Tenant Manager または Tenant Management API を使用して設定されます。グループ ポリシーはアカウント内のグループに添付され、そのグループがそのアカウントが所有する特定のリソースにアクセスできるように構成されます。グループ ポリシーは 1 つのグループにのみ適用され、複数のバケットに適用される場合もあります。



NOTE: グループ ポリシーとバケット ポリシーの優先順位に違いはありません。

StorageGRIDバケットおよびグループ ポリシーは、Amazon によって定義された特定の文法に従います。各ポリシー内にはポリシー ステートメントの配列があり、各ステートメントには次の要素が含まれています。

* ステートメントID（Sid）（オプション）
* 効果
* プリンシパル/非プリンシパル
* リソース/非リソース
* アクション/非アクション
* 条件（オプション）


ポリシー ステートメントは、次の構造を使用して作成され、アクセス許可を指定します: <Condition> が適用される場合に、<Principal> が <Resource> に対して <Action> を実行することを許可/拒否するには、<Effect> を付与します。

各ポリシー要素は特定の機能に使用されます。

[cols="1a,2a"]
|===
| 要素 | 説明 


 a| 
シド
 a| 
Sid 要素はオプションです。 Sid はユーザーへの説明としてのみ使用されます。これはStorageGRIDシステムによって保存されますが、解釈されません。



 a| 
効果
 a| 
Effect 要素を使用して、指定された操作が許可されるか拒否されるかを決定します。サポートされているアクション要素のキーワードを使用して、バケットまたはオブジェクトに対して許可 (または拒否) する操作を識別する必要があります。



 a| 
プリンシパル/非プリンシパル
 a| 
ユーザー、グループ、アカウントが特定のリソースにアクセスし、特定のアクションを実行できるようにすることができます。リクエストに S3 署名が含まれていない場合は、プリンシパルとしてワイルドカード文字 (*) を指定することにより匿名アクセスが許可されます。デフォルトでは、アカウント ルートのみがアカウントが所有するリソースにアクセスできます。

バケット ポリシーでは、Principal 要素のみを指定する必要があります。グループ ポリシーの場合、ポリシーが関連付けられているグループは暗黙的な Principal 要素です。



 a| 
リソース/非リソース
 a| 
リソース要素はバケットとオブジェクトを識別します。リソースを識別する Amazon リソースネーム (ARN) を使用して、バケットとオブジェクトへのアクセス許可を許可または拒否できます。



 a| 
アクション/非アクション
 a| 
アクション要素と効果要素は、権限の 2 つのコンポーネントです。グループがリソースを要求すると、リソースへのアクセスが許可または拒否されます。権限を明示的に割り当てない限りアクセスは拒否されますが、明示的な拒否を使用して、別のポリシーによって付与された権限を上書きすることができます。



 a| 
条件
 a| 
Condition 要素はオプションです。条件を使用すると、ポリシーをいつ適用するかを決定する式を作成できます。

|===
Action 要素では、ワイルドカード文字 (*) を使用して、すべての操作または操作のサブセットを指定できます。たとえば、このアクションは、s3:GetObject、s3:PutObject、s3:DeleteObject などの権限と一致します。

[listing]
----
s3:*Object
----
リソース要素では、ワイルドカード文字 (\*) と (?) を使用できます。アスタリスク (*) は 0 個以上の文字に一致しますが、疑問符 (?) は任意の 1 文字に一致します。

Principal 要素では、すべてのユーザーに権限を付与する匿名アクセスを設定する場合を除き、ワイルドカード文字はサポートされていません。たとえば、ワイルドカード (*) をプリンシパル値として設定します。

[listing]
----
"Principal":"*"
----
[listing]
----
"Principal":{"AWS":"*"}
----
次の例では、ステートメントは Effect、Principal、Action、および Resource 要素を使用しています。この例では、効果「許可」を使用してプリンシパル、管理者グループに権限を付与する完全なバケットポリシーステートメントを示しています。 `federated-group/admin`財務グループ `federated-group/finance`、アクションを実行する権限 `s3:ListBucket`バケットの名前 `mybucket`そしてアクション `s3:GetObject`そのバケット内のすべてのオブジェクトに適用されます。

[listing]
----
{
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::27233906934684427525:federated-group/admin",
          "arn:aws:iam::27233906934684427525:federated-group/finance"
        ]
      },
      "Action": [
        "s3:ListBucket",
        "s3:GetObject"
      ],
      "Resource": [
        "arn:aws:s3:::mybucket",
        "arn:aws:s3:::mybucket/*"
      ]
    }
  ]
}
----
バケット ポリシーのサイズ制限は 20,480 バイト、グループ ポリシーのサイズ制限は 5,120 バイトです。



== 政策の一貫性

デフォルトでは、グループ ポリシーに加えた更新はすべて最終的に一貫性を持ちます。グループ ポリシーが整合すると、ポリシーのキャッシュにより、変更が有効になるまでにさらに 15 分かかることがあります。デフォルトでは、バケット ポリシーに加えた更新はすべて強力な整合性を持ちます。

必要に応じて、バケット ポリシー更新の一貫性保証を変更できます。たとえば、サイトが停止している間もバケット ポリシーの変更を利用できるようにしたい場合があります。

この場合、 `Consistency-Control` PutBucketPolicy リクエストのヘッダーを追加するか、PUT Bucket 一貫性リクエストを使用することもできます。バケット ポリシーが整合すると、ポリシーのキャッシュにより、変更が有効になるまでにさらに 8 秒かかることがあります。


NOTE: 一時的な状況を回避するために一貫性を別の値に設定する場合は、完了したらバケット レベルの設定を元の値に戻してください。それ以外の場合、今後のすべてのバケット リクエストでは変更された設定が使用されます。



== ポリシーステートメントで ARN を使用する

ポリシーステートメントでは、ARN は Principal 要素と Resource 要素で使用されます。

* S3 リソース ARN を指定するには、次の構文を使用します。
+
[listing]
----
arn:aws:s3:::bucket-name
arn:aws:s3:::bucket-name/object_key
----
* 次の構文を使用して、アイデンティティ リソース ARN (ユーザーとグループ) を指定します。
+
[listing]
----
arn:aws:iam::account_id:root
arn:aws:iam::account_id:user/user_name
arn:aws:iam::account_id:group/group_name
arn:aws:iam::account_id:federated-user/user_name
arn:aws:iam::account_id:federated-group/group_name
----


その他の考慮事項:

* アスタリスク (*) をワイルドカードとして使用して、オブジェクト キー内の 0 個以上の文字を一致させることができます。
* オブジェクト キーで指定できる国際文字は、JSON UTF-8 または JSON \u エスケープ シーケンスを使用してエンコードする必要があります。パーセントエンコーディングはサポートされていません。
+
https://www.ietf.org/rfc/rfc2141.txt["RFC 2141 URN構文"^]

+
PutBucketPolicy 操作の HTTP リクエスト本体は、charset=UTF-8 でエンコードする必要があります。





== ポリシーでリソースを指定する

ポリシー ステートメントでは、Resource 要素を使用して、権限を許可または拒否するバケットまたはオブジェクトを指定できます。

* 各ポリシー ステートメントには、リソース要素が必要です。ポリシーでは、リソースは要素で表されます `Resource`、または、 `NotResource`除外のため。
* S3 リソース ARN を使用してリソースを指定します。例えば：
+
[listing]
----
"Resource": "arn:aws:s3:::mybucket/*"
----
* オブジェクト キー内でポリシー変数を使用することもできます。例えば：
+
[listing]
----
"Resource": "arn:aws:s3:::mybucket/home/${aws:username}/*"
----
* リソース値には、グループ ポリシーの作成時にまだ存在しないバケットを指定できます。




== ポリシーでプリンシパルを指定する

Principal 要素を使用して、ポリシー ステートメントによってリソースへのアクセスが許可/拒否されるユーザー、グループ、またはテナント アカウントを識別します。

* バケット ポリシー内の各ポリシー ステートメントには、Principal 要素を含める必要があります。グループ ポリシー内のポリシー ステートメントでは、グループがプリンシパルであると認識されるため、Principal 要素は必要ありません。
* ポリシーでは、プリンシパルは要素「Principal」で示され、除外する場合は「NotPrincipal」で示されます。
* アカウントベースの ID は、ID または ARN を使用して指定する必要があります。
+
[listing]
----
"Principal": { "AWS": "account_id"}
"Principal": { "AWS": "identity_arn" }
----
* この例では、アカウント ルートとアカウント内のすべてのユーザーを含むテナント アカウント ID 27233906934684427525 を使用します。
+
[listing]
----
 "Principal": { "AWS": "27233906934684427525" }
----
* アカウント ルートのみを指定することもできます。
+
[listing]
----
"Principal": { "AWS": "arn:aws:iam::27233906934684427525:root" }
----
* 特定のフェデレーション ユーザー (「Alex」) を指定できます。
+
[listing]
----
"Principal": { "AWS": "arn:aws:iam::27233906934684427525:federated-user/Alex" }
----
* 特定のフェデレーション グループ (「マネージャー」) を指定できます。
+
[listing]
----
"Principal": { "AWS": "arn:aws:iam::27233906934684427525:federated-group/Managers"  }
----
* 匿名プリンシパルを指定できます。
+
[listing]
----
"Principal": "*"
----
* 曖昧さを避けるために、ユーザー名の代わりにユーザーの UUID を使用できます。
+
[listing]
----
arn:aws:iam::27233906934684427525:user-uuid/de305d54-75b4-431b-adb2-eb6b9e546013
----
+
例えば、アレックスが組織を離れ、ユーザー名が `Alex`削除されます。新しいアレックスが組織に参加し、同じ役割を担う場合 `Alex`ユーザー名を変更すると、新しいユーザーが元のユーザーに付与された権限を意図せず継承してしまう可能性があります。

* プリンシパル値には、バケット ポリシーの作成時にまだ存在しないグループ/ユーザー名を指定できます。




== ポリシーで権限を指定する

ポリシーでは、アクション要素はリソースへのアクセス許可を許可/拒否するために使用されます。ポリシーで指定できる一連の権限があり、これらは要素「Action」で示され、除外の場合は「NotAction」で示されます。これらの各要素は、特定の S3 REST API 操作にマッピングされます。

表には、バケットに適用される権限とオブジェクトに適用される権限がリストされています。


NOTE: Amazon S3 は、PutBucketReplication アクションと DeleteBucketReplication アクションの両方に s3:PutReplicationConfiguration 権限を使用するようになりました。  StorageGRID は、元の Amazon S3 仕様に一致する、アクションごとに個別の権限を使用します。


NOTE: 既存の値を上書きするために put が使用されると、削除が実行されます。



=== バケットに適用される権限

[cols="2a,2a,1a"]
|===
| 権限 | S3 REST API 操作 | StorageGRID向けカスタム 


 a| 
s3:バケットの作成
 a| 
CreateBucket
 a| 
○

*注*: グループ ポリシーでのみ使用します。



 a| 
s3:バケットの削除
 a| 
DeleteBucket
 a| 



 a| 
s3:DeleteBucketMetadata通知
 a| 
バケットメタデータ通知設定の削除
 a| 
はい



 a| 
s3:DeleteBucketポリシー
 a| 
DeleteBucketPolicy
 a| 



 a| 
s3:レプリケーション構成の削除
 a| 
バケットレプリケーションの削除
 a| 
はい、PUTとDELETEに別々の権限が必要です



 a| 
s3:GetBucketAcl
 a| 
GetBucketAcl
 a| 



 a| 
s3:GetBucketCompliance
 a| 
GET バケットコンプライアンス（非推奨）
 a| 
はい



 a| 
s3:GetBucketConsistency
 a| 
GETバケットの一貫性
 a| 
はい



 a| 
s3:GetBucketCORS
 a| 
GetBucketCors
 a| 



 a| 
s3:暗号化設定の取得
 a| 
バケット暗号化を取得
 a| 



 a| 
s3:GetBucketLastAccessTime
 a| 
GET バケットの最終アクセス時刻
 a| 
はい



 a| 
s3:GetBucketLocation
 a| 
GetBucketLocation
 a| 



 a| 
s3:GetBucketMetadataNotification
 a| 
バケットメタデータ通知設定の取得
 a| 
はい



 a| 
s3:GetBucketNotification
 a| 
GetBucketNotificationConfiguration
 a| 



 a| 
s3:GetBucketObjectLockConfiguration
 a| 
GetObjectLockConfiguration
 a| 



 a| 
s3:GetBucketPolicy
 a| 
GetBucketPolicy
 a| 



 a| 
s3:GetBucketTagging
 a| 
GetBucketTagging
 a| 



 a| 
s3:GetBucketVersioning
 a| 
GetBucketVersioning
 a| 



 a| 
s3:GetLifecycleConfiguration
 a| 
GetBucketLifecycleConfiguration
 a| 



 a| 
s3:GetReplicationConfiguration
 a| 
GetBucketReplication
 a| 



 a| 
s3:すべてのバケットをリスト
 a| 
* ListBuckets
* ストレージ使用量の取得

 a| 
はい、GET ストレージ使用量の場合です。

*注*: グループ ポリシーでのみ使用します。



 a| 
s3:リストバケット
 a| 
* ListObjects
* HeadBucket
* オブジェクトの復元

 a| 



 a| 
s3:リストバケットマルチパートアップロード
 a| 
* リストマルチパートアップロード
* オブジェクトの復元

 a| 



 a| 
s3:バケットバージョンのリスト
 a| 
GETバケットのバージョン
 a| 



 a| 
s3:PutBucketコンプライアンス
 a| 
PUT バケットコンプライアンス（非推奨）
 a| 
はい



 a| 
s3:PutBucketConsistency
 a| 
PUT バケットの一貫性
 a| 
はい



 a| 
s3:PutBucketCORS
 a| 
* バケットCorsの削除†
* PutBucketCors

 a| 



 a| 
s3:PutEncryptionConfiguration
 a| 
* バケット暗号化の削除
* PutBucketEncryption

 a| 



 a| 
s3:PutBucket最終アクセス時間
 a| 
バケットの最終アクセス時刻をPUTする
 a| 
はい



 a| 
s3:PutBucketMetadataNotification
 a| 
PUT バケットメタデータ通知設定
 a| 
はい



 a| 
s3:PutBucket通知
 a| 
PutBucketNotificationConfiguration
 a| 



 a| 
s3:PutBucketObjectLockConfiguration
 a| 
* CreateBucketで `x-amz-bucket-object-lock-enabled: true`リクエストヘッダー（s3:CreateBucket権限も必要）
* PutObjectLockConfiguration

 a| 



 a| 
s3:PutBucketポリシー
 a| 
PutBucketPolicy
 a| 



 a| 
s3:PutBucketTagging
 a| 
* バケットタグの削除†
* PutBucketTagging

 a| 



 a| 
s3:PutBucketバージョン管理
 a| 
PutBucketVersioning
 a| 



 a| 
s3:PutLifecycleConfiguration
 a| 
* バケットライフサイクルの削除†
* PutBucketLifecycleConfiguration

 a| 



 a| 
s3:PutReplicationConfiguration
 a| 
PutBucketレプリケーション
 a| 
はい、PUTとDELETEに別々の権限が必要です

|===


=== オブジェクトに適用される権限

[cols="2a,2a,1a"]
|===
| 権限 | S3 REST API 操作 | StorageGRID向けカスタム 


 a| 
s3:マルチパートアップロードの中止
 a| 
* AbortMultipartUpload
* オブジェクトの復元

 a| 



 a| 
s3:バイパスガバナンス保持
 a| 
* DeleteObject
* DeleteObjects
* PutObjectRetention

 a| 



 a| 
s3:オブジェクトの削除
 a| 
* DeleteObject
* DeleteObjects
* オブジェクトの復元

 a| 



 a| 
s3:オブジェクトのタグ付けを削除
 a| 
DeleteObjectTagging
 a| 



 a| 
s3:オブジェクトバージョンタグ付けの削除
 a| 
DeleteObjectTagging (オブジェクトの特定のバージョン)
 a| 



 a| 
s3:オブジェクトバージョンの削除
 a| 
DeleteObject (オブジェクトの特定のバージョン)
 a| 



 a| 
s3:GetObject
 a| 
* GetObject
* HeadObject
* オブジェクトの復元
* オブジェクトコンテンツの選択

 a| 



 a| 
s3:GetObjectAcl
 a| 
GetObjectAcl
 a| 



 a| 
s3:GetObjectLegalHold
 a| 
GetObjectLegalHold
 a| 



 a| 
s3:GetObjectRetention
 a| 
GetObjectRetention
 a| 



 a| 
s3:GetObjectTagging
 a| 
GetObjectTagging
 a| 



 a| 
s3:GetObjectVersionTagging
 a| 
GetObjectTagging (オブジェクトの特定のバージョン)
 a| 



 a| 
s3:GetObjectVersion
 a| 
GetObject (オブジェクトの特定のバージョン)
 a| 



 a| 
s3:ListMultipartUploadParts
 a| 
リストパーツ、復元オブジェクト
 a| 



 a| 
s3:PutObject
 a| 
* PutObject
* CopyObject
* オブジェクトの復元
* CreateMultipartUpload
* CompleteMultipartUpload
* UploadPart
* UploadPartCopy

 a| 



 a| 
s3:PutObjectLegalHold
 a| 
PutObjectLegalHold
 a| 



 a| 
s3:PutObjectRetention
 a| 
PutObjectRetention
 a| 



 a| 
s3:オブジェクトのタグ付け
 a| 
PutObjectTagging
 a| 



 a| 
s3:PutObjectVersionTagging
 a| 
PutObjectTagging（オブジェクトの特定のバージョン）
 a| 



 a| 
s3:上書きオブジェクト
 a| 
* PutObject
* CopyObject
* PutObjectTagging
* DeleteObjectTagging
* CompleteMultipartUpload

 a| 
はい



 a| 
s3:オブジェクトの復元
 a| 
オブジェクトの復元
 a| 

|===


== PutOverwriteObject権限を使用する

s3:PutOverwriteObject 権限は、オブジェクトを作成または更新する操作に適用されるカスタムStorageGRID権限です。この権限の設定により、クライアントがオブジェクトのデータ、ユーザー定義のメタデータ、または S3 オブジェクトのタグ付けを上書きできるかどうかが決まります。

この権限で可能な設定は次のとおりです:

* *許可*: クライアントはオブジェクトを上書きできます。これがデフォルト設定です。
* *拒否*: クライアントはオブジェクトを上書きできません。  Deny に設定すると、PutOverwriteObject 権限は次のように動作します。
+
** 同じパスに既存のオブジェクトが見つかった場合:
+
*** オブジェクトのデータ、ユーザー定義のメタデータ、または S3 オブジェクトのタグ付けは上書きできません。
*** 進行中の取り込み操作はすべてキャンセルされ、エラーが返されます。
*** S3 のバージョン管理が有効になっている場合、Deny 設定により、PutObjectTagging または DeleteObjectTagging 操作によってオブジェクトとその非現在のバージョンの TagSet が変更されることが防止されます。


** 既存のオブジェクトが見つからない場合、この権限は効果がありません。


* この権限が存在しない場合は、Allow が設定されている場合と同じ効果になります。



NOTE: 現在の S3 ポリシーで上書きが許可されていて、PutOverwriteObject 権限が Deny に設定されている場合、クライアントはオブジェクトのデータ、ユーザー定義のメタデータ、またはオブジェクトのタグ付けを上書きできません。さらに、*クライアントによる変更を禁止する* チェックボックスが選択されている場合 (*[構成] > [セキュリティ設定] > [ネットワークとオブジェクト]*)、その設定は PutOverwriteObject 権限の設定よりも優先されます。



== ポリシーで条件を指定する

条件は、ポリシーがいつ有効になるかを定義します。条件は演算子とキーと値のペアで構成されます。

条件では、評価にキーと値のペアを使用します。 Condition 要素には複数の条件を含めることができ、各条件には複数のキーと値のペアを含めることができます。条件ブロックは次の形式を使用します。

[listing, subs="specialcharacters,quotes"]
----
Condition: {
     _condition_type_: {
          _condition_key_: _condition_values_
----
次の例では、IpAddress 条件で SourceIp 条件キーが使用されています。

[listing]
----
"Condition": {
    "IpAddress": {
      "aws:SourceIp": "54.240.143.0/24"
		...
},
		...
----


=== サポートされている条件演算子

条件演算子は次のように分類されます。

* 弦
* 数字
* ブーリアン
* IPアドレス
* ヌルチェック


[cols="1a,2a"]
|===
| 条件演算子 | 説明 


 a| 
文字列に等しい
 a| 
完全一致 (大文字と小文字を区別) に基づいてキーと文字列値を比較します。



 a| 
文字列が等しくない
 a| 
否定一致（大文字と小文字を区別）に基づいてキーと文字列値を比較します。



 a| 
文字列が等しい場合、大文字と小文字を区別しない
 a| 
完全一致 (大文字と小文字は区別されません) に基づいてキーと文字列値を比較します。



 a| 
文字列が等しくない場合大文字と小文字を区別しない
 a| 
否定一致（大文字と小文字を区別しない）に基づいてキーと文字列値を比較します。



 a| 
文字列のような
 a| 
完全一致 (大文字と小文字を区別) に基づいてキーと文字列値を比較します。  * および ? ワイルドカード文字を含めることができます。



 a| 
文字列が似ていない
 a| 
否定一致（大文字と小文字を区別）に基づいてキーと文字列値を比較します。  * および ? ワイルドカード文字を含めることができます。



 a| 
数値等しい
 a| 
完全一致に基づいてキーと数値を比較します。



 a| 
数値NotEquals
 a| 
否定一致に基づいてキーと数値を比較します。



 a| 
数値より大きい
 a| 
「より大きい」一致に基づいてキーと数値を比較します。



 a| 
数値より大きい
 a| 
「以上」の一致に基づいてキーと数値を比較します。



 a| 
数値の小数点以下
 a| 
「より小さい」一致に基づいてキーを数値と比較します。



 a| 
数値の「未満」
 a| 
「以下」の一致に基づいてキーと数値を比較します。



 a| 
ブール
 a| 
「true または false」の一致に基づいてキーをブール値と比較します。



 a| 
IPアドレス
 a| 
キーを IP アドレスまたは IP アドレスの範囲と比較します。



 a| 
IPアドレスなし
 a| 
否定一致に基づいて、キーを IP アドレスまたは IP アドレスの範囲と比較します。



 a| 
Null
 a| 
現在のリクエスト コンテキストに条件キーが存在するかどうかを確認します。

|===


=== サポートされている条件キー

[cols="1a,1a,2a"]
|===
| 条件キー | アクション | 説明 


 a| 
aws:ソースIP
 a| 
IPオペレーター
 a| 
リクエストの送信元の IP アドレスと比較します。バケットまたはオブジェクトの操作に使用できます。

*注:* S3 リクエストが管理ノードおよびゲートウェイ ノードのロード バランサ サービスを通じて送信された場合、これはロード バランサ サービスのアップストリームの IP アドレスと比較されます。

*注*: サードパーティの非透過ロードバランサが使用されている場合、これはそのロードバランサの IP アドレスと比較されます。どれでも `X-Forwarded-For`ヘッダーの有効性を確認できないため、無視されます。



 a| 
aws:ユーザー名
 a| 
リソース/アイデンティティ
 a| 
リクエストの送信元のユーザー名と比較します。バケットまたはオブジェクトの操作に使用できます。



 a| 
s3:区切り文字
 a| 
s3:ListBucketと

s3:ListBucketVersions 権限
 a| 
ListObjects または ListObjectVersions リクエストで指定された区切り文字パラメータと比較します。



 a| 
s3:ExistingObjectTag/<タグキー>
 a| 
s3:オブジェクトのタグ付けを削除

s3:オブジェクトバージョンタグ付けの削除

s3:GetObject

s3:GetObjectAcl

3:オブジェクトのタグ付けを取得する

s3:GetObjectVersion

s3:GetObjectVersionAcl

s3:GetObjectVersionTagging

s3:PutObjectAcl

s3:オブジェクトのタグ付け

s3:PutObjectVersionAcl

s3:PutObjectVersionTagging
 a| 
既存のオブジェクトに特定のタグ キーと値があることが必要になります。



 a| 
s3:最大キー数
 a| 
s3:ListBucketと

s3:ListBucketVersions 権限
 a| 
ListObjects または ListObjectVersions リクエストで指定された max-keys パラメータと比較します。



 a| 
s3:オブジェクトロックの残り保持日数
 a| 
s3:PutObject
 a| 
指定された保持期限日と比較します `x-amz-object-lock-retain-until-date`リクエスト ヘッダーまたはバケットのデフォルトの保持期間から計算され、これらの値が次のリクエストの許容範囲内であることを確認します。

* PutObject
* CopyObject
* CreateMultipartUpload




 a| 
s3:オブジェクトロックの残り保持日数
 a| 
s3:PutObjectRetention
 a| 
PutObjectRetention リクエストで指定された retain-until-date と比較して、それが許容範囲内であることを確認します。



 a| 
s3:プレフィックス
 a| 
s3:ListBucketと

s3:ListBucketVersions 権限
 a| 
ListObjects または ListObjectVersions リクエストで指定されたプレフィックス パラメータと比較します。



 a| 
s3:RequestObjectTag/<タグキー>
 a| 
s3:PutObject

s3:オブジェクトのタグ付け

s3:PutObjectVersionTagging
 a| 
オブジェクト リクエストにタグ付けが含まれている場合は、特定のタグ キーと値が必要になります。

|===


== ポリシーで変数を指定する

利用可能な場合にポリシー情報を入力するには、ポリシー内の変数を使用できます。ポリシー変数は、 `Resource`要素と文字列の比較では `Condition`要素。

この例では、変数 `${aws:username}`リソース要素の一部です:

[listing]
----
"Resource": "arn:aws:s3:::bucket-name/home/${aws:username}/*"
----
この例では、変数 `${aws:username}`条件ブロック内の条件値の一部です。

[listing]
----
"Condition": {
    "StringLike": {
      "s3:prefix": "${aws:username}/*"
		...
},
		...
----
[cols="1a,2a"]
|===
| 変数 | 説明 


 a| 
`${aws:SourceIp}`
 a| 
提供された変数として SourceIp キーを使用します。



 a| 
`${aws:username}`
 a| 
提供された変数としてユーザー名キーを使用します。



 a| 
`${s3:prefix}`
 a| 
提供された変数としてサービス固有のプレフィックス キーを使用します。



 a| 
`${s3:max-keys}`
 a| 
提供された変数としてサービス固有の max-keys キーを使用します。



 a| 
`${*}`
 a| 
特殊文字。文字をリテラル * 文字として使用します。



 a| 
`${?}`
 a| 
特殊文字。文字をリテラル ? 文字として使用します。



 a| 
`${$}`
 a| 
特殊文字。文字をリテラル $ 文字として使用します。

|===


== 特別な処理を必要とするポリシーを作成する

場合によっては、ポリシーによって、アカウントのルート ユーザーをロックアウトするなど、セキュリティ上危険な権限や継続的な操作にとって危険な権限が付与されることがあります。  StorageGRID S3 REST API 実装は、ポリシー検証時には Amazon よりも制限が少なくなりますが、ポリシー評価時には同様に厳格になります。

[cols="2a,1a,2a,2a"]
|===
| ポリシーの説明 | ポリシー タイプ | アマゾンの行動 | StorageGRIDの動作 


 a| 
ルートアカウントへのすべての権限を拒否する
 a| 
バケット
 a| 
有効かつ強制されていますが、ルートユーザーアカウントはすべての S3 バケットポリシー操作の権限を保持します。
 a| 
同じ



 a| 
ユーザー/グループへのすべての権限を拒否する
 a| 
グループ
 a| 
有効かつ強制
 a| 
同じ



 a| 
外国のアカウントグループに任意の権限を許可する
 a| 
バケット
 a| 
無効なプリンシパル
 a| 
有効ですが、すべての S3 バケットポリシー操作の権限は、ポリシーで許可されている場合、405 メソッドが許可されていないエラーを返します。



 a| 
外部アカウントのルートまたはユーザーに任意の権限を許可する
 a| 
バケット
 a| 
有効ですが、すべての S3 バケットポリシー操作の権限は、ポリシーで許可されている場合、405 メソッドが許可されていないエラーを返します。
 a| 
同じ



 a| 
すべてのアクションに対する権限を全員に許可する
 a| 
バケット
 a| 
有効ですが、すべてのS3バケットポリシー操作の権限は、外部アカウントのルートとユーザーに対して405 Method Not Allowedエラーを返します。
 a| 
同じ



 a| 
すべてのアクションに対する全員の権限を拒否
 a| 
バケット
 a| 
有効かつ強制されていますが、ルートユーザーアカウントはすべての S3 バケットポリシー操作の権限を保持します。
 a| 
同じ



 a| 
プリンシパルは存在しないユーザーまたはグループです
 a| 
バケット
 a| 
無効なプリンシパル
 a| 
有効



 a| 
リソースは存在しないS3バケットです
 a| 
グループ
 a| 
有効
 a| 
同じ



 a| 
校長は地元のグループです
 a| 
バケット
 a| 
無効なプリンシパル
 a| 
有効



 a| 
ポリシーは、所有者以外のアカウント (匿名アカウントを含む) にオブジェクトを配置する権限を付与します。
 a| 
バケット
 a| 
有効。オブジェクトは作成者アカウントによって所有され、バケット ポリシーは適用されません。作成者アカウントは、オブジェクト ACL を使用してオブジェクトへのアクセス権限を付与する必要があります。
 a| 
有効。オブジェクトはバケット所有者アカウントによって所有されます。バケットポリシーが適用されます。

|===


== 一度書き込み、何度も読み取り可能な（WORM）保護

データ、ユーザー定義のオブジェクト メタデータ、および S3 オブジェクトのタグ付けを保護するために、Write Once Read Many (WORM) バケットを作成できます。 WORM バケットを構成して、新しいオブジェクトの作成を許可し、既存のコンテンツの上書きや削除を防止します。ここで説明するいずれかのアプローチを使用します。

上書きが常に拒否されるようにするには、次の操作を実行します。

* グリッド マネージャーから、[構成] > [セキュリティ] > [セキュリティ設定] > [ネットワークとオブジェクト] に移動し、[クライアントの変更を禁止する] チェックボックスをオンにします。
* 次のルールと S3 ポリシーを適用します。
+
** S3 ポリシーに PutOverwriteObject DENY 操作を追加します。
** S3 ポリシーに DeleteObject DENY 操作を追加します。
** S3 ポリシーに PutObject ALLOW 操作を追加します。





NOTE: S3 ポリシーで DeleteObject を DENY に設定しても、「30 日後にコピーがゼロ」などのルールが存在する場合は ILM によるオブジェクトの削除を防ぐことはできません。


NOTE: これらすべてのルールとポリシーを適用しても、同時書き込みを防ぐことはできません (状況 A を参照)。連続した完了上書きは防止します (状況 B を参照)。

*状況A*: 同時書き込み（防御されていない）

[listing]
----
/mybucket/important.doc
PUT#1 ---> OK
PUT#2 -------> OK
----
*状況B*: 連続した完了上書き（防止対象）

[listing]
----
/mybucket/important.doc
PUT#1 -------> PUT#2 ---X (denied)
----
.関連情報
* link:how-storagegrid-ilm-rules-manage-objects.html["StorageGRID ILMルールによるオブジェクトの管理方法"]
* link:example-bucket-policies.html["バケットポリシーの例"]
* link:example-group-policies.html["グループポリシーの例"]
* link:../ilm/index.html["ILMでオブジェクトを管理する"]
* link:../tenant/index.html["テナントアカウントを使用する"]

