---
permalink: s3/complete-multipart-upload.html 
sidebar: sidebar 
keywords: multipart upload, object, object size 
summary: CompleteMultipartUpload 操作は、以前にアップロードされた部分を組み立てることで、オブジェクトのマルチパートアップロードを完了します。 
---
= CompleteMultipartUpload
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CompleteMultipartUpload 操作は、以前にアップロードされた部分を組み立てることで、オブジェクトのマルチパートアップロードを完了します。


NOTE: StorageGRIDは昇順で連続しない値をサポートします。 `partNumber` CompleteMultipartUpload のリクエスト パラメータ。パラメータは任意の値で始めることができます。



== 紛争を解決する

2 つのクライアントが同じキーに書き込むなど、競合するクライアント要求は、「最新のものを優先」して解決されます。  「最新のもの優先」評価のタイミングは、S3 クライアントが操作を開始した時点ではなく、 StorageGRIDシステムが特定のリクエストを完了した時点に基づきます。



== サポートされているリクエストヘッダー

次のリクエスト ヘッダーがサポートされています。

* `x-amz-checksum-sha256`
* `x-amz-storage-class`
+
その `x-amz-storage-class`ヘッダーは、一致するILMルールで指定されている場合にStorageGRIDが作成するオブジェクトコピーの数に影響します。link:../ilm/data-protection-options-for-ingest.html["デュアルコミットまたはバランス取り込みオプション"] 。

* `STANDARD`
+
(デフォルト) ILM ルールがデュアル コミット オプションを使用する場合、またはバランス オプションが中間コピーの作成にフォールバックする場合に、デュアル コミット インジェスト操作を指定します。

* `REDUCED_REDUNDANCY`
+
ILM ルールがデュアル コミット オプションを使用する場合、またはバランス オプションが中間コピーの作成にフォールバックする場合に、単一コミットの取り込み操作を指定します。

+

NOTE: S3オブジェクトロックが有効になっているバケットにオブジェクトを取り込む場合、 `REDUCED_REDUNDANCY`オプションは無視されます。レガシーコンプライアンスバケットにオブジェクトを取り込む場合、 `REDUCED_REDUNDANCY`オプションはエラーを返します。  StorageGRID は、コンプライアンス要件が満たされていることを確認するために、常にデュアルコミット取り込みを実行します。




CAUTION: マルチパートアップロードが 15 日以内に完了しない場合、操作は非アクティブとしてマークされ、関連するすべてのデータがシステムから削除されます。


NOTE: その `ETag`返される値はデータのMD5合計ではなく、Amazon S3 API実装に従います。 `ETag`マルチパートオブジェクトの値。



== サポートされていないリクエストヘッダー

次のリクエスト ヘッダーはサポートされていません。

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`




== バージョン管理

この操作により、マルチパートアップロードが完了します。バケットのバージョン管理が有効になっている場合、マルチパートアップロードの完了後にオブジェクト バージョンが作成されます。

バケットのバージョン管理が有効になっている場合、一意の `versionId`保存されるオブジェクトのバージョンに応じて自動的に生成されます。これ `versionId`レスポンスでは、 `x-amz-version-id`レスポンス ヘッダー。

バージョン管理が中断されている場合、オブジェクトのバージョンはnullで保存されます。 `versionId`ヌル バージョンがすでに存在する場合は上書きされます。


NOTE: バケットのバージョン管理が有効になっている場合、同じオブジェクト キーで同時にマルチパート アップロードが完了している場合でも、マルチパート アップロードを完了すると常に新しいバージョンが作成されます。バケットでバージョン管理が有効になっていない場合、マルチパートアップロードを開始し、次に同じオブジェクト キーで別のマルチパートアップロードを開始して完了させることが可能です。バージョン管理されていないバケットでは、最後に完了したマルチパートアップロードが優先されます。



== レプリケーション、通知、またはメタデータ通知が失敗しました

マルチパートアップロードが行われるバケットがプラットフォーム サービス用に構成されている場合、関連付けられたレプリケーションまたは通知アクションが失敗しても、マルチパートアップロードは成功します。

テナントは、オブジェクトのメタデータまたはタグを更新することで、失敗したレプリケーションまたは通知をトリガーできます。テナントは、不要な変更を避けるために既存の値を再送信できます。

。 link:../admin/troubleshooting-platform-services.html["プラットフォームサービスのトラブルシューティング"] 。
