---
permalink: s3/get-storage-usage-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET storage usage request 
summary: GET ストレージ使用量リクエストは、アカウントで使用されているストレージの合計量と、アカウントに関連付けられている各バケットのストレージ量を通知します。 
---
= GETストレージ使用量リクエスト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
GET ストレージ使用量リクエストは、アカウントで使用されているストレージの合計量と、アカウントに関連付けられている各バケットのストレージ量を通知します。

アカウントとそのバケットで使用されているストレージの量は、ListBucketsリクエストを修正することで取得できます。 `x-ntap-sg-usage`クエリパラメータ。バケット ストレージの使用量は、システムによって処理される PUT および DELETE 要求とは別に追跡されます。特にシステムの負荷が高い場合、リクエストの処理に基づいて使用量の値が予想値と一致するまでに多少の遅延が発生する可能性があります。

デフォルトでは、 StorageGRID は強力なグローバル一貫性を使用して使用状況情報を取得しようとします。強力なグローバル一貫性を実現できない場合、 StorageGRID は強力なサイト一貫性で使用状況情報を取得しようとします。

この操作を完了するには、s3:ListAllMyBuckets 権限を持っているか、アカウント ルートである必要があります。



== リクエスト例

[listing, subs="specialcharacters,quotes"]
----
GET /?x-ntap-sg-usage HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== 応答例

この例では、2 つのバケットに 4 つのオブジェクトと 12 バイトのデータがあるアカウントを示しています。各バケットには 2 つのオブジェクトと 6 バイトのデータが含まれます。

[listing]
----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 00:49:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/10.2.0
x-amz-request-id: 727237123
Content-Length: 427
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<UsageResult xmlns="http://s3.storagegrid.com/doc/2015-02-01">
<CalculationTime>2014-11-19T05:30:11.000000Z</CalculationTime>
<ObjectCount>4</ObjectCount>
<DataBytes>12</DataBytes>
<Buckets>
<Bucket>
<Name>bucket1</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
<Bucket>
<Name>bucket2</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
</Buckets>
</UsageResult>
----


== バージョン管理

保存されたすべてのオブジェクトバージョンは、 `ObjectCount`そして `DataBytes`応答内の値。削除マーカーは追加されません `ObjectCount`合計。

.関連情報
link:consistency-controls.html["一貫性の値"]
