---
permalink: s3/initiate-multipart-upload.html 
sidebar: sidebar 
keywords: initiate multipart upload, CreateMultipartUpload, upload ID 
summary: CreateMultipartUpload 操作は、オブジェクトのマルチパートアップロードを開始し、アップロード ID を返します。 
---
= CreateMultipartUpload
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CreateMultipartUpload (以前の名前は Initiate Multipart Upload) 操作は、オブジェクトのマルチパートアップロードを開始し、アップロード ID を返します。

その `x-amz-storage-class`リクエスト ヘッダーがサポートされています。提出された値は `x-amz-storage-class`StorageGRID が取り込み中にオブジェクト データを保護する方法に影響しますが、オブジェクトの永続コピーがStorageGRIDシステムにいくつ保存されるかには影響しません (これは ILM によって決定されます)。

取り込まれたオブジェクトに一致するILMルールが厳密なlink:../ilm/data-protection-options-for-ingest.html["取り込みオプション"]、 `x-amz-storage-class`ヘッダーは効果がありません。

以下の値は、 `x-amz-storage-class` :

* `STANDARD`（デフォルト）
+
** *デュアル コミット*: ILM ルールでデュアル コミット取り込みオプションが指定されている場合は、オブジェクトが取り込まれるとすぐにそのオブジェクトの 2 番目のコピーが作成され、別のストレージ ノードに配布されます (デュアル コミット)。 ILM が評価されると、 StorageGRID はこれらの初期の中間コピーがルール内の配置指示を満たしているかどうかを判断します。そうでない場合は、別の場所に新しいオブジェクトのコピーを作成し、初期の中間コピーを削除する必要があるかもしれません。
** *バランス*: ILM ルールでバランス オプションが指定されていて、 StorageGRID がルールで指定されたすべてのコピーをすぐに作成できない場合、 StorageGRID は異なるストレージ ノードに 2 つの中間コピーを作成します。
+
StorageGRIDがILMルールで指定されたすべてのオブジェクトコピーを即時に作成できる場合（同期配置）、 `x-amz-storage-class`ヘッダーは効果がありません。



* `REDUCED_REDUNDANCY`
+
** *デュアル コミット*: ILM ルールでデュアル コミット オプションが指定されている場合、 StorageGRID はオブジェクトが取り込まれると単一の中間コピーを作成します (シングル コミット)。
** *バランス*: ILM ルールでバランス オプションが指定されている場合、 StorageGRID は、システムがルールで指定されたすべてのコピーをすぐに作成できない場合にのみ、単一の中間コピーを作成します。 StorageGRID が同期配置を実行できる場合、このヘッダーは効果がありません。その `REDUCED_REDUNDANCY`このオプションは、オブジェクトに一致する ILM ルールによって単一の複製コピーが作成される場合に最適です。この場合、 `REDUCED_REDUNDANCY`すべての取り込み操作で余分なオブジェクト コピーが不必要に作成および削除されるのを防ぎます。


+
使用して `REDUCED_REDUNDANCY`他の状況ではこのオプションは推奨されません。 `REDUCED_REDUNDANCY`取り込み中にオブジェクト データが失われるリスクが高まります。たとえば、ILM 評価が行われる前に障害が発生したストレージ ノードに単一のコピーが最初に保存された場合、データが失われる可能性があります。




CAUTION: 任意の期間に複製されたコピーが 1 つしかない場合、データが永久に失われるリスクがあります。オブジェクトの複製されたコピーが 1 つしか存在しない場合、ストレージ ノードに障害が発生したり重大なエラーが発生すると、そのオブジェクトは失われます。また、アップグレードなどのメンテナンス手順中は、オブジェクトへのアクセス権が一時的に失われます。

指定 `REDUCED_REDUNDANCY`オブジェクトが最初に取り込まれたときに作成されるコピーの数にのみ影響します。これは、オブジェクトがアクティブな ILM ポリシーによって評価されるときに作成されるオブジェクトのコピー数には影響せず、 StorageGRIDシステムに低いレベルの冗長性でデータが保存されることにはなりません。


NOTE: S3オブジェクトロックが有効になっているバケットにオブジェクトを取り込む場合、 `REDUCED_REDUNDANCY`オプションは無視されます。レガシーコンプライアンスバケットにオブジェクトを取り込む場合、 `REDUCED_REDUNDANCY`オプションはエラーを返します。  StorageGRID は、コンプライアンス要件が満たされていることを確認するために、常にデュアルコミット取り込みを実行します。



== サポートされているリクエストヘッダー

次のリクエスト ヘッダーがサポートされています。

* `Content-Type`
* `x-amz-checksum-algorithm`
+
現在、SHA256値のみが `x-amz-checksum-algorithm`サポートされています。

* `x-amz-meta-`、その後にユーザー定義のメタデータを含む名前と値のペアが続く
+
ユーザー定義のメタデータの名前と値のペアを指定する場合は、次の一般的な形式を使用します。

+
[listing]
----
x-amz-meta-_name_: `value`
----
+
ILMルールの参照時間として*ユーザー定義作成時間*オプションを使用する場合は、 `creation-time`オブジェクトが作成された日時を記録するメタデータの名前として。例えば：

+
[listing]
----
x-amz-meta-creation-time: 1443399726
----
+
の価値 `creation-time`1970 年 1 月 1 日からの秒数として評価されます。

+

NOTE: 追加 `creation-time`従来のコンプライアンスが有効になっているバケットにオブジェクトを追加する場合、ユーザー定義のメタデータは許可されません。エラーが返されます。

* S3 オブジェクトロックリクエストヘッダー:
+
** `x-amz-object-lock-mode`
** `x-amz-object-lock-retain-until-date`
** `x-amz-object-lock-legal-hold`
+
これらのヘッダーなしでリクエストが行われた場合、バケットのデフォルトの保持設定を使用して、オブジェクト バージョンの保持期限が計算されます。

+
link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API を使用して S3 オブジェクトロックを設定する"]



* SSE リクエスト ヘッダー:
+
** `x-amz-server-side-encryption`
** `x-amz-server-side-encryption-customer-key-MD5`
** `x-amz-server-side-encryption-customer-key`
** `x-amz-server-side-encryption-customer-algorithm`
+
<<サーバー側暗号化のリクエストヘッダー>>



+

NOTE: StorageGRIDがUTF-8文字を処理する方法については、以下を参照してください。link:put-object.html["PutObject"] 。





== サーバー側暗号化のリクエストヘッダー

次のリクエスト ヘッダーを使用して、サーバー側暗号化でマルチパート オブジェクトを暗号化できます。  SSE オプションと SSE-C オプションは相互に排他的です。

* *SSE*: StorageGRIDによって管理される一意のキーを使用してオブジェクトを暗号化する場合は、CreateMultipartUpload リクエストで次のヘッダーを使用します。いずれの UploadPart リクエストでもこのヘッダーを指定しないでください。
+
** `x-amz-server-side-encryption`


* *SSE-C*: 提供および管理する一意のキーを使用してオブジェクトを暗号化する場合は、CreateMultipartUpload リクエスト (および後続の各 UploadPart リクエスト) でこれら 3 つのヘッダーをすべて使用します。
+
** `x-amz-server-side-encryption-customer-algorithm`： 特定 `AES256`。
** `x-amz-server-side-encryption-customer-key`: 新しいオブジェクトの暗号化キーを指定します。
** `x-amz-server-side-encryption-customer-key-MD5`: 新しいオブジェクトの暗号化キーの MD5 ダイジェストを指定します。





CAUTION: 提供された暗号化キーは保存されません。暗号化キーを紛失すると、対応するオブジェクトも失われます。顧客提供のキーを使用してオブジェクトデータを保護する前に、以下の考慮事項を確認してください。link:using-server-side-encryption.html["サーバー側暗号化を使用する"] 。



== サポートされていないリクエストヘッダー

次のリクエスト ヘッダーはサポートされていません。

* `x-amz-website-redirect-location`
+
その `x-amz-website-redirect-location`ヘッダーリターン `XNotImplemented`。





== バージョン管理

マルチパートアップロードは、アップロードの開始、アップロードの一覧表示、パーツのアップロード、アップロードされたパーツの組み立て、アップロードの完了という個別の操作で構成されます。  CompleteMultipartUpload 操作が実行されると、オブジェクトが作成され (該当する場合はバージョン管理も行われます)。
