---
permalink: s3/object-versioning.html 
sidebar: sidebar 
keywords: object version, object versioning 
summary: オブジェクトの複数のバージョンを保持する場合は、バケットのバージョン管理状態を設定できます。バケットのバージョン管理を有効にすると、オブジェクトが誤って削除されるのを防ぎ、オブジェクトの以前のバージョンを取得して復元できるようになります。 
---
= オブジェクトのバージョン管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各オブジェクトの複数のバージョンを保持する場合は、バケットのバージョン管理状態を設定できます。バケットのバージョン管理を有効にすると、オブジェクトが誤って削除されるのを防ぎ、オブジェクトの以前のバージョンを取得して復元できるようになります。

StorageGRIDシステムは、ほとんどの機能をサポートするバージョン管理を実装していますが、いくつかの制限があります。  StorageGRID は、各オブジェクトの最大 10,000 バージョンをサポートします。

オブジェクトのバージョン管理は、 StorageGRID情報ライフサイクル管理 (ILM) または S3 バケット ライフサイクル構成と組み合わせることができます。各バケットに対してバージョン管理を明示的に有効にする必要があります。バケットのバージョン管理が有効になっている場合、バケットに追加された各オブジェクトには、 StorageGRIDシステムによって生成されるバージョン ID が割り当てられます。

MFA (多要素認証) を使用した削除はサポートされていません。


NOTE: バージョン管理は、 StorageGRIDバージョン 10.3 以降で作成されたバケットでのみ有効にできます。



== ILMとバージョン管理

ILM ポリシーはオブジェクトの各バージョンに適用されます。  ILM スキャン プロセスは、すべてのオブジェクトを継続的にスキャンし、現在の ILM ポリシーに対して再評価します。 ILM ポリシーに加えた変更は、以前に取り込まれたすべてのオブジェクトに適用されます。バージョン管理が有効になっている場合は、以前に取り込まれたバージョンも含まれます。  ILM スキャンは、以前に取り込まれたオブジェクトに新しい ILM 変更を適用します。

バージョン管理が有効なバケット内のS3オブジェクトの場合、バージョン管理のサポートにより、「非現在時刻」を参照時刻として使用するILMルールを作成できます（「このルールを古いオブジェクトバージョンにのみ適用しますか？」という質問に対して*はい*を選択します）。link:../ilm/create-ilm-rule-enter-details.html["ILMルールの作成ウィザードのステップ1"] ）。オブジェクトが更新されると、以前のバージョンは非最新になります。  「非現在の時間」フィルターを使用すると、オブジェクトの以前のバージョンによるストレージへの影響を軽減するポリシーを作成できます。


NOTE: マルチパートアップロード操作を使用してオブジェクトの新しいバージョンをアップロードすると、オブジェクトの元のバージョンの非現在の時間は、マルチパートアップロードが完了したときではなく、新しいバージョンのマルチパートアップロードが作成されたときに反映されます。場合によっては、元のバージョンの非現在の時刻が現在のバージョンの時刻よりも数時間または数日前になることがあります。

.関連情報
* link:../ilm/how-objects-are-deleted.html#delete-s3-versioned-objects["S3 バージョン管理オブジェクトの削除方法"]
* link:../ilm/example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["S3 バージョン管理オブジェクトの ILM ルールとポリシー (例 4)"] 。

