---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, RestoreObject, object 
summary: S3 RestoreObject リクエストを使用して、クラウド ストレージ プールに保存されているオブジェクトを復元できます。 
---
= オブジェクトの復元
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 RestoreObject リクエストを使用して、クラウド ストレージ プールに保存されているオブジェクトを復元できます。



== サポートされているリクエストタイプ

StorageGRID は、オブジェクトを復元するための RestoreObject 要求のみをサポートします。サポートされていません `SELECT`修復の種類。選択したリクエストの戻り `XNotImplemented`。



== バージョン管理

オプションで指定 `versionId`バージョン管理されたバケット内のオブジェクトの特定のバージョンを復元します。指定しない場合 `versionId`オブジェクトの最新バージョンが復元されます



== Cloud Storage Pool オブジェクトにおける RestoreObject の動作

オブジェクトがlink:../ilm/what-cloud-storage-pool-is.html["クラウド ストレージ プール"]RestoreObject 要求は、オブジェクトの状態に基づいて次の動作をします。見るlink:head-object.html["HeadObject"]詳細についてはこちらをご覧ください。


NOTE: オブジェクトがクラウド ストレージ プールに保存され、そのオブジェクトの 1 つ以上のコピーがグリッド上に存在する場合は、RestoreObject リクエストを発行してオブジェクトを復元する必要はありません。代わりに、GetObject 要求を使用してローカル コピーを直接取得できます。

[cols="1a,2a"]
|===
| オブジェクトの状態 | RestoreObjectの動作 


 a| 
オブジェクトはStorageGRIDに取り込まれましたが、ILM によってまだ評価されていません。または、オブジェクトが Cloud Storage Pool にありません。
 a| 
`403 Forbidden` 、  `InvalidObjectState`



 a| 
Cloud Storage Pool 内のオブジェクトですが、まだ取得不可の状態に移行していません
 a| 
`200 OK`変更は行われません。

*注意*: オブジェクトが取得不可能な状態に移行する前に、そのオブジェクトを変更することはできません。 `expiry-date` 。



 a| 
オブジェクトは取得不可能な状態に移行しました
 a| 
`202 Accepted`リクエスト本文で指定された日数の間、オブジェクトの取得可能なコピーを Cloud Storage プールに復元します。この期間が終了すると、オブジェクトは取得不可能な状態に戻されます。

オプションとして、 `Tier`復元ジョブの完了にかかる時間を決定するためのリクエスト要素(`Expedited`、 `Standard` 、 または `Bulk`）。指定しない場合 `Tier`、 `Standard`ティアが使用されます。

*重要*: オブジェクトがS3 Glacier Deep Archiveに移行されている場合、またはクラウドストレージプールがAzure Blobストレージを使用している場合は、 `Expedited`層。次のエラーが返されます `403 Forbidden`、 `InvalidTier` : `Retrieval option is not supported by this storage class` 。



 a| 
回復不可能な状態から復元中のオブジェクト
 a| 
`409 Conflict` 、  `RestoreAlreadyInProgress`



 a| 
オブジェクトがクラウド ストレージ プールに完全に復元されました
 a| 
`200 OK`

*注:* オブジェクトが取得可能な状態に復元された場合、その `expiry-date`新しい値でRestoreObjectリクエストを再発行することにより、 `Days` 。復元日付はリクエストの時刻に応じて更新されます。

|===