---
permalink: s3/put-bucket-consistency-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, PUT bucket consistency request 
summary: PUT Bucket 整合性リクエストを使用すると、バケットに対して実行される操作に適用する整合性を指定できます。 
---
= PUT バケットの一貫性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PUT Bucket 整合性リクエストを使用すると、バケットに対して実行される操作に適用する整合性を指定できます。

デフォルトの一貫性は、新しく作成されたオブジェクトの書き込み後の読み取りを保証するように設定されています。

.開始する前に
この操作を完了するには、s3:PutBucketConsistency 権限を持っているか、アカウント ルートである必要があります。



== 要求

その `x-ntap-sg-consistency`パラメータには次のいずれかの値が含まれている必要があります。

[cols="1a,2a"]
|===
| 一貫性 | 説明 


 a| 
全て
 a| 
すべてのノードがデータを直ちに受信します。そうでない場合、要求は失敗します。



 a| 
strong-global
 a| 
すべてのサイトにわたるすべてのクライアント要求に対して、書き込み後の読み取りの一貫性を保証します。



 a| 
strong-site
 a| 
サイト内のすべてのクライアント要求に対して、書き込み後の読み取り一貫性を保証します。



 a| 
新規書き込み後の読み取り
 a| 
(デフォルト) 新しいオブジェクトに対しては書き込み後の読み取り一貫性を提供し、オブジェクトの更新に対しては最終的な一貫性を提供します。高可用性とデータ保護の保証を提供します。ほとんどの場合に推奨されます。



 a| 
使用可能
 a| 
新しいオブジェクトとオブジェクトの更新の両方に対して最終的な一貫性を提供します。  S3 バケットの場合は、必要な場合にのみ使用してください (たとえば、めったに読み取られないログ値を含むバケットの場合や、存在しないキーに対する HEAD または GET 操作の場合など)。  S3 FabricPoolバケットではサポートされていません。

|===
*注:* 一般的には、「新規書き込み後の読み取り」の一貫性を使用する必要があります。リクエストが正しく機能しない場合は、可能であればアプリケーション クライアントの動作を変更します。または、各 API リクエストの一貫性を指定するようにクライアントを構成します。最後の手段としてのみ、バケット レベルで一貫性を設定します。



== リクエスト例

[listing, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-consistency=strong-global HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
.関連情報
link:consistency-controls.html["一貫性の値"]
