---
permalink: s3/upload-part-copy.html 
sidebar: sidebar 
keywords: UploadPart, UploadPartCopy, multipart uploads, uploads, 
summary: UploadPartCopy 操作は、データ ソースとして既存のオブジェクトからデータをコピーして、オブジェクトの一部をアップロードします。 
---
= UploadPartCopy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UploadPartCopy 操作は、データ ソースとして既存のオブジェクトからデータをコピーして、オブジェクトの一部をアップロードします。

UploadPartCopy 操作は、すべての Amazon S3 REST API 動作で実装されます。予告なく変更されることがあります。

このリクエストは、指定されたオブジェクトデータの読み取りと書き込みを行います。 `x-amz-copy-source-range` StorageGRIDシステム内。

次のリクエスト ヘッダーがサポートされています。

* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-copy-source-if-modified-since`




== サーバー側暗号化のリクエストヘッダー

CreateMultipartUpload リクエストに SSE-C 暗号化を指定した場合は、各 UploadPartCopy リクエストに次のリクエスト ヘッダーも含める必要があります。

* `x-amz-server-side-encryption-customer-algorithm`： 特定 `AES256`。
* `x-amz-server-side-encryption-customer-key`: CreateMultipartUpload リクエストで指定したのと同じ暗号化キーを指定します。
* `x-amz-server-side-encryption-customer-key-MD5`: CreateMultipartUpload リクエストで指定したものと同じ MD5 ダイジェストを指定します。


ソース オブジェクトが顧客提供のキー (SSE-C) を使用して暗号化されている場合は、オブジェクトを復号化してコピーできるように、UploadPartCopy 要求に次の 3 つのヘッダーを含める必要があります。

* `x-amz-copy-source​-server-side​-encryption​-customer-algorithm`： 特定 `AES256`。
* `x-amz-copy-source​-server-side-encryption-customer-key`: ソース オブジェクトの作成時に指定した暗号化キーを指定します。
* `x-amz-copy-source​-server-side-encryption-customer-key-MD5`: ソース オブジェクトの作成時に指定した MD5 ダイジェストを指定します。



CAUTION: 提供された暗号化キーは保存されません。暗号化キーを紛失すると、対応するオブジェクトも失われます。顧客提供のキーを使用してオブジェクトデータを保護する前に、以下の考慮事項を確認してください。link:using-server-side-encryption.html["サーバー側の暗号化を使用する"] 。



== バージョン管理

マルチパートアップロードは、アップロードの開始、アップロードの一覧表示、パーツのアップロード、アップロードされたパーツの組み立て、アップロードの完了という個別の操作で構成されます。  CompleteMultipartUpload 操作が実行されると、オブジェクトが作成され (該当する場合はバージョン管理も行われます)。
