---
permalink: monitor/alerts-reference.html 
sidebar: sidebar 
keywords: alerts reference 
summary: このリファレンスには、グリッド マネージャーに表示されるデフォルトのアラートの一覧を示します。推奨されるアクションは、受信した警告メッセージに記載されています。 
---
= アラート一覧
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このリファレンスには、グリッド マネージャーに表示されるデフォルトのアラートの一覧を示します。推奨されるアクションは、受信した警告メッセージに記載されています。

必要に応じて、システム管理アプローチに適合するカスタムアラート ルールを作成できます。

デフォルトのアラートの一部はlink:commonly-used-prometheus-metrics.html["Prometheusメトリクス"]。



== アプライアンスアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
家電製品の電池切れ
 a| 
アプライアンスのストレージ コントローラのバッテリーの有効期限が切れました。



 a| 
家電製品のバッテリーが故障しました
 a| 
アプライアンスのストレージ コントローラのバッテリーが故障しました。



 a| 
家電製品のバッテリーの学習容量が不十分です
 a| 
アプライアンスのストレージ コントローラのバッテリーの学習容量が不十分です。



 a| 
家電製品のバッテリーの有効期限が近づいています
 a| 
アプライアンスのストレージ コントローラのバッテリーの有効期限が近づいています。



 a| 
家電製品のバッテリーを取り外しました
 a| 
アプライアンスのストレージ コントローラのバッテリーがありません。



 a| 
家電製品のバッテリーが熱すぎる
 a| 
アプライアンスのストレージ コントローラ内のバッテリーが過熱しています。



 a| 
アプライアンスBMC通信エラー
 a| 
ベースボード管理コントローラ (BMC) との通信が失われました。



 a| 
アプライアンスのブートデバイスの障害が検出されました
 a| 
アプライアンスのブート デバイスに問題が検出されました。



 a| 
アプライアンス キャッシュ バックアップ デバイスに障害が発生しました
 a| 
永続キャッシュ バックアップ デバイスに障害が発生しました。



 a| 
アプライアンスのキャッシュバックアップデバイスの容量が不足しています
 a| 
キャッシュバックアップデバイスの容量が不足しています。



 a| 
アプライアンスのキャッシュバックアップデバイスが書き込み保護されています
 a| 
キャッシュ バックアップ デバイスは書き込み保護されています。



 a| 
アプライアンスのキャッシュメモリサイズの不一致
 a| 
アプライアンス内の 2 つのコントローラのキャッシュ サイズが異なります。



 a| 
アプライアンスのCMOSバッテリー障害
 a| 
アプライアンスの CMOS バッテリーに問題が検出されました。



 a| 
アプライアンスのコンピューティング コントローラ シャーシの温度が高すぎます
 a| 
StorageGRIDアプライアンスのコンピューティング コントローラの温度が公称しきい値を超えました。



 a| 
アプライアンスのコンピューティング コントローラの CPU 温度が高すぎます
 a| 
StorageGRIDアプライアンスのコンピューティング コントローラの CPU の温度が公称しきい値を超えました。



 a| 
アプライアンスのコンピューティング コントローラに注意が必要です
 a| 
StorageGRIDアプライアンスのコンピューティング コントローラでハードウェア障害が検出されました。



 a| 
アプライアンスのコンピューティング コントローラの電源 A に問題があります
 a| 
コンピューティング コントローラーの電源 A に問題があります。



 a| 
アプライアンスのコンピューティング コントローラの電源 B に問題があります
 a| 
コンピューティング コントローラーの電源 B に問題があります。



 a| 
アプライアンスのコンピューティング ハードウェア モニター サービスが停止しました
 a| 
ストレージ ハードウェアの状態を監視するサービスが停止しました。



 a| 
アプライアンス DAS ドライブが 1 日あたりの書き込みデータ制限を超えています
 a| 
毎日過剰な量のデータがドライブに書き込まれているため、保証が無効になる可能性があります。



 a| 
アプライアンスDASドライブ障害が検出されました
 a| 
アプライアンス内の直接接続ストレージ (DAS) ドライブに問題が検出されました。



 a| 
アプライアンスDASドライブロケータライトが点灯
 a| 
アプライアンス ストレージ ノード内の 1 つ以上の直接接続ストレージ (DAS) ドライブのドライブ ロケータ ライトがオンになっています。



 a| 
アプライアンスDASドライブの再構築
 a| 
直接接続ストレージ (DAS) ドライブを再構築しています。最近交換または削除/再挿入された場合、この現象が予想されます。



 a| 
機器のファンの故障が検出されました
 a| 
アプライアンス内のファン ユニットに問題が検出されました。



 a| 
アプライアンスのファイバーチャネル障害が検出されました
 a| 
アプライアンスのストレージ コントローラとコンピューティング コントローラ間でファイバー チャネル リンクの問題が検出されました



 a| 
アプライアンスのファイバーチャネルHBAポート障害
 a| 
ファイバー チャネル HBA ポートに障害が発生しているか、または障害が発生しています。



 a| 
アプライアンスのフラッシュキャッシュドライブは最適化されていない
 a| 
SSD キャッシュに使用されるドライブは最適ではありません。



 a| 
アプライアンス相互接続/バッテリーキャニスターを取り外しました
 a| 
インターコネクト/バッテリーキャニスターがありません。



 a| 
アプライアンスのLACPポートが見つかりません
 a| 
StorageGRIDアプライアンス上のポートが LACP ボンドに参加していません。



 a| 
アプライアンスのNIC障害が検出されました
 a| 
アプライアンスのネットワーク インターフェイス カード (NIC) に問題が検出されました。



 a| 
アプライアンス全体の電源が劣化
 a| 
StorageGRIDアプライアンスの電力が推奨動作電圧から外れています。



 a| 
アプライアンス SSD の重大な警告
 a| 
アプライアンス SSD が重大な警告を報告しています。



 a| 
アプライアンスストレージコントローラAの障害
 a| 
StorageGRIDアプライアンスのストレージ コントローラ A に障害が発生しました。



 a| 
アプライアンスストレージコントローラBの障害
 a| 
StorageGRIDアプライアンスのストレージ コントローラ B に障害が発生しました。



 a| 
アプライアンスのストレージ コントローラ ドライブの障害
 a| 
StorageGRIDアプライアンス内の 1 つ以上のドライブに障害が発生しているか、最適ではありません。



 a| 
アプライアンス ストレージ コントローラのハードウェアの問題
 a| 
SANtricityソフトウェアは、 StorageGRIDアプライアンスのコンポーネントについて「注意が必要」と報告しています。



 a| 
アプライアンスストレージコントローラ電源Aの障害
 a| 
StorageGRIDアプライアンスの電源 A が推奨動作電圧から外れています。



 a| 
アプライアンス ストレージ コントローラの電源 B の障害
 a| 
StorageGRIDアプライアンスの電源 B が推奨動作電圧から外れています。



 a| 
アプライアンス ストレージ ハードウェア モニター サービスが停止しました
 a| 
ストレージ ハードウェアの状態を監視するサービスが停止しました。



 a| 
家電収納棚の劣化
 a| 
ストレージ アプライアンスのストレージ シェルフ内のコンポーネントの 1 つのステータスが低下しています。



 a| 
機器の温度超過
 a| 
アプライアンスのストレージ コントローラの公称温度または最大温度を超えました。



 a| 
機器の温度センサーを取り外しました
 a| 
温度センサーが取り外されました。



 a| 
アプライアンスのUEFIセキュアブートエラー
 a| 
アプライアンスは安全に起動されていません。



 a| 
ディスクI/Oが非常に遅い
 a| 
非常に遅いディスク I/O がグリッドのパフォーマンスに影響している可能性があります。



 a| 
ストレージアプライアンスのファンの障害が検出されました
 a| 
アプライアンスのストレージ コントローラ内のファン ユニットに問題が検出されました。



 a| 
ストレージアプライアンスのストレージ接続が低下しました
 a| 
コンピューティング コントローラーとストレージ コントローラー間の 1 つ以上の接続に問題があります。



 a| 
ストレージデバイスにアクセスできません
 a| 
ストレージデバイスにアクセスできません。

|===


== 監査とSyslogアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
監査ログがメモリ内キューに追加されています
 a| 
ノードはローカル syslog サーバーにログを送信できず、メモリ内のキューがいっぱいになっています。



 a| 
外部 syslog サーバ転送エラー
 a| 
ノードはログを外部 syslog サーバーに転送できません。



 a| 
大規模な監査キュー
 a| 
監査メッセージのディスク キューがいっぱいです。この状態に対処しないと、S3 または Swift の操作が失敗する可能性があります。



 a| 
ログはディスク上のキューに追加されています
 a| 
ノードはログを外部 syslog サーバーに転送できず、ディスク上のキューがいっぱいになっています。

|===


== バケットアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
FabricPoolバケットにはサポートされていないバケット整合性設定があります
 a| 
FabricPoolバケットは、サポートされていない使用可能または強力なサイト整合性レベルを使用します。



 a| 
FabricPoolバケットにはサポートされていないバージョン設定があります
 a| 
FabricPoolバケットではバージョン管理または S3 オブジェクト ロックが有効になっていますが、これらはサポートされていません。

|===


== カサンドラアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
Cassandra自動圧縮エラー
 a| 
Cassandra 自動コンパクターでエラーが発生しました。



 a| 
Cassandra の自動コンパクターのメトリクスが古い
 a| 
Cassandra 自動コンパクターを説明するメトリックは古くなっています。



 a| 
Cassandra通信エラー
 a| 
Cassandra サービスを実行するノード間で通信に問題が発生しています。



 a| 
Cassandraの圧縮が過負荷になった
 a| 
Cassandra 圧縮プロセスが過負荷になっています。



 a| 
Cassandra のオーバーサイズ書き込みエラー
 a| 
内部のStorageGRIDプロセスが Cassandra に大きすぎる書き込み要求を送信しました。



 a| 
Cassandraの修復メトリクスが古い
 a| 
Cassandra 修復ジョブを説明するメトリックは古くなっています。



 a| 
カサンドラの修復の進捗が遅い
 a| 
Cassandra データベースの修復の進行が遅いです。



 a| 
Cassandraの修理サービスは利用できません
 a| 
Cassandra 修理サービスは利用できません。



 a| 
Cassandraテーブルの破損
 a| 
Cassandra はテーブルの破損を検出しました。  Cassandra はテーブルの破損を検出すると自動的に再起動します。

|===


== クラウドストレージプールのアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
クラウド ストレージ プールの接続エラー
 a| 
Cloud Storage Pools のヘルスチェックで 1 つ以上の新しいエラーが検出されました。



 a| 
IAM Roles Anywhereエンドエンティティ認証の有効期限
 a| 
IAM Roles Anywhere エンドエンティティ証明書の有効期限が近づいています。

|===


== クロスグリッドレプリケーションアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
クロスグリッドレプリケーションの永続的な障害
 a| 
解決するにはユーザーの介入が必要な、グリッド間レプリケーション エラーが発生しました。



 a| 
クロスグリッドレプリケーションリソースが利用できません
 a| 
リソースが利用できないため、クロスグリッド レプリケーション要求は保留中です。

|===


== DHCPアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
DHCPリースの有効期限が切れました
 a| 
ネットワーク インターフェイスの DHCP リースの有効期限が切れました。



 a| 
DHCPリースがまもなく期限切れになります
 a| 
ネットワーク インターフェイスの DHCP リースがまもなく期限切れになります。



 a| 
DHCPサーバーが利用できません
 a| 
DHCP サーバーが利用できません。

|===


== デバッグとトレースのアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
デバッグパフォーマンスへの影響
 a| 
デバッグ モードを有効にすると、システム パフォーマンスに悪影響が出る可能性があります。



 a| 
トレース構成が有効
 a| 
トレース構成を有効にすると、システム パフォーマンスに悪影響が及ぶ可能性があります。

|===


== 電子メールとAutoSupportアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
AutoSupportメッセージの送信に失敗しました
 a| 
最新のAutoSupportメッセージの送信に失敗しました。



 a| 
ドメイン名解決の失敗
 a| 
StorageGRIDノードはドメイン名を解決できませんでした。



 a| 
メール通知の失敗
 a| 
アラートの電子メール通知を送信できませんでした。



 a| 
SNMP通知エラー
 a| 
トラップの宛先に SNMP 情報通知を送信するときにエラーが発生しました。



 a| 
SSHまたはコンソールログインが検出されました
 a| 
過去 24 時間以内に、ユーザーが Web コンソールまたは SSH を使用してログインしました。

|===


== 消失訂正符号（EC）アラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
ECリバランスの失敗
 a| 
EC 再バランス手順が失敗したか、停止しました。



 a| 
EC修復失敗
 a| 
EC データの修復ジョブが失敗したか、停止しました。



 a| 
EC修理が行き詰まる
 a| 
EC データの修復作業が停止しました。



 a| 
消失訂正符号化フラグメント検証エラー
 a| 
消失訂正符号化されたフラグメントは検証できなくなります。破損したフラグメントは修復されない可能性があります。

|===


== 証明書の有効期限の警告

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
管理プロキシ CA 証明書の有効期限
 a| 
管理プロキシ サーバーの CA バンドル内の 1 つ以上の証明書の有効期限が近づいています。



 a| 
クライアント証明書の有効期限
 a| 
1 つ以上のクライアント証明書の有効期限が近づいています。



 a| 
S3 および Swift のグローバル サーバー証明書の有効期限
 a| 
S3 および Swift のグローバル サーバー証明書の有効期限が近づいています。



 a| 
ロードバランサエンドポイント証明書の有効期限
 a| 
1 つ以上のロード バランサ エンドポイント証明書の有効期限が近づいています。



 a| 
管理インターフェースのサーバー証明書の有効期限
 a| 
管理インターフェイスに使用されているサーバー証明書の有効期限が近づいています。



 a| 
外部 syslog CA 証明書の有効期限
 a| 
外部 syslog サーバー証明書の署名に使用される証明機関 (CA) 証明書の有効期限が近づいています。



 a| 
外部 syslog クライアント証明書の有効期限
 a| 
外部 syslog サーバーのクライアント証明書の有効期限が近づいています。



 a| 
外部 syslog サーバー証明書の有効期限
 a| 
外部 syslog サーバーによって提示されたサーバー証明書の有効期限が近づいています。

|===


== グリッドネットワークアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
グリッドネットワークMTUの不一致
 a| 
グリッド ネットワーク インターフェイス (eth0) の MTU 設定は、グリッド内のノード間で大きく異なります。

|===


== グリッドフェデレーションアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
グリッドフェデレーション証明書の有効期限
 a| 
1 つ以上のグリッド フェデレーション証明書の有効期限が近づいています。



 a| 
グリッドフェデレーション接続失敗
 a| 
ローカル グリッドとリモート グリッド間のグリッド フェデレーション接続が機能していません。

|===


== 使用率が高い、または遅延が大きい場合のアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
Javaヒープ使用量が多い
 a| 
Java ヒープスペースの高い割合が使用されています。



 a| 
メタデータクエリのレイテンシが高い
 a| 
Cassandra メタデータ クエリの平均時間が長すぎます。

|===


== アイデンティティ連携アラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
アイデンティティ連携の同期に失敗しました
 a| 
アイデンティティ ソースからフェデレーション グループとユーザーを同期できません。



 a| 
テナントの ID フェデレーション同期の失敗
 a| 
テナントによって構成された ID ソースからフェデレーション グループとユーザーを同期できません。

|===


== 情報ライフサイクル管理（ILM）アラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
ILMの配置は達成不可能
 a| 
特定のオブジェクトに対して、ILM ルール内の配置指示を実行できません。



 a| 
ILMスキャン率が低い
 a| 
ILM スキャン レートは 100 オブジェクト/秒未満に設定されています。

|===


== キー管理サーバー（KMS）アラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
KMS CA証明書の有効期限
 a| 
キー管理サーバー (KMS) 証明書の署名に使用される証明機関 (CA) 証明書の有効期限が近づいています。



 a| 
KMSクライアント証明書の有効期限
 a| 
キー管理サーバーのクライアント証明書の有効期限が近づいています



 a| 
KMS構成の読み込みに失敗しました
 a| 
キー管理サーバーの構成は存在しますが、ロードに失敗しました。



 a| 
KMS接続エラー
 a| 
アプライアンス ノードは、そのサイトのキー管理サーバーに接続できませんでした。



 a| 
KMS暗号化キー名が見つかりません
 a| 
構成されたキー管理サーバーには、指定された名前と一致する暗号化キーがありません。



 a| 
KMS暗号化キーのローテーションに失敗しました
 a| 
すべてのアプライアンス ボリュームは正常に復号化されましたが、1 つ以上のボリュームを最新のキーにローテーションできませんでした。



 a| 
KMSが設定されていません
 a| 
このサイトにはキー管理サーバーが存在しません。



 a| 
KMS キーがアプライアンス ボリュームの暗号化に失敗しました
 a| 
ノード暗号化が有効になっているアプライアンス上の 1 つ以上のボリュームを、現在の KMS キーで復号化できませんでした。



 a| 
KMSサーバー証明書の有効期限
 a| 
キー管理サーバー (KMS) で使用されるサーバー証明書の有効期限が近づいています。



 a| 
KMSサーバーの接続障害
 a| 
アプライアンス ノードは、そのサイトのキー管理サーバー クラスター内の 1 つ以上のサーバーに接続できませんでした。

|===


== ロードバランサーアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
ゼロリクエストロードバランサ接続の昇格
 a| 
リクエストを実行せずに切断されたロード バランサー エンドポイントへの接続の割合が増加しました。

|===


== ローカルクロックオフセットアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
ローカルクロックの大きな時間オフセット
 a| 
ローカル クロックとネットワーク タイム プロトコル (NTP) の時間間のオフセットが大きすぎます。

|===


== メモリ不足または空き容量不足の警告

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
監査ログのディスク容量が少ない
 a| 
監査ログに使用できるスペースが少なくなっています。この状態に対処しないと、S3 または Swift の操作が失敗する可能性があります。



 a| 
利用可能なノードメモリが少ない
 a| 
ノード上で使用可能な RAM の量が少ない。



 a| 
ストレージプールの空き容量が少ない
 a| 
ストレージ ノード内のオブジェクト データを保存するために使用できるスペースが少なくなっています。



 a| 
インストールされたノードのメモリが少ない
 a| 
ノードにインストールされているメモリの量が少ないです。



 a| 
メタデータの保存容量が少ない
 a| 
オブジェクト メタデータを保存するために使用できるスペースが少なくなっています。



 a| 
低メトリクスディスク容量
 a| 
メトリック データベースに使用できるスペースが少なくなっています。



 a| 
低オブジェクトデータストレージ
 a| 
オブジェクト データを保存するために使用できるスペースが少なくなっています。



 a| 
読み取り専用の透かしの上書きが少ない
 a| 
ストレージ ボリュームのソフト読み取り専用ウォーターマーク オーバーライドが、ストレージ ノードの最小最適化ウォーターマークよりも小さくなっています。



 a| 
ルートディスク容量が少ない
 a| 
ルート ディスクの使用可能な容量が少なくなっています。



 a| 
システムデータ容量が低い
 a| 
/var/local に使用可能なスペースが少なくなっています。この状態に対処しないと、S3 または Swift の操作が失敗する可能性があります。



 a| 
tmpディレクトリの空き容量が少ない
 a| 
/tmp ディレクトリの使用可能なスペースが少なくなっています。

|===


== ノードまたはノードネットワークのアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
管理ネットワーク受信使用状況
 a| 
管理ネットワークの受信使用率が高くなっています。



 a| 
管理ネットワーク送信使用量
 a| 
管理ネットワークの送信使用量が高くなっています。



 a| 
ファイアウォールの設定失敗
 a| 
ファイアウォール構成の適用に失敗しました。



 a| 
フォールバックモードの管理インターフェースエンドポイント
 a| 
すべての管理インターフェースのエンドポイントが、長い間デフォルト ポートにフォールバックしています。



 a| 
ノードネットワーク接続エラー
 a| 
ノード間でデータを転送中にエラーが発生しました。



 a| 
ノードネットワーク受信フレームエラー
 a| 
ノードが受信したネットワーク フレームのかなりの割合にエラーがありました。



 a| 
ノードがNTPサーバーと同期していません
 a| 
ノードはネットワーク タイム プロトコル (NTP) サーバーと同期していません。



 a| 
ノードがNTPサーバーにロックされていません
 a| 
ノードはネットワーク タイム プロトコル (NTP) サーバーにロックされていません。



 a| 
アプライアンス以外のノードのネットワークがダウンしています
 a| 
1 つ以上のネットワーク デバイスがダウンしているか、切断されています。



 a| 
管理ネットワーク上のサービス アプライアンスのリンクがダウンしています
 a| 
管理ネットワーク (eth1) へのアプライアンス インターフェイスがダウンしているか、切断されています。



 a| 
管理ネットワーク ポート 1 のサービス アプライアンス リンクがダウンしました
 a| 
アプライアンスの管理ネットワーク ポート 1 がダウンしているか、切断されています。



 a| 
クライアントネットワーク上のサービスアプライアンスのリンクがダウンしています
 a| 
クライアント ネットワーク (eth2) へのアプライアンス インターフェイスがダウンしているか、切断されています。



 a| 
ネットワーク ポート 1 のサービス アプライアンス リンクがダウンしました
 a| 
アプライアンスのネットワーク ポート 1 がダウンしているか、切断されています。



 a| 
ネットワーク ポート 2 のサービス アプライアンス リンクがダウンしました
 a| 
アプライアンスのネットワーク ポート 2 がダウンしているか、切断されています。



 a| 
ネットワーク ポート 3 のサービス アプライアンス リンクがダウンしました
 a| 
アプライアンスのネットワーク ポート 3 がダウンしているか、切断されています。



 a| 
ネットワーク ポート 4 のサービス アプライアンス リンクがダウンしました
 a| 
アプライアンスのネットワーク ポート 4 がダウンしているか、切断されています。



 a| 
管理ネットワーク上のストレージアプライアンスのリンクがダウンしました
 a| 
管理ネットワーク (eth1) へのアプライアンス インターフェイスがダウンしているか、切断されています。



 a| 
管理ネットワークポート1のストレージアプライアンスのリンクがダウンしました
 a| 
アプライアンスの管理ネットワーク ポート 1 がダウンしているか、切断されています。



 a| 
クライアントネットワーク上のストレージアプライアンスのリンクがダウンしています
 a| 
クライアント ネットワーク (eth2) へのアプライアンス インターフェイスがダウンしているか、切断されています。



 a| 
ネットワーク ポート 1 のストレージ アプライアンスのリンクがダウンしました
 a| 
アプライアンスのネットワーク ポート 1 がダウンしているか、切断されています。



 a| 
ネットワークポート2のストレージアプライアンスのリンクダウン
 a| 
アプライアンスのネットワーク ポート 2 がダウンしているか、切断されています。



 a| 
ネットワークポート3のストレージアプライアンスのリンクがダウンしました
 a| 
アプライアンスのネットワーク ポート 3 がダウンしているか、切断されています。



 a| 
ネットワークポート4のストレージアプライアンスのリンクダウン
 a| 
アプライアンスのネットワーク ポート 4 がダウンしているか、切断されています。



 a| 
ストレージノードが望ましいストレージ状態ではありません
 a| 
ストレージノード上のLDRサービスは、内部エラーまたはボリューム関連の問題のため、目的の状態に移行できません。



 a| 
TCP接続の使用
 a| 
このノード上の TCP 接続の数は、追跡できる最大数に近づいています。



 a| 
ノードと通信できません
 a| 
1 つ以上のサービスが応答しないか、ノードにアクセスできません。



 a| 
予期しないノードの再起動
 a| 
過去 24 時間以内にノードが予期せず再起動しました。

|===


== オブジェクトアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
オブジェクトの存在チェックに失敗しました
 a| 
オブジェクト存在チェックジョブが失敗しました。



 a| 
オブジェクトの存在チェックが停止しました
 a| 
オブジェクト存在チェックジョブが停止しました。



 a| 
失われた物
 a| 
1 つ以上のオブジェクトがグリッドから失われました。



 a| 
S3 PUT オブジェクトのサイズが大きすぎます
 a| 
クライアントが S3 のサイズ制限を超える PUT Object 操作を試行しています。



 a| 
未確認の破損オブジェクトが検出されました
 a| 
複製オブジェクト ストレージ内に、複製オブジェクトとして識別できないファイルが見つかりました。

|===


== プラットフォームサービスアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
プラットフォーム サービスの保留中のリクエスト容量が不足しています
 a| 
保留中のリクエストのプラットフォーム サービスの数が容量に近づいています。



 a| 
プラットフォームサービスは利用できません
 a| 
RSM サービスを備えたストレージ ノードがサイトで実行中または使用可能数が少なすぎます。

|===


== ストレージボリュームアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
ストレージ容量に注意が必要
 a| 
ストレージ ボリュームがオフラインであり、注意が必要です。



 a| 
ストレージボリュームを復元する必要があります
 a| 
ストレージ ボリュームが回復されたため、復元する必要があります。



 a| 
ストレージボリュームがオフライン
 a| 
ストレージ ボリュームが 5 分以上オフラインになっています。



 a| 
ストレージボリュームの再マウントを試行しました
 a| 
ストレージ ボリュームがオフラインになったため、自動再マウントがトリガーされました。これは、ドライブの問題またはファイルシステムのエラーを示している可能性があります。



 a| 
ボリュームの復元で複製されたデータの修復を開始できませんでした
 a| 
修復されたボリュームの複製されたデータの修復を自動的に開始できませんでした。

|===


== StorageGRIDサービスアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
バックアップ設定を使用したnginxサービス
 a| 
nginx サービスの構成が無効です。以前の構成が現在使用されています。



 a| 
バックアップ構成を使用した nginx-gw サービス
 a| 
nginx-gw サービスの構成が無効です。以前の構成が現在使用されています。



 a| 
FIPSを無効にするには再起動が必要です
 a| 
セキュリティ ポリシーでは FIPS モードは必要ありませんが、 NetApp暗号化セキュリティ モジュールが有効になっています。



 a| 
FIPSを有効にするには再起動が必要です
 a| 
セキュリティ ポリシーでは FIPS モードが必要ですが、 NetApp暗号化セキュリティ モジュールが無効になっています。



 a| 
バックアップ構成を使用した SSH サービス
 a| 
SSH サービスの構成が無効です。以前の構成が現在使用されています。

|===


== テナントアラート

[cols="1a,2a"]
|===
| アラート名 | 説明 


 a| 
テナントのクォータ使用量が高い
 a| 
割り当て領域の高い割合が使用されています。このルールは、通知が多すぎる可能性があるため、デフォルトでは無効になっています。

|===