---
permalink: monitor/configuring-snmp-agent.html 
sidebar: sidebar 
keywords: snmp agent, mib, trap, inform 
summary: 読み取り専用の MIB アクセスと通知にサードパーティの SNMP 管理システムを使用するようにStorageGRID SNMP エージェントを設定できます。 
---
= SNMPエージェントを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
読み取り専用の MIB アクセスと通知にサードパーティの SNMP 管理システムを使用するようにStorageGRID SNMP エージェントを設定できます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["ルートアクセス権限"]。


.タスク概要
StorageGRID SNMP エージェントは、SNMPv1、SNMPv2c、および SNMPv3 をサポートします。エージェントを 1 つ以上のバージョンに対して構成できます。  SNMPv3 では、ユーザー セキュリティ モデル (USM) 認証のみがサポートされます。

グリッド内のすべてのノードは同じ SNMP 構成を使用します。



== 基本設定を指定する

最初のステップとして、 StorageGRID SMNP エージェントを有効にし、基本情報を提供します。

.手順
. *構成* > *監視* > *SNMP エージェント* を選択します。
+
SNMP エージェント ページが表示されます。

. すべてのグリッド ノードで SNMP エージェントを有効にするには、[*SNMP を有効にする*] チェックボックスをオンにします。
. 基本設定セクションに次の情報を入力します。
+
[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
システム連絡先
 a| 
オプション。  StorageGRIDシステムの主な連絡先。SNMP メッセージでは sysContact として返されます。

システム連絡先は通常、電子メール アドレスです。この値は、 StorageGRIDシステム内のすべてのノードに適用されます。  *システム連絡先* は最大 255 文字までです。



 a| 
システムの場所
 a| 
オプション。  StorageGRIDシステムの場所。SNMP メッセージでは sysLocation として返されます。

システムの場所には、 StorageGRIDシステムの場所を識別するのに役立つ任意の情報を指定できます。たとえば、施設の住所を使用する場合があります。この値は、 StorageGRIDシステム内のすべてのノードに適用されます。  *システムの場所* は最大 255 文字までです。



 a| 
SNMPエージェント通知を有効にする
 a| 
** 選択すると、 StorageGRID SNMP エージェントはトラップ通知とインフォーム通知を送信します。
** 選択されていない場合、SNMP エージェントは読み取り専用の MIB アクセスをサポートしますが、SNMP 通知は送信しません。




 a| 
認証トラップを有効にする
 a| 
選択すると、 StorageGRID SNMP エージェントは、不適切に認証されたプロトコル メッセージを受信した場合に認証トラップを送信します。

|===




== コミュニティ文字列を入力してください

SNMPv1 または SNMPv2c を使用する場合は、コミュニティ文字列セクションを入力します。

管理システムがStorageGRID MIB を照会すると、コミュニティ文字列が送信されます。コミュニティ文字列がここで指定された値のいずれかと一致する場合、SNMP エージェントは管理システムに応答を送信します。

.手順
. *読み取り専用コミュニティ* の場合は、オプションでコミュニティ文字列を入力して、IPv4 および IPv6 エージェント アドレスでの読み取り専用 MIB アクセスを許可します。
+

TIP: StorageGRIDシステムのセキュリティを確保するには、コミュニティ文字列として「public」を使用しないでください。このフィールドを空白のままにすると、SNMP エージェントはコミュニティ文字列としてStorageGRIDシステムのグリッド ID を使用します。

+
各コミュニティ文字列は最大 32 文字で、空白文字を含めることはできません。

. 追加の文字列を追加するには、「*別のコミュニティ文字列を追加*」を選択します。
+
最大 5 つの文字列が許可されます。





== [[select_trap_destination]]トラップ先を作成する

[その他の構成] セクションの [トラップの送信先] タブを使用して、 StorageGRIDトラップまたはインフォーム通知の 1 つ以上の送信先を定義します。 SNMP エージェントを有効にして [*保存*] を選択すると、アラートがトリガーされたときにStorageGRID は定義済みの各宛先に通知を送信します。サポートされている MIB-II エンティティ (ifDown や coldStart など) についても標準通知が送信されます。

.手順
. *デフォルトのトラップ コミュニティ* フィールドに、必要に応じて、SNMPv1 または SNMPv2 トラップの宛先に使用するデフォルトのコミュニティ文字列を入力します。
+
必要に応じて、特定のトラップの宛先を定義するときに、異なる (「カスタム」) コミュニティ文字列を指定できます。

+
*デフォルトのトラップ コミュニティ* は最大 32 文字で、空白文字を含めることはできません。

. トラップの宛先を追加するには、[*作成*] を選択します。
. このトラップの宛先に使用する SNMP バージョンを選択します。
. 選択したバージョンのトラップ宛先の作成フォームに入力します。
+
[role="tabbed-block"]
====
.SNMPv1
--
バージョンとして SNMPv1 を選択した場合は、これらのフィールドに入力します。

[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
タイプ
 a| 
SNMPv1 の場合はトラップである必要があります。



 a| 
ホスト
 a| 
トラップを受信するための IPv4 または IPv6 アドレス、あるいは完全修飾ドメイン名 (FQDN)。



 a| 
ポート
 a| 
別の値を使用する必要がない限り、SNMP トラップの標準ポートである 162 を使用します。



 a| 
プロトコル
 a| 
TCP を使用する必要がない限り、標準の SNMP トラップ プロトコルである UDP を使用します。



 a| 
コミュニティ文字列
 a| 
デフォルトのトラップ コミュニティが指定されている場合はそれを使用するか、このトラップの宛先にカスタム コミュニティ文字列を入力します。

カスタム コミュニティ文字列は最大 32 文字までで、空白を含めることはできません。

|===
--
.SNMPv2c
--
バージョンとして SNMPv2c を選択した場合は、これらのフィールドに入力します。

[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
タイプ
 a| 
宛先がトラップまたはインフォームに使用されるかどうか。



 a| 
ホスト
 a| 
トラップを受信する IPv4 または IPv6 アドレスまたは FQDN。



 a| 
ポート
 a| 
別の値を使用する必要がない限り、SNMP トラップの標準ポートである 162 を使用します。



 a| 
プロトコル
 a| 
TCP を使用する必要がない限り、標準の SNMP トラップ プロトコルである UDP を使用します。



 a| 
コミュニティ文字列
 a| 
デフォルトのトラップ コミュニティが指定されている場合はそれを使用するか、このトラップの宛先にカスタム コミュニティ文字列を入力します。

カスタム コミュニティ文字列は最大 32 文字までで、空白を含めることはできません。

|===
--
.SNMPv3
--
バージョンとして SNMPv3 を選択した場合は、これらのフィールドに入力します。

[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
タイプ
 a| 
宛先がトラップまたはインフォームに使用されるかどうか。



 a| 
ホスト
 a| 
トラップを受信する IPv4 または IPv6 アドレスまたは FQDN。



 a| 
ポート
 a| 
別の値を使用する必要がない限り、SNMP トラップの標準ポートである 162 を使用します。



 a| 
プロトコル
 a| 
TCP を使用する必要がない限り、標準の SNMP トラップ プロトコルである UDP を使用します。



 a| 
USMユーザ
 a| 
認証に使用される USM ユーザー。

** *Trap* を選択した場合は、権限のあるエンジン ID を持たない USM ユーザーのみが表示されます。
** *Inform* を選択した場合は、権限のあるエンジン ID を持つ USM ユーザーのみが表示されます。
** ユーザーが表示されない場合:
+
... トラップの宛先を作成して保存します。
... へ移動<<create-usm-users,USMユーザーを作成する>>ユーザーを作成します。
... トラップの宛先タブに戻り、テーブルから保存した宛先を選択して、*編集*を選択します。
... ユーザーを選択します。




|===
--
====
. *作成*を選択します。
+
トラップの宛先が作成され、テーブルに追加されます。





== エージェントアドレスを作成する

必要に応じて、[その他の構成] セクションの [エージェント アドレス] タブを使用して、1 つ以上の「リスニング アドレス」を指定します。これらは、SNMP エージェントがクエリを受信できるStorageGRIDアドレスです。

エージェント アドレスを設定しない場合、デフォルトのリスニング アドレスはすべてのStorageGRIDネットワーク上の UDP ポート 161 になります。

.手順
. *作成*を選択します。
. 以下の情報を入力してください。
+
[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
インターネットプロトコル
 a| 
このアドレスが IPv4 を使用するか IPv6 を使用するかを指定します。

デフォルトでは、SNMP は IPv4 を使用します。



 a| 
転送プロトコル
 a| 
このアドレスが UDP を使用するか TCP を使用するかを指定します。

デフォルトでは、SNMP は UDP を使用します。



 a| 
StorageGRIDネットワーク
 a| 
エージェントがリッスンするStorageGRIDネットワーク。

** グリッド、管理、およびクライアント ネットワーク: SNMP エージェントは、3 つのネットワークすべてでクエリをリッスンします。
** グリッド ネットワーク
** 管理者ネットワーク
** クライアント ネットワーク
+
*注意*: 安全でないデータにクライアント ネットワークを使用し、クライアント ネットワークのエージェント アドレスを作成する場合は、SNMP トラフィックも安全でないことに注意してください。





 a| 
ポート
 a| 
オプションで、SNMP エージェントがリッスンするポート番号。

SNMP エージェントのデフォルトの UDP ポートは 161 ですが、未使用のポート番号を入力できます。

*注*: SNMP エージェントを保存すると、 StorageGRID は内部ファイアウォール上のエージェント アドレス ポートを自動的に開きます。外部ファイアウォールがこれらのポートへのアクセスを許可していることを確認する必要があります。

|===
. *作成*を選択します。
+
エージェント アドレスが作成され、テーブルに追加されます。





== [[create-usm-users]]USMユーザーを作成する

SNMPv3 を使用している場合は、[その他の構成] セクションの [USM ユーザー] タブを使用して、MIB を照会したり、トラップやインフォームを受信したりする権限を持つ USM ユーザーを定義します。


NOTE: SNMPv3 _inform_ 宛先には、エンジン ID を持つユーザーが必要です。  SNMPv3 _trap_ の宛先には、エンジン ID を持つユーザーを指定できません。

SNMPv1 または SNMPv2c のみを使用している場合、これらの手順は適用されません。

.手順
. *作成*を選択します。
. 以下の情報を入力してください。
+
[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
ユーザー名
 a| 
この USM ユーザーの一意の名前。

ユーザー名は最大 32 文字までで、空白文字を含めることはできません。ユーザーの作成後はユーザー名を変更できません。



 a| 
読み取り専用MIBアクセス
 a| 
選択すると、このユーザーには MIB への読み取り専用アクセス権が与えられます。



 a| 
権限のあるエンジンID
 a| 
このユーザーが通知先で使用される場合、このユーザーの権限のあるエンジン ID。

スペースなしで 10 ～ 64 文字 (5 ～ 32 バイト) の 16 進文字を入力します。この値は、通知のトラップ送信先で選択される USM ユーザーに必要です。この値は、トラップのトラップ送信先で選択される USM ユーザーには許可されません。

*注意*: 読み取り専用 MIB アクセスを持つ USM ユーザーはエンジン ID を持つことができないため、*読み取り専用 MIB アクセス* を選択した場合、このフィールドは表示されません。



 a| 
セキュリティレベル
 a| 
USM ユーザーのセキュリティ レベル:

** *authPriv*: このユーザーは認証とプライバシー (暗号化) を使用して通信します。認証プロトコルとパスワード、およびプライバシー プロトコルとパスワードを指定する必要があります。
** *authNoPriv*: このユーザーは認証あり、プライバシーなし (暗号化なし) で通信します。認証プロトコルとパスワードを指定する必要があります。




 a| 
認証プロトコル
 a| 
常に、唯一サポートされているプロトコルである SHA (HMAC-SHA-96) に設定されます。



 a| 
パスワード
 a| 
このユーザーが認証に使用するパスワード。



 a| 
プライバシー プロトコル
 a| 
*authPriv* を選択し、常に AES に設定した場合にのみ表示されます。AES は、唯一サポートされているプライバシー プロトコルです。



 a| 
パスワード
 a| 
*authPriv* を選択した場合にのみ表示されます。このユーザーがプライバシーのために使用されるパスワード。

|===
. *作成*を選択します。
+
USM ユーザーが作成され、テーブルに追加されます。

. SNMP エージェントの設定が完了したら、[*保存*] を選択します。
+
新しい SNMP エージェント構成がアクティブになります。


