---
permalink: monitor/monitoring-information-lifecycle-management.html 
sidebar: sidebar 
keywords: lifecycle management, lifecycle, monitoring, ILM, information lifecycle management 
summary: '情報ライフサイクル管理 (ILM) システムは、グリッドに保存されているすべてのオブジェクトのデータ管理を提供します。グリッドが現在の負荷を処理できるかどうか、またはさらにリソースが必要かどうかを把握するには、ILM 操作を監視する必要があります。' 
---
= 情報ライフサイクル管理を監視する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
情報ライフサイクル管理 (ILM) システムは、グリッドに保存されているすべてのオブジェクトのデータ管理を提供します。グリッドが現在の負荷を処理できるかどうか、またはさらにリソースが必要かどうかを把握するには、ILM 操作を監視する必要があります。

.タスク概要
StorageGRIDシステムは、アクティブな ILM ポリシーを適用してオブジェクトを管理します。  ILM ポリシーと関連する ILM ルールによって、作成されるコピーの数、作成されるコピーの種類、コピーの配置場所、および各コピーが保持される期間が決まります。

オブジェクトの取り込みやその他のオブジェクト関連のアクティビティによって、 StorageGRID がILM を評価できる速度が超過する可能性があり、その結果、ILM 配置指示をほぼリアルタイムで実行できないオブジェクトがシステムによってキューに入れられることになります。  StorageGRID がクライアントのアクションに対応しているかどうかを監視する必要があります。



== グリッドマネージャーダッシュボードタブを使用する

.手順
Grid Manager ダッシュボードの ILM タブを使用して、ILM 操作を監視します。

. グリッド マネージャーにSign in。
. ダッシュボードから ILM タブを選択し、ILM キュー (オブジェクト) カードと ILM 評価レート カードの値をメモします。
+
ダッシュボードの ILM キュー (オブジェクト) カードに一時的な急増が発生することが予想されます。しかし、キューが増加し続け、減少しない場合は、グリッドが効率的に動作するために、より多くのリソース（ストレージ ノードを増やすか、ILM ポリシーによってオブジェクトがリモートの場所に配置されている場合はより多くのネットワーク帯域幅）が必要になります。





== NODESページを使用する

.手順
さらに、*NODES* ページを使用して ILM キューを調査します。


NOTE: *NODES* ページのチャートは、将来のStorageGRIDリリースで対応するダッシュボード カードに置き換えられます。

. 「NODES」を選択します。
. *_グリッド名_* > *ILM* を選択します。
. ILM キュー グラフの上にカーソルを置くと、特定の時点での次の属性の値が表示されます。
+
** *キューに入れられたオブジェクト (クライアント操作から)*: クライアント操作 (取り込みなど) により ILM 評価を待機しているオブジェクトの合計数。
** *キューに入れられたオブジェクト (すべての操作から)*: ILM 評価を待機しているオブジェクトの合計数。
** *スキャン レート (オブジェクト/秒)*: グリッド内のオブジェクトがスキャンされ、ILM のキューに追加されるレート。
** *評価レート (オブジェクト/秒)*: グリッド内の ILM ポリシーに対してオブジェクトが評価される現在のレート。


. ILM キュー セクションで、次の属性を確認します。
+

NOTE: ILM キュー セクションはグリッドのみに含まれます。この情報は、サイトまたはストレージ ノードの ILM タブには表示されません。

+
** *スキャン期間 - 推定*: すべてのオブジェクトの完全な ILM スキャンを完了するのにかかる推定時間。
+

NOTE: 完全スキャンでは、すべてのオブジェクトに ILM が適用されていることが保証されるわけではありません。

** *試行された修復*: 複製されたデータに対して試行されたオブジェクト修復操作の合計数。このカウントは、ストレージ ノードが高リスクのオブジェクトの修復を試みるたびに増加します。グリッドが混雑している場合は、リスクの高い ILM 修復が優先されます。
+

NOTE: 修復後にレプリケーションが失敗した場合、同じオブジェクトの修復が再度増加する可能性があります。



+
これらの属性は、ストレージ ノード ボリュームのリカバリの進行状況を監視するときに役立ちます。修復の試行回数の増加が止まり、完全スキャンが完了した場合、修復は完了したと考えられます。


