---
permalink: monitor/monitoring-put-and-get-performance.html 
sidebar: sidebar 
keywords: put, get, performance 
summary: オブジェクトの保存や取得などの特定の操作のパフォーマンスを監視して、さらに調査が必要となる可能性のある変更を特定することができます。 
---
= PUTとGETのパフォーマンスを監視する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトの保存や取得などの特定の操作のパフォーマンスを監視して、さらに調査が必要となる可能性のある変更を特定することができます。

.タスク概要
PUT および GET のパフォーマンスを監視するには、ワークステーションから直接 S3 コマンドを実行するか、オープンソースの S3tester アプリケーションを使用します。これらの方法を使用すると、クライアント アプリケーションの問題や外部ネットワークの問題など、 StorageGRIDの外部の要因に左右されずにパフォーマンスを評価できます。

PUT および GET 操作のテストを実行するときは、次のガイドラインに従います。

* 通常グリッドに取り込むオブジェクトと同等のオブジェクト サイズを使用します。
* ローカル サイトとリモート サイトの両方に対して操作を実行します。


メッセージlink:../audit/index.html["監査ログ"]特定の操作を実行するために必要な合計時間を示します。たとえば、S3 GET リクエストの合計処理時間を確認するには、SGET 監査メッセージの TIME 属性の値を確認します。また、次のS3操作の監査メッセージにはTIME属性が含まれています: DELETE、GET、HEAD、メタデータ更新、POST、PUT

結果を分析するときは、リクエストを満たすのに必要な平均時間と、達成できる全体的なスループットを確認します。同じテストを定期的に繰り返し、結果を記録して、調査が必要な傾向を特定できるようにします。

* あなたはできる https://github.com/s3tester["githubからS3testerをダウンロードする"^]。

