---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: ロード バランサを使用してStorageGRIDへのクライアント接続を管理している場合は、システムを最初に構成した後、および構成の変更や拡張を実行した後に、ロード バランシング操作を監視する必要があります。 
---
= 負荷分散操作を監視する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロード バランサを使用してStorageGRIDへのクライアント接続を管理している場合は、システムを最初に構成した後、および構成の変更や拡張を実行した後に、ロード バランシング操作を監視する必要があります。

.タスク概要
管理ノードまたはゲートウェイ ノード上のロード バランサ サービス、または外部のサードパーティ ロード バランサを使用して、クライアント要求を複数のストレージ ノードに分散できます。

負荷分散を構成した後、オブジェクトの取り込みおよび取得操作がストレージ ノード間で均等に分散されていることを確認する必要があります。要求が均等に分散されるため、 StorageGRID は負荷がかかってもクライアントの要求に応答し続け、クライアントのパフォーマンスを維持することができます。

ゲートウェイ ノードまたは管理ノードの高可用性 (HA) グループをアクティブ バックアップ モードで構成した場合、グループ内の 1 つのノードのみがクライアント要求をアクティブに分散します。

詳細については、以下を参照してください。 link:../admin/configuring-client-connections.html["S3クライアント接続を構成する"] 。

.手順
. S3 クライアントがロード バランサ サービスを使用して接続する場合は、管理ノードまたはゲートウェイ ノードが期待どおりにトラフィックをアクティブに分散していることを確認します。
+
.. 「NODES」を選択します。
.. ゲートウェイ ノードまたは管理ノードを選択します。
.. *概要* タブで、ノード インターフェイスが HA グループに属しているかどうか、およびノード インターフェイスにプライマリの役割があるかどうかを確認します。
+
プライマリの役割を持つノードと HA グループに属していないノードは、クライアントへのリクエストをアクティブに分散する必要があります。

.. クライアントリクエストをアクティブに分散する各ノードに対して、link:viewing-load-balancer-tab.html["ロードバランサタブ"] 。
.. 過去 1 週間のロード バランサ要求トラフィックのグラフを確認して、ノードが要求をアクティブに分散していることを確認します。
+
アクティブ バックアップ HA グループ内のノードは、随時バックアップ ロールを引き受ける場合があります。その間、ノードはクライアントの要求を分散しません。

.. 過去 1 週間のロード バランサの受信要求率のグラフを確認して、ノードのオブジェクト スループットを確認します。
.. StorageGRIDシステム内の各管理ノードまたはゲートウェイ ノードに対してこれらの手順を繰り返します。
.. 必要に応じて、トラフィック分類ポリシーを使用して、ロード バランサ サービスによって処理されるトラフィックのより詳細な分析を表示します。


. これらの要求がストレージ ノードに均等に分散されていることを確認します。
+
.. *_Storage Node_* > *LDR* > *HTTP* を選択します。
.. *現在確立されている着信セッション*の数を確認します。
.. グリッド内の各ストレージ ノードに対して繰り返します。
+
セッション数は、すべてのストレージ ノード間でほぼ等しくなる必要があります。




