---
permalink: monitor/reviewing-audit-messages.html 
sidebar: sidebar 
keywords: how to review audit messages, how to view audit messages 
summary: 監査メッセージは、 StorageGRIDシステムの詳細な操作をより深く理解するのに役立ちます。監査ログを使用して、問題のトラブルシューティングやパフォーマンスの評価を行うことができます。 
---
= 監査メッセージを確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査メッセージは、 StorageGRIDシステムの詳細な操作をより深く理解するのに役立ちます。監査ログを使用して、問題のトラブルシューティングやパフォーマンスの評価を行うことができます。

通常のシステム操作中、すべてのStorageGRIDサービスは次のように監査メッセージを生成します。

* システム監査メッセージは、監査システム自体、グリッド ノードの状態、システム全体のタスク アクティビティ、およびサービス バックアップ操作に関連しています。
* オブジェクト ストレージ監査メッセージは、オブジェクトの保存と取得、グリッド ノード間の転送、検証など、 StorageGRID内のオブジェクトの保存と管理に関連しています。
* S3 クライアント アプリケーションがオブジェクトの作成、変更、または取得を要求すると、クライアントの読み取りおよび書き込み監査メッセージが記録されます。
* 管理監査メッセージには、管理 API へのユーザー リクエストが記録されます。


各管理ノードは監査メッセージをテキスト ファイルに保存します。監査共有には、アクティブ ファイル (audit.log) と、前日からの圧縮された監査ログが含まれます。グリッド内の各ノードには、ノード上で生成された監査情報のコピーも保存されます。

管理ノードのコマンド ラインから監査ログ ファイルに直接アクセスできます。

StorageGRID はデフォルトで監査情報を送信できますが、送信先を変更することもできます。

* StorageGRID はデフォルトでローカル ノードの監査宛先を使用します。
* Grid Manager および Tenant Manager の監査ログ エントリがストレージ ノードに送信される場合があります。
* 必要に応じて、監査ログの送信先を変更し、監査情報を外部の syslog サーバーに送信することもできます。外部 Syslog サーバーが構成されている場合、監査レコードのローカル ログは引き続き生成され、保存されます。
* link:../monitor/configure-audit-messages.html["監査メッセージとログの送信先の設定について学習します"] 。


監査ログファイル、監査メッセージの形式、監査メッセージの種類、監査メッセージを分析するために使用できるツールの詳細については、以下を参照してください。link:../audit/index.html["監査ログを確認する"] 。
