---
permalink: monitor/updating-snmp-agent.html 
sidebar: sidebar 
keywords: how to update the SNMP agent 
summary: SNMP 通知を無効にしたり、コミュニティ文字列を更新したり、エージェント アドレス、USM ユーザー、トラップの送信先を追加または削除したりできます。 
---
= SNMPエージェントを更新する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP 通知を無効にしたり、コミュニティ文字列を更新したり、エージェント アドレス、USM ユーザー、トラップの送信先を追加または削除したりできます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["ルートアクセス権限"]。


.タスク概要
見るlink:configuring-snmp-agent.html["SNMPエージェントを構成する"]SNMP エージェント ページの各フィールドの詳細については、こちらをご覧ください。各タブで行った変更を確定するには、ページの下部にある [*保存*] を選択する必要があります。

.手順
. *構成* > *監視* > *SNMP エージェント* を選択します。
+
SNMP エージェント ページが表示されます。

. すべてのグリッド ノードで SNMP エージェントを無効にするには、[SNMP を有効にする] チェックボックスをオフにし、[保存] を選択します。
+
SNMP エージェントを再度有効にすると、以前の SNMP 構成設定はすべて保持されます。

. 必要に応じて、基本構成セクションの情報を更新します。
+
.. 必要に応じて、*システムの連絡先*と*システムの場所*を更新します。
.. 必要に応じて、[SNMP エージェント通知を有効にする] チェックボックスをオンまたはオフにして、 StorageGRID SNMP エージェントがトラップ通知とインフォーム通知を送信するかどうかを制御します。
+
このチェックボックスをオフにすると、SNMP エージェントは読み取り専用の MIB アクセスをサポートしますが、SNMP 通知は送信しません。

.. オプションで、[認証トラップを有効にする] チェックボックスをオンまたはオフにして、 StorageGRID SNMP エージェントが不適切に認証されたプロトコル メッセージを受信したときに認証トラップを送信するかどうかを制御します。


. SNMPv1 または SNMPv2c を使用する場合は、必要に応じて、コミュニティ文字列セクションで *読み取り専用コミュニティ* を更新または追加します。
. トラップの送信先を更新するには、[その他の構成] セクションの [トラップの送信先] タブを選択します。
+
このタブを使用して、 StorageGRIDトラップまたはインフォーム通知の 1 つ以上の宛先を定義します。 SNMP エージェントを有効にして [*保存*] を選択すると、アラートがトリガーされたときにStorageGRID は定義済みの各宛先に通知を送信します。サポートされている MIB-II エンティティ (ifDown や coldStart など) についても標準通知が送信されます。

+
入力内容の詳細については、link:../monitor/configuring-snmp-agent.html#create-trap-destinations["トラップ先を作成する"] 。

+
** 必要に応じて、デフォルトのトラップ コミュニティを更新または削除します。
+
デフォルトのトラップ コミュニティを削除する場合は、まず既存のトラップの送信先でカスタム コミュニティ文字列が使用されていることを確認する必要があります。

** トラップの宛先を追加するには、[*作成*] を選択します。
** トラップの宛先を編集するには、ラジオ ボタンを選択し、[編集] を選択します。
** トラップの宛先を削除するには、ラジオ ボタンを選択し、[削除] を選択します。
** 変更を確定するには、ページの下部にある [*保存*] を選択します。


. エージェント アドレスを更新するには、[その他の構成] セクションの [エージェント アドレス] タブを選択します。
+
このタブを使用して、1 つ以上の「リスニング アドレス」を指定します。これらは、SNMP エージェントがクエリを受信できるStorageGRIDアドレスです。

+
入力内容の詳細については、link:../monitor/configuring-snmp-agent.html#create-agent-addresses["エージェントアドレスを作成する"] 。

+
** エージェント アドレスを追加するには、[*作成*] を選択します。
** エージェント アドレスを編集するには、ラジオ ボタンを選択し、[編集] を選択します。
** エージェント アドレスを削除するには、ラジオ ボタンを選択し、[削除] を選択します。
** 変更を確定するには、ページの下部にある [*保存*] を選択します。


. USM ユーザーを更新するには、[その他の構成] セクションで [USM ユーザー] タブを選択します。
+
このタブを使用して、MIB を照会したり、トラップやインフォームを受信したりする権限を持つ USM ユーザーを定義します。

+
入力内容の詳細については、link:../monitor/configuring-snmp-agent.html#create-usm-users["USMユーザーを作成する"] 。

+
** USM ユーザーを追加するには、[*作成*] を選択します。
** USM ユーザーを編集するには、ラジオ ボタンを選択し、[編集] を選択します。
+
既存の USM ユーザーのユーザー名は変更できません。ユーザー名を変更する必要がある場合は、ユーザーを削除して新しいユーザーを作成する必要があります。

+

NOTE: ユーザーの権限のあるエンジン ID を追加または削除し、そのユーザーが現在宛先に選択されている場合は、宛先を編集または削除する必要があります。そうしないと、SNMP エージェント構成を保存するときに検証エラーが発生します。

** USM ユーザーを削除するには、ラジオ ボタンを選択し、[削除] を選択します。
+

NOTE: 削除したユーザーが現在トラップの送信先として選択されている場合は、送信先を編集または削除する必要があります。そうしないと、SNMP エージェント構成を保存するときに検証エラーが発生します。

** 変更を確定するには、ページの下部にある [*保存*] を選択します。


. SNMP エージェントの設定を更新したら、[*保存*] を選択します。

