---
permalink: monitor/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, monitoring 
summary: '簡易ネットワーク管理プロトコル (SNMP) を使用してStorageGRID を監視する場合は、 StorageGRIDに含まれている SNMP エージェントを構成する必要があります。' 
---
= SNMP監視を使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
簡易ネットワーク管理プロトコル (SNMP) を使用してStorageGRID を監視する場合は、 StorageGRIDに含まれている SNMP エージェントを構成する必要があります。

* link:configuring-snmp-agent.html["SNMPエージェントを構成する"]
* link:updating-snmp-agent.html["SNMPエージェントを更新する"]




== 機能

各StorageGRIDノードは、MIB を提供する SNMP エージェントまたはデーモンを実行します。  StorageGRID MIB には、アラートのテーブルと通知の定義が含まれています。 MIB には、各ノードのプラットフォームやモデル番号などのシステム記述情報も含まれています。各StorageGRIDノードは、MIB-II オブジェクトのサブセットもサポートします。


NOTE: 見るlink:access-snmp-mib.html["MIBファイルにアクセスする"]グリッド ノードに MIB ファイルをダウンロードする場合。

最初は、すべてのノードで SNMP が無効になっています。  SNMP エージェントを構成すると、すべてのStorageGRIDノードは同じ構成を受け取ります。

StorageGRID SNMP エージェントは、SNMP プロトコルの 3 つのバージョンすべてをサポートします。クエリに対して読み取り専用の MIB アクセスを提供し、管理システムに 2 種類のイベント駆動型通知を送信できます。

罠:: トラップは、管理システムによる確認を必要としない、SNMP エージェントによって送信される通知です。トラップは、アラートがトリガーされるなど、 StorageGRID内で何かが発生したことを管理システムに通知するために使用されます。
+
--
トラップは、SNMP の 3 つのバージョンすべてでサポートされています。

--
通知する:: インフォームはトラップに似ていますが、管理システムによる確認が必要です。  SNMP エージェントが一定時間内に確認応答を受信しない場合、確認応答を受信するか最大再試行値に達するまで、情報を再送信します。
+
--
インフォームは、SNMPv2c および SNMPv3 でサポートされています。

--


トラップ通知とインフォーム通知は、次の場合に送信されます。

* デフォルトまたはカスタムのアラートは、どの重大度レベルでもトリガーされます。アラートのSNMP通知を抑制するには、link:silencing-alert-notifications.html["サイレンスを設定する"]警告のため。アラート通知は、link:../primer/what-admin-node-is.html["優先送信者管理ノード"] 。
+
各アラートは、アラートの重大度レベルに基づいて、activeMinorAlert、activeMajorAlert、activeCriticalAlert の 3 つのトラップ タイプのいずれかにマッピングされます。これらのトラップを作動させる可能性のあるアラートのリストについては、link:alerts-reference.html["アラート一覧"] 。





== SNMPバージョンのサポート

この表には、各 SNMP バージョンでサポートされている内容の概要が示されています。

[cols="1a,2a,2a,2a"]
|===
|  | SNMPv1 | SNMPv2c | SNMPv3 


 a| 
クエリ

（GETとGETNEXT）
 a| 
読み取り専用MIBクエリ
 a| 
読み取り専用MIBクエリ
 a| 
読み取り専用MIBクエリ



 a| 
クエリ認証
 a| 
コミュニティ文字列
 a| 
コミュニティ文字列
 a| 
ユーザーベースセキュリティモデル（USM）ユーザー



 a| 
通知

（トラップと情報）
 a| 
トラップのみ
 a| 
罠と情報
 a| 
罠と情報



 a| 
通知認証
 a| 
デフォルトのトラップコミュニティまたは各トラップ宛先のカスタムコミュニティ文字列
 a| 
デフォルトのトラップコミュニティまたは各トラップ宛先のカスタムコミュニティ文字列
 a| 
各トラップ宛先のUSMユーザー

|===


== 制限事項

* StorageGRID は読み取り専用の MIB アクセスをサポートします。読み取り/書き込みアクセスはサポートされていません。
* グリッド内のすべてのノードは同じ構成を受け取ります。
* SNMPv3: StorageGRID はトランスポート サポート モード (TSM) をサポートしていません。
* SNMPv3: サポートされる認証プロトコルは SHA (HMAC-SHA-96) のみです。
* SNMPv3: サポートされている唯一のプライバシー プロトコルは AES です。

