---
permalink: maintain/accessing-server-manager-log-file.html 
sidebar: sidebar 
keywords: storagegrid, server manager, log file 
summary: Server Manager の使用中に問題が発生した場合は、ログ ファイルを確認してください。 
---
= サーバーマネージャーのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Server Manager の使用中に問題が発生した場合は、ログ ファイルを確認してください。

Server Manager に関連するエラー メッセージは、次の場所にある Server Manager ログ ファイルに記録されます。 `/var/local/log/servermanager.log`

失敗に関するエラー メッセージについてはこのファイルを確認してください。必要に応じて、問題をテクニカル サポートにエスカレーションします。ログ ファイルをテクニカル サポートに転送するよう求められる場合があります。



== エラー状態のサービス

サービスがエラー状態になったことが検出された場合は、サービスの再起動を試みてください。

.開始する前に
あなたは `Passwords.txt`ファイル。

.タスク概要
サーバー マネージャーはサービスを監視し、予期せず停止したサービスを再起動します。サービスに障害が発生した場合、サーバー マネージャーはサービスの再起動を試みます。 5 分以内にサービスの開始に 3 回失敗すると、サービスはエラー状態になります。サーバー マネージャーは再度の再起動を試行しません。

.手順
. グリッド ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。


+
ルートとしてログインすると、プロンプトは `$`に `#`。

. サービスのエラー状態を確認します。 `service _servicename_ status`
+
例えば：

+
[listing]
----
service ldr status
----
+
サービスがエラー状態の場合、次のメッセージが返されます。 `_servicename_ in error state` 。例えば：

+
[listing]
----
ldr in error state
----
+

NOTE: サービスステータスが `disabled`については、link:using-donotstart-file.html["サービスのDoNotStartファイルを削除する"] 。

. サービスを再起動してエラー状態を解除してみます。 `service _servicename_ restart`
+
サービスの再起動に失敗した場合は、テクニカル サポートにお問い合わせください。

. コマンド シェルからログアウトします。 `exit`

