---
permalink: maintain/all-node-types-replacing-vmware-node.html 
sidebar: sidebar 
keywords: replace VMware node 
summary: VMware でホストされていた障害の発生したStorageGRIDノードをリカバリする場合は、障害の発生したノードを削除し、リカバリ ノードを展開します。 
---
= VMwareノードの置き換え
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware でホストされていた障害の発生したStorageGRIDノードをリカバリする場合は、障害の発生したノードを削除し、リカバリ ノードを展開します。

.開始する前に
仮想マシンを復元できず、置き換える必要があることが判明しました。

.タスク概要
まず、VMware vSphere Web Client を使用して、障害が発生したグリッド ノードに関連付けられている仮想マシンを削除します。その後、新しい仮想マシンを展開できます。

この手順は、グリッド ノード回復プロセスの 1 つのステップにすぎません。ノードの削除と展開の手順は、管理ノード、ストレージ ノード、ゲートウェイ ノードを含むすべての VMware ノードで同じです。

.手順
. VMware vSphere Web Clientにログインします。
. 障害が発生したグリッド ノード仮想マシンに移動します。
. リカバリノードを展開するために必要なすべての情報をメモします。
+
.. 仮想マシンを右クリックし、[設定の編集] タブを選択して、使用中の設定をメモします。
.. グリッド ノードのネットワーク設定を表示および記録するには、*vApp オプション* タブを選択します。


. 障害が発生したグリッド ノードがストレージ ノードである場合は、データ ストレージに使用されている仮想ハード ディスクが破損していないかどうかを確認し、回復したグリッド ノードに再接続できるように保存します。
. 仮想マシンの電源をオフにします。
. 仮想マシンを削除するには、[アクション] > [すべての vCenter アクション] > [ディスクから削除] を選択します。
. 交換ノードとなる新しい仮想マシンを展開し、1 つ以上のStorageGRIDネットワークに接続します。手順については、link:../vmware/deploying-storagegrid-node-as-virtual-machine.html["StorageGRIDノードを仮想マシンとして展開する"] 。
+
ノードをデプロイするときに、オプションでノード ポートを再マップしたり、CPU またはメモリの設定を増やしたりすることができます。

+

NOTE: 新しいノードを展開した後、ストレージ要件に応じて新しい仮想ディスクを追加したり、以前に削除して障害が発生したグリッド ノードから保存した仮想ハード ディスクを再接続したり、またはその両方を行うことができます。

. 回復するノードのタイプに基づいて、ノード回復手順を完了します。
+
[cols="1a,2a"]
|===
| ノードの種類 | [ 


 a| 
プライマリ管理ノード
 a| 
link:configuring-replacement-primary-admin-node.html["代替プライマリ管理ノードを構成する"]



 a| 
非プライマリ管理ノード
 a| 
link:selecting-start-recovery-to-configure-non-primary-admin-node.html["非プライマリ管理ノードを構成するには、「リカバリの開始」を選択します"]



 a| 
ゲートウェイ ノード
 a| 
link:selecting-start-recovery-to-configure-gateway-node.html["ゲートウェイノードを構成するには、「リカバリの開始」を選択します。"]



 a| 
ストレージ ノード
 a| 
link:selecting-start-recovery-to-configure-storage-node.html["ストレージノードを構成するには、「リカバリの開始」を選択します。"]

|===

