---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: configure ip address, change IP tool, ethernet, dhcp, ha group 
summary: IP 変更ツールを使用してグリッド ノードの IP アドレスを構成することにより、ネットワーク構成を実行できます。 
---
= IPアドレスガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IP 変更ツールを使用してグリッド ノードの IP アドレスを構成することにより、ネットワーク構成を実行できます。

グリッドの展開中に最初に設定されたネットワーク構成にほとんどの変更を加えるには、IP 変更ツールを使用する必要があります。標準の Linux ネットワーク コマンドとファイルを使用した手動の変更は、すべてのStorageGRIDサービスに伝播されない可能性があり、アップグレード、再起動、またはノード回復手順にわたって保持されない可能性があります。


NOTE: IP 変更手順は中断を伴う手順となる場合があります。新しい構成が適用されるまで、グリッドの一部が使用できない可能性があります。


NOTE: グリッド ネットワーク サブネット リストのみを変更する場合は、グリッド マネージャを使用してネットワーク構成を追加または変更します。それ以外の場合、ネットワーク構成の問題によりグリッド マネージャーにアクセスできない場合、またはグリッド ネットワーク ルーティングの変更とその他のネットワークの変更を同時に実行している場合は、IP 変更ツールを使用します。


TIP: グリッド内のすべてのノードのグリッドネットワークIPアドレスを変更する場合は、link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["グリッド全体の変更のための特別な手順"] 。



== イーサネットインターフェース

eth0 に割り当てられる IP アドレスは、常にグリッド ノードのグリッド ネットワーク IP アドレスです。  eth1 に割り当てられる IP アドレスは、常にグリッド ノードの管理ネットワーク IP アドレスです。  eth2 に割り当てられる IP アドレスは常にグリッド ノードのクライアント ネットワーク IP アドレスです。

StorageGRIDアプライアンスなどの一部のプラットフォームでは、eth0、eth1、eth2 は、物理または VLAN インターフェイスの従属ブリッジまたは結合で構成された集約インターフェイスである可能性があることに注意してください。これらのプラットフォームでは、*SSM* > *リソース* タブに、eth0、eth1、eth2 に加えて、他のインターフェースに割り当てられたグリッド、管理、およびクライアント ネットワークの IP アドレスが表示される場合があります。



== DHCP

DHCP を設定できるのは、展開フェーズ中のみです。構成中に DHCP を設定することはできません。グリッド ノードの IP アドレス、サブネット マスク、およびデフォルト ゲートウェイを変更する場合は、IP アドレス変更手順を使用する必要があります。  IP 変更ツールを使用すると、DHCP アドレスが静的になります。



== 高可用性（HA）グループ

* クライアント ネットワーク インターフェイスが HA グループに含まれている場合、そのインターフェイスのクライアント ネットワーク IP アドレスを、HA グループに設定されているサブネットの外部のアドレスに変更することはできません。
* クライアント ネットワーク IP アドレスを、クライアント ネットワーク インターフェイスで構成された HA グループに割り当てられた既存の仮想 IP アドレスの値に変更することはできません。
* グリッド ネットワーク インターフェイスが HA グループに含まれている場合、そのインターフェイスのグリッド ネットワーク IP アドレスを、HA グループに構成されたサブネットの外部のアドレスに変更することはできません。
* グリッド ネットワーク IP アドレスを、グリッド ネットワーク インターフェイスで構成された HA グループに割り当てられた既存の仮想 IP アドレスの値に変更することはできません。

