---
permalink: maintain/configuring-ntp-servers.html 
sidebar: sidebar 
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp 
summary: 'StorageGRIDシステム内のグリッド ノード間でデータが正確に同期されるように、Network Time Protocol (NTP) サーバーを追加、更新、または削除できます。' 
---
= NTPサーバの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDシステム内のグリッド ノード間でデータが正確に同期されるように、Network Time Protocol (NTP) サーバーを追加、更新、または削除できます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["メンテナンスまたはルートアクセス権限"]。
* プロビジョニング パスフレーズを持っています。
* 設定する NTP サーバーの IPv4 アドレスがあります。




== StorageGRIDがNTPを使用する方法

StorageGRIDシステムは、ネットワーク タイム プロトコル (NTP) を使用して、グリッド内のすべてのグリッド ノード間の時間を同期します。

各サイトでは、 StorageGRIDシステム内の少なくとも 2 つのノードにプライマリ NTP ロールが割り当てられます。これらは、推奨される最小 4 つ、最大 6 つの外部タイム ソースと相互に同期します。  StorageGRIDシステム内のプライマリ NTP ノードではないすべてのノードは NTP クライアントとして機能し、これらのプライマリ NTP ノードと同期します。

外部 NTP サーバーは、以前にプライマリ NTP ロールを割り当てたノードに接続します。このため、プライマリ NTP ロールを持つノードを少なくとも 2 つ指定することをお勧めします。



== NTPサーバーのガイドライン

タイミングの問題を防ぐには、次のガイドラインに従ってください。

* 外部 NTP サーバーは、以前にプライマリ NTP ロールを割り当てたノードに接続します。このため、プライマリ NTP ロールを持つノードを少なくとも 2 つ指定することをお勧めします。
* 各サイトの少なくとも 2 つのノードが少なくとも 4 つの外部 NTP ソースにアクセスできることを確認します。サイト内の 1 つのノードだけが NTP ソースに到達できる場合、そのノードがダウンするとタイミングの問題が発生します。さらに、サイトごとに 2 つのノードをプライマリ NTP ソースとして指定すると、サイトがグリッドの残りの部分から分離されている場合でも正確なタイミングが保証されます。
* 指定された外部 NTP サーバーは NTP プロトコルを使用する必要があります。時間のずれの問題を防ぐには、Stratum 3 以上の NTP サーバー参照を指定する必要があります。



NOTE: 運用レベルのStorageGRIDインストールに外部 NTP ソースを指定する場合は、Windows Server 2016 より前のバージョンの Windows で Windows Time (W32Time) サービスを使用しないでください。以前のバージョンの Windows のタイム サービスは精度が十分でないため、 StorageGRIDなどの高精度環境で使用することは Microsoft によってサポートされていません。詳細については、 https://support.microsoft.com/en-us/help/939322/support-boundary-to-configure-the-windows-time-service-for-high-accura["高精度環境向けに Windows Time サービスを構成するためのサポート境界"^] 。



== NTPサーバーを構成する

NTP サーバーを追加、更新、または削除するには、次の手順に従います。

.手順
. *メンテナンス* > *ネットワーク* > *NTP サーバー* を選択します。
. [サーバー] セクションで、必要に応じて NTP サーバー エントリを追加、更新、または削除します。
+
少なくとも 4 台の NTP サーバーを含める必要があり、最大 6 台のサーバーを指定できます。

. StorageGRIDシステムのプロビジョニング パスフレーズを入力し、[保存] を選択します。
+
構成の更新が完了するまで、ページは無効になります。

+

NOTE: 新しい NTP サーバーを保存した後、すべての NTP サーバーが接続テストに失敗した場合は、続行しないでください。テクニカル サポートにお問い合わせください。





== NTPサーバーの問題を解決する

インストール時に最初に指定した NTP サーバーの安定性または可用性に問題が発生した場合、サーバーを追加するか、既存のサーバーを更新または削除することで、 StorageGRIDシステムが使用する外部 NTP ソースのリストを更新できます。
