---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storage node decommission, considerations, appliance node clone 
summary: ストレージ ノードを廃止する前に、代わりにノードのクローンを作成できるかどうかを検討してください。その後、ノードを廃止することに決めた場合は、廃止手順中にStorageGRID がオブジェクトとメタデータを管理する方法を確認します。 
---
= ストレージノードの廃止に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ ノードを廃止する前に、代わりにノードのクローンを作成できるかどうかを検討してください。その後、ノードを廃止することに決めた場合は、廃止手順中にStorageGRID がオブジェクトとメタデータを管理する方法を確認します。



== ノードを廃止するのではなくクローン化するタイミング

古いアプライアンス ストレージ ノードを新しいアプライアンスまたはより大きなアプライアンスに置き換える場合は、拡張で新しいアプライアンスを追加してから古いアプライアンスを廃止するのではなく、アプライアンス ノードのクローンを作成することを検討してください。

アプライアンス ノードのクローン作成により、同じStorageGRIDサイトにある既存のアプライアンス ノードを互換性のあるアプライアンスに簡単に置き換えることができます。クローン作成プロセスでは、すべてのデータが新しいアプライアンスに転送され、新しいアプライアンスがサービスを開始し、古いアプライアンスはインストール前の状態のままになります。

必要に応じてアプライアンス ノードのクローンを作成できます。

* 寿命が近づいている機器を交換します。
* 既存のノードをアップグレードして、改善されたアプライアンス テクノロジを活用します。
* StorageGRIDシステム内のストレージ ノードの数を変更せずに、グリッド ストレージ容量を増やします。
* RAID モードを変更するなどして、ストレージ効率を向上します。


見る https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["アプライアンスノードのクローン作成"^]詳細については。



== 接続されたストレージノードに関する考慮事項

接続されたストレージ ノードを廃止する場合の考慮事項を確認します。

* 1 回のノード廃止手順で 10 台を超えるストレージ ノードを廃止しないでください。
* システムには、常に、運用要件を満たすのに十分なストレージノードが含まれていなければなりません。link:understanding-adc-service-quorum.html["ADCクォーラム"]そしてアクティブなlink:reviewing-ilm-policy-and-storage-configuration.html["ILM ポリシー"]。この制限を満たすには、既存のストレージ ノードを廃止する前に、拡張操作で新しいストレージ ノードを追加する必要がある場合があります。
+
ソフトウェア ベースのメタデータのみのノードを含むグリッド内のストレージ ノードを廃止する場合は注意してください。オブジェクトとメタデータの両方を保存するように構成されたすべてのノードを廃止すると、オブジェクトを保存する機能がグリッドから削除されます。見るlink:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードの種類"]メタデータのみのストレージ ノードの詳細については、こちらをご覧ください。

* ストレージ ノードを削除すると、大量のオブジェクト データがネットワーク経由で転送されます。これらの転送は通常のシステム操作には影響しませんが、 StorageGRIDシステムによって消費されるネットワーク帯域幅の合計量に影響を及ぼす可能性があります。
* ストレージ ノードの廃止に関連するタスクには、通常のシステム操作に関連するタスクよりも低い優先度が与えられます。つまり、廃止によってStorageGRIDシステムの通常の操作が妨げられることはなく、システムが非アクティブな期間にスケジュールする必要もありません。廃止はバックグラウンドで実行されるため、プロセスが完了するまでにどのくらいの時間がかかるかを予測することは困難です。一般に、システムが静止しているとき、または一度に 1 つのストレージ ノードのみが削除されるときは、廃止はより速く完了します。
* ストレージ ノードの廃止には数日または数週間かかる場合があります。それに応じてこの手順を計画します。廃止プロセスはシステム運用に影響を与えないように設計されていますが、他の手順を制限する可能性があります。一般に、グリッド ノードを削除する前に、計画されているシステムのアップグレードまたは拡張を実行する必要があります。
* ストレージノードの削除中に別のメンテナンス手順を実行する必要がある場合は、link:pausing-and-resuming-decommission-process-for-storage-nodes.html["廃止手続きを一時停止する"]他の手順が完了したら再開します。
+

NOTE: *一時停止* ボタンは、ILM 評価または消去コード化されたデータの廃止段階に達したときにのみ有効になります。ただし、ILM 評価 (データ移行) はバックグラウンドで引き続き実行されます。

* 廃止タスクの実行中は、どのグリッド ノードでもデータ修復操作を実行することはできません。
* ストレージ ノードが廃止されている間は、ILM ポリシーに変更を加えないでください。
* データを永久的かつ安全に削除するには、廃止手順が完了した後にストレージ ノードのドライブを消去する必要があります。




== 切断されたストレージノードに関する考慮事項

切断されたストレージ ノードを廃止する場合の考慮事項を確認します。

* 切断されたノードをオンラインに戻したり回復したりできないことが確実でない限り、そのノードを廃止しないでください。
+

CAUTION: ノードからオブジェクト データを回復できる可能性があると思われる場合は、この手順を実行しないでください。代わりに、テクニカル サポートに連絡して、ノードの回復が可能かどうかを確認してください。

* 切断されたストレージ ノードを廃止すると、 StorageGRID は他のストレージ ノードのデータを使用して、切断されたノード上にあったオブジェクト データとメタデータを再構築します。
* 切断されたストレージ ノードを複数廃止すると、データが失われる可能性があります。十分なオブジェクト コピー、消失訂正符号化フラグメント、またはオブジェクト メタデータが残っていない場合、システムはデータを再構築できない可能性があります。ソフトウェア ベースのメタデータのみのノードを含むグリッド内のストレージ ノードを廃止する場合、オブジェクトとメタデータの両方を保存するように構成されたすべてのノードを廃止すると、グリッドからすべてのオブジェクト ストレージが削除されます。見るlink:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードの種類"]メタデータのみのストレージ ノードの詳細については、こちらをご覧ください。
+

CAUTION: 復旧できない切断されたストレージ ノードが複数ある場合は、テクニカル サポートに連絡して最善の対処方法を確認してください。

* 切断されたストレージ ノードを廃止すると、 StorageGRID は廃止プロセスの最後にデータ修復ジョブを開始します。これらのジョブは、切断されたノードに保存されていたオブジェクト データとメタデータを再構築しようとします。
* 切断されたストレージ ノードを廃止する場合、廃止手順は比較的早く完了します。ただし、データ修復ジョブの実行には数日または数週間かかる場合があり、廃止手順では監視されません。これらのジョブを手動で監視し、必要に応じて再起動する必要があります。見るlink:checking-data-repair-jobs.html["データ修復ジョブを確認する"] 。
* オブジェクトのコピーのみを含む切断されたストレージ ノードを廃止すると、オブジェクトは失われます。データ修復ジョブは、現在接続されているストレージ ノードに少なくとも 1 つの複製されたコピーまたは十分な消去コード化されたフラグメントが存在する場合にのみ、オブジェクトを再構築および回復できます。

