---
permalink: maintain/copying-audit-logs-from-failed-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, non-primary admin node, non primary admin node 
summary: 障害が発生した管理ノードから監査ログをコピーできる場合は、グリッドのシステム アクティビティと使用状況の記録を維持するために、それらを保存する必要があります。回復した非プライマリ管理ノードが起動して実行された後、保存された監査ログをそのノードに復元できます。 
---
= 障害が発生した非プライマリ管理ノードから監査ログをコピーする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生した管理ノードから監査ログをコピーできる場合は、グリッドのシステム アクティビティと使用状況の記録を維持するために、それらを保存する必要があります。回復した非プライマリ管理ノードが起動して実行された後、保存された監査ログをそのノードに復元できます。

この手順では、障害が発生した管理ノードから監査ログ ファイルを別のグリッド ノード上の一時的な場所にコピーします。保存された監査ログは、交換用の管理ノードにコピーできます。監査ログは新しい管理ノードに自動的にコピーされません。

障害の種類によっては、障害が発生した管理ノードから監査ログをコピーできない場合があります。デプロイメントに管理ノードが 1 つしかない場合、回復された管理ノードは新しい空のファイルに監査ログへのイベントの記録を開始し、以前に記録されたデータは失われます。デプロイメントに複数の管理ノードが含まれている場合は、別の管理ノードから監査ログを回復できます。


NOTE: 障害が発生した管理ノードで監査ログに現在アクセスできない場合でも、ホストの回復後など、後でアクセスできる可能性があります。

. 可能であれば、障害が発生した管理ノードにログインします。それ以外の場合は、プライマリ管理ノードまたは別の管理ノード（使用可能な場合）にログインします。
+
.. 次のコマンドを入力します。 `ssh admin@grid_node_IP`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。


+
ルートとしてログインすると、プロンプトは `$`に `#`。

. 新しいログ ファイルが作成されないように、AMS サービスを停止します。``service ams stop``
. 監査エクスポート ディレクトリに移動します。
+
`cd /var/local/log`

. ソース audit.log ファイルの名前を、一意の番号付きファイル名に変更します。たとえば、audit.logファイルの名前を次のように変更します。 `2023-10-25.txt.1` 。
+
[listing]
----
ls -l
mv audit.log 2023-10-25.txt.1
----
. AMS サービスを再起動します。 `service ams start`
. すべての監査ログ ファイルを別のグリッド ノード上の一時的な場所にコピーするためのディレクトリを作成します。 `ssh admin@grid_node_IP mkdir -p /var/local/tmp/saved-audit-logs`
+
プロンプトが表示されたら、管理者のパスワードを入力します。

. すべての監査ログ ファイルを一時的な場所にコピーします。 `scp -p * admin@grid_node_IP:/var/local/tmp/saved-audit-logs`
+
プロンプトが表示されたら、管理者のパスワードを入力します。

. rootとしてログアウトします: `exit`

