---
permalink: maintain/downloading-recovery-package.html 
sidebar: sidebar 
keywords: storagegrid, recovery package 
summary: リカバリ パッケージ ファイルを使用すると、障害が発生した場合にStorageGRIDシステムを復元できます。 
---
= リカバリ パッケージをダウンロード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リカバリ パッケージ ファイルを使用すると、障害が発生した場合にStorageGRIDシステムを復元できます。

.開始する前に
* プライマリ管理ノードから、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* プロビジョニング パスフレーズを持っています。
* あなたが持っているlink:../admin/admin-group-permissions.html["特定のアクセス権限"]。


StorageGRIDシステムのグリッド トポロジを変更する前、またはソフトウェアをアップグレードする前に、現在のリカバリ パッケージ ファイルをダウンロードしてください。次に、グリッド トポロジを変更した後、またはソフトウェアをアップグレードした後、リカバリ パッケージの新しいコピーをダウンロードします。

.手順
. *メンテナンス* > *システム* > *回復パッケージ*を選択します。
. プロビジョニング パスフレーズを入力し、[ダウンロードの開始] を選択します。
+
ダウンロードはすぐに開始されます。

. ダウンロードが完了したら、 `.zip`ファイルの内容にアクセスできることを確認してください。 `Passwords.txt`ファイル。
. ダウンロードしたリカバリパッケージファイルをコピーします(`.zip`) を 2 つの安全でセキュリティ保護された別の場所に保管します。
+

CAUTION: リカバリ パッケージ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティ保護する必要があります。


