---
permalink: maintain/downloading-hotfix-file.html 
sidebar: sidebar 
keywords: storagegrid, hotfix, download 
summary: 修正プログラムを適用する前に、修正プログラム ファイルをダウンロードする必要があります。 
---
= 修正プログラムファイルをダウンロード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
修正プログラムを適用する前に、修正プログラム ファイルをダウンロードする必要があります。

.手順
. へ移動 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetAppのダウンロード：StorageGRID"^]。
. *利用可能なソフトウェア*の下の下矢印を選択すると、ダウンロード可能な修正プログラムのリストが表示されます。
+

NOTE: 修正プログラム ファイルのバージョンの形式は、11.4__.x.y__ です。

. アップデートに含まれる変更を確認します。
+

NOTE: もしあなたがlink:configuring-replacement-primary-admin-node.html["プライマリ管理ノードを回復しました"]修正プログラムを適用する必要がある場合は、他のグリッド ノードにインストールされているものと同じ修正プログラム バージョンを選択します。

+
.. ダウンロードする修正プログラムのバージョンを選択し、[Go] を選択します。
.. NetAppアカウントのユーザ名とパスワードを使用してサインインします。
.. エンドユーザー使用許諾契約書を読んで同意します。
+
選択したバージョンのダウンロード ページが表示されます。

.. 修正プログラムをダウンロードする `readme.txt`ファイルにアクセスして、修正プログラムに含まれる変更の概要を表示します。


. 修正プログラムのダウンロード ボタンを選択し、ファイルを保存します。
+

NOTE: このファイルの名前を変更しないでください。

+

NOTE: macOSデバイスを使用している場合、修正プログラムは自動的に `.txt`ファイル。もしそうなら、ファイル名を `.txt`拡大。

. ダウンロード場所を選択し、[保存] を選択します。

