---
permalink: maintain/grid-node-decommissioning.html 
sidebar: sidebar 
keywords: storagegrid, decommission, remove grid node 
summary: ノード廃止手順を使用して、1 つ以上のサイトから 1 つ以上のグリッド ノードを削除できます。プライマリ管理ノードを廃止することはできません。 
---
= グリッドノードの廃止
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノード廃止手順を使用して、1 つ以上のサイトから 1 つ以上のグリッド ノードを削除できます。プライマリ管理ノードを廃止することはできません。



== ノードを廃止するタイミング

次のいずれかに該当する場合は、ノード廃止手順を使用します。

* 拡張で大きなストレージ ノードを追加し、同時にオブジェクトを保持しながら 1 つ以上の小さなストレージ ノードを削除したいと考えています。
+

TIP: 古い家電を新しい家電に交換したい場合は、 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["アプライアンスノードのクローン作成"^]拡張時に新しいアプライアンスを追加し、その後古いアプライアンスを廃止する代わりに。

* 必要な総ストレージ容量が少なくなります。
* ゲートウェイ ノードは不要になりました。
* プライマリ以外の管理ノードは必要なくなりました。
* グリッドには、回復したりオンラインに戻したりできない切断されたノードが含まれています。
* グリッドにはアーカイブ ノードが含まれます。




== ノードを廃止する方法

接続されているグリッド ノードまたは切断されているグリッド ノードを廃止できます。

接続されたノードを廃止する:: 一般的に、グリッド ノードを廃止する場合は、それらがStorageGRIDシステムに接続されており、すべてのノードの状態が正常である ([ノード] ページと [ノードの廃止] ページに緑色のアイコンが表示される) 場合にのみ行う必要があります。
+
--
手順については、link:decommissioning-connected-grid-nodes.html["接続されたグリッドノードを廃止する"] 。

--
切断されたノードを廃止する:: 場合によっては、現在グリッドに接続されていないグリッド ノード (ヘルスが不明または管理上ダウンしているノード) を廃止する必要があることがあります。
+
--
手順については、link:decommissioning-disconnected-grid-nodes.html["切断されたグリッドノードの廃止"] 。

--




== ノードを廃止する前に考慮すべきこと

いずれかの手順を実行する前に、各ノード タイプに関する考慮事項を確認してください。

* link:considerations-for-decommissioning-admin-or-gateway-nodes.html["管理ノードまたはゲートウェイノードの廃止に関する考慮事項"]
* link:considerations-for-decommissioning-storage-nodes.html["ストレージノードの廃止に関する考慮事項"]

