---
permalink: maintain/how-site-recovery-is-performed-by-technical-support.html 
sidebar: sidebar 
keywords: storagegrid, site recovery, technical support, tech support 
summary: StorageGRIDサイト全体に障害が発生した場合、または複数のストレージ ノードに障害が発生した場合は、テクニカル サポートに連絡する必要があります。テクニカル サポートは、お客様の状況を評価し、復旧計画を策定して、ビジネス目標を満たし、復旧時間を最適化し、不要なデータ損失を防ぐ方法で、障害が発生したノードまたはサイトを復旧します。 
---
= テクニカルサポートがサイトを復旧する方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDサイト全体に障害が発生した場合、または複数のストレージ ノードに障害が発生した場合は、テクニカル サポートに連絡する必要があります。テクニカル サポートは、お客様の状況を評価し、復旧計画を策定して、ビジネス目標を満たし、復旧時間を最適化し、不要なデータ損失を防ぐ方法で、障害が発生したノードまたはサイトを復旧します。


CAUTION: サイトの回復はテクニカル サポートによってのみ実行できます。

StorageGRIDシステムはさまざまな障害に対して耐性があり、多くのリカバリおよびメンテナンス手順を自分で正常に実行できます。ただし、詳細な手順は状況に固有の要因によって異なるため、単純で一般的なサイト回復手順を作成することは困難です。例えば：

* *ビジネス目標*: StorageGRIDサイトが完全に失われた後、ビジネス目標を最も効果的に達成する方法を評価する必要があります。たとえば、失われたサイトを元の状態で再構築しますか? 失われたStorageGRIDサイトを新しい場所に置き換えますか? 顧客ごとに状況は異なるため、復旧計画は優先事項に対応するように設計する必要があります。
* *障害の正確な性質*: サイトの回復を開始する前に、障害が発生したサイトのノードがそのまま残っているかどうか、またはストレージ ノードに回復可能なオブジェクトが含まれているかどうかを確認します。有効なデータを含むノードまたはストレージ ボリュームを再構築すると、不要なデータ損失が発生する可能性があります。
* *アクティブな ILM ポリシー*: グリッド内のオブジェクト コピーの数、タイプ、場所は、アクティブな ILM ポリシーによって制御されます。  ILM ポリシーの詳細は、回復可能なデータの量や、回復に必要な特定の手法に影響を与える可能性があります。
+

CAUTION: サイトにオブジェクトの唯一のコピーが含まれていて、そのサイトが失われると、オブジェクトも失われます。

* *バケット (またはコンテナ) の一貫性*: バケット (またはコンテナ) に適用される一貫性は、オブジェクトの取り込みが成功したことをクライアントに通知する前に、 StorageGRID がオブジェクトのメタデータをすべてのノードとサイトに完全に複製するかどうかに影響します。一貫性値が最終的な一貫性を許可する場合、サイト障害で一部のオブジェクト メタデータが失われている可能性があります。これにより、回復可能なデータの量や、回復手順の詳細に影響する可能性があります。
* *最近の変更履歴*: 障害発生時にメンテナンス手順が進行中であったかどうか、または ILM ポリシーに最近変更が加えられたかどうかによって、回復手順の詳細が影響を受ける可能性があります。サイトの復旧を開始する前に、テクニカル サポートがグリッドの最近の履歴と現在の状況を評価する必要があります。



CAUTION: サイトの回復はテクニカル サポートによってのみ実行できます。

これは、障害が発生したサイトを復旧するためにテクニカル サポートが使用するプロセスの概要です。

. テクニカルサポート：
+
.. 障害の詳細な評価を行います。
.. お客様と協力してビジネス目標を確認します。
.. あなたの状況に合わせた復旧計画を作成します。


. プライマリ管理ノードに障害が発生した場合、テクニカル サポートが復旧します。
. テクニカル サポートは、次の概要に従ってすべてのストレージ ノードを回復します。
+
.. 必要に応じて、ストレージ ノードのハードウェアまたは仮想マシンを交換します。
.. 障害が発生したサイトにオブジェクト メタデータを復元します。
.. 回復されたストレージ ノードにオブジェクト データを復元します。
+

CAUTION: 単一の障害が発生したストレージ ノードの回復手順を使用すると、データが失われます。

+

NOTE: サイト全体に障害が発生した場合、テクニカル サポートは特殊なコマンドを使用して、オブジェクトとオブジェクト メタデータを正常に復元します。



. テクニカル サポートが他の障害ノードを回復します。
+
オブジェクトのメタデータとデータが回復された後、テクニカル サポートは標準の手順を使用して、障害が発生したゲートウェイ ノードまたはプライマリ以外の管理ノードを回復します。



.関連情報
link:site-decommissioning.html["サイトの廃止"]
