---
permalink: maintain/how-your-system-is-affected-when-you-apply-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 修正プログラムを適用するとStorageGRIDシステムにどのような影響が及ぶかを理解する必要があります。 
---
= 修正プログラムを適用した場合のシステムへの影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
修正プログラムを適用するとStorageGRIDシステムにどのような影響が及ぶかを理解する必要があります。



== StorageGRIDホットフィックスは無停止です

StorageGRIDシステムは、ホットフィックス プロセス全体を通じてクライアント アプリケーションからデータを取り込んで取得できます。同じタイプのすべてのノード (たとえば、ストレージ ノード) をホットフィックスに承認すると、ノードは 1 つずつ停止されるため、すべてのグリッド ノードまたは特定のタイプのすべてのグリッド ノードが使用できなくなる時間はありません。

継続的な可用性を確保するには、ILM ポリシーに各オブジェクトの複数のコピーを保存することを指定するルールが含まれていることを確認します。また、すべての外部 S3 クライアントが次のいずれかにリクエストを送信するように設定されていることを確認する必要があります。

* 高可用性（HA）グループの仮想IPアドレス
* 他社製の高可用性ロード バランサ
* 各クライアントに複数のゲートウェイノード
* 各クライアントに複数のストレージノード




== クライアントアプリケーションで短期的な中断が発生する可能性があります

StorageGRIDシステムは、ホットフィックス プロセス全体を通じてクライアント アプリケーションからデータを取り込んで取得できます。ただし、ホットフィックスで各ゲートウェイ ノードまたはストレージ ノード上のサービスを再起動する必要がある場合、クライアントから各ゲートウェイ ノードまたはストレージ ノードへの接続が一時的に中断される可能性があります。修正プログラム プロセスが完了し、個々のノードでサービスが再開されると、接続が復元されます。

短期間の接続の喪失が許容できない場合は、修正プログラムを適用するためにダウンタイムをスケジュールする必要がある場合があります。選択的承認を使用して、特定のノードが更新されるタイミングをスケジュールできます。


NOTE: 複数のゲートウェイと高可用性 (HA) グループを使用して、修正プログラム プロセス中に自動フェールオーバーを実現できます。説明書をご覧くださいlink:../admin/configure-high-availability-group.html["高可用性グループの構成"]。



== アラートやSNMP通知がトリガーされる可能性があります

サービスが再起動されたとき、およびStorageGRIDシステムが混在バージョン環境 (一部のグリッド ノードが以前のバージョンを実行し、他のグリッド ノードが新しいバージョンにアップグレードされている) として動作しているときに、アラートおよび SNMP 通知がトリガーされることがあります。通常、これらのアラートと通知は、修正プログラムが完了すると消去されます。



== 構成の変更は制限されています

StorageGRIDにホットフィックスを適用する場合:

* すべてのノードに修正プログラムが適用されるまで、グリッド構成の変更 (グリッド ネットワーク サブネットの指定や保留中のグリッド ノードの承認など) を行わないでください。
* すべてのノードに修正プログラムが適用されるまで、ILM 構成を更新しないでください。

