---
permalink: maintain/linux-adding-trunk-or-access-interfaces-to-node.html 
sidebar: sidebar 
keywords: add extra interface to node, trunk interface, access interface 
summary: Linux ノードをインストールした後、追加のトランクまたはアクセス インターフェイスを追加できます。追加したインターフェースは、VLAN インターフェース ページと HA グループ ページに表示されます。 
---
= Linux: ノードにトランクまたはアクセスインターフェースを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux ノードをインストールした後、追加のトランクまたはアクセス インターフェイスを追加できます。追加したインターフェースは、VLAN インターフェース ページと HA グループ ページに表示されます。

.開始する前に
* Linux プラットフォームにStorageGRIDをインストールするための手順にアクセスできます。
+
** link:../rhel/index.html["Red Hat Enterprise LinuxにStorageGRIDをインストールする"]
** link:../ubuntu/index.html["UbuntuまたはDebianにStorageGRIDをインストールする"]


* あなたは `Passwords.txt`ファイル。
* あなたが持っているlink:../admin/admin-group-permissions.html["特定のアクセス権限"]。



CAUTION: ソフトウェアのアップグレード、リカバリ手順、または拡張手順がアクティブな間は、ノードにインターフェイスを追加しないでください。

.タスク概要
ノードをインストールした後、Linux ノードに 1 つ以上の追加インターフェイスを追加するには、次の手順に従います。たとえば、管理ノードまたはゲートウェイ ノードにトランク インターフェイスを追加して、VLAN インターフェイスを使用して、異なるアプリケーションまたはテナントに属するトラフィックを分離することができます。または、高可用性 (HA) グループで使用するアクセス インターフェイスを追加することもできます。

トランク インターフェイスを追加する場合は、 StorageGRIDで VLAN インターフェイスを設定する必要があります。アクセス インターフェイスを追加する場合は、インターフェイスを HA グループに直接追加できます。VLAN インターフェイスを構成する必要はありません。

インターフェイスを追加すると、ノードはしばらくの間使用できなくなります。この手順は一度に 1 つのノードで実行する必要があります。

.手順
. ノードをホストしている Linux サーバーにログインします。
. vim や pico などのテキスト エディターを使用して、ノード構成ファイルを編集します。
+
`/etc/storagegrid/nodes/_node-name_.conf`

. ファイルにエントリを追加して、ノードに追加する各追加インターフェイスの名前と、オプションで説明を指定します。この形式を使用します。
+
`INTERFACE_TARGET_nnnn=_value_`

+
_nnnn_には、それぞれに固有の番号を指定します `INTERFACE_TARGET`追加するエントリ。

+
_value_ には、ベアメタル ホスト上の物理インターフェースの名前を指定します。次に、オプションでコンマを追加し、VLAN インターフェイス ページと HA グループ ページに表示されるインターフェイスの説明を入力します。

+
例えば：

+
`INTERFACE_TARGET_0001=ens256, Trunk`

+

NOTE: 他のネットワーク パラメータを指定しないでください。指定すると検証エラーが発生します。

. ノード構成ファイルへの変更を検証するには、次のコマンドを実行します。
+
`sudo storagegrid node validate _node-name_`

+
次のステップに進む前に、エラーや警告に対処してください。

. ノードの構成を更新するには、次のコマンドを実行します。
+
`sudo storagegrid node reload _node-name_`



.終了後の操作
* 1つ以上のトランクインターフェースを追加した場合は、link:../admin/configure-vlan-interfaces.html["VLANインターフェースを設定する"]新しい親インターフェースごとに 1 つ以上の VLAN インターフェースを設定します。
* 1つ以上のアクセスインターフェースを追加した場合は、link:../admin/configure-high-availability-group.html["高可用性グループを構成する"]新しいインターフェースを HA グループに直接追加します。

