---
permalink: maintain/modifying-dns-configuration-for-single-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, dns, modify dns 
summary: デプロイメント全体に対して DNS をグローバルに構成するのではなく、スクリプトを実行してグリッド ノードごとに DNS を個別に構成できます。 
---
= 単一グリッドノードのDNS構成を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デプロイメント全体に対して DNS をグローバルに構成するのではなく、スクリプトを実行してグリッド ノードごとに DNS を個別に構成できます。

通常、DNS サーバーを構成するには、グリッド マネージャーの *MAINTENANCE* > *Network* > *DNS servers* オプションを使用する必要があります。異なるグリッド ノードに異なる DNS サーバーを使用する必要がある場合のみ、次のスクリプトを使用してください。

.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
+
ルートとしてログインすると、プロンプトは `$`に `#`。

.. SSH エージェントに SSH 秘密キーを追加します。入力： `ssh-add`
.. に記載されているSSHアクセスパスワードを入力してください `Passwords.txt`ファイル。


. [[log_in_to_node]]カスタム DNS 構成で更新するノードにログインします。 `ssh _node_IP_address_`
. DNS セットアップ スクリプトを実行します。 `setup_resolv.rb.`
+
スクリプトは、サポートされているコマンドのリストで応答します。

+
[listing]
----
Tool to modify external name servers

available commands:
  add search <domain>
               add a specified domain to search list
               e.g.> add search netapp.com
  remove search <domain>
               remove a specified domain from list
               e.g.> remove search netapp.com
  add nameserver <ip>
               add a specified IP address to the name server list
               e.g.> add nameserver 192.0.2.65
  remove nameserver <ip>
               remove a specified IP address from list
               e.g.> remove nameserver 192.0.2.65
  remove nameserver all
               remove all nameservers from list
  save         write configuration to disk and quit
  abort        quit without saving changes
  help         display this help message


Current list of name servers:
    192.0.2.64
Name servers inherited from global DNS configuration:
    192.0.2.126
    192.0.2.127
Current list of search entries:
    netapp.com

Enter command [`add search <domain>|remove search <domain>|add nameserver <ip>`]
              [`remove nameserver <ip>|remove nameserver all|save|abort|help`]
----
. ネットワークにドメイン名サービスを提供するサーバーの IPv4 アドレスを追加します。 `add <nameserver IP_address>`
. 繰り返します `add nameserver`ネームサーバーを追加するコマンド。
. 他のコマンドについては、プロンプトの指示に従ってください。
. 変更を保存してアプリケーションを終了します。 `save`
. [[close_cmd_shell]]サーバーのコマンドシェルを閉じます。 `exit`
. 各グリッドノードについて、<<log_in_to_node,ノードにログインする>>を通して<<close_cmd_shell,コマンドシェルを閉じる>>。
. 他のサーバーへのパスワードなしのアクセスが不要になったら、SSH エージェントから秘密キーを削除します。入力： `ssh-add -D`

