---
permalink: maintain/obtaining-required-materials-for-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 修正プログラムを適用する前に、必要な資料をすべて入手する必要があります。 
---
= 修正プログラムに必要な資料を入手する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
修正プログラムを適用する前に、必要な資料をすべて入手する必要があります。

[cols="1a,2a"]
|===
| 項目 | 注記 


 a| 
StorageGRID修正プログラム ファイル
 a| 
StorageGRID修正プログラム ファイルをダウンロードする必要があります。



 a| 
* ネットワークポート
* link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"]
* SSHクライアント（例：PuTTY）

 a| 



 a| 
リカバリパッケージ(`.zip`） ファイル
 a| 
修正プログラムを適用する前に、link:downloading-recovery-package.html["最新のリカバリパッケージファイルをダウンロードする"]ホットフィックス中に問題が発生した場合に備えて。次に、修正プログラムを適用した後、回復パッケージ ファイルの新しいコピーをダウンロードし、安全な場所に保存します。更新されたリカバリ パッケージ ファイルを使用すると、障害が発生した場合にシステムを復元できます。



| Passwords.txt ファイル  a| 
オプションであり、SSH クライアントを使用して手動で修正プログラムを適用する場合にのみ使用されます。その `Passwords.txt`ファイルはリカバリパッケージの一部です `.zip`ファイル。



 a| 
プロビジョニングパスフレーズ
 a| 
パスフレーズは、 StorageGRIDシステムが最初にインストールされたときに作成され、文書化されます。プロビジョニングパスフレーズは、 `Passwords.txt`ファイル。



 a| 
関連ドキュメント
 a| 
`readme.txt`修正プログラムのファイル。このファイルは、修正プログラムのダウンロード ページに含まれています。必ず確認してください `readme`修正プログラムを適用する前に、ファイルを注意深く確認してください。

|===