---
permalink: maintain/powering-off-and-on-all-nodes-in-grid.html 
sidebar: sidebar 
keywords: storagegrid, recover, power nodes, power on nodes, power off nodes, power down nodes 
summary: たとえば、データ センターを移動する場合は、 StorageGRIDシステム全体をシャットダウンする必要がある場合があります。これらの手順では、制御されたシャットダウンと起動を実行するための推奨シーケンスの概要を示します。 
---
= グリッド内のすべてのノードの電源をオフにしてオンにする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
たとえば、データ センターを移動する場合は、 StorageGRIDシステム全体をシャットダウンする必要がある場合があります。これらの手順では、制御されたシャットダウンと起動を実行するための推奨シーケンスの概要を示します。

サイトまたはグリッド内のすべてのノードの電源をオフにすると、ストレージ ノードがオフラインの間は取り込まれたオブジェクトにアクセスできなくなります。



== サービスを停止し、グリッドノードをシャットダウンする

StorageGRIDシステムの電源をオフにする前に、各グリッド ノードで実行されているすべてのサービスを停止し、すべての VMware 仮想マシン、コンテナ エンジン、およびStorageGRIDアプライアンスをシャットダウンする必要があります。

.タスク概要
まず管理ノードとゲートウェイ ノードのサービスを停止し、次にストレージ ノードのサービスを停止します。

このアプローチにより、プライマリ管理ノードを使用して、他のグリッド ノードのステータスを可能な限り長く監視できます。


NOTE: 単一のホストに複数のグリッド ノードが含まれている場合は、そのホスト上のすべてのノードを停止するまでホストをシャットダウンしないでください。ホストにプライマリ管理ノードが含まれている場合は、最後にそのホストをシャットダウンします。


NOTE: 必要に応じて、link:linux-migrating-grid-node-to-new-host.html["ある Linux ホストから別の Linux ホストにノードを移行する"]グリッドの機能や可用性に影響を与えずにホストのメンテナンスを実行します。

.手順
. すべてのクライアント アプリケーションによるグリッドへのアクセスを停止します。
. [[log_in_to_gn]]各ゲートウェイノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。


+
ルートとしてログインすると、プロンプトは `$`に `#`。

. [[stop_all_services]]ノード上で実行されているすべてのサービスを停止します。 `service servermanager stop`
+
サービスのシャットダウンには最大 15 分かかる場合があり、シャットダウン プロセスを監視するためにシステムにリモートでログインする必要がある場合があります。

. 前の 2 つの手順を繰り返して、すべてのストレージ ノードと非プライマリ管理ノード上のサービスを停止します。
+
これらのノード上のサービスは任意の順序で停止できます。

+

NOTE: 発行する場合は `service servermanager stop`アプライアンス ストレージ ノード上のサービスを停止するコマンドを使用する場合は、アプライアンスの電源を入れ直してノードを再起動する必要があります。

. プライマリ管理ノードの場合は、以下の手順を繰り返します。<<log_in_to_gn,ノードにログインする>>そして<<stop_all_services,ノード上のすべてのサービスを停止する>>。
. Linux ホスト上で実行されているノードの場合:
+
.. ホスト オペレーティング システムにログインします。
.. ノードを停止します。 `storagegrid node stop`
.. ホスト オペレーティング システムをシャットダウンします。


. VMware 仮想マシン上で実行されているノードおよびアプライアンス ストレージ ノードの場合は、シャットダウン コマンドを発行します。 `shutdown -h now`
+
結果に関係なくこの手順を実行します。 `service servermanager stop`指示。

+
アプライアンスの場合、このコマンドはコンピューティング コントローラーをシャットダウンしますが、アプライアンスの電源はオンのままです。次のステップを完了する必要があります。

. アプライアンス ノードがある場合は、アプライアンスの手順に従います。
+
[role="tabbed-block"]
====
.SG110またはSG1100
--
.. 機器の電源をオフにします。
.. 青い電源 LED が消えるまで待ちます。


--
.SG100またはSG1000
--
.. 機器の電源をオフにします。
.. 青い電源 LED が消えるまで待ちます。


--
.SG6160
--
.. SG6100-CN ストレージ コントローラの電源をオフにします。
.. SG6100-CN ストレージ コントローラの青色の電源 LED が消えるまで待ちます。


--
.SGF6112
--
.. 機器の電源をオフにします。
.. 青い電源 LED が消えるまで待ちます。


--
.SG6000
--
.. ストレージ コントローラーの背面にある緑色の Cache Active LED が消灯するまで待ちます。
+
この LED は、キャッシュされたデータをドライブに書き込む必要があるときに点灯します。電源をオフにする前に、この LED がオフになるまで待つ必要があります。

.. 機器の電源をオフにして、青色の電源 LED が消えるまで待ちます。


--
.SG5800
--
.. ストレージ コントローラーの背面にある緑色の Cache Active LED が消灯するまで待ちます。
+
この LED は、キャッシュされたデータをドライブに書き込む必要があるときに点灯します。電源をオフにする前に、この LED がオフになるまで待つ必要があります。

.. SANtricity System Manager のホームページから、*進行中の操作の表示*を選択します。
.. 次の手順に進む前に、すべての操作が完了していることを確認してください。
.. コントローラー シェルフの両方の電源スイッチをオフにし、コントローラー シェルフのすべての LED がオフになるまで待ちます。


--
.SG5700
--
.. ストレージ コントローラーの背面にある緑色の Cache Active LED が消灯するまで待ちます。
+
この LED は、キャッシュされたデータをドライブに書き込む必要があるときに点灯します。電源をオフにする前に、この LED がオフになるまで待つ必要があります。

.. 機器の電源をオフにし、すべての LED と 7 セグメント ディスプレイのアクティビティが停止するまで待ちます。


--
====
. 必要に応じて、コマンド シェルからログアウトします。 `exit`
+
StorageGRIDグリッドはシャットダウンされました。





== グリッドノードを起動する


CAUTION: グリッド全体が 15 日以上シャットダウンされている場合は、グリッド ノードを起動する前にテクニカル サポートに連絡する必要があります。 Cassandra データを再構築する回復手順を実行しないでください。データが失われることがあります。

可能であれば、次の順序でグリッド ノードの電源をオンにします。

* まず管理ノードに電源を供給します。
* 最後にゲートウェイ ノードに電源を供給します。



NOTE: ホストに複数のグリッド ノードが含まれている場合、ホストの電源をオンにすると、ノードは自動的にオンラインに戻ります。

.手順
. プライマリ管理ノードと非プライマリ管理ノードのホストの電源をオンにします。
+

NOTE: ストレージ ノードが再起動されるまで、管理ノードにログインすることはできません。

. すべてのストレージ ノードのホストの電源をオンにします。
+
これらのノードは任意の順序で電源をオンにできます。

. すべてのゲートウェイ ノードのホストの電源をオンにします。
. グリッド マネージャーにSign in。
. *NODES* を選択し、グリッド ノードのステータスを監視します。ノード名の横に警告アイコンがないことを確認します。


.関連情報
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112およびSG6160ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["SG110およびSG1100サービス アプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100およびSG1000サービス アプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["SG6000ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/index.html["SG5800ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["SG5700ストレージアプライアンス"^]

