---
permalink: maintain/preparing-appliance-storage-node-for-reinstallation.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: アプライアンス ストレージ ノードをリカバリする場合は、まずアプライアンスを準備してStorageGRIDソフトウェアを再インストールする必要があります。 
---
= アプライアンス ストレージ ノードの再インストールの準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプライアンス ストレージ ノードをリカバリする場合は、まずアプライアンスを準備してStorageGRIDソフトウェアを再インストールする必要があります。

.手順
. 障害が発生したストレージノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。


+
ルートとしてログインすると、プロンプトは `$`に `#`。

. StorageGRIDソフトウェアをインストールするためにアプライアンス ストレージ ノードを準備します。 `sgareinstall`
. 続行するように求められたら、次のように入力します。 `y`
+
アプライアンスが再起動し、SSH セッションが終了します。  StorageGRIDアプライアンス インストーラが使用可能になるまでに通常は約 5 分かかりますが、場合によっては最大 30 分ほど待つ必要があることもあります。

+

CAUTION: 電源を入れ直したり、アプライアンスをリセットしたりして再起動を早めようとしないでください。  BIOS、 BMC、またはその他のファームウェアの自動アップグレードが中断される可能性があります。

+
StorageGRIDアプライアンスのストレージ ノードがリセットされ、ストレージ ノード上のデータにアクセスできなくなります。元のインストール プロセス中に構成された IP アドレスはそのまま残りますが、手順が完了したらこれを確認することをお勧めします。

+
実行後 `sgareinstall`コマンドを実行すると、 StorageGRIDによってプロビジョニングされたすべてのアカウント、パスワード、および SSH キーが削除され、新しいホスト キーが生成されます。


