---
permalink: maintain/preparing-appliance-for-reinstallation-platform-replacement-only.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: サービス アプライアンスでホストされていたグリッド ノードを回復する場合は、まずアプライアンスを準備してStorageGRIDソフトウェアを再インストールする必要があります。 
---
= アプライアンスの再インストールの準備（プラットフォームの交換のみ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サービス アプライアンスでホストされていたグリッド ノードを回復する場合は、まずアプライアンスを準備してStorageGRIDソフトウェアを再インストールする必要があります。

サービス アプライアンスでホストされていた障害が発生したノードを交換する場合にのみ、この手順を実行してください。障害が発生したノードが元々 VMware または Linux ホストでホストされていた場合は、これらの手順に従わないでください。

.手順
. 障害が発生したグリッド ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。


+
ルートとしてログインすると、プロンプトは `$`に `#`。

. StorageGRIDソフトウェアをインストールするためにアプライアンスを準備します。入力： `sgareinstall`
. 続行するように求められたら、次のように入力します。 `y`
+
アプライアンスが再起動し、SSH セッションが終了します。  StorageGRIDアプライアンス インストーラが使用可能になるまでに通常は約 5 分かかりますが、場合によっては最大 30 分ほど待つ必要があることもあります。

+
サービス アプライアンスがリセットされ、グリッド ノード上のデータにアクセスできなくなります。元のインストール プロセス中に構成された IP アドレスはそのまま残りますが、手順が完了したらこれを確認することをお勧めします。

+
実行後 `sgareinstall`コマンドを実行すると、 StorageGRIDによってプロビジョニングされたすべてのアカウント、パスワード、および SSH キーが削除され、新しいホスト キーが生成されます。


