---
permalink: maintain/rebooting-grid-node-from-grid-manager.html 
sidebar: sidebar 
keywords: reboot grid node, tasks tab 
summary: 「ノード」ページの「タスク」タブから個々のグリッド ノードを再起動できます。 
---
= タスクタブからグリッドノードを再起動します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「ノード」ページの「タスク」タブから個々のグリッド ノードを再起動できます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["メンテナンスまたはルートアクセス権限"]。
* プロビジョニング パスフレーズを持っています。
* プライマリ管理ノードまたは任意のストレージ ノードを再起動する場合は、次の考慮事項を確認してください。
+
** プライマリ管理ノードを再起動すると、ブラウザは一時的にグリッド マネージャにアクセスできなくなります。
** 特定のサイトで 2 つ以上のストレージ ノードを再起動すると、再起動中は特定のオブジェクトにアクセスできなくなる可能性があります。この問題は、いずれかの ILM ルールで *デュアル コミット* 取り込みオプションが使用されている場合 (またはルールで *バランス* が指定されていて、必要なすべてのコピーをすぐに作成できない場合) に発生する可能性があります。この場合、 StorageGRID は新しく取り込まれたオブジェクトを同じサイト上の 2 つのストレージ ノードにコミットし、後で ILM を評価します。
** ストレージ ノードの再起動中にすべてのオブジェクトにアクセスできるようにするには、ノードを再起動する約 1 時間前に、サイトでのオブジェクトの取り込みを停止します。




.タスク概要
StorageGRIDがグリッドノードを再起動すると、 `reboot`ノード上でコマンドを実行し、ノードをシャットダウンして再起動します。すべてのサービスが自動的に再起動されます。

* VMware ノードを再起動すると、仮想マシンも再起動します。
* Linux ノードを再起動すると、コンテナも再起動されます。
* StorageGRIDアプライアンス ノードを再起動すると、コンピューティング コントローラも再起動されます。



TIP: 複数のノードを再起動する必要がある場合は、link:../maintain/rolling-reboot-procedure.html["ローリング再起動手順"] 。

.手順
. 「NODES」を選択します。
. 再起動するグリッド ノードを選択します。
. *タスク*タブを選択します。
. *再起動*を選択します。
+
確認ダイアログボックスが表示されます。プライマリ管理ノードを再起動する場合は、サービスが停止するとブラウザとグリッド マネージャの接続が一時的に失われることを通知する確認ダイアログ ボックスが表示されます。

. プロビジョニング パスフレーズを入力し、[*OK*] を選択します。
. ノードが再起動するまで待ちます。
+
サービスの停止には時間がかかる場合があります。

+
ノードが再起動中の場合、[ノード] ページのノードに灰色 (管理上ダウン) アイコンが表示されます。すべてのサービスが再開され、ノードがグリッドに正常に接続されると、[ノード] ページに通常のステータス (ノード名の左側にアイコンが表示されない) が表示され、アクティブなアラートがなく、ノードがグリッドに接続されていることが示されます。


