---
permalink: maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html 
sidebar: sidebar 
keywords: storagegrid, recover, maintenance, maintain, failed storage volumes, failed volumes, cassandra, cassandra rebuild, rebuild cassandra, cassandra database 
summary: 障害が発生したストレージ ボリューム上のストレージを再フォーマットして再マウントし、システムで必要と判断された場合はストレージ ノード上の Cassandra データベースを再構築するスクリプトを実行する必要があります。 
---
= 障害が発生したストレージボリュームを回復し、Cassandra データベースを再構築する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生したストレージ ボリューム上のストレージを再フォーマットして再マウントし、システムで必要と判断された場合はストレージ ノード上の Cassandra データベースを再構築するスクリプトを実行する必要があります。

.開始する前に
* あなたは `Passwords.txt`ファイル。
* サーバー上のシステム ドライブはそのままです。
* 障害の原因は特定されており、必要に応じて交換用のストレージ ハードウェアがすでに取得されています。
* 交換用ストレージの合計サイズは元のストレージと同じです。
* ストレージ ノードの廃止が進行中でないことを確認したか、ノードの廃止手順を一時停止しました。(グリッド マネージャーで、*メンテナンス* > *タスク* > *廃止* を選択します。)
* 拡張が進行中ではないことを確認しました。(グリッド マネージャーで、*メンテナンス* > *タスク* > *拡張* を選択します。)
* あなたが持っているlink:reviewing-warnings-about-storage-volume-recovery.html["ストレージボリュームの回復に関する警告を確認しました"]。


.手順
. 必要に応じて、先ほど特定してマウント解除した障害の発生したストレージ ボリュームに関連付けられている、障害の発生した物理ストレージまたは仮想ストレージを交換します。
+
この手順ではボリュームを再マウントしないでください。ストレージが再マウントされ、 `/etc/fstab`後のステップで。

. グリッドマネージャで*ノード*に移動します > `*appliance Storage Node*` > *ハードウェア*。ページのStorageGRIDアプライアンス セクションで、ストレージ RAID モードが正常であることを確認します。
. 障害が発生したストレージノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
+
ルートとしてログインすると、プロンプトは `$`に `#`。



. テキストエディタ（viまたはvim）を使用して、障害が発生したボリュームを `/etc/fstab`ファイルを保存してください。
+

NOTE: 障害が発生したボリュームをコメントアウトする `/etc/fstab`ファイルが不十分です。ボリュームは削除する必要があります `fstab`回復プロセスでは、 `fstab`ファイルはマウントされたファイルシステムと一致します。

. 障害が発生したストレージ ボリュームを再フォーマットし、必要に応じて Cassandra データベースを再構築します。入力： `reformat_storage_block_devices.rb`
+
** ストレージ ボリューム 0 がマウント解除されると、Cassandra サービスが停止されていることを示すプロンプトとメッセージが表示されます。
** 必要に応じて、Cassandra データベースを再構築するように求められます。
+
*** 警告を確認してください。いずれにも該当しない場合は、Cassandra データベースを再構築します。入力してください: *y*
*** 複数のストレージ ノードがオフラインの場合、または過去 15 日間に別のストレージ ノードが再構築された場合。入力してください: *n*
+
スクリプトは Cassandra を再構築せずに終了します。テクニカル サポートにお問い合わせください。



** ストレージ ノード上の各 rangedb ドライブについて、次のことを尋ねられます。 `Reformat the rangedb drive _<name>_ (device _<major number>:<minor number>_)? [y/n]?` 、次のいずれかの応答を入力します。
+
*** *y* を押すと、エラーが発生したドライブが再フォーマットされます。これにより、ストレージボリュームが再フォーマットされ、再フォーマットされたストレージボリュームが `/etc/fstab`ファイル。
*** *n* ドライブにエラーがなく、再フォーマットしたくない場合は、*n* を指定します。
+

NOTE: *n* を選択するとスクリプトが終了します。ドライブをマウントするか (ドライブ上のデータを保持する必要があると思われる場合、またはドライブが誤ってマウント解除された場合)、ドライブを取り外します。次に、 `reformat_storage_block_devices.rb`再度コマンドを実行します。

+

NOTE: 一部のStorageGRIDリカバリ手順では、Reaper を使用して Cassandra の修復を処理します。関連するサービスまたは必要なサービスが開始されるとすぐに、修復が自動的に実行されます。スクリプト出力に「reaper」または「Cassandra repair」と記載されていることに気付くかもしれません。修復が失敗したことを示すエラー メッセージが表示された場合は、エラー メッセージに示されているコマンドを実行します。

+
次の出力例では、ドライブ `/dev/sdf`再フォーマットする必要があり、Cassandra を再構築する必要はありませんでした。

+
[listing]
----
root@DC1-S1:~ # reformat_storage_block_devices.rb
Formatting devices that are not in use...
Skipping in use device /dev/sdc
Skipping in use device /dev/sdd
Skipping in use device /dev/sde
Reformat the rangedb drive /dev/sdf (device 8:64)? [Y/n]? y
Successfully formatted /dev/sdf with UUID b951bfcb-4804-41ad-b490-805dfd8df16c
All devices processed
Running: /usr/local/ldr/setup_rangedb.sh 12368435
Cassandra does not need rebuilding.
Starting services.
Informing storage services of new volume

Reformatting done.  Now do manual steps to
restore copies of data.
----






ストレージボリュームが再フォーマットされ、再マウントされ、必要なCassandra操作が完了したら、link:../maintain/restoring-volume.html["グリッド マネージャーを使用してオブジェクト データを復元する"] 。
