---
permalink: maintain/recovering-from-storage-volume-failure-where-system-drive-is-intact.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage volume failure, volume failure, system drive intact 
summary: ストレージ ノード上の 1 つ以上のストレージ ボリュームに障害が発生しているが、システム ドライブはそのままの状態である場合、ソフトウェア ベースのストレージ ノードを回復するには、一連のタスクを完了する必要があります。ストレージ ボリュームのみに障害が発生した場合、ストレージ ノードは引き続きStorageGRIDシステムで使用できます。 
---
= システムドライブが損傷していないストレージボリュームの障害から回復する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ ノード上の 1 つ以上のストレージ ボリュームに障害が発生しているが、システム ドライブはそのままの状態である場合、ソフトウェア ベースのストレージ ノードを回復するには、一連のタスクを完了する必要があります。ストレージ ボリュームのみに障害が発生した場合、ストレージ ノードは引き続きStorageGRIDシステムで使用できます。


NOTE: この回復手順は、ソフトウェア ベースのストレージ ノードにのみ適用されます。アプライアンス ストレージ ノードでストレージ ボリュームに障害が発生した場合は、代わりにアプライアンスの手順を使用します。link:recovering-storagegrid-appliance-storage-node.html["アプライアンスストレージノードの回復"] 。

この回復手順には、次のタスクが含まれます。

* link:reviewing-warnings-about-storage-volume-recovery.html["ストレージボリュームの回復に関する警告を確認する"]
* link:identifying-and-unmounting-failed-storage-volumes.html["障害が発生したストレージボリュームを識別してマウント解除する"]
* link:recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["ボリュームを回復し、Cassandraデータベースを再構築します"]
* link:restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["オブジェクトデータを復元する"]
* link:checking-storage-state-after-recovering-storage-volumes.html["保管状態を確認する"]

