---
permalink: maintain/recovering-from-storage-node-failures.html 
sidebar: sidebar 
keywords: recover, storage node failure, Reaper 
summary: 障害が発生したストレージ ノードを回復する手順は、障害の種類と障害が発生したストレージ ノードの種類によって異なります。 
---
= ストレージノードの障害からの回復
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生したストレージ ノードを回復する手順は、障害の種類と障害が発生したストレージ ノードの種類によって異なります。

この表を使用して、障害が発生したストレージ ノードの回復手順を選択します。

[cols="1a,1a,1a"]
|===
| 問題 | アクション | 注記 


 a| 
* 複数のストレージ ノードに障害が発生しました。
* ストレージ ノードの障害または回復後 15 日以内に 2 番目のストレージ ノードに障害が発生しました。
+
これには、別のストレージ ノードのリカバリが進行中に、ストレージ ノードに障害が発生した場合も含まれます。


 a| 
テクニカル サポートにお問い合わせください。
 a| 
複数のストレージ ノード (または 15 日以内に複数のストレージ ノード) を回復すると、Cassandra データベースの整合性に影響が及び、データが失われる可能性があります。

テクニカル サポートは、2 番目のストレージ ノードのリカバリをいつ開始しても安全かを判断できます。

*注意*: 1 つのサイトで ADC サービスを含む複数のストレージ ノードに障害が発生した場合、そのサイトの保留中のプラットフォーム サービス要求はすべて失われます。



 a| 
サイトの複数のストレージ ノードに障害が発生したか、サイト全体に障害が発生しました。
 a| 
テクニカル サポートにお問い合わせください。サイトの回復手順を実行する必要がある場合があります。
 a| 
テクニカル サポートが状況を評価し、回復計画を作成します。見るlink:how-site-recovery-is-performed-by-technical-support.html["テクニカルサポートがサイトを復旧する方法"] 。



 a| 
アプライアンス ストレージ ノードに障害が発生しました。
 a| 
link:recovering-storagegrid-appliance-storage-node.html["アプライアンスストレージノードの回復"]
 a| 
アプライアンス ストレージ ノードの回復手順は、すべての障害に対して同じです。



 a| 
1 つ以上のストレージ ボリュームに障害が発生しましたが、システム ドライブは正常です
 a| 
link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["システムドライブが損傷していないストレージボリュームの障害から回復する"]
 a| 
この手順は、ソフトウェア ベースのストレージ ノードに使用されます。



 a| 
システムドライブに障害が発生しました。
 a| 
link:reviewing-warnings-for-system-drive-recovery.html["システムドライブ障害からの回復"]
 a| 
ノードの交換手順は、デプロイメント プラットフォームと、ストレージ ボリュームにも障害が発生しているかどうかによって異なります。

|===

NOTE: 一部のStorageGRIDリカバリ手順では、Reaper を使用して Cassandra の修復を処理します。関連するサービスまたは必要なサービスが開始されるとすぐに、修復が自動的に実行されます。スクリプト出力に「reaper」または「Cassandra repair」と記載されていることに気付くかもしれません。修復が失敗したことを示すエラー メッセージが表示された場合は、エラー メッセージに示されているコマンドを実行します。
