---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: ロード バランサ サービスのエンドポイントを構成し、ポート再マップのマップ先ポートとして既に構成されているポートを使用する場合は、まず既存のポート再マップを削除する必要があります。そうしないと、エンドポイントは有効になりません。競合する再マップされたポートを持つ各管理ノードとゲートウェイ ノードでスクリプトを実行して、ノードのすべてのポートの再マップを削除する必要があります。 
---
= ポートの再マップを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロード バランサ サービスのエンドポイントを構成し、ポート再マップのマップ先ポートとして既に構成されているポートを使用する場合は、まず既存のポート再マップを削除する必要があります。そうしないと、エンドポイントは有効になりません。競合する再マップされたポートを持つ各管理ノードとゲートウェイ ノードでスクリプトを実行して、ノードのすべてのポートの再マップを削除する必要があります。

.タスク概要
この手順により、すべてのポートの再マップが削除されます。再マップの一部を保持する必要がある場合は、テクニカル サポートにお問い合わせください。

ロードバランサエンドポイントの構成については、以下を参照してください。link:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイントの構成"] 。


NOTE: ポートの再マップによってクライアント アクセスが提供される場合は、サービスの損失を回避するために、ロード バランサのエンドポイントとして別のポートを使用するようにクライアントを再構成します。そうしないと、ポート マッピングを削除するとクライアント アクセスが失われるため、適切にスケジュールする必要があります。


NOTE: この手順は、ベアメタル ホスト上にコンテナとして展開されたStorageGRIDシステムでは機能しません。説明書をご覧くださいlink:removing-port-remaps-on-bare-metal-hosts.html["ベアメタルホスト上のポート再マップの削除"]。

.手順
. ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh -p 8022 admin@node_IP`
+
ポート 8022 はベース OS の SSH ポートであり、ポート 22 はStorageGRIDを実行しているコンテナ エンジンの SSH ポートです。

.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
+
ルートとしてログインすると、プロンプトは `$`に `#`。



. 次のスクリプトを実行します。 `remove-port-remap.sh`
. ノードを再起動します。 `reboot`
. コマンド シェルからログアウトします。 `exit`
. 競合する再マップされたポートを持つ各管理ノードとゲートウェイ ノードでこれらの手順を繰り返します。

