---
permalink: maintain/rename-grid-site-node-overview.html 
sidebar: sidebar 
keywords: rename grid, rename site, rename node, display name, system name 
summary: 必要に応じて、グリッド マネージャー全体でグリッド全体、各サイト、各ノードに対して表示される表示名を変更できます。表示名は、必要なときにいつでも安全に更新できます。 
---
= 名前変更手順を使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必要に応じて、グリッド マネージャ全体、各サイト、および各ノードに表示される表示名を変更できます。表示名は、必要なときにいつでも安全に更新できます。



== 名前の変更手順は何ですか?

StorageGRID を最初にインストールするときに、グリッド、各サイト、および各ノードの名前を指定します。これらの初期名は「システム名」と呼ばれ、 StorageGRID全体で最初に表示される名前です。

システム名は内部StorageGRID操作に必要であり、変更できません。ただし、名前変更手順を使用して、グリッド、各サイト、および各ノードの新しい _表示名_ を定義することができます。これらの表示名は、基盤となるシステム名の代わりに (または場合によっては基盤となるシステム名に加えて)、さまざまなStorageGRID の場所に表示されます。

名前変更手順は、タイプミスを修正したり、異なる命名規則を実装したり、サイトとそのすべてのノードが再配置されたことを示す場合に使用します。システム名とは異なり、表示名は、 StorageGRID の操作に影響を与えることなく、必要に応じていつでも更新できます。



== システム名と表示名はどこに表示されますか?

次の表は、 StorageGRIDユーザー インターフェイスおよびStorageGRIDファイルでシステム名と表示名が表示される場所をまとめたものです。

[cols="2a,2a,3a"]
|===
| Location | システム名 | 表示名 


 a| 
グリッドマネージャーページ
 a| 
アイテムの名前が変更されない限り表示されます
 a| 
項目の名前が変更されると、システム名の代わりに次の場所に表示されます。

* ダッシュボード
* [Nodes]ページ
* 高可用性グループ、ロードバランサエンドポイント、VLANインターフェース、キー管理サーバ、グリッドパスワード、ファイアウォール制御の構成ページ
* アラート
* ストレージプールの定義
* オブジェクトメタデータ検索ページ
* アップグレード、ホットフィックス、 SANtricity OS のアップグレード、廃止、拡張、回復、オブジェクトの存在確認などのメンテナンス手順に関連するページ
* サポートページ（ログと診断）
* シングル サインオン ページ、管理ノードの詳細の表にある管理ノードのホスト名の横




 a| 
*ノード* > ノードの*概要*タブ
 a| 
常に表示
 a| 
アイテムの名前が変更された場合にのみ表示されます



 a| 
グリッド マネージャーの従来のページ (例: *サポート* > *グリッド トポロジ*)
 a| 
表示
 a| 
表示されません



 a| 
*ノードヘルス* API
 a| 
常に返される
 a| 
アイテムの名前が変更された場合にのみ返されます



 a| 
SSH を使用してノードにアクセスするときにプロンプトを表示する
 a| 
アイテムの名前が変更されていない限り、プライマリ名として表示されます。

`admin@SYSTEM-NAME: ~ $`

項目名を変更するときに括弧内に含まれるもの:

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`
 a| 
アイテムの名前が変更されたときにプライマリ名として表示されるもの:

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`



 a| 
`Passwords.txt`リカバリパッケージ内のファイル
 a| 
表示 `Server Name`
 a| 
表示 `Display Name`



 a| 
`/etc/hosts`すべてのノード上のファイル

例えば：

`10.96.99.128 SYSTEM-NAME 28989c59-a2c3-4d30-bb09-6879adf2437f DISPLAY-NAME localhost-grid # storagegrid-gen-host`
 a| 
常に2列目に表示されます
 a| 
アイテムの名前が変更されると、4番目の列に表示されます



 a| 
`topology-display-names.json`（ AutoSupportデータに含まれる）
 a| 
含まれません
 a| 
項目の名前が変更されていない限り空です。それ以外の場合は、グリッド、サイト、およびノード ID を表示名にマッピングします。

|===


== 表示名の要件

この手順を使用する前に、表示名の要件を確認してください。



=== ノードの表示名

ノードの表示名は、次の規則に従う必要があります。

* StorageGRIDシステム全体で一意である必要があります。
* StorageGRIDシステム内の他の項目のシステム名と同じにすることはできません。
* 1 文字以上 32 文字以下でなければなりません。
* 数字、ハイフン (-)、大文字、小文字を含めることができます。
* 文字または数字で開始または終了できますが、ハイフンで開始または終了することはできません。
* すべて数字にすることはできません。
* 大文字と小文字は区別されません。例えば、 `DC1-ADM`そして `dc1-adm`重複とみなされます。


名前の変更によって表示名またはシステム名が重複しない限り、以前別のノードで使用されていた表示名を使用してノードの名前を変更できます。



=== グリッドとサイトの表示名

グリッドとサイトの表示名は、次の例外を除いて同じルールに従います。

* スペースを含めることができます。
* 次の特殊文字を含めることができます: `= - _ : , . @ !`
* ハイフンを含む特殊文字で開始および終了できます。
* すべて数字または特殊文字を使用できます。




== 表示名のベストプラクティス

複数の項目の名前を変更する予定の場合は、この手順を使用する前に、一般的な命名スキームを文書化してください。名前が一意で、一貫性があり、一目で理解しやすいことを保証するシステムを考え出してください。

組織の要件に適合する任意の命名規則を使用できます。何を含めるかについては、次の基本的な提案を検討してください。

* *サイトインジケーター*: 複数のサイトがある場合は、各ノード名にサイト コードを追加します。
* *ノード タイプ*: ノード名は通常、ノードのタイプを示します。次のような略語も使えます `s`、 `adm` 、 そして `gw`(ストレージ ノード、管理ノード、ゲートウェイ ノード)。
* *ノード番号*: サイトに特定のタイプのノードが複数含まれている場合は、各ノードの名前に一意の番号を追加します。


時間の経過とともに変化する可能性のある名前に具体的な詳細を追加する前に、よく考えてください。たとえば、IP アドレスは変更される可能性があるため、ノード名に IP アドレスを含めないでください。同様に、機器を移動したりハードウェアをアップグレードしたりすると、ラックの場所やアプライアンスのモデル番号が変わることがあります。



=== 表示名の例

StorageGRIDシステムに 3 つのデータ センターがあり、各データ センターに異なるタイプのノードがあるとします。表示名は次のように単純なものになります。

* *グリッド*： `StorageGRID Deployment`
* *最初のサイト*: `Data Center 1`
+
** `dc1-adm1`
** `dc1-s1`
** `dc1-s2`
** `dc1-s3`
** `dc1-gw1`


* *2番目のサイト*: `Data Center 2`
+
** `dc2-adm2`
** `dc2-s1`
** `dc2-s2`
** `dc2-s3`


* *3番目のサイト*: `Data Center 3`
+
** `dc3-s1`
** `dc3-s2`
** `dc3-s3`



