---
permalink: maintain/restoring-prometheus-metrics-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore metrics, restore prometheus, primary admin node 
summary: オプションで、障害が発生したプライマリ管理ノード上で Prometheus によって維持される履歴メトリックを保持できます。  Prometheus メトリックは、 StorageGRIDシステムに別の管理ノードが含まれている場合にのみ復元できます。 
---
= プライマリ管理ノードを復旧するときに Prometheus メトリックを復元する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オプションで、障害が発生したプライマリ管理ノード上で Prometheus によって維持される履歴メトリックを保持できます。  Prometheus メトリックは、 StorageGRIDシステムに別の管理ノードが含まれている場合にのみ復元できます。

.開始する前に
* 回復された管理ノードがインストールされ、実行されています。
* StorageGRIDシステムには、少なくとも 2 つの管理ノードが含まれます。
* あなたは `Passwords.txt`ファイル。
* プロビジョニング パスフレーズを持っています。


.タスク概要
管理ノードに障害が発生すると、管理ノード上の Prometheus データベースに保持されているメトリックが失われます。管理ノードを回復すると、ソフトウェアのインストール プロセスによって新しい Prometheus データベースが作成されます。回復された管理ノードが起動すると、 StorageGRIDシステムの新規インストールを実行した場合と同じようにメトリックが記録されます。

プライマリ管理ノードを復元し、 StorageGRIDシステムに別の管理ノードがある場合は、プライマリ以外の管理ノード (_ソース管理ノード_) から復元したプライマリ管理ノードに Prometheus データベースをコピーすることで、履歴メトリックを復元できます。システムにプライマリ管理ノードしかない場合は、Prometheus データベースを復元できません。


NOTE: Prometheus データベースのコピーには 1 時間以上かかる場合があります。ソース管理ノードでサービスが停止している間は、一部の Grid Manager 機能は利用できなくなります。

.手順
. ソース管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。


. ソース管理ノードから、Prometheus サービスを停止します。 `service prometheus stop`
. 回復した管理ノードで次の手順を実行します。
+
.. 回復した管理ノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... 記載されているパスワードを入力してください `Passwords.txt`ファイル。
... ルートに切り替えるには、次のコマンドを入力します。 `su -`
... 記載されているパスワードを入力してください `Passwords.txt`ファイル。


.. Prometheus サービスを停止します。 `service prometheus stop`
.. SSH エージェントに SSH 秘密キーを追加します。入力：``ssh-add``
.. に記載されているSSHアクセスパスワードを入力してください `Passwords.txt`ファイル。
.. ソース管理ノードから回復した管理ノードに Prometheus データベースをコピーします。 `/usr/local/prometheus/bin/prometheus-clone-db.sh Source_Admin_Node_IP`
.. プロンプトが表示されたら、*Enter* キーを押して、回復した管理ノード上の新しい Prometheus データベースを破棄することを確認します。
+
元の Prometheus データベースとその履歴データは、回復された管理ノードにコピーされます。コピー操作が完了すると、スクリプトは回復された管理ノードを起動します。次のステータスが表示されます。

+
データベースのクローンを作成し、サービスを開始しています

.. 他のサーバーへのパスワードなしのアクセスが不要になったら、SSH エージェントから秘密キーを削除します。入力：``ssh-add -D``


. ソース管理ノードでPrometheusサービスを再起動します。.`service prometheus start`

