---
permalink: maintain/restoring-admin-node-database-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, non-primary admin node 
summary: 障害が発生した非プライマリ管理ノードの属性とアラートに関する履歴情報を保持する場合は、プライマリ管理ノードから管理ノード データベースを復元できます。 
---
= 非プライマリ管理ノードを回復するときに管理ノードデータベースを復元する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生した非プライマリ管理ノードの属性とアラートに関する履歴情報を保持する場合は、プライマリ管理ノードから管理ノード データベースを復元できます。

.開始する前に
* 回復された管理ノードがインストールされ、実行されています。
* StorageGRIDシステムには、少なくとも 2 つの管理ノードが含まれます。
* あなたは `Passwords.txt`ファイル。
* プロビジョニング パスフレーズを持っています。


.タスク概要
管理ノードに障害が発生すると、その管理ノード データベースに保存されている履歴情報が失われます。このデータベースには次の情報が含まれています。

* アラート履歴
* ノードページの従来のチャートで使用される履歴属性データ


管理ノードを回復すると、ソフトウェアのインストール プロセスによって、回復されたノード上に空の管理ノード データベースが作成されます。ただし、新しいデータベースには、現在システムの一部となっているサーバーおよびサービス、または後で追加されたサーバーおよびサービスに関する情報のみが含まれます。

プライマリ以外の管理ノードを復元した場合は、プライマリ管理ノード (_ソース管理ノード_) から回復したノードに管理ノード データベースをコピーすることで、履歴情報を復元できます。


NOTE: 管理ノード データベースのコピーには数時間かかる場合があります。ソース ノードでサービスが停止している間は、一部の Grid Manager 機能は利用できなくなります。

.手順
. ソース管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。


. ソース管理ノードから次のコマンドを実行します。次に、プロンプトが表示されたらプロビジョニング パスフレーズを入力します。 `recover-access-points`
. ソース管理ノードから、MI サービスを停止します。 `service mi stop`
. ソース管理ノードから、管理アプリケーション プログラム インターフェイス (mgmt-api) サービスを停止します。 `service mgmt-api stop`
. 回復した管理ノードで次の手順を実行します。
+
.. 回復した管理ノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... 記載されているパスワードを入力してください `Passwords.txt`ファイル。
... ルートに切り替えるには、次のコマンドを入力します。 `su -`
... 記載されているパスワードを入力してください `Passwords.txt`ファイル。


.. MI サービスを停止します。 `service mi stop`
.. mgmt-api サービスを停止します。 `service mgmt-api stop`
.. SSH エージェントに SSH 秘密キーを追加します。入力：``ssh-add``
.. に記載されているSSHアクセスパスワードを入力してください `Passwords.txt`ファイル。
.. ソース管理ノードから回復した管理ノードにデータベースをコピーします。 `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
.. プロンプトが表示されたら、回復した管理ノード上の MI データベースを上書きすることを確認します。
+
データベースとその履歴データは、回復された管理ノードにコピーされます。コピー操作が完了すると、スクリプトは回復された管理ノードを起動します。

.. 他のサーバーへのパスワードなしのアクセスが不要になったら、SSH エージェントから秘密キーを削除します。入力：``ssh-add -D``


. ソース管理ノードでサービスを再起動します。 `service servermanager start`

