---
permalink: maintain/restoring-audit-log-on-recovered-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore audit log, primary admin node 
summary: 障害が発生したプライマリ管理ノードから監査ログを保存できた場合は、それを回復するプライマリ管理ノードにコピーできます。 
---
= 回復したプライマリ管理ノードで監査ログを復元する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生したプライマリ管理ノードから監査ログを保存できた場合は、それを回復するプライマリ管理ノードにコピーできます。

.開始する前に
* 回復された管理ノードがインストールされ、実行されています。
* 元の管理ノードに障害が発生した後、監査ログを別の場所にコピーしました。


.タスク概要
管理ノードに障害が発生すると、その管理ノードに保存されている監査ログが失われる可能性があります。障害が発生した管理ノードから監査ログをコピーし、これらの監査ログを回復した管理ノードに復元することで、データの損失を防ぐことができる可能性があります。障害によっては、障害が発生した管理ノードから監査ログをコピーできない場合があります。その場合、デプロイメントに複数の管理ノードがある場合は、監査ログがすべての管理ノードに複製されるため、別の管理ノードから監査ログを回復できます。

管理ノードが 1 つしかなく、障害が発生したノードから監査ログをコピーできない場合、回復された管理ノードは、インストールが新規であるかのように監査ログにイベントを記録し始めます。

ログ機能を復元するには、管理ノードをできるだけ早く回復する必要があります。

[NOTE]
====
デフォルトでは、監査情報は管理ノードの監査ログに送信されます。次のいずれかに該当する場合は、これらの手順をスキップできます。

* 外部 Syslog サーバーを構成したため、監査ログは管理ノードではなく Syslog サーバーに送信されるようになりました。
* 監査メッセージは、それを生成したローカル ノードにのみ保存されるように明示的に指定しました。


見るlink:../monitor/configure-audit-messages.html["監査メッセージとログの保存先を構成する"]詳細については。

====
.手順
. 回復した管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@recovery_Admin_Node_IP`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。


+
ルートとしてログインすると、プロンプトが `$`に `#`。

. 保存された監査ファイルを確認します。 `cd /var/local/log`
. 保存した監査ログ ファイルを回復した管理ノードにコピーします。 `scp admin@_grid_node_IP_:/var/local/tmp/saved-audit-logs/YYYY* .`
+
プロンプトが表示されたら、管理者のパスワードを入力します。

. セキュリティのため、監査ログが回復された管理ノードに正常にコピーされたことを確認した後、障害が発生したグリッド ノードから監査ログを削除します。
. 回復された管理ノード上の監査ログ ファイルのユーザーとグループの設定を更新します。 `chown ams-user: bycast *`
. rootとしてログアウトします: `exit`

