---
permalink: maintain/reviewing-ilm-policy-and-storage-configuration.html 
sidebar: sidebar 
keywords: storagegrid, restore, ilm policy, storage configuration 
summary: ストレージ ノードを廃止する予定の場合は、廃止プロセスを開始する前に、 StorageGRIDシステムの ILM ポリシーを確認する必要があります。 
---
= ILMポリシーとストレージ構成を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ ノードを廃止する予定の場合は、廃止プロセスを開始する前に、 StorageGRIDシステムの ILM ポリシーを確認する必要があります。

廃止中、すべてのオブジェクト データは廃止されたストレージ ノードから他のストレージ ノードに移行されます。


NOTE: 廃止中に有効な ILM ポリシーが、廃止後に使用されるポリシーになります。廃止を開始する前と廃止が完了した後の両方で、このポリシーがデータ要件を満たしていることを確認する必要があります。

それぞれのルールを確認してくださいlink:../ilm/creating-ilm-policy.html["アクティブなILMポリシー"]ストレージノードの廃止に対応するために、 StorageGRIDシステムが適切なタイプと適切な場所に十分な容量を継続的に確保できるようにします。

次の点を考慮してください。

* ILM 評価サービスでは、ILM ルールが満たされるようにオブジェクト データをコピーすることは可能でしょうか?
* 廃止作業の進行中にサイトが一時的に利用できなくなった場合はどうなりますか? 追加のコピーを別の場所に作成することはできますか?
* 廃止プロセスはコンテンツの最終的な配布にどのような影響を与えますか? 記載の通りlink:consolidating-storage-nodes.html["ストレージノードの統合"]、 あなたがすべきlink:../expand/index.html["新しいストレージノードを追加する"]古いものを廃止する前に。小さなストレージ ノードを廃止した後、より大きな代替ストレージ ノードを追加すると、古いストレージ ノードの容量がほぼいっぱいになり、新しいストレージ ノードにはほとんどコンテンツが残らない可能性があります。新しいオブジェクト データの書き込み操作のほとんどは新しいストレージ ノードに向けられるため、システム操作の全体的な効率が低下します。
* システムには、アクティブな ILM ポリシーを満たすのに十分なストレージ ノードが常に含まれますか?
+

NOTE: 満たすことができない ILM ポリシーはバックログとアラートにつながり、 StorageGRIDシステムの動作が停止する可能性があります。



表に記載されている領域を評価して、廃止プロセスの結果として得られる提案されたトポロジが ILM ポリシーを満たしていることを確認します。

[cols="1a,2a"]
|===
| 評価対象領域 | 考慮すべきこと 


 a| 
使用可能容量
 a| 
廃止されるストレージ ノードに現在保存されているオブジェクト データの永続コピーを含む、 StorageGRIDシステムに保存されているすべてのオブジェクト データを収容するのに十分なストレージ容量はありますか?

廃止が完了した後、妥当な期間にわたって、保存されたオブジェクト データの予想される増加を処理するのに十分な容量がありますか?



 a| 
保管場所
 a| 
StorageGRIDシステム全体に十分な容量が残っている場合、その容量はStorageGRIDシステムのビジネス ルールを満たす適切な場所にありますか?



 a| 
ストレージ タイプ
 a| 
廃止が完了した後も適切なタイプの保管スペースは十分にあるでしょうか?

たとえば、ILM ルールでは、コンテンツの古くなるにつれて、コンテンツをある種類のストレージから別の種類のストレージに移動する場合があります。この場合、 StorageGRIDシステムの最終構成で適切なタイプの十分なストレージが利用可能であることを確認する必要があります。

|===