---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: ストレージ ノードの障害が発生したシステム ドライブをリカバリする前に、グリッド ノードのリカバリに関する一般的な警告と考慮事項、および次の特定の警告を確認してください。 
---
= ストレージノードシステムドライブの回復に関する警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの障害が発生したシステムドライブを復旧する前に、一般的なlink:warnings-and-considerations-for-grid-node-recovery.html["グリッドノードの回復に関する警告と考慮事項"]および以下の具体的な警告。

ストレージ ノードには、オブジェクト メタデータを含む Cassandra データベースがあります。次の状況では、Cassandra データベースが再構築される可能性があります。

* ストレージ ノードは、15 日以上オフラインになった後にオンラインに戻ります。
* ストレージ ボリュームに障害が発生しましたが、回復されました。
* システム ドライブおよび 1 つ以上のストレージ ボリュームに障害が発生し、回復されました。


Cassandra が再構築されると、システムは他のストレージ ノードからの情報を使用します。オフラインのストレージノードが多すぎると、一部の Cassandra データが利用できなくなる可能性があります。Cassandra が最近再構築された場合、Cassandra データはグリッド全体でまだ一貫していない可能性があります。オフラインのストレージ ノードが多すぎるときに Cassandra が再構築された場合、または 2 つ以上のストレージ ノードが 15 日以内に再構築された場合、データ損失が発生する可能性があります。


CAUTION: 複数のストレージ ノードに障害が発生した場合 (またはオフラインの場合) は、テクニカル サポートにお問い合わせください。次の回復手順を実行しないでください。データが失われる可能性があります。


CAUTION: ストレージ ノードの障害または回復後 15 日以内に 2 回目のストレージ ノード障害が発生した場合は、テクニカル サポートに連絡してください。  15 日以内に 2 つ以上のストレージ ノードで Cassandra を再構築すると、データが失われる可能性があります。


NOTE: サイトの複数のストレージ ノードに障害が発生した場合は、サイトの回復手順が必要になることがあります。見るlink:how-site-recovery-is-performed-by-technical-support.html["テクニカルサポートがサイトを復旧する方法"] 。


CAUTION: このストレージ ノードが読み取り専用メンテナンス モードになっていて、障害の発生したストレージ ボリュームを持つ別のストレージ ノードによるオブジェクトの取得を許可している場合は、この障害の発生したストレージ ノードを回復する前に、障害の発生したストレージ ボリュームを持つストレージ ノード上のボリュームを回復します。指示を参照してくださいlink:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["システムドライブが損傷していないストレージボリュームの障害から回復する"]。


CAUTION: ILM ルールが複製されたコピーを 1 つだけ保存するように設定されていて、そのコピーが障害が発生したストレージ ボリューム上に存在する場合、オブジェクトを回復することはできません。
