---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: グリッド ノードは、ノードのコマンド シェルからシャットダウンできます。 
---
= グリッドノードをシャットダウンする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド ノードは、ノードのコマンド シェルからシャットダウンできます。

.開始する前に
* あなたは `Passwords.txt`ファイル。


.タスク概要
この手順を実行する前に、次の考慮事項を確認してください。

* 一般に、中断を避けるため、一度に複数のノードをシャットダウンしないでください。
* ドキュメントまたはテクニカル サポートによって明示的に指示されていない限り、メンテナンス手順中にノードをシャットダウンしないでください。
* シャットダウン プロセスは、ノードがインストールされている場所に基づいて次のように実行されます。
+
** VMware ノードをシャットダウンすると、仮想マシンもシャットダウンされます。
** Linux ノードをシャットダウンすると、コンテナもシャットダウンされます。
** StorageGRIDアプライアンス ノードをシャットダウンすると、コンピューティング コントローラもシャットダウンされます。


* サイトで複数のストレージ ノードをシャットダウンする予定の場合は、ノードをシャットダウンする前に、そのサイトでのオブジェクトの取り込みを約 1 時間停止します。
+
いずれかの ILM ルールが *デュアル コミット* 取り込みオプションを使用する場合 (またはルールが *バランス* オプションを使用していて、必要なすべてのコピーをすぐに作成できない場合)、 StorageGRID は新しく取り込まれたオブジェクトを同じサイト上の 2 つのストレージ ノードにすぐにコミットし、後で ILM を評価します。サイト内の複数のストレージ ノードがシャットダウンされた場合、シャットダウン中は新しく取り込まれたオブジェクトにアクセスできない可能性があります。サイトに利用可能なストレージ ノードが少なすぎる場合も、書き込み操作が失敗する可能性があります。見るlink:../ilm/index.html["ILMでオブジェクトを管理する"] 。



.手順
. グリッド ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。


+
ルートとしてログインすると、プロンプトは `$`に `#`。

. すべてのサービスを停止します: `service servermanager stop`
+
サービスのシャットダウンには最大 15 分かかる場合があり、シャットダウン プロセスを監視するためにシステムにリモートでログインする必要がある場合があります。

. ノードが VMware 仮想マシン上で実行されている場合、またはアプライアンス ノードである場合は、シャットダウン コマンドを発行します。 `shutdown -h now`
+
結果に関係なくこの手順を実行します。 `service servermanager stop`指示。

+

NOTE: 発行後 `shutdown -h now`アプライアンス ノードでコマンドを実行する場合、ノードを再起動するにはアプライアンスの電源を入れ直す必要があります。

+
アプライアンスの場合、このコマンドはコントローラをシャットダウンしますが、アプライアンスの電源はオンのままです。次のステップを完了する必要があります。

. アプライアンス ノードの電源をオフにする場合は、アプライアンスの手順に従います。
+
[role="tabbed-block"]
====
.SG6160
--
.. SG6100-CN ストレージ コントローラの電源をオフにします。
.. SG6100-CN ストレージ コントローラの青色の電源 LED が消えるまで待ちます。


--
.SGF6112
--
.. 機器の電源をオフにします。
.. 青い電源 LED が消えるまで待ちます。


--
.SG6000
--
.. ストレージ コントローラーの背面にある緑色の Cache Active LED が消灯するまで待ちます。
+
この LED は、キャッシュされたデータをドライブに書き込む必要があるときに点灯します。電源をオフにする前に、この LED がオフになるまで待つ必要があります。

.. 機器の電源をオフにして、青色の電源 LED が消えるまで待ちます。


--
.SG5800
--
.. ストレージ コントローラーの背面にある緑色の Cache Active LED が消灯するまで待ちます。
+
この LED は、キャッシュされたデータをドライブに書き込む必要があるときに点灯します。電源をオフにする前に、この LED がオフになるまで待つ必要があります。

.. SANtricity System Manager のホームページから、*進行中の操作の表示*を選択します。
.. 次の手順に進む前に、すべての操作が完了していることを確認してください。
.. コントローラー シェルフの両方の電源スイッチをオフにし、コントローラー シェルフのすべての LED がオフになるまで待ちます。


--
.SG5700
--
.. ストレージ コントローラーの背面にある緑色の Cache Active LED が消灯するまで待ちます。
+
この LED は、キャッシュされたデータをドライブに書き込む必要があるときに点灯します。電源をオフにする前に、この LED がオフになるまで待つ必要があります。

.. 機器の電源をオフにし、すべての LED と 7 セグメント ディスプレイのアクティビティが停止するまで待ちます。


--
.SG100またはSG1000
--
.. 機器の電源をオフにします。
.. 青い電源 LED が消えるまで待ちます。


--
====

