---
permalink: maintain/step-3-revise-ilm-policy.html 
sidebar: sidebar 
keywords: storagegrid, recover, revise ilm policies 
summary: 'サイトの廃止ウィザードのステップ 3 (ILM ポリシーの修正) では、サイトが ILM ポリシーによって参照されているかどうかを確認できます。' 
---
= ステップ3: ILMポリシーの改訂
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サイトの廃止ウィザードのステップ 3 (ILM ポリシーの修正) では、サイトが ILM ポリシーによって参照されているかどうかを確認できます。

.開始する前に
あなたは、どのようにlink:../ilm/index.html["ILMでオブジェクトを管理する"]。ストレージ プールと ILM ルールの作成、および ILM ポリシーのシミュレーションとアクティブ化について理解している必要があります。

.タスク概要
いずれかのポリシー (アクティブまたは非アクティブ) 内のいずれかの ILM ルールがそのサイトを参照している場合、 StorageGRID はそのサイトを廃止できません。

廃止するサイトを参照する ILM ポリシーがある場合は、それらのポリシーを削除するか、次の要件を満たすように編集する必要があります。

* すべてのオブジェクト データを完全に保護します。
* 廃止するサイトを参照しないでください。
* サイトを参照するストレージ プールを使用しないでください。また、[すべてのサイト] オプションも使用しないでください。
* サイトを参照する消去コーディング プロファイルを使用しないでください。
* StorageGRID 11.6 以前のインストールの「2 つのコピーを作成」ルールを使用しないでください。



CAUTION: サイトの削除に対応するために、単一コピーの ILM ルールを作成しないでください。任意の期間に複製されたコピーを 1 つだけ作成する ILM ルールでは、データが永久に失われるリスクがあります。オブジェクトの複製されたコピーが 1 つしか存在しない場合、ストレージ ノードに障害が発生したり重大なエラーが発生すると、そのオブジェクトは失われます。また、アップグレードなどのメンテナンス手順中は、オブジェクトへのアクセス権が一時的に失われます。


TIP: _接続サイトの廃止_ を実行する場合は、削除するサイトに現在あるオブジェクト データをStorageGRID がどのように管理するかを検討する必要があります。データ保護の要件に応じて、新しいルールによって既存のオブジェクト データを別のサイトに移動したり、不要になったオブジェクトのコピーを削除したりできます。

新しいポリシーの設計についてサポートが必要な場合は、テクニカル サポートにお問い合わせください。

.手順
. ステップ 3 (ILM ポリシーの修正) で、廃止対象として選択したサイトを参照する ILM ポリシーがあるかどうかを確認します。
. ポリシーがリストされていない場合は、「次へ」を選択して次に進みます。link:step-4-remove-ilm-references.html["ステップ4: ILM参照を削除する"] 。
. 1 つ以上のアクティブな ILM ポリシーがリストされている場合は、既存の各ポリシーを複製するか、廃止するサイトを参照しない新しいポリシーを作成します。
+
.. 「ポリシー名」列でポリシーのリンクを選択します。
+
ポリシーの ILM ポリシー詳細ページが新しいブラウザ タブに表示されます。  「サイトの廃止」ページは他のタブで開いたままになります。

.. 必要に応じて、次のガイドラインと指示に従ってください。
+
*** ILM ルールを操作します。
+
**** link:../ilm/creating-storage-pool.html["1つ以上のストレージプールを作成する"]サイトを参照しないもの。
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html["ルールを編集または置換する"]サイトを参照します。
+

NOTE: *2 つのコピーを作成* ルールは *すべてのストレージ ノード* ストレージ プールを使用するため、これは許可されていないため、選択しないでください。



*** ILM ポリシーを操作します。
+
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#clone-ilm-policy["既存の ILM ポリシーを複製する"]またはlink:../ilm/creating-ilm-policy.html["新しいILMポリシーを作成する"]。
**** デフォルトのルールとその他のルールがサイトを参照していないことを確認します。
+

CAUTION: ILM ルールが正しい順序になっていることを確認する必要があります。ポリシーを有効にすると、新規オブジェクトと既存オブジェクトは、上から順にリストされた順序でルールによって評価されます。





.. テスト オブジェクトを取り込み、ポリシーをシミュレートして、正しいルールが適用されていることを確認します。
+

CAUTION: ILM ポリシーにエラーがあると、回復不能なデータ損失が発生する可能性があります。ポリシーをアクティブ化する前に慎重に確認してシミュレートし、意図したとおりに機能することを確認します。

+

CAUTION: 新しい ILM ポリシーをアクティブ化すると、 StorageGRID はそれを使用して、既存のオブジェクトと新しく取り込まれたオブジェクトを含むすべてのオブジェクトを管理します。新しい ILM ポリシーをアクティブ化する前に、既存の複製および消去コード化されたオブジェクトの配置の変更を確認してください。既存のオブジェクトの場所を変更すると、新しい配置が評価され実装されるときに一時的なリソースの問題が発生する可能性があります。

.. 新しいポリシーをアクティブ化し、古いポリシーが非アクティブになっていることを確認します。
+
複数のポリシーを有効にする場合は、link:../ilm/creating-ilm-policy.html#activate-ilm-policy["ILMポリシータグを作成する手順に従います"] 。

+
接続されたサイトの廃止を実行する場合、 StorageGRID は新しい ILM ポリシーをアクティブ化するとすぐに、選択したサイトからオブジェクト データの削除を開始します。すべてのオブジェクトのコピーを移動または削除するには、数週間かかる場合があります。オブジェクト データがサイトにまだ存在している間も、サイトの廃止を安全に開始できますが、実際の廃止手順を開始する前にサイトからデータを移動できるようにしておくと (ウィザードの手順 5 で [廃止の開始] を選択して)、廃止手順がより迅速に完了し、中断やパフォーマンスへの影響が少なくなります。



. それぞれの非アクティブポリシーについては、前の手順で説明したように、まず各ポリシーのリンクを選択して編集または削除します。
+
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy["ポリシーを編集する"]したがって、廃止されるサイトを指すものではありません。
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy["ポリシーを削除する"] 。


. ILM ルールとポリシーの変更が完了すると、手順 3 (ILM ポリシーの修正) にポリシーがリストされなくなります。*次へ*を選択します。
+
ステップ 4 (ILM 参照の削除) が表示されます。


