---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords: apply hotfix, install hotfix, replace primary admin node 
summary: 機能リリース間でソフトウェアの問題が検出され、解決された場合は、 StorageGRIDシステムに修正プログラムを適用する必要がある場合があります。 
---
= StorageGRIDホットフィックス手順
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
機能リリース間でソフトウェアの問題が検出され、解決された場合は、 StorageGRIDシステムに修正プログラムを適用する必要がある場合があります。

StorageGRIDホットフィックスには、機能またはパッチリリースの外部で提供されるソフトウェアの変更が含まれています。将来のリリースにも同じ変更が組み込まれる予定です。さらに、各ホットフィックス リリースには、機能またはパッチ リリース内の以前のすべてのホットフィックスのロールアップが含まれています。



== 修正プログラムの適用に関する考慮事項

別のメンテナンス手順が実行されている場合は、 StorageGRIDホットフィックスを適用できません。たとえば、廃止、拡張、または回復手順の実行中は、修正プログラムを適用できません。


NOTE: ノードまたはサイトの廃止手順が一時停止されている場合は、修正プログラムを安全に適用できます。さらに、 StorageGRIDアップグレード手順の最終段階で修正プログラムを適用できる場合もあります。詳細については、 StorageGRIDソフトウェアのアップグレード手順を参照してください。

グリッド マネージャーで修正プログラムをアップロードすると、修正プログラムはプライマリ管理ノードに自動的に適用されます。その後、 StorageGRIDシステム内の残りのノードへの修正プログラムの適用を承認できます。

1 つ以上のノードへのホットフィックスの適用に失敗した場合、ホットフィックスの進行状況テーブルの詳細列に失敗の理由が表示されます。失敗の原因となった問題を解決してから、プロセス全体を再試行する必要があります。以前に修正プログラムの適用が成功したノードは、後続の適用ではスキップされます。すべてのノードが更新されるまで、修正プログラムのプロセスを必要な回数だけ安全に再試行できます。アプリケーションを完了するには、すべてのグリッド ノードに修正プログラムを正常にインストールする必要があります。

グリッド ノードは新しいホットフィックス バージョンで更新されますが、ホットフィックスの実際の変更は特定の種類のノード上の特定のサービスにのみ影響する可能性があります。たとえば、ホットフィックスはストレージノード上の LDR サービスにのみ影響する場合があります。



== 回復と拡張のためのホットフィックスの適用方法

グリッドに修正プログラムが適用されると、プライマリ管理ノードは、リカバリ操作によって復元されたノードや拡張で追加されたノードに同じ修正プログラム バージョンを自動的にインストールします。

ただし、プライマリ管理ノードを回復する必要がある場合は、正しいStorageGRIDリリースを手動でインストールしてから、修正プログラムを適用する必要があります。プライマリ管理ノードの最終的なStorageGRIDバージョンは、グリッド内の他のノードのバージョンと一致する必要があります。

次の例は、プライマリ管理ノードを回復するときに修正プログラムを適用する方法を示しています。

. グリッドが最新のホットフィックスを適用したStorageGRID 11._A.B_ バージョンを実行していると仮定します。  「グリッドバージョン」は11._A.B.y_です。
. プライマリ管理ノードに障害が発生します。
. StorageGRID 11._A.B_ を使用してプライマリ管理ノードを再展開し、リカバリ手順を実行します。
+

NOTE: グリッド バージョンと一致させる必要がある場合、ノードをデプロイするときにマイナー リリースを使用できます。最初にメジャー リリースをデプロイする必要はありません。

. 次に、プライマリ管理ノードにホットフィックス 11._A.B.y_ を適用します。


詳細については、以下を参照してください。 link:configuring-replacement-primary-admin-node.html["代替プライマリ管理ノードを構成する"] 。
