---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: '廃止後に残る管理ドメイン コントローラ (ADC) サービスが少なすぎる場合、サイト上の特定のストレージ ノードを廃止できない可能性があります。' 
---
= ADC クォーラムとは何ですか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
廃止後に残る管理ドメイン コントローラ (ADC) サービスが少なすぎる場合は、サイト上の特定のストレージ ノードを廃止できない可能性があります。

一部のストレージ ノードにある ADC サービスは、グリッド トポロジ情報を維持し、グリッドに構成サービスを提供します。  StorageGRIDシステムでは、各サイトで常時利用可能な ADC サービスのクォーラムが必要です。

ノードを削除すると ADC クォーラムが満たされなくなる場合は、ストレージ ノードを廃止することはできません。廃止中に ADC クォーラムを満たすには、各サイトで少なくとも 3 つのストレージ ノードに ADC サービスが必要です。サイトに ADC サービスを備えた 3 つ以上のストレージ ノードがある場合、廃止後もそれらのノードの過半数が利用可能な状態になっている必要があります。 `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: ソフトウェア ベースのメタデータのみのノードを含むグリッド内のストレージ ノードを廃止する場合は注意してください。オブジェクトとメタデータの両方を保存するように構成されたすべてのノードを廃止すると、オブジェクトを保存する機能がグリッドから削除されます。見るlink:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードの種類"]メタデータのみのストレージ ノードの詳細については、こちらをご覧ください。

たとえば、サイトに現在 ADC サービスを備えた 6 つのストレージ ノードが含まれており、そのうち 3 つのストレージ ノードを廃止するとします。  ADC クォーラム要件のため、次の 2 つの廃止手順を完了する必要があります。

* 最初の廃止手順では、ADC サービスを備えた 4 つのストレージ ノードが引き続き使用可能であることを確認する必要があります。 `((0.5 * 6) + 1)` 。つまり、最初に廃止できるのは 2 つのストレージ ノードのみです。
* 2 番目の廃止手順では、ADC クォーラムで利用可能な状態を保つために必要な ADC サービスが 3 つだけになったため、3 番目のストレージ ノードを削除できます。 `((0.5 * 4) + 1)` 。


ストレージノードを廃止する必要があるが、ADCクォーラム要件のためにそれができない場合は、新しいストレージノードをlink:../expand/index.html["拡張"]ADC サービスが必要であることを指定します。次に、既存のストレージ ノードを廃止します。
