---
permalink: maintain/warnings-and-considerations-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, warning 
summary: グリッド ノードに障害が発生した場合は、できるだけ早く回復する必要があります。開始する前に、ノード回復に関するすべての警告と考慮事項を確認する必要があります。 
---
= グリッドノードの回復に関する警告と考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド ノードに障害が発生した場合は、できるだけ早く回復する必要があります。開始する前に、ノード回復に関するすべての警告と考慮事項を確認する必要があります。


CAUTION: StorageGRID は、相互に連携する複数のノードから構成される分散システムです。グリッド ノードを復元するためにディスク スナップショットを使用しないでください。代わりに、各タイプのノードの回復およびメンテナンスの手順を参照してください。


NOTE: StorageGRIDサイト全体に障害が発生した場合は、テクニカル サポートにお問い合わせください。テクニカル サポートはお客様と協力し、回復されるデータの量を最大化し、ビジネス目標を満たすサイト回復計画を策定し、実行します。見るlink:how-site-recovery-is-performed-by-technical-support.html["テクニカルサポートがサイトを復旧する方法"] 。

障害が発生したグリッド ノードをできるだけ早く回復する必要がある理由としては、次のようなものが挙げられます。

* グリッド ノードに障害が発生すると、システムとオブジェクト データの冗長性が低下し、別のノードに障害が発生した場合に永続的なデータ損失が発生するリスクが高まります。
* グリッド ノードに障害が発生すると、日常業務の効率に影響が出る可能性があります。
* グリッド ノードに障害が発生すると、システム操作を監視する能力が低下する可能性があります。
* 厳格な ILM ルールが適用されている場合、グリッド ノードに障害が発生すると、500 内部サーバー エラーが発生する可能性があります。
* グリッド ノードが速やかに回復されない場合、回復時間が長くなる可能性があります。たとえば、回復が完了する前にクリアする必要があるキューが発生する可能性があります。


常に、回復するグリッド ノードの特定のタイプの回復手順に従ってください。リカバリ手順は、プライマリまたは非プライマリ管理ノード、ゲートウェイ ノード、アプライアンス ノード、およびストレージ ノードによって異なります。



== グリッドノードの回復の前提条件

グリッド ノードを回復する場合は、次のすべての条件が満たされていることが前提となります。

* 障害が発生した物理または仮想ハードウェアが交換され、構成されました。
* 交換用アプライアンスのStorageGRIDアプライアンスインストーラのバージョンは、 StorageGRIDシステムのソフトウェアバージョンと一致します（詳細は、 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["StorageGRIDアプライアンスインストーラのバージョンを確認してアップグレードする"^] 。
* プライマリ管理ノード以外のグリッド ノードをリカバリする場合、リカバリ対象のグリッド ノードとプライマリ管理ノードの間に接続が存在します。
* アプライアンス ストレージ ノードをリカバリする場合は、アプライアンスのインストール時に、元のアプライアンスと同じストレージ タイプ (結合、メタデータのみ、またはデータのみ) を指定する必要があります。異なるストレージ タイプを指定した場合、リカバリは失敗し、正しいストレージ タイプを指定してアプライアンスを再インストールする必要があります。




== 複数のグリッドノードをホストするサーバーに障害が発生した場合のノード回復の順序

複数のグリッド ノードをホストしているサーバーに障害が発生した場合、任意の順序でノードを回復できます。ただし、障害が発生したサーバーがプライマリ管理ノードをホストしている場合は、まずそのノードを回復する必要があります。最初にプライマリ管理ノードを回復すると、プライマリ管理ノードへの接続を待機している間に他のノードの回復が停止することがなくなります。



== 回復したノードのIPアドレス

現在他のノードに割り当てられている IP アドレスを使用してノードを回復しようとしないでください。新しいノードを展開するときは、障害が発生したノードの現在の IP アドレスまたは未使用の IP アドレスを使用します。

新しい IP アドレスを使用して新しいノードを展開し、その後ノードを回復すると、回復されたノードでは新しい IP アドレスが引き続き使用されます。元の IP アドレスに戻したい場合は、回復が完了した後に IP 変更ツールを使用します。
