---
permalink: primer/hybrid-clouds-with-storagegrid.html 
sidebar: sidebar 
keywords: hybrid cloud, cloud storage pool, platform services, fabricpool, ontap 
summary: ポリシー駆動型データ管理を実装してオブジェクトをクラウド ストレージ プールに保存し、 StorageGRIDプラットフォーム サービスを活用し、 NetApp FabricPoolを使用してONTAPからStorageGRIDにデータを階層化することで、ハイブリッド クラウド構成でStorageGRIDを使用します。 
---
= StorageGRIDによるハイブリッドクラウド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ポリシー駆動型データ管理を実装してオブジェクトをクラウド ストレージ プールに保存し、 StorageGRIDプラットフォーム サービスを活用し、 NetApp FabricPoolを使用してONTAPからStorageGRIDにデータを階層化することで、ハイブリッド クラウド構成でStorageGRIDを使用します。



== クラウドストレージプール

クラウド ストレージ プールを使用すると、 StorageGRIDシステムの外部にオブジェクトを保存できます。たとえば、あまりアクセスされないオブジェクトを、Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud、または Microsoft Azure Blob ストレージのアーカイブ アクセス層などの低コストのクラウド ストレージに移動することが考えられます。または、ストレージ ボリュームまたはストレージ ノードの障害によって失われたデータを回復するために使用できるStorageGRIDオブジェクトのクラウド バックアップを維持することもできます。

ディスク ストレージやテープ ストレージなどのサードパーティ パートナー ストレージもサポートされています。


NOTE: Cloud Storage Pool ターゲットからオブジェクトを取得するための遅延が追加されるため、 FabricPoolでの Cloud Storage Pool の使用はサポートされていません。



== S3 プラットフォームサービス

S3 プラットフォーム サービスを使用すると、オブジェクト レプリケーション、イベント通知、または検索統合のエンドポイントとしてリモート サービスを使用できるようになります。プラットフォーム サービスはグリッドの ILM ルールとは独立して動作し、個々の S3 バケットに対して有効になります。以下のサービスがサポートされています:

* CloudMirror レプリケーション サービスは、指定されたオブジェクトをターゲット S3 バケット (Amazon S3 または 2 番目のStorageGRIDシステム上にある) に自動的にミラーリングします。
* イベント通知サービスは、指定されたアクションに関するメッセージを、Simple Notification Service (Amazon SNS) イベントの受信をサポートする外部エンドポイントに送信します。
* 検索統合サービスは、オブジェクトのメタデータを外部の Elasticsearch サービスに送信し、サードパーティのツールを使用してメタデータを検索、視覚化、分析できるようにします。


たとえば、CloudMirror レプリケーションを使用して特定の顧客レコードを Amazon S3 にミラーリングし、AWS サービスを活用してデータの分析を実行することができます。



== FabricPoolを使用したONTAPデータ階層化

FabricPoolを使用してStorageGRIDにデータを階層化することで、 ONTAPストレージのコストを削減できます。  FabricPool を使用すると、オンプレミスでもオフプレミスでも、低コストのオブジェクト ストレージ層へのデータの自動階層化が可能になります。

手動の階層化ソリューションとは異なり、FabricPoolはデータの階層化を自動化して、ストレージのコストを削減することで、総所有コストを削減します。StorageGRIDを含むパブリック クラウドとプライベート クラウドに階層化することで、クラウド経済のメリットを実現します。

.関連情報
* link:../ilm/what-cloud-storage-pool-is.html["クラウド ストレージ プールとは何ですか?"]
* link:../tenant/what-platform-services-are.html["プラットフォームサービスの管理"]
* link:../fabricpool/index.html["FabricPool用にStorageGRIDを構成する"]

