---
permalink: primer/nodes-and-services.html 
sidebar: sidebar 
keywords: services, grid nodes, primary admin, storage, gateway 
summary: StorageGRIDシステムの基本的な構成要素はグリッド ノードです。ノードには、グリッド ノードに一連の機能を提供するソフトウェア モジュールであるサービスが含まれています。 
---
= グリッドノードとサービス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDシステムの基本的な構成要素はグリッド ノードです。ノードには、グリッド ノードに一連の機能を提供するソフトウェア モジュールであるサービスが含まれています。



== グリッドノードの種類

StorageGRIDシステムでは、次の 4 種類のグリッド ノードが使用されます。

管理ノード:: システム構成、監視、ログ記録などの管理サービスを提供します。グリッド マネージャーにサインインすると、管理ノードに接続されます。各グリッドには 1 つのプライマリ管理ノードが必要ですが、冗長性のために追加の非プライマリ管理ノードが存在する場合もあります。任意の管理ノードに接続することができ、各管理ノードにはStorageGRIDシステムの同様のビューが表示されます。ただし、メンテナンス手順はプライマリ管理ノードを使用して実行する必要があります。
+
--
管理ノードは、S3 クライアント トラフィックの負荷分散にも使用できます。

見るlink:what-admin-node-is.html["管理ノードとは何ですか?"]

--
ストレージ ノード:: オブジェクト データとメタデータを管理および保存します。  StorageGRIDシステムの各サイトには、少なくとも 3 つのストレージ ノードが必要です。
+
--
見るlink:what-storage-node-is.html["ストレージノードとは何ですか?"]

--
ゲートウェイノード（オプション）:: クライアント アプリケーションがStorageGRIDに接続するために使用できる負荷分散インターフェイスを提供します。ロード バランサは、クライアントを最適なストレージ ノードにシームレスに誘導するため、ノードまたはサイト全体の障害が透過的になります。
+
--
見るlink:what-gateway-node-is.html["ゲートウェイノードとは何ですか?"]

--




== ハードウェアノードとソフトウェアノード

StorageGRIDノードは、 StorageGRIDアプライアンス ノードまたはソフトウェア ベースのノードとして展開できます。



=== StorageGRIDアプライアンスノード

StorageGRIDハードウェア アプライアンスは、 StorageGRIDシステムで使用するために特別に設計されています。一部のアプライアンスはストレージ ノードとして使用できます。その他のアプライアンスは、管理ノードまたはゲートウェイ ノードとして使用できます。アプライアンス ノードをソフトウェア ベースのノードと組み合わせたり、外部のハイパーバイザー、ストレージ、コンピューティング ハードウェアに依存しない、完全に設計されたオールアプライアンス グリッドを展開したりできます。

利用可能なアプライアンスの詳細については、以下を参照してください。

* https://docs.netapp.com/us-en/storagegrid-appliances/["StorageGRIDアプライアンスのドキュメント"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]




=== ソフトウェアベースのノード

ソフトウェア ベースのグリッド ノードは、VMware 仮想マシンとして、または Linux ホスト上のコンテナー エンジン内に展開できます。

* VMware vSphereの仮想マシン（VM）：link:../vmware/index.html["VMwareにStorageGRIDをインストールする"] 。
* Red Hat Enterprise Linuxのコンテナエンジン内:link:../rhel/index.html["Red Hat Enterprise LinuxにStorageGRIDをインストールする"] 。
* UbuntuまたはDebianのコンテナエンジン内:link:../ubuntu/index.html["UbuntuまたはDebianにStorageGRIDをインストールする"] 。


使用 https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool（IMT）"^]サポートされているバージョンを確認します。

新しいソフトウェアベースのストレージノードの初期インストール時に、次の目的のみに使用するように指定できます。link:../primer/what-storage-node-is.html#types-of-storage-nodes["メタデータを保存する"] 。



== StorageGRIDサービス

以下はStorageGRIDサービスの完全なリストです。

[cols="2a,3a,2a"]
|===
| サービス | 説明 | Location 


 a| 
アカウントサービスフォワーダー
 a| 
ロード バランサ サービスがリモート ホスト上のアカウント サービスを照会するためのインターフェイスを提供し、ロード バランサ エンドポイントの構成変更の通知をロード バランサ サービスに提供します。
 a| 
管理ノードとゲートウェイノード上のロードバランササービス



 a| 
ADC (管理ドメイン コントローラ)
 a| 
トポロジ情報を維持し、認証サービスを提供し、LDR および CMN サービスからのクエリに応答します。
 a| 
各サイトにADCサービスを含む少なくとも3つのストレージノード



 a| 
AMS（監査管理システム）
 a| 
監査対象のすべてのシステム イベントとトランザクションを監視し、テキスト ログ ファイルに記録します。
 a| 
管理ノード



 a| 
カサンドラ・リーパー
 a| 
オブジェクト メタデータの自動修復を実行します。
 a| 
ストレージ ノード



 a| 
チャンクサービス
 a| 
消去コード化されたデータとパリティ フラグメントを管理します。
 a| 
ストレージ ノード



 a| 
CMN（構成管理ノード）
 a| 
システム全体の構成とグリッド タスクを管理します。各グリッドには 1 つの CMN サービスがあります。
 a| 
プライマリ管理ノード



 a| 
DDS（分散データストア）
 a| 
Cassandra データベースとのインターフェースを介してオブジェクトのメタデータを管理します。
 a| 
ストレージ ノード



 a| 
DMV（データムーバー）
 a| 
データをクラウド エンドポイントに移動します。
 a| 
ストレージ ノード



 a| 
動的IP（dynip）
 a| 
グリッドの動的な IP 変更を監視し、ローカル構成を更新します。
 a| 
すべてのノード



 a| 
Grafana
 a| 
グリッド マネージャーでのメトリックの視覚化に使用されます。
 a| 
管理ノード



 a| 
高可用性
 a| 
高可用性グループ ページで構成されたノード上の高可用性仮想 IP を管理します。このサービスは、keepalived サービスとも呼ばれます。
 a| 
管理ノードとゲートウェイノード



 a| 
アイデンティティ（idnt）
 a| 
LDAP と Active Directory からのユーザー ID を統合します。
 a| 
ADC サービスを使用するストレージノード



 a| 
ラムダ仲裁者
 a| 
S3 Select SelectObjectContent リクエストを管理します。
 a| 
すべてのノード



 a| 
ロードバランサ (nginx-gw)
 a| 
クライアントからストレージ ノードへの S3 トラフィックの負荷分散を提供します。ロード バランサ サービスは、ロード バランサ エンドポイント構成ページから構成できます。このサービスは、nginx-gw サービスとも呼ばれます。
 a| 
管理ノードとゲートウェイノード



 a| 
LDR（ローカル配布ルータ）
 a| 
グリッド内のコンテンツの保存と転送を管理します。
 a| 
ストレージ ノード



 a| 
MISCd 情報サービス制御デーモン
 a| 
他のノード上のサービスを照会および管理したり、他のノードで実行されているサービスの状態を照会するなど、ノード上の環境構成を管理したりするためのインターフェイスを提供します。
 a| 
すべてのノード



 a| 
nginx
 a| 
さまざまなグリッド サービス (Prometheus や動的 IP など) が HTTPS API を介して他のノード上のサービスと通信できるようにするための認証および安全な通信メカニズムとして機能します。
 a| 
すべてのノード



 a| 
nginx-gw
 a| 
ロード バランサ サービスを強化します。
 a| 
管理ノードとゲートウェイノード



 a| 
NMS（ネットワーク管理システム）
 a| 
グリッド マネージャーを通じて表示される監視、レポート、および構成オプションを強化します。
 a| 
管理ノード



 a| 
粘り強さ
 a| 
再起動後も保持する必要があるルート ディスク上のファイルを管理します。
 a| 
すべてのノード



 a| 
プロメテウス
 a| 
すべてのノード上のサービスから時系列メトリックを収集します。
 a| 
管理ノード



 a| 
RSM（複製ステートマシン）
 a| 
プラットフォーム サービス リクエストがそれぞれのエンドポイントに送信されることを確認します。
 a| 
ADC サービスを使用するストレージノード



 a| 
SSM (サーバーステータスモニター)
 a| 
ハードウェアの状態を監視し、NMS サービスに報告します。
 a| 
インスタンスはすべてのグリッドノードに存在する



 a| 
トレースコレクター
 a| 
テクニカル サポートで使用する情報を収集するためにトレース収集を実行します。トレース コレクター サービスは、オープン ソースの Jaeger ソフトウェアを使用します。
 a| 
管理ノード

|===