---
permalink: primer/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 管理ノードは、システム構成、監視、ログ記録などの管理サービスを提供します。管理ノードは、S3 クライアント トラフィックの負荷分散にも使用できます。各グリッドには 1 つのプライマリ管理ノードが必要ですが、冗長性のために任意の数の非プライマリ管理ノードが存在する場合があります。 
---
= 管理ノードとは何ですか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理ノードは、システム構成、監視、ログ記録などの管理サービスを提供します。管理ノードは、S3 クライアント トラフィックの負荷分散にも使用できます。各グリッドには 1 つのプライマリ管理ノードが必要ですが、冗長性のために任意の数の非プライマリ管理ノードが存在する場合があります。



== プライマリ管理ノードと非プライマリ管理ノードの違い

Grid Manager または Tenant Manager にサインインすると、管理ノードに接続されます。任意の管理ノードに接続することができ、各管理ノードにはStorageGRIDシステムの同様のビューが表示されます。ただし、プライマリ管理ノードは、非プライマリ管理ノードよりも多くの機能を提供します。たとえば、ほとんどのメンテナンス手順はプライマリ管理ノードから実行する必要があります。

この表は、プライマリ管理ノードと非プライマリ管理ノードの機能をまとめたものです。

[cols="2a,1a,1a"]
|===
| 機能 | プライマリ管理ノード | 非プライマリ管理ノード 


 a| 
含まれるもの<<ams,アムス>>サービス
 a| 
はい
 a| 
はい



 a| 
含まれるもの<<cmn,CMN>>サービス
 a| 
はい
 a| 
いいえ



 a| 
含まれるもの<<nms,NMS>>サービス
 a| 
はい
 a| 
はい



 a| 
含まれるもの<<prometheus,プロメテウス>>サービス
 a| 
はい
 a| 
はい



 a| 
含まれるもの<<ssm,SSM>>サービス
 a| 
はい
 a| 
はい



 a| 
含まれるもの<<load-balancer,ロード バランサ>>そして<<high-availability,高可用性>>サービス
 a| 
はい
 a| 
はい



 a| 
サポート<<mgmt-api,管理アプリケーションプログラムインターフェース>>（管理API）
 a| 
はい
 a| 
はい



 a| 
IPアドレスの変更やNTPサーバーの更新など、ネットワーク関連のあらゆるメンテナンスタスクに使用できます。
 a| 
はい
 a| 
いいえ



 a| 
ストレージノードの拡張後にECの再バランスを実行できます
 a| 
はい
 a| 
いいえ



 a| 
ボリュームの復元手順に使用できます
 a| 
はい
 a| 
はい



 a| 
1 つ以上のノードからログ ファイルとシステム データを収集できます
 a| 
はい
 a| 
いいえ



 a| 
アラート通知、 AutoSupportパッケージ、SNMPトラップを送信して通知します
 a| 
○として機能します<<preferred-sender,優先送信者>>。
 a| 
○スタンバイ送信者として機能します。

|===


== [[preferred-sender]]優先送信者管理ノード

StorageGRID の展開に複数の管理ノードが含まれている場合、プライマリ管理ノードがアラート通知、 AutoSupportパッケージ、SNMP トラップおよびインフォームの優先送信元になります。

通常のシステム操作では、優先送信者のみが通知を送信します。ただし、他のすべての管理ノードは優先送信者を監視します。問題が検出された場合は、他の管理ノードがスタンバイ送信者として機能します。

以下の場合には複数の通知が送信される可能性があります:

* 管理ノードが互いに「孤立」した場合、優先送信者とスタンバイ送信者の両方が通知の送信を試み、通知の複数のコピーが受信される可能性があります。
* スタンバイ送信者が優先送信者の問題を検出し、通知の送信を開始すると、優先送信者は通知の送信能力を回復する可能性があります。この問題が発生すると、重複した通知が送信される可能性があります。スタンバイ送信者は、優先送信者でエラーが検出されなくなると、通知の送信を停止します。
+

NOTE: AutoSupportパッケージをテストすると、すべての管理ノードがテストを送信します。アラート通知をテストするときは、すべての管理ノードにサインインして接続を確認する必要があります。





== 管理ノードの主なサービス

次の表は管理ノードの主なサービスを示しています。ただし、この表にはすべてのノード サービスが記載されているわけではありません。

[cols="1a,2a"]
|===
| サービス | キー機能 


 a| 
[[ams]]監査管理システム（AMS）
 a| 
システムのアクティビティとイベントを追跡します。



 a| 
[[cmn]]構成管理ノード (CMN)
 a| 
システム全体の構成を管理します。



 a| 
[[高可用性]]高可用性
 a| 
管理ノードとゲートウェイ ノードのグループの高可用性仮想 IP アドレスを管理します。

*注:* このサービスはゲートウェイ ノードでも利用できます。



 a| 
[[ロードバランサー]]ロードバランサー
 a| 
クライアントからストレージ ノードへの S3 トラフィックの負荷分散を提供します。

*注:* このサービスはゲートウェイ ノードでも利用できます。



 a| 
[[mgmt-api]]管理アプリケーションプログラムインターフェース (mgmt-api)
 a| 
グリッド管理 API およびテナント管理 API からの要求を処理します。



 a| 
[[nms]]ネットワーク管理システム (NMS)
 a| 
グリッド マネージャーの機能を提供します。



 a| 
[[プロメテウス]]プロメテウス
 a| 
すべてのノード上のサービスから時系列メトリックを収集して保存します。



 a| 
[[ssm]]サーバーステータスモニター（SSM）
 a| 
オペレーティング システムと基盤となるハードウェアを監視します。

|===