---
permalink: primer/what-gateway-node-is.html 
sidebar: sidebar 
keywords: gateway nodes, api gateway 
summary: ゲートウェイ ノードは、S3 クライアント アプリケーションがStorageGRIDに接続するために使用できる専用の負荷分散インターフェイスを提供します。負荷分散は、複数のストレージ ノードにワークロードを分散することで、速度と接続容量を最大化します。ゲートウェイ ノードはオプションです。 
---
= ゲートウェイノードとは何ですか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ゲートウェイ ノードは、S3 クライアント アプリケーションがStorageGRIDに接続するために使用できる専用の負荷分散インターフェイスを提供します。負荷分散は、複数のストレージ ノードにワークロードを分散することで、速度と接続容量を最大化します。ゲートウェイ ノードはオプションです。

StorageGRIDロード バランサ サービスは、すべての管理ノードとすべてのゲートウェイ ノードで提供されます。クライアント要求のトランスポート層セキュリティ (TLS) 終了を実行し、要求を検査し、ストレージ ノードへの新しい安全な接続を確立します。ロード バランサ サービスは、クライアントを最適なストレージ ノードにシームレスに誘導するため、ノードまたはサイト全体の障害が透過的になります。

1 つ以上のロード バランサ エンドポイントを構成して、受信および送信クライアント要求がゲートウェイおよび管理ノード上のロード バランサ サービスにアクセスするために使用するポートとネットワーク プロトコル (HTTPS または HTTP) を定義します。ロード バランサ エンドポイントは、クライアント タイプ (S3)、バインディング モード、およびオプションで許可またはブロックされたテナントのリストも定義します。見るlink:../admin/managing-load-balancing.html["負荷分散に関する考慮事項"] 。

必要に応じて、複数のゲートウェイ ノードと管理ノードのネットワーク インターフェイスを高可用性 (HA) グループにグループ化できます。 HA グループ内のアクティブ インターフェイスに障害が発生した場合、バックアップ インターフェイスがクライアント アプリケーションのワークロードを管理できます。見るlink:../admin/managing-high-availability-groups.html["高可用性（HA）グループの管理"] 。



== ゲートウェイノードの主なサービス

次の表はゲートウェイ ノードの主なサービスを示しています。ただし、この表にはすべてのノード サービスが記載されているわけではありません。

[cols="1a,2a"]
|===
| サービス | キー機能 


 a| 
高可用性
 a| 
管理ノードとゲートウェイ ノードのグループの高可用性仮想 IP アドレスを管理します。

*注:* このサービスは管理ノードにも存在します。



 a| 
ロード バランサ
 a| 
クライアントからストレージ ノードへの S3 トラフィックのレイヤー 7 ロード バランシングを提供します。これは推奨される負荷分散メカニズムです。

*注:* このサービスは管理ノードにも存在します。



 a| 
サーバーステータスモニター (SSM)
 a| 
オペレーティング システムと基盤となるハードウェアを監視します。

|===