---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: ストレージ ノードは、オブジェクト データとメタデータを管理および保存します。ストレージ ノードには、ディスク上のオブジェクト データとメタデータを保存、移動、検証、取得するために必要なサービスとプロセスが含まれます。 
---
= ストレージノードとは何ですか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ ノードは、オブジェクト データとメタデータを管理および保存します。ストレージ ノードには、ディスク上のオブジェクト データとメタデータを保存、移動、検証、取得するために必要なサービスとプロセスが含まれます。

StorageGRIDシステムの各サイトには、少なくとも 3 つのストレージ ノードが必要です。



== ストレージノードの種類

インストール中に、インストールするストレージ ノードのタイプを選択できます。これらのタイプは、ソフトウェア ベースのストレージ ノードと、機能をサポートするアプライアンス ベースのストレージ ノードで使用できます。

* データとメタデータを統合したストレージノード
* メタデータのみのストレージノード
* データ専用ストレージノード


次の状況でストレージ ノード タイプを選択できます。

* ストレージノードを最初にインストールする場合
* StorageGRIDシステムの拡張中にストレージノードを追加する場合



NOTE: ストレージ ノードのインストールが完了した後は、タイプを変更することはできません。

データとメタデータのストレージノード（結合）:: デフォルトでは、すべての新しいストレージ ノードはオブジェクト データとメタデータの両方を保存します。このタイプのストレージ ノードは、_複合_ストレージ ノードと呼ばれます。
メタデータのみのストレージノード:: グリッドに非常に多くの小さなオブジェクトが格納されている場合は、メタデータ専用のストレージ ノードを使用することが合理的です。専用のメタデータ容量をインストールすると、多数の小さなオブジェクトに必要なスペースとそれらのオブジェクトのメタデータに必要なスペースのバランスが向上します。さらに、高性能アプライアンスでホストされるメタデータのみのストレージ ノードにより、パフォーマンスを向上できます。


メタデータのみのストレージ ノードには、特定のハードウェア要件があります。

* StorageGRIDアプライアンスを使用する場合、メタデータ専用ノードは、12 台の 1.9 TB ドライブまたは 12 台の 3.8 TB ドライブを搭載した SGF6112 アプライアンスでのみ構成できます。
* ソフトウェア ベースのノードを使用する場合、メタデータのみのノード リソースは既存のストレージ ノード リソースと一致する必要があります。例えば：
+
** 既存のStorageGRIDサイトが SG6000 または SG6100 アプライアンスを使用している場合、ソフトウェアベースのメタデータのみのノードは次の最小要件を満たしている必要があります。
+
*** 128GBのRAM
*** 8コアCPU
*** Cassandra データベース用の 8 TB SSD または同等のストレージ (rangedb/0)


** 既存のStorageGRIDサイトが 24 GB RAM、8 コア CPU、3 TB または 4 TB のメタデータ ストレージを備えた仮想ストレージ ノードを使用している場合、ソフトウェア ベースのメタデータ専用ノードでは同様のリソース (24 GB RAM、8 コア CPU、4 TB のメタデータ ストレージ (rangedb/0)) を使用する必要があります。


* 新しいStorageGRIDサイトを追加する場合、新しいサイトの合計メタデータ容量は少なくとも既存のStorageGRIDサイトと一致し、新しいサイトのリソースは既存のStorageGRIDサイトのストレージ ノードと一致する必要があります。


メタデータのみのノードをインストールする場合、グリッドにはデータ ストレージ用の最小数のノードも含まれている必要があります。

* 単一サイト グリッドの場合は、少なくとも 2 つの結合ストレージ ノードまたはデータ専用ストレージ ノードを構成します。
* マルチサイト グリッドの場合は、サイトごとに少なくとも 1 つの結合ストレージ ノードまたはデータ専用ストレージ ノードを構成します。



NOTE: メタデータのみのストレージノードには、<<ldr-service,LDRサービス>> S3 クライアント要求を処理できる場合、 StorageGRID のパフォーマンスは向上しない可能性があります。

データ専用ストレージノード:: ストレージ ノードのパフォーマンス特性が異なる場合は、データ専用のストレージ ノードを使用することが合理的です。たとえば、パフォーマンスを向上させるために、データ専用の大容量回転ディスク ストレージ ノードと、メタデータ専用の高性能ストレージ ノードを組み合わせることができます。


データ専用ノードをインストールする場合、グリッドには以下が含まれている必要があります。

* グリッドごとに最低2つの複合またはデータ専用のストレージノード
* サイトごとに少なくとも 1 つの複合またはデータ専用のストレージ ノード
* サイトごとに少なくとも 3 つの統合またはメタデータのみのストレージ ノード




== ストレージノードの主なサービス

次の表は、ストレージ ノードの主なサービスを示しています。ただし、この表にはすべてのノード サービスが記載されているわけではありません。


NOTE: ADC サービスや RSM サービスなどの一部のサービスは、通常、各サイトの 3 つのストレージ ノードにのみ存在します。

[cols="1a,3a"]
|===
| サービス | キー機能 


 a| 
アカウント（アカウント）
 a| 
テナント アカウントを管理します。



 a| 
管理ドメイン コントローラ (ADC)
 a| 
トポロジとグリッド全体の構成を維持します。

*注*: データ専用ストレージノードは ADC サービスをホストしません。

.詳細
[%collapsible]
====
管理ドメイン コントローラ (ADC) サービスは、グリッド ノードとそれらの相互接続を認証します。  ADC サービスは、サイト内の少なくとも 3 つのストレージ ノードでホストされます。

ADC サービスは、サービスの場所や可用性などのトポロジ情報を維持します。グリッド ノードが別のグリッド ノードからの情報を必要とする場合、または別のグリッド ノードによって実行されるアクションを必要とする場合、グリッド ノードは ADC サービスに接続して、その要求を処理するのに最適なグリッド ノードを見つけます。さらに、ADC サービスはStorageGRIDデプロイメントの構成バンドルのコピーを保持するため、どのグリッド ノードでも現在の構成情報を取得できます。

分散型および孤立型の操作を容易にするために、各 ADC サービスは、証明書、構成バンドル、およびサービスとトポロジに関する情報をStorageGRIDシステム内の他の ADC サービスと同期します。

一般に、すべてのグリッド ノードは少なくとも 1 つの ADC サービスへの接続を維持します。これにより、グリッド ノードが常に最新の情報にアクセスできるようになります。グリッド ノードが接続すると、他のグリッド ノードの証明書がキャッシュされ、ADC サービスが利用できない場合でも、システムが既知のグリッド ノードで機能し続けることができるようになります。新しいグリッド ノードは、ADC サービスを使用してのみ接続を確立できます。

各グリッド ノードを接続すると、ADC サービスはトポロジ情報を収集できます。このグリッド ノード情報には、CPU 負荷、使用可能なディスク容量 (ストレージがある場合)、サポートされているサービス、グリッド ノードのサイト ID が含まれます。他のサービスは、トポロジ クエリを通じて ADC サービスにトポロジ情報を要求します。  ADC サービスは、 StorageGRIDシステムから受信した最新情報を使用して各クエリに応答します。

====


 a| 
Cassandra
 a| 
オブジェクトのメタデータを保存および保護します。

*注*: データ専用ストレージノードは Cassandra サービスをホストしません。



 a| 
カサンドラ・リーパー
 a| 
オブジェクト メタデータの自動修復を実行します。

*注*: データ専用ストレージノードは Cassandra Reaper サービスをホストしません。



 a| 
かたまり
 a| 
消去コード化されたデータとパリティ フラグメントを管理します。



 a| 
データムーバー（dmv）
 a| 
データをクラウド ストレージ プールに移動します。



 a| 
分散データストア（DDS）
 a| 
オブジェクト メタデータ ストレージを監視します。

.詳細
[%collapsible]
====
各ストレージ ノードには、分散データ ストア (DDS) サービスが含まれています。このサービスは Cassandra データベースとインターフェースし、 StorageGRIDシステムに保存されているオブジェクト メタデータに対してバックグラウンド タスクを実行します。

DDS サービスは、 StorageGRIDシステムに取り込まれたオブジェクトの合計数と、システムでサポートされている各インターフェイス (S3) を介して取り込まれたオブジェクトの合計数を追跡します。

====


 a| 
アイデンティティ（idnt）
 a| 
LDAP と Active Directory からのユーザー ID を統合します。



 a| 
[[ldr-service]]ローカル配布ルータ（LDR）
 a| 
オブジェクト ストレージ プロトコル要求を処理し、ディスク上のオブジェクト データを管理します。

.詳細
[%collapsible]
====
各結合ストレージ ノード、データのみのストレージ ノード、およびメタデータのみのストレージ ノードには、ローカル配布ルーター (LDR) サービスが含まれています。このサービスは、データの保存、ルーティング、要求の処理などのコンテンツ転送機能を処理します。  LDR サービスは、データ転送の負荷とデータ トラフィック機能を処理することで、 StorageGRIDシステムのハードワークの大部分を実行します。

LDR サービスは次のタスクを処理します。

* クエリ
* 情報ライフサイクル管理（ILM）活動
* オブジェクトの削除
* オブジェクトデータストレージ
* 別のLDRサービス（ストレージノード）からのオブジェクトデータ転送
* データストレージ管理
* S3プロトコルインターフェース


LDR サービスは、各 S3 オブジェクトをその一意の UUID にマッピングします。

オブジェクトストア:: LDR サービスの基盤となるデータ ストレージは、固定数のオブジェクト ストア (ストレージ ボリュームとも呼ばれます) に分割されます。各オブジェクト ストアは個別のマウント ポイントです。
+
--
ストレージ ノード内のオブジェクト ストアは、ボリューム ID と呼ばれる 0000 から 002F までの 16 進数で識別されます。 Cassandra データベース内のオブジェクト メタデータ用に最初のオブジェクト ストア (ボリューム 0) にスペースが予約され、そのボリュームの残りのスペースはオブジェクト データに使用されます。その他のすべてのオブジェクト ストアは、複製されたコピーや消去コード化されたフラグメントを含むオブジェクト データ専用に使用されます。

複製されたコピーのスペース使用が均等になるように、特定のオブジェクトのオブジェクト データは、使用可能なストレージ スペースに基づいて 1 つのオブジェクト ストアに保存されます。オブジェクト ストアの容量がいっぱいになると、ストレージ ノードに空き容量がなくなるまで、残りのオブジェクト ストアにオブジェクトが保存され続けます。

--
メタデータ保護:: StorageGRID は、LDR サービスとインターフェースする Cassandra データベースにオブジェクト メタデータを保存します。
+
--
冗長性を確保し、損失を防止するために、オブジェクト メタデータのコピーが各サイトに 3 つ保持されます。このレプリケーションは構成不可能であり、自動的に実行されます。詳細については、 link:../admin/managing-object-metadata-storage.html["オブジェクトメタデータストレージの管理"] 。

--


====


 a| 
複製された状態マシン (RSM)
 a| 
S3 プラットフォーム サービス リクエストがそれぞれのエンドポイントに送信されるようにします。



 a| 
サーバーステータスモニター (SSM)
 a| 
オペレーティング システムと基盤となるハードウェアを監視します。

|===