---
permalink: expand/adding-storage-capacity-for-replicated-objects.html 
sidebar: sidebar 
keywords: replication, replicated, copies, capacity, storage nodes, expand, expansion 
summary: '展開の情報ライフサイクル管理 (ILM) ポリシーに、オブジェクトの複製コピーを作成するルールが含まれている場合は、追加するストレージの量と、新しいストレージ ボリュームまたはストレージ ノードを追加する場所を考慮する必要があります。' 
---
= 複製されたオブジェクト用のストレージ容量を追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
展開の情報ライフサイクル管理 (ILM) ポリシーにオブジェクトの複製コピーを作成するルールが含まれている場合は、追加するストレージの量と、新しいストレージ ボリュームまたはストレージ ノードを追加する場所を考慮する必要があります。

追加のストレージを追加する場所に関するガイダンスについては、複製されたコピーを作成する ILM ルールを確認してください。 ILM ルールによって 2 つ以上のオブジェクト コピーが作成される場合は、オブジェクト コピーが作成される各場所にストレージを追加することを計画します。簡単な例として、2つのサイトグリッドがあり、各サイトに1つのオブジェクトコピーを作成するILMルールがある場合、link:../expand/adding-storage-volumes-to-storage-nodes.html["ストレージを追加"]各サイトにオブジェクトを追加して、グリッド全体のオブジェクト容量を増やします。オブジェクトの複製については、以下を参照してください。link:../ilm/what-replication-is.html["レプリケーションとは何か"] 。

パフォーマンス上の理由から、サイト間でストレージ容量とコンピューティング能力のバランスを保つようにする必要があります。したがって、この例では、各サイトに同じ数のストレージ ノードを追加するか、各サイトで追加のストレージ ボリュームを追加する必要があります。

バケット名などの基準に基づいてオブジェクトを異なる場所に配置するルールや、時間の経過とともにオブジェクトの場所を変更するルールを含む、より複雑な ILM ポリシーがある場合、拡張のためにストレージが必要となる場所の分析は同様になりますが、より複雑になります。

全体的なストレージ容量がどのくらいの速さで消費されているかをグラフ化すると、拡張時にどのくらいのストレージを追加すればよいか、また追加のストレージ容量がいつ必要になるかを把握するのに役立ちます。グリッドマネージャを使用すると、link:../monitor/monitoring-storage-capacity.html["ストレージ容量を監視し、グラフ化する"] 。

拡張のタイミングを計画するときは、追加のストレージの調達とインストールにどれくらいの時間がかかるかを考慮する必要があります。
