---
permalink: expand/adding-new-site.html 
sidebar: sidebar 
keywords: expand, expansion, new site, add site, guidelines 
summary: 新しいサイトを追加することで、 StorageGRIDシステムを拡張できます。 
---
= 新しいサイトを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいサイトを追加することで、 StorageGRIDシステムを拡張できます。



== サイトを追加するためのガイドライン

サイトを追加する前に、次の要件と制限を確認してください。

* 拡張操作ごとに追加できるサイトは 1 つだけです。
* 同じ拡張の一部として既存のサイトにグリッド ノードを追加することはできません。
* すべてのサイトには少なくとも 3 つのストレージ ノードが含まれている必要があります。
* 新しいサイトを追加しても、保存できるオブジェクトの数は自動的には増加しません。グリッドの合計オブジェクト容量は、使用可能なストレージの量、ILM ポリシー、および各サイトのメタデータ容量によって異なります。
* 新しいサイトのサイズを決定するときは、十分なメタデータ容量が含まれていることを確認する必要があります。
+
StorageGRID は、すべてのオブジェクト メタデータのコピーを各サイトに保存します。新しいサイトを追加するときは、既存のオブジェクト メタデータに十分なメタデータ容量と、成長に十分なメタデータ容量が含まれていることを確認する必要があります。

+
詳細については、次を参照してください。

+
** link:../admin/managing-object-metadata-storage.html["オブジェクトメタデータストレージの管理"]
** link:../monitor/monitoring-storage-capacity.html#monitor-object-metadata-capacity-for-each-storage-node["各ストレージノードのオブジェクトメタデータ容量を監視する"]


* サイト間の利用可能なネットワーク帯域幅とネットワーク遅延のレベルを考慮する必要があります。すべてのオブジェクトが取り込まれたサイトにのみ保存されている場合でも、メタデータの更新はサイト間で継続的に複製されます。
* 拡張中もStorageGRIDシステムは稼働し続けるため、拡張手順を開始する前に ILM ルールを確認する必要があります。拡張手順が完了するまで、オブジェクトのコピーが新しいサイトに保存されないようにする必要があります。
+
たとえば、拡張を開始する前に、デフォルトのストレージ プール (すべてのストレージ ノード) を使用するルールがあるかどうかを確認します。存在する場合は、既存のストレージ ノードを含む新しいストレージ プールを作成し、新しいストレージ プールを使用するように ILM ルールを更新する必要があります。それ以外の場合、そのサイトの最初のノードがアクティブになるとすぐに、オブジェクトは新しいサイトにコピーされます。

+
新しいサイトを追加するときにILMを変更する方法の詳細については、link:../ilm/example-6-changing-ilm-policy.html["ILMポリシーの変更例"] 。


