---
permalink: expand/adding-storage-capacity-for-erasure-coded-objects.html 
sidebar: sidebar 
keywords: erasure coding, capacity, storage nodes, ec, expand, expansion 
summary: ILM ポリシーに、消去コード化されたコピーを作成するルールが含まれている場合は、新しいストレージを追加する場所と、新しいストレージを追加するタイミングを計画する必要があります。追加するストレージの量と追加のタイミングは、グリッドの使用可能なストレージ容量に影響を与える可能性があります。 
---
= 消失訂正コード付きオブジェクト用のストレージ容量を追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM ポリシーに、消去コード化されたコピーを作成するルールが含まれている場合は、新しいストレージを追加する場所と、新しいストレージを追加するタイミングを計画する必要があります。追加するストレージの量と追加のタイミングは、グリッドの使用可能なストレージ容量に影響を与える可能性があります。

ストレージ拡張を計画する最初のステップは、消去コード化されたオブジェクトを作成する ILM ポリシーのルールを調べることです。 StorageGRID は、すべての消去コード化オブジェクトに対して _k+m_ 個のフラグメントを作成し、各フラグメントを異なるストレージ ノードに保存するため、拡張後に少なくとも _k+m_ 個のストレージ ノードに新しい消去コード化データ用のスペースがあることを確認する必要があります。消去コーディング プロファイルがサイト損失保護を提供する場合は、各サイトにストレージを追加する必要があります。見るlink:../ilm/what-erasure-coding-schemes-are.html["消失訂正符号化方式とは何か"]消失訂正コーディング プロファイルの詳細については、こちらをご覧ください。

追加する必要があるノードの数は、拡張を実行するときに既存のノードがどの程度いっぱいになっているかによっても異なります。



== 消失訂正符号化オブジェクト用のストレージ容量を追加するための一般的な推奨事項

詳細な計算を避けたい場合は、既存のストレージ ノードの容量が 70% に達したときに、サイトごとに 2 つのストレージ ノードを追加できます。

この一般的な推奨事項は、単一サイトのグリッドと、消失訂正符号化によってサイト損失保護が提供されるグリッドの両方に対して、広範囲の消失訂正符号化方式にわたって妥当な結果を提供します。

この推奨に至った要因をより深く理解したり、サイトに適したより正確な計画を立てるには、以下を参照してください。link:considerations-for-rebalancing-erasure-coded-data.html["消失訂正符号化データの再バランスに関する考慮事項"] 。状況に合わせて最適化されたカスタム推奨事項については、 NetAppプロフェッショナル サービス コンサルタントにお問い合わせください。
