---
permalink: expand/copying-admin-node-database.html 
sidebar: sidebar 
keywords: copy Admin Node database, alert history, Admin Node expansion 
summary: 拡張手順を通じて管理ノードを追加する場合、オプションでプライマリ管理ノードから新しい管理ノードにデータベースをコピーできます。データベースをコピーすると、属性、アラート、警告に関する履歴情報を保持できます。 
---
= 管理ノードデータベースのコピー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張手順を通じて管理ノードを追加する場合、オプションでプライマリ管理ノードから新しい管理ノードにデータベースをコピーできます。データベースをコピーすると、属性、アラート、警告に関する履歴情報を保持できます。

.開始する前に
* 管理ノードを追加するために必要な拡張手順が完了しました。
* あなたは `Passwords.txt`ファイル。
* プロビジョニング パスフレーズを持っています。


.タスク概要
StorageGRIDソフトウェアのアクティベーション プロセスでは、拡張管理ノード上の NMS サービス用の空のデータベースが作成されます。拡張管理ノードで NMS サービスが開始されると、現在システムの一部である、または後で追加されたサーバーとサービスの情報が記録されます。この管理ノード データベースには次の情報が含まれます。

* アラート履歴
* ノードページの従来のチャートで使用される履歴属性データ


管理ノード データベースがノード間で一貫していることを確認するには、プライマリ管理ノードから拡張管理ノードにデータベースをコピーできます。


NOTE: プライマリ管理ノード (__ソース管理ノード__) から拡張管理ノードへのデータベースのコピーは、完了するまでに最大数時間かかる場合があります。この期間中、グリッド マネージャーにはアクセスできません。

データベースをコピーする前に、プライマリ管理ノードと拡張管理ノードの両方で MI サービスと管理 API サービスを停止するには、次の手順に従います。

.手順
. プライマリ管理ノードで次の手順を実行します。
+
.. 管理ノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... 記載されているパスワードを入力してください `Passwords.txt`ファイル。
... ルートに切り替えるには、次のコマンドを入力します。 `su -`
... 記載されているパスワードを入力してください `Passwords.txt`ファイル。


.. 次のコマンドを実行します。 `recover-access-points`
.. プロビジョニング パスフレーズを入力します。
.. MI サービスを停止します。 `service mi stop`
.. 管理アプリケーション プログラム インターフェイス (mgmt-api) サービスを停止します。 `service mgmt-api stop`


. 拡張管理ノードで次の手順を実行します。
+
.. 拡張管理ノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... 記載されているパスワードを入力してください `Passwords.txt`ファイル。
... ルートに切り替えるには、次のコマンドを入力します。 `su -`
... 記載されているパスワードを入力してください `Passwords.txt`ファイル。


.. MI サービスを停止します。 `service mi stop`
.. mgmt-api サービスを停止します。 `service mgmt-api stop`
.. SSH エージェントに SSH 秘密キーを追加します。入力：``ssh-add``
.. に記載されているSSHアクセスパスワードを入力してください `Passwords.txt`ファイル。
.. ソース管理ノードから拡張管理ノードにデータベースをコピーします。 `/usr/local/mi/bin/mi-clone-db.sh _Source_Admin_Node_IP_`
.. プロンプトが表示されたら、拡張管理ノード上の MI データベースを上書きすることを確認します。
+
データベースとその履歴データは拡張管理ノードにコピーされます。コピー操作が完了すると、スクリプトは拡張管理ノードを起動します。

.. 他のサーバーへのパスワードなしのアクセスが不要になったら、SSH エージェントから秘密キーを削除します。入力：``ssh-add -D``


. プライマリ管理ノードでサービスを再起動します。 `service servermanager start`

