---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: 拡張手順を通じて新しい管理ノードを追加すると、その AMS サービスは、その管理ノードがシステムに参加した後に発生するイベントとアクションのみをログに記録します。必要に応じて、以前にインストールした管理ノードから新しい拡張管理ノードに監査ログをコピーして、 StorageGRIDシステムの残りの部分と同期させることができます。 
---
= 監査ログのコピー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張手順を通じて新しい管理ノードを追加すると、その AMS サービスは、その管理ノードがシステムに参加した後に発生するイベントとアクションのみをログに記録します。必要に応じて、以前にインストールした管理ノードから新しい拡張管理ノードに監査ログをコピーして、 StorageGRIDシステムの残りの部分と同期させることができます。

.開始する前に
* 管理ノードを追加するために必要な拡張手順が完了しました。
* あなたは `Passwords.txt`ファイル。


.タスク概要
新しい管理ノードで履歴監査メッセージを利用できるようにするには、既存の管理ノードから拡張管理ノードに監査ログ ファイルを手動でコピーする必要があります。

[NOTE]
====
デフォルトでは、監査情報は管理ノードの監査ログに送信されます。次のいずれかに該当する場合は、これらの手順をスキップできます。

* 外部 Syslog サーバーを構成したため、監査ログは管理ノードではなく Syslog サーバーに送信されるようになりました。
* 監査メッセージは、それを生成したローカル ノードにのみ保存されるように明示的に指定しました。


見るlink:../monitor/configure-audit-messages.html["監査メッセージとログの保存先を構成する"]詳細については。

====
.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh _admin@_primary_Admin_Node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
+
ルートとしてログインすると、プロンプトは `$`に `#`。



. 新しいファイルが作成されないように、AMS サービスを停止します。 `service ams stop`
. 監査エクスポート ディレクトリに移動します。
+
`cd /var/local/log`

. ソースの名前を変更する `audit.log`ファイルをコピーして、コピー先の拡張管理ノード上のファイルを上書きしないようにします。
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. すべての監査ログ ファイルを拡張管理ノード上の宛先場所にコピーします。
+
`scp -p * _IP_address_:/var/local/log`

. パスフレーズの入力を求められた場合は、 `/root/.ssh/id_rsa`にリストされているプライマリ管理ノードのSSHアクセスパスワードを入力します。 `Passwords.txt`ファイル。
. オリジナルを復元する `audit.log`ファイル：
+
`mv _new_name_.txt audit.log`

. AMS サービスを開始します。
+
`service ams start`

. サーバーからログアウトします:
+
`exit`

. 拡張管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_expansion_Admin_Node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
+
ルートとしてログインすると、プロンプトは `$`に `#`。



. 監査ログ ファイルのユーザーとグループの設定を更新します。
+
`cd /var/local/log`

+
`chown ams-user:bycast *`

. サーバーからログアウトします:
+
`exit`


