---
permalink: expand/guidelines-for-adding-object-capacity.html 
sidebar: sidebar 
keywords: adding storage capacity, guidelines, storage volumes, expansion 
summary: '既存のストレージ ノードにストレージ ボリュームを追加するか、既存のサイトに新しいストレージ ノードを追加することで、 StorageGRIDシステムのオブジェクト ストレージ容量を拡張できます。情報ライフサイクル管理 (ILM) ポリシーの要件を満たす方法でストレージ容量を追加する必要があります。' 
---
= オブジェクト容量を追加するためのガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のストレージ ノードにストレージ ボリュームを追加するか、既存のサイトに新しいストレージ ノードを追加することで、 StorageGRIDシステムのオブジェクト ストレージ容量を拡張できます。情報ライフサイクル管理 (ILM) ポリシーの要件を満たす方法でストレージ容量を追加する必要があります。



== ストレージボリュームを追加するためのガイドライン

既存のストレージ ノードにストレージ ボリュームを追加する前に、次のガイドラインと制限事項を確認してください。

* 現在のILMルールを調べて、どこでいつ行うかを決定する必要があります。link:../expand/adding-storage-volumes-to-storage-nodes.html["ストレージボリュームを追加する"]利用可能なストレージを増やすlink:../ilm/what-replication-is.html["複製されたオブジェクト"]またはlink:../ilm/what-erasure-coding-schemes-are.html["消失訂正符号化オブジェクト"]。
* オブジェクト メタデータはボリューム 0 にのみ保存されるため、ストレージ ボリュームを追加してシステムのメタデータ容量を増やすことはできません。
* 各ソフトウェア ベースのストレージ ノードは、最大 48 個のストレージ ボリュームをサポートできます。それ以上の容量を追加する必要がある場合は、新しいストレージ ノードを追加する必要があります。
* 各 SG6060 アプライアンスに 1 つまたは 2 つの拡張シェルフを追加できます。各拡張シェルフには 16 個のストレージ ボリュームが追加されます。両方の拡張シェルフをインストールすると、SG6060 は合計 48 個のストレージ ボリュームをサポートできます。
* 各 SG6160 アプライアンスに 1 つまたは 2 つの拡張シェルフを追加できます。拡張シェルフごとに 60 個のストレージ ボリュームが追加されます。両方の拡張シェルフをインストールすると、SG6160 は合計 180 個のストレージ ボリュームをサポートできます。
* 他のストレージアプライアンスにストレージボリュームを追加することはできません。
* 既存のストレージボリュームのサイズを増やすことはできません。
* システムのアップグレード、リカバリ操作、またはその他の拡張を実行しているときに、ストレージ ノードにストレージ ボリュームを追加することはできません。


ストレージ ボリュームを追加することを決定し、ILM ポリシーを満たすために拡張する必要があるストレージ ノードを決定したら、ストレージ ノードのタイプに応じた手順に従います。

* SG6060ストレージアプライアンスに1台または2台の拡張シェルフを追加するには、 https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/adding-expansion-shelf-to-deployed-sg6060.html["展開済みのSG6060に拡張シェルフを追加する"^] 。
* SG6160ストレージアプライアンスに1台または2台の拡張シェルフを追加するには、 https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/adding-expansion-shelf-to-deployed-sg6160.html["展開済みのSG6160に拡張シェルフを追加する"^]
* ソフトウェアベースのノードの場合は、link:adding-storage-volumes-to-storage-nodes.html["ストレージノードにストレージボリュームを追加する"] 。




== ストレージノードを追加するためのガイドライン

既存のサイトにストレージ ノードを追加する前に、次のガイドラインと制限事項を確認してください。

* 現在のILMルールを調べて、ストレージノードをどこにいつ追加すれば、利用可能なストレージ容量を増やすことができるかを決定する必要があります。link:../ilm/what-replication-is.html["複製されたオブジェクト"]またはlink:../ilm/what-erasure-coding-schemes-are.html["消失訂正符号化オブジェクト"]。
* 1 回の拡張手順で 10 個を超えるストレージ ノードを追加しないでください。
* 1 回の拡張手順で、ストレージ ノードを複数のサイトに追加できます。
* ストレージ ノードと他のタイプのノードを 1 回の拡張手順で追加できます。
* 拡張手順を開始する前に、回復の一環として実行されたすべてのデータ修復操作が完了していることを確認する必要があります。見るlink:../maintain/checking-data-repair-jobs.html["データ修復ジョブを確認する"] 。
* 拡張を実行する前または実行後にストレージ ノードを削除する必要がある場合は、1 回のノード廃止手順で 10 個を超えるストレージ ノードを廃止しないでください。




== ストレージノード上のADCサービスのガイドライン

拡張を構成するときは、新しいストレージ ノードごとに管理ドメイン コントローラ (ADC) サービスを含めるかどうかを選択する必要があります。ADC サービスは、グリッド サービスの場所と可用性を追跡します。

* StorageGRIDシステムには、link:../maintain/understanding-adc-service-quorum.html["ADCサービスの定足数"]各サイトでいつでも利用できるようになります。
* 各サイトの少なくとも 3 つのストレージ ノードに ADC サービスが含まれている必要があります。
* すべてのストレージ ノードに ADC サービスを追加することはお勧めしません。  ADC サービスを多すぎる数含めると、ノード間の通信量が増加して速度が低下する可能性があります。
* 1 つのグリッドには、ADC サービスを備えたストレージ ノードが 48 個を超えてはなりません。これは、各サイトに 3 つの ADC サービスがある 16 サイトに相当します。
* 通常、新しいノードに対して *ADC サービス* 設定を選択する場合は、 *自動* を選択する必要があります。新しいノードが ADC サービスを含む別のストレージ ノードを置き換える場合にのみ、[はい] を選択します。残っている ADC サービスが少なすぎる場合はストレージ ノードを廃止することはできないため、これにより、古いサービスが削除される前に新しい ADC サービスが利用可能になります。
* ADC サービスをデプロイ後にノードに追加することはできません。

