---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: ストレージ ノードを追加した後、消去コーディングの再バランス手順を使用して、消去コーディングされたフラグメントを既存および新しいストレージ ノード間で再配布できます。 
---
= ストレージノードを追加した後、消失訂正符号化データを再バランスする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ ノードを追加した後、消失訂正符号化 (EC) 再バランス手順を使用して、消失訂正符号化されたフラグメントを既存および新しいストレージ ノード間で再配布できます。

.開始する前に
* 新しいストレージ ノードを追加するための拡張手順が完了しました。
* あなたは、link:considerations-for-rebalancing-erasure-coded-data.html["消失訂正符号化データの再バランスに関する考慮事項"] 。
* この手順では複製されたオブジェクト データは移動されず、EC 再バランス手順では、消去コード化されたデータの移動先を決定する際に各ストレージ ノード上の複製されたデータの使用は考慮されないことを理解します。
* あなたは `Passwords.txt`ファイル。


.この手順を実行すると何が起こるか
手順を開始する前に、次の点に注意してください。

* 1 つ以上のボリュームがオフライン (マウント解除) の場合、またはオンライン (マウント) であってもエラー状態の場合、EC 再バランス手順は開始されません。
* EC 再バランス手順では、一時的に大量のストレージが予約されます。ストレージアラートがトリガーされる可能性がありますが、再バランスが完了すると解決されます。予約に十分なストレージがない場合、EC 再バランス手順は失敗します。  EC 再バランス手順が完了すると、手順が失敗したか成功したかに関係なく、ストレージ予約が解放されます。
* EC 再バランス手順の実行中にボリュームがオフラインになった場合、再バランス手順は終了します。すでに移動されたデータ断片は新しい場所に残り、データが失われることはありません。
+
すべてのボリュームがオンラインに戻ったら、この手順を再実行できます。

* EC 再バランス手順の実行中は、ILM 操作と S3 クライアント操作のパフォーマンスが影響を受ける可能性があります。
+

NOTE: オブジェクト (またはオブジェクトの一部) をアップロードする S3 API 操作は、完了までに 24 時間以上かかる場合、EC 再バランス手順中に失敗する可能性があります。適用可能な ILM ルールが取り込み時にバランス配置または厳密配置を使用する場合、長時間の PUT 操作は失敗します。次のエラーが報告されます: `500 Internal Server Error` 。

* この手順中、すべてのノードのストレージ容量制限は 80% になります。この制限を超えても、ターゲット データ パーティションの下に格納されるノードは、以下から除外されます。
+
** サイトアンバランス値
** ジョブ完了条件
+

NOTE: ターゲット データ パーティションは、サイトの合計データをノード数で割ることによって計算されます。



* *ジョブの完了条件*。  EC 再バランス手順は、次のいずれかが当てはまる場合に完了したとみなされます。
+
** 消去コード化されたデータはこれ以上移動できません。
** すべてのノードのデータは、ターゲット データ パーティションの 5% の偏差以内です。
** この手続きは30日間実行されています。




.手順
. [[review_object_storage]]再バランス調整を計画しているサイトの現在のオブジェクト ストレージの詳細を確認します。
+
.. 「NODES」を選択します。
.. サイトの最初のストレージ ノードを選択します。
.. *ストレージ*タブを選択します。
.. ストレージ ノード上の複製されたデータと消去コード化されたデータの現在の量を確認するには、「使用済みストレージ - オブジェクト データ」チャートの上にカーソルを置きます。
.. これらの手順を繰り返して、サイト内の他のストレージ ノードを表示します。


. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
+
ルートとしてログインすると、プロンプトは `$`に `#`。



. 手順を開始します。
+
`rebalance-data start --site "_サイト名_"

+
「_site-name_」には、新しいストレージ ノードを追加した最初のサイトを指定します。同封 `site-name`引用符で囲みます。

+
EC 再バランス手順が開始され、ジョブ ID が返されます。

. ジョブ ID をコピーします。
. [[view-status]]EC 再バランス手順のステータスを監視します。
+
** 単一の EC 再バランス手順のステータスを表示するには:
+
`rebalance-data status --job-id _job-id_`

+
のために `_job-id_`、手順を開始したときに返された ID を指定します。

** 現在の EC 再バランス手順と以前に完了した手順のステータスを表示するには:
+
`rebalance-data status`

+
[NOTE]
====
rebalance-data コマンドのヘルプを取得するには:

`rebalance-data --help`

====


. 返されたステータスに基づいて、追加の手順を実行します。
+
** もし `State`は `In progress`EC リバランス操作はまだ実行中です。手順が完了するまで定期的に監視する必要があります。
+
使用 `Site Imbalance`この値は、サイト内のストレージ ノード間での消去コード データの使用量の不均衡を評価するために使用されます。この値の範囲は 1.0 ～ 0 で、0 は消去コーディング データの使用がサイト内のすべてのストレージ ノード間で完全に分散されていることを示します。

+
すべてのノードのデータがターゲット データ パーティションの 5% の偏差以内になると、EC 再バランス ジョブは完了したとみなされ、停止します。

** もし `State`は `Success`オプションで<<review_object_storage,オブジェクトストレージのレビュー>>サイトの更新された詳細を確認します。
+
消去コード化されたデータは、サイト内のストレージ ノード間でよりバランスが取れるようになるはずです。

** もし `State`は `Failure`:
+
... サイト内のすべてのストレージ ノードがグリッドに接続されていることを確認します。
... これらのストレージ ノードに影響を与える可能性のあるアラートを確認し、解決します。
... EC 再バランス手順を再開します。
+
`rebalance-data start –-job-id _job-id_`

... <<view-status,ステータスを表示する>>新しい手順の。もし `State`まだ `Failure`テクニカル サポートにお問い合わせください。




. EC 再バランス手順によって過度の負荷が発生している場合 (たとえば、取り込み操作が影響を受ける場合)、手順を一時停止します。
+
`rebalance-data pause --job-id _job-id_`

. EC 再バランス手順を終了する必要がある場合 (たとえば、 StorageGRIDソフトウェアのアップグレードを実行するため)、次のように入力します。
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: EC 再バランス手順を終了すると、すでに移動されたデータ フラグメントは新しい場所に残ります。データは元の場所に戻されません。

. 複数のサイトで消去コーディングを使用している場合は、影響を受ける他のすべてのサイトに対してこの手順を実行します。

