---
permalink: troubleshoot/troubleshooting-syslog-server.html 
sidebar: sidebar 
keywords: how to troubleshoot the external syslog server 
summary: 次の表では、外部 Syslog サーバーの使用に関連する可能性のあるエラー メッセージについて説明し、修正アクションを示します。 
---
= 外部 syslog サーバーのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表では、外部 Syslog サーバーの使用に関連する可能性のあるエラー メッセージについて説明し、修正アクションを示します。

監査情報を外部 Syslog サーバーに送信する方法の詳細については、以下を参照してください。

* link:../monitor/considerations-for-external-syslog-server.html["外部Syslogサーバーの使用に関する考慮事項"]
* link:../monitor/configure-audit-messages.html["監査メッセージと外部Syslogサーバーを構成する"]


[cols="1a,3a"]
|===
| エラー メッセージ | 説明と推奨アクション 


 a| 
ホスト名を解決できません
 a| 
Syslog サーバーに入力した FQDN を IP アドレスに解決できませんでした。

. 入力したホスト名を確認してください。  IP アドレスを入力した場合は、それが WXYZ (ドット付き 10 進数) 表記の有効な IP アドレスであることを確認してください。
. DNS サーバーが正しく設定されていることを確認します。
. 各ノードが DNS サーバーの IP アドレスにアクセスできることを確認します。




 a| 
接続が拒否されました
 a| 
Syslog サーバーへの TCP または TLS 接続が拒否されました。ホストの TCP または TLS ポートをリッスンしているサービスがないか、ファイアウォールがアクセスをブロックしている可能性があります。

. Syslog サーバーの正しい FQDN または IP アドレス、ポート、プロトコルを入力したことを確認します。
. Syslog サービスのホストが、指定されたポートでリッスンしている Syslog デーモンを実行していることを確認します。
. ファイアウォールがノードから Syslog サーバーの IP およびポートへの TCP/TLS 接続へのアクセスをブロックしていないことを確認します。




 a| 
ネットワークにアクセスできません
 a| 
Syslog サーバーは直接接続されたサブネット上にありません。ルータは、リストされたノードからのテスト メッセージを syslog サーバーに転送できなかったことを示す ICMP 障害メッセージを返しました。

. Syslog サーバーの正しい FQDN または IP アドレスを入力したことを確認します。
. リストされている各ノードについて、グリッド ネットワーク サブネット リスト、管理ネットワーク サブネット リスト、およびクライアント ネットワーク ゲートウェイを確認します。これらが、予想されるネットワーク インターフェイスとゲートウェイ (グリッド、管理、またはクライアント) を介して syslog サーバーにトラフィックをルーティングするように構成されていることを確認します。




 a| 
ホストに到達できません
 a| 
Syslog サーバーは、直接接続されたサブネット (リストされたノードのグリッド、管理、またはクライアント IP アドレスに使用されるサブネット) 上にあります。ノードはテスト メッセージを送信しようとしましたが、Syslog サーバーの MAC アドレスに対する ARP 要求への応答を受信しませんでした。

. Syslog サーバーの正しい FQDN または IP アドレスを入力したことを確認します。
. syslog サービスを実行しているホストが起動していることを確認します。




 a| 
接続がタイムアウトしました
 a| 
TCP/TLS 接続を試行しましたが、長時間にわたって syslog サーバーからの応答が受信されませんでした。ルーティングの設定に誤りがあるか、ファイアウォールが応答を送信せずにトラフィックをドロップしている可能性があります (一般的な設定)。

. Syslog サーバーの正しい FQDN または IP アドレスを入力したことを確認します。
. リストされている各ノードについて、グリッド ネットワーク サブネット リスト、管理ネットワーク サブネット リスト、およびクライアント ネットワーク ゲートウェイを確認します。  Syslog サーバーに到達すると予想されるネットワーク インターフェイスとゲートウェイ (グリッド、管理、またはクライアント) を使用して、Syslog サーバーにトラフィックをルーティングするようにこれらが構成されていることを確認します。
. ファイアウォールが、リストされているノードから Syslog サーバーの IP とポートへの TCP/TLS 接続へのアクセスをブロックしていないことを確認します。




 a| 
パートナーによって接続が閉じられました
 a| 
Syslog サーバーへの TCP 接続は正常に確立されましたが、その後閉じられました。これには次のような理由が考えられます:

* Syslog サーバーが再起動またはリブートされた可能性があります。
* ノードと syslog サーバーの TCP/TLS 設定が異なる場合があります。
* 中間ファイアウォールがアイドル状態の TCP 接続を閉じている可能性があります。
* syslog サーバー ポートをリッスンしている非 syslog サーバーが接続を閉じた可能性があります。


この問題を解決するには:

. Syslog サーバーの正しい FQDN または IP アドレス、ポート、プロトコルを入力したことを確認します。
. TLS を使用している場合は、syslog サーバーも TLS を使用していることを確認してください。  TCP を使用している場合は、syslog サーバーも TCP を使用していることを確認してください。
. 中間ファイアウォールがアイドル状態の TCP 接続を閉じるように構成されていないことを確認します。




 a| 
TLS証明書エラー
 a| 
Syslog サーバーから受信したサーバー証明書は、指定した CA 証明書バンドルおよびクライアント証明書と互換性がありません。

. CA 証明書バンドルとクライアント証明書 (存在する場合) が syslog サーバー上のサーバー証明書と互換性があることを確認します。
. Syslog サーバーからのサーバー証明書の ID に、予想される IP または FQDN 値が含まれていることを確認します。




 a| 
転送停止
 a| 
Syslog レコードが Syslog サーバーに転送されなくなり、 StorageGRID はその理由を検出できません。

このエラーとともに提供されるデバッグ ログを確認して、根本原因を特定してください。



 a| 
TLSセッションが終了しました
 a| 
Syslog サーバーが TLS セッションを終了しましたが、 StorageGRID はその理由を検出できません。

. このエラーとともに提供されるデバッグ ログを確認して、根本原因を特定してください。
. Syslog サーバーの正しい FQDN または IP アドレス、ポート、プロトコルを入力したことを確認します。
. TLS を使用している場合は、syslog サーバーも TLS を使用していることを確認してください。  TCP を使用している場合は、syslog サーバーも TCP を使用していることを確認してください。
. CA 証明書バンドルとクライアント証明書 (存在する場合) が syslog サーバーのサーバー証明書と互換性があることを確認します。
. Syslog サーバーからのサーバー証明書の ID に、予想される IP または FQDN 値が含まれていることを確認します。




 a| 
結果クエリに失敗しました
 a| 
Syslog サーバーの構成とテストに使用される管理ノードは、リストされているノードからテスト結果を要求できません。  1 つ以上のノードがダウンしている可能性があります。

. 標準的なトラブルシューティング手順に従って、ノードがオンラインであり、必要なすべてのサービスが実行されていることを確認します。
. リストされたノードで miscd サービスを再起動します。


|===