---
permalink: troubleshoot/troubleshoot-s3-put-object-size-too-large-alert.html 
sidebar: sidebar 
keywords: how to troubleshoot S3 PUT Object size too large alert, S3 PutObject size 
summary: テナントが 5 GiB の S3 サイズ制限を超える非マルチパート PutObject 操作を試行すると、S3 PUT オブジェクト サイズが大きすぎるというアラートがトリガーされます。 
---
= S3 PUT オブジェクトサイズが大きすぎるというアラートのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナントが 5 GiB の S3 サイズ制限を超える非マルチパート PutObject 操作を試行すると、S3 PUT オブジェクト サイズが大きすぎるというアラートがトリガーされます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたが持っているlink:../admin/admin-group-permissions.html["特定のアクセス権限"]。


5 GiB を超えるオブジェクトを使用するテナントを特定し、通知できるようにします。

.手順
. *構成* > *監視* > *監査および syslog サーバー* に移動します。
. クライアント書き込みが正常の場合は、監査ログにアクセスします。
+
.. 入力 `ssh admin@_primary_Admin_Node_IP_`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
.. ルートに切り替えるには、次のコマンドを入力します。 `su -`
.. 記載されているパスワードを入力してください `Passwords.txt`ファイル。
+
ルートとしてログインすると、プロンプトは `$`に `#`。

.. 監査ログが保存されているディレクトリに変更します。
+
--
監査ログ ディレクトリと適用可能なノードは、監査の宛先設定によって異なります。

[cols="1a,2a"]
|===
| オプション | デスティネーション 


 a| 
ローカルノード（デフォルト）
 a| 
`/var/local/log/localaudit.log`



 a| 
管理ノード/ローカルノード
 a| 
*** 管理ノード (プライマリおよび非プライマリ): `/var/local/audit/export/audit.log`
*** すべてのノード: `/var/local/log/localaudit.log`このモードでは通常、ファイルは空であるか、存在しません。




 a| 
外部 syslog サーバー
 a| 
`/var/local/log/localaudit.log`

|===
監査先の設定に応じて、次のように入力します。 `cd /var/local/log`または `/var/local/audit/export/`

詳細については、link:../monitor/configure-audit-messages.html#select-audit-information-destinations["監査情報の送信先を選択する"] 。

--
.. 5 GiB を超えるオブジェクトを使用しているテナントを特定します。
+
... 入力 `zgrep SPUT * | egrep "CSIZ\(UI64\):([5-9]|[1-9][0-9]+)[0-9]{9}"`
... 結果の各監査メッセージについては、 `S3AI`テナント アカウント ID を決定するフィールド。メッセージ内の他のフィールドを使用して、クライアント、バケット、およびオブジェクトによって使用された IP アドレスを判別します。
+
[cols="1a,2a"]
|===
| コード | 説明 


| SAIP  a| 
ソースIP



| S3AI  a| 
テナントID



| S3BK  a| 
バケット



| S3KY  a| 
オブジェクト



| CSIZ  a| 
サイズ（バイト）

|===
+
*監査ログ結果の例*

+
[listing]
----
audit.log:2023-01-05T18:47:05.525999 [AUDT:[RSLT(FC32):SUCS][CNID(UI64):1672943621106262][TIME(UI64):804317333][SAIP(IPAD):"10.96.99.127"][S3AI(CSTR):"93390849266154004343"][SACC(CSTR):"bhavna"][S3AK(CSTR):"06OX85M40Q90Y280B7YT"][SUSR(CSTR):"urn:sgws:identity::93390849266154004343:root"][SBAI(CSTR):"93390849266154004343"][SBAC(CSTR):"bhavna"][S3BK(CSTR):"test"][S3KY(CSTR):"large-object"][CBID(UI64):0x077EA25F3B36C69A][UUID(CSTR):"A80219A2-CD1E-466F-9094-B9C0FDE2FFA3"][CSIZ(UI64):6040000000][MTME(UI64):1672943621338958][AVER(UI32):10][ATIM(UI64):1672944425525999][ATYP(FC32):SPUT][ANID(UI32):12220829][AMID(FC32):S3RQ][ATID(UI64):4333283179807659119]]
----




. クライアント書き込みが正常でない場合は、アラートのテナント ID を使用してテナントを識別します。
+
.. *サポート* > *ツール* > *ログ* に移動します。アラート内のストレージ ノードのアプリケーション ログを収集します。アラートの前後 15 分を指定します。
.. ファイルを解凍して `bycast.log`:
+
`/GID<grid_id>_<time_stamp>/<site_node>/<time_stamp>/grid/bycast.log`

.. ログを検索する `method=PUT`そしてクライアントを識別します `clientIP`分野。
+
*bycast.logの例*

+
[listing]
----
Jan  5 18:33:41 BHAVNAJ-DC1-S1-2-65 ADE: |12220829 1870864574 S3RQ %CEA 2023-01-05T18:33:41.208790| NOTICE   1404 af23cb66b7e3efa5 S3RQ: EVENT_PROCESS_CREATE - connection=1672943621106262 method=PUT name=</test/4MiB-0> auth=<V4> clientIP=<10.96.99.127>
----


. PutObject の最大サイズは 5 GiB であり、5 GiB を超えるオブジェクトにはマルチパートアップロードを使用するようにテナントに通知します。
. アプリケーションが変更された場合は、1 週間アラートを無視してください。

