---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: オブジェクトは、クライアント アプリケーションからの読み取り要求、複製されたオブジェクト データのバックグラウンド検証、ILM の再評価、ストレージ ノードの回復中のオブジェクト データの復元など、さまざまな理由で取得できます。 
---
= 失われたオブジェクトデータのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトは、クライアント アプリケーションからの読み取り要求、複製されたオブジェクト データのバックグラウンド検証、ILM の再評価、ストレージ ノードの回復中のオブジェクト データの復元など、さまざまな理由で取得できます。

StorageGRIDシステムは、オブジェクトのメタデータ内の場所情報を使用して、オブジェクトを取得する場所を決定します。オブジェクトのコピーが予期された場所に見つからない場合、システムは、ILM ポリシーにオブジェクトのコピーを 2 つ以上作成するルールが含まれていると想定して、システム内の他の場所からオブジェクトの別のコピーを取得しようとします。

この取得が成功すると、 StorageGRIDシステムはオブジェクトの失われたコピーを置き換えます。それ以外の場合は、次のように「オブジェクトが失われました」というアラートがトリガーされます。

* 複製されたコピーの場合、別のコピーを取得できない場合、オブジェクトは失われたとみなされ、アラートがトリガーされます。
* 消去コード化されたコピーの場合、予想される場所からコピーを取得できない場合、別の場所からコピーを取得しようとする前に、破損コピー検出 (ECOR) 属性が 1 増加します。他のコピーが見つからない場合、アラートがトリガーされます。


すべての「オブジェクト損失」アラートをただちに調査して、損失の根本原因を特定し、オブジェクトがオフラインまたは現在利用できないストレージ ノードにまだ存在するかどうかを確認する必要があります。見るlink:../troubleshoot/investigating-lost-objects.html["紛失物の調査"] 。

コピーのないオブジェクト データが失われた場合、回復ソリューションはありません。ただし、既知の紛失オブジェクトによって新しい紛失オブジェクトが隠されないように、紛失オブジェクト カウンターをリセットする必要があります。見るlink:resetting-lost-and-missing-object-counts.html["紛失した物や行方不明の物の数をリセットする"] 。
