---
permalink: ilm/advantages-disadvantages-and-requirements-for-ec.html 
sidebar: sidebar 
keywords: erasure coding advantages, disadvantages, EC requirements 
summary: オブジェクト データの損失を防ぐためにレプリケーションを使用するか、消失訂正コーディングを使用するかを決定する前に、消失訂正コーディングの利点、欠点、および要件を理解しておく必要があります。 
---
= 消失訂正符号化の利点、欠点、要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクト データの損失を防ぐためにレプリケーションを使用するか、消失訂正コーディングを使用するかを決定する前に、消失訂正コーディングの利点、欠点、および要件を理解しておく必要があります。



== 消失訂正符号の利点

レプリケーションと比較すると、消去コーディングにより信頼性、可用性、およびストレージ効率が向上します。

* *信頼性*: 信頼性はフォールト トレランス、つまりデータの損失なしに耐えられる同時障害の数という観点から評価されます。レプリケーションでは、複数の同一コピーが異なるノードおよびサイト間に保存されます。消失訂正符号化では、オブジェクトはデータとパリティのフラグメントにエンコードされ、多数のノードとサイトに分散されます。この分散により、サイトとノードの両方の障害からの保護が提供されます。レプリケーションと比較すると、消去コーディングは同等のストレージ コストで信頼性を向上させます。
* *可用性*: 可用性は、ストレージ ノードに障害が発生したりアクセスできなくなった場合にオブジェクトを取得できる能力として定義できます。レプリケーションと比較すると、消去コーディングでは同等のストレージ コストで可用性が向上します。
* *ストレージ効率*: 同様のレベルの可用性と信頼性を実現するために、消失訂正コーディングによって保護されたオブジェクトは、レプリケーションによって保護された同じオブジェクトよりもディスク容量を少なく消費します。たとえば、2 つのサイトに複製された 10 MB のオブジェクトは 20 MB のディスク領域 (2 つのコピー) を消費しますが、6+3 消失訂正符号化スキームを使用して 3 つのサイト間で消失訂正符号化されたオブジェクトは 15 MB のディスク領域しか消費しません。
+

NOTE: 消去コード化されたオブジェクトのディスク容量は、オブジェクト サイズとストレージ オーバーヘッドの合計として計算されます。ストレージ オーバーヘッドのパーセンテージは、パリティ フラグメントの数をデータ フラグメントの数で割った値です。





== 消失訂正符号の欠点

レプリケーションと比較すると、消失訂正符号化には次のような欠点があります。

* 消去コーディング方式に応じて、ストレージ ノードとサイトの数を増やすことが推奨されます。対照的に、オブジェクト データを複製する場合は、コピーごとに 1 つのストレージ ノードのみが必要になります。見るlink:what-erasure-coding-schemes-are.html#erasure-coding-schemes-for-storage-pools-containing-three-or-more-sites["3つ以上のサイトを含むストレージプールの消失訂正符号化方式"]そしてlink:what-erasure-coding-schemes-are.html#erasure-coding-schemes-for-one-site-storage-pools["ワンサイトストレージプールの消失訂正符号化方式"]。
* ストレージ拡張のコストと複雑さが増大します。レプリケーションを使用するデプロイメントを拡張するには、オブジェクトのコピーが作成されるすべての場所にストレージ容量を追加します。消去コーディングを使用する展開を拡張するには、使用中の消去コーディング スキームと既存のストレージ ノードの使用状況の両方を考慮する必要があります。たとえば、既存のノードが100%いっぱいになるまで待つ場合は、少なくとも `k+m`ストレージ ノードですが、既存のノードが 70% 使用されているときに拡張すると、サイトごとに 2 つのノードを追加して、使用可能なストレージ容量を最大化できます。詳細については、以下を参照してください。 link:../expand/adding-storage-capacity-for-erasure-coded-objects.html["消失訂正コード付きオブジェクト用のストレージ容量を追加する"] 。
* 地理的に分散したサイト間で消去コーディングを使用すると、取得の待ち時間が長くなります。消失訂正符号化され、リモート サイト間に分散されているオブジェクトのオブジェクト フラグメントは、複製されてローカル (クライアントが接続するのと同じサイト) で使用できるオブジェクトよりも、WAN 接続経由で取得するのに時間がかかります。
* 地理的に分散したサイト間で消去コーディングを使用する場合、特に頻繁に取得されるオブジェクトや WAN ネットワーク接続を介したオブジェクトの修復の場合、取得と修復のための WAN ネットワーク トラフィックの使用量が増加します。
* サイト間で消去コーディングを使用すると、サイト間のネットワーク遅延が増加するため、オブジェクトの最大スループットが大幅に低下します。この減少は、TCP ネットワーク スループットの対応する減少によるもので、 StorageGRIDシステムがオブジェクト フラグメントを保存および取得できる速度に影響します。
* コンピューティング リソースの使用率が高くなります。




== 消失訂正符号を使用する場合

消失訂正符号化は、次の要件に最適です。

* サイズが 1 MB を超えるオブジェクト。
+

NOTE: 消失訂正符号化は、1 MB を超えるオブジェクトに最適です。非常に小さな消去符号化フラグメントを管理するオーバーヘッドを回避するために、200 KB 未満のオブジェクトには消去符号化を使用しないでください。

* 頻繁に取得されないコンテンツの長期保存またはコールド ストレージ。
* 高いデータ可用性と信頼性。
* サイト全体およびノードの障害に対する保護。
* ストレージ効率。
* 複数の複製されたコピーではなく、単一の消去コード化されたコピーのみによる効率的なデータ保護を必要とする単一サイトの展開。
* サイト間の遅延が 100 ミリ秒未満の複数サイトの展開。

