---
permalink: ilm/advantages-disadvantages-of-ingest-options.html 
sidebar: sidebar 
keywords: ingest options, balance ingest, strict ingest, dual commit ingest 
summary: '取り込み時にデータを保護するための 3 つのオプション (バランス、厳密、またはデュアル コミット) のそれぞれの利点と欠点を理解することで、ILM ルールにどのオプションを選択するかを決定するのに役立ちます。' 
---
= 取り込みオプションの利点、欠点、制限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
取り込み時にデータを保護するための 3 つのオプション (バランス、厳密、またはデュアル コミット) のそれぞれの利点と欠点を理解することで、ILM ルールにどのオプションを選択するかを決定するのに役立ちます。

取り込みオプションの概要については、link:data-protection-options-for-ingest.html["取り込みオプション"] 。



== バランス型と厳密型のオプションの利点

取り込み中に中間コピーを作成するデュアルコミットと比較すると、2 つの同期配置オプションには次の利点があります。

* *データ セキュリティの向上*: オブジェクト データは、ILM ルールの配置手順で指定されたとおりに直ちに保護されます。この手順は、複数のストレージ場所の障害など、さまざまな障害条件から保護するように構成できます。デュアルコミットでは、単一のローカルコピーの損失のみを保護できます。
* *より効率的なグリッド操作*: 各オブジェクトは取り込まれると 1 回だけ処理されます。  StorageGRIDシステムでは中間コピーを追跡または削除する必要がないため、処理負荷が軽減され、消費されるデータベース領域も少なくなります。
* *(バランス) 推奨*: バランス オプションは、最適な ILM 効率を提供します。厳密な取り込み動作が必要な場合、またはグリッドがデュアルコミットを使用するためのすべての基準を満たしている場合を除き、バランス オプションを使用することをお勧めします。
* *(厳密) オブジェクトの場所に関する確実性*: 厳密オプションは、ILM ルールの配置指示に従って、オブジェクトがすぐに保存されることを保証します。




== バランス型と厳密型のオプションの欠点

デュアルコミットと比較すると、バランスおよび厳密なオプションにはいくつかの欠点があります。

* *クライアントの取り込み時間が長くなる*: クライアントの取り込み待ち時間が長くなる可能性があります。 Balanced または Strict オプションを使用すると、すべての消去コード化フラグメントまたは複製されたコピーが作成されて保存されるまで、「取り込み成功」メッセージはクライアントに返されません。ただし、オブジェクト データは、最終的な配置にかなり早く到達する可能性が高くなります。
* *(厳密) 取り込み失敗率が高い*: 厳密オプションでは、 StorageGRID がILM ルールで指定されたすべてのコピーをすぐに作成できない場合、取り込みは失敗します。必要なストレージの場所が一時的にオフラインになっている場合や、ネットワークの問題によりサイト間でのオブジェクトのコピーが遅延している場合は、取り込み失敗率が高くなる可能性があります。
* *(Strict) S3 マルチパートアップロードの配置は、状況によっては期待どおりにならない場合があります*: Strict では、オブジェクトが ILM ルールで説明されているとおりに配置される、または取り込みが失敗すると予想されます。ただし、S3 マルチパートアップロードでは、オブジェクトの各部分が取り込まれると ILM が評価され、マルチパートアップロードが完了するとオブジェクト全体が評価されます。次のような状況では、予想とは異なる配置になる可能性があります。
+
** *S3 マルチパートアップロードの進行中に ILM が変更された場合*: 各パーツは、そのパーツが取り込まれたときにアクティブなルールに従って配置されるため、マルチパートアップロードが完了したときに、オブジェクトの一部のパーツが現在の ILM 要件を満たしていない可能性があります。このような場合、オブジェクトの取り込みは失敗しません。代わりに、正しく配置されていないパーツは ILM 再評価のキューに入れられ、後で正しい場所に移動されます。
** *ILM ルールがサイズに基づいてフィルタリングする場合*: パーツの ILM を評価する場合、 StorageGRID はオブジェクトのサイズではなくパーツのサイズに基づいてフィルタリングします。つまり、オブジェクトの一部は、オブジェクト全体の ILM 要件を満たさない場所に保存される可能性があります。たとえば、ルールで 10 GB 以上のすべてのオブジェクトを DC1 に保存し、それより小さいすべてのオブジェクトを DC2 に保存するように指定している場合、取り込み時に、10 個の部分からなるマルチパートアップロードの各 1 GB の部分が DC2 に保存されます。オブジェクトに対して ILM が評価されると、オブジェクトのすべての部分が DC1 に移動されます。


* *(Strict) オブジェクト タグまたはメタデータが更新され、新しく必要な配置が行えない場合でも、取り込みは失敗しません。*: Strict では、オブジェクトが ILM ルールで説明されているとおりに配置される、または取り込みが失敗すると予想されます。ただし、グリッドにすでに保存されているオブジェクトのメタデータまたはタグを更新しても、そのオブジェクトは再取り込まれません。つまり、更新によってトリガーされるオブジェクトの配置の変更は、すぐには行われません。配置の変更は、通常のバックグラウンド ILM プロセスによって ILM が再評価されるときに行われます。必要な配置変更ができない場合 (たとえば、新しく必要な場所が利用できないなど)、更新されたオブジェクトは、配置変更が可能になるまで現在の配置を保持します。




== バランスと厳密オプションによるオブジェクト配置の制限

バランスまたは厳密なオプションは、次の配置指示を含む ILM ルールには使用できません。

* 0 日目にクラウド ストレージ プールに配置します。
* ルールにユーザー定義の作成時刻が参照時刻として設定されている場合の、クラウド ストレージ プール内の配置。


これらの制限が存在するのは、 StorageGRID がクラウド ストレージ プールに同期的にコピーを作成できず、ユーザー定義の作成時刻が現在に解決される可能性があるためです。



== ILM ルールと一貫性がどのように相互作用してデータ保護に影響を与えるか

ILM ルールと一貫性の選択はどちらも、オブジェクトが保護される方法に影響します。これらの設定は相互作用する可能性があります。

たとえば、ILM ルールに選択された取り込み動作はオブジェクト コピーの初期配置に影響し、オブジェクトの保存時に使用される一貫性はオブジェクト メタデータの初期配置に影響します。  StorageGRID はクライアントの要求を満たすためにオブジェクトのデータとメタデータの両方にアクセスする必要があるため、一貫性と取り込み動作に一致する保護レベルを選択すると、初期データ保護が向上し、システム応答がより予測可能になります。

StorageGRIDで使用できる一貫性値の簡単な概要は次のとおりです。

* *すべて*: すべてのノードがオブジェクト メタデータを直ちに受信します。そうでない場合、要求は失敗します。
* *強力なグローバル*: オブジェクト メタデータはすべてのサイトに直ちに配布されます。すべてのサイトにわたるすべてのクライアント要求に対して、書き込み後の読み取りの一貫性を保証します。
* *強力サイト*: オブジェクト メタデータは、サイト内の他のノードに直ちに配布されます。サイト内のすべてのクライアント要求に対して、書き込み後の読み取り一貫性を保証します。
* *新規書き込み後の読み取り*: 新しいオブジェクトに対して書き込み後の読み取りの一貫性を提供し、オブジェクトの更新に対しては最終的な一貫性を提供します。高可用性とデータ保護の保証を提供します。ほとんどの場合に推奨されます。
* *利用可能*: 新しいオブジェクトとオブジェクトの更新の両方に対して最終的な一貫性を提供します。  S3 バケットの場合は、必要な場合にのみ使用してください (たとえば、めったに読み取られないログ値を含むバケットの場合や、存在しないキーに対する HEAD または GET 操作の場合など)。  S3 FabricPoolバケットではサポートされていません。



NOTE: 一貫性値を選択する前に、link:../s3/consistency-controls.html["一貫性の完全な説明を読む"] 。デフォルト値を変更する前に、利点と制限事項を理解しておく必要があります。



== 一貫性とILMルールの相互作用の例

次の ILM ルールと次の一貫性を持つ 2 つのサイト グリッドがあるとします。

* *ILM ルール*: ローカル サイトとリモート サイトに 1 つずつ、合計 2 つのオブジェクト コピーを作成します。厳密な取り込み動作を使用します。
* *一貫性*: 強力なグローバル (オブジェクト メタデータはすべてのサイトに直ちに配布されます)。


クライアントがオブジェクトをグリッドに保存すると、 StorageGRID は両方のオブジェクトのコピーを作成し、両方のサイトにメタデータを配布してから、クライアントに成功を返します。

オブジェクトは、取り込み成功メッセージの時点で損失から完全に保護されます。たとえば、取り込み直後にローカル サイトが失われた場合でも、オブジェクト データとオブジェクト メタデータの両方のコピーがリモート サイトに残ります。オブジェクトは完全に取得可能です。

代わりに同じ ILM ルールと強力なサイト一貫性を使用した場合、オブジェクト データがリモート サイトにレプリケートされた後、オブジェクト メタデータがそこに配布される前に、クライアントは成功メッセージを受信する可能性があります。この場合、オブジェクト メタデータの保護レベルは、オブジェクト データの保護レベルと一致しません。取り込み直後にローカル サイトが失われた場合、オブジェクト メタデータは失われます。オブジェクトを取得できません。

一貫性と ILM ルール間の相互関係は複雑になる可能性があります。サポートが必要な場合は、 NetAppにお問い合わせください。

.関連情報
link:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.html["例5: 厳格な取り込み動作のためのILMルールとポリシー"]
