---
permalink: ilm/comparing-cloud-storage-pools-to-cloudmirror-replication.html 
sidebar: sidebar 
keywords: cloud storage pools, cloudmirror replication 
summary: Cloud Storage Pools の使用を開始する際には、Cloud Storage Pools とStorageGRID CloudMirror レプリケーション サービスの類似点と相違点を理解しておくと役立ちます。 
---
= クラウド ストレージ プールと CloudMirror レプリケーションの比較
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cloud Storage Pools の使用を開始する際には、Cloud Storage Pools とStorageGRID CloudMirror レプリケーション サービスの類似点と相違点を理解しておくと役立ちます。

[cols="1a,3a,3a"]
|===
|  | クラウド ストレージ プール | CloudMirrorレプリケーションサービス 


 a| 
主な目的は何ですか?
 a| 
アーカイブターゲットとして機能します。クラウド ストレージ プール内のオブジェクト コピーは、オブジェクトの唯一のコピーにすることも、追加のコピーにすることもできます。つまり、オンサイトで 2 つのコピーを保持する代わりに、1 つのコピーをStorageGRID内に保持し、もう 1 つのコピーをクラウド ストレージ プールに送信することができます。
 a| 
テナントがStorageGRID内のバケット (ソース) から外部の S3 バケット (宛先) にオブジェクトを自動的に複製できるようにします。独立した S3 インフラストラクチャにオブジェクトの独立したコピーを作成します。



 a| 
どのように設定されていますか?
 a| 
グリッド マネージャーまたはグリッド管理 API を使用して、ストレージ プールと同じ方法で定義されます。 ILM ルール内の配置場所として選択できます。ストレージ プールはストレージ ノードのグループで構成されますが、クラウド ストレージ プールはリモート S3 または Azure エンドポイント (IP アドレス、資格情報など) を使用して定義されます。
 a| 
テナントユーザーlink:../tenant/configuring-cloudmirror-replication.html["CloudMirrorレプリケーションを構成する"]テナント マネージャーまたは S3 API を使用して CloudMirror エンドポイント (IP アドレス、資格情報など) を定義します。  CloudMirror エンドポイントが設定されると、そのテナント アカウントが所有するすべてのバケットを CloudMirror エンドポイントを指すように構成できます。



 a| 
設定の責任者は誰ですか?
 a| 
通常、グリッド管理者は
 a| 
通常、テナントユーザーは



 a| 
目的地はどこですか？
 a| 
* 互換性のある S3 インフラストラクチャ (Amazon S3 を含む)
* Azure BLOB アーカイブ層
* Google Cloud Platform（GCP）

 a| 
* 互換性のある S3 インフラストラクチャ (Amazon S3 を含む)
* Google Cloud Platform（GCP）




 a| 
オブジェクトが目的地に移動される原因は何ですか?
 a| 
アクティブな ILM ポリシー内の 1 つ以上の ILM ルール。  ILM ルールは、 StorageGRID がクラウド ストレージ プールに移動するオブジェクトと、そのオブジェクトがいつ移動されるかを定義します。
 a| 
CloudMirror エンドポイントで設定されたソースバケットに新しいオブジェクトを取り込む行為。バケットが CloudMirror エンドポイントで構成される前にソース バケットに存在していたオブジェクトは、変更されない限り複製されません。



 a| 
オブジェクトはどのように取得されますか?
 a| 
アプリケーションは、クラウド ストレージ プールに移動されたオブジェクトを取得するために、 StorageGRIDにリクエストを送信する必要があります。オブジェクトの唯一のコピーがアーカイブ ストレージに移行されている場合、 StorageGRID はオブジェクトを復元して取得できるようにするプロセスを管理します。
 a| 
宛先バケット内のミラーリングされたコピーは独立したコピーであるため、アプリケーションはStorageGRIDまたは S3 宛先にリクエストを送信することでオブジェクトを取得できます。たとえば、CloudMirror レプリケーションを使用してオブジェクトをパートナー組織にミラーリングするとします。パートナーは独自のアプリケーションを使用して、S3 の送信先からオブジェクトを直接読み取ったり更新したりできます。  StorageGRIDの使用は必須ではありません。



 a| 
宛先から直接読み取れますか?
 a| 
いいえ。クラウド ストレージ プールに移動されたオブジェクトは、 StorageGRIDによって管理されます。読み取りリクエストはStorageGRIDに送信する必要があります ( StorageGRIDが Cloud Storage Pool からの取得を担当します)。
 a| 
はい、ミラーコピーは独立したコピーであるためです。



 a| 
ソースからオブジェクトが削除されるとどうなりますか?
 a| 
オブジェクトはクラウド ストレージ プールからも削除されます。
 a| 
削除アクションは複製されません。削除されたオブジェクトはStorageGRIDバケット内に存在しなくなりますが、宛先バケット内には引き続き存在します。同様に、ソースに影響を与えずに宛先バケット内のオブジェクトを削除できます。



 a| 
災害発生後（StorageGRIDシステムが動作不能）にオブジェクトにアクセスするにはどうすればよいでしょうか?
 a| 
障害が発生したStorageGRIDノードを回復する必要があります。このプロセス中に、複製されたオブジェクトのコピーは、クラウド ストレージ プール内のコピーを使用して復元される場合があります。
 a| 
CloudMirror の宛先にあるオブジェクトのコピーはStorageGRIDから独立しているため、 StorageGRIDノードが回復される前に直接アクセスできます。

|===