---
permalink: ilm/considerations-for-cloud-storage-pools.html 
sidebar: sidebar 
keywords: what is a cloud storage pool, considerations for a cloud storage pool 
summary: Cloud Storage Pool を使用してオブジェクトをStorageGRIDシステムから移動する予定の場合は、Cloud Storage Pool の構成と使用に関する考慮事項を確認する必要があります。 
---
= クラウドストレージプールに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cloud Storage Pool を使用してオブジェクトをStorageGRIDシステムから移動する予定の場合は、Cloud Storage Pool の構成と使用に関する考慮事項を確認する必要があります。



== 一般的な考慮事項

* 一般的に、Amazon S3 Glacier や Azure Blob ストレージなどのクラウド アーカイブ ストレージは、オブジェクト データを安価に保存できる場所です。ただし、クラウド アーカイブ ストレージからデータを取得するためのコストは比較的高くなります。全体的なコストを最小限に抑えるには、クラウド ストレージ プール内のオブジェクトにアクセスするタイミングと頻度を考慮する必要があります。クラウド ストレージ プールの使用は、アクセス頻度が低いと予想されるコンテンツにのみお勧めします。
* Cloud Storage Pool ターゲットからオブジェクトを取得するための遅延が追加されるため、 FabricPoolでの Cloud Storage Pool の使用はサポートされていません。
* S3 オブジェクト ロックが有効になっているオブジェクトは、クラウド ストレージ プールに配置できません。
* クラウド ストレージ プールの宛先 S3 バケットで S3 オブジェクト ロックが有効になっている場合、バケット レプリケーション (PutBucketReplication) を構成する試みは AccessDenied エラーで失敗します。
* S3 オブジェクト ロックを使用した次のプラットフォーム、認証、プロトコルの組み合わせは、クラウド ストレージ プールではサポートされていません。
+
** *プラットフォーム*: Google Cloud Platform と Azure
** *認証タイプ*: IAM Roles Anywhereと匿名アクセス
** *プロトコル*: HTTP






== クラウド ストレージ プールに使用されるポートに関する考慮事項

ILM ルールが指定されたクラウド ストレージ プールとの間でオブジェクトを移動できるようにするには、システムのストレージ ノードを含むネットワークを構成する必要があります。次のポートがクラウド ストレージ プールと通信できることを確認する必要があります。

デフォルトでは、クラウド ストレージ プールは次のポートを使用します。

* *80*: httpで始まるエンドポイントURIの場合
* *443*: httpsで始まるエンドポイントURIの場合


クラウド ストレージ プールを作成または編集するときに、別のポートを指定できます。

非透過プロキシサーバーを使用する場合は、link:../admin/configuring-storage-proxy-settings.html["ストレージプロキシを構成する"]インターネット上のエンドポイントなどの外部エンドポイントにメッセージを送信できるようにします。



== コストに関する考慮事項

クラウド ストレージ プールを使用してクラウド内のストレージにアクセスするには、クラウドへのネットワーク接続が必要です。クラウド ストレージ プールを使用してStorageGRIDとクラウド間で移動すると予想されるデータの量に基づいて、クラウドにアクセスするために使用するネットワーク インフラストラクチャのコストを考慮し、適切にプロビジョニングする必要があります。

StorageGRID は、外部のクラウド ストレージ プールのエンドポイントに接続すると、接続を監視し、必要な操作を実行できることを確認するためにさまざまなリクエストを発行します。これらのリクエストにはいくらかの追加コストが関連しますが、クラウド ストレージ プールを監視するコストは、S3 または Azure にオブジェクトを保存する全体的なコストのほんの一部にすぎません。

オブジェクトを外部の Cloud Storage Pool エンドポイントからStorageGRIDに戻す必要がある場合は、さらに大きなコストが発生する可能性があります。次のいずれかの場合に、オブジェクトはStorageGRIDに戻される可能性があります。

* オブジェクトの唯一のコピーはクラウド ストレージ プール内にあるため、代わりにオブジェクトをStorageGRIDに保存することにしました。この場合、ILM ルールとポリシーを再構成します。 ILM 評価が行われると、 StorageGRID はCloud Storage Pool からオブジェクトを取得するための複数のリクエストを発行します。その後、 StorageGRID は指定された数の複製または消去コード化されたコピーをローカルに作成します。オブジェクトがStorageGRIDに戻された後、クラウド ストレージ プール内のコピーは削除されます。
* ストレージ ノードの障害によりオブジェクトが失われました。オブジェクトの唯一のコピーがクラウド ストレージ プール内にある場合、 StorageGRID はオブジェクトを一時的に復元し、回復したストレージ ノードに新しいコピーを作成します。



NOTE: オブジェクトが Cloud Storage Pool からStorageGRIDに戻されると、 StorageGRID はオブジェクトごとに Cloud Storage Pool エンドポイントに複数のリクエストを発行します。多数のオブジェクトを移動する前に、テクニカル サポートに連絡して、時間枠と関連コストを見積もってもらってください。



== S3: クラウドストレージプールバケットに必要な権限

Cloud Storage Pool に使用される外部 S3 バケットのポリシーでは、オブジェクトをバケットに移動したり、オブジェクトのステータスを取得したり、必要に応じて Glacier ストレージからオブジェクトを復元したりする権限をStorageGRIDに付与する必要があります。理想的には、 StorageGRIDはバケットへのフルコントロールアクセス権を持つ必要があります(`s3:*`); ただし、これが不可能な場合は、バケットポリシーでStorageGRIDに次の S3 権限を付与する必要があります。

* `s3:AbortMultipartUpload`
* `s3:DeleteObject`
* `s3:GetObject`
* `s3:ListBucket`
* `s3:ListBucketMultipartUploads`
* `s3:ListMultipartUploadParts`
* `s3:PutObject`
* `s3:RestoreObject`




== S3: 外部バケットのライフサイクルに関する考慮事項

StorageGRIDと Cloud Storage Pool で指定された外部 S3 バケット間のオブジェクトの移動は、ILM ルールとStorageGRID内のアクティブな ILM ポリシーによって制御されます。対照的に、クラウド ストレージ プールで指定された外部 S3 バケットから Amazon S3 Glacier または S3 Glacier Deep Archive (または Glacier ストレージクラスを実装するストレージソリューション) へのオブジェクトの移行は、そのバケットのライフサイクル設定によって制御されます。

Cloud Storage Pool からオブジェクトを移行する場合は、外部 S3 バケットに適切なライフサイクル設定を作成し、Glacier ストレージ クラスを実装し、S3 RestoreObject API をサポートするストレージ ソリューションを使用する必要があります。

たとえば、 StorageGRIDからクラウド ストレージ プールに移動されたすべてのオブジェクトを、Amazon S3 Glacier ストレージにすぐに移行したいとします。次のように、単一のアクション (*Transition*) を指定するライフサイクル設定を外部 S3 バケットに作成します。

[listing]
----
<LifecycleConfiguration>
  <Rule>
    <ID>Transition Rule</ID>
    <Filter>
       <Prefix></Prefix>
    </Filter>
    <Status>Enabled</Status>
    <Transition>
      <Days>0</Days>
      <StorageClass>GLACIER</StorageClass>
    </Transition>
  </Rule>
</LifecycleConfiguration>
----
このルールは、すべてのバケット オブジェクトを、作成された日 (つまり、 StorageGRIDからクラウド ストレージ プールに移動された日) に Amazon S3 Glacier に移行します。


CAUTION: 外部バケットのライフサイクルを設定するときは、オブジェクトの有効期限を定義するために *Expiration* アクションを使用しないでください。有効期限アクションにより、外部ストレージ システムは期限切れのオブジェクトを削除します。後でStorageGRIDから期限切れのオブジェクトにアクセスしようとすると、削除されたオブジェクトは見つかりません。

クラウドストレージプール内のオブジェクトをAmazon S3 GlacierではなくS3 Glacier Deep Archiveに移行する場合は、以下を指定します。 `<StorageClass>DEEP_ARCHIVE</StorageClass>`バケットのライフサイクルにおいて。ただし、 `Expedited` S3 Glacier Deep Archive からオブジェクトを復元する層。



== Azure: アクセス層に関する考慮事項

Azure ストレージ アカウントを構成するときに、既定のアクセス層をホットまたはクールに設定できます。クラウド ストレージ プールで使用するストレージ アカウントを作成する場合は、ホット層をデフォルト層として使用する必要があります。  StorageGRID はオブジェクトをクラウド ストレージ プールに移動するとすぐに層をアーカイブに設定しますが、デフォルトのホット設定を使用すると、30 日間の最小期間が経過する前にクール層から削除されたオブジェクトに対して早期削除料金が請求されることはありません。



== Azure: ライフサイクル管理はサポートされていません

クラウド ストレージ プールで使用されるコンテナーには、Azure Blob ストレージ ライフサイクル管理を使用しないでください。ライフサイクル操作は、クラウド ストレージ プールの操作に干渉する可能性があります。

.関連情報
link:creating-cloud-storage-pool.html["クラウドストレージプールを作成する"]
