---
permalink: ilm/creating-cloud-storage-pool.html 
sidebar: sidebar 
keywords: how to create cloud storage pool 
summary: クラウド ストレージ プールは、単一の外部 Amazon S3 バケットまたはその他の S3 互換プロバイダー、または Azure Blob ストレージ コンテナーを指定します。 
---
= クラウドストレージプールを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウド ストレージ プールは、単一の外部 Amazon S3 バケットまたはその他の S3 互換プロバイダー、または Azure Blob ストレージ コンテナーを指定します。

クラウド ストレージ プールを作成するときは、 StorageGRID がオブジェクトの保存に使用する外部バケットまたはコンテナの名前と場所、クラウド プロバイダーの種類 (Amazon S3/GCP または Azure Blob ストレージ)、およびStorageGRID が外部バケットまたはコンテナにアクセスするために必要な情報を指定します。

StorageGRID は、クラウド ストレージ プールを保存するとすぐにそれを検証するため、クラウド ストレージ プールで指定されたバケットまたはコンテナが存在し、アクセス可能であることを確認する必要があります。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["必要なアクセス権限"]。
* あなたは、link:considerations-for-cloud-storage-pools.html["クラウドストレージプールに関する考慮事項"] 。
* Cloud Storage Pool が参照する外部バケットまたはコンテナがすでに存在し、<<service-endpoint-info,サービスエンドポイント情報>> 。
* バケットまたはコンテナにアクセスするには、<<authentication-account-info,認証タイプのアカウント情報>>あなたが選ぶでしょう。


.手順
. *ILM* > *ストレージ プール* > *クラウド ストレージ プール* を選択します。
. *作成*を選択し、次の情報を入力します。
+
[cols="1a,3a"]
|===
| フィールド | 説明 


 a| 
クラウドストレージプール名
 a| 
クラウド ストレージ プールとその目的を簡単に説明する名前。  ILM ルールを構成するときに識別しやすい名前を使用します。



 a| 
プロバイダーの種類
 a| 
このクラウド ストレージ プールに使用するクラウド プロバイダー:

** *Amazon S3/GCP*: Amazon S3、Commercial Cloud Services (C2S) S3、Google Cloud Platform (GCP)、またはその他の S3 互換プロバイダーの場合はこのオプションを選択します。
** *Azure Blob ストレージ*




 a| 
バケツまたは容器
 a| 
外部 S3 バケットまたは Azure コンテナーの名前。クラウド ストレージ プールを保存した後、この値を変更することはできません。

|===
. [[service-endpoint-info]]プロバイダータイプの選択に基づいて、サービスエンドポイント情報を入力します。
+
[role="tabbed-block"]
====
.Amazon S3/GCP
--
.. プロトコルには、HTTPS または HTTP のいずれかを選択します。
+

NOTE: 機密データには HTTP 接続を使用しないでください。

.. ホスト名を入力します。例：
+
`s3-_aws-region_.amazonaws.com`

.. URL スタイルを選択します:
+
[cols="1a,3a"]
|===
| オプション | 説明 


 a| 
自動検出
 a| 
提供された情報に基づいて、使用する URL スタイルを自動的に検出します。たとえば、IP アドレスを指定すると、 StorageGRID はパス形式の URL を使用します。使用する特定のスタイルがわからない場合にのみ、このオプションを選択してください。



 a| 
仮想ホストスタイル
 a| 
仮想ホスト形式の URL を使用してバケットにアクセスします。仮想ホスト形式の URL には、ドメイン名の一部としてバケット名が含まれます。例： `+https://bucket-name.s3.company.com/key-name+`



 a| 
パススタイル
 a| 
バケットにアクセスするには、パス形式の URL を使用します。パス形式の URL には、末尾にバケット名が含まれます。例： `+https://s3.company.com/bucket-name/key-name+`

*注:* パス形式の URL オプションは推奨されておらず、 StorageGRIDの将来のリリースでは廃止される予定です。

|===
.. 必要に応じて、ポート番号を入力するか、デフォルトのポート (HTTPS の場合は 443、HTTP の場合は 80) を使用します。


--
.Azure Blob Storage
--
.. 次のいずれかの形式を使用して、サービス エンドポイントの URI を入力します。
+
*** `+https://host:port+`
*** `+http://host:port+`




例： `https://_myaccount_.blob.core.windows.net:443`

ポートを指定しない場合は、デフォルトで HTTPS にはポート 443 が使用され、HTTP にはポート 80 が使用されます。

--
====


. [[authentication-account-info]]*続行*を選択します。次に、認証タイプを選択し、クラウド ストレージ プールのエンドポイントに必要な情報を入力します。
+
[role="tabbed-block"]
====
.アクセス キー
--
_Amazon S3/GCP またはその他の S3 互換プロバイダーの場合_

.. *アクセス キー ID*: 外部バケットを所有するアカウントのアクセス キー ID を入力します。
.. *シークレットアクセスキー*: シークレットアクセスキーを入力します。


--
.IAMロールをどこでも
--
_AWS IAM Roles Anywhere サービスの場合_

StorageGRID は、AWS セキュリティ トークン サービス (STS) を使用して、AWS リソースにアクセスするための短命トークンを動的に生成します。

.. *AWS IAM Roles Anywhere リージョン*: クラウド ストレージ プールのリージョンを選択します。例：  `us-east-1` 。
.. *信頼アンカー URN*: 短命 STS 資格情報の要求を検証する信頼アンカーの URN を入力します。ルート CA または中間 CA にすることができます。
.. *プロファイル URN*: 信頼されたすべてのユーザーが引き受けることができるロールをリストする IAM Roles Anywhere プロファイルの URN を入力します。
.. *ロール URN*: 信頼できるすべてのユーザーが引き受けることができる IAM ロールの URN を入力します。
.. *セッション期間*: 一時的なセキュリティ資格情報とロール セッションの期間を入力します。少なくとも 15 分、最大 12 時間を入力してください。
.. *サーバー CA 証明書* (オプション): IAM Roles Anywhere サーバーを検証するための、PEM 形式の 1 つ以上の信頼できる CA 証明書。省略した場合、サーバーは検証されません。
.. *エンドエンティティ証明書*: 信頼アンカーによって署名された X509 証明書の PEM 形式の公開キー。  AWS IAM Roles Anywhere はこのキーを使用して STS トークンを発行します。
.. *エンド エンティティの秘密キー*: エンド エンティティ証明書の秘密キー。


--
.CAP（C2Sアクセスポータル）
--
_商用クラウドサービス（C2S）S3サービスの場合_

.. *一時資格情報 URL*: C2S アカウントに割り当てられたすべての必須およびオプションの API パラメータを含む、 StorageGRID がCAP サーバーから一時資格情報を取得するために使用する完全な URL を入力します。
.. *サーバー CA 証明書*: *参照* を選択し、 StorageGRID がCAP サーバーの検証に使用する CA 証明書をアップロードします。証明書は PEM でエンコードされ、適切な政府証明機関 (CA) によって発行される必要があります。
.. *クライアント証明書*: *参照* を選択し、 StorageGRID がCAP サーバーに対して自身を識別するために使用する証明書をアップロードします。クライアント証明書は PEM でエンコードされ、適切な政府証明機関 (CA) によって発行され、C2S アカウントへのアクセスが許可されている必要があります。
.. *クライアント秘密キー*: *参照* を選択し、クライアント証明書の PEM でエンコードされた秘密キーをアップロードします。
.. クライアントの秘密キーが暗号化されている場合は、クライアントの秘密キーを復号化するためのパスフレーズを入力します。それ以外の場合は、「*クライアント秘密キーのパスフレーズ*」フィールドを空白のままにします。



NOTE: クライアント証明書を暗号化する場合は、暗号化に従来の形式を使用します。  PKCS #8 暗号化形式はサポートされていません。

--
.Azure Blob Storage
--
_Azure Blob Storage の場合、共有キーのみ_

.. *アカウント名*: 外部コンテナを所有するストレージアカウントの名前を入力します
.. *アカウントキー*: ストレージアカウントの秘密キーを入力します


これらの値は、Azure ポータルを使用して見つけることができます。

--
.匿名
--
追加情報は必要ありません。

--
====
. *続行*を選択します。次に、使用するサーバー検証の種類を選択します。
+
[cols="1a,2a"]
|===
| オプション | 説明 


 a| 
ストレージノードOSでルートCA証明書を使用する
 a| 
接続を保護するには、オペレーティング システムにインストールされている Grid CA 証明書を使用します。



 a| 
カスタムCA証明書を使用する
 a| 
カスタム CA 証明書を使用します。  *参照*を選択し、PEM でエンコードされた証明書をアップロードします。



 a| 
証明書を検証しない
 a| 
このオプションを選択すると、クラウド ストレージ プールへの TLS 接続は安全ではなくなります。

|===
. *保存*を選択します。
+
クラウド ストレージ プールを保存すると、 StorageGRID は次の処理を実行します。

+
** バケットまたはコンテナとサービス エンドポイントが存在し、指定した資格情報を使用してアクセスできることを検証します。
** バケットまたはコンテナにマーカー ファイルを書き込み、それを Cloud Storage プールとして識別します。このファイルは絶対に削除しないでください。 `x-ntap-sgws-cloud-pool-uuid` 。
+
Cloud Storage Pool の検証に失敗した場合は、検証が失敗した理由を説明するエラー メッセージが表示されます。たとえば、証明書エラーがある場合や、指定したバケットまたはコンテナがまだ存在しない場合には、エラーが報告されることがあります。



. エラーが発生した場合は、link:troubleshooting-cloud-storage-pools.html["クラウド ストレージ プールのトラブルシューティング手順"]問題を解決してから、クラウド ストレージ プールを再度保存してください。

