---
permalink: ilm/editing-cloud-storage-pool.html 
sidebar: sidebar 
keywords: edit cloud storage pool 
summary: クラウド ストレージ プールを編集して、名前、サービス エンドポイント、その他の詳細を変更することはできますが、クラウド ストレージ プールの S3 バケットまたは Azure コンテナーを変更することはできません。 
---
= クラウドストレージプールを編集する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウド ストレージ プールを編集して、名前、サービス エンドポイント、その他の詳細を変更することはできますが、クラウド ストレージ プールの S3 バケットまたは Azure コンテナーを変更することはできません。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたが持っているlink:../admin/admin-group-permissions.html["特定のアクセス権限"]。
* あなたは、link:considerations-for-cloud-storage-pools.html["クラウドストレージプールに関する考慮事項"] 。


.手順
. *ILM* > *ストレージ プール* > *クラウド ストレージ プール* を選択します。
+
クラウド ストレージ プール テーブルには、既存のクラウド ストレージ プールが一覧表示されます。

. 編集するクラウド ストレージ プールのチェックボックスをオンにして、[*アクション*] > [*編集*] を選択します。
+
または、クラウド ストレージ プールの名前を選択し、[編集] を選択します。

. 必要に応じて、クラウド ストレージ プール名、サービス エンドポイント、認証資格情報、または証明書検証方法を変更します。
+

NOTE: クラウド ストレージ プールのプロバイダー タイプ、S3 バケット、または Azure コンテナーを変更することはできません。

+
以前にサーバー証明書またはクライアント証明書をアップロードした場合は、[証明書の詳細] アコーディオンを展開して、現在使用中の証明書を確認できます。

. *保存*を選択します。
+
クラウド ストレージ プールを保存すると、 StorageGRID はバケットまたはコンテナとサービス エンドポイントが存在し、指定した認証情報を使用してそれらにアクセスできることを検証します。

+
クラウド ストレージ プールの検証が失敗すると、エラー メッセージが表示されます。たとえば、証明書エラーがある場合、エラーが報告される可能性があります。

+
説明書をご覧くださいlink:troubleshooting-cloud-storage-pools.html["クラウド ストレージ プールのトラブルシューティング"]問題を解決してから、クラウド ストレージ プールを再度保存してください。


