---
permalink: ilm/editing-storage-pool.html 
sidebar: sidebar 
keywords: edit storage pool 
summary: ストレージ プールを編集して、名前を変更したり、サイトやストレージ グレードを更新したりできます。 
---
= ストレージプールを編集する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ プールを編集して、名前を変更したり、サイトやストレージ グレードを更新したりできます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたが持っているlink:../admin/admin-group-permissions.html["特定のアクセス権限"]。
* あなたは、link:guidelines-for-creating-storage-pools.html["ストレージプールを作成するためのガイドライン"] 。
* アクティブな ILM ポリシーのルールによって使用されるストレージ プールを編集する予定の場合は、変更がオブジェクト データの配置にどのように影響するかを考慮しておく必要があります。


.タスク概要
アクティブな ILM ポリシーで使用されているストレージ プールに新しいサイトまたはストレージ グレードを追加する場合、新しいサイトまたはストレージ グレードのストレージ ノードは自動的には使用されないことに注意してください。  StorageGRID に新しいサイトまたはストレージ グレードを強制的に使用させるには、編集したストレージ プールを保存した後、新しい ILM ポリシーをアクティブ化する必要があります。

.手順
. *ILM* > *ストレージ プール* を選択します。
. 編集するストレージ プールのチェックボックスを選択します。
+
All Storage Nodes ストレージ プール (StorageGRID 11.6 以前) を編集することはできません。

. *編集*を選択します。
. 必要に応じて、ストレージ プール名を変更します。
. 必要に応じて、他のサイトおよびストレージグレードを選択します。
+
ストレージ プールが消去コーディング プロファイルで使用されており、変更によって消去コーディング スキームが無効になる場合は、サイトまたはストレージ グレードを変更することはできません。たとえば、現在、消去コーディング プロファイルで使用されているストレージ プールにサイトが 1 つだけのストレージ グレードが含まれている場合、変更によって消去コーディング スキームが無効になるため、サイトが 2 つあるストレージ グレードを使用することはできません。

+

CAUTION: 既存のストレージ プールにサイトを追加または削除しても、既存の消去エンコードされたデータは移動されません。サイトから既存のデータを移動する場合は、新しいストレージ プールと EC プロファイルを作成して、データを再エンコードする必要があります。

. *保存*を選択します。


.終了後の操作
アクティブな ILM ポリシーで使用されているストレージ プールに新しいサイトまたはストレージ グレードを追加した場合は、新しい ILM ポリシーをアクティブ化して、 StorageGRID が新しいサイトまたはストレージ グレードを使用するように強制します。たとえば、既存の ILM ポリシーを複製し、その複製をアクティブ化します。見るlink:working-with-ilm-rules-and-ilm-policies.html["ILMルールとILMポリシーを操作する"] 。
