---
permalink: ilm/enabling-s3-object-lock-globally.html 
sidebar: sidebar 
keywords: enable s3 object lock, object lock 
summary: S3 テナント アカウントがオブジェクト データを保存するときに規制要件に準拠する必要がある場合は、 StorageGRIDシステム全体に対して S3 オブジェクト ロックを有効にする必要があります。グローバル S3 オブジェクト ロック設定を有効にすると、すべての S3 テナント ユーザーが S3 オブジェクト ロックを使用してバケットとオブジェクトを作成および管理できるようになります。 
---
= S3 オブジェクトロックをグローバルに有効にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 テナント アカウントがオブジェクト データを保存するときに規制要件に準拠する必要がある場合は、 StorageGRIDシステム全体に対して S3 オブジェクト ロックを有効にする必要があります。グローバル S3 オブジェクト ロック設定を有効にすると、すべての S3 テナント ユーザーが S3 オブジェクト ロックを使用してバケットとオブジェクトを作成および管理できるようになります。

.開始する前に
* あなたはlink:../admin/admin-group-permissions.html["ルートアクセス権限"]。
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* S3 オブジェクトロックのワークフローを確認し、考慮事項を理解しました。
* アクティブな ILM ポリシーのデフォルト ルールが準拠していることを確認しました。見るlink:creating-default-ilm-rule.html["デフォルトのILMルールを作成する"]詳細については。


.タスク概要
グリッド管理者は、テナント ユーザーが S3 オブジェクト ロックが有効になっている新しいバケットを作成できるように、グローバル S3 オブジェクト ロック設定を有効にする必要があります。この設定を有効にすると、無効にすることはできません。

グローバル S3 オブジェクトロック設定を有効にした後、既存のテナントのコンプライアンス設定を確認します。この設定を有効にすると、テナントごとの S3 オブジェクト ロック設定は、テナントが作成された時点のStorageGRIDリリースによって異なります。


NOTE: グローバル コンプライアンス設定は非推奨です。以前のバージョンのStorageGRIDを使用してこの設定を有効にした場合、S3 オブジェクト ロック設定は自動的に有効になります。既存の準拠バケットの設定を管理するためにStorageGRID を引き続き使用できますが、新しい準拠バケットを作成することはできません。詳細については、 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetAppナレッジベース: StorageGRID 11.5 でレガシー準拠バケットを管理する方法"^] 。

.手順
. *構成* > *システム* > *S3 オブジェクト ロック* を選択します。
+
S3 オブジェクトロック設定ページが表示されます。

. *S3 オブジェクトロックを有効にする*を選択します。
. *適用*を選択します。
+
確認ダイアログボックスが表示され、S3 オブジェクトロックを有効にした後は無効にすることはできないことが通知されます。

. システム全体に対して S3 オブジェクト ロックを永続的に有効にする場合は、[*OK*] を選択します。
+
*OK*を選択した場合:

+
** アクティブな ILM ポリシーのデフォルトルールが準拠している場合、S3 オブジェクト ロックはグリッド全体で有効になり、無効にすることはできません。
** デフォルトのルールに準拠していない場合は、エラーが表示されます。準拠ルールをデフォルト ルールとして含む新しい ILM ポリシーを作成してアクティブ化する必要があります。「OK」を選択します。次に、新しいポリシーを作成し、シミュレートしてアクティブ化します。見るlink:creating-ilm-policy.html["ILMポリシーを作成する"]手順についてはこちらをご覧ください。



