---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: ストレージ プールを構成して使用し、複数のサイトにデータを分散してデータ損失を防ぎます。複製されたコピーと消去コード化されたコピーには、異なるストレージ プール構成が必要です。 
---
= ストレージプール作成のガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ プールを構成して使用し、複数のサイトにデータを分散してデータ損失を防ぎます。複製されたコピーと消去コード化されたコピーには、異なるストレージ プール構成が必要です。

見るlink:using-multiple-storage-pools-for-cross-site-replication.html["レプリケーションと消失訂正符号を使用したサイト損失保護の有効化の例"] 。



== すべてのストレージプールのガイドライン

* ストレージ プールの構成はできる限りシンプルに保ちます。必要以上にストレージ プールを作成しないでください。
* できるだけ多くのノードでストレージ プールを作成します。各ストレージ プールには 2 つ以上のノードが含まれている必要があります。ノードが不足しているストレージ プールでは、ノードが使用できなくなった場合に ILM バックログが発生する可能性があります。
* 重複する（1 つ以上の同じノードを含む）ストレージ プールの作成や使用は避けてください。ストレージ プールが重複している場合、オブジェクト データの複数のコピーが同じノードに保存される可能性があります。
* 一般に、すべてのストレージ ノード ストレージ プール (StorageGRID 11.6 以前) またはすべてのサイト サイトは使用しないでください。これらの項目は、拡張で追加した新しいサイトを含めるように自動的に更新されますが、これは望ましくない動作である可能性があります。




== 複製コピーに使用するストレージプールのガイドライン

* サイト損失保護を使用するにはlink:what-replication-is.html["複製"]、1つまたは複数のサイト固有のストレージプールを指定します。link:create-ilm-rule-define-placements.html["各ILMルールの配置手順"] 。
+
StorageGRID のインストール中に、サイトごとに 1 つのストレージ プールが自動的に作成されます。

+
各サイトにストレージ プールを使用すると、複製されたオブジェクトのコピーが期待どおりの場所に正確に配置されるようになります (たとえば、サイト損失保護のために各サイトに各オブジェクトのコピーが 1 つずつ配置されます)。

* 拡張でサイトを追加する場合は、新しいサイトのみを含む新しいストレージ プールを作成します。それから、link:working-with-ilm-rules-and-ilm-policies.html#edit-an-ilm-rule["ILMルールを更新する"]新しいサイトにどのオブジェクトを保存するかを制御します。
* コピーの数がストレージ プールの数より少ない場合、システムはコピーを分散してプール間のディスク使用量のバランスをとります。
* ストレージ プールが重複している場合 (同じストレージ ノードが含まれている場合)、オブジェクトのすべてのコピーが 1 つのサイトのみに保存される可能性があります。選択したストレージ プールに同じストレージ ノードが含まれていないことを確認する必要があります。




== 消失訂正コードコピーに使用されるストレージプールのガイドライン

* サイト損失保護を使用するにはlink:what-erasure-coding-is.html["消失訂正符号"]少なくとも 3 つのサイトで構成されるストレージ プールを作成します。ストレージ プールに 2 つのサイトのみが含まれている場合、そのストレージ プールを消去コーディングに使用することはできません。  2 つのサイトを持つストレージ プールでは、消去コーディング スキームは使用できません。
* ストレージプールに含まれるストレージノードとサイトの数によって、link:what-erasure-coding-schemes-are.html["消失訂正符号化方式"]ご利用いただけます。
* 可能であれば、ストレージ プールには、選択した消去コーディング スキームに必要な最小数を超えるストレージ ノードを含める必要があります。たとえば、6+3 消去コーディング方式を使用する場合は、少なくとも 9 つのストレージ ノードが必要です。ただし、サイトごとに少なくとも 1 つの追加のストレージ ノードを用意することをお勧めします。
* ストレージ ノードをサイト間で可能な限り均等に分散します。たとえば、6+3 消去コーディング スキームをサポートするには、3 つのサイトに少なくとも 3 つのストレージ ノードを含むストレージ プールを構成します。
* スループット要件が高く、サイト間のネットワーク遅延が 100 ミリ秒を超える場合は、複数のサイトを含むストレージ プールの使用はお勧めしません。レイテンシが増加すると、TCP ネットワーク スループットの低下により、 StorageGRID がオブジェクト フラグメントを作成、配置、および取得できる速度が大幅に低下します。
+
スループットの低下は、オブジェクトの取り込みと取得の最大達成可能速度に影響します (取り込み動作として「バランス」または「厳密」が選択されている場合)。また、ILM キューのバックログが発生する可能性があります (取り込み動作として「デュアル コミット」が選択されている場合)。見るlink:what-ilm-rule-is.html#ilm-rule-ingest-behavior["ILMルール取り込み動作"] 。

+

NOTE: グリッドにサイトが 1 つしか含まれていない場合は、消去コーディング プロファイルで「すべてのストレージ ノード」ストレージ プール (StorageGRID 11.6 以前) または「すべてのサイト」サイトを使用することはできません。この動作により、2 番目のサイトが追加された場合にプロファイルが無効になることが防止されます。


