---
permalink: ilm/how-object-retention-is-determined.html 
sidebar: sidebar 
keywords: how object retention is determined 
summary: StorageGRID は、グリッド管理者と個々のテナント ユーザーの両方に、オブジェクトを保存する期間を指定するためのオプションを提供します。一般に、テナント ユーザーが提供する保持指示は、グリッド管理者が提供する保持指示よりも優先されます。 
---
= 物体の保持がどのように決定されるか
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID は、グリッド管理者と個々のテナント ユーザーの両方に、オブジェクトを保存する期間を指定するためのオプションを提供します。一般に、テナント ユーザーが提供する保持指示は、グリッド管理者が提供する保持指示よりも優先されます。



== テナントユーザーがオブジェクトの保持を制御する方法

テナント ユーザーは、次の方法を使用して、オブジェクトがStorageGRIDに保存される期間を制御できます。

* グリッドに対してグローバル S3 オブジェクト ロック設定が有効になっている場合、S3 テナント ユーザーは S3 オブジェクト ロックが有効になっているバケットを作成し、各バケットに対して *デフォルトの保持期間* を選択できます。
* グリッドに対してグローバル S3 オブジェクト ロック設定が有効になっている場合、S3 テナント ユーザーは S3 オブジェクト ロックが有効になっているバケットを作成し、S3 REST API を使用して、そのバケットに追加された各オブジェクト バージョンに対して保持期限と法的保留の設定を指定できます。
+
** 法的保留中のオブジェクト バージョンは、どのような方法でも削除できません。
** オブジェクト バージョンの保持期限に達するまで、そのバージョンはどの方法でも削除できません。
** S3 オブジェクトロックが有効になっているバケット内のオブジェクトは、ILM によって「永久に」保持されます。ただし、保持期限に達した後は、クライアントのリクエストまたはバケットのライフサイクルの有効期限によってオブジェクト バージョンが削除される可能性があります。見るlink:managing-objects-with-s3-object-lock.html["S3 オブジェクトロックでオブジェクトを管理する"] 。


* S3 テナント ユーザーは、有効期限アクションを指定するライフサイクル設定をバケットに追加できます。バケットのライフサイクルが存在する場合、クライアントが最初にオブジェクトを削除しない限り、 StorageGRID は有効期限アクションで指定された日付または日数に達するまでオブジェクトを保存します。見るlink:../s3/create-s3-lifecycle-configuration.html["S3ライフサイクル設定を作成する"] 。
* S3 クライアントはオブジェクトの削除リクエストを発行できます。  StorageGRID は、オブジェクトを削除するか保持するかを決定する際に、常に S3 バケットのライフサイクルや ILM よりもクライアントの削除リクエストを優先します。




== グリッド管理者がオブジェクトの保持を制御する方法

グリッド管理者は、次の方法を使用してオブジェクトの保持を制御できます。

* 各テナントの S3 オブジェクトロックの最大保持期間を設定します。次に、テナント ユーザーは各バケットのデフォルトの保持期間を設定できます。最大保持期間は、そのバケットに新しく取り込まれたオブジェクトにも適用されます (オブジェクトの保持期限日)。
* ILM 配置指示を作成して、オブジェクトの保存期間を制御します。オブジェクトが ILM ルールに一致すると、 StorageGRID はILM ルールの最後の期間が経過するまでそれらのオブジェクトを保存します。配置命令に「永久」が指定されている場合、オブジェクトは無期限に保持されます。
* オブジェクトの保持期間を誰が制御するかに関係なく、ILM 設定では、保存されるオブジェクト コピーの種類 (複製または消去コード化) と、コピーの保存場所 (ストレージ ノードまたはクラウド ストレージ プール) を制御します。




== S3 バケットのライフサイクルと ILM の相互作用

S3 バケットのライフサイクルが設定されている場合、ライフサイクル フィルターに一致するオブジェクトの ILM ポリシーは、ライフサイクル有効期限アクションによって上書きされます。その結果、オブジェクトを配置するための ILM 指示が失効した後でも、オブジェクトがグリッド上に保持される可能性があります。



== 物体保持の例

S3 オブジェクトロック、バケットライフサイクル設定、クライアント削除リクエスト、ILM 間の相互作用をよりよく理解するには、次の例を検討してください。



=== 例 1: S3 バケットのライフサイクルでは、ILM よりも長くオブジェクトが保持されます。

ILM:: 2部を1年間（365日間）保管する
バケットのライフサイクル:: オブジェクトは2年（730日）で期限切れになります
結果:: StorageGRID はオブジェクトを 730 日間保存します。  StorageGRID はバケットのライフサイクル設定を使用して、オブジェクトを削除するか保持するかを決定します。



NOTE: バケットのライフサイクルで、オブジェクトを ILM で指定された期間よりも長く保持するように指定されている場合、 StorageGRID は保存するコピーの数とタイプを決定するときに ILM 配置指示を引き続き使用します。この例では、オブジェクトの 2 つのコピーが 366 日目から 730 日目までStorageGRIDに保存され続けます。



=== 例 2: S3 バケットのライフサイクルにより、ILM の前にオブジェクトが期限切れになる

ILM:: 2部を2年間（730日間）保管する
バケットのライフサイクル:: オブジェクトを1年（365日）で期限切れにする
結果:: StorageGRID は365 日後にオブジェクトの両方のコピーを削除します。




=== 例3: クライアントの削除によりバケットのライフサイクルとILMが上書きされる

ILM:: ストレージノードに2つのコピーを「永久に」保存する
バケットのライフサイクル:: オブジェクトは2年（730日）で期限切れになります
クライアント削除リクエスト:: 400日目に発行
結果:: StorageGRID は、クライアントの削除要求に応じて、400 日目にオブジェクトの両方のコピーを削除します。




=== 例4: S3オブジェクトロックがクライアントの削除リクエストを上書きする

S3 オブジェクトロック:: オブジェクト バージョンの保持期限は 2026-03-31 です。法的保留は有効ではありません。
準拠したILMルール:: ストレージノードに2つのコピーを「永久に」保存する
クライアント削除リクエスト:: 2024年3月31日発行
結果:: 保持期限がまだ 2 年先であるため、 StorageGRID はオブジェクト バージョンを削除しません。

