---
permalink: ilm/lifecycle-of-cloud-storage-pool-object.html 
sidebar: sidebar 
keywords: lifecycle of cloud storage pool object 
summary: クラウド ストレージ プールを実装する前に、各タイプのクラウド ストレージ プールに保存されるオブジェクトのライフサイクルを確認してください。 
---
= Cloud Storage Pool オブジェクトのライフサイクル
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウド ストレージ プールを実装する前に、各タイプのクラウド ストレージ プールに保存されるオブジェクトのライフサイクルを確認してください。



== S3: クラウド ストレージ プール オブジェクトのライフサイクル

これらの手順では、S3 クラウド ストレージ プールに保存されているオブジェクトのライフサイクル ステージについて説明します。


NOTE: 「Glacier」は、Glacier ストレージ クラスと Glacier Deep Archive ストレージ クラスの両方を指しますが、1 つの例外があります。Glacier Deep Archive ストレージ クラスは、Expedited 復元層をサポートしていません。一括取得または標準取得のみがサポートされています。


NOTE: Google Cloud Platform (GCP) は、POST Restore 操作を必要とせずに長期ストレージからのオブジェクトの取得をサポートしています。

. * StorageGRIDに保存されたオブジェクト*
+
ライフサイクルを開始するために、クライアント アプリケーションはオブジェクトをStorageGRIDに保存します。

. *オブジェクトはS3クラウドストレージプールに移動されました*
+
** オブジェクトが、配置場所として S3 クラウド ストレージ プールを使用する ILM ルールに一致すると、 StorageGRID はオブジェクトをクラウド ストレージ プールで指定された外部 S3 バケットに移動します。
** オブジェクトが S3 クラウド ストレージ プールに移動されると、オブジェクトが Glacier ストレージに移行されていない限り、クライアント アプリケーションはStorageGRIDからの S3 GetObject リクエストを使用してそのオブジェクトを取得できます。


. *オブジェクトはGlacier（取得不可能な状態）に移行しました*
+
** オプションで、オブジェクトを Glacier ストレージに移行できます。たとえば、外部 S3 バケットはライフサイクル設定を使用して、オブジェクトをすぐに、または数日後に Glacier ストレージに移行する場合があります。
+

NOTE: オブジェクトを移行する場合は、外部 S3 バケットのライフサイクル設定を作成し、Glacier ストレージクラスを実装し、S3 RestoreObject API をサポートするストレージソリューションを使用する必要があります。

** 遷移中、クライアント アプリケーションは S3 HeadObject リクエストを使用してオブジェクトのステータスを監視できます。


. *Glacierストレージから復元されたオブジェクト*
+
オブジェクトが Glacier ストレージに移行されている場合、クライアント アプリケーションは S3 RestoreObject リクエストを発行して、取得可能なコピーを S3 クラウド ストレージ プールに復元できます。リクエストでは、クラウド ストレージ プールでコピーを利用できる日数と、復元操作に使用するデータ アクセス層 (迅速、標準、一括) を指定します。取得可能なコピーの有効期限が切れると、コピーは自動的に取得不可能な状態に戻されます。

+

NOTE: オブジェクトのコピーがStorageGRID内のストレージ ノードにも 1 つ以上存在する場合は、RestoreObject 要求を発行して Glacier からオブジェクトを復元する必要はありません。代わりに、GetObject 要求を使用してローカル コピーを直接取得できます。

. *オブジェクトを取得しました*
+
オブジェクトが復元されると、クライアント アプリケーションは GetObject 要求を発行して、復元されたオブジェクトを取得できます。





== Azure: クラウド ストレージ プール オブジェクトのライフサイクル

これらの手順では、Azure クラウド ストレージ プールに保存されているオブジェクトのライフサイクル ステージについて説明します。

. * StorageGRIDに保存されたオブジェクト*
+
ライフサイクルを開始するために、クライアント アプリケーションはオブジェクトをStorageGRIDに保存します。

. *オブジェクトは Azure クラウド ストレージ プールに移動されました*
+
オブジェクトが、Azure クラウド ストレージ プールを配置場所として使用する ILM ルールに一致すると、 StorageGRID はオブジェクトをクラウド ストレージ プールで指定された外部 Azure Blob ストレージ コンテナーに移動します。

. *オブジェクトはアーカイブ層に移行しました（取得不可能な状態）*
+
オブジェクトを Azure クラウド ストレージ プールに移動する直後、 StorageGRID はオブジェクトを Azure Blob ストレージ アーカイブ層に自動的に移行します。

. *アーカイブ層から復元されたオブジェクト*
+
オブジェクトがアーカイブ層に移行されている場合、クライアント アプリケーションは S3 RestoreObject 要求を発行して、取得可能なコピーを Azure クラウド ストレージ プールに復元できます。

+
StorageGRID はRestoreObject を受信すると、オブジェクトを一時的に Azure Blob Storage のクール層に移行します。  RestoreObject 要求の有効期限に達するとすぐに、 StorageGRID はオブジェクトをアーカイブ層に戻します。

+

NOTE: オブジェクトのコピーがStorageGRID内のストレージ ノードにも 1 つ以上存在する場合は、RestoreObject 要求を発行してアーカイブ アクセス層からオブジェクトを復元する必要はありません。代わりに、GetObject 要求を使用してローカル コピーを直接取得できます。

. *オブジェクトを取得しました*
+
オブジェクトが Azure クラウド ストレージ プールに復元されると、クライアント アプリケーションは GetObject 要求を発行して、復元されたオブジェクトを取得できます。



.関連情報
link:../s3/index.html["S3 REST APIを使用する"]
