---
permalink: ilm/managing-objects-with-s3-object-lock.html 
sidebar: sidebar 
keywords: s3 object lock, manage objects with object lock 
summary: グリッド管理者は、 StorageGRIDシステムに対して S3 オブジェクト ロックを有効にし、準拠した ILM ポリシーを実装して、特定の S3 バケット内のオブジェクトが一定期間削除または上書きされないようにすることができます。 
---
= S3 オブジェクトロックでオブジェクトを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド管理者は、 StorageGRIDシステムに対して S3 オブジェクト ロックを有効にし、準拠した ILM ポリシーを実装して、特定の S3 バケット内のオブジェクトが指定された期間削除または上書きされないようにすることができます。



== S3 オブジェクトロックとは何ですか?

StorageGRID S3 オブジェクト ロック機能は、Amazon Simple Storage Service (Amazon S3) の S3 オブジェクト ロックと同等のオブジェクト保護ソリューションです。

StorageGRIDシステムでグローバル S3 オブジェクト ロック設定が有効になっている場合、S3 テナント アカウントは、S3 オブジェクト ロックが有効になっているかどうかに関係なくバケットを作成できます。バケットで S3 オブジェクトロックが有効になっている場合は、バケットのバージョン管理が必要となり、自動的に有効になります。

*S3 オブジェクト ロックのないバケット* には、保持設定が指定されていないオブジェクトのみを含めることができます。取り込まれたオブジェクトには保持設定はありません。

*S3 オブジェクト ロックが有効なバケット* には、S3 クライアント アプリケーションによって指定された保持設定のあるオブジェクトと、保持設定のないオブジェクトを含めることができます。取り込まれたオブジェクトの中には保持設定を持つものがあります。

*S3 オブジェクト ロックとデフォルトの保持期間が設定されたバケット* には、保持期間設定が指定されたアップロード済みオブジェクトと、保持期間設定のない新しいオブジェクトを含めることができます。保持設定がオブジェクト レベルで構成されていないため、新しいオブジェクトではデフォルト設定が使用されます。

実際には、デフォルトの保持期間が設定されている場合、新しく取り込まれたすべてのオブジェクトに保持設定が行われます。オブジェクト保持設定のない既存のオブジェクトは影響を受けません。



=== 保持モード

StorageGRID S3 オブジェクト ロック機能は、オブジェクトに異なるレベルの保護を適用するための 2 つの保持モードをサポートしています。これらのモードは、Amazon S3 保持モードと同等です。

* コンプライアンスモードの場合:
+
** オブジェクトは、保持期限に達するまで削除できません。
** オブジェクトの保持期限を増やすことはできますが、減らすことはできません。
** オブジェクトの保持期限は、その日付に達するまで削除できません。


* ガバナンス モードの場合:
+
** 特別な権限を持つユーザーは、リクエストでバイパス ヘッダーを使用して、特定の保持設定を変更できます。
** これらのユーザーは、オブジェクト バージョンを、その保持期限に達する前に削除できます。
** これらのユーザーは、オブジェクトの保持期限を増減または削除できます。






=== オブジェクトバージョンの保持設定

S3 オブジェクト ロックを有効にしてバケットを作成した場合、ユーザーは S3 クライアント アプリケーションを使用して、バケットに追加されるオブジェクトごとに次の保持設定をオプションで指定できます。

* *保持モード*: コンプライアンスまたはガバナンスのいずれか。
* *保持期限*: オブジェクト バージョンの保持期限が将来の日付である場合、オブジェクトを取得することはできますが、削除することはできません。
* *法的保留*: オブジェクト バージョンに法的保留を適用すると、そのオブジェクトは直ちにロックされます。たとえば、調査や法的紛争に関連するオブジェクトに対して法的保留を設定する必要がある場合があります。法的保留には有効期限はありませんが、明示的に削除されるまで有効のままになります。法的保留は、保持期限とは無関係です。
+

NOTE: オブジェクトが法的保留中の場合、保持モードに関係なく、誰もそのオブジェクトを削除することはできません。

+
オブジェクト設定の詳細については、link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API を使用して S3 オブジェクトロックを設定する"] 。





=== バケットのデフォルトの保持設定

S3 オブジェクトロックを有効にしてバケットを作成すると、ユーザーはオプションでバケットの次のデフォルト設定を指定できます。

* *デフォルトの保持モード*: コンプライアンスまたはガバナンスのいずれか。
* *デフォルトの保持期間*: このバケットに追加された新しいオブジェクト バージョンを、追加された日から保持する期間。


デフォルトのバケット設定は、独自の保持設定を持たない新しいオブジェクトにのみ適用されます。これらのデフォルト設定を追加または変更しても、既存のバケット オブジェクトは影響を受けません。

見るlink:../tenant/creating-s3-bucket.html["S3バケットを作成する"]そしてlink:../tenant/update-default-retention-settings.html["S3 オブジェクトロックのデフォルト保持を更新"]。



== S3 オブジェクトロックと従来のコンプライアンスの比較

S3 オブジェクト ロックは、以前のStorageGRIDバージョンで利用可能だったコンプライアンス機能に代わるものです。  S3 オブジェクト ロック機能は Amazon S3 の要件に準拠しているため、独自のStorageGRIDコンプライアンス機能は廃止され、現在は「レガシー コンプライアンス」と呼ばれています。


NOTE: グローバル コンプライアンス設定は非推奨です。以前のバージョンのStorageGRIDを使用してこの設定を有効にした場合、S3 オブジェクト ロック設定は自動的に有効になります。既存の準拠バケットの設定を管理するためにStorageGRID を引き続き使用できますが、新しい準拠バケットを作成することはできません。詳細については、 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetAppナレッジベース: StorageGRID 11.5 でレガシー準拠バケットを管理する方法"^] 。

以前のバージョンのStorageGRIDで従来のコンプライアンス機能を使用していた場合は、次の表を参照して、 StorageGRIDの S3 オブジェクト ロック機能との比較を確認してください。

[cols="1a,1a,1a"]
|===
|  | S3 オブジェクトロック | コンプライアンス（レガシー） 


 a| 
この機能はどのようにしてグローバルに有効化されますか?
 a| 
グリッド マネージャーから、*構成* > *システム* > *S3 オブジェクト ロック* を選択します。
 a| 
サポートされなくなりました。



 a| 
バケットに対して機能を有効にするにはどうすればよいでしょうか?
 a| 
ユーザーは、テナント マネージャー、テナント管理 API、または S3 REST API を使用して新しいバケットを作成するときに、S3 オブジェクト ロックを有効にする必要があります。
 a| 
サポートされなくなりました。



 a| 
バケットのバージョン管理はサポートされていますか?
 a| 
○バケットのバージョン管理は必須であり、バケットに対して S3 オブジェクト ロックが有効になっている場合は自動的に有効になります。
 a| 
デスティネーション



 a| 
オブジェクトの保持はどのように設定されますか?
 a| 
ユーザーは、各オブジェクト バージョンに保持期限を設定したり、各バケットにデフォルトの保持期間を設定したりできます。
 a| 
ユーザーはバケット全体の保持期間を設定する必要があります。保持期間はバケット内のすべてのオブジェクトに適用されます。



 a| 
保存期間は変更できますか？
 a| 
* コンプライアンス モードでは、オブジェクト バージョンの保持期限を増やすことはできますが、減らすことはできません。
* ガバナンス モードでは、特別な権限を持つユーザーは、オブジェクトの保持設定を減らしたり、削除したりすることができます。

 a| 
バケットの保持期間は増やすことはできますが、減らすことはできません。



 a| 
法的保留はどこで管理されますか?
 a| 
ユーザーは、バケット内の任意のオブジェクト バージョンに対して法的保留を設定したり、法的保留を解除したりできます。
 a| 
リーガルホールドがバケットに設定され、バケット内のすべてのオブジェクトに影響します。



 a| 
オブジェクトはいつ削除できますか?
 a| 
* コンプライアンス モードでは、オブジェクトが法的保留中でない場合、保持期限に達した後にオブジェクト バージョンを削除できます。
* ガバナンス モードでは、オブジェクトが法的保留中でない場合、特別な権限を持つユーザーは、オブジェクトの保持期限に達する前にそのオブジェクトを削除できます。

 a| 
バケットが法的保留中でない場合、保持期間の終了後にオブジェクトを削除できます。オブジェクトは自動または手動で削除できます。



 a| 
バケットのライフサイクル構成はサポートされていますか?
 a| 
はい
 a| 
いいえ

|===