---
permalink: ilm/manage-ilm-policy-tags.html 
sidebar: sidebar 
keywords: ILM policy tag 
summary: ILM ポリシー タグの詳細を表示したり、タグを編集したり、タグを削除したりできます。 
---
= ILMポリシータグの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM ポリシー タグの詳細を表示したり、タグを編集したり、タグを削除したりできます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["必要なアクセス権限"]。




== ILM ポリシータグの詳細を表示

タグの詳細を表示するには:

. *ILM* > *ポリシー タグ* を選択します。
. 表からポリシーの名前を選択します。タグの詳細ページが表示されます。
. 詳細ページで、割り当てられたポリシーの以前の履歴を表示します。
. ポリシーを選択して表示します。




== ILMポリシータグを編集する


NOTE: タグ名と説明はテナントに表示されます。バケットに割り当てるポリシー タグを選択する際に、テナントが十分な情報に基づいた決定を下せるようにする値を選択します。たとえば、割り当てられたポリシーによって一定期間後にオブジェクトが削除される場合は、説明でその旨を伝えることができます。これらのフィールドには機密情報を含めないでください。

既存のタグの説明を編集するには:

. *ILM* > *ポリシー タグ* を選択します。
. タグのチェックボックスを選択し、[編集] を選択します。
+
または、タグの名前を選択します。タグの詳細ページが表示され、そのページで*編集*を選択できます。

. 必要に応じてタグの説明を変更します
. *保存*を選択します。




== ILMポリシータグを削除する

ポリシータグを削除すると、そのタグが割り当てられているすべてのバケットにデフォルトポリシーが適用されます。

タグを削除するには:

. *ILM* > *ポリシー タグ* を選択します。
. タグのチェックボックスを選択し、[削除] を選択します。確認ダイアログボックスが表示されます。
+
または、タグの名前を選択します。タグの詳細ページが表示され、そのページで [削除] を選択できます。

. タグを削除するには*はい*を選択してください。

