---
permalink: ilm/removing-cloud-storage-pool.html 
sidebar: sidebar 
keywords: remove cloud storage pool 
summary: ILM ルールで使用されておらず、オブジェクト データが含まれていない場合は、クラウド ストレージ プールを削除できます。 
---
= クラウドストレージプールを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM ルールで使用されておらず、オブジェクト データが含まれていない場合は、クラウド ストレージ プールを削除できます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["必要なアクセス権限"]。




== 必要に応じてILMを使用してオブジェクトデータを移動します

削除するクラウド ストレージ プールにオブジェクト データが含まれている場合は、ILM を使用してデータを別の場所に移動する必要があります。たとえば、データをグリッド上のストレージ ノードまたは別のクラウド ストレージ プールに移動できます。

.手順
. *ILM* > *ストレージ プール* > *クラウド ストレージ プール* を選択します。
. 表の ILM 使用状況列を確認して、クラウド ストレージ プールを削除できるかどうかを判断します。
+
ILM ルールまたは消去コーディング プロファイルで使用されているクラウド ストレージ プールを削除することはできません。

. クラウド ストレージ プールが使用されている場合は、*_クラウド ストレージ プール名_* > *ILM 使用状況* を選択します。
. link:working-with-ilm-rules-and-ilm-policies.html["各ILMルールを複製する"]削除する Cloud Storage プールに現在オブジェクトを配置しているもの。
. 複製した各ルールによって管理される既存のオブジェクトを移動する場所を決定します。
+
1 つ以上のストレージ プール、または異なるクラウド ストレージ プールを使用できます。

. 複製した各ルールを編集します。
+
ILM ルールの作成ウィザードのステップ 2 では、*コピー先* フィールドから新しい場所を選択します。

. link:creating-ilm-policy.html["新しいILMポリシーを作成する"]そして、古いルールをそれぞれ複製したルールに置き換えます。
. 新しいポリシーを有効にします。
. ILM がクラウド ストレージ プールからオブジェクトを削除し、新しい場所に配置してくれるまで待ちます。




== クラウドストレージプールの削除

クラウド ストレージ プールが空で、どの ILM ルールでも使用されていない場合は、削除できます。

.開始する前に
* プールを使用した可能性がある ILM ルールをすべて削除しました。
* S3 バケットまたは Azure コンテナーにオブジェクトが含まれていないことを確認しました。
+
オブジェクトが含まれているクラウド ストレージ プールを削除しようとすると、エラーが発生します。見るlink:troubleshooting-cloud-storage-pools.html["クラウド ストレージ プールのトラブルシューティング"] 。

+

NOTE: クラウド ストレージ プールを作成すると、 StorageGRID はバケットまたはコンテナにマーカー ファイルを書き込み、それをクラウド ストレージ プールとして識別します。このファイルは削除しないでください。 `x-ntap-sgws-cloud-pool-uuid` 。



.手順
. *ILM* > *ストレージ プール* > *クラウド ストレージ プール* を選択します。
. ILM 使用状況列にクラウド ストレージ プールが使用されていないことが示されている場合は、チェックボックスをオンにします。
. *アクション* > *削除*を選択します。
. 「OK」を選択します。

