---
permalink: ilm/requirements-for-s3-object-lock.html 
sidebar: sidebar 
keywords: requirements, s3 object lock, compliant ilm rule, compliant ilm policy 
summary: グローバル S3 オブジェクト ロック設定を有効にするための要件、準拠した ILM ルールと ILM ポリシーを作成するための要件、および S3 オブジェクト ロックを使用するバケットとオブジェクトにStorageGRID が課す制限を確認する必要があります。 
---
= S3 オブジェクトロックの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グローバル S3 オブジェクト ロック設定を有効にするための要件、準拠した ILM ルールと ILM ポリシーを作成するための要件、および S3 オブジェクト ロックを使用するバケットとオブジェクトにStorageGRID が課す制限を確認する必要があります。



== グローバル S3 オブジェクトロック設定を使用するための要件

* S3 テナントが S3 オブジェクト ロックを有効にしたバケットを作成するには、グリッド マネージャーまたはグリッド管理 API を使用して、グローバル S3 オブジェクト ロック設定を有効にする必要があります。
* グローバル S3 オブジェクト ロック設定を有効にすると、すべての S3 テナント アカウントが S3 オブジェクト ロックが有効になっているバケットを作成できるようになります。
* グローバル S3 オブジェクトロック設定を有効にした後は、その設定を無効にすることはできません。
* すべてのアクティブな ILM ポリシーのデフォルト ルールが _準拠_ していない限り (つまり、デフォルト ルールは S3 オブジェクト ロックが有効になっているバケットの要件に準拠している必要があります)、グローバル S3 オブジェクト ロックを有効にすることはできません。
* グローバル S3 オブジェクトロック設定が有効になっている場合、ポリシー内のデフォルトルールが準拠していない限り、新しい ILM ポリシーを作成したり、既存の ILM ポリシーをアクティブ化したりすることはできません。グローバル S3 オブジェクト ロック設定を有効にすると、ILM ルールと ILM ポリシーのページに、準拠している ILM ルールが表示されます。




== 準拠したILMルールの要件

グローバル S3 オブジェクトロック設定を有効にする場合は、すべてのアクティブな ILM ポリシーのデフォルトルールが準拠していることを確認する必要があります。準拠ルールは、S3 オブジェクト ロックが有効になっているバケットと、レガシー コンプライアンスが有効になっている既存のバケットの両方の要件を満たします。

* 少なくとも 2 つの複製されたオブジェクトのコピー、または 1 つの消去コード化されたコピーを作成する必要があります。
* これらのコピーは、配置指示の各行の有効期間中、ストレージ ノード上に存在している必要があります。
* オブジェクトのコピーはクラウド ストレージ プールに保存できません。
* 配置手順の少なくとも 1 行は、*取り込み時間* を参照時間として使用して、0 日目から始まる必要があります。
* 配置指示の少なくとも 1 行は「forever」にする必要があります。




== ILMポリシーの要件

グローバル S3 オブジェクト ロック設定が有効になっている場合、アクティブおよび非アクティブな ILM ポリシーには、準拠ルールと非準拠ルールの両方を含めることができます。

* アクティブまたは非アクティブな ILM ポリシーのデフォルト ルールは準拠している必要があります。
* 非準拠ルールは、S3 オブジェクト ロックが有効になっていないバケット内のオブジェクト、または従来のコンプライアンス機能が有効になっていないバケット内のオブジェクトにのみ適用されます。
* コンプライアンス ルールは任意のバケット内のオブジェクトに適用できます。バケットに対して S3 オブジェクト ロックまたはレガシー コンプライアンスを有効にする必要はありません。


link:example-7-compliant-ilm-policy-for-s3-object-lock.html["S3 オブジェクトロックに準拠した ILM ポリシーの例"]



== S3 オブジェクトロックが有効になっているバケットの要件

* StorageGRIDシステムでグローバル S3 オブジェクト ロック設定が有効になっている場合は、テナント マネージャ、テナント管理 API、または S3 REST API を使用して、S3 オブジェクト ロックが有効になっているバケットを作成できます。
* S3 オブジェクトロックを使用する予定の場合は、バケットを作成するときに S3 オブジェクトロックを有効にする必要があります。既存のバケットに対して S3 オブジェクトロックを有効にすることはできません。
* バケットに対して S3 オブジェクト ロックが有効になっている場合、 StorageGRID はそのバケットのバージョン管理を自動的に有効にします。  S3 オブジェクトロックを無効にしたり、バケットのバージョン管理を一時停止したりすることはできません。
* オプションで、テナント マネージャー、テナント管理 API、または S3 REST API を使用して、各バケットのデフォルトの保持モードと保持期間を指定できます。バケットのデフォルトの保持設定は、バケットに追加された、独自の保持設定を持たない新しいオブジェクトにのみ適用されます。アップロード時に各オブジェクト バージョンの保持モードと保持期限を指定することにより、これらのデフォルト設定を上書きできます。
* バケットのライフサイクル設定は、S3 オブジェクト ロックが有効になっているバケットでサポートされます。
* S3 オブジェクト ロックが有効になっているバケットでは、CloudMirror レプリケーションはサポートされません。




== S3 オブジェクトロックが有効になっているバケット内のオブジェクトの要件

* オブジェクト バージョンを保護するには、バケットのデフォルトの保持設定を指定するか、オブジェクト バージョンごとに保持設定を指定できます。オブジェクト レベルの保持設定は、S3 クライアント アプリケーションまたは S3 REST API を使用して指定できます。
* 保持設定は個々のオブジェクト バージョンに適用されます。オブジェクト バージョンには、保持期限設定と法的保留設定の両方が含まれる場合もあれば、どちらか一方だけが含まれる場合もあり、どちらも含まれない場合もあります。オブジェクトに対して保持期限または法的保留設定を指定すると、リクエストで指定されたバージョンのみが保護されます。オブジェクトの以前のバージョンはロックされたまま、オブジェクトの新しいバージョンを作成できます。




== S3 オブジェクトロックが有効になっているバケット内のオブジェクトのライフサイクル

S3 オブジェクトロックが有効になっているバケットに保存された各オブジェクトは、以下の段階を経ます。

. *オブジェクトの取り込み*
+
S3 オブジェクトロックが有効になっているバケットにオブジェクトバージョンが追加されると、保持設定が次のように適用されます。

+
** オブジェクトに保持設定が指定されている場合は、オブジェクト レベルの設定が適用されます。デフォルトのバケット設定はすべて無視されます。
** オブジェクトに保持設定が指定されていない場合は、デフォルトのバケット設定（存在する場合）が適用されます。
** オブジェクトまたはバケットに保持設定が指定されていない場合、オブジェクトは S3 オブジェクト ロックによって保護されません。


+
保持設定が適用されると、オブジェクトと S3 ユーザー定義メタデータの両方が保護されます。

. *オブジェクトの保持と削除*
+
保護された各オブジェクトの複数のコピーは、指定された保持期間にわたってStorageGRIDによって保存されます。オブジェクト コピーの正確な数とタイプ、および保存場所は、アクティブな ILM ポリシーの準拠ルールによって決まります。保護されたオブジェクトを、その保持期限に達する前に削除できるかどうかは、その保持モードによって異なります。

+
** オブジェクトが法的保留中の場合、保持モードに関係なく、誰もそのオブジェクトを削除することはできません。




.関連情報
* link:../tenant/creating-s3-bucket.html["S3バケットを作成する"]
* link:../tenant/update-default-retention-settings.html["S3 オブジェクトロックのデフォルト保持を更新"]
* link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API を使用して S3 オブジェクトロックを設定する"]
* link:example-7-compliant-ilm-policy-for-s3-object-lock.html["例7: S3オブジェクトロックの準拠ILMポリシー"]

