---
permalink: ilm/troubleshooting-cloud-storage-pools.html 
sidebar: sidebar 
keywords: cloud storage pool, troubleshoot 
summary: クラウド ストレージ プールの作成、編集、または削除時に発生する可能性のあるエラーを解決するには、次のトラブルシューティング手順を使用します。 
---
= クラウド ストレージ プールのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウド ストレージ プールの作成、編集、または削除時に発生する可能性のあるエラーを解決するには、次のトラブルシューティング手順を使用します。



== エラーが発生したかどうかを確認する

StorageGRIDは、既知のオブジェクトを読み取り、すべてのクラウドストレージプールの簡単なヘルスチェックを実行します。 `x-ntap-sgws-cloud-pool-uuid`クラウド ストレージ プールにアクセスでき、正しく機能していることを確認します。 StorageGRID はエンドポイントでエラーを検出すると、各ストレージ ノードから 1 分ごとにヘルス チェックを実行します。エラーが解決されると、ヘルスチェックは停止します。ヘルスチェックで問題が検出されると、「ストレージ プール」ページの「クラウド ストレージ プール」テーブルの「最後のエラー」列にメッセージが表示されます。

表には、各クラウド ストレージ プールで検出された最新のエラーと、そのエラーが発生した時間が表示されます。

さらに、ヘルスチェックで過去 5 分以内に 1 つ以上の新しい Cloud Storage Pool エラーが発生したことが検出された場合、*Cloud Storage Pool 接続エラー* アラートがトリガーされます。このアラートの電子メール通知を受信した場合は、[ストレージ プール] ページ ([ILM] > [ストレージ プール] を選択) に移動し、[最後のエラー] 列のエラー メッセージを確認して、以下のトラブルシューティング ガイドラインを参照してください。



== エラーが解決されたか確認する

根本的な問題を解決したら、エラーが解決されたかどうかを判断できます。クラウド ストレージ プール ページでエンドポイントを選択し、*エラーをクリア*を選択します。確認メッセージは、 StorageGRIDがクラウド ストレージ プールのエラーをクリアしたことを示します。

根本的な問題が解決された場合、エラー メッセージは表示されなくなります。ただし、根本的な問題が修正されていない場合 (または別のエラーが発生した場合)、数分以内に [最後のエラー] 列にエラー メッセージが表示されます。



== エラー: ヘルスチェックに失敗しました。エンドポイントからのエラー

クラウド ストレージ プールにこのバケットの使用を開始した後、Amazon S3 バケットに対してデフォルトの保持期間で S3 オブジェクト ロックを有効にすると、このエラーが発生する可能性があります。このエラーは、PUT操作に次のようなペイロードチェックサム値を持つHTTPヘッダーがない場合に発生します。 `Content-MD5` 。このヘッダー値は、S3 オブジェクトロックが有効になっているバケットへの PUT 操作に AWS によって要求されます。

この問題を修正するには、以下の手順に従ってください。link:editing-cloud-storage-pool.html["クラウドストレージプールを編集する"]何も変更せずに。このアクションは、クラウド ストレージ プールのエンドポイント構成の S3 オブジェクト ロック フラグを自動的に検出して更新するクラウド ストレージ プール構成の検証をトリガーします。



== エラー: このクラウド ストレージ プールには予期しないコンテンツが含まれています

クラウド ストレージ プールを作成、編集、または削除しようとしたときに、このエラーが発生する可能性があります。このエラーは、バケットまたはコンテナに `x-ntap-sgws-cloud-pool-uuid`マーカー ファイルですが、そのファイルには、期待される UUID を持つメタデータ フィールドがありません。

通常、このエラーは、新しいクラウド ストレージ プールを作成し、 StorageGRIDの別のインスタンスがすでに同じクラウド ストレージ プールを使用している場合にのみ表示されます。

問題を修正するには、次のいずれかの手順を試してください。

* 新しいクラウドストレージプールを構成していて、バケットに `x-ntap-sgws-cloud-pool-uuid`次の例のようなファイルと追加のオブジェクト キーがある場合は、新しいバケットを作成し、代わりにこの新しいバケットを使用します。
+
追加のオブジェクト キーの例: `my-bucket.3E64CF2C-B74D-4B7D-AFE7-AD28BC18B2F6.1727326606730410`

* もし `x-ntap-sgws-cloud-pool-uuid`ファイルがバケット内の唯一のオブジェクトである場合は、このファイルを削除します。


これらの手順がシナリオに当てはまらない場合は、サポートにお問い合わせください。



== エラー: クラウド ストレージ プールを作成または更新できませんでした。エンドポイントからのエラー

次の状況でこのエラーが発生する可能性があります。

* クラウド ストレージ プールを作成または編集しようとしたとき。
* 新しいクラウド ストレージ プールの構成中に、S3 オブジェクト ロックでサポートされていないプラットフォーム、認証、またはプロトコルの組み合わせを選択した場合。見るlink:../ilm/considerations-for-cloud-storage-pools.html["クラウドストレージプールに関する考慮事項"] 。


このエラーは、接続または構成の問題により、 StorageGRID がクラウド ストレージ プールに書き込むことができないことを示します。

問題を修正するには、エンドポイントからのエラー メッセージを確認してください。

* エラーメッセージに `Get _url_: EOF`Cloud Storage Pool に使用されるサービス エンドポイントが、HTTPS を必要とするコンテナまたはバケットに対して HTTP を使用していないことを確認します。
* エラーメッセージに `Get _url_: net/http: request canceled while waiting for connection`ネットワーク構成により、ストレージ ノードが Cloud Storage Pool に使用されるサービス エンドポイントにアクセスできることを確認します。
* エラーの原因がサポートされていないプラットフォーム、認証、またはプロトコルである場合は、S3 オブジェクト ロックを使用してサポートされている構成に変更し、新しいクラウド ストレージ プールを再度保存してみてください。
* その他のすべてのエンドポイント エラー メッセージについては、次のいずれかまたは複数を試してください。
+
** クラウド ストレージ プールに入力したのと同じ名前で外部コンテナまたはバケットを作成し、新しいクラウド ストレージ プールを再度保存してみます。
** クラウド ストレージ プールに指定したコンテナまたはバケット名を修正し、新しいクラウド ストレージ プールを再度保存してください。






== エラー: CA証明書の解析に失敗しました

クラウド ストレージ プールを作成または編集しようとしたときに、このエラーが発生する可能性があります。このエラーは、 StorageGRID がクラウド ストレージ プールの構成時に入力した証明書を解析できなかった場合に発生します。

この問題を修正するには、提供した CA 証明書に問題がないか確認してください。



== エラー: このIDのクラウドストレージプールが見つかりませんでした

クラウド ストレージ プールを編集または削除しようとしたときに、このエラーが発生する可能性があります。このエラーは、エンドポイントが 404 応答を返した場合に発生し、次のいずれかを意味します。

* Cloud Storage Pool に使用される認証情報には、バケットの読み取り権限がありません。
* クラウドストレージプールに使用されるバケットには、 `x-ntap-sgws-cloud-pool-uuid`マーカーファイル。


問題を修正するには、以下の手順を 1 つ以上試してください。

* 設定されたアクセス キーに関連付けられたユーザーに必要な権限があることを確認します。
* 必要な権限を持つ認証情報を使用してクラウド ストレージ プールを編集します。
* 権限が正しい場合は、サポートにお問い合わせください。




== エラー: クラウド ストレージ プールの内容を確認できませんでした。エンドポイントからのエラー

クラウド ストレージ プールを削除しようとすると、このエラーが発生する可能性があります。このエラーは、何らかの接続または構成の問題により、 StorageGRID がCloud Storage Pool バケットの内容を読み取ることができないことを示しています。

問題を修正するには、エンドポイントからのエラー メッセージを確認してください。



== エラー: オブジェクトはすでにこのバケットに配置されています

クラウド ストレージ プールを削除しようとすると、このエラーが発生する可能性があります。  ILM によって移動されたデータ、クラウド ストレージ プールを構成する前にバケット内にあったデータ、またはクラウド ストレージ プールの作成後に他のソースによってバケット内に置かれたデータが含まれている場合、クラウド ストレージ プールを削除することはできません。

問題を修正するには、以下の手順を 1 つ以上試してください。

* 「クラウド ストレージ プール オブジェクトのライフサイクル」の手順に従って、オブジェクトをStorageGRIDに戻します。
* 残りのオブジェクトが ILM によってクラウド ストレージ プールに配置されていないことが確実な場合は、バケットからオブジェクトを手動で削除します。
+

NOTE: ILM によってクラウド ストレージ プールに配置された可能性のあるオブジェクトを手動で削除しないでください。後でStorageGRIDから手動で削除したオブジェクトにアクセスしようとすると、削除されたオブジェクトは見つかりません。





== エラー: クラウド ストレージ プールにアクセスしようとしたときにプロキシが外部エラーが発生しました

ストレージノードと、クラウド ストレージ プールに使用される外部 S3 エンドポイントとの間に非透過ストレージ プロキシを構成している場合、このエラーが発生する可能性があります。このエラーは、外部プロキシ サーバーが Cloud Storage Pool エンドポイントに到達できない場合に発生します。たとえば、DNS サーバーがホスト名を解決できないか、外部ネットワークの問題が発生している可能性があります。

問題を修正するには、以下の手順を 1 つ以上試してください。

* クラウド ストレージ プールの設定を確認します (*ILM* > *ストレージ プール*)。
* ストレージ プロキシ サーバーのネットワーク構成を確認します。




== エラー: X.509証明書の有効期限が切れています

クラウド ストレージ プールを削除しようとすると、このエラーが発生する可能性があります。このエラーは、正しい外部クラウド ストレージ プールが検証され、クラウド ストレージ プールの構成が削除される前に外部プールが空であることを確認するために認証で X.509 証明書が必要な場合に発生します。

問題を修正するには、次の手順を試してください。

* クラウド ストレージ プールへの認証用に構成された証明書を更新します。
* このクラウド ストレージ プールの証明書の有効期限アラートが解決されていることを確認してください。


.関連情報
link:lifecycle-of-cloud-storage-pool-object.html["Cloud Storage Pool オブジェクトのライフサイクル"]
