---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: ILM ルールでは、最終アクセス時刻を参照時刻として使用できます。たとえば、過去 3 か月間に表示されたオブジェクトをローカル ストレージ ノードに残し、それほど最近表示されていないオブジェクトをオフサイトの場所に移動することができます。特定の日付に最後にアクセスされたオブジェクトにのみ ILM ルールを適用する場合は、最終アクセス時刻を詳細フィルターとして使用することもできます。 
---
= ILMルールで最終アクセス時刻を使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM ルールでは、最終アクセス時刻を参照時刻として使用できます。たとえば、過去 3 か月間に表示されたオブジェクトをローカル ストレージ ノードに残し、それほど最近表示されていないオブジェクトをオフサイトの場所に移動することができます。特定の日付に最後にアクセスされたオブジェクトにのみ ILM ルールを適用する場合は、最終アクセス時刻を詳細フィルターとして使用することもできます。

.タスク概要
ILM ルールで最終アクセス時刻を使用する前に、次の考慮事項を確認してください。

* 最終アクセス時刻を参照時刻として使用する場合、オブジェクトの最終アクセス時刻を変更しても ILM 評価が直ちにトリガーされないことに注意してください。代わりに、バックグラウンド ILM がオブジェクトを評価するときに、オブジェクトの配置が評価され、必要に応じてオブジェクトが移動されます。オブジェクトにアクセスしてから 2 週間以上かかる場合があります。
+
最終アクセス時間に基づいて ILM ルールを作成するときは、この遅延を考慮し、短い期間 (1 か月未満) を使用する配置を避けてください。

* 最終アクセス時刻を詳細フィルターまたは参照時刻として使用する場合は、S3 バケットの最終アクセス時刻の更新を有効にする必要があります。使用することができますlink:../tenant/enabling-or-disabling-last-access-time-updates.html["Tenant Manager"]またはlink:../s3/put-bucket-last-access-time-request.html["テナント管理API"]。
+

NOTE: S3 バケットの最終アクセス時間の更新はデフォルトで無効になっています。

+

NOTE: 最終アクセス時刻の更新を有効にすると、特に小さなオブジェクトを含むシステムではパフォーマンスが低下する可能性があることに注意してください。オブジェクトが取得されるたびに、 StorageGRID は新しいタイムスタンプでオブジェクトを更新する必要があるため、パフォーマンスに影響が発生します。



次の表は、さまざまな種類のリクエストに対して、バケット内のすべてのオブジェクトの最終アクセス時間が更新されるかどうかをまとめたものです。

[cols="1a,1a,1a"]
|===
| リクエストの種類 | 最終アクセス時間の更新が無効になっている場合に最終アクセス時間を更新するかどうか | 最終アクセス時間の更新が有効になっている場合に最終アクセス時間を更新するかどうか 


 a| 
オブジェクト、そのアクセス制御リスト、またはそのメタデータの取得要求
 a| 
いいえ
 a| 
はい



 a| 
オブジェクトのメタデータの更新リクエスト
 a| 
はい
 a| 
はい



 a| 
あるバケットから別のバケットにオブジェクトをコピーするリクエスト
 a| 
* いいえ、ソースコピーの場合
* はい、宛先コピー用

 a| 
* はい、ソースコピーの場合
* はい、宛先コピー用




 a| 
マルチパートアップロードの完了リクエスト
 a| 
はい、組み立てられたオブジェクトの場合
 a| 
はい、組み立てられたオブジェクトの場合

|===