---
permalink: ilm/viewing-storage-pool-details.html 
sidebar: sidebar 
keywords: storage pool, view details 
summary: ストレージ プールの詳細を表示して、ストレージ プールが使用されている場所を特定し、含まれるノードとストレージ グレードを確認できます。 
---
= ストレージプールの詳細を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ プールの詳細を表示して、ストレージ プールが使用されている場所を特定し、含まれるノードとストレージ グレードを確認できます。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたが持っているlink:../admin/admin-group-permissions.html["特定のアクセス権限"]。


.手順
. *ILM* > *ストレージ プール* を選択します。
+
ストレージ プール テーブルには、ストレージ ノードを含む各ストレージ プールの次の情報が含まれます。

+
** *名前*: ストレージ プールの一意の表示名。
** *ノード数*: ストレージ プール内のノードの数。
** *ストレージ使用量*: このノード上のオブジェクト データに使用されている使用可能な合計スペースの割合。この値にはオブジェクト メタデータは含まれません。
** *合計容量*: ストレージ プールのサイズ。これは、ストレージ プール内のすべてのノードのオブジェクト データに使用可能なスペースの合計量に相当します。
** *ILM の使用状況*: ストレージ プールの現在の使用状況。ストレージ プールは未使用の場合もあれば、1 つ以上の ILM ルール、消去コーディング プロファイル、またはその両方で使用されている場合もあります。


. 特定のストレージ プールの詳細を表示するには、その名前を選択します。
+
ストレージ プールの詳細ページが表示されます。

. ストレージ プールに含まれるストレージ ノードの詳細については、「*ノード*」タブを参照してください。
+
表には各ノードに関する次の情報が含まれています。

+
** ノード名
** サイト名
** 保管グレード
** ストレージ使用量: ストレージ ノードで使用されているオブジェクト データに使用可能な合計スペースの割合。
+

NOTE: 同じストレージ使用量 (%) の値は、各ストレージ ノードの「使用済みストレージ - オブジェクト データ」チャートにも表示されます (*NODES* > *_Storage Node_* > *Storage* を選択)。



. *ILM 使用状況* タブを表示して、ストレージ プールが現在 ILM ルールまたは消去コーディング プロファイルで使用されているかどうかを確認します。
. オプションで、*ILM ルール ページ* に移動して、ストレージ プールを使用するルールを確認し、管理します。
+
参照link:working-with-ilm-rules-and-ilm-policies.html["ILMルールの操作手順"]。


