---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure-coding scheme 
summary: 消失訂正符号化方式は、各オブジェクトに対して作成されるデータ フラグメントの数とパリティ フラグメントの数を制御します。 
---
= 消失訂正符号化方式とは何ですか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
消失訂正符号化方式は、各オブジェクトに対して作成されるデータ フラグメントの数とパリティ フラグメントの数を制御します。

ILM ルールを作成または編集するときに、使用可能な消去コーディング スキームを選択します。  StorageGRID は、使用する予定のストレージ プールを構成するストレージ ノードとサイトの数に基づいて、自動的に消去コーディング スキームを作成します。



== データ保護

StorageGRIDシステムは、リード・ソロモン消去符号化アルゴリズムを使用します。このアルゴリズムはオブジェクトを `k`データの断片化と計算 `m`パリティフラグメント。

その `k + m = n`破片が広がっている `n`ストレージ ノードは次のようにデータ保護を提供します。

* オブジェクトを回収または修復するには、 `k`断片が必要です。
* 物体は最大 `m`失われた、または破損したフラグメント。値が高いほど `m`、障害許容度が高くなります。


最高のデータ保護は、ストレージ プール内で最も高いノードまたはボリューム障害許容度を備えた消去コーディング スキームによって提供されます。



== ストレージオーバーヘッド

消失訂正符号化方式のストレージオーバーヘッドは、パリティフラグメントの数を(`m`）データフラグメントの数(`k`）。ストレージ オーバーヘッドを使用して、各消去コード化オブジェクトに必要なディスク容量を計算できます。

`_disk space_ = _object size_ + (_object size_ * _storage overhead_)`

たとえば、4+2 スキーム (ストレージ オーバーヘッドが 50%) を使用して 10 MB のオブジェクトを保存する場合、オブジェクトは 15 MB のグリッド ストレージを消費します。同じ 10 MB のオブジェクトを 6+2 スキーム (ストレージ オーバーヘッドが 33%) を使用して保存すると、オブジェクトは約 13.3 MB を消費します。

合計値が最小となる消失訂正符号化方式を選択する。 `k+m`あなたのニーズを満たすもの。フラグメントの数が少ない消失訂正符号化方式は、次の理由により計算効率が高くなります。

* オブジェクトごとに作成および配布（または取得）されるフラグメントの数が少なくなります
* フラグメントサイズが大きいため、パフォーマンスが向上します
* より少ないノードを追加する必要があるlink:../expand/index.html["より多くのストレージが必要な場合の拡張"]




== ストレージプールのガイドライン

消去コード化されたコピーを作成するルールに使用するストレージ プールを選択するときは、ストレージ プールに関する次のガイドラインに従います。

* ストレージ プールには、3 つ以上のサイト、または 1 つのサイトが含まれている必要があります。
+

NOTE: ストレージ プールに 2 つのサイトが含まれている場合、消去コーディングは使用できません。

+
** <<3つ以上のサイトを含むストレージプールの消失訂正符号化方式,3つ以上のサイトを含むストレージプールの消失訂正符号化方式>>
** <<ワンサイトストレージプールの消失訂正符号化方式,ワンサイトストレージプールの消失訂正符号化方式>>


* すべてのサイト サイトを含むストレージ プールを使用しないでください。
* ストレージプールには少なくとも `_k+m_ +1`オブジェクト データを保存できるストレージ ノード。
+

NOTE: ストレージ ノードは、インストール時に、オブジェクト データではなくオブジェクト メタデータのみが含まれるように構成できます。詳細については、以下を参照してください。 link:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードの種類"] 。

+
必要なストレージノードの最小数は `k+m`。ただし、少なくとも 1 つの追加のストレージ ノードがあれば、必要なストレージ ノードが一時的に利用できなくなった場合に、取り込みの失敗や ILM バックログを防ぐことができます。





== 3つ以上のサイトを含むストレージプールの消失訂正符号化方式

次の表は、3 つ以上のサイトを含むストレージ プールに対してStorageGRIDが現在サポートしている消去コーディング スキームを示しています。これらのスキームはすべて、サイト損失保護を提供します。  1 つのサイトが失われても、オブジェクトには引き続きアクセスできます。

サイトロス保護を提供する消失訂正符号化方式の場合、ストレージプール内のストレージノードの推奨数は `_k+m_ +1`各サイトには少なくとも 3 つのストレージ ノードが必要であるためです。

[cols="1a,1a,1a,1a,1a,1a"]
|===
| 消失訂正符号化方式（_k+m_） | 展開サイトの最小数 | 各サイトのストレージノードの推奨数 | 推奨されるストレージノードの合計数 | サイト損失保護? | ストレージオーバーヘッド 


 a| 
4+2
 a| 
3
 a| 
3
 a| 
9
 a| 
はい
 a| 
50%



 a| 
6+2
 a| 
4
 a| 
3
 a| 
12
 a| 
はい
 a| 
33%



 a| 
8+2
 a| 
5
 a| 
3
 a| 
15
 a| 
はい
 a| 
25%



 a| 
6+3
 a| 
3
 a| 
4
 a| 
12
 a| 
はい
 a| 
50%



 a| 
9+3
 a| 
4
 a| 
4
 a| 
16
 a| 
はい
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
3
 a| 
9
 a| 
はい
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
3
 a| 
15
 a| 
はい
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
3
 a| 
21
 a| 
はい
 a| 
17%



 a| 
7+5
 a| 
3
 a| 
5
 a| 
15
 a| 
はい
 a| 
71%

|===

NOTE: StorageGRID、サイトごとに少なくとも 3 つのストレージ ノードが必要です。 7+5 スキームを使用するには、各サイトに少なくとも 4 つのストレージ ノードが必要です。サイトごとに 5 つのストレージ ノードを使用することをお勧めします。

サイト保護を提供する消去コーディング方式を選択するときは、次の要素の相対的な重要性のバランスをとってください。

* *フラグメントの数*: フラグメントの合計数が少ないほど、パフォーマンスと拡張の柔軟性は一般的に向上します。
* *フォールトトレランス*: フォールトトレランスはパリティセグメントを増やすことで向上します（つまり、 `m`価値が高くなります。
* *ネットワークトラフィック*: 障害からの回復時に、フラグメント数が多い（つまり、 `k+m` ) は、より多くのネットワーク トラフィックを生成します。
* *ストレージ オーバーヘッド*: オーバーヘッドが大きいスキームでは、オブジェクトごとにより多くのストレージ スペースが必要になります。


たとえば、4+2 方式と 6+3 方式 (どちらもストレージ オーバーヘッドが 50%) のどちらかを選択する場合、追加のフォールト トレランスが必要な場合は 6+3 方式を選択します。ネットワーク リソースが制限されている場合は、4+2 スキームを選択します。他のすべての要因が等しい場合は、フラグメントの合計数が少ない 4+2 を選択します。


NOTE: どちらの方式を使用するか不明な場合は、4+2 または 6+3 を選択するか、テクニカル サポートにお問い合わせください。



== ワンサイトストレージプールの消失訂正符号化方式

1 サイトのストレージ プールは、サイトに十分なストレージ ノードがある場合、3 つ以上のサイトに対して定義されているすべての消去コーディング スキームをサポートします。

必要なストレージノードの最小数は `k+m`、しかし、ストレージプールは `k+m +1`ストレージノードが推奨されます。たとえば、2+1 イレイジャー コーディング スキームでは、少なくとも 3 つのストレージ ノードを持つストレージ プールが必要ですが、4 つのストレージ ノードが推奨されます。

[cols="1a,1a,1a,1a"]
|===
| 消失訂正符号化方式（_k+m_） | ストレージノードの最小数 | 推奨ストレージノード数 | ストレージオーバーヘッド 


 a| 
4+2
 a| 
6
 a| 
7
 a| 
50%



 a| 
6+2
 a| 
8
 a| 
9
 a| 
33%



 a| 
8+2
 a| 
10
 a| 
11
 a| 
25%



 a| 
6+3
 a| 
9
 a| 
10
 a| 
50%



 a| 
9+3
 a| 
12
 a| 
13
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
4
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
6
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
8
 a| 
17%



 a| 
7+5
 a| 
12
 a| 
13
 a| 
71%

|===