---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: クラウド ストレージ プールを使用すると、ILM を使用してオブジェクト データをStorageGRIDシステム外部に移動できます。たとえば、あまりアクセスされないオブジェクトを、Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud、または Microsoft Azure Blob ストレージのアーカイブ アクセス層などの低コストのクラウド ストレージに移動することが考えられます。または、災害復旧を強化するために、 StorageGRIDオブジェクトのクラウド バックアップを維持することもできます。 
---
= クラウド ストレージ プールとは何ですか?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウド ストレージ プールを使用すると、ILM を使用してオブジェクト データをStorageGRIDシステム外部に移動できます。たとえば、あまりアクセスされないオブジェクトを、Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud、または Microsoft Azure Blob ストレージのアーカイブ アクセス層などの低コストのクラウド ストレージに移動することが考えられます。または、災害復旧を強化するために、 StorageGRIDオブジェクトのクラウド バックアップを維持することもできます。

ILM の観点から見ると、クラウド ストレージ プールはストレージ プールに似ています。どちらかの場所にオブジェクトを保存するには、ILM ルールの配置指示を作成するときにプールを選択します。ただし、ストレージ プールはStorageGRIDシステム内のストレージ ノードで構成されますが、クラウド ストレージ プールは外部バケット (S3) またはコンテナー (Azure Blob ストレージ) で構成されます。

この表は、ストレージ プールとクラウド ストレージ プールを比較し、大まかな類似点と相違点を示しています。

[cols="1a,2a,5a"]
|===
|  | ストレージ プール | クラウド ストレージ プール 


 a| 
どのように作成されるのですか?
 a| 
Grid Manager の *ILM* > *ストレージ プール* オプションを使用します。
 a| 
Grid Manager の *ILM* > *ストレージ プール* > *クラウド ストレージ プール* オプションを使用します。

Cloud Storage Pool を作成する前に、外部バケットまたはコンテナを設定する必要があります。



 a| 
いくつのプールを作成できますか?
 a| 
無制限。
 a| 
最大10個。



 a| 
オブジェクトはどこに保存されますか?
 a| 
StorageGRID内の 1 つ以上のストレージ ノード上。
 a| 
StorageGRIDシステムの外部にある Amazon S3 バケット、Azure Blob ストレージ コンテナ、または Google Cloud 内。

クラウド ストレージ プールが Amazon S3 バケットの場合:

* オプションでバケットライフサイクルを設定して、オブジェクトを Amazon S3 Glacier や S3 Glacier Deep Archive などの低コストの長期ストレージに移行することもできます。外部ストレージ システムは、Glacier ストレージ クラスと S3 RestoreObject API をサポートしている必要があります。
* AWS シークレットリージョンをサポートする AWS Commercial Cloud Services (C2S) で使用するためのクラウドストレージプールを作成できます。


クラウド ストレージ プールが Azure Blob ストレージ コンテナーの場合、 StorageGRID はオブジェクトをアーカイブ層に移行します。

*注:* 一般に、クラウド ストレージ プールに使用されるコンテナーに対して Azure Blob ストレージ ライフサイクル管理を構成しないでください。  Cloud Storage Pool 内のオブジェクトに対する RestoreObject 操作は、構成されたライフサイクルの影響を受ける可能性があります。



 a| 
オブジェクトの配置を制御するものは何ですか?
 a| 
アクティブな ILM ポリシー内の ILM ルール。
 a| 
アクティブな ILM ポリシー内の ILM ルール。



 a| 
どのようなデータ保護方法が使用されていますか?
 a| 
レプリケーションまたは消去コーディング。
 a| 
レプリケーション。



 a| 
各オブジェクトのコピーはいくつまで許可されますか?
 a| 
複数。
 a| 
クラウド ストレージ プールに 1 つのコピーがあり、オプションでStorageGRIDに 1 つ以上のコピーがあります。

*注:* 一度に複数のクラウド ストレージ プールにオブジェクトを保存することはできません。



 a| 
利点は何ですか?
 a| 
オブジェクトにはいつでもすぐにアクセスできます。
 a| 
低コストのストレージ。

*注意*: FabricPoolデータは、クラウド ストレージ プールに階層化できません。

|===