---
permalink: ilm/when-to-use-cloud-storage-pools.html 
sidebar: sidebar 
keywords: use cloud storage pool, benefits of cloud storage pools 
summary: Cloud Storage Pools を使用すると、データを外部の場所にバックアップしたり階層化したりできます。さらに、複数のクラウドにデータをバックアップしたり階層化したりすることもできます。 
---
= クラウドストレージプールを使用する場合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cloud Storage Pools を使用すると、データを外部の場所にバックアップしたり階層化したりできます。さらに、複数のクラウドにデータをバックアップしたり階層化したりすることもできます。



== StorageGRIDデータを外部の場所にバックアップする

Cloud Storage Pool を使用して、 StorageGRIDオブジェクトを外部の場所にバックアップできます。

StorageGRID内のコピーにアクセスできない場合は、クラウド ストレージ プール内のオブジェクト データを使用してクライアント要求に対応できます。ただし、クラウド ストレージ プール内のバックアップ オブジェクトのコピーにアクセスするには、S3 RestoreObject リクエストを発行する必要がある場合があります。

クラウド ストレージ プール内のオブジェクト データは、ストレージ ボリュームまたはストレージ ノードの障害によってStorageGRIDから失われたデータを回復するためにも使用できます。オブジェクトの唯一のコピーがクラウド ストレージ プール内にある場合、 StorageGRID はオブジェクトを一時的に復元し、回復したストレージ ノードに新しいコピーを作成します。

バックアップ ソリューションを実装するには:

. 単一のクラウド ストレージ プールを作成します。
. ストレージ ノード上のオブジェクト コピー (複製されたコピーまたは消去コード化されたコピーとして) とクラウド ストレージ プール内の単一のオブジェクト コピーを同時に保存する ILM ルールを構成します。
. ルールを ILM ポリシーに追加します。次に、ポリシーをシミュレートしてアクティブ化します。




== StorageGRIDから外部の場所への階層化データ

Cloud Storage Pool を使用して、 StorageGRIDシステムの外部にオブジェクトを保存できます。たとえば、保持する必要があるオブジェクトが多数あるが、それらのオブジェクトにアクセスする機会はほとんどない、あるいはまったくないとします。  Cloud Storage Pool を使用すると、オブジェクトを低コストのストレージに階層化し、 StorageGRIDのスペースを解放できます。

階層化ソリューションを実装するには:

. 単一のクラウド ストレージ プールを作成します。
. あまり使用されないオブジェクトをストレージ ノードからクラウド ストレージ プールに移動する ILM ルールを構成します。
. ルールを ILM ポリシーに追加します。次に、ポリシーをシミュレートしてアクティブ化します。




== 複数のクラウドエンドポイントを維持する

オブジェクト データを複数のクラウドに階層化またはバックアップする場合は、複数の Cloud Storage Pool エンドポイントを構成できます。 ILM ルールのフィルターを使用すると、各クラウド ストレージ プールに保存されるオブジェクトを指定できます。たとえば、一部のテナントまたはバケットのオブジェクトを Amazon S3 Glacier に保存し、他のテナントまたはバケットのオブジェクトを Azure Blob ストレージに保存したい場合があります。あるいは、Amazon S3 Glacier と Azure Blob ストレージ間でデータを移動する必要がある場合もあります。


NOTE: 複数の Cloud Storage Pool エンドポイントを使用する場合、オブジェクトは一度に 1 つの Cloud Storage Pool にのみ保存できることに注意してください。

複数のクラウド エンドポイントを実装するには:

. 最大 10 個のクラウド ストレージ プールを作成します。
. 適切なオブジェクト データを適切なタイミングで各クラウド ストレージ プールに保存するように ILM ルールを構成します。たとえば、バケット A のオブジェクトを Cloud Storage プール A に保存し、バケット B のオブジェクトを Cloud Storage プール B に保存します。または、オブジェクトを Cloud Storage プール A に一定期間保存してから、Cloud Storage プール B に移動します。
. ILM ポリシーにルールを追加します。次に、ポリシーをシミュレートしてアクティブ化します。

