---
permalink: fabricpool/configure-ontap.html 
sidebar: sidebar 
keywords: fabricPool, system manager, ONTAP CLI, add cloud tier 
summary: 必要なStorageGRID情報を取得したら、 ONTAPに移動してStorageGRID をクラウド層として追加できます。 
---
= ONTAP System Managerを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必要なStorageGRID情報を取得したら、 ONTAPに移動してStorageGRID をクラウド層として追加できます。

.開始する前に
* FabricPoolセットアップウィザードを完了した場合は、 `ONTAP_FabricPool_settings___bucketname__.txt`ダウンロードしたファイル。
* StorageGRID を手動で設定した場合は、 StorageGRIDに使用している完全修飾ドメイン名 (FQDN) またはStorageGRID HA グループの仮想 IP (VIP) アドレス、ロード バランサ エンドポイントのポート番号、ロード バランサ証明書、テナント アカウントのルート ユーザーのアクセス キー ID と秘密キー、およびそのテナントでONTAP が使用するバケットの名前がわかります。




== ONTAPシステムマネージャにアクセスする

これらの手順では、 ONTAP System Manager を使用してStorageGRID をクラウド層として追加する方法について説明します。 ONTAP CLI を使用して同じ設定を完了できます。手順については、 https://docs.netapp.com/us-en/ontap/fabricpool/index.html["FabricPoolのONTAPドキュメント"^] 。

.手順
. StorageGRIDに階層化するONTAPクラスターの System Manager にアクセスします。
. クラスターの管理者としてSign in。
. *ストレージ* > *階層* > *クラウド階層の追加* に移動します。
. オブジェクト ストア プロバイダーのリストから * StorageGRID* を選択します。




== StorageGRIDの値を入力してください

見る https://docs.netapp.com/us-en/ontap/fabricpool/index.html["FabricPoolのONTAPドキュメント"^]詳細についてはこちらをご覧ください。

.手順
. クラウド層の追加フォームに記入します。 `ONTAP_FabricPool_settings___bucketname__.txt`ファイルまたは手動で取得した値。
+
[cols="1a,3a"]
|===
| フィールド | 説明 


 a| 
Name
 a| 
このクラウド層の一意の名前を入力します。デフォルト値を受け入れることができます。



 a| 
URLスタイル
 a| 
もしあなたがlink:../admin/configuring-s3-api-endpoint-domain-names.html["設定されたS3エンドポイントドメイン名"]で、*仮想ホストスタイルの URL* を選択します。

*パス スタイルの URL* はONTAPのデフォルトですが、 StorageGRIDでは仮想ホスト スタイルのリクエストを使用することをお勧めします。  *サーバー名 (FQDN)* フィールドにドメイン名ではなく IP アドレスを指定する場合、*パス形式の URL* を使用する必要があります。



 a| 
サーバー名（FQDN）
 a| 
StorageGRIDに使用している完全修飾ドメイン名 (FQDN) またはStorageGRID HA グループの仮想 IP (VIP) アドレスを入力します。例：  `s3.storagegrid.__company__.com` 。

次の点に注意してください。

** ここで指定する IP アドレスまたはドメイン名は、 StorageGRIDロード バランサ エンドポイント用にアップロードまたは生成した証明書と一致する必要があります。
** ドメイン名を指定する場合、DNS レコードはStorageGRIDへの接続に使用する各 IP アドレスにマッピングする必要があります。見るlink:configure-dns-server.html["DNSサーバーを構成する"] 。




 a| 
SSL
 a| 
有効（デフォルト）。



 a| 
オブジェクト ストアの証明書
 a| 
次の内容を含む、 StorageGRIDロード バランサ エンドポイントに使用している証明書 PEM を貼り付けます。
`-----BEGIN CERTIFICATE-----`そして `-----END CERTIFICATE-----`。

*注:* 中間 CA がStorageGRID証明書を発行した場合は、中間 CA 証明書を提供する必要があります。  StorageGRID証明書がルート CA によって直接発行された場合は、ルート CA 証明書を提供する必要があります。



 a| 
ポート
 a| 
StorageGRIDロード バランサ エンドポイントで使用されるポートを入力します。 ONTAP は、 StorageGRIDに接続するときにこのポートを使用します。たとえば、10433。



 a| 
アクセスキーとシークレットキー
 a| 
StorageGRIDテナント アカウントのルート ユーザーのアクセス キー ID とシークレット アクセス キーを入力します。

*ヒント*: 将来StorageGRIDで新しいアクセス キーとシークレット アクセス キーを生成する場合は、 StorageGRIDから古い値を削除する前に、新しいキーをONTAPに入力します。そうしないと、 ONTAP は一時的にStorageGRIDへのアクセスを失う可能性があります。



 a| 
コンテナ名
 a| 
このONTAP層で使用するために作成したStorageGRIDバケットの名前を入力します。

|===
. ONTAPで最終的なFabricPool構成を完了します。
+
.. 1 つ以上のアグリゲートをクラウド層に接続します。
.. 必要に応じて、ボリューム階層化ポリシーを作成します。



