---
permalink: fabricpool/creating-load-balancer-endpoint-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, load balancer, endpoint, load balancing, create, creating, certificate 
summary: StorageGRID はロード バランサを使用して、 FabricPoolなどのクライアント アプリケーションからのワークロードを管理します。負荷分散により、複数のストレージ ノード間の速度と接続容量が最大化されます。 
---
= FabricPoolのロードバランサエンドポイントを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID はロード バランサを使用して、 FabricPoolなどのクライアント アプリケーションからのワークロードを管理します。負荷分散により、複数のストレージ ノード間の速度と接続容量が最大化されます。

FabricPoolで使用するためにStorageGRID を構成する場合は、ロード バランサ エンドポイントを構成し、 ONTAPとStorageGRID間の接続を保護するために使用されるロード バランサ エンドポイント証明書をアップロードまたは生成する必要があります。

FabricPoolセットアップウィザードを使用してこのタスクを完了するには、link:use-fabricpool-setup-wizard-steps.html["FabricPoolセットアップ ウィザードにアクセスして完了します"] 。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["ルートアクセス権限"]。
* 一般的なlink:../admin/managing-load-balancing.html["負荷分散に関する考慮事項"]だけでなくlink:best-practices-for-load-balancing.html["FabricPoolの負荷分散に関するベストプラクティス"]。


.手順
. *構成* > *ネットワーク* > *ロード バランサー エンドポイント* を選択します。
. *作成*を選択します。
. *エンドポイントの詳細を入力* ステップで、次のフィールドに入力します。
+
[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
Name
 a| 
エンドポイントの説明的な名前。



 a| 
ポート
 a| 
負荷分散に使用するStorageGRIDポート。このフィールドは、最初に作成するエンドポイントに対してデフォルトで 10433 に設定されますが、未使用の外部ポートを入力できます。 80 または 443 を入力すると、エンドポイントはゲートウェイ ノードでのみ構成されます。これらのポートは管理ノードで予約されています。

*注意:* 他のグリッド サービスで使用されるポートは許可されません。参照link:../network/internal-grid-node-communications.html["ネットワークポートリファレンス"]。

StorageGRID をFabricPoolクラウド層として接続するときに、この番号をONTAPに提供します。



 a| 
クライアントタイプ
 a| 
*S3*を選択します。



 a| 
ネットワークプロトコル
 a| 
「HTTPS」を選択します。

*注*: TLS 暗号化なしでのStorageGRIDとの通信はサポートされていますが、推奨されません。

|===
. *バインディング モードの選択* ステップで、バインディング モードを指定します。バインディング モードは、任意の IP アドレスまたは特定の IP アドレスとネットワーク インターフェイスを使用してエンドポイントにアクセスする方法を制御します。
+
[cols="1a,3a"]
|===
| モード | 説明 


 a| 
グローバル（デフォルト）
 a| 
クライアントは、任意のゲートウェイ ノードまたは管理ノードの IP アドレス、任意のネットワーク上の任意の HA グループの仮想 IP (VIP) アドレス、または対応する FQDN を使用してエンドポイントにアクセスできます。

このエンドポイントのアクセシビリティを制限する必要がない限り、*グローバル*設定 (デフォルト) を使用します。



 a| 
HAグループの仮想IP
 a| 
クライアントはこのエンドポイントにアクセスするために、HA グループの仮想 IP アドレス (または対応する FQDN) を使用する必要があります。

このバインディング モードのエンドポイントは、エンドポイントに選択した HA グループが重複していない限り、すべて同じポート番号を使用できます。



 a| 
ノードインターフェース
 a| 
クライアントは、このエンドポイントにアクセスするために、選択したノード インターフェイスの IP アドレス (または対応する FQDN) を使用する必要があります。



 a| 
ノード タイプ
 a| 
選択したノードのタイプに基づいて、クライアントは、このエンドポイントにアクセスするために、任意の管理ノードの IP アドレス (または対応する FQDN) または任意のゲートウェイ ノードの IP アドレス (または対応する FQDN) を使用する必要があります。

|===
. *テナント アクセス* ステップでは、次のいずれかを選択します。
+
[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
すべてのテナントを許可する（デフォルト）
 a| 
すべてのテナント アカウントは、このエンドポイントを使用してバケットにアクセスできます。

FabricPoolに使用されるロード バランサ エンドポイントの場合、ほとんどの場合、*すべてのテナントを許可する* が適切なオプションになります。

テナント アカウントをまだ作成していない場合は、このオプションを選択する必要があります。



 a| 
選択したテナントを許可する
 a| 
選択されたテナント アカウントのみがこのエンドポイントを使用してバケットにアクセスできます。



 a| 
選択したテナントをブロック
 a| 
選択されたテナント アカウントは、このエンドポイントを使用してバケットにアクセスできません。他のすべてのテナントはこのエンドポイントを使用できます。

|===
. *証明書の添付*ステップでは、次のいずれかを選択します。
+
[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
証明書をアップロードする（推奨）
 a| 
このオプションを使用して、CA 署名付きサーバー証明書、証明書の秘密キー、およびオプションの CA バンドルをアップロードします。



 a| 
証明書を生成する
 a| 
このオプションを使用して、自己署名証明書を生成します。見るlink:../admin/configuring-load-balancer-endpoints.html["ロードバランサのエンドポイントを構成する"]入力内容の詳細については、こちらをご覧ください。



 a| 
StorageGRID S3証明書を使用する
 a| 
このオプションは、 StorageGRIDグローバル証明書のカスタム バージョンをすでにアップロードまたは生成している場合にのみ使用できます。見るlink:../admin/configuring-custom-server-certificate-for-storage-node.html["S3 API証明書を設定する"]詳細については。

|===
. *作成*を選択します。



NOTE: エンドポイント証明書の変更がすべてのノードに適用されるまでに最大 15 分かかる場合があります。
