---
permalink: fabricpool/creating-tenant-account-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, tenant, SSO 
summary: FabricPool を使用するには、Grid Manager でテナント アカウントを作成する必要があります。 
---
= FabricPoolのテナントアカウントを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool を使用するには、Grid Manager でテナント アカウントを作成する必要があります。

テナント アカウントにより、クライアント アプリケーションはStorageGRID上でオブジェクトを保存および取得できるようになります。各テナント アカウントには、独自のアカウント ID、承認されたグループとユーザー、バケット、オブジェクトがあります。

このタスクの詳細については、link:../admin/creating-tenant-account.html["テナントアカウントを作成する"] 。  FabricPoolセットアップウィザードを使用してこのタスクを完了するには、link:use-fabricpool-setup-wizard-steps.html["FabricPoolセットアップ ウィザードにアクセスして完了します"] 。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたが持っているlink:../admin/admin-group-permissions.html["特定のアクセス権限"]。


.手順
. *TENANTS*を選択します。
. *作成*を選択します。
. 詳細入力の手順では、次の情報を入力します。
+
[cols="1a,3a"]
|===
| フィールド | 説明 


 a| 
Name
 a| 
テナント アカウントの名前。テナント名は一意である必要はありません。テナント アカウントが作成されると、一意の数値アカウント ID が割り当てられます。



 a| 
説明（オプション）
 a| 
テナントを識別するのに役立つ説明。



 a| 
クライアントタイプ
 a| 
FabricPoolの場合は *S3* である必要があります。



 a| 
ストレージクォータ（オプション）
 a| 
FabricPoolの場合はこのフィールドを空白のままにします。

|===
. 権限の選択手順:
+
.. *プラットフォーム サービスを許可する* を選択しないでください。
+
FabricPoolテナントは通常、CloudMirror レプリケーションなどのプラットフォーム サービスを使用する必要はありません。

.. 必要に応じて、「*独自の ID ソースを使用する*」を選択します。
.. *S3 Select を許可する*を選択しないでください。
+
FabricPoolテナントは通常、S3 Select を使用する必要はありません。

.. オプションで、*グリッドフェデレーション接続を使用する*を選択して、テナントがlink:../admin/grid-federation-overview.html["グリッドフェデレーション接続"]アカウントのクローンとクロスグリッドレプリケーション用。次に、使用するグリッド フェデレーション接続を選択します。


. ルートアクセスの定義ステップでは、 StorageGRIDシステムがテナントアカウントの初期ルートアクセス権限を持つユーザーを指定します。link:../admin/using-identity-federation.html["アイデンティティフェデレーション"] 、link:../admin/configuring-sso.html["シングルサインオン（SSO）"] 、またはその両方。
+
[cols="1a,2a"]
|===
| オプション | これをする 


 a| 
アイデンティティ連携が有効になっていない場合
 a| 
ローカル ルート ユーザーとしてテナントにサインインするときに使用するパスワードを指定します。



 a| 
アイデンティティ連携が有効になっている場合
 a| 
.. テナントのルート アクセス権限を付与する既存のフェデレーション グループを選択します。
.. 必要に応じて、ローカル ルート ユーザーとしてテナントにサインインするときに使用するパスワードを指定します。




 a| 
ID連携とシングルサインオン（SSO）の両方が有効になっている場合
 a| 
テナントのルート アクセス権限を付与する既存のフェデレーション グループを選択します。ローカル ユーザーはサインインできません。

|===
. *テナントの作成*を選択します。

