---
permalink: fabricpool/creating-s3-bucket-and-access-key.html 
sidebar: sidebar 
keywords: fabricPool, S3 bucket, bucket, access key, secret access key 
summary: StorageGRID をFabricPoolワークロードで使用する前に、 FabricPoolデータ用の S3 バケットを作成する必要があります。また、 FabricPoolに使用するテナント アカウントのアクセス キーとシークレット アクセス キーを取得する必要があります。 
---
= S3バケットを作成し、アクセスキーを取得する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID をFabricPoolワークロードで使用する前に、 FabricPoolデータ用の S3 バケットを作成する必要があります。また、 FabricPoolに使用するテナント アカウントのアクセス キーとシークレット アクセス キーを取得する必要があります。

このタスクの詳細については、link:../tenant/creating-s3-bucket.html["S3バケットを作成する"]そしてlink:../tenant/creating-your-own-s3-access-keys.html["独自のS3アクセスキーを作成する"]。  FabricPoolセットアップウィザードを使用してこのタスクを完了するには、link:use-fabricpool-setup-wizard-steps.html["FabricPoolセットアップ ウィザードにアクセスして完了します"] 。

.開始する前に
* FabricPoolで使用するためのテナント アカウントを作成しました。
* テナント アカウントへのルート アクセス権があります。


.手順
. テナント マネージャーにSign in。
+
次のいずれかを実行できます。

+
** グリッド マネージャーのテナント アカウント ページで、テナントの *Sign in* リンクを選択し、資格情報を入力します。
** Web ブラウザにテナント アカウントの URL を入力し、資格情報を入力します。


. FabricPoolデータ用の S3 バケットを作成します。
+
使用する予定のONTAPクラスタごとに一意のバケットを作成する必要があります。

+
.. ダッシュボードから*バケットの表示*を選択するか、*ストレージ (S3)* > *バケット*を選択します。
.. *バケットを作成*を選択します。
.. FabricPoolで使用するStorageGRIDバケットの名前を入力します。例：  `fabricpool-bucket` 。
+

TIP: バケットを作成した後は、バケット名を変更することはできません。

.. このバケットのリージョンを選択します。
+
デフォルトでは、すべてのバケットは `us-east-1`地域。

.. *続行*を選択します。
.. *バケットを作成*を選択します。
+

NOTE: FabricPoolバケットに対して *オブジェクトのバージョン管理を有効にする* を選択しないでください。同様に、 FabricPoolバケットを編集して *Available* またはデフォルト以外の一貫性を使用しないでください。  FabricPoolバケットに推奨されるバケット一貫性は *Read-after-new-write* であり、これは新しいバケットのデフォルトの一貫性です。



. アクセス キーとシークレット アクセス キーを作成します。
+
.. *ストレージ (S3)* > *マイアクセスキー* を選択します。
.. *キーの作成*を選択します。
.. *アクセスキーの作成*を選択します。
.. アクセス キー ID とシークレット アクセス キーを安全な場所にコピーするか、*.csv をダウンロード* を選択して、アクセス キー ID とシークレット アクセス キーを含むスプレッドシート ファイルを保存します。
+
StorageGRID をFabricPoolクラウド層として設定するときに、これらの値をONTAPに入力します。

+

TIP: 将来StorageGRIDで新しいアクセス キーとシークレット アクセス キーを生成する場合は、 StorageGRIDから古い値を削除する前に、新しいキーをONTAPに入力します。そうしないと、 ONTAP は一時的にStorageGRIDへのアクセスを失う可能性があります。




