---
permalink: fabricpool/creating-traffic-classification-policy-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, traffic classification, traffic policy, QoS, quality of service 
summary: オプションで、 StorageGRIDトラフィック分類ポリシーを設計して、 FabricPoolワークロードのサービス品質を最適化できます。 
---
= FabricPoolのトラフィック分類ポリシーを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オプションで、 StorageGRIDトラフィック分類ポリシーを設計して、 FabricPoolワークロードのサービス品質を最適化できます。

このタスクの詳細については、link:../admin/managing-traffic-classification-policies.html["トラフィック分類ポリシーを管理する"] 。  FabricPoolセットアップウィザードを使用してこのタスクを完了するには、link:use-fabricpool-setup-wizard-steps.html["FabricPoolセットアップ ウィザードにアクセスして完了します"] 。

.開始する前に
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["ルートアクセス権限"]。


.タスク概要
FabricPoolのトラフィック分類ポリシーを作成するためのベスト プラクティスは、次のようにワークロードによって異なります。

* FabricPoolプライマリ ワークロード データをStorageGRIDに階層化することを計画している場合は、 FabricPoolワークロードが帯域幅の大部分を占めるようにする必要があります。トラフィック分類ポリシーを作成して、他のすべてのワークロードを制限できます。
+

NOTE: 一般的に、 FabricPool の読み取り操作は書き込み操作よりも優先されることが重要です。

+
たとえば、他の S3 クライアントがこのStorageGRIDシステムを使用する場合は、トラフィック分類ポリシーを作成する必要があります。他のバケット、テナント、IP サブネット、またはロードバランサ エンドポイントのネットワーク トラフィックを制限できます。

* 一般的に、 FabricPoolワークロードにサービス品質の制限を課すべきではなく、他のワークロードのみを制限する必要があります。
* 他のワークロードに課される制限は、それらのワークロードの動作を考慮する必要があります。課される制限は、グリッドのサイズと機能、および予想される利用量によっても異なります。


.手順
. *構成* > *ネットワーク* > *トラフィック分類*を選択します。
. *作成*を選択します。
. ポリシーの名前と説明（オプション）を入力し、「続行」を選択します。
. 「一致するルールの追加」ステップでは、少なくとも 1 つのルールを追加します。
+
.. *ルールを追加*を選択
.. タイプには、*ロード バランサ エンドポイント* を選択し、 FabricPool用に作成したロード バランサ エンドポイントを選択します。
+
FabricPoolテナント アカウントまたはバケットを選択することもできます。

.. このトラフィック ポリシーで他のエンドポイントのトラフィックを制限する場合は、*逆一致* を選択します。


. 必要に応じて、ルールに一致するネットワーク トラフィックを制御するための 1 つ以上の制限を追加します。
+

NOTE: StorageGRID は、制限を追加しない場合でもメトリックを収集するため、トラフィックの傾向を把握できます。

+
.. *制限を追加*を選択します。
.. 制限するトラフィックの種類と適用する制限を選択します。


. *続行*を選択します。
. トラフィック分類ポリシーを読んで確認します。 *前へ*ボタンを使用して戻って、必要に応じて変更を加えます。ポリシーに満足したら、[*保存して続行*] を選択します。


.終了後
link:../admin/viewing-network-traffic-metrics.html["ネットワークトラフィックのメトリックを表示する"]ポリシーが期待どおりのトラフィック制限を適用していることを確認します。
