---
permalink: fabricpool/creating-ha-group-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, active interface, backup interface 
summary: 'FabricPoolで使用するためにStorageGRIDを構成する場合、オプションで 1 つ以上の高可用性 (HA) グループを作成できます。  HA グループは、それぞれにStorageGRID Load Balancer サービスが含まれるノードの集合です。  HA グループには、ゲートウェイ ノード、管理ノード、またはその両方を含めることができます。' 
---
= FabricPoolの高可用性 (HA) グループを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPoolで使用するためにStorageGRIDを構成する場合、オプションで 1 つ以上の高可用性 (HA) グループを作成できます。  HA グループは、それぞれにStorageGRID Load Balancer サービスが含まれるノードの集合です。  HA グループには、ゲートウェイ ノード、管理ノード、またはその両方を含めることができます。

HA グループを使用すると、 FabricPoolデータ接続を利用可能な状態に保つことができます。  HA グループは、仮想 IP アドレス (VIP) を使用して、ロード バランサ サービスへの高可用性アクセスを提供します。  HA グループ内のアクティブ インターフェイスに障害が発生した場合、バックアップ インターフェイスはFabricPool操作にほとんど影響を与えずにワークロードを管理できます。

このタスクの詳細については、link:../admin/managing-high-availability-groups.html["高可用性グループの管理"] 。  FabricPoolセットアップウィザードを使用してこのタスクを完了するには、link:use-fabricpool-setup-wizard-steps.html["FabricPoolセットアップ ウィザードにアクセスして完了します"] 。

.開始する前に
* あなたは、link:best-practices-for-high-availability-groups.html["高可用性グループのベストプラクティス"] 。
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["ルートアクセス権限"]。
* VLAN を使用する予定の場合は、VLAN インターフェイスを作成しておきます。見るlink:../admin/configure-vlan-interfaces.html["VLANインターフェースを構成する"] 。


.手順
. *構成* > *ネットワーク* > *高可用性グループ*を選択します。
. *作成*を選択します。
. *詳細を入力*手順では、次のフィールドに入力します。
+
[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
HAグループ名
 a| 
この HA グループの一意の表示名。



 a| 
説明（オプション）
 a| 
この HA グループの説明。

|===
. *インターフェースの追加*手順では、この HA グループで使用するノード インターフェースを選択します。
+
列ヘッダーを使用して行を並べ替えるか、検索語を入力してインターフェイスをより速く見つけます。

+
1 つ以上のノードを選択できますが、各ノードに対して選択できるインターフェースは 1 つだけです。

. *インターフェースの優先順位付け*手順では、この HA グループのプライマリ インターフェースとバックアップ インターフェースを決定します。
+
行をドラッグして、「優先順位」列の値を変更します。

+
リストの最初のインターフェースはプライマリ インターフェースです。障害が発生しない限り、プライマリ インターフェイスはアクティブ インターフェイスになります。

+
HA グループに複数のインターフェイスが含まれており、アクティブ インターフェイスに障害が発生した場合、仮想 IP (VIP) アドレスは優先順位の最初のバックアップ インターフェイスに移動します。そのインターフェースに障害が発生した場合、VIP アドレスは次のバックアップ インターフェースに移動し、これが繰り返されます。障害が解決されると、VIP アドレスは利用可能な最高優先度のインターフェースに戻ります。

. *IP アドレスを入力* の手順では、次のフィールドに入力します。
+
[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
サブネットCIDR
 a| 
CIDR 表記の VIP サブネットのアドレス (IPv4 アドレスの後にスラッシュとサブネットの長さ (0 ～ 32) が続きます)。

ネットワーク アドレスにはホスト ビットを設定しないでください。例：  `192.16.0.0/22` 。



 a| 
ゲートウェイIPアドレス（オプション）
 a| 
オプション。 StorageGRID へのアクセスに使用されるONTAP IP アドレスがStorageGRID VIP アドレスと同じサブネット上にない場合は、 StorageGRID VIP ローカル ゲートウェイ IP アドレスを入力します。ローカル ゲートウェイ IP アドレスは VIP サブネット内にある必要があります。



 a| 
仮想IPアドレス
 a| 
HA グループ内のアクティブ インターフェイスに、少なくとも 1 個、最大 10 個の VIP アドレスを入力します。すべての VIP アドレスは VIP サブネット内にある必要があります。

少なくとも 1 つのアドレスは IPv4 である必要があります。必要に応じて、追加の IPv4 および IPv6 アドレスを指定できます。

|===
. *HA グループの作成* を選択し、*完了* を選択します。

