---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure coding, replication, cloud storage pool, glacier 
summary: この単純なポリシー例を、独自の ILM ルールとポリシーの開始点として使用できます。 
---
= FabricPoolデータ用のILMを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この単純なポリシー例を、独自の ILM ルールとポリシーの開始点として使用できます。

この例では、コロラド州デンバーの単一のデータセンターに 4 つのストレージ ノードを持つStorageGRIDシステムの ILM ルールと ILM ポリシーを設計していると想定しています。この例のFabricPoolデータは、 `fabricpool-bucket` 。


CAUTION: 次の ILM ルールとポリシーは例にすぎません。 ILM ルールを構成する方法は多数あります。新しいポリシーを有効にする前に、ポリシーをシミュレートして、コンテンツの損失を防ぐためにポリシーが意図したとおりに機能することを確認します。詳細については、link:../ilm/index.html["ILMでオブジェクトを管理する"] 。


CAUTION: データの損失を避けるため、 FabricPoolクラウド層データの有効期限が切れたり、データが削除されたりする ILM ルールを使用しないでください。  FabricPoolオブジェクトがStorageGRID ILM によって削除されないようにするには、保持期間を *永久* に設定します。

.開始する前に
* あなたは、link:best-practices-ilm.html["FabricPoolデータで ILM を使用するためのベスト プラクティス"] 。
* グリッドマネージャにサインインするには、link:../admin/web-browser-requirements.html["サポートされているウェブブラウザ"] 。
* あなたはlink:../admin/admin-group-permissions.html["ILMまたはルートアクセス権限"]。
* 以前のStorageGRIDバージョンからStorageGRID 11.9 にアップグレードした場合は、使用するストレージ プールが構成されています。一般的に、データの保存に使用するStorageGRIDサイトごとにストレージ プールを作成する必要があります。
+

NOTE: 最初にStorageGRID 11.7 または 11.8 をインストールした場合、この前提条件は適用されません。これらのいずれかのバージョンを最初にインストールすると、サイトごとにストレージ プールが自動的に作成されます。



.手順
. 以下のデータにのみ適用されるILMルールを作成します。 `fabricpool-bucket`このサンプルルールは、消去コード化されたコピーを作成します。
+
[cols="1a,2a"]
|===
| ルールの定義 | 値の例 


 a| 
ルール名
 a| 
FabricPoolデータの 2 + 1 消去符号化



 a| 
バケット名
 a| 
`fabricpool-bucket`

FabricPoolテナント アカウントでフィルターすることもできます。



 a| 
高度なフィルター
 a| 
オブジェクト サイズが 0.2 MB を超えています。

*注:* FabricPool は4 MB のオブジェクトのみを書き込みますが、このルールは消去コーディングを使用するため、オブジェクト サイズ フィルターを追加する必要があります。



 a| 
基準時間
 a| 
取り込み時間



 a| 
期間と配置
 a| 
0日目から永遠に保存

デンバーで 2+1 EC スキームを使用して消去コーディングによってオブジェクトを保存し、それらのオブジェクトをStorageGRIDに永久に保持します。


CAUTION: データの損失を避けるため、 FabricPoolクラウド層データの有効期限が切れたり、データが削除されたりする ILM ルールを使用しないでください。



 a| 
摂取行動
 a| 
バランスの取れた

|===
. 最初のルールに一致しないオブジェクトの複製コピーを 2 つ作成するデフォルトの ILM ルールを作成します。基本フィルター (テナント アカウントまたはバケット名) や高度なフィルターは選択しないでください。
+
[cols="1a,2a"]
|===
| ルールの定義 | 値の例 


 a| 
ルール名
 a| 
2つの複製コピー



 a| 
バケット名
 a| 
_なし_



 a| 
高度なフィルター
 a| 
_なし_



 a| 
基準時間
 a| 
取り込み時間



 a| 
期間と配置
 a| 
0日目から永遠に保存

デンバーに 2 つのコピーを複製してオブジェクトを保存します。



 a| 
摂取行動
 a| 
バランスの取れた

|===
. ILM ポリシーを作成し、2 つのルールを選択します。レプリケーション ルールはフィルターを使用しないため、ポリシーのデフォルト (最後の) ルールにすることができます。
. テスト オブジェクトをグリッドに取り込みます。
. テスト オブジェクトを使用してポリシーをシミュレートし、動作を確認します。
. ポリシーをアクティブ化する。


このポリシーを有効にすると、 StorageGRID はオブジェクト データを次のように配置します。

* FabricPoolから階層化されたデータは `fabricpool-bucket`2+1 消失訂正符号化方式を使用して消失訂正符号化されます。  2 つのデータ フラグメントと 1 つのパリティ フラグメントが 3 つの異なるストレージ ノードに配置されます。
* 他のすべてのバケット内のすべてのオブジェクトが複製されます。  2 つのコピーが作成され、2 つの異なるストレージ ノードに配置されます。
* コピーはStorageGRIDに永久に保存されます。  StorageGRID ILM はこれらのオブジェクトを削除しません。

